### ISSUE TITLE
确认 PowerShell 版本时报错 `'powershell' 不是内部或外部命令...`

### ISSUE THREAD

**Issue by jianqingchen** [neolee/pilot#10]
电脑版本Windows7， 64位操作系统
确认 PowerShell 版本
PowerShell 是 Windows 下的增强命令行环境，也是我们以后要用的主要命令行界面。以下操作继续在上面打开的命令行界面进行：

在命令行界面输入 powershell ↩︎，注意到命令行界面的行首提示信息出现了 PS 字样；
在命令行界面输入 $PSVersionTable.PSVersion.Major ↩︎。

在执行以上操作时报错：
C:\Users\Administrator>powershell
'powershell' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
C:\Users\Administrator>$PSVersionTable.PSVersion.Major
'$PSVersionTable.PSVersion.Major' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
请问：这是什么原因啊？应该如何解决呢？

**Comment by neolee** [comment]
说明你的系统里没有 PowerShell，你应该是比较老的 Windows 吧？

我建议最好用 Windows 10，如果一定想在老系统上试试，可以尝试按照环境配置指引里的说明，先安装 .NET Framework 4.5（或更高）和 Windows Management Framework 5.1，然后再继续。
