### ISSUE TITLE
看学习用书时出现一个弹窗

### ISSUE THREAD

**Issue by hailinsu** [neolee/pilot#1001]
刚开始我点蓝色的标记，它消失了。不一会又出现了，我点颜色的。可是总这样反反复复的；于是我重新登录学习用书，发现还是这样，

![image](https://user-images.githubusercontent.com/48571418/73413658-579f0600-4347-11ea-93b6-41673a7bb1a2.png)

**Comment by neolee** [comment]
你执行 `jupyter lab` 命令的那个命令行窗口里有什么信息？
