### ISSUE TITLE
Jupyter Lab 里为何 list 显示格式有时是竖向有时是横向，能否都为横向？

### ISSUE THREAD

**Issue by arieljin2006** [neolee/pilot#1002]
![截图1](https://user-images.githubusercontent.com/59655550/73420283-f8e48700-435c-11ea-86d0-1e4111e4b7ee.jpg)
![截图2](https://user-images.githubusercontent.com/59655550/73420284-f8e48700-435c-11ea-829a-70b5a759fc62.jpg)

```
list(range(2, 100, 8))
[2, 10, 18, 26, 34, 42, 50, 58, 66, 74, 82, 90, 98]

list(range(2, 100, 2))
[2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
```

**Comment by neolee** [comment]
嗯，这个说起来挺搞笑的，这是 Jupyter Notebook 的一个叫做 “pretty print” 功能，但是很多人和你一样，觉得多行打印不好看（当然，也有很多人觉得好看）。不过好在我们可以很容易地关掉这个功能，你可以打开一个新的 code cell，输入并执行下面的 "magic command"：

```
%pprint
```

这会关掉 “pretty print” 功能，然后就能得到你想要的效果了。再执行一次可以再打开。
