### ISSUE TITLE
MySQL 使用 cursor.executemany 报语法错误

### ISSUE THREAD

**Issue by xushengjun** [neolee/pilot#1003]
李老师好！
执行以下代码出现语法错误
```
cursor = conn.cursor(buffered=True)
sql2 = 'INSERT INTO users (username, firstname, lastname) VALUES (%s, %s, %s)'
cursor.execute(sql2)
values = [
    ('trinity', 'Carrie-Anne', 'Moss'),
    ('morpheus', 'Laurence', 'Fishburne'),
    ('smith', 'Hugo', 'Weaving')
]
cursor.executemany(sql2,values)
conn.commit()
conn.close
```
错误如下
```
Traceback (most recent call last):
  File "/Users/xushengjun/Code/com/xsj/demo/mysql-demo01.py", line 24, in <module>
    cursor.execute(sql2)
  File "/usr/local/lib/python3.7/site-packages/mysql/connector/cursor_cext.py", line 266, in execute
    raw_as_string=self._raw_as_string)
  File "/usr/local/lib/python3.7/site-packages/mysql/connector/connection_cext.py", line 492, in cmd_query
    sqlstate=exc.sqlstate)
mysql.connector.errors.ProgrammingError: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '%s, %s, %s)' at line 1
```
请问下是什么原因？

**Comment by neolee** [comment]
你前面创建 conn 和 cursor 的完整代码是啥样的？

**Comment by xushengjun** [comment]
> 你前面创建 conn 和 cursor 的完整代码是啥样的？

如下：
`import mysql.connector as mysql
import pandas as pd

conn = mysql.connect(
    host = 'localhost',
    user = 'learn',
    password = 'demo',
    database='demo'
)
cursor = conn.cursor(buffered=True)
sql2 = 'INSERT INTO users (username, firstname, lastname) VALUES (%s, %s, %s)'
cursor.execute(sql2)
values = [
    ('trinity', 'Carrie-Anne', 'Moss'),
    ('morpheus', 'Laurence', 'Fishburne'),
    ('smith', 'Hugo', 'Weaving')
]
cursor.executemany(sql2,values)
conn.commit()
conn.close
`

**Comment by neolee** [comment]
你运行出错的是 `cursor.execute(sql2)` 这一行，这一行是要出错的呀，因为你的 `sql2` 里面的那几个 `(%s, %s, %s)` 不是合法的 SQL，要通过 `executemany` 将其置换为 `values` 里面的值。

**Comment by xushengjun** [comment]
解决了，谢谢李老师！
