### ISSUE TITLE
Jupyter Lab 网页打开无学习用书

### ISSUE THREAD

**Issue by wangcyber** [neolee/pilot#1005]
已经看过《进入编程世界的第一课 - 学习环境准备》视频。我的操作和老师操作一致。
jupyter lab网页呈现空白页。尝试关闭防火墙，尝试scoop install nodejs安装成功。未能解决求帮助。
问题截图：
1~powershell 代码截图。2~jupyter lab网页截图。3~\pilot-student> ls截图。均正常。

**Comment by neolee** [comment]
如果打开的浏览器是老的 IE，会出现空白网页，因为 Jupyter Lab 不支持 IE。

你需要把系统浏览器换成 IE 10（Edge）或者 Chrome 或者 Firefox 之类的。

**Comment by wangcyber** [comment]
浏览器换成 Chrome 问题已经解决
