### ISSUE TITLE
为什么我 git commit，立即会出现画红线的这句话，然后提交不成功

### ISSUE THREAD

**Issue by lisengrong** [neolee/pilot#1006]
![image](https://user-images.githubusercontent.com/58058613/73515713-3e728400-4431-11ea-8e41-8b476a0a70df.png)
我git commit时，能打开VSC，但在命令行总是同时显示：aborting commit due to empty commit message.然后提交不成功，于是用老师issues回答的拆中办法：git commit -m’提交说明信息’的方法来绕过去，成功了。但是我检查后，没有发现错误，能不能不用绕过去的这种方法那？

**Comment by neolee** [comment]
你执行 `git config -l` 的输出是怎样的？
