### ISSUE TITLE
函数运行无 return 的问题

### ISSUE THREAD

**Issue by zhangSen1987** [neolee/pilot#1007]
李老师，敲了一个质数判定函数，体验函数别名。运行的时候，敲了几个数字，发现输入23 没有反馈结果，这是什么情况，第一次遇到这个问题。
![函数无返回值么](https://user-images.githubusercontent.com/53714512/73517944-f73bc180-4437-11ea-9090-9fc17fd7504e.jpg)

**Comment by zhangSen1987** [comment]
运行了好几次，都是这个情况，这段代码用VScode运行 输入23 还是没有return

**Comment by neolee** [comment]
因为某种条件下你的函数就是没有返回的，事实上还是挺大比例的情况。你试着仔细分析你的代码，把 23 带进去一步步模拟程序的运行看看。还可以看看讲 VS Code 的支线课，然后试试单步调试下你的代码，验证你用自己大脑模拟的运行过程。

**Comment by onefacebig** [comment]
去掉else应该就可以了。

**Comment by xiaoerhai** [comment]
我按李骏老师说的去做了，虽然还没有成功操作单步调试，但该issue应该是代码缩进的问题。如下图就能正常返回：
![image](https://user-images.githubusercontent.com/48662601/73621069-95659c80-466f-11ea-89b7-30f4144a4904.png)

**Comment by PATIEN** [comment]
@xiaoerhai你的代码可以再检查一下，其实输入任何奇数，都会输出True。
正确的做法就是如@onefacebig 所说，去掉else
