### ISSUE TITLE
几天前别人动了电脑改了点什么导致现在教材里的东西不能用了，问题如图 如何修改正常

### ISSUE THREAD

**Issue by Yukiwly** [neolee/pilot#1009]
![image](https://user-images.githubusercontent.com/48648174/73587189-bbfec880-44f3-11ea-8a1b-1b176ab83a5f.png)

**Comment by neolee** [comment]
你说的“教材里的东西不能用了”具体是指什么？

你贴出的图是 VS Code 的一个 warning，说环境变量 PATH 中有可能带来麻烦的特殊字符，你可以检查下 PATH 设置（在系统设置里有）。
