### ISSUE TITLE
运行 Jupyter Lab 浏览器显示空白

### ISSUE THREAD

**Issue by 18p2p** [neolee/pilot#101]

**Comment by neolee** [comment]
提供运行 jupyter lab 的命令行窗口，以及打开的浏览器窗口的截图。

**Comment by 18p2p** [comment]
正在研究上图按钮在哪里？

**Comment by neolee** [comment]
把截图拖到输入框，等那个 Uploading 的提示变成 <img src=...> 的一串之后，提交。

**Comment by 18p2p** [comment]
![4](https://user-images.githubusercontent.com/48624321/67582652-bcf9be80-f77c-11e9-999d-1b182db36924.png)
![3](https://user-images.githubusercontent.com/48624321/67582662-c08d4580-f77c-11e9-850b-42409f021a59.png)

**Comment by 18p2p** [comment]
![1](https://user-images.githubusercontent.com/48624321/67582810-fd593c80-f77c-11e9-93ee-8ab5775a722b.jpg)

**Comment by neolee** [comment]
命令行这里没有出错信息，应该没啥问题，那么很可能是你的浏览器太久，你把命令行窗口里 http://localhost 打头的那个完整的网址 copy 出来，贴到你正在用的那个新的浏览器的地址栏，应该可以用。

**Comment by 18p2p** [comment]
方法有效，谢谢老师！

**Comment by zhenrany** [comment]
我也出现这个问题，google浏览器就是打不开，地址粘贴到 360浏览器可以用，但是怎么修改jupyter lab 打开的浏览器？

**Comment by zhenrany** [comment]
我运行的过程是这样的：
运行jupyter lab:
![image](https://user-images.githubusercontent.com/55627503/68638922-fdf42000-053d-11ea-8594-4c01cd9e50de.png)
闪过短暂的提示2秒，如下：
![image](https://user-images.githubusercontent.com/55627503/68638967-182dfe00-053e-11ea-8964-356fd2de4fba.png)
跳转如下空白界面：
![image](https://user-images.githubusercontent.com/55627503/68638972-1e23df00-053e-11ea-9c5f-1cb8ea983e8a.png)

现在360浏览器可以用，但不知道怎么切换到360浏览器，或者怎么设置 谷歌浏览器 才可以正常使用

**Comment by neolee** [comment]
@zhenrany 如果你的 Chrome 是原版比较新的版本，不会有这个问题。
