### ISSUE TITLE
关于p1-2中练习输入typt(f)后显示类型是bool的疑问

### ISSUE THREAD

**Issue by golddeng** [neolee/pilot#1011]
在p1-2的练习中输入type(f)后显示类型是bool，和type(t)显示结果一样
```python
a = 12
b = 30
f = 3.14
s = 'abracadabra'
l = [1, 2, 3]
t = True
f = False
```
<img width="455" alt="捕获" src="https://user-images.githubusercontent.com/48916401/73593339-14f34e80-453e-11ea-9a62-eb215c774772.PNG">
但f = 3.14,我觉得type类型应该是float
<img width="309" alt="捕获1" src="https://user-images.githubusercontent.com/48916401/73593493-0dcd4000-4540-11ea-8b76-515828e39d95.PNG">
是哪里输错了么,或者是系统配置问题。

**Comment by onefacebig** [comment]
f赋值了两次，最后一次是False。

**Comment by golddeng** [comment]
> f赋值了两次，最后一次是False。

谢谢，我明白哪里错了
