### ISSUE TITLE
编程环境设置不成功

### ISSUE THREAD

**Issue by joy999999** [neolee/pilot#1013]
显示访问被拒绝
![屏幕快照 2020-02-02 上午10 27 58](https://user-images.githubusercontent.com/53077496/73601997-badaa380-45a6-11ea-9c2c-b6d9759fe46a.png)

**Comment by Longmen328** [comment]
换个网络试试，用手机做热点联网试试就行了

**Comment by joy999999** [comment]
用手机热点联网后还是不成功
![Uploading 屏幕快照 2020-02-02  #下午1.54.20.png…]()

**Comment by hong66666** [comment]
建议你在网上找下如何科学上网
先解决网络问题
再安装配置环境
网络问题如果不解决，后面的安装和学习都会很麻烦
