### ISSUE TITLE
关于p2-8-list中 List comprehension 的一个例子的疑问

### ISSUE THREAD

**Issue by Liujiale02** [neolee/pilot#1016]
首先, 祝老师新年快乐. 

在list那一章节中,有一个List comprehension的例子: 
lowercased_good = [name.lower() if name != 'Smith' else name.upper() for name in names]
print(lowercased_good)
输出结果: ['neo', 'trinity', 'morpheus', 'SMITH']

对于这个结果,有点不明白. 如果执行的是if name != 'Smith' ,  那么之后输出的结果应该是['neo', 'trinity', 'morpheus'] 吧,
怎么还会执行后面else部分的代码?(因为有'SMITH')
不应该是执行 if 或者 else 其中一个的吗?
我对输出结果中有 'SMITH' 表示看不懂.
麻烦老师解答一下,我的愚见. 谢谢

**Comment by hpy729** [comment]
这句的意思是：

if它不是'Smith'，则lower；否则（即它是‘Simth’的话），就upper。

**Comment by neolee** [comment]
Python 中的下面这个语法是个表达式：

```python
X if cond else Y
```

这个表达式的值，如果条件 `cond` 为真则为 X，否则就为 Y。仔细读一下上面的语法就能理解（和记住）。

**Comment by Liujiale02** [comment]
哦我明白了,我将后面的for...in语句 误以为是嵌套在else里面的.谢谢老师和同学的指点.
