### ISSUE TITLE
print_tree 折线如何输入

### ISSUE THREAD

**Issue by 18p2p** [neolee/pilot#1017]
![7I521CL~X{2R7QYEBKQF8)3](https://user-images.githubusercontent.com/48624321/73627308-154b3100-4687-11ea-8a31-29fa6ef09fc0.png)
(tier-1) 和 tier+1 理解困难;
len(root.children) 如何理解

**Comment by neolee** [comment]
1. 第一版本，也就是用空格来缩进各层节点的版本，能看懂吗？那几个版本是一个个逐层递进的，理解第一个是关键。

2. `len(root.children)` 这个不能理解吗？想想 `root.children` 是个什么东西，然后复习一下几个数据容器。

3. 那些折线，其实用 `+--` `|` 等标准 ASCII 字符完全 OK；如果要更好看，就要用 Unicode 中的一些画线字符，可以在这里找到： https://en.wikipedia.org/wiki/Box-drawing_character
