### ISSUE TITLE
为什么 for 循环后可以跟 else 语句而 while 循环后不能？

### ISSUE THREAD

**Issue by xiaozhunaoke** [neolee/pilot#1021]
![image](https://user-images.githubusercontent.com/60306096/73660563-6123c780-46d3-11ea-843e-2814c3056cf8.png)

![image](https://user-images.githubusercontent.com/60306096/73660579-6b45c600-46d3-11ea-896c-d9356bd84313.png)

**Comment by neolee** [comment]
`while` 也可以有 `else` 子句，你的代码出错是因为前面一行 `i = i + 1` 缩进错误，Python 解释器会认为 `while` 这个 block 已经在它上面结束了，于是就不认识后面的 `else` 了。

不过我个人的观点是，无论 `for` 还是 `while` 的 `else` 子句都不是太好的东西，虽然在很少数情形下有用（主要是为了区分循环正常结束和被 `break` 中止两种情况），但通常都有更清晰和简明的写法，大多数时候使用这个语法都是逻辑上没找到最简明的表达而已。
