### ISSUE TITLE
关于树的层级

### ISSUE THREAD

**Issue by xiaoerhai** [neolee/pilot#1022]
疑问：计算机是怎么知道各个`node`的`tier`的？一开始我们只在这棵树的类里创建了2个方法（``__init__()``和``add_child()``），并没有创建层级相关的方法。
![image](https://user-images.githubusercontent.com/48662601/73709411-f5c21000-473b-11ea-982c-506be42f8c40.png)

**Comment by neolee** [comment]
根节点层级是0，它的孩子们就是1，孩子的孩子就是2，依此类推。

**Comment by xiaoerhai** [comment]
盯着代码看了许久，好像搞懂了，就是递归的作用。感谢李骏老师。
