### ISSUE TITLE
教材内容被删除或者被修改后如何恢复？

### ISSUE THREAD

**Issue by hong66666** [neolee/pilot#1023]
李老师，您好；我在学习过程中，不注意，把教材中的第八节的部分内容删除了，请问该如何恢复？

<img width="501" alt="718755e91ed2f4f4a92a8a4e3e12159" src="https://user-images.githubusercontent.com/53136135/73735294-02655900-477a-11ea-8bbb-f8c13b9cbe3b.png">

<img width="854" alt="a2e2d52b1877ed123d965de2301e659" src="https://user-images.githubusercontent.com/53136135/73735509-53754d00-477a-11ea-8df3-94a3bc7b53c5.png">

**Comment by hong66666** [comment]
经过与李骏老师沟通，
1、老师给我的方法是利用git 恢复我要恢复的那个文件（即被我自己修改的那个教材文件 p1-8-oo-2.ipynb），git checkout--p1-8-oo-2.ipynb
我执行此文件后，得出的结果如下：

<img width="433" alt="72cd70edd809075323e69f13ec6820c" src="https://user-images.githubusercontent.com/53136135/73735776-c1ba0f80-477a-11ea-8af9-b94813752fc1.png">

2、之后我发现居然在Visual Studio Code执行学习用书jupyter lab的窗口左边有个Source Control（下图左边已标记），我选择了我要恢复的文件 p1-8-oo-2.ipynb，就发现了两个版本的文件，一个是原始的文件里红色部分就是我自己手误删除的部分，（下图中间已标记），我直接复制这部分，再回到Visual Studio Code，我的教材目录里，找到这页教材（即我要恢复的文件），把上图的红色部分，粘贴在教材文件中，千万别忘了Ctrl+S保存，然后再回到p1-8-oo-2.ipynb（Working Tree）的页面，看看两个文件有没有不同，如果有不同，还会有红色部分出现，如果没有，可以重新打开jupyter lab，在网页上再重新看看教材页面是否已经恢复

**Comment by neolee** [comment]
那个命令 `--` 和文件名之间要空一格。

**Comment by hong66666** [comment]
> 那个命令 -- 和文件名之间要空一格。

我好像又用了一种土办法。。。
也能恢复。
