### ISSUE TITLE
p1-9 中猫类定义中的 mew 方法是否有不同调用方法的疑惑

### ISSUE THREAD

**Issue by HwangJea** [neolee/pilot#1024]
老师好：
为什么使用mew(c)来调用mew这个方法会报错，
而我尝试把mew方法的缩进取消之后又正确了呢？

![20200204171446921](https://user-images.githubusercontent.com/59499058/73736329-8ff57880-477b-11ea-95b9-03bbac643436.jpg)
![360截图20200204182053247](https://user-images.githubusercontent.com/59499058/73736343-95eb5980-477b-11ea-87a2-ac286f22d1fb.jpg)

**Comment by neolee** [comment]
当函数定义包含在类定义里面时，它是对象的方法；否则它是个独立的函数。

对象的方法要用 `obj.xxx()` 来调用。

结合上面的两个解释，你可以再试试理解你看到的现象。
