### ISSUE TITLE
支线视频课程里的打字错误

### ISSUE THREAD

**Issue by hangmars** [neolee/pilot#1025]
P2 初步设计和责任分离
最后子类GreetingBot的代码中， if 'good' in **feeling**.lower():语句中变量feeling并未修改。
**但是在视频jupyter中为何可以运行？**（发现后来老师改了。。）
以下是代码：
class GreetingBot(Bot):
    def __init__(self):
        self.q = "How are you today?"

    def _think(self,s):
        if 'good' in feeling.lower():
            return("I'm feeling good too")
        else:
            return("Sorry to hear that")
g = GreetingBot()
g.run()

**Comment by neolee** [comment]
这个肯定是不对的，后面就改正了 😁
