### ISSUE TITLE
运行 jupter lab 时没有跳出学习用书

### ISSUE THREAD

**Issue by yusen7** [neolee/pilot#1026]
在运行jupter lab的时候，没有在本地上跳出学习用书。这是出了什么问题呢/

**Comment by neolee** [comment]
你是指没有弹出浏览器吗？这个可能有很多原因，一般是系统配置的问题，可以检查下你的系统缺省浏览器设置。

也可以手动打开你喜欢的浏览器，然后把你运行命令 `jupyter lab` 之后输出的提示中，`http://localhost...` 那一行地址拷贝到浏览器里打开，效果是一样的。
