### ISSUE TITLE
关于组合的问题

### ISSUE THREAD

**Issue by iceberg-yuan** [neolee/pilot#1027]
``` python
#  用组合的方法 计算圆环的 面积 
from math import pi

class Circle:
    def __init__(self,r):
        self.r = r

    def area(self,r):
        return pi * self.r**2

    def perimeter(self,r):
        return 2*pi*self.r

class Ring:
    def __init__(self,ourter_r,inner_r):
        ourter_r,inner_r = (ourter_r,inner_r) if ourter_r>inner_r else (inner_r,ourter_r)
        self.out_c = Circle(ourter_r)
        self.in_c = Circle(inner_r)
        
    def area(self):
        return self.out_c.area() - self.in_c.area()

a = Ring(10,8)
```
李老师，上面这段代码我在执行的时候提示传参不对，把 return self.out_c.area() - self.in_c.area()改为 return self.out_c.area(self) - self.in_c.area(self)就没问题了，但是没想明白，里边不是应该传个半径吗？请帮忙解答，谢谢。

**Comment by neolee** [comment]
这里有两个问题：

一，你的 `Circle` 类的 `area()` 方法里其实并不需要 `r` 这个参数，这个方法内也没用到这个参数，使用属性 `self.r` 是对的。这个问题改正后，`Ring` 类里的代码就没错了。

二，但上面这个问题的价值是引出了你遇到的问题。下面这段话可能会有点难懂，但尽量努力理解下：Python 是一种动态类型的语言，意思是，并不会严格检查某个参数的类型，只有用到这个值的时候才会知道该类型是不是会出错。

如果一个函数调用缺一个参数，那肯定不行，所以你贴出的代码会出错；当你改了代码之后，给 `Circle` 的 `area` 方法送了一个 `self` 参数进去，由于 Python 并不会严格检查这个参数的类型，所以就接受了，然后在`Circle` 的 `area` 方法里又没用到这个参数，所以也没有发现它其实不是正确的类型！听上去很搞笑是不是？但实际情况就是这么回事。

动态类型带来很多方便之处，但代价是，程序编写者自己要保证传递参数的类型没问题。

**Comment by iceberg-yuan** [comment]
谢谢李老师，明白了。

**Comment by Zhang-Jinlei** [comment]
好玩。

我这里加一个可以预先规避掉这种情况的方法：

![Snip20200206_1](https://user-images.githubusercontent.com/28210665/73906514-14600c80-48de-11ea-9da9-8b9e0855f576.png)

（使用有语法高亮的 ID，可以预先发现这个问题。我用的是PyCharm）

**Comment by neolee** [comment]
@Zhang-Jinlei 没明白，是什么意思呀？这俩函数都不需要 r 这个参数吧？

**Comment by Zhang-Jinlei** [comment]
老师，
我的意思是在写代码的时候可以提前发现不需要的函数参数。具体到我这个来说，当我用 PyCharm 时，用到的参数会相对亮一些，如函数 area 中的 参数 r。而没有用到的函数参数，如函数 perimeter 中的参数 r 会相对暗一些。
这样就可以删掉没有用到的参数，也就不会产生上面的问题了。这是我昨天将上面的代码复制到 PyCharm  凑巧想到的，顺便就在这里分享一下。

**Comment by neolee** [comment]
@Zhang-Jinlei 明白了！PyCharm 收费，我没用过，我瞅瞅别的编辑器有没有这个设计 😃

**Comment by Zhang-Jinlei** [comment]
@neolee 老师，我用的是社区版的，感觉对新手来讲基本够用，对大家来讲也比较方便。

若以后有需求的话，再升级到专业版也挺好。

**Comment by hpy729** [comment]
听人说，高手用pycharm，新手用vs code，有没有这种说法啊？

**Comment by neolee** [comment]
@hpy729 说这话的一定是新手。

**Comment by hpy729** [comment]
@neolee 哈哈哈，同意
