### ISSUE TITLE
MySQL Workbench 连接本地运行的服务出错

### ISSUE THREAD

**Issue by hope1324** [neolee/pilot#1028]
李骏老师你好，我学会用jupyterlab了，这回用jupyterlab看的书。x5章节用MySQL Workbench连接本地运行的服务出错：
![Screenshot_20200205_095852](https://user-images.githubusercontent.com/33803562/73804562-23bc5880-47ff-11ea-8269-eb902ae8e2ad.png)
请问如何解决?

**Comment by hope1324** [comment]
系统kubuntu18.04 x86-64

**Comment by neolee** [comment]
没见过这个出错信息。你在命令行执行 `mysql` 会怎样？你的 MySQL 的 root 密码改过吗？

**Comment by hope1324** [comment]
![Screenshot_20200205_161254](https://user-images.githubusercontent.com/33803562/73823055-6f3c2a00-4832-11ea-8f6b-3cfb6bc7ab15.png)
![Screenshot_20200205_161431](https://user-images.githubusercontent.com/33803562/73823138-9eeb3200-4832-11ea-8549-3509b7869a10.png)
MySQL 的 root 密码改过。

**Comment by neolee** [comment]
Google 了下，找到这个问题：

https://bbs.archlinux.org/viewtopic.php?id=244193

似乎你需要先安装 `gnome-keyring` 这个包。

很久没用过 KDE 了，难怪没见过这个错儿……

**Comment by hope1324** [comment]
已解决，谢谢老师。
