### ISSUE TITLE
安装 Homebrew 的时候一直卡在了这一步

### ISSUE THREAD

**Issue by leeyeep** [neolee/pilot#103]
Press RETURN to continue or any other key to abort
==> Downloading and installing Homebrew...
HEAD is now at 06ed951f5 Merge pull request #6642 from reitermarkus/pkg-before-app

**Comment by neolee** [comment]
应该是网络问题，尝试换网络或者代理，或者使用国内镜像安装，有其他同学的成功例子。

**Comment by wangbingfeng** [comment]
这个要耐心等待，等安装成功，会提示successful
