### ISSUE TITLE
P1-b-final 中《增量式优化》出现报错提示的问题

### ISSUE THREAD

**Issue by shengdaomoluo** [neolee/pilot#1032]
在用第一种方法对对话颜色进行优化中，出现报错，如图：
![P1-b-final（1）](https://user-images.githubusercontent.com/24812990/73823955-487ef300-4834-11ea-9e21-6f4a408a9d80.png)
![P1-b-final(2)](https://user-images.githubusercontent.com/24812990/73823964-4ae14d00-4834-11ea-8b33-ab59e7f56067.png)
请问这是什么原因造成的，如何解决？

**Comment by neolee** [comment]
你没有安装 termcolor 这个第三方包，你需要先 `pip install termcolor`。
