### ISSUE TITLE
为什么用在vscode中，用return显示不出返回值，而用print可以打印出返回值？

### ISSUE THREAD

**Issue by xiaozhunaoke** [neolee/pilot#1033]
![image](https://user-images.githubusercontent.com/60306096/73833824-8fc1af80-4845-11ea-946c-781d01ea2ee4.png)

![image](https://user-images.githubusercontent.com/60306096/73833523-11fda400-4845-11ea-8f2e-33740094e053.png)

**Comment by neolee** [comment]
这个问题被问过很多次，课上我也讲过好多次。
