### ISSUE TITLE
parse_str() 函数返回 name ‘Flase’ is not defined

### ISSUE THREAD

**Issue by zhipingyang120** [neolee/pilot#1034]
```python
s3="440abc312"
s4="3.1415g26"

def is_float(s):
    try:
        float(s)
        return True
    except ValueError:
        return Flase

def is_int(s):
    try:
        int(s)
        return True
    except ValueError:
        return False
    
def parse_str(s):
    if is_int(s):
        print (f"输入是整数，其值为{int(s)}。")
    elif is_float(s):
        print (f"输入是浮点数，其值为{float(s)}。")
    else:
        print (f"输入“{s}”不是数值类型。")
```

![Snap 2020-02-05 at 20 01 27](https://user-images.githubusercontent.com/55620481/73840710-b1299800-4853-11ea-8aaa-bb9f2ddc847b.png)

李老师，我的计算机为什么出现这个答案？不是很理解？
#893 我已经查看了，但不是我想要的答案。

**Comment by neolee** [comment]
`NameError: name 'Flase' is not defined`

这句话是什么意思呢？`Flase` 又是什么呢？

**Comment by zhipingyang120** [comment]
这句话的意思是没有定义‘Flase’名称。
```Flase```是is_float(s)和is_int(s)两个函数的返回值吗？

**Comment by neolee** [comment]
你写的两个函数，`is_float()` 和 `is_int()`，一个返回是 `True` 或者 `False`，另一个返回是 `True` 或者 `Flase`，这是怎么回事呢？

你是从头开始学习，听了课的么？`True` `False` 分别是啥知道吧？

**Comment by zhipingyang120** [comment]
李老师，我是照抄教材上的代码，运行出上述结果。我得出的结果和教材中得出的结果不一样，所以才有疑问。
之前的都学习了，我来把关于这部分教材的课听一下吧。

**Comment by zhipingyang120** [comment]
我明白了，不好意思，李老师，我才看出来，是我写错了。

**Comment by zhipingyang120** [comment]
flase  和 false   拼写错误啊！之前也犯过这样的错误！
