### ISSUE TITLE
运行了 jupyterlab 打开学习用书输入代码不会 print 结果

### ISSUE THREAD

**Issue by yunnanlinhong** [neolee/pilot#1035]
在conemu上运行了jupyterlab，打开学习用书输入代码，不会print结果，怎么解？

李老师，我的软件按要求都已经装过了，但是输入代码不会出结果，在conemu上调用Python可以运行，求解

![微信图片_3](https://user-images.githubusercontent.com/32616598/73864193-3032c680-487c-11ea-89d8-c506b00df385.png)
![Uploading 微信图片1.png…]()

**Comment by yunnanlinhong** [comment]
![微信图片1 jpg](https://user-images.githubusercontent.com/32616598/73865498-4ccffe00-487e-11ea-9264-2002892bd8ae.png)

**Comment by neolee** [comment]
你有在代码 cell 里按 Shift+Enter 或者 Alt+Enter 了吗？

**Comment by yunnanlinhong** [comment]
哦哦，可以了，谢谢（我刚刚点页面上的前进键也会出来，谢谢）
老师早点休息哈
