### ISSUE TITLE
MySQL Workbench 在 win10-x86-64bit 中无法启动

### ISSUE THREAD

**Issue by hope1324** [neolee/pilot#1036]
李骏老师你好。我在windows中也配置了环境，因为笔记本中只安装了windows，有时只会使用笔记本，台式机回到家里才能用。昨天在win10-64位中文版上安装并配置了mysql后，然后又下载安装了mysql-workbench-community-8.0.19-winx64.msi，双击启动不了。自己在网上搜索了一气，解决不了。请问怎么解决？

**Comment by neolee** [comment]
提问之前可以先搜索下，已有类似问题： #996

**Comment by hope1324** [comment]
看了链接的帖子，换了8.0.18版解决。谢谢老师，我下回搜索。
