### ISSUE TITLE
安装 scoop 提示 iwr:基础连接已关闭

### ISSUE THREAD

**Issue by xiao-sky** [neolee/pilot#1038]
PS C:\Users\lenovo> Get-ExecutionPolicy
RemoteSigned
PS C:\Users\lenovo>
PS C:\Users\lenovo> iwr -useb get.scoop.sh | iex
iwr : 基础连接已经关闭: 发送时发生错误。
所在位置 行:1 字符: 1
+ iwr -useb get.scoop.sh | iex
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [I
   nvoke-WebRequest]，WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.Inv
   okeWebRequestCommand

**Comment by neolee** [comment]
网络问题。有很多一样的 issue 了。

**Comment by xiao-sky** [comment]
问题解决了，谢谢！
