### ISSUE TITLE
配置环境时遇到难题，如何解决

### ISSUE THREAD

**Issue by Mason999** [neolee/pilot#1039]
配置环境时，遇到两个问题：
1.在comemu中输入code. 后切换不到VScode；
2.在comemu中打不开学生用书的浏览器。

**Comment by zorahong57** [comment]
1. 输入`Code .`（中间有一个空格），才能切换VScode。
2. 看一下目录是否正确，按照指南操作应该是 `C:\Users\Administrator\Code\pilot-student>`， 然后输入`jupyter lab` 等它运行就可以了。

**Comment by neolee** [comment]
@Mason999 同学，这些不能叫难题，哪怕是刚开始学习，这也不能叫难题啊！另外你所提供的信息太少了，其实是没法确切的回答的，其他同学和我只能靠猜。比如“切换不到 VSCode”是啥意思，“打不开学生用书”又是什么意思？是浏览器没出现，还是浏览器出现了但是一片空白？输入这些命令后命令行界面出现了什么提示？如果这些都懒得写，别人为啥要费劲儿回答呢？

@zorahong57 说的都对，我补充两点：
1. 要用 Visual Studio Code 打开当前目录，命令是 `code .`，仔细看清楚，并**充分理解**这个命令的意思，不要输错。
2. 除了要留意你目前的工作目录是不是正确，还要注意 Jupyter Lab 不支持老版本的 IE，你需要使用其他浏览器（除了老 IE 基本都可以）。
