### ISSUE TITLE
安装好 Jupyter Lab 后运行 jupyter lab 代码显示无法找到

### ISSUE THREAD

**Issue by lidewen-yue** [neolee/pilot#104]
lidewendeMacBook-Air:~ k$ cd pilot-student
lidewendeMacBook-Air:pilot-student k$ jupyter lab
-bash: jupyter: command not found
lidewendeMacBook-Air:pilot-student k$

**Comment by neolee** [comment]
你的系统的路径有些乱，不过我估计下面的命令应该是可以的：

```shell
python3 -m jupyter lab
```

**Comment by lidewen-yue** [comment]
还是无法找到呢！
lidewendeMacBook-Air:~ k$ python3 -m jupyter lab
/usr/local/opt/python/bin/python3.7: No module named jupyter
lidewendeMacBook-Air:~ k$

**Comment by neolee** [comment]
那么你就没有成功安装 jupyterlab。

**Comment by zilin19** [comment]
李老师，我的问题同上，分别输入: 1. pip install jupyterlab. 2 . python3 -m jupyter lab 都显示：404 NOT Found。请问是不是系统路径太乱造成的。
powershell 中显示如下：                                                                                                                                                            
PS C:\Users\GAOZILIN> python3 -m jupyter lab                                                                                                                
[I 11:23:33.704 LabApp] JupyterLab beta preview extension loaded from D:\360Downloads\360\lib\site-packages\jupyterlab                                      
[I 11:23:33.704 LabApp] JupyterLab application directory is D:\360Downloads\360\share\jupyter\lab                                                           
[W 11:23:33.714 LabApp] Error loading server extension jupyterlab                                                                                           
    Traceback (most recent call last):                                                                                                                      
      File "D:\360Downloads\360\lib\site-packages\jupyterlab\commands.py", line 321, in __init__                                                            
        self._run(['node', 'node-version-check.js'], cwd=HERE, quiet=True)                                                                                  
      File "D:\360Downloads\360\lib\site-packages\jupyterlab\commands.py", line 1165, in _run                                                               
        proc = Process(cmd, **kwargs)                                                                                                                       
      File "D:\360Downloads\360\lib\site-packages\jupyterlab\process.py", line 73, in __init__                                                              
        self.proc = self._create_process(cwd=cwd, env=env)                                                                                                  
      File "D:\360Downloads\360\lib\site-packages\jupyterlab\process.py", line 131, in _create_process                                                      
        cmd[0] = which(cmd[0], kwargs.get('env'))                                                                                                           
      File "D:\360Downloads\360\lib\site-packages\jupyterlab\jlpmapp.py", line 59, in which                                                                 
        raise ValueError(msg)                                                                                                                               
    ValueError: Please install nodejs 5+ and npm before continuing installation. nodejs may be installed using conda or directly from the nodejs website.   
                                                                                                                                                            
    During handling of the above exception, another exception occurred:                                                                                     
                                                                                                                                                            
    Traceback (most recent call last):                                                                                                                      
      File "D:\360Downloads\360\lib\site-packages\notebook\notebookapp.py", line 1454, in init_server_extensions                                            
        func(self)                                                                                                                                          
      File "D:\360Downloads\360\lib\site-packages\jupyterlab\extension.py", line 111, in load_jupyter_server_extension                                      
        info = get_app_info(app_dir)                                                                                                                        
      File "D:\360Downloads\360\lib\site-packages\jupyterlab\commands.py", line 244, in get_app_info                                                        
        handler = _AppHandler(app_dir, logger)                                                                                                              
      File "D:\360Downloads\360\lib\site-packages\jupyterlab\commands.py", line 324, in __init__                                                            
        raise ValueError(msg)                                                                                                                               
    ValueError: Please install nodejs 5+ and npm before continuing installation. nodejs may be installed using conda or directly from the nodejs website.   
[I 11:23:34.375 LabApp] Serving notebooks from local directory: C:\Users\GAOZILIN                                                                           
[I 11:23:34.375 LabApp] 0 active kernels                                                                                                                    
[I 11:23:34.375 LabApp] The Jupyter Notebook is running at:                                                                                                 
[I 11:23:34.375 LabApp] http://localhost:8888/?token=e07b64da87df056d560deefd1b1f1a5ae09cca9585418fdb                                                       
[I 11:23:34.375 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).                                           
[C 11:23:34.375 LabApp]                                                                                                                                     
                                                                                                                                                            
    Copy/paste this URL into your browser when you connect for the first time,                                                                              
    to login with a token:                                                                                                                                  
        http://localhost:8888/?token=e07b64da87df056d560deefd1b1f1a5ae09cca9585418fdb                                                                       
[I 11:23:36.609 LabApp] Accepting one-time-token-authenticated connection from ::1                                                                          
[W 11:23:36.650 LabApp] 404 GET /lab?token=78b9b44cc54e902d125ab6e5ef951560fe61631f2c919f1a (::1) 40.89ms referer=None 

请问该如何解决这个问题。
盼回复

**Comment by neolee** [comment]
@zilin19 你的 jupyter 命令在一个奇怪的目录下，可以确定不是按照配置指南安装的。应该你以前装过 Python 和 Jupyter Lab。

需要清理干净再按指南操作。

**Comment by dfdssgb** [comment]
如何清理

**Comment by zilin19** [comment]
@dfdssgb 
可以手动卸载之前安装在你电脑上的python和Jupyter lab

**Comment by jarodlong** [comment]
> @zilin19 你的 jupyter 命令在一个奇怪的目录下，可以确定不是按照配置指南安装的。应该你以前装过 Python 和 Jupyter Lab。
> 
> 需要清理干净再按指南操作。

![image](https://user-images.githubusercontent.com/54735562/67644321-8d54dd00-f95b-11e9-8440-1e30b41c29ee.png)
![image](https://user-images.githubusercontent.com/54735562/67644326-9d6cbc80-f95b-11e9-899a-dca96cd4f000.png)
安装成功但是无法运行JUPYTER，我曾经安装过一次
![image](https://user-images.githubusercontent.com/54735562/67644442-621ebd80-f95c-11e9-893e-e069896be16b.png)
刚刚使用jupyter --vision 查询居然jupyter lab 没有安装！

**Comment by neolee** [comment]
你先前的 Python 和 Jupyter Lab 安装是不完整的，而且两个系统对于新手来说也会比较容易出问题，先清理环境，否则不好弄。
