### ISSUE TITLE
jupyter 代码无法运行

### ISSUE THREAD

**Issue by Lijk117** [neolee/pilot#1043]
![屏幕截图(462)](https://user-images.githubusercontent.com/48860837/74012825-1dc4a400-49c6-11ea-9dd8-1a643630775c.png)

老师您看，代码无法执行，只是显示【*】，试过挺多方法都没办法解决。

**Comment by Lijk117** [comment]
![屏幕截图(462)](https://user-images.githubusercontent.com/48860837/74013034-91ff4780-49c6-11ea-87d4-4c18246ed023.png)

**Comment by Lijk117** [comment]
代码显示：  raise NotImplementedError
NotImplementedError

我担心图片发出来看不到

**Comment by Lijk117** [comment]
同步把问题放到了知乎上，这里可以加载图片
https://www.zhihu.com/question/370284828

**Comment by neolee** [comment]
你为什么装了 Python 3.8.1？据我所知 Jupyter Lab 并不能很好地和 3.8 兼容。

严格按照我们的指南来配置环境，你应该运行 Python 3.7.4。

**Comment by Lijk117** [comment]
抱歉没注意到这个版本号，我又查了查，在我安装python这个文件夹下
> C:\Users\13207\scoop\apps\python\3.8.1\Lib\site-packages\tornado\platform
打开`asyncio` 文件，添加如下代码：
```
import sys

if sys.platform == 'win32':
    asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
```
就可以用了

**Comment by neolee** [comment]
这只是一种临时的 workaround，一旦这个包升级了还要手工维护。当然了，你愿意就好。
