### ISSUE TITLE
git commit 无法添加版本信息

### ISSUE THREAD

**Issue by lovemg11** [neolee/pilot#1044]
git commit 时候，VSCode自动打开，提示输入版本信息，同时控制台提示:Aborting commit due to empty commit message;
在文本编辑器输入版本信息后，保存、关闭编辑器，再次进行git commit ，仍提示:Aborting commit due to empty commit message；
但使用git commit -m “版本信息”的方式则可以成功commit，不知道是什么原因；

**Comment by neolee** [comment]
你的 `git config -l` 输出结果是啥样子？

**Comment by lovemg11** [comment]
![image](https://user-images.githubusercontent.com/48599312/74015414-8cf0c700-49cb-11ea-80b7-3f38c342f5d6.png)

**Comment by lovemg11** [comment]
![image](https://user-images.githubusercontent.com/48599312/74015579-dccf8e00-49cb-11ea-9f26-71203467d7d2.png)
@neolee

**Comment by lovemg11** [comment]
$ git config -l
core.symlinks=false
core.autocrlf=true
core.fscache=true
color.diff=auto
color.status=auto
color.branch=auto
color.interactive=true
help.format=html
rebase.autosquash=true
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
http.sslbackend=openssl
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
credential.helper=manager
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
user.name=Chen Hao
user.email=faith0322@126.com
core.editor=code
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
gui.wmstate=normal
gui.geometry=1640x853+196+196 360 389

**Comment by neolee** [comment]
`core.editor` 设置不对，应该是 `code -w`。
