### ISSUE TITLE
关于 for 循环体内边界的认识

### ISSUE THREAD

**Issue by xiaowei0189** [neolee/pilot#1045]
```
for n in range(2, 100):
    if n == 2:
        print(n)
        continue
    for i in range(2, n):
        if (n % i) == 0:
            break
    else:               
        print(n)
```
******************************************
```
for n in range(2, 100):
    if n == 2:
        print(n)
        continue
    for i in range(2, n):
        if (n % i) == 0:
            break
    print(n)  
```

对每次循环的边界如何判定比较模糊

例1中，当break条件满足时跳过了下面的else。例2中，break条件满足时却执行了最后一行的print()语句。循环体结束要怎么界定，在网上没有搜索到能理解的答案，希望老师同学帮忙解惑。

**Comment by neolee** [comment]
1. `break` 跳出的是当前的循环，不影响外层的循环。

2. `for` 的 `else` 子句仅在 `for` 循环正常结束后才会执行，在 `break` 结束循环的情况下会被忽略。在另外一个 issue 里我提过，我不太建议新人去使用循环的 `else` 子句，更好的办法是少用 `break`，尽力寻找一个更简明清晰的逻辑表达。
