### ISSUE TITLE
在 VS Code 中使用 Markdown 时 IE 界面显示无法连接

### ISSUE THREAD

**Issue by focusgrowth** [neolee/pilot#1046]
在 Visual Studio 中使用 Markdown 时，IE 界面显示 http://localhost:8090/ 无法连接

**Comment by neolee** [comment]
信息太少，无法判断。

**Comment by focusgrowth** [comment]
这个问题解决了，是网络问题，我发现很多问题都可以先等等，网络不稳定，早上5点使用电脑就没有这个问题
