### ISSUE TITLE
在练习的这个notebook里，程序没有反应；在新开的notebook里可以。是什么原因？

### ISSUE THREAD

**Issue by hermanxie** [neolee/pilot#1047]
![image](https://user-images.githubusercontent.com/48776732/74082216-bde7ff00-4a92-11ea-8693-029be6296121.png)
![image](https://user-images.githubusercontent.com/48776732/74082221-ccceb180-4a92-11ea-8132-ada1eccf875e.png)

**Comment by neolee** [comment]
可以看看支线课程里关于 Jupyter Lab 的那一课。

你前一张截图里应该是 notebook 背后的 Python 解释器（Jupyter 术语叫 kernel）挂了，需要 restart kernel 就可以了。如果这种情况反复出现，应该是 Python 环境有问题。

类似的问题这里也不少了，可以先搜索下。
