### ISSUE TITLE
编程环境配置出错 

### ISSUE THREAD

**Issue by sunyunhang1010** [neolee/pilot#1048]
==> Downloading and installing Homebrew...
remote: Enumerating objects: 131102, done.
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
Failed during: git fetch origin master:refs/remotes/origin/master --tags --force
sunyunhangdeMacBook-Pro:~ sunyunhang$

**Comment by neolee** [comment]
网络问题。
