### ISSUE TITLE
在獲取學習用書第二部遇到問題 按照步驟輸入卻一直出現No such file or directory

### ISSUE THREAD

**Issue by aprilsing** [neolee/pilot#1049]
Last login: Sat Feb  8 17:20:59 on ttys000
MacBook-Pro:~ aprillin$ mrdir Code
-bash: mrdir: command not found
MacBook-Pro:~ aprillin$ mkdir Code
mkdir: Code: File exists
MacBook-Pro:~ aprillin$ cd Code
MacBook-Pro:Code aprillin$ git clone
fatal: 您必須指定一個版本庫來複製。

用法：git clone [<選項>] [--] <版本庫> [<路徑>]

    -v, --verbose         更加詳細
    -q, --quiet           更加安靜
    --progress            強制顯示進度報告
    -n, --no-checkout     不建立一個簽出
    --bare                建立一個純版本庫
    --mirror              建立一個鏡像版本庫（也是純版本庫）
    -l, --local           從本機版本庫複製
    --no-hardlinks        不使用本機硬連結，始終複製
    -s, --shared          設定為共享版本庫
    --recursive ...       --recurse-submodules 的別名
    --recurse-submodules[=<路徑規格>]
                          在複製時初始化子模組
    -j, --jobs <n>        並發複製的子模組的數量
    --template <範本目錄>
                          範本目錄將被使用
    --reference <版本庫>  參考版本庫
    --reference-if-able <版本庫>
                          參考版本庫
    --dissociate          僅在複製時參考 --reference 指向的本機版本庫
    -o, --origin <名稱>   使用 <名稱> 而不是 'origin' 去追蹤上游
    -b, --branch <分支>   簽出 <分支> 而不是遠端 HEAD
    -u, --upload-pack <路徑>
                          遠端 git-upload-pack 路徑
    --depth <深度>        建立一個指定深度的淺複製
    --shallow-since <時間>
                          從一個特定時間建立一個淺複製
    --shallow-exclude <版本>
                          深化淺複製的歷史，除了特定版本
    --single-branch       只複製一個分支、HEAD 或 --branch
    --no-tags             不要複製任何標籤，並且後續取得動作也不下載它們
    --shallow-submodules  子模組將以淺下載模式複製
    --separate-git-dir <git目錄>
                          git目錄和工作區分離
    -c, --config <key=value>
                          在新版本庫中設定設定訊息
    --server-option <server-specific>
                          傳輸選項
    -4, --ipv4            只使用 IPv4 位址
    -6, --ipv6            只使用 IPv6 位址
    --filter <參數>       物件過濾
    --remote-submodules   任何複製的子模組將使用它們的遠端追蹤分支
    --sparse              初始化稀疏簽出檔案，只包含根目錄中的檔案

MacBook-Pro:Code aprillin$ https://github.com/aprilsing/pilot-student.git
-bash: https://github.com/aprilsing/pilot-student.git: No such file or directory
MacBook-Pro:Code aprillin$ cd pilot-student
-bash: cd: pilot-student: No such file or directory
MacBook-Pro:Code aprillin$ 

我已經重複輸入很多次，但都還是一直No such file or directory，請問我該如何解決這問題？

**Comment by neolee** [comment]
> 输入 git clone ，在最后有个空格，在空格后粘贴你前面拷贝的，你 fork 的 repo 的地址，然后输入回车

在学习用书指南中的这句话你是如何理解的？

**Comment by aprilsing** [comment]
原來git clone後面不用按回車，而是在貼上repo地址後才按！問題解決了！謝謝老師！
