### ISSUE TITLE
停止 jupyter lab 服务时出错

### ISSUE THREAD

**Issue by Yidong-Guo** [neolee/pilot#105]

**Comment by neolee** [comment]
So?

**Comment by Yidong-Guo** [comment]
^C[I 00:35:00.184 LabApp] 中断
启动notebooks 在本地路径: /Users/xingnan/Code/pilot-student
3 活跃的服务
本程序运行在: http://localhost:8888/?token=95a0fc317bb7296474715f2c87328bc9d749fb3765cd8581
 or http://127.0.0.1:8888/?token=95a0fc317bb7296474715f2c87328bc9d749fb3765cd8581
关闭服务 (y/[n])5s 未响应 重启操作...

**Comment by Yidong-Guo** [comment]
可以了。原来只关闭网页不行，需要点左上角停止服务。。。

**Comment by neolee** [comment]
关闭 Jupyter Lab 的方法是在运行 jupyter lab 命令的命令行窗口按 Control+C，然后提示时按 Y

**Comment by Yidong-Guo** [comment]
谢谢老师，我试试
