### ISSUE TITLE
VSCode 按钮 run code 运行报错无法识别

### ISSUE THREAD

**Issue by YanYeek** [neolee/pilot#1050]
![Snipaste_2020-02-08_20-22-02](https://user-images.githubusercontent.com/48875922/74085166-35c52200-4ab1-11ea-9ec0-01ee644cae82.png)

**Comment by neolee** [comment]
去看支线课程里关于 VS Code 的那一讲。

**Comment by YanYeek** [comment]
谢谢老师，我没在vscode支线视频和Google中找到答案，大概率是我另一台电脑系统问题，尽管我刚刚重置系统，我打算用settings-sync插件同步正常配置再试试，大不了那台电脑不用了。

**Comment by neolee** [comment]
你真的看明白支线课程了吗？只要你能在命令行运行 .py 文件，然后正确配置 VSCode 里的 Python Interpreter，就一定能使用那个运行按钮（虽然其实完全不需要用那个按钮）。

如果你在命令行运行 .py 文件就有问题，那就先解决和 VSCode 无关的这个问题。问题隔离之后通常会简单很多。
