### ISSUE TITLE
如何在 kbuntu 中配置 Redis 环境

### ISSUE THREAD

**Issue by hope1324** [neolee/pilot#1051]
李骏老师你好，请问如何在kbuntu 18.04 x86-64版本中配置Redis 环境？教材中没有，个人力量太小，小白搞不了。

**Comment by neolee** [comment]
哈？你一个用 Linux 的人搞不定这个有点说不过去啊，这不就是 apt install 的事儿吗？随便 Google 一下就有啊，比如：

https://www.digitalocean.com/community/tutorials/how-to-install-and-secure-redis-on-ubuntu-18-04

前两天我还在跟一个同学说千万别用自己“笨”“小白”来做借口，凡是课程里让大家尝试的都没什么难的，世界上也没有真的笨人；真想学会编程先把这个思想去掉。

最差情况是你找了试了很多，但出现问题，尝试解决有困难，那就可以具体问问。

**Comment by hope1324** [comment]
不好意思，我上午问完问题后自己又乱试，最后能用了。但还是不太明白。

**Comment by hope1324** [comment]
我虽然用linux，但是并不熟练，英语还是刚学的。

**Comment by neolee** [comment]
如果真的没有基础，身边也没人可以给你指点帮助的话，用 Linux 前面还有无数的坑，挑战会挺大的。

**Comment by hope1324** [comment]
我喜欢挑战，而且正在看鸟哥的linux私房菜，我是不会放弃的。
