### ISSUE TITLE
有关 CSV 数据文件的数据类型的小疑问

### ISSUE THREAD

**Issue by xiaoerhai** [neolee/pilot#1052]
如下图所示，数据类型`pandas.DataFrame`和`pandas.core.frame.DataFrame`是同一个意思吗？
![image](https://user-images.githubusercontent.com/48662601/74095079-7a3ed500-4b26-11ea-8695-17ef86e9e664.png)

**Comment by neolee** [comment]
这个类型是 pandas 装好数据给你操作用的对象，不是 “CVS 数据类型”，表达要严谨。

你看到的 `pandas.DataFrame` 和 `pandas.core.frame.DataFrame` 是因为 pandas 改了它的代码结构，所以和以前写的不一样了，我回头检查和更新下教材。

**Comment by xiaoerhai** [comment]
明白了，感谢李骏老师解答。
