### ISSUE TITLE
x4-regex 中文字校对问题

### ISSUE THREAD

**Issue by ZhaiGuangkai** [neolee/pilot#1053]
(?<=pattern)：look behind positive assert，这是检查匹配部分之前的字符，例如 (?<=95|98|NT|2000)Windows**Windows)** 能匹配 2000Windows 中的 Windows，但不能匹配 3.1Windows 中的 Windows；

以上文字位于 **控制标记** 段落上方第五行的位置，以上加粗为多余文字。

**Comment by Milkmocha** [comment]
请问老师，在学习用书中并没有包括这一章（我已经更新过学习用书了）。我怎么样才能把这一章加入到自己的学习用书中呢？就是如何把这一章保存成一个本地的notebook?

**Comment by neolee** [comment]
@ZhaiGuangkai 我检查了目前最新的版本，似乎没有你说的这个问题？有可能你看的是 GitHub 渲染的 notebook 中有问题。

@Milkmocha 如果需要可以直接下载主仓库的这个文件到本地：

https://raw.githubusercontent.com/neolee/pilot/master/x4-regex.ipynb
