### ISSUE TITLE
安装软件包管理工具 Scoop 失败

### ISSUE THREAD

**Issue by QQ326684857** [neolee/pilot#1054]
![70QR9D41C S)4HCL8OP9D(H](https://user-images.githubusercontent.com/39524795/74104272-09cb9e80-4b8e-11ea-8f74-f53fbef8ef86.png)

在输入 iwr -useb get.scoop.sh | iex 后报错

**Comment by neolee** [comment]
有不少类似的 issue 了，提问前可以先搜索下。

你这个问题是因为 PowerShell 的版本太低，你是 Windows 7 吧？课程的指南里明确写了只支持 Windows 10，并且要检查 PowerShell 的版本不低于 5 才可以。你有严格按照指南一步步操作吗？

**Comment by QQ326684857** [comment]
回看的时候才发现这个问题，确实是windows7

**Comment by 3216571985** [comment]
.....
