### ISSUE TITLE
git commit 无法进行的错误

### ISSUE THREAD

**Issue by hong66666** [neolee/pilot#1055]
之前执行了git config --global core.editor "code -w"

<img width="524" alt="d3332cc43e8e9464cf901610cc686cb" src="https://user-images.githubusercontent.com/53136135/74104661-dab72c00-4b91-11ea-91c0-fca7ce6f471f.png">

再执行git commit的时候就是这个情况，也没有文本编辑器跳出来

<img width="524" alt="52dbf8842d04fd643c0c8d1266b85d2" src="https://user-images.githubusercontent.com/53136135/74104666-e7d41b00-4b91-11ea-828e-928c59dd5961.png">

**Comment by neolee** [comment]
已有类似的 issue： #415  #483 

目前还不知道这个问题什么条件下会触发，我在 #415  中给了一个临时的 workaround。

p.s. 你好像经常提 issue 会出问题，出现完全空着的一个 issue，然后你就给关了不管了，不知道是遇到啥问题？你自己的 issue 你是可以不断修改的，也可以随时关闭和打开，即使误操作了也可以修正，不需要反复另开。
