### ISSUE TITLE
安装 Scoop 时候，打指令报错

### ISSUE THREAD

**Issue by lori1989** [neolee/pilot#1059]
![image](https://user-images.githubusercontent.com/60845641/74136952-f241f380-4c29-11ea-9207-9ca9284c27b6.png)

**Comment by lori1989** [comment]
刚看了，老师回答其他的类似问题，说是版本问题，我电脑是win7的，不是win10，那怎么解决啊？

**Comment by isparkyou-github** [comment]
安装win10
