### ISSUE TITLE
p1-9 的这些代码不理解

### ISSUE THREAD

**Issue by Gittplayer** [neolee/pilot#1060]

**Comment by Gittplayer** [comment]
> 李老师，这是p1-9 中的代码，有些不理解，如下：
> class Animal:
> 
> ```
> kind = ''
> 
> def __init__(self, name):
>     self.name = name
>     
> def voice(self):
>     return'...'
> ```
> 
> class Dog(Animal):
> 
> ```
> kind = 'canidae'
> 
> def voice(self):
>     return 'woof-woof'
> 
> bark = voice
> ```
> 
> class Cat(Animal):
> 
> ```
> kind = 'felidae'
> 
> def voice(self):
>     return 'meow-meow'
> 
> mew = voice
> ```
> 
> a = Animal('キュゥべえ')
> c = Cat('Garfield')
> d = Dog('Snoopy')
> 
> for animal in [a, c, d]:
> print(animal.name, ':', animal.voice())
> 我不理解的地方是最后这个for循环后打印出来的结果，不理解为什么是
> キュゥべえ : ...
> Garfield : meow-meow
> Snoopy : woof-woof
> 这3个结果，不明白代码怎么运行出这个结果的，另外，这个animal.name和animal.voice是属于什么变量类型呢？

**Comment by neolee** [comment]
去听下群里的课程，关于面向对象的应该是第四和第五课。前面的如果没听也要听听。
