### ISSUE TITLE
S2 课程练习：“树形数据结构”的实现

### ISSUE THREAD

**Issue by neolee** [neolee/pilot#1061]
请大家在此分享自己的作业成果，建议把代码写到 [GitHub Gist](https://gist.github.com/)，然后在这里贴出链接即可。

这样大家可以互相学习，互相挑毛病，一定会大有收获。

**Comment by jiangsv** [comment]
https://gist.github.com/fca0f1b89ed807ea24c3203cc5682cb5.git

完成了差不多了，还剩节点之间的path 和 distance。应该过两天能完成。
里面写些有疑问的地方，麻烦老师解答。

**Comment by xu-kai-xu** [comment]
https://gist.github.com/xu-kai-xu/557e7c55e7c0fdb0171122f10adaccbd

这是我做的，感觉自己不会用递归。所以有些看起来比较繁琐。还有，打印树结构的是从 issues 里面发现的，自己实在想不出来了。

**Comment by neolee** [comment]
> https://gist.github.com/xu-kai-xu/557e7c55e7c0fdb0171122f10adaccbd
> 
> 这是我做的，感觉自己不会用递归。所以有些看起来比较繁琐。还有，打印树结构的是从 issues 里面发现的，自己实在想不出来了。

哈哈，一开始模仿也是学习的一种途径，但别停在这里就好。
