### ISSUE TITLE
安装 homebrew 报错 curl: Failed to connect 

### ISSUE THREAD

**Issue by xuexu23** [neolee/pilot#1062]
安装homebrew的时候，在终端输入

/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

提示：
curl: (7) Failed to connect to raw.githubusercontent.com port 443: Connection refused

看提示应该是我的网络问题，但是我不知道怎么解决？

**Comment by lanlan816** [comment]
应该是没有先安装xcode这个工具包，我之前也这样报错。

**Comment by neolee** [comment]
是网络问题。

**Comment by xuexu23** [comment]
请教老师，这个问题怎么解决呢？

**Comment by neolee** [comment]
网络问题需要换网络、换时间或者换代理。
