### ISSUE TITLE
在 p1-2 的学习用书中输入 type(f) 后显示没有定义

### ISSUE THREAD

**Issue by SalimaYang89** [neolee/pilot#1063]
![image](https://user-images.githubusercontent.com/53242782/74302209-a1004400-4d90-11ea-884a-139da8e15d9a.png)

**Comment by neolee** [comment]
截图里第一个代码格子里的代码没有运行过，你看各自前面的 [] 里是空的，就代表这个 cell 没运行过。

**Comment by SalimaYang89** [comment]
已经解决。非常感谢！
