### ISSUE TITLE
JupyterLab 不可运行代码

### ISSUE THREAD

**Issue by jiahaolawyer** [neolee/pilot#1064]
在jupyterlab里，把代码编辑好之后，点一下运行按钮，正常的情况是左侧会增加编号，然后代码运行后会返回结果，但现在按三角形运行健却不是这样，而是焦点往下走，不给返回情况，不知道自己在哪里摁错了。

**Comment by neolee** [comment]
有截图吗？光看描述不好判断问题。

**Comment by jiahaolawyer** [comment]
李老师，我把视频放在邮件的附件里了，因为github上我还不知道如何传视频。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Neo Lee <notifications@github.com&gt;
发送时间: 2020年2月12日 13:54
收件人: neolee/pilot <pilot@noreply.github.com&gt;
抄送: jiahaolawyer <94697734@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[neolee/pilot] JupyterLab 不可运行代码 (#1064)




有截图吗？光看描述不好判断问题。

**Comment by neolee** [comment]
没收到邮件呀。

不需要贴视频，贴截图就行了。
