### ISSUE TITLE
为什么安装了这个工具包之后还是反馈没有这个模块？

### ISSUE THREAD

**Issue by hermanxie** [neolee/pilot#1065]
![image](https://user-images.githubusercontent.com/48776732/74403371-f0fb0b80-4e61-11ea-81bb-a07104497230.png)
运行您给的几个命令之后，列表里已经有这个模块了。但还是出现上面的情况。
![image](https://user-images.githubusercontent.com/48776732/74403459-361f3d80-4e62-11ea-99e7-70932f3de456.png)
![image](https://user-images.githubusercontent.com/48776732/74403499-57802980-4e62-11ea-8d6f-72b96ce7de41.png)

**Comment by neolee** [comment]
运行下这几个命令：

```shell
python -V
pip -V

pip list
```

**Comment by hermanxie** [comment]
![image](https://user-images.githubusercontent.com/48776732/74319894-a83c4780-4dba-11ea-9203-a56d19d6e6d4.png)

**Comment by hermanxie** [comment]
运行完之后还是不行。这两个文件保存后显示这个颜色，是提示文件有问题吧？

**Comment by hermanxie** [comment]
![image](https://user-images.githubusercontent.com/48776732/74319979-ce61e780-4dba-11ea-9121-bd2e79367677.png)

**Comment by hermanxie** [comment]
![image](https://user-images.githubusercontent.com/48776732/74320395-7a0b3780-4dbb-11ea-867d-8257702abf5c.png)

**Comment by hermanxie** [comment]
这里的波浪线提示是否提示有问题？

**Comment by hermanxie** [comment]
![image](https://user-images.githubusercontent.com/48776732/74320514-b63e9800-4dbb-11ea-98e3-a66c816a3db3.png)

**Comment by hermanxie** [comment]
感谢老师！

**Comment by hermanxie** [comment]
![image](https://user-images.githubusercontent.com/48776732/74354807-db043100-4df6-11ea-8d43-eba944929fc6.png)
已经有了，但运行的时候还是提示：No module named 'termcolor'

**Comment by neolee** [comment]
你在做什么？遇到了什么问题？希望得到什么？

前面让你运行两个命令，其结果是啥？

**Comment by hermanxie** [comment]
请老师再看一下我的提问，谢谢

**Comment by neolee** [comment]
让你运行几个命令，一直没有告诉我结果是啥，只顾说你觉得重要的事情，这样的话，怎么帮你呀？

**Comment by hermanxie** [comment]
![image](https://user-images.githubusercontent.com/48776732/74415148-bef7a280-4e7d-11ea-8289-31aa16e2fadc.png)
![image](https://user-images.githubusercontent.com/48776732/74415189-d767bd00-4e7d-11ea-82e8-6b9b0fce5e01.png)
![image](https://user-images.githubusercontent.com/48776732/74415211-e3537f00-4e7d-11ea-8f26-208407c280bf.png)

**Comment by hermanxie** [comment]
抱歉！之前没有截图。

**Comment by neolee** [comment]
你的系统里有两个 Python 环境，一个是 `python` 这个命令指向的 3.8.0，一个是 `pip` 这个命令用的 3.7.4，后者可以确定是用 Scoop 装的，而前面那个我就不知道你怎么弄的了。

这个状况导致你用 pip 安装的包都在 3.7.4 那个环境下，而你用 python 命令运行 .py 程序时用的是完全不同的一个 3.8.0 的环境，找不到你用 pip 安装的包。

解决思路是：删掉 3.8.0 的 Python（我不知道你咋装的，咋装的就咋卸）；检查系统 PATH 设定，确保 python 命令指向 Scoop 安装的 Python。

**Comment by hermanxie** [comment]
老师好！我把2个版本的phthon删除后又重装了。但是在导入termcolor模块后，运行又出现了新的问题：
![image](https://user-images.githubusercontent.com/48776732/74514241-2168a580-4f47-11ea-9846-de2f1dd5e42d.png)
![image](https://user-images.githubusercontent.com/48776732/74514263-288fb380-4f47-11ea-8fd1-a7dc6bfa3ee6.png)

![image](https://user-images.githubusercontent.com/48776732/74514121-ed8d8000-4f46-11ea-85e8-0e67a2f380da.png)

**Comment by hermanxie** [comment]
还有这个problems里面提示有这些问题
![image](https://user-images.githubusercontent.com/48776732/74514326-4bba6300-4f47-11ea-95a3-f1fdc780ca0a.png)

**Comment by neolee** [comment]
1. 你还是装了 3.8.1，这个版本有些包会不兼容，和我的环境也不一样，风险自担。

2. VSCode 的 Terminal 环境和 ConEmu 会有区别，对有些功能支持不足，所以会出现你看到的那些奇怪的码，你在 ConEmu 下运行就会看到这些码的效果，其实是给中间的文字指定颜色。

**Comment by hermanxie** [comment]
明白了，谢谢！
