### ISSUE TITLE
派生类运行过程中提示变量未定义？

### ISSUE THREAD

**Issue by trayoung** [neolee/pilot#1066]
基类创建完成之后，第一个派生类可以正常运行，
![第一个派生类可以正常运行](https://user-images.githubusercontent.com/39803462/74329518-e7729480-4dca-11ea-87ad-5371a9b7e7e5.JPG)
但是第二个派生类运行时报错，我自己理解的是：派生类中是通过基类传递变量的，无需再次定义，但是一直提示该变量，
![派生类定义之后运行失败](https://user-images.githubusercontent.com/39803462/74329543-f5281a00-4dca-11ea-8a4d-75241dc9c6df.JPG)
请李骏老师指点迷津

**Comment by neolee** [comment]
`feeling` 这个变量确实没定义呀。

**Comment by trayoung** [comment]
我把feeling改成s之后就如就可以了，谢谢李骏老师。
