### ISSUE TITLE
在执行git的时候出现了些问题

### ISSUE THREAD

**Issue by yusen7** [neolee/pilot#1067]
按照git与github的视频课程一步步来的

**Comment by yusen7** [comment]
这是老师视频的截图：
![Uploading 老师.jpg…]()

**Comment by yusen7** [comment]
![Uploading K8Y9`AP[FNW2$`EE{8LER10.png…]()

**Comment by neolee** [comment]
图片上传没成功，你要等 Uploading 完毕，那句话变成 <img>... 才行。
