### ISSUE TITLE
输入 git commit 这个指令的时候出现了些问题

### ISSUE THREAD

**Issue by yusen7** [neolee/pilot#1068]
今天在学习《Git 与 GitHub 入门》这一章节中，我先把视频全看完，并边看视频边敲代码。
在执行git config --global core.editor "code -w"的时候，我仔细和视频对照，发现少了：
alias.co=checkout
alias.st=status
alias.br=branch
alias.ci=commit
这四个。
然后我继续按步骤执行。
在输入git commit 这个指令时提交失败（我觉得是少了那四个代码导致的）
我重试了几次，还是这样。
最后一次执行git config --global core.editor "code -w"的时候，出现了SUMMARY OF LESS COMMANDS(LESS命令摘要)，下面出现了命令，我按了q退了出来。
然后输入code .\.gitconfig ,跳出VScode界面，gitconfig 文件的内容是空的。（前几次不是空的）

**Comment by yusen7** [comment]
![J}{JJ)Q7BLOH%P0$KA$47J1](https://user-images.githubusercontent.com/59310500/74340119-527a9600-4de0-11ea-92a4-860bb9ce4e7f.png)

**Comment by yusen7** [comment]
![8 CLVUJW9C~5HW~1CJ(49H](https://user-images.githubusercontent.com/59310500/74340738-71c5f300-4de1-11ea-9c26-eb5304640705.png)

**Comment by yusen7** [comment]
![我](https://user-images.githubusercontent.com/59310500/74340801-9326df00-4de1-11ea-9e21-59f661031fcd.png)

**Comment by yusen7** [comment]
第二张图片是执行了git config --global core.editor "code -w"的时候。少了：
alias.co=checkout
alias.st=status
alias.br=branch
alias.ci=commit
然后就卡在那边没有结束。

**Comment by yusen7** [comment]
![0OBCW2PRG4AHJDC_W VZ)0N](https://user-images.githubusercontent.com/59310500/74342196-1812f800-4de4-11ea-9c02-859219d90f60.png)

**Comment by yusen7** [comment]
![Uploading 0OBCW2PRG4AHJDC_W]VZ)0N.png…]()

**Comment by yusen7** [comment]
![wo](https://user-images.githubusercontent.com/59310500/74344068-fd8e4e00-4de6-11ea-889f-e3ac975f7ec2.png)

**Comment by neolee** [comment]
那几个 alias 的配置无所谓的，可以做也可以不做，做了就是输入命令简短一点罢了。

`git config -l` 显示出来之后，在冒号后面输入 q 就可以退出。

那个配置文件是 `.gitconfig`，最前面有个点。

所以你的问题是啥？

**Comment by yusen7** [comment]
就是昨天输入 git commit 这个指令时出现提交不成功的情况，怎么办呢？我当时以为是没有那几个指令造成的。

**Comment by yusen7** [comment]
今天又试了一次
输入git commit
出现：
提示：等待编辑器关闭文件。。。内部/模块/cjs/loader.js:630

抛出错误；

^



错误：找不到模块“C:\用户”

在Function.Module.\u resolveFilename（内部/modules/cjs/loader.js:627:15）

在功能模块加载（内部/模块/cjs/loader.js:531:27）

at Function.Module.runMain（内部/modules/cjs/loader.js:850:10）

内部/主/运行主模块。js:17:11{

code:'未找到模块'，

要求检查：[]

}

错误：编辑器“code-w”有问题。

请使用-m或-F选项提供消息。

**Comment by neolee** [comment]
嗯，你最后这个回复才是个问题，不过已经有好几个一样的问题了，很容易搜索到，最近一个是 #1055

**Comment by neolee** [comment]
顺便，你试试在命令行直接运行 `code -w -m`，会出现什么提示？

**Comment by yusen7** [comment]
直接运行code -w -m，会出现这个提示：
Warning: 'm' is not in the list of known options, but still passed to Electron/Chromium.
警告：“m”不在已知选项列表中，但仍传递给Electron/Chromium。
然后跳出VScode 的界面，文件README.md的内容出现:This is a test file.

**Comment by yusen7** [comment]
浏览了几个战友的问题
发现有个战友给了一个方法，试着输入：git commit -m .\README.md
提交成功了！
显示：
[master (root-commit) b16e980] .\README.md
 1 file changed, 1 insertion(+)
 create mode 100644 README.md

**Comment by yusen7** [comment]
但是用这个git commit -m .\README.md 提交，不会从VScode中跳出 COMMIT_EDITMSG这个文件出来。

**Comment by neolee** [comment]
`git commit -m` 后面应该跟提交说明文字，你输入这个没意义。仔细看我在 #415 里的回复。

搞清楚你输入的命令是什么意思，每个字是啥意思；搞清楚电脑反馈给你的信息是啥意思。一开始会有点累，但很快就能进步。否则是走不远的。

**Comment by yusen7** [comment]
git commit -m "add notes to README.md"
git    做出    向 README.md 增加注释？ 
电脑反馈的信息：
On branch master
Changes not staged for commit:
        modified:   README.md
在分支主机上

未暂存以提交的更改：

修改：README.md

**Comment by yusen7** [comment]
git commit -m "add notes to README.md"
 git 向 README.md提交 增加注释？
电脑反馈的信息：
On branch master
Changes not staged for commit:
modified: README.md
在分支主机上

未暂存以提交的更改：

修改：README.md

**Comment by neolee** [comment]
`git commit -m "add notes to README.md"`

这个用法就对了。

在命令行输入 `code -w`  回车，结果是什么？

**Comment by yusen7** [comment]
在命令行输入 code -w 回车，结果是跳出了vscode 界面。里面有README.md的内容。

**Comment by yusen7** [comment]
git commit -m "提交说明文字"
和 code -w 回车
这两个命令可以代替git commit 指令？

**Comment by neolee** [comment]
不能替代，我是在尝试搞清楚为啥会有最开始那个问题。算了，你继续学习吧。
