### ISSUE TITLE
pandas 无法运行

### ISSUE THREAD

**Issue by bigbigblock** [neolee/pilot#1070]
请教下老师
pip list | grep pandas

pandas             1.0.1    
Note: you may need to restart the kernel to use updated packages.

import pandas as pd
print(pd.__version__)

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-16-6142b137f9a0> in <module>
----> 1 import pandas as pd
      2 print(pd.__version__)

~/Code/51/pandas.py in <module>
      1 
      2 import pandas as pd
----> 3 print(pd.__version__)
      4 
      5 

AttributeError: module 'pandas' has no attribute '__version__'

使用pip 可以看到 version
但 import 后 就报出 module 'pandas' has no attribute '__version__
已经 用 pip uninstall pandas
              pip install pandas   
一瞬间好了，然后又不行了

**Comment by neolee** [comment]
你的目录下有个叫 pandas.py 的文件吧，这种情况下你的 `import pandas` 会引入这个文件而不是安装的库。

**Comment by bigbigblock** [comment]
还真是 ，删除就好了，但是是怎么出现这个文件的？我不记得创建过，谢谢
