### ISSUE TITLE
MySQL 环境准备卡在安装 mysq157

### ISSUE THREAD

**Issue by Erika00** [neolee/pilot#1071]
![dc07e79c2ebedbe0d30ad2b576bc358](https://user-images.githubusercontent.com/52418630/74400661-98c00b80-4e59-11ea-9c8e-a9435a2ff104.png)
李骏老师 ，按指南安装'mysq157'，显示找不到该文件，是要我自建一个空的文件？

**Comment by neolee** [comment]
是 `mysql57` 不是 `mysq157`。睁大眼睛仔细看……

**Comment by Erika00** [comment]
好呢
