### ISSUE TITLE
有限状态机示例问题

### ISSUE THREAD

**Issue by Lilidandan321** [neolee/pilot#1072]
![4QU58G__ZCC) 606 {LVQPT](https://user-images.githubusercontent.com/53359222/74412473-7b4e6a00-4e78-11ea-97ce-dd15a0f7179b.png)
有限状态机示例中succeeded和state方法从未定义但是可以直接使用，是因为Python 自带吗，还是因为我理解有问题。

**Comment by neolee** [comment]
`state` 是 `Order` 类里定义的变量，你错写成了 `states`。

`payment_service` 是个假想中存在的函数，我没有真的实现它，其返回值可能是一个对象，包含成功和失败的方法/属性。

这段代码是示意性的，说明不适用状态机来维护复杂状态系统会很麻烦。

**Comment by Lilidandan321** [comment]
好的，知道了，谢谢老师。
