### ISSUE TITLE
pip install pandas 失败

### ISSUE THREAD

**Issue by Sclarlett** [neolee/pilot#1073]

**Comment by Sclarlett** [comment]
老师  这是网络问题嘛？试过几次都这样
![Uploading 1581594095(1).png…]()
![Uploading 1581594222(1).png…]()

**Comment by neolee** [comment]
看不到截图。

**Comment by Sclarlett** [comment]
![1581594095(1)](https://user-images.githubusercontent.com/56901849/74525928-423bf580-4f5d-11ea-8736-3baec3448220.png)
![1581594222(1)](https://user-images.githubusercontent.com/56901849/74525929-423bf580-4f5d-11ea-94e6-858000dc55e5.png)
如果截图还是不行，估计就是网络问题了，山区的网络。。。。

**Comment by neolee** [comment]
截图成功……

安装失败是因为网络问题，可能需要代理。

**Comment by gaoteng-pro** [comment]
看不到你的图片，你可以在命令行试试pip3 install pandas，我就是用的这个装的。
