### ISSUE TITLE
PATH 环境变量

### ISSUE THREAD

**Issue by tsao86** [neolee/pilot#1074]
Mac 系统，Visual studio code按照教材设置后，无法用快捷键code . 在Termial 打开，查看Issue可能是PATH环境变理的问题，通过网上搜查输入```echo $PATH``` 提示路径如下：```/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin```
请老师和同学们指点我的路径有没有问题，如何设置路径？多谢。

![Uploading 屏幕快照 2020-02-13 下午10.25.55.png…]()

**Comment by neolee** [comment]
这个 PATH 值没问题的，code 命令会被安装在 `/usr/local/bin` 下面。

所以不是这个问题，你确定做好了设置吗？看看 `/usr/local/bin/code` 这个 symbol link 是不是存在，并指向 `/Applications/Visual Studio Code.app/Contents/Resources/app/bin/code`。

**Comment by tsao86** [comment]
刚刚```brew doctor``` Hombrew. 出现了warning，应该是跟Path 路径有关的问题，不明白```echo 'export PATH="/usr/local/bin:$PATH"' >> ~/.bash_profile```,是什么意思，随付载图，请指点，多谢。
![Uploading 屏幕快照 2020-02-13 下午11.37.28.png…]()

**Comment by tsao86** [comment]
疫情期间，宅家用的手机热点，载图可能没有成功，再摘录一遍Warning.
```Warning: /usr/bin occurs before /usr/local/bin
This means that system-provided programs will be used instead of those
provided by Homebrew. The following tools exist at both paths:

Consider setting your PATH so that /usr/local/bin
occurs before /usr/bin. Here is a one-liner:
  echo 'export PATH="/usr/local/bin:$PATH"' >> ~/.bash_profile
  git-receive-pack
  git-upload-archive
  git-cvsserver
  git-shell
  git-upload-pack
  git
caoyuelongdeMacBook-Pro:~ Tsao$ 
```

**Comment by neolee** [comment]
一个问题一个问题来，不要一个没解决就开始搞另一个。前一个问题看我上面的回复，先把这个解决掉。

下面这个问题是说 `/usr/local/bin` 这个目录要放在 PATH 变量的前面，这样遇到同名的程序会优先运行 `/usr/local/bin` 下面的那个。这个需要编辑你的 `~/.bash_profile` 文件，解决了前一个问题后，可以用 `code ~/.bash_profile` 打开该文件，在最后加上下面一句就可以了：
```shell
export PATH="/usr/local/bin:$PATH"
```

**Comment by tsao86** [comment]
好的，先解决第一个问题。
输入```/usr/local/bin/code``` 输出```-bash: /usr/local/bin/code: No such file or directory```
另附截图：visual studio code 的 shell command 设置如下： 
<img width="584" alt="屏幕快照 2020-02-14 下午3 29 24" src="https://user-images.githubusercontent.com/49138260/74510533-efebdc00-4f3e-11ea-9bd1-3d020c2816cc.png">

**Comment by neolee** [comment]
这个说明没有设置成功，你在 Visual Studio Code 下面执行了你截图的这个命令了么？执行后有什么反馈？

**Comment by tsao86** [comment]
第一个问题解决了。
visual studio code   需要在打开的状态下 再输入```code .```命令。
另外，visual studio code在打开的状态下输入```/usr/local/bin/code```会直接打开visual studio code。
visual studio code   在没有打开的情况下，输入```/usr/local/bin/code```会输出```-bash: /usr/local/bin/code: No such file or directory```.

多谢李骏老师

**Comment by neolee** [comment]
> visual studio code 需要在打开的状态下 再输入`code .`命令。
> 另外，visual studio code在打开的状态下输入`/usr/local/bin/code`会直接打开visual studio code。
> visual studio code 在没有打开的情况下，输入`/usr/local/bin/code`会输出`-bash: /usr/local/bin/code: No such file or directory`.

不会吧！没有这样的道理，你执行这几个命令，把*完整的*结果给我看看：

```shell
ls -l /usr/local
ls -l /usr/local/bin/code

ls -l /Applications/Visual Studio Code.app/Contents/Resources/app/bin/
```

**Comment by tsao86** [comment]
```Last login: Fri Feb 14 15:48:47 on ttys000
caoyuelongdeMacBook-Pro:~ Tsao$ ls -l /usr/local
total 0
drwxrwxr-x    2 Tsao  admin    64  1 17 18:25 Caskroom
drwxrwxr-x   20 Tsao  admin   640  1 18 14:33 Cellar
drwxrwxr-x    4 Tsao  admin   128  2  6 21:44 Frameworks
drwxrwxr-x   20 Tsao  admin   640  2 13 23:33 Homebrew
drwxrwxr-x  132 Tsao  admin  4224  2 14 15:29 bin
drwxrwxr-x    8 Tsao  admin   256  1 18 14:33 etc
drwxrwxr-x   26 Tsao  admin   832  1 18 14:33 include
drwxrwxr-x   62 Tsao  admin  1984  1 18 14:33 lib
drwxrwxr-x   29 Tsao  admin   928  2  6 21:44 opt
drwxrwxr-x    3 Tsao  admin    96  1 17 18:27 sbin
drwxrwxr-x   17 Tsao  admin   544  1 17 18:44 share
drwxrwxr-x    3 Tsao  admin    96  1 17 18:25 var
caoyuelongdeMacBook-Pro:~ Tsao$ ls -l /usr/local/bin/code
lrwxr-xr-x  1 Tsao  admin  167  2 14 15:29 /usr/local/bin/code -> /private/var/folders/0d/crjcvbk54k33xknhls480mc40000gn/T/AppTranslocation/8990AD59-A406-43D2-B162-2DBF68664522/d/Visual Studio Code.app/Contents/Resources/app/bin/code
caoyuelongdeMacBook-Pro:~ Tsao$ ls -l /Applications/Visual Studio Code.app/Contents/Resources/app/bin/
ls: /Applications/Visual: No such file or directory
ls: Code.app/Contents/Resources/app/bin/: No such file or directory
ls: Studio: No such file or directory
caoyuelongdeMacBook-Pro:~ Tsao$ 
```

**Comment by neolee** [comment]
对了，你是不是没有把 Visual Studio Code 放到 Applications 目录下？

macOS 安装一个应用，就需要把这个应用拖到 Applications 目录下去，否则很多东西会有问题。

**Comment by tsao86** [comment]
<img width="587" alt="屏幕快照 2020-02-14 下午4 42 23" src="https://user-images.githubusercontent.com/49138260/74515336-5675f780-4f49-11ea-9ba0-f693be07a0b5.png">

**Comment by neolee** [comment]
再执行一次安装 code 命令的操作，你之前做的 code 命令指向错误的地方，你把 VSCode 搬到 Applicaitons 下面之后要再做一次。

**Comment by tsao86** [comment]
命令行输入```code .``` 可以直接接打开visual studio code 了，十分多谢。
