### ISSUE TITLE
运行自检命令 brew doctor 出现警告

### ISSUE THREAD

**Issue by tsao86** [neolee/pilot#1076]
出现的警告如下：
```caoyuelongdeMacBook-Pro:code Tsao$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: /usr/bin occurs before /usr/local/bin
This means that system-provided programs will be used instead of those
provided by Homebrew. The following tools exist at both paths:

Consider setting your PATH so that /usr/local/bin
occurs before /usr/bin. Here is a one-liner:
  echo 'export PATH="/usr/local/bin:$PATH"' >> ~/.bash_profile
  git-receive-pack
  git-upload-archive
  git-cvsserver
  git-shell
  git-upload-pack
  git

Warning: Broken symlinks were found. Remove them with `brew cleanup`:
  /usr/local/bin/code
caoyuelongdeMacBook-Pro:code Tsao$ 
```

**Comment by neolee** [comment]
这个问题是说 `/usr/local/bin` 这个目录要放在 PATH 变量的最前面，这样遇到同名的程序会优先运行 `/usr/local/bin` 下面的那个。这个需要编辑你的 `~/.bash_profile` 文件，可以用 `code ~/.bash_profile` 打开该文件，在最后加上下面一句就可以了：

```shell
export PATH="/usr/local/bin:$PATH"
```

**Comment by tsao86** [comment]
在终端输入```code ~/.bash_profile``` 直接打开了visual studio code .

经搜索是不是需要创建 .bash_profile？链接如下：[https://blog.csdn.net/huxinguang_ios/article/details/78709428](url)
如是，链接内容是否可信，谢谢。

**Comment by neolee** [comment]
如果你没有这个文件，可以创建，然后加入上面那句就行了。

**Comment by tsao86** [comment]
输入```ls -a``` 查询没有 ```.bash_profile```
百度查询CSDN贴子 依次输入 ```cd ~/```  ```touch .bash_profile``` ```open .bash_profile```
这样打开一个记事本 输入```export PATH="/usr/local/bin:$PATH"```
快捷键``` command+s```保存,退出记事本.
执行生效命令 ```source .bash_profile```

最后再次执行``` brew doctor```,没再出现Warning.
这是从网上看到的内容，请李骏老师和同学们再次检查下。

**Comment by neolee** [comment]
别怕，做就是了，有问题再解决。只要你知道你改过什么，知道怎么复原，没啥不可逆的危险。

**Comment by tsao86** [comment]
搞定，多谢。
