### ISSUE TITLE
第三课大小比较操作符里 'aab' > 'aaa' 这个部分是字母的比较，还是字母所赋值的数字的比较

### ISSUE THREAD

**Issue by zorahong57** [neolee/pilot#1077]
程序的基本结构（二）里
```python
a = 6
b = 30
```
在大小比较操作符这部分里有一个比较
```python
'aab' > 'aaa'
```
如果是数字的比较，```'aab'``` 和 ```'aaa'``` 是字符串没有办法输出任何数值
![{3AA979F9-F224-4389-96FB-6BC9536B183B} png](https://user-images.githubusercontent.com/60477266/74512695-ced9ba00-4f43-11ea-9031-7d0a8ca858b0.jpg)

在这里，我理解的是字母本身不代表任何数值，只是按字母顺序大小进行比较。因为用其它没有赋值的字母比较，也是按字母顺序来比较的。但```'dfg' > 'ewr'```结果却是False。所以想问一下，是应该按下面这种来理解吗？
![Annotation 2020-02-14 161157](https://user-images.githubusercontent.com/60477266/74513091-c2099600-4f44-11ea-9a44-edb1a78a71c3.jpg)

**Comment by neolee** [comment]
`a = 6` 里面的 a 是一个“变量”，也就是编程语言里面给 `6` 这个值起了个名字叫做 `a`。

`'aab'` 里面的 a 和 b 都是“字符”，是我们处理的一种“值”。

这个差别能理解吧？

比较字符和字符串时是按照字母表顺序，也可以说是按照 ASCII 码的大小顺序。

**Comment by zorahong57** [comment]
现在明白了，谢谢李老师
