### ISSUE TITLE
输入“输入 git clone ”时出错

### ISSUE THREAD

**Issue by lxj376169569** [neolee/pilot#1078]
PS C:\Users\Administrator\Code> git clone https://github.com/lxj376169569/pilot-student.git
Cloning into 'pilot-student'...
fatal: unable to access 'https://github.com/lxj376169569/pilot-student.git/': Failed to connect to github.com port 443: Timed out

**Comment by jiangsv** [comment]
众所周知的我国的网络问题，只能多试几次想想用什么工具了
[了解更多](https://github.community/t5/How-to-use-Git-and-GitHub/Unable-to-git-clone-a-repo-due-to-port-443-time-out-issue/td-p/3459)

**Comment by lxj376169569** [comment]
谢谢  我自己找到方法了 输入 git config --global http.https://github.com.proxy socks5://127.0.0.1:1080  就解决了
