### ISSUE TITLE
字符串数据一节中输入 email 并打印

### ISSUE THREAD

**Issue by Milkmocha** [neolee/pilot#1079]
老师好，我不知道下面的code出了什么问题，但我输入邮箱后打印出来的总是“Please enter your Email:”， 而不是“Your Email address is”。我觉得和这个单引号有关系，就试着把句子中间的单引号换成双引号，但还是同样的问题。您觉得问题出在哪里呢？十分感谢！
![email code](https://user-images.githubusercontent.com/52839136/74561043-ddb97000-4f35-11ea-826a-377702f715db.PNG)
![email code 2](https://user-images.githubusercontent.com/52839136/74561383-76e88680-4f36-11ea-8de0-730973fd5465.PNG)

**Comment by neolee** [comment]
最后一行 print 的缩进错了，你这样写它变成 while 循环里的一部分了。

**Comment by Milkmocha** [comment]
不好意思，这么没有水平的错误。感谢老师的及时反馈！

**Comment by neolee** [comment]
问题不分水平，都要问都要解决，解决就好。

重要的是同样的错误不犯两次。
