### ISSUE TITLE
新手上路

### ISSUE THREAD

**Issue by caochao-lei** [neolee/pilot#1082]
在VScode 里输入了源代码，但是在命令行界面输入python hello.py 没有输出，请问这是除了什么问题？（代码没有输错）

**Comment by neolee** [comment]
至少要给出你的代码和运行时的截图吧，要不然让我们如何猜出了啥事呢……

**Comment by caochao-lei** [comment]
![UL)EW9JVV4E 8O1 OH5HBQF](https://user-images.githubusercontent.com/59311022/74584209-c5675500-500a-11ea-8e93-e9624b490d67.png)
![QH{RWQ(F`BA3B3 } FHD H](https://user-images.githubusercontent.com/59311022/74584210-c6988200-500a-11ea-9aa0-5baeab5d25bd.png)

**Comment by caochao-lei** [comment]
---原始邮件---
发件人: "Neo Lee"<notifications@github.com&gt;
发送时间: 2020年2月15日(周六) 下午2:45
收件人: "neolee/pilot"<pilot@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"caochao-lei"<1191971507@qq.com&gt;;
主题: Re: [neolee/pilot] 新手上路 (#1082)



至少要给出你的代码和运行时的截图吧，要不然让我们如何猜出了啥事呢……

**Comment by neolee** [comment]
邮件里贴的图片不会出现在这里，最好还是在 GitHub 的网页上回复。

看了你的截图之后，你在 VS Code 里运行的是 `C:\Users\86133\Code` 目录下的 `hello.py`；而在命令行下，你是在 `C:\Users\86133` 目录下运行，可能这两个目录下的 `hello.py` 不一样吧。

几点建议：
1. 认真学习支线课程，看上去你对命令行以及工作目录的概念不熟悉，支线课程一是必看的；另外讲述 Visual Studio Code 的那一讲也最好看看。
2. 命令行界面不要用 Windows 的 cmd.exe，用我推荐的 ConEmu 配合 PowerShell，否则很多东西是会出问题的。

如果你是专家，当然可以不管教材里的环境配置指南；如果不是，最好按部就班照做。

**Comment by caochao-lei** [comment]
好的，谢谢老师



---原始邮件---
发件人: "Neo Lee"<notifications@github.com&gt;
发送时间: 2020年2月15日(周六) 下午4:13
收件人: "neolee/pilot"<pilot@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"caochao-lei"<1191971507@qq.com&gt;;
主题: Re: [neolee/pilot] 新手上路 (#1082)



邮件里贴的图片不会出现在这里，最好还是在 GitHub 的网页上回复。
 
看了你的截图之后，你在 VS Code 里运行的是 C:\Users\86133\Code 目录下的 hello.py；而在命令行下，你是在 C:\Users\86133 目录下运行，可能这两个目录下的 hello.py 不一样吧。
 
几点建议：
  
认真学习支线课程，看上去你对命令行以及工作目录的概念不熟悉，支线课程一是必看的；另外讲述 Visual Studio Code 的那一讲也最好看看。 

命令行界面不要用 Windows 的 cmd.exe，用我推荐的 ConEmu 配合 PowerShell，否则很多东西是会出问题的。 
 
如果你是专家，当然可以不管教材里的环境配置指南；如果不是，最好按部就班照做。

**Comment by caochao-lei** [comment]
我是新手，肯定听老师的



---原始邮件---
发件人: "Neo Lee"<notifications@github.com&gt;
发送时间: 2020年2月15日(周六) 下午4:13
收件人: "neolee/pilot"<pilot@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"caochao-lei"<1191971507@qq.com&gt;;
主题: Re: [neolee/pilot] 新手上路 (#1082)



邮件里贴的图片不会出现在这里，最好还是在 GitHub 的网页上回复。
 
看了你的截图之后，你在 VS Code 里运行的是 C:\Users\86133\Code 目录下的 hello.py；而在命令行下，你是在 C:\Users\86133 目录下运行，可能这两个目录下的 hello.py 不一样吧。
 
几点建议：
  
认真学习支线课程，看上去你对命令行以及工作目录的概念不熟悉，支线课程一是必看的；另外讲述 Visual Studio Code 的那一讲也最好看看。 

命令行界面不要用 Windows 的 cmd.exe，用我推荐的 ConEmu 配合 PowerShell，否则很多东西是会出问题的。 
 
如果你是专家，当然可以不管教材里的环境配置指南；如果不是，最好按部就班照做。
