### ISSUE TITLE
pandas 打开 CSV 文件时报错

### ISSUE THREAD

**Issue by gaoteng-pro** [neolee/pilot#1083]
```python

import pandas as pd
​
data = pd.read_csv('assets/moma-artists.csv')
data.head(10)

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-226-59356af6b878> in <module>
----> 1 import pandas as pd
      2 
      3 data = pd.read_csv('assets/moma-artists.csv')
      4 data.head(10)

/usr/local/lib/python3.7/site-packages/pandas/__init__.py in <module>
    190 # GH 27101
    191 # TODO: remove Panel compat in 1.0
--> 192 if pandas.compat.PY37:
    193 
    194     def __getattr__(name):

AttributeError: module 'pandas' has no attribute 'compat'
```

**Comment by neolee** [comment]
你的 Python 环境是怎么安装的？是完全按照我的环境配置指南么？

执行下述命令，给我看看结果：

```shell
python -V
python3 -V
pip -V

pip list
```

**Comment by gaoteng-pro** [comment]
![图像2020-2-15 下午7 17](https://user-images.githubusercontent.com/57254889/74587007-77614a00-5028-11ea-8f03-1b2751276ff3.jpeg)
![图像2020-2-15 下午7 18](https://user-images.githubusercontent.com/57254889/74587025-98c23600-5028-11ea-975c-e0d0668aa985.jpeg)

**Comment by gaoteng-pro** [comment]
按照老师的指南安装的，唯一不一样的是Xcode我是在mac 的app store下载的，因为安装老师的方法无法完成Xcode相关部分的安装，索性就下载了整个Xcode。

**Comment by neolee** [comment]
那你运行 `pip3 list --outdated` 的结果是什么呢？

**Comment by gaoteng-pro** [comment]
![图像2020-2-16 下午1 50](https://user-images.githubusercontent.com/57254889/74599819-513cb800-50c3-11ea-873c-fffdda157656.jpeg)

**Comment by neolee** [comment]
你看看我让你跑的命令是啥，你输入的又是啥。

**Comment by gaoteng-pro** [comment]
sorry
![图像2020-2-16 下午4 33](https://user-images.githubusercontent.com/57254889/74601504-1c882b00-50da-11ea-96f8-c358f071a535.jpeg)

**Comment by neolee** [comment]
你的环境里有很多包很久了（有些又很新），有可能会有兼容性问题，建议先把所有包都升到最新，我们学习用的包的最新版本基本都是没问题的，可以用下面的命令来一次性更新所有过期的包：

```shell
pip list --outdated --format=freeze | grep -v ^-e | cut -d = -f 1 | xargs -n1 pip install -U
```

**Comment by gaoteng-pro** [comment]
编程课开课之后才买的新电脑，然后就按照教程操作，应该不存在很久。两个月不算太久吧。。。

无法更新
![图像2020-2-16 下午8 40](https://user-images.githubusercontent.com/57254889/74604843-bbbe1a00-50fc-11ea-8695-c0f064541a1f.jpeg)

**Comment by neolee** [comment]
有两个 pip，都改成 pip3。

**Comment by gaoteng-pro** [comment]
命令行pip运行后有三处报错，其余都成功了。在jupyter lab 里运行，问题依旧。
```python 
import pandas as pd
​
data = pd.read_csv('assets/moma-artists.csv')
data.head(10)
​
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-239-59356af6b878> in <module>
----> 1 import pandas as pd
      2 
      3 data = pd.read_csv('assets/moma-artists.csv')
      4 data.head(10)

/usr/local/lib/python3.7/site-packages/pandas/__init__.py in <module>
    190 # GH 27101
    191 # TODO: remove Panel compat in 1.0
--> 192 if pandas.compat.PY37:
    193 
    194     def __getattr__(name):

AttributeError: module 'pandas' has no attribute 'compat'
```

下面是pip时的三处报错的图片。
![图像2020-2-16 下午10 37](https://user-images.githubusercontent.com/57254889/74606751-f54b5100-510d-11ea-9031-36d9f3e58239.jpeg)

**Comment by neolee** [comment]
试试：

```shell
pip3 uninstall pandas
pip3 install pandas
```

**Comment by neolee** [comment]
另外，你的 Python 环境是干净的重新安装的吗？`pip list` 里面有些 module 并不是课程所需要的，课程中也没有指引安装过。

你碰到的这个错误通常是 Python 的某些包和 pandas 冲突导致的。

**Comment by gaoteng-pro** [comment]
`pip3 uninstall pandas`，`pip3 install pandas`这两个运行完，jupyter lab问题依旧（报错完全一样）。

python环境是干净的，有pip过笑来老师的《自学是门手艺》里的某几个包，好像还有没装成功的。

**Comment by gaoteng-pro** [comment]
目前pip list目录
<img width="405" alt="截屏2020-02-17上午10 17 51" src="https://user-images.githubusercontent.com/57254889/74618988-e47ef780-516e-11ea-92ba-7b19f90f489e.png">
<img width="304" alt="截屏2020-02-17上午10 17 00" src="https://user-images.githubusercontent.com/57254889/74618995-e9dc4200-516e-11ea-909b-e87233c5cc68.png">

**Comment by neolee** [comment]
感觉应该是某些包损坏了（丢失了文件或者有不正确的版本），这个情况很罕见，犹豫不知道曾经做过哪些操作，所以不好判断。

可以考虑：要么删掉这个 Python 环境重新来一遍，要么创建一个虚拟环境测试一下。可以自己 Google 一下方法。

**Comment by gaoteng-pro** [comment]
又重新彻底地重装了系统，然后按github上的照教程一步一步去做。第一步就出现了问题（和上一次按照教程去做出现一样的问题）按如下图：
![图像2020-2-18 下午9 23](https://user-images.githubusercontent.com/57254889/74741380-a4fffa80-5297-11ea-88fe-cb3caacb0d76.jpeg)

**Comment by neolee** [comment]
这是网络的问题。

**Comment by gaoteng-pro** [comment]
前前后后折腾了好久，问题终于解决了。
感受：利用好issues社区，当你家的Wi-Fi不行的时候（虽然Wi-Fi可以很流畅地看视频网速也很快，但就是不行，无解。。。），可以试试手机的热点，一次不行就两次，两次不行就三次，我前前后后试了几十次。。。
PS：国内装个编程环境这么费劲，心疼那些程序员同学。。。
![图像2020-2-20 下午4 58](https://user-images.githubusercontent.com/57254889/74917968-5c655000-5403-11ea-96f8-b0676312bea8.jpeg)

**Comment by neolee** [comment]
称职的程序员基本都有办法搞定网络的问题 😀
