### ISSUE TITLE
视频课《内存中的数据》（15:51）

### ISSUE THREAD

**Issue by gaoteng-pro** [neolee/pilot#1084]
```python
import uuid
import hashlib

def hashpw(passwd):
    salt = uuid.uuid4().hex
    return hashlib.sha256(salt.encode() + passwd.encode()).hexdigest() + ':' + salt
```
由上所得，
`salt.encode() = uuid.uuid4().hex.encode()`

**问题：**

 为什么`uuid.uuid4().hex.encode()`有这么多点`.`，我们学过的引用一个包，里面也才一个点`.`。如，随机生成10个1-99的整数组成的列表：
```python
import random
[random.randrange(1,100) for i in range(10)]
```
这里也才用了一个点`.`，就是调用random包里的randrange函数，即使object调用自身的method，格式也是`object.method`一个点`.`就可以了。像`uuid.uuid4().hex.encode()`一下子这么多点`.`，确实有些懵，不知如何理解，望老师解惑。

**Comment by neolee** [comment]
`uuid.uuid4().hex.encode()`

这些点的含义是不同的。

`uuid.uuid4()` 是调用 `uuid` 包里的一个函数 `uuid4()`，返回的是一个 `UUID` 类型的对象。

然后 `uuid.uuid4().hex` 是取上述 `UUID` 对象的 `hex` 属性，这是一个长度为32的字符串。

最后，`uuid.uuid4().hex.encode()` 是调用上述字符串对象的 `encode()` 方法。

对初学者来说，搞懂上面所有这些需要花点时间，查查对应的文档，但不难。

**Comment by gaoteng-pro** [comment]
`uuid.uuid4().hex.encode()`第一个点`.`是安装包里的函数调用，剩下的两个点`.`属于object的调用。`uuid.uuid4()`这一句的函数调用没有参数，也就是说`uuid4()`这个函数的返回值是固定的，可以这么理解吗？

**Comment by neolee** [comment]
`uuid4()` 的返回不是固定的，而是通过算法生成的一个唯一的随机数。其他理解没问题。

**Comment by gaoteng-pro** [comment]
`uuid4()`返回虽然不是固定的，但是不是可以理解成，`uuid4()`里的函数体是固定的，就像`random.randrange(1,100)`这句代码是固定的，但每次返回的随机数是唯一且不一定的，可以这样理解吗？

在今后遇见许多点`.`这种形式（如`uuid.uuid4().hex.encode()`），我们该如何理解它是函数的调用还是`object`的`attribute` 或`method`的调用？
是不是这种形式，只有第一个点`.`是安装包里的函数调用，除此之外后面的所有点`.`都是`object`的`attribute`或`method`的调用，可以这样理解吗？

安装包和里面的函数只有一层的层级关系吗？目前遇到的都是一层就到函数，形式都是：`安装包.函数（）`，有例外吗？是不是无论安装包到函数有几层，只要`安装包.XX.XX.XX.函数（）`它就是最后的这个`函数（）`的调用。往后如果还有点`.`，它就统统都是`object`的`attribute`和`method`的调用？

希望我描述清楚了。

**Comment by neolee** [comment]
点的含义看它前面是个啥，是个 module 还是个 object，如果不知道可以去 Google 呀，比如看到我 import 了 uuid 这个 module，就可以找到它的文档，看看这个 module 里有些啥，这就是学习。
