### ISSUE TITLE
jupyter lab 运行时不会同时使用命令行

### ISSUE THREAD

**Issue by Gaomingzhao** [neolee/pilot#1086]
“如果在 jupyter lab 运行着的时候你需要命令行界面执行一些任务，只要在 ConEmu 里打开一个新的 tab 就可以了，不用动之前的那个。”

看到老师的教程里是这么写的，但是我搜了下 ConEmu，发现好像只适用于 Windows？macOS 系统下是否也是只要安装使用就好呢

**Comment by neolee** [comment]
macOS 下面的 Terminal 也支持多窗口和多 tab，另开一个 Termnal tab 或者窗口就行了，道理是一样的。

**Comment by onthebus98** [comment]
terminal窗口菜单 -shell--新建窗口---使用描述文件basic新建窗口

**Comment by Gaomingzhao** [comment]
原来如此，谢谢老师和bus
