### ISSUE TITLE
关于 JSON 数据视频课程中的疑问

### ISSUE THREAD

**Issue by xiaoerhai** [neolee/pilot#1087]
如下图：视频当中的格式和我电脑上显示的格式为什么不一样？视频教程中显示的更整洁些，我电脑上显示的更乱一些。
![image](https://user-images.githubusercontent.com/48662601/74586073-bc807e80-501e-11ea-81bc-5cbcb5b330cb.png)

**Comment by neolee** [comment]
因为我的 Chrome 装了一个美化 JSON 显示的插件，你去搜搜 JSON，有不少。

**Comment by xiaoerhai** [comment]
已解决该问题（如下图所示），感谢老师的解答！
![image](https://user-images.githubusercontent.com/48662601/74598079-aa95ee80-50a5-11ea-87a8-f44c271bc77c.png)
