### ISSUE TITLE
scoop 下载的 python 在 VS Code 里面找不到怎么办

### ISSUE THREAD

**Issue by hpy729** [neolee/pilot#1089]
用 `scoop install python` 安装的python，然后装了VS Code，却在**选择解释器**那里找不到python，这该如何是好，这又是为何？感谢大神 @neolee

**Comment by neolee** [comment]
你在命令行里运行 `python -V` 是啥结果？

**Comment by hpy729** [comment]
![image](https://user-images.githubusercontent.com/48587215/74591250-43e6e580-5051-11ea-93a3-e8b39e22c35b.png)

如图，上面搜不到python，下面运行`python -V`正常。

**Comment by neolee** [comment]
你这个给我的感觉是没装 Python 插件？点左边那一列的第五个图片，搜索和安装 Python 插件试试。

**Comment by hpy729** [comment]
确实如此，装了就好了。

可是我在老家的电脑没有要刻意去装这个插件呀，按照你的步骤，打开vs code就会有python可以选择的，奇怪。

**Comment by neolee** [comment]
都要装的，你第一次打开 .py 文件会提示自动安装，可能你选择过安装自己忘了。
