### ISSUE TITLE
在 Jupiter Lab 输入函数 type（） 时无法识别

### ISSUE THREAD

**Issue by lidewen-yue** [neolee/pilot#109]
![image](https://user-images.githubusercontent.com/56989072/67612818-d4ff2b80-f7d8-11e9-925c-2684352a60d9.png)
在

type（）中的（）离左边的函数type隔的很远，导致运行没有结果，但是中间又没有空格，请问这种问题如何解决

**Comment by neolee** [comment]
似乎括号用了中文全角括号，是会出错的。

程序里所有标点符号都要用英文半角，这种 ()
