### ISSUE TITLE
git 命令行中的中文提示怎样修改成英文？

### ISSUE THREAD

**Issue by tsao86** [neolee/pilot#1091]
MAC 系统，尝试使用```echo "alias git='LANG=en_GB git'" >> ~/.bashrc```  和 ```echo "alias git='LANG=en_GB git'" >> ~/.zshrc```,都没有作用，请老师和同学多多指教

**Comment by neolee** [comment]
这个应该是跟着你的系统区域设定的，需要在 System Preferences 的语言设定中，把英文放到中文前面。

**Comment by tsao86** [comment]
已解决，谢谢。
