### ISSUE TITLE
git add 未跟踪的文件输出未匹配任何文件

### ISSUE THREAD

**Issue by tsao86** [neolee/pilot#1092]
输入```git add "vor/\346\234\252\345\221\275\345\220\215.ipynb"```
输出```fatal: 路径规格 'vor/\346\234\252\345\221\275\345\220\215.ipynb' 未匹配任何文件```
<img width="567" alt="屏幕快照 2020-02-16 下午4 10 31" src="https://user-images.githubusercontent.com/49138260/74601228-e4331d80-50d6-11ea-8631-7ba7682477d2.png">
请多指教，谢谢。

**Comment by neolee** [comment]
你那应该是个名字带中文的文件吧？中文文件名会撞到不少坑，需要各个地方都配置好才能正确处理，最简单的办法就是避免用中文文件名。

几个方向可以试试：

1. `git add ` 命令后面直接用中文的文件名，用 git 显示给你的编码之后的文件名肯定是不行的。
2. `git add ` 命令后用 Tab 键补全来自动输入正确的文件名。
3. 使用 Visual Studio Code 里面的 git 图形化界面。

**Comment by tsao86** [comment]
使用第二种方法 用Tab补全解决了，多谢。
