### ISSUE TITLE
git commit 疑问

### ISSUE THREAD

**Issue by tsao86** [neolee/pilot#1093]
mac 环境，已git add 所有S1的学习内容到暂存区域，git commit时出现下面的代码，

```
hint: Waiting for your editor to close the file... code -w: code: command not found
error: There was a problem with the editor 'code -w'.
Please supply the message using either -m or -F option.
```

```code -w``` 是以visual studio code 的形式书写说明，S1的课程是jupiter lab 书写的，是不是这个原因出现的问题，请指教，谢谢。

**Comment by stones-zhang** [comment]
我看git的支线课程中，可以用 git commit -a -m " " 命令，可以直接输入说明内容。你试试

**Comment by tsao86** [comment]
是的，已经解决。谢谢。

**Comment by neolee** [comment]
@tsao86 你在命令行执行 code 命令会怎样？

**Comment by tsao86** [comment]
@neolee 在目录 pilot-student 下执行 ```code``` 
输出 ```-bash: code: command not found```

**Comment by neolee** [comment]
所以你还没没有在 Visual Studio Code 下配置好命令行 code 命令，commit 的时候会调用你配置的 core.editor 来输入提交信息，也就是 `code -w` 这个命令，当然就不会成功。

建议你最好按部就班的从头配置环境，从头学起，把支线课程也好好都看一遍。

**Comment by tsao86** [comment]
找到原因了，今天更改了system preferences 的英语优先，更改一次就需要把Visual Studio Code 下的code命令重新配置一下。多谢李骏老师。
