### ISSUE TITLE
mysql-connector 安装完成后如何进入

### ISSUE THREAD

**Issue by 18p2p** [neolee/pilot#1095]
![KO0TBIFI7~FHE9}W@{1YPT0](https://user-images.githubusercontent.com/48624321/74611998-04e18e80-513c-11ea-9045-828d2e302f24.png)
![4Z$~6R1`JRC%)@%VDVJ D93](https://user-images.githubusercontent.com/48624321/74612065-dca65f80-513c-11ea-9d1f-f045d7465d96.png)

**Comment by neolee** [comment]
你不看教材的么？要尝试这个部分需要先安装配置 MySQL 服务呀。

**Comment by 18p2p** [comment]
晕，老师我把视频都看了，居然忘看教材了
