### ISSUE TITLE
安装nodejs的问题

### ISSUE THREAD

**Issue by sunyunhang1010** [neolee/pilot#1097]
<img width="555" alt="image" src="https://user-images.githubusercontent.com/60560117/74619167-91f20b00-516f-11ea-888e-c9e0fb17bbb6.png">
<img width="572" alt="image" src="https://user-images.githubusercontent.com/60560117/74619192-a0d8bd80-516f-11ea-94d6-09752e928f1c.png">

**Comment by neolee** [comment]
你要安装 nodejs 为啥执行 `brew install code`，code 是什么软件包？

**Comment by sunyunhang1010** [comment]
抱歉老师 打错字母了 。node--code，下次注意。
