### ISSUE TITLE
无法正常安装 scoop

### ISSUE THREAD

**Issue by J-xiaodan** [neolee/pilot#1098]
PS C:\Users\12450> iwr -useb get.scoop.sh | iex
iwr : 基础连接已经关闭: 发送时发生错误。
所在位置 行:1 字符: 1
+ iwr -useb get.scoop.sh | iex
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest]，Web
    Exception
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

**Comment by neolee** [comment]
网络问题。

**Comment by xiao-sky** [comment]
换个网络代理可以解决

**Comment by J-xiaodan** [comment]
https://10beasts.net/rusvpn-free/

**Comment by J-xiaodan** [comment]
上面的连接是可以通过下载插件实现浏览器翻墙，但是我无法打开插件下载连接....

**Comment by neolee** [comment]
那个是给浏览器用的，对命令行没用。另外我们不讨论网络代理问题。此问题关闭。
