### ISSUE TITLE
无法将“code”项识别为 cmdlet、函数...

### ISSUE THREAD

**Issue by Jenny0523** [neolee/pilot#110]
code : 无法将“code”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
![微信图片_20191026104001](https://user-images.githubusercontent.com/48664589/67613181-1b568980-f7dd-11e9-891b-392e3a09cd5a.png)

还有，请问 VSCode 中按 ⌃+N 打开一个新文件，请问在哪里按？谢谢

**Comment by neolee** [comment]
下载运行 Visual Studio Code 安装程序，装好后应该就可以在命令行里使用 code 这个命令了。如果有问题可以试试重启一下 Windows 再试。

“VSCode 中按 ⌃+N 打开一个新文件”，意思是启动 VIsual Studio Code，然后按 Control+N。

**Comment by tiger595** [comment]
重启电脑也不行，是否和 Visual Studio Code 安装路径有关系?

**Comment by tiger595** [comment]
又试了下，可以了。
