### ISSUE TITLE
配置环境 scoop update 失败

### ISSUE THREAD

**Issue by shixiaodu** [neolee/pilot#1100]
![image](https://user-images.githubusercontent.com/59480593/74652308-b9bd8f00-51c0-11ea-8d64-0b7c0fe7053a.png)

请老师帮忙看下，操作到设置scoop的第三步，执行scoop update失败，不知该怎么操作了，请老师指导下，谢谢

**Comment by shixiaodu** [comment]
安装软件包管理工具 Scoop时，执行第三个命令，更新 Scoop 的本地数据库，即
scoop update 
显示失败，请问该怎么解决？

**Comment by neolee** [comment]
网络问题，换网络或者换时间或者挂代理重试。
