### ISSUE TITLE
如何安装这个模块fastnumbers 

### ISSUE THREAD

**Issue by hailinsu** [neolee/pilot#1102]
在conemu中在命令行用 pip install fastnumbers 来安装这个模块吗?
也可以直接在 Jupyter Notebook 中用 ! 来运行这个命令（在一个新的 cell 中输入 !pip install fastnumbers 并运行）。这个操作怎么弄，感觉这个问题不解决，难以进行下去
![image](https://user-images.githubusercontent.com/48571418/74716204-0a88c280-5269-11ea-96ef-89bd336b50b5.png)

**Comment by neolee** [comment]
所以你做了什么？遇到啥问题？
