### ISSUE TITLE
异常了，不知道怎么处理

### ISSUE THREAD

**Issue by hailinsu** [neolee/pilot#1103]
![image](https://user-images.githubusercontent.com/48571418/74727963-f0f17600-527c-11ea-8fe6-e627007c7287.png)
百度过问题，但是因为不知道原理，只是粘贴别人的代码，并不能解决问题，所以问问你。

**Comment by neolee** [comment]
标题很不好，标题应该具体有用，不然看着就没有回答的欲望。

另外你既然搜素过解决方案，那么搜到了啥？为什么没解决问题？什么原理不知道？这些不能具体说说么？懒得写？那为什么别人要费事来回答你呢？

最后，提问题之前可以先搜索下 issues，很多都是提过的老问题，比如你这个，可以参考  #627  和 #728
