### ISSUE TITLE
Scoop 安装不成功

### ISSUE THREAD

**Issue by Yixin2020** [neolee/pilot#1104]
PS C:\Users\xinyi18> iwr -useb get.scoop.sh | iex
iwr : 基础连接已经关闭: 发送时发生错误。
所在位置 行:1 字符: 1
+ iwr -useb get.scoop.sh | iex
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest]，WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

**Comment by neolee** [comment]
网络问题，换网络或者换时间或者挂代理试试。

**Comment by pengdong2020** [comment]
加我QQ 发你一个加速器 我也遇到过类似问题

**Comment by pengdong2020** [comment]
我的QQ 258346685
