### ISSUE TITLE
tree 树的章节，find 功能如何解决找不到的情况？

### ISSUE THREAD

**Issue by sxuya** [neolee/pilot#1105]
## 递归寻找中，怎么完成「查无此项」的功能

自己想到的方法，得到的结果不是正常的，不知道代码再如何修改。

想要的效果是：当历遍 Tree 里面所有的内容，没有找到对应项，打印「not find」的文字。

### 结果
返回了很多「not find」。

## 具体 code

Version 1：
```python
def find(self, name):
    for child in self.children:
        if child.name == name:
            print(child.data['tag'])
        child.find(name)
```
如下测试代码
```python
root.find('浙江')  # 第一层是 root，这个是第二层（省份）的一个
root.find('小区2')  # 这个是第三层的随便的内容
root.find('bala') # 这个是没有的，
```
的结果是：
```python
a4
c112
```
第三个没有的内容没有类似「not find」的提示。

---

Version 2：
```python
    def find(self, name, notfind = True):
        notfindbool = notfind
        for child in self.children:
            if child.name == name:
                print(child.data['tag'])
                notfindbool = False
            child.find(name, notfindbool)
        if notfindbool:
            print('not find')
```
同样的测试代码，得到的结果是：
```python
...
not find
not find
not find
a4
c112
not find
not find
...
```
前后有很多「not find」

---
## all code
```python
class TreeNode:
    def __init__(self, name='root', data=None, parent=None, children=None):
        self.name = name
        self.data = data
        
        if parent:  # 这里是根节点的特点
            assert isinstance(parent, TreeNode)
            parent.add_child(self)
        self.parent = parent  # 这个是第二次没有想到的
            
        self.children = []
        if children:  # 这里是最后一片叶子的特点。头、尾是有单独的特点的。
            for child in children:
                assert isinstance(child, TreeNode)  # 这个是我结合上面 parent 的特点，添加上去的。
                self.add_child(child)
    
    def add_child(self, node):
        assert isinstance(node, TreeNode)
        node.parent = self
        self.children.append(node)
    
    def add_children(self, nodes):
        for node in nodes:
            assert isinstance(node, TreeNode)
        for node in nodes:
            node.parent = self
            self.children.append(node)
    
    def remove(self, node):
        node.parent = None
        self.children.remove(node)
    
    def move(self, node, new_parent):
        node.parent.remove(node)
        node.parent = new_parent
        new_parent.add_child(node)

    def find(self, name, notfind = True):
        notfindbool = notfind
        for child in self.children:
            if child.name == name:
                print(child.data['tag'])
                notfindbool = False
            child.find(name, notfindbool)
        if notfindbool:
            print('not find')
    
    def _print_tree(self, _prefix='', _last=True):
        print(''.join([_prefix, '┗━━' if _last else '┣━━', self.name]))
        _prefix += '   ' if _last else '┃  '
        count = len(self.children)
        for n, node in enumerate(self.children):
            _last = n==(count-1)
            node._print_tree(_prefix, _last)
            
    def print_tree(self):
        print(self.name)
        for node in self.children[:-1]:
            node._print_tree(_last = False)
        self.children[-1]._print_tree(_last=True)
        
root = TreeNode('中国', {'name':'习近平', 'age':5000, 'capitals':'Beijing'})

a1 = TreeNode('北京', {'tag':'a1', 'name':'BeiJing', 'age':18, 'level':1})
a2 = TreeNode('上海', {'tag':'a2', 'name':'ShangHai', 'age':17, 'level':1})
a3 = TreeNode('广东', {'tag':'a3', 'name':'GuangZhou', 'age':10, 'level':1})
a4 = TreeNode('浙江', {'tag':'a4', 'name':'ShenZhen', 'age':8, 'level':1})
a5 = TreeNode('天津', {'tag':'a5'})

root.add_children([a1, a2, a3, a4, a5])
b11 = TreeNode('朝阳区', {'tag':'b11', 'name':'chaoyangqu', 'number':1000})
b12 = TreeNode('海淀区', {'tag':'b12', 'name':'haidingqu', 'number':1200})
b13 = TreeNode('天安门', {'tag':'b13', 'name':'tianojmenqu', 'number':0})

b21 = TreeNode('浦东区', {'tag':'b21', 'name':'hongqiao', 'number':900})
b22 = TreeNode('蒲西区', {'tag':'b22', 'name':'nanjinglu', 'number':800})
b23 = TreeNode('南京路', {'tag':'b23', 'name':'pudongqu', 'number':999})

b31 = TreeNode('广州', {'tag':'b31', 'name':'yuexiu', 'number':2000})
b32 = TreeNode('深圳', {'tag':'b32', 'name':'tianhe', 'number':1900})
b33 = TreeNode('东莞', {'tag':'b33', 'name':'liwan', 'number':1500})

b41 = TreeNode('杭州', {'tag':'b41', 'name':'huaweiqu', 'number':300})
b42 = TreeNode('宁波', {'tag':'b42', 'name':'tencent', 'number':251})
b43 = TreeNode('温州', {'tag':'b43', 'name':'dajiang', 'number':120})

c111 = TreeNode('小区1', {'tag':'c111', 'xcvh':'vhbhxn', 'fuxcvh':'xcm;'})
c112 = TreeNode('小区2', {'tag':'c112', 'hbqnvugr':'days', 'fuhbqnvugr':'xcys'})

a1.add_children([b11, b12, b13])
b11.add_children([c111, c112])
a2.add_children([b21, b22, b23])
a3.add_children([b31, b32, b33])
a4.add_children([b41, b42, b43])
```

**Comment by neolee** [comment]
我的解决方案是这样的，你可以尝试理解一下：

```python
class TreeNode:
    ...
    def find(self, name):
        if self.name == name:
            return self
        
        for node in self.children:
            t = node.find(name)
            if t:
                return t
        else:
            return None
    ...

if __name__ == '__main__':
    root = TreeNode()
    a = TreeNode(name='A', parent=root)
    a1 = TreeNode(name='A1', parent=a)
    a2 = TreeNode(name='A2', parent=a)
    a21 = TreeNode(name='A21', parent=a2)
    a22 = TreeNode(name='A22', parent=a2)
    b = TreeNode(name='B', parent=root)
    c = TreeNode(name='C', parent=root)
    c1 = TreeNode(name='C1')
    c2 = TreeNode(name='C2')
    c.add_child(c1)
    c.add_child(c2)
    c21 = TreeNode(name='C21', parent=c2)
    c22 = TreeNode(name='C22', parent=c2)

node = root.find('A22')
if node:
    print('Found', node.name)
else:
    print('Not found')
```

**Comment by sxuya** [comment]
> 我的解决方案是这样的，你可以尝试理解一下：
> 
> ```python
> class TreeNode:
>     ...
>     def find(self, name):
>         if self.name == name:
>             return self
>         
>         for node in self.children:
>             t = node.find(name)
>             if t:
>                 return t
>         else:
>             return None
>     ...
> 
> # Testing
> if __name__ == '__main__':
>     root = TreeNode()
>     a = TreeNode(name='A', parent=root)
>     a1 = TreeNode(name='A1', parent=a)
>     a2 = TreeNode(name='A2', parent=a)
>     a21 = TreeNode(name='A21', parent=a2)
>     a22 = TreeNode(name='A22', parent=a2)
>     b = TreeNode(name='B', parent=root)
>     c = TreeNode(name='C', parent=root)
>     c1 = TreeNode(name='C1')
>     c2 = TreeNode(name='C2')
>     c.add_child(c1)
>     c.add_child(c2)
>     c21 = TreeNode(name='C21', parent=c2)
>     c22 = TreeNode(name='C22', parent=c2)
> 
>     node = root.find('A22')
>     if node:
>         print('Found', node.name)
>     else:
>         print('Not found')
> ```

```def find() ```里面最后一个 else 是跟着第一个 if 么？如果是这样的话，那么中间的 for 是跟着谁呢？这个顺序无法理解。

**Comment by sxuya** [comment]
> 我的解决方案是这样的，你可以尝试理解一下：
> 
> ```python
> class TreeNode:
>     ...
>     def find(self, name):
>         if self.name == name:
>             return self
>         
>         for node in self.children:
>             t = node.find(name)
>             if t:
>                 return t
>         else:
>             return None
>     ...
> 
> # Testing
> if __name__ == '__main__':
>     root = TreeNode()
>     a = TreeNode(name='A', parent=root)
>     a1 = TreeNode(name='A1', parent=a)
>     a2 = TreeNode(name='A2', parent=a)
>     a21 = TreeNode(name='A21', parent=a2)
>     a22 = TreeNode(name='A22', parent=a2)
>     b = TreeNode(name='B', parent=root)
>     c = TreeNode(name='C', parent=root)
>     c1 = TreeNode(name='C1')
>     c2 = TreeNode(name='C2')
>     c.add_child(c1)
>     c.add_child(c2)
>     c21 = TreeNode(name='C21', parent=c2)
>     c22 = TreeNode(name='C22', parent=c2)
> 
>     node = root.find('A22')
>     if node:
>         print('Found', node.name)
>     else:
>         print('Not found')
> ```

明白了，是使用 ```for ... else...``` 的方法，不是 ```if ... else ...``` 的语法。难怪我用 ```if ... else ...``` 的逻辑方法怎么也想不来怎么实现「找不到」的方法。

---

使用的搜索关键词是「python if for else」，然后 Google 就显示出「for else」的结果连接。虽然看标题感觉缺少「if」，但是总感觉是有关联，果然，Python 里面好多技巧需要积累。

**Comment by neolee** [comment]
其实不用 `for...else` 也可以写出来，关键不是这个；你还需要仔细体会下，看我给你的代码和你的代码的真正本质区别在哪。

**Comment by sxuya** [comment]
> 其实不用 `for...else` 也可以写出来，关键不是这个；你还需要仔细体会下，看我给你的代码和你的代码的真正本质区别在哪。

--- 

我先一点点攻克，for……else…… 的逻辑搞蒙了：

如果一棵树是：root 下面是 A、B、C，A 下面是 A1、A2、A3。

当使用 ```root.find(B)``` 的时候，

第一次迭代的路径是 root - A - A1，当到 A1 的时候，A1 的 children 是空的 list，那这时候执行 code 的时候，for 循环是在空的 list 上运行，相当于过去、到了 else 这部分，那么不是应该直接抛出了 None，code 结束。

但是，真正的却是在继续执行 A2 的部分？

**Comment by neolee** [comment]
`return None` 只是结束了一层循环，上一层的循环还在继续，所以继续处理 A2。
