### ISSUE TITLE
TypeError: 'itertools.islice' object is not callable

### ISSUE THREAD

**Issue by malicklin** [neolee/pilot#1107]
def fib():
    prev, curr = 0, 1
    while True
        yield curr
        prev, curr = curr, prev + curr

f = fib()
list(islice(f, 0, 10))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-43-83182258253e> in <module>
      7 
      8 f = fib()
----> 9 list(islice(f, 0, 10))

TypeError: 'itertools.islice' object is not callable

字面理解itertools 模块的islice 无法调用。误以为自己拼写错误，即便重新粘贴代码无解。
再次之前的学习用书代码可运行，请老师指点，谢谢！

**Comment by neolee** [comment]
请贴完整的代码。

**Comment by malicklin** [comment]
上面那段代码是改写之前的fib()定义，
课程原文如下：

”One More Thing...
不知道你有没有在书写上面的代码时觉得每次要定义个 class 还有 __iter__() __next__() 这样的“八股”很啰嗦？恭喜你，很有优秀程序员的潜质，事实上上面代码里真正有价值的就是 __next__() 的实现部分，所以 Python 提供了一种特殊的迭代器（iterator ）写法，叫做“生成器（generator）”，更紧凑更精简。比如上面的 Fibonacci 数列，用生成器来写就是这样的：
def fib():
    prev, curr = 0, 1
    while True:
        yield curr
        prev, curr = curr, prev + curr

f = fib()
list(islice(f, 0, 10)) 

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-50-d839ff199b7c> in <module>
      8 
      9 f = fib()
---> 10 list(islice(f, 0, 10))

TypeError: 'itertools.islice' object is not callable

一直在找原因..

**Comment by neolee** [comment]
我让你贴你的完整代码，你贴教材的内容有啥用啊……

**Comment by malicklin** [comment]
抱歉，我还在学习教材。。没有写自己一段完整代码，后来重新启用jupyter lab之后，问题突然就解决了。。多谢老师！

**Comment by neolee** [comment]
然后你就没搞清楚什么时候会出错，浪费了一次学习的机会……

你碰到的情况多半是你曾经有意或者无意的执行了类似 `islice = ...` 这样的语句，使得 `islice` 变成了别的东西（而不是一个你引入的函数）。
