### ISSUE TITLE
busybox 一直安装不成

### ISSUE THREAD

**Issue by hpy729** [neolee/pilot#1108]
scoop install busybox一直安装不成功，是网络问题，但挂了代理也不行，气死了，找遍了搜索引擎没有其他途径，老师有没办法帮助！~

**Comment by hpy729** [comment]
@neolee 研究了一下，看到有些人在github建源，我建议老师也整一个，我们就好下载了~-.-

**Comment by neolee** [comment]
既然你已经研究了一下，为啥你不建个源给大家用呢？

**Comment by hpy729** [comment]
是个好主意，但是，，，`（此处是个哭脸）`感觉能力不足也，，
