### ISSUE TITLE
怎样根据操作系统部署代码

### ISSUE THREAD

**Issue by jiangsv** [neolee/pilot#1109]
老师，如果我们写了一个python的文件，需要在mac和windows环境下都可以使用。是否可以通过什么库来获取操作系统的信息，通过if语来调整代码里的换行符和PATH。或者直接写两份代码？一般的做法是什么呢？

**Comment by neolee** [comment]
大多数情况下，只要你使用的方法得当，是不需要这样做的，Python 有大量的库本身就是跨平台的。

所以要看你具体想做什么。

**Comment by jiangsv** [comment]
我最近写了一个读取Excel数据（题库），然后生成文本（试卷）写入word文档的脚本。
涉及的问题有:
若从运行程序的文件夹转到数据存放的文件夹，写路径时就会因为系统差异而有所不同,如：
`os.chdir(r"/Users/xxx/xxx)`
还有一个是`\n`,`\n\r`的问题。好在系统会自动转换，一般情况下运行是正常的，但是否会在特定情况下会报错甚至运行时不报错但会在parsing的时候，生成错误的文本呢？

**Comment by neolee** [comment]
噢，操作文件的这个，下周就会讲。如果你使用 `pathlib` 就不会有这个问题了。

**Comment by jiangsv** [comment]
谢谢老师
