### ISSUE TITLE
获取你的学习用书

### ISSUE THREAD

**Issue by hailinsu** [neolee/pilot#111]
在最后有一个空格，在空格前面粘贴你前面拷贝的repo的地址，不知道在哪里输入，然后出错了，您看一下哪儿有问题
![K 8}G59TA%Z30U3$YRKW}5C](https://user-images.githubusercontent.com/48571418/67614533-3cc17080-f7f1-11e9-84d8-669e7f6a964a.png)

**Comment by neolee** [comment]
你要运行的是这么个命令：`git clone 把你拷贝的地址贴在这里`。

另外，你需要 fork 我们的学习用书仓库 https://github.com/neolee/pilot-student

然后 clone 你 fork 的那个仓库。

**Comment by hailinsu** [comment]
![0)6Z{SHH9MV`IJM${3D$6H5](https://user-images.githubusercontent.com/48571418/67615856-dd209080-f803-11e9-9f54-06042560ed2f.png)
这样是获取学习用书成功了吗

**Comment by neolee** [comment]
成了！
