### ISSUE TITLE
访问 SQLIte 数据库出错

### ISSUE THREAD

**Issue by fangmenghuohuo1019** [neolee/pilot#1110]
老师，您好，我输入代码后显示这样，检查了几遍觉得没问题，还是不行，请问我哪里出错了，谢谢。

![image](https://user-images.githubusercontent.com/61229661/74822934-dc76b180-5340-11ea-9c61-8751fb67f7da.png)

**Comment by neolee** [comment]
最好不要在标题里写一大堆东西，标题应该言简意赅。我帮你做了修改，你体会下。

这个问题看上去是数据文件有问题，可以办你的数据文件作为附件贴上来吗？

**Comment by fangmenghuohuo1019** [comment]
李老师，我把数据文件重新下载了下，现在可以访问了，谢谢您。
