### ISSUE TITLE
"no value for argument" or “SyntaxError: invalid syntax” for Primes programs

### ISSUE THREAD

**Issue by tyler1zhang** [neolee/pilot#1111]
李老师，我尝试运行这个Python文件发现两个error，如果我使用 `lst = list(islice(primes(), 0, 100000))` ,会出现`“no value for argument”`
![image](https://user-images.githubusercontent.com/49228317/74830217-996f0b00-534d-11ea-882b-63d2e3fef751.png)

如果我把这句改成
`lst = list(primes(100000))` 就会出现 `“SyntaxError: invalid syntax”`
![image](https://user-images.githubusercontent.com/49228317/74830403-07b3cd80-534e-11ea-979e-e4f6b7a8a7d6.png)

所有的code如下：
![image](https://user-images.githubusercontent.com/49228317/74830696-afc99680-534e-11ea-8cf8-1f18278d0f1b.png)

**Comment by jiangsv** [comment]
第一个写法：
`lst = list(islice(primes(), 0, 100000))`, primes()里面没给参数。你可以看看`__init__`里面是需要`nlimt`的。
同理第二个`islice()`函数也缺少参数。
可以写成这样，取10000里的前10的素数
``` python
lst = list(islice(primes(10000), 0, 10)
```

**Comment by tyler1zhang** [comment]
谢谢，我试了一下，还有个关键的错误在25行， 应该是`elif self.is_prime[n]:`， 而不是`elif self.is_prime(n):`
不过老师在12月31号的课程中，`primes()`里面就没有argument, 不懂为啥没有Error。
![image](https://user-images.githubusercontent.com/49228317/74832825-25cffc80-5353-11ea-8b18-c8374fa5a678.png)

**Comment by neolee** [comment]
@tyler1zhang 你原问题的第一个错误是你的 primes 类实例化需要一个参数（前面 @jiangsv 同学说的很对）；第二个问题则是你出错的前一行少了一个反括号。

你最后问的是我上课讲的例子，我一共讲了四个不同版本的实现，其中第一个（mk1.py）的类实例化是不需要参数的，第二个（mk2.py）则是需要的。你在体会下 @jiangsv 同学说的。
