### ISSUE TITLE
请问为什么 return 返回后面不用加冒号

### ISSUE THREAD

**Issue by PanChuang2019** [neolee/pilot#1112]

**Comment by neolee** [comment]
请问它为什么要加冒号？

**Comment by PanChuang2019** [comment]
![maohao](https://user-images.githubusercontent.com/48653618/74838189-186c3f80-535e-11ea-865b-6b149e129f86.png)  好吧，我思考了一下，冒号后面应该是要说明一些什么东西；如果没有说明什么的话，理论上就不用加冒号，类似print ，return这些。我的理解对吗，老师。

**Comment by neolee** [comment]
编程语言有自己的语法规则，该有的地方就要有，不能有的地方就不能有。
