### ISSUE TITLE
for 循环下的 if else 语句

### ISSUE THREAD

**Issue by Gaomingzhao** [neolee/pilot#1113]
以下两个代码的区别在于，后者多了一个 else。

从运行结果上来看，前者出现了很多重复值。为什么会产生这种现象，百思不得其解，想请教一下李骏老师。

```python
for n in range(2, 100):

    if n == 2:
        print(n)
        continue

    for i in range(2, n):

        if (n % i) == 0:
            break

        print(n)
```

```python
for n in range(2, 100):

    if n == 2:
        print(n)
        continue

    for i in range(2, n):

        if (n % i) == 0:
            break

    else:               
        print(n)
```

**Comment by Zhang-Jinlei** [comment]
@Gaomingzhao 因为你第一个 print(n) 在for循环的嵌套里，也就是说只要当前的这个 n 对 从 2 到 n-1 的这些数不能整除，当前的这个 n 的值都会被重复打印出来，所以，有了很多重复值。

而下面这种，是只有在 “for i in range(2, n)” 执行完了之后并且没有被 break 的情况下，才会顺序执行下面的 print(n)。

我是通过 debug( 逮 bug)，单步执行一下就整明白了。

**Comment by Zhang-Jinlei** [comment]
@Gaomingzhao 
![Snip20200220_1](https://user-images.githubusercontent.com/28210665/74901393-b4895b80-53dd-11ea-8dc6-ad3d6aca1e58.png)

你看，第一个 for 循环 n = 5，第二个 for 循环 i 从 = 2 开始，只要 5 不能 整除 2 或 3 或 4，都会打印 5。有几个就会重复打印几遍 5。

**Comment by Gaomingzhao** [comment]
> @Gaomingzhao
> ![Snip20200220_1](https://user-images.githubusercontent.com/28210665/74901393-b4895b80-53dd-11ea-8dc6-ad3d6aca1e58.png)
> 
> 你看，第一个 for 循环 n = 5，第二个 for 循环 i 从 = 2 开始，只要 5 不能 整除 2 或 3 或 4，都会打印 5。有几个就会重复打印几遍 5。

你这么说我大致能理解，一开始我也是根据运行结果这么猜想的，但是我这边 n = 9 的时候，运行结果里 9 为什么只出现了1次呢，照理说也应该出现很多次啊。

还有就是，突然发现，这个程序是无法满足「输出所有质数」这个要求的...

**Comment by Zhang-Jinlei** [comment]
@Gaomingzhao 

那是因为第二个 for 循环，当 n = 9，i = 3 的时候，break 了。而之前 i = 2 打印了一次，所以就只显示一次。

我之前的回复也说了“并且没有被 break 的情况下”。

至于，『能否输出所有素数』这个我倒是没有在意。

**Comment by Gaomingzhao** [comment]
> @Gaomingzhao
> 
> 那是因为第二个 for 循环，当 n = 9，i = 3 的时候，break 了。而之前 i = 2 打印了一次，所以就只显示一次。
> 
> 我之前的回复也说了“并且没有被 break 的情况下”。
> 
> 至于，『能否输出所有素数』这个我倒是没有在意。

有道理。谢谢。后面这个我再想想

**Comment by neolee** [comment]
@Zhang-Jinlei 同学已经说得很清楚了。

@Gaomingzhao 你需要学到的有几个点：
1. 单步调试（debugging）很有用，讲 Visual Studio Code 的那一期支线课程里有说怎么做。
2. `for...else` 的语法含义要理解清晰，@Zhang-Jinlei 同学表述很精确。如果理解不清楚可以不用，有替代办法。
3. 我帮你改了下顶楼的代码块，Markdown 标记整块代码的正确语法是我帮你改的，你可以点编辑看看。

**Comment by Gaomingzhao** [comment]
> @Zhang-Jinlei 同学已经说得很清楚了。
> 
> @Gaomingzhao 你需要学到的有几个点：
> 
> 1. 单步调试（debugging）很有用，讲 Visual Studio Code 的那一期支线课程里有说怎么做。
> 2. `for...else` 的语法含义要理解清晰，@Zhang-Jinlei 同学表述很精确。如果理解不清楚可以不用，有替代办法。
> 3. 我帮你改了下顶楼的代码块，Markdown 标记整块代码的正确语法是我帮你改的，你可以点编辑看看。

谢谢老师，我继续补课
