### ISSUE TITLE
网络问题

### ISSUE THREAD

**Issue by pengdong2020** [neolee/pilot#1114]
PS C:\Users\apple> iwr -useb get.scoop.sh | iex
iwr : 基础连接已经关闭: 发送时发生错误。
所在位置 行:1 字符: 1
+ iwr -useb get.scoop.sh | iex
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:
   HttpWebRequest) [Invoke-WebRequest]，WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.Power
   Shell.Commands.InvokeWebRequestCommand

PS C:\Users\apple> iwr -useb get.scoop.sh | iex
iwr :
 500 Internal Privoxy Error

500 Internal Privoxy Error
Privoxy encountered an error while processing your request:
Could not load template file no-server-data or one of its included component
s.
Please contact your proxy administrator.
If you are the proxy administrator, please put the required file(s)in the (c
onfdir)/templates directory.  The location of the (confdir) directory is spe
cified in the main Privoxy config file.  (It's typically the Privoxy install
 directory).
所在位置 行:1 字符: 1
+ iwr -useb get.scoop.sh | iex
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:
   HttpWebRequest) [Invoke-WebRequest]，WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.Power
   Shell.Commands.InvokeWebRequestCommand
PS C:\Users\apple>

**Comment by pengdong2020** [comment]
问题已经解决了，哈哈 ， 是加速器线路选择错误，换成米国就好了，然后过程中多重头来几次就好，（如果第一次或者第二次安装到一半，进行不下去了，记得把原来的删掉，才能重头再来）

**Comment by neolee** [comment]
不要重复发相同问题。
