### ISSUE TITLE
网络配置问题

### ISSUE THREAD

**Issue by pengdong2020** [neolee/pilot#1115]
Windows PowerShell
版权所有 (C) Microsoft Corporation。保留所有权利。

PS C:\Users\apple> iwr -useb get.scoop.sh | iex
iwr : 无法连接到远程服务器
所在位置 行:1 字符: 1
+ iwr -useb get.scoop.sh | iex
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:
   HttpWebRequest) [Invoke-WebRequest]，WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.Power
   Shell.Commands.InvokeWebRequestCommand

PS C:\Users\apple> scoop list
Installed apps:

  7zip  *failed*
  git  *failed*

PS C:\Users\apple> scoop install git
Scoop uses Git to update itself. Run 'scoop install git' and try again.
ERROR It looks like a previous installation of git failed.
Run 'scoop uninstall git' before retrying the install.
WARN  'git' () is already installed.
Use 'scoop update git' to install a new version.
PS C:\Users\apple> scoop update
Scoop uses Git to update itself. Run 'scoop install git' and try again.
PS C:\Users\apple>

**Comment by Yixin2020** [comment]
> Windows PowerShell
> 版权所有 (C) Microsoft Corporation。保留所有权利。
> PS C:\Users\apple> iwr -useb get.scoop.sh | iex
> iwr : 无法连接到远程服务器
> 所在位置 行:1 字符: 1
> 
> iwr -useb get.scoop.sh | iex
> 
>   + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:
>  HttpWebRequest) [Invoke-WebRequest]，WebException
>   + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.Power
>  Shell.Commands.InvokeWebRequestCommand
> 
> 
> 
> 
> PS C:\Users\apple> scoop list
> Installed apps:
> 7zip  failed
> git  failed
> PS C:\Users\apple> scoop install git
> Scoop uses Git to update itself. Run 'scoop install git' and try again.
> ERROR It looks like a previous installation of git failed.
> Run 'scoop uninstall git' before retrying the install.
> WARN  'git' () is already installed.
> Use 'scoop update git' to install a new version.
> PS C:\Users\apple> scoop update
> Scoop uses Git to update itself. Run 'scoop install git' and try again.
> PS C:\Users\apple>

我刚碰到并解决这个问题，确实是网络不行。尝试代理啥的都困扰我好几天。结果今早5点起来，人少没人用的时候安装，就安装成功了。祝你好运

**Comment by pengdong2020** [comment]
哦哦 太感谢了------------------ 原始邮件 ------------------
发件人: "Yixin2020"<notifications@github.com>
发送时间: 2020年2月20日(星期四) 下午4:05
收件人: "neolee/pilot"<pilot@noreply.github.com>;
抄送: "pengdong2020"<258346685@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [neolee/pilot] 新手最新问题，网络配置不行，那么怎么配置，使用加速器也不行 (#1115)


 
Windows PowerShell
 版权所有 (C) Microsoft Corporation。保留所有权利。
 PS C:\Users\apple> iwr -useb get.scoop.sh | iex
 iwr : 无法连接到远程&#x670D;务器
 所在位置 行:1 字符: 1
 
iwr -useb get.scoop.sh | iex
  
CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:
 HttpWebRequest) [Invoke-WebRequest]，WebException
 
FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.Power
 Shell.Commands.InvokeWebRequestCommand
  
PS C:\Users\apple> scoop list
 Installed apps:
 7zip  failed
 git  failed
 PS C:\Users\apple> scoop install git
 Scoop uses Git to update itself. Run 'scoop install git' and try again.
 ERROR It looks like a previous installation of git failed.
 Run 'scoop uninstall git' before retrying the install.
 WARN  'git' () is already installed.
 Use 'scoop update git' to install a new version.
 PS C:\Users\apple> scoop update
 Scoop uses Git to update itself. Run 'scoop install git' and try again.
 PS C:\Users\apple>
  
我刚碰到并解决这个问题，确实是网络不行。尝试代理啥的都困扰我好几天。结果今早5点起来，人少没人用的时候安装，就安装成功了。祝你好运
 
&mdash;

**Comment by pengdong2020** [comment]
找到原因了 是我的加速器 线路选择不对，从台湾换到米国就好了

**Comment by pengdong2020** [comment]
哈哈 谢谢 李俊老师帮修改 标题  以后注意
