### ISSUE TITLE
数据和数据库 JSON 一节中输出不一致问题

### ISSUE THREAD

**Issue by qingyix** [neolee/pilot#1117]
![1](https://user-images.githubusercontent.com/48583363/74917429-6fc3eb80-5402-11ea-8926-8ee7f0213c08.JPG)
虽然可正常显示，但是和老师教材中显示的结果不一样。
![2](https://user-images.githubusercontent.com/48583363/74917580-ae59a600-5402-11ea-8ad6-b6d3fe3f3cfc.JPG)

**Comment by neolee** [comment]
这个正常呀，人家是个电商网站，商品经常会变的。
