### ISSUE TITLE
访问CSV文件报错

### ISSUE THREAD

**Issue by fangmenghuohuo1019** [neolee/pilot#1118]
老师，您好，我输入 gdp = pd.read_csv('assets/gdp.csv',skiprows=4)，执行代码时，显示gdp.csv不存在。

![image](https://user-images.githubusercontent.com/61229661/74926463-e23bc800-5410-11ea-8b6e-b6f4a6d5e2e1.png)
![image](https://user-images.githubusercontent.com/61229661/74926478-e962d600-5410-11ea-92f9-e052315246e7.png)

**Comment by neolee** [comment]
1. 错误提示里显示的是找不到 moma-artists.csv？

2. 你的这个 notebook 为啥放在 assets 目录下？这样就和数据文件在一个目录下了，你那个相对路径就不对了。

**Comment by fangmenghuohuo1019** [comment]
![image](https://user-images.githubusercontent.com/61229661/75005183-8cb2fa00-54a8-11ea-9c8f-c86e44123abf.png)
![image](https://user-images.githubusercontent.com/61229661/75005193-95a3cb80-54a8-11ea-97be-8b5b8502a535.png)
![image](https://user-images.githubusercontent.com/61229661/75005287-e6b3bf80-54a8-11ea-9db4-d93818590c2f.png)
老师，我把notebook调出了，专门建了文件夹notebook，统一归放在里面，与assets不在一个目录下了，执行代码后，还是不行，请老师指导下，谢谢。

**Comment by neolee** [comment]
你的 notebook 所在的目录是你的“当前工作目录”，简称 CWD，那么你的 CSV 文件要放在 CWD 下的 `assets` 子目录下。

你写了 `pd.read_csv('assets/gdp.csv', skiprows=4)` 这样的代码，就要理解其中的 `'assets/gdp.csv'` 是什么意思呀，不然只是照着写一遍，并不是学习（虽然也是其中的一个步骤）。

从第一课开始我就一直讲，学编程是和计算机交朋友，搞懂你和它说了啥，它有对你说了啥。如果不能向着这个方向前进，会很艰难。

你在尝试的是一个很进阶的支线课程，如果基础不扎实，意义并不大。
