### ISSUE TITLE
运行scoop update failed

### ISSUE THREAD

**Issue by tiger595** [neolee/pilot#112]
PS C:\Users\Administrator> scoop update
Updating Scoop...
efrror: RPC failed; curl 56 OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 10054
fatal: the remote end hung up unexpectedly
atal: early EOF
fatal: index-pack failed
Scoop update failed.

**Comment by neolee** [comment]
网络问题，多试几次或者换网络或者挂代理。

**Comment by zouwenxi** [comment]
运行“scoop upddate”出错，是哪里没做对呢？

**Comment by zouwenxi** [comment]
运行“scoop upddate”出错，是哪里没做对呢？
