### ISSUE TITLE
这是电脑本身出毛病了吗？

### ISSUE THREAD

**Issue by tinalll12** [neolee/pilot#1122]
![1](https://user-images.githubusercontent.com/57087700/74998106-d0026e00-5492-11ea-93e0-0fda13f7bbd9.jpg)
![2](https://user-images.githubusercontent.com/57087700/74998112-d395f500-5492-11ea-97de-e83f7031a092.jpg)
如图，我输入的这个程序，电脑的两次输出不一样，试了几次也是不一样，请问老师，这是我自己电脑的问题吗？

**Comment by neolee** [comment]
你碰到的现象是，每次运行下面代码都是上述两种结果之一随机出现？还是目前总是出后一个结果？

```python
n = 0
while n < 5:
    print(n)
    n += 1
```
