### ISSUE TITLE
老师能帮我看下，为什么这个运算结果是这个？跟我想的不一样啊

### ISSUE THREAD

**Issue by lori1989** [neolee/pilot#1124]
![image](https://user-images.githubusercontent.com/60845641/75001563-ba924180-549c-11ea-9dbc-9c577cbdfb3b.png)

**Comment by neolee** [comment]
你为啥用这样的工具？为啥不按照环境配置指南来呢？Python 的版本也不是课程要求的。

如果你按照环境配置来，就可以学习支线课程里关于 Visual Studio 的那一节，然后自己尝试单步 debug，搞清你的程序一步一步是怎么执行的，每一步之后各个变量等于多少。

还有你的问题，能不能说清楚你认为应该是啥结果，实际结果哪里不一样了。这些都懒得写的话，别人怎么猜呢？别人又为啥要费力来回答你呢？

**Comment by lori1989** [comment]
> 你为啥用这样的工具？为啥不按照环境配置指南来呢？Python 的版本也不是课程要求的。
> 
> 如果你按照环境配置来，就可以学习支线课程里关于 Visual Studio 的那一节，然后自己尝试单步 debug，搞清你的程序一步一步是怎么执行的，每一步之后各个变量等于多少。
> 
> 还有你的问题，能不能说清楚你认为应该是啥结果，实际结果哪里不一样了。这些都懒得写的话，别人怎么猜呢？别人又为啥要费力来回答你呢？

谢谢老师指正，我确实没有表达清楚！1.用这个软件的原因是因为，环境配置过程中出现问题，我无法解决，需要换系统，我又不太会弄，于是退了求其次，就先学程序了。
2.关于这个问题，我认为如果输入12的话，print（count）的结果应该是12+1=13啊
print（myInt）的话，因为12%2=6.0余0不等于1，所以应该执行：myInt=myInt-1,应该等于11，不知道为什么运行结果会是这个数字？

**Comment by neolee** [comment]
仍然建议你按照指南搭建环境，遇到问题可以解决，不然效率很低，类似这样的问题完全可以自己解决。另外，问具体代码的问题，就把代码贴出来，这样别人也可以 copy 你的代码去测试，像你这样扔个截图，别人可能还要动手把你的代码输入一遍来验证，你觉得麻烦不？

具体到你的问题，有几个点请你注意：

1. 你的代码是放在 `while` 循环中的，在被操作的那个数（`myInt`）大于 0 之前会循环执行，所以并不像你想的执行一次就出结果；
2. 每循环一次，`count = count + 1`，所以 count 最终会是循环执行的次数，为啥你认为应该是 12+1？
3. `%` 是整除运算符，`12 % 2` 的值是整数 6，不是浮点数 `6.0`。

最后，你的代码中如果数值为奇数就执行 `myInt / 2`，这会返回一个小数，`myInt` 就不再是一个 `int` 了，这是你的本意吗？据我所知，有一道数学题，其大意是：

> 取一个自然数 n，如果它是偶数就除以 2，如果是奇数就减去 1，对结果继续执行上述操作，证明照此反复执行下去最后都会变成 1，并进一步研究操作次数和原始 n 之间的关系。

如果你是在研究这个问题，那么你的实现错误的地方可就多了。

综上所述，你没有搭建一个好的编程和学习环境，课程 S1 的基础知识也没学好。建议还是按部就班的去围绕课程学习和练习，否则这就是我能给你提供的最后一次帮助。

**Comment by lori1989** [comment]
> 仍然建议你按照指南搭建环境，遇到问题可以解决，不然效率很低，类似这样的问题完全可以自己解决。另外，问具体代码的问题，就把代码贴出来，这样别人也可以 copy 你的代码去测试，像你这样扔个截图，别人可能还要动手把你的代码输入一遍来验证，你觉得麻烦不？
> 
> 具体到你的问题，有几个点请你注意：
> 
> 1. 你的代码是放在 `while` 循环中的，在被操作的那个数（`myInt`）大于 0 之前会循环执行，所以并不像你想的执行一次就出结果；
> 2. 每循环一次，`count = count + 1`，所以 count 最终会是循环执行的次数，为啥你认为应该是 12+1？
> 3. `%` 是整除运算符，`12 % 2` 的值是整数 6，不是浮点数 `6.0`。
> 
> 最后，你的代码中如果数值为奇数就执行 `myInt / 2`，这会返回一个小数，`myInt` 就不再是一个 `int` 了，这是你的本意吗？据我所知，有一道数学题，其大意是：
> 
> > 取一个自然数 n，如果它是偶数就除以 2，如果是奇数就减去 1，对结果继续执行上述操作，证明照此反复执行下去最后都会变成 1，并进一步研究操作次数和原始 n 之间的关系。
> 
> 如果你是在研究这个问题，那么你的实现错误的地方可就多了。
> 
> 综上所述，你没有搭建一个好的编程和学习环境，课程 S1 的基础知识也没学好。建议还是按部就班的去围绕课程学习和练习，否则这就是我能给你提供的最后一次帮助。

好的，谢谢老师，我去琢磨装个win10系统，重新搭载环境。
