### ISSUE TITLE
为什么不在 randrange(1,100) 范围之内的数字程序也是正常运行

### ISSUE THREAD

**Issue by myhappylife2002** [neolee/pilot#1125]
![image](https://user-images.githubusercontent.com/57083738/75010145-621c6d80-54b7-11ea-92c0-65fccdefbe90.png)

**Comment by neolee** [comment]
你这个输入参数 n 有啥用么？进入函数 n 就被赋值为 `randrange(1, 100)` 了，和输入值有关系么？
