### ISSUE TITLE
启动 Jupyter Lab 的服务程序，并打开一个浏览器页面为空白页面

### ISSUE THREAD

**Issue by pengdong2020** [neolee/pilot#1126]
![微信图片_20200221164432](https://user-images.githubusercontent.com/61263434/75018236-78cbc000-54c9-11ea-92ed-b6ee266f9621.png)
本地图书馆为空白，无内容

**Comment by neolee** [comment]
Jupyter Lab 不支持旧的 IE，你需要把系统的缺省浏览器设为新的 IE（Microsoft Edge）或者 Chrome 等浏览器。或者直接打开你习惯的浏览器（只要不是老的 IE 就行），然后把命令行里 `http://localhost...` 那一整行地址拷贝到浏览器里打开也可以。

**Comment by pengdong2020** [comment]
好的 谢谢老师
