### ISSUE TITLE
pyautogui 的 click 方法无法激活所在位置的窗口。

### ISSUE THREAD

**Issue by Ceasar1978** [neolee/pilot#1127]
教材中讲述 pyautogui 模块时出现以下一段代码：
import pyautogui
pyautogui.click((500,500))
pyautogui.typewrite('hello world!')

目的是移动鼠标至一个文本编辑框（比如 Word），然后输入 hello world!。 
但运行结果是，鼠标能移动，也能点击，但是无法激活文本编辑框的窗口，导致仍然是在 Vscode 代码编辑器下方的命令行中输入  hello world!.请问 @neolee 老师和各位战友，这是什么问题？
我的系统是 mac 10.15，Python 版本是 3.7.5. pyautogui 版本 0.9.48。

**Comment by Ceasar1978** [comment]
后来通过谷歌搜到了解决方案：
import pyautogui
pyautogui.moveTo(500, 500)   # move mouse to the window
pyautogui.dragTo(500, 500, button='left')   # focus the window
pyautogui.typewrite('hello world!')
可以实现功能，但不知道原因是什么。

**Comment by neolee** [comment]
教材哪里有这个东西？

**Comment by Ceasar1978** [comment]
忘了说清楚，是我自己目前正在学习的教材 Automate the Boring Stuff with Python。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Neo Lee"<notifications@github.com&gt;; 
发送时间: 2020年2月21日(星期五) 晚上10:25
收件人: "neolee/pilot"<pilot@noreply.github.com&gt;; 
抄送: "云轩"<4655438@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [neolee/pilot] pyautogui 的 click 方法无法激活所在位置的窗口。 (#1127)




教材哪里有这个东西？
