### ISSUE TITLE
get_descendants 到底返回什么结果？是 tree 的 list，还是名字呢？

### ISSUE THREAD

**Issue by sxuya** [neolee/pilot#1128]
## 心情

当涉及到递归寻找的时候，逻辑很容易被绕进去，完全乱了。

## 问题

获取所有后代 descendants，应该返回什么数据呢？
在做了几个内容，并且看到 neolee 给出的关于 ```find``` 的解决方法后，觉得应该是「返回一个 descendants 的 tree 的 list」。

## 困惑

如果返回的是 list 的列表，那么里面「子一代」、「子二代」……怎么排列呢？
看了 [jiangsv](https://gist.github.com/jiangsv/fca0f1b89ed807ea24c3203cc5682cb5?short_path=33ec52a)  同学提交的作业的样子，发现，ta 的实现是像 ```print_tree``` 一样，只是打印出名字。
如果是这样，就完全可以引用 ```print_tree``` 的 def 来进行实现就好了。

## 想不通

```print_tree``` 的递归，其中是直接 print 出去，所以没有数据接受；
```find``` 的递归，是只找到其中唯一一个，没有数据接受，只需找到数据，然后抛出来、停止程序就好。
```get_descendants``` 需要实现：在递归的过程中，把 every layer 的 treeNode 都集中起来，这时候「局部变量」、「全局变量」就不知道怎么实现了。
感觉把 version 2 里面加入递归，```descendants``` 的 list 就变掉了。

### 第二次（一半）

```python
   # version 2
    def get_descendants(self, name):
        node = self.find(name)
        descendants = []
        
        for child in node.children:
            descendants.append(child)
            descendants.append(child.get_descendants(child.name))  # 就是这句想要的实现递归不知道怎么实现
            
        return descendants
```

### 第一次（失败）

```python
    # version 1
    def get_descendants(self, name):
        descendants = []
        this_node = self.find(name)
        
        for child in this_node.children:
            descendants.append(child)
            if child.children:
                child.get_descendants(name)
        else:
            return descendants
```

**Comment by neolee** [comment]
这个方法的接口如何设计，要看你打算怎么用它，用不到的时候其实不管它也没问题。

如果是从一般考虑来说，可能返回一个包含所有 descendent nodes 的 list 是比较正常的设计。
