### ISSUE TITLE
编程环境这样是否配置成功了

### ISSUE THREAD

**Issue by Yao-Jing-2020** [neolee/pilot#1130]
到最后一步，输入python hello.py，并未见程序运行结果；我这样是否配置成功？
![image](https://user-images.githubusercontent.com/61304018/75064584-34204300-5522-11ea-9182-97361b11eab5.png)
另外指令里“ls”和“1s”怎么区分？之前我以为是1s，后来用ls（Ls）就可以了。
![image](https://user-images.githubusercontent.com/61304018/75064412-e277b880-5521-11ea-9675-5846ca99c9f2.png)

**Comment by Yao-Jing-2020** [comment]
![image](https://user-images.githubusercontent.com/61304018/75065269-79914000-5523-11ea-87d9-17d736ddffce.png)
应该还没配置好，哪里不对呢？

**Comment by neolee** [comment]
你的 python git code 等命令都没安装上呀。

你执行 `scoop list` 出来啥？

并没有 `1s` 这样的命令，只有 `ls`。要更清晰的区分，需要更好的 Terminal 字体。

**Comment by Yao-Jing-2020** [comment]
> 你的 python git code 等命令都没安装上呀。
> 
> 你执行 `scoop list` 出来啥？
> 
![image](https://user-images.githubusercontent.com/61304018/75087221-56dd4680-5578-11ea-99c5-e87754c0f916.png)

> 并没有 `1s` 这样的命令，只有 `ls`。要更清晰的区分，需要更好的 Terminal 字体。

**Comment by neolee** [comment]
看这个截图 Scoop 和 git python 等都安装好了。

然后你在命令行运行 `git` `python` 等命令都出错？似乎系统 PATH 没有配置好，试试重启下 Windows 再试？

**Comment by Yao-Jing-2020** [comment]
> 看这个截图 Scoop 和 git python 等都安装好了。
> 
> 然后你在命令行运行 `git` `python` 等命令都出错？似乎系统 PATH 没有配置好，试试重启下 Windows 再试？
![image](https://user-images.githubusercontent.com/61304018/75089108-6ec0c480-5590-11ea-8f01-8a1012acc95c.png)
李俊老师，scoop checkup, 按指示安装了innounp、dark和wixtoolset，然后重启，还显示一条潜在问题，怎么解决？谢谢！

**Comment by neolee** [comment]
嗯，你的 Python 似乎是装好了，为了确认，可以执行下面几个命令让我看看结果：

```shell
which python
python -V
pip -V

git --version
```

至于那个提示，是一个潜在风险，不是一定有问题，如果要解决它，执行下面的命令：

```
Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1
```

**Comment by Yao-Jing-2020** [comment]
> 嗯，你的 Python 似乎是装好了，为了确认，可以执行下面几个命令让我看看结果：
> 
> ```shell
> which python
> python -V
> pip -V
> 
> git --version
> ```
> 
> 至于那个提示，是一个潜在风险，不是一定有问题，如果要解决它，执行下面的命令：
> 
> ```
> Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1
> ```
![image](https://user-images.githubusercontent.com/61304018/75089888-5359b780-5598-11ea-9aa1-de841fb6385a.png)
潜在问题还是没法解决，没法访问注册表；是否跟公司权限有关？

**Comment by neolee** [comment]
前面的信息表明你的 Python 和 git 两个最重要的系统都装好了，可以开始学习了。

最后那个问题也常见，你可以试试在 ConEmu 中打开一个管理员权限的 PowerShell (Admin) 界面，执行那句命令试试。如果还不行就先不管它了。

**Comment by Yao-Jing-2020** [comment]
> 前面的信息表明你的 Python 和 git 两个最重要的系统都装好了，可以开始学习了。
> 
> 最后那个问题也常见，你可以试试在 ConEmu 中打开一个管理员权限的 PowerShell (Admin) 界面，执行那句命令试试。如果还不行就先不管它了。

试了一下，PowerShell（Admin）界面进不去，会弹出输入管理员密码和账户，就这样吧，还比较顺利，谢谢李老师。
