### ISSUE TITLE
关于学习用书 在使用过程的问题

### ISSUE THREAD

**Issue by pengdong2020** [neolee/pilot#1133]
![微信图片_20200222105216](https://user-images.githubusercontent.com/61263434/75085283-900abc00-5562-11ea-9d74-47753f3c0a96.png)
在学习用书使用过程中，在书中相应的练习代码输入的地方，输入数字或者代码，回车不会直接运行，而是直接换到下一行，

**Comment by wangkai-china1993** [comment]
Ctrl+回车

**Comment by neolee** [comment]
为啥提了三个一模一样的问题？而且是只要认真看指南和支线课程就能解决的问题。

**Comment by pengdong2020** [comment]
不好意思 我以为已经撤回了前面两个。------------------ 原始邮件 ------------------
发件人: "Neo Lee"<notifications@github.com>
发送时间: 2020年2月22日(星期六) 中午12:47
收件人: "neolee/pilot"<pilot@noreply.github.com>;
抄送: "pengdong2020"<258346685@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [neolee/pilot] 关于学习用书 在使用过程的问题 (#1133)



为啥提了三个一模一样的问题？而且是只要认真看指南和支线课程就能解决的问题。
 
&mdash;
