### ISSUE TITLE
安装 Scoop 配置代理服务器出错

### ISSUE THREAD

**Issue by lxj376169569** [neolee/pilot#1134]
电脑主机坏了好几天了，因为疫情还找不到人修。新找了个笔记本电脑在重新配置编程环境，但遇到非常棘手的问题，怎么也解决不了，求帮助。
```
PS C:\Users\Administrator> scoop checkup
WARN  Failed to use proxy '[username:password@]host:port': Exception calling ".c
WARN  Failed to use proxy '[username:passn'wenweword@]host:port': Exception calling ".c
WARN  Failed to use proxy '[username:password@]host:port': Exception calling ".c
WARN  Failed to use proxy '[username:password@]host:port': Exception calling ".c
No problems identified!
PS C:\Users\Administrator> scoop update
WARN  Failed to use proxy '[username:password@]host:port': Exception calling ".c
WARN  Failed to use proxy '[username:password@]host:port': Exception calling ".c
WARN  Failed to use proxy '[username:password@]host:port': Exception calling ".c
WARN  Failed to use proxy '[username:password@]host:port': Exception calling ".c
WARN  Failed to use proxy '[username:password@]host:port': Exception calling ".c
WARN  Failed to use proxy '[username:password@]host:port': Exception calling ".c
WARN  Failed to use proxy '[username:password@]host:port': Exception calling ".c
WARN  Failed to use proxy '[username:password@]host:port': Exception calling ".c
Updating Scoop...
WARN  Failed to use proxy '[username:password@]host:port': Exception calling ".c
WARN  Failed to use proxy '[username:password@]host:port': Exception calling ".c
WARN  Failed to use proxy '[username:password@]host:port': Exception calling ".c
fatal: unable to access 'https://github.com/lukesampson/scoop/': Unsupported pro
Scoop update failed.
```

上面是先按照李老师的方法安装Scoop,但提示代理失败无法连接，于是自己按谷歌搜出来的方法改了下代理，就变成了上面这样，感觉问题更多了，而且怎么也改不回去了，求助。。。

**Comment by neolee** [comment]
用代理的思路是对的，但是你设置代理的命令直接拷贝了网上搜到的命令，没有吧 username password host port 这几个东西换成你的代理服务实际的值，所以就不成功了。

你之前怎么设置代理的，再执行一次，把那几个单词换成你实际的代理服务器的账号、密码、服务地址和端口。如果要还原，设置代理为空就可以了。

学编程第一是打消对计算机的恐惧，努力读懂计算机告诉你什么，更要搞清楚自己让计算机做了什么，没搞懂就别做。

**Comment by neolee** [comment]
另外我改了你的标题和内容，不要标题写一大堆，标题应该言简意赅。

以及，如果把人的名字写错还不如不写。

**Comment by lxj376169569** [comment]
抱歉啊，李骏老师。今天弄了一上午，还没弄好，有点焦躁，所以打错字了。我基础很差，感觉很吃力，在尽力用谷歌。

**Comment by neolee** [comment]
按照我前面一个回复操作有什么问题没？

**Comment by lxj376169569** [comment]
代理服务器的账号、密码、服务地址和端口不知道在哪找，还有通过命令行界面怎么输入这些信息也不确定。试了好多方法，都不成功。

**Comment by lxj376169569** [comment]
scoop config proxy currentuser@149.129.50.116:26533
'proxy' has been set to 'currentuser@149.129.50.116:26533'
进步是scoop config proxy会改了，但运行Scoop update还是失败~

**Comment by lxj376169569** [comment]
fatal: unable to access 'https://github.com/lukesampson/scoop/': Received HTTP code 301 from proxy after CONNECT
Scoop update failed.

**Comment by lxj376169569** [comment]
我正在问我购买的代理服务器商家客服，代理服务器的账号、密码、服务地址和端口是什么，还没有回信

**Comment by neolee** [comment]
你现在的路子是对的。账号密码地址端口都需要代理服务商给你，你还可以问它在命令行里使用需要怎样配置。做好了之后再尝试 Scoop 的安装。

**Comment by lxj376169569** [comment]
好的，非常感谢李骏老师

**Comment by lxj376169569** [comment]
李骏老师，昨天关于代理问题解决了，现在进行到安装 Visual Studio Code，里面最后一步输入 python hello.py ↩︎ 应该可以看到运行 hello.py 程序的结果，但我在命令行输入python hello.py无反映。

另外在VS code里提示Python is not installed. Please download and install Python before using the extension.

**Comment by lxj376169569** [comment]
我坏的那台WIN10的主机上没出现过这些问题。今天早上解决的代理问题，今天出现这个问题后也是利用谷歌在想办法，但都是“环境配置”之类的做法，尝试了很多种方法，但仍然没有解决问题。

**Comment by gongchengyong** [comment]
iwr : 基础连接已经关闭: 发送时发生错误。
所在位置 行:1 字符: 1
+ iwr -useb get.scoop.sh | iex
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest]，WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

李老师这个问题怎么解决

**Comment by lxj376169569** [comment]
如果继续后面的操作，进行到安装jupyterlab时会出现：
PS C:\Users\Administrator\code\pilot-student> pip install jupyterlab
pip : The term 'pip' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, v erify that the path is correct and try again.
At line:1 char:1
+ pip install jupyterlab
+ ~~~
    + CategoryInfo          : ObjectNotFound: (pip:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by lxj376169569** [comment]
感觉是python在命令行里没有被调用

**Comment by neolee** [comment]
@gongchengyong 不要在别人的问题下问无关的问题，有问题先搜索，你问的这个不少人问过了；如果需要可以自己提新问题。

@lxj376169569 你这个问题看上去是 Python 没装好，或者虽然装好了但是系统找不到。执行下面的命令，让我看看结果是啥：

```powershell
scoop checkup
scoop list

python -V
pip -V
```

**Comment by gongchengyong** [comment]
PS C:\Users\hffwg&gt; scoop checkup
scoop : 无法将“scoop”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ scoop checkup
+ ~~~~~
&nbsp; &nbsp; + CategoryInfo&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; : ObjectNotFound: (scoop:String) [], CommandNotFoundException
&nbsp; &nbsp; + FullyQualifiedErrorId : CommandNotFoundException




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Neo Lee"<notifications@github.com&gt;; 
发送时间: 2020年2月23日(星期天) 下午5:10
收件人: "neolee/pilot"<pilot@noreply.github.com&gt;; 
抄送: "太阳正当头"<164272909@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [neolee/pilot] 安装 Scoop 配置代理服务器出错 (#1134)




@gongchengyong 不要在别人的问题下问无关的问题，有问题先搜索，你问的这个不少人问过了；如果需要可以自己提新问题。
 
@lxj376169569 你这个问题看上去是 Python 没装好，或者虽然装好了但是系统找不到。执行下面的命令，让我看看结果是啥：
 scoop checkup scoop list python -V pip -V

**Comment by neolee** [comment]
那你的 Scoop 就没装好啊，你的 Python 哪儿来的？

**Comment by lxj376169569** [comment]
命令行输入python - V，没反应。如下：

PS C:\Users\Administrator> python - V
PS C:\Users\Administrator>

命令行输入PIP - 出现：
PS C:\Users\Administrator> PIP - V
PIP : The term 'PIP' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, v erify that the path is correct and try again.
At line:1 char:1
+ PIP - V
+ ~~~
    + CategoryInfo          : ObjectNotFound: (PIP:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by lxj376169569** [comment]
安装 Python
如果一切无误，我们就可以着手安装 Python 了，运行：

scoop bucket add versions
scoop update
scoop install python37@3.7.4
目前 Python 3.8.0 已经正式发布，Scoop 上最新的 python 包就是 3.8.x 版本，但因为太新，一些我们会用到的第三方程序没有完全兼容，所以目前仍需使用 3.7.x（这里推荐使用课程本身开发时的 3.7.4 版本）。

上述安装命令运行完毕之后可以再次运行 scoop list，应会列出已经安装好的几个软件包。我们还可以输入 python -V 来查看安装的 Python 的版本（应该是 3.7.4）。

另外有个常用的工具包叫 busybox，里面包含了大量 Unix、Linux、macOS 系统里常用的命令，让我们在 Windows 下也能使用这些命令，推荐安装：

scoop install busybox

按上面步骤装的李老师

**Comment by lxj376169569** [comment]
当时在命令行里显示是安装成功啊

**Comment by gongchengyong** [comment]
上面的问题还没解决






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"lxj376169569"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月23日(星期天) 下午5:30
收件人:&nbsp;"neolee/pilot"<pilot@noreply.github.com&gt;;
抄送:&nbsp;"太阳正当头"<164272909@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [neolee/pilot] 安装 Scoop 配置代理服务器出错 (#1134)




安装 Python
 如果一切无误，我们就可以着手安装 Python 了，运行：
 
scoop bucket add versions
 scoop update
 scoop install python37@3.7.4
 目前 Python 3.8.0 已经正式发布，Scoop 上最新的 python 包就是 3.8.x 版本，但因为太新，一些我们会用到的第三方程序没有完全兼容，所以目前仍需使用 3.7.x（这里推荐使用课程本身开发时的 3.7.4 版本）。
 
上述安装命令运行完毕之后可以再次运行 scoop list，应会列出已经安装好的几个软件包。我们还可以输入 python -V 来查看安装的 Python 的版本（应该是 3.7.4）。
 
另外有个常用的工具包叫 busybox，里面包含了大量 Unix、Linux、macOS 系统里常用的命令，让我们在 Windows 下也能使用这些命令，推荐安装：
 
scoop install busybox
 
按上面步骤装的李老师

**Comment by lxj376169569** [comment]
PS C:\Users\Administrator> scoop checkup
No problems identified!
PS C:\Users\Administrator> scoop list
Installed apps:

  7zip 19.00
  busybox 3329-gcf0fa4d13
  dark 3.11.2
  git 2.25.1.windows.1
  innounp 0.49
  nodejs 13.9.0
  python37 3.7.4 [C:\Users\Administrator\scoop\workspace\python37.json]

**Comment by gongchengyong** [comment]
PS C:\Users\hffwg&gt; scoop checkup
scoop : 无法将“scoop”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ scoop checkup
+ ~~~~~
&nbsp; &nbsp; + CategoryInfo&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; : ObjectNotFound: (scoop:String) [], CommandNotFoundException
&nbsp; &nbsp; + FullyQualifiedErrorId : CommandNotFoundException





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"lxj376169569"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月23日(星期天) 下午5:33
收件人:&nbsp;"neolee/pilot"<pilot@noreply.github.com&gt;;
抄送:&nbsp;"太阳正当头"<164272909@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [neolee/pilot] 安装 Scoop 配置代理服务器出错 (#1134)




PS C:\Users\Administrator&gt; scoop checkup
 No problems identified!
 PS C:\Users\Administrator&gt; scoop list
 Installed apps:
 
7zip 19.00
 busybox 3329-gcf0fa4d13
 dark 3.11.2
 git 2.25.1.windows.1
 innounp 0.49
 nodejs 13.9.0
 python37 3.7.4 [C:\Users\Administrator\scoop\workspace\python37.json]

**Comment by neolee** [comment]
@gongchengyong 上面已经说了，拜托不要在别人的问题里串场了好吗？你提的问题我已经回了，去那边看去。

@lxj376169569 你两个命令都输错了啊，第一个命令 `python -V`，横线和 V 之间没有空格；第二个命令 `pip -V`，是小写的 pip，不是大写的。看你 `scoop list` 的输出，Python 应该是装好了的。你把命令写对给我看下。

**Comment by lxj376169569** [comment]
PS C:\Users\Administrator> python -V
PS C:\Users\Administrator> pip -V
pip : The term 'pip' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, v erify that the path is correct and try again.
At line:1 char:1
+ pip -V
+ ~~~
    + CategoryInfo          : ObjectNotFound: (pip:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by lxj376169569** [comment]
这个对么李老师

**Comment by gongchengyong** [comment]
PS C:\Users\hffwg&gt; python -V
python : 无法将“python”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ python -V
+ ~~~~~~
&nbsp; &nbsp; + CategoryInfo&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; : ObjectNotFound: (python:String) [], CommandNotFoundException
&nbsp; &nbsp; + FullyQualifiedErrorId : CommandNotFoundException





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "lxj376169569"<notifications@github.com&gt;; 
发送时间: 2020年2月23日(星期天) 下午5:36
收件人: "neolee/pilot"<pilot@noreply.github.com&gt;; 
抄送: "太阳正当头"<164272909@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [neolee/pilot] 安装 Scoop 配置代理服务器出错 (#1134)




PS C:\Users\Administrator&gt; python -V
 PS C:\Users\Administrator&gt; pip -V
 pip : The term 'pip' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, v erify that the path is correct and try again.
 At line:1 char:1
  
pip -V
 
   + CategoryInfo          : ObjectNotFound: (pip:String) [], CommandNotFoundException   + FullyQualifiedErrorId : CommandNotFoundException

**Comment by neolee** [comment]
这次命令对了，但是返回结果很奇怪。

再试试这两个命令：

```powershell
which python
which pip
```

**Comment by gongchengyong** [comment]
PS C:\Users\hffwg&gt; which python
which : 无法将“which”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ which python
+ ~~~~~
&nbsp; &nbsp; + CategoryInfo&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; : ObjectNotFound: (which:String) [], CommandNotFoundException
&nbsp; &nbsp; + FullyQualifiedErrorId : CommandNotFoundException


PS C:\Users\hffwg&gt; which pip
which : 无法将“which”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ which pip
+ ~~~~~
&nbsp; &nbsp; + CategoryInfo&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; : ObjectNotFound: (which:String) [], CommandNotFoundException
&nbsp; &nbsp; + FullyQualifiedErrorId : CommandNotFoundException





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Neo Lee"<notifications@github.com&gt;; 
发送时间: 2020年2月23日(星期天) 下午5:45
收件人: "neolee/pilot"<pilot@noreply.github.com&gt;; 
抄送: "太阳正当头"<164272909@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [neolee/pilot] 安装 Scoop 配置代理服务器出错 (#1134)




这次命令对了，但是返回结果很奇怪。
 
再试试这两个命令：
 which python which pip

**Comment by lxj376169569** [comment]
PS C:\Users\Administrator> which python
C:/Users/Administrator/scoop/shims/python.exe
PS C:\Users\Administrator> which pip
PS C:\Users\Administrator>

**Comment by neolee** [comment]
似乎是这样，你虽然用 Scoop 安装成功了不少软件包，但是系统找不到装好的软件。

运行这个看看：

```powershell
$Env:Path
```

**Comment by lxj376169569** [comment]
PS C:\Users\Administrator> $Env:Path
E:\ConEmuPack.191012\ConEmu\Scripts;E:\ConEmuPack.191012;E:\ConEmuPack.191012\ConEmu;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Users\Administrator\scoop\workspace;C:\Users\Administrator\scoop\apps\nodejs\current\bin;C:\Users\Administrator\scoop\apps\nodejs\current;C:\Users\Administrator\scoop\apps\python37\current\scripts;C:\Users\Administrator\AppData\Local\Programs\Python\Launcher\;C:\Users\Administrator\scoop\shims;E:\VS Code\Microsoft VS Code\bin

**Comment by gongchengyong** [comment]
PS C:\Users\hffwg&gt; $Env:Path
C:\Program Files\ConEmu\ConEmu\Scripts;C:\Program Files\ConEmu;C:\Program Files\ConEmu\ConEmu;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;%SYSTEMROOT%\System32\OpenSSH\;C:\Users\hffwg\AppData\Local\Microsoft\WindowsApps;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Neo Lee"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月23日(星期天) 下午5:49
收件人:&nbsp;"neolee/pilot"<pilot@noreply.github.com&gt;;
抄送:&nbsp;"太阳正当头"<164272909@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [neolee/pilot] 安装 Scoop 配置代理服务器出错 (#1134)




似乎是这样，你虽然用 Scoop 安装成功了不少软件包，但是系统找不到装好的软件。
 
运行这个看看：
 $Env:Path

**Comment by neolee** [comment]
你的 Path 变量里的 `C:\Users\Administrator\AppData\Local\Programs\Python\Launcher;` 这个部分很可疑，你装过 Python Launcher 之类的软件吧，把这个软件删掉，或者至少从 Path 里把上述路径删掉，应该就好了。

**Comment by neolee** [comment]
另外，删掉那个路径之后重启下 Windows，有的系统需要重启才能让 Path 的变动生效。

**Comment by lxj376169569** [comment]
好的  我试一下  谢谢李骏老师

**Comment by neolee** [comment]
啊，不对，我看了下，那个路径应该是 Scoop 的 Python 安装包装的，你不需要删除它。直接重启 Windows，你的 Path 内容没问题，但看上去没有生效而已。

**Comment by lxj376169569** [comment]
好的  我还没删  直接重启电脑就行  是吗

**Comment by neolee** [comment]
先重启看看是不是就好了，之前有别的同学就是这样，装好 Scoop 之后要重启一次才能找到 Scoop 安装的软件。尤其是老一点 Windows 很可能是这样的。

**Comment by lxj376169569** [comment]
好的

**Comment by lxj376169569** [comment]
李骏老师，重启后问题还没有解决，是不是因为系统的原因？我的笔记本电脑系统是WIN7。

**Comment by lxj376169569** [comment]
以前那台主机就是WIN7，配置环境时就碰到很多问题，后来重装系统换成WIN10后配置环境时一路很顺畅

**Comment by neolee** [comment]
如果可以的话，换 Windows 10 确实会少很多麻烦。

你现在用 ConEmu 打开一个 PowerShell (Admin) 命令行界面试试？有的 Win 7 系统即使设置好了 PATH 也没有权限访问某些目录，用管理员权限的命令行环境可以解决，试试看。

**Comment by lxj376169569** [comment]
好的，非常感谢李骏老师的耐心解答~
