### ISSUE TITLE
安装 Homebrew

### ISSUE THREAD

**Issue by muse1171** [neolee/pilot#1136]
安装Homebrew，不懂是不是已经成功了，之前有装过xcode，在mac环境下。
<img width="911" alt="截屏2020-02-2213 58 26" src="https://user-images.githubusercontent.com/26201194/75087482-e46e6580-557b-11ea-9048-7c4d7e99556a.png">

**Comment by neolee** [comment]
你这个是安装 Homebrew 的那一个命令正在运行中，你现在输入命令没用，等那个安装命令成功运行完毕才能继续。

**Comment by muse1171** [comment]
<img width="787" alt="截屏2020-02-2420 46 47" src="https://user-images.githubusercontent.com/26201194/75153692-f94b2480-5746-11ea-9abe-ac36f1c76dcd.png">
<img width="1295" alt="截屏2020-02-2420 46 03" src="https://user-images.githubusercontent.com/26201194/75153716-06681380-5747-11ea-9534-94602584d828.png">

**Comment by muse1171** [comment]
google 搜解决方法，最后还是没成功。

**Comment by neolee** [comment]
还是网络的问题，下载 Homebrew 数据时出错了。

**Comment by muse1171** [comment]
<img width="986" alt="截屏2020-02-2621 41 16" src="https://user-images.githubusercontent.com/26201194/75350913-40215180-58e2-11ea-8fdf-48c4da98d6eb.png">
到底哪里错了？一直google了几天都没成功，求救！！！

**Comment by muse1171** [comment]
<img width="975" alt="截屏2020-02-2621 53 36" src="https://user-images.githubusercontent.com/26201194/75351094-84145680-58e2-11ea-90d2-c9dc3b6d8080.png">
最后我是按照图中的方法弄的，把图中的换成了export https_proxy=http://127.0.0.1:9090;export http_proxy=http://127.0.0.1:9090       因为我用的是SpetchLite
