### ISSUE TITLE
安装 scoop 出错

### ISSUE THREAD

**Issue by xiaohouzi2020** [neolee/pilot#1138]
iwr -useb get.scoop.sh | iex 无法将“iwr”项识别为 cmd
let、函数、脚本文件或可运行程序的名称。请检查名称的拼 写，如果包括路径，请确保路径
正确，然后重试。 所在位置 行:1 字符: 4 + iwr <<<<  -useb get.scoop.sh | iex     +
 CategoryInfo          : ObjectNotFound: (iwr:String) [], CommandNotFound    Exception     + FullyQualifiedErrorId : CommandNotFoundException

**Comment by neolee** [comment]
你的系统太老，PowerShell 需要在 5.0 或以上才能支持环境指南的要求，在指南的一开始就说了，为什么不仔细看呢？
