### ISSUE TITLE
克隆 repo 中断后如何继续

### ISSUE THREAD

**Issue by Yao-Jing-2020** [neolee/pilot#1139]
输入 cd Code ↩︎ 进入我们之前创建的子目录（如果还没有建立，可以用 mkdir Code ↩︎ 来创建）；
输入 git clone ，在最后有个空格，在空格后粘贴你前面拷贝的，你 fork 的 repo 的地址，然后输入回车 ↩︎；
走到这一步的时候，克隆90个里的17个，但是下载速度变为零；我就把它关了，我重新按上面的步骤，告知目标路径已经存在，怎么继续克隆？
![image](https://user-images.githubusercontent.com/61304018/75090455-f6610000-559d-11ea-9300-af5d8b5e975b.png)
另外，很多时候想退出当前的文档（比如下图PS C:\Users\yaoj22\Code\pilot-student>）或运行的命令，怎么退出？我一般直接把窗口关了，有没有指令让其关闭或退出呢？
![image](https://user-images.githubusercontent.com/61304018/75090447-daf5f500-559d-11ea-9bea-df0aa5264825.png)

**Comment by neolee** [comment]
不能继续，所以你必须先删掉之前遗留的目录：

```shell
cd
cd Code
rm -Force pilot-student
```

然后再重执行 `git clone` 命令。

**Comment by Yao-Jing-2020** [comment]
> 不能继续，所以你必须先删掉之前遗留的目录：
> 
> ```powershell
> cd ~\Code
> rm -Force pilot-student
> ```
> 
> 然后再重执行 `git clone` 命令。

已搞定
