### ISSUE TITLE
运行结果查看

### ISSUE THREAD

**Issue by yayuehuizi** [neolee/pilot#114]
在程序结构查看一节，按照pilot格式在student里面输入相同的命令后，如何显示运行结果呢？比如我输入type（42），它仍旧停留在这样的界面，并没有in和out显示，也没出现“int“的结果。

**Comment by neolee** [comment]
在 cell 里输入代码之后按 Control+回车 执行。

另外，注意括号（以及代码里其他标点符号）都要用英文半角的。
