### ISSUE TITLE
关于函数别名的疑问？

### ISSUE THREAD

**Issue by gaoteng-pro** [neolee/pilot#1140]
看教材，函数取别名的方式有两种：一种是直接写好一个函数，然后用一个**别名 = 函数名**的方式（如图1）；另一种是在引用模块的时候，`from XXX import YYY as ZZZ`（如图2）。

老师在《函数式思想-装饰器》的视频（13:27）中，用`logged_greeting = log_decorator(greeting)`来为`log_decorator(greeting)`取别名`logged_greeting`（如图3）。函数取别名是**新名字 = 旧名字**这种**名字 = 名字**的格式，而用`logged_greeting = log_decorator(greeting)`来取别名，格式是不是不对，解释器怎么知道`logged_greeting`是个函数名而不是一个变量名呢？
<img width="1440" alt="截屏2020-02-21下午10 37 08" src="https://user-images.githubusercontent.com/57254889/75091870-0207f300-55ad-11ea-99fa-f0f6679fe905.png">
<img width="1440" alt="截屏2020-02-22下午7 33 10" src="https://user-images.githubusercontent.com/57254889/75091881-249a0c00-55ad-11ea-975d-9f53f56d012e.png">
![IMG_0071](https://user-images.githubusercontent.com/57254889/75091889-38457280-55ad-11ea-88c4-826c5aef8eb1.jpeg)

**Comment by neolee** [comment]
函数也是数据。

`log_decorator()` 是一个高阶函数，接受一个函数作为输入参数，返回一个新的函数；所以 `log_decorator(greeting)` 的值就是一个函数。

`logged_greeting = log_decorator(greeting)` 就把这个值赋给了 `logged_greeting`，`logged_greeting` 本来就是一个变量，其值是一个函数。

有什么问题呢？

**Comment by gaoteng-pro** [comment]
不知道该怎么讲，我们学过的赋值语句是这样的：
```python
a = 1
a = 3.14
a = True
a = "abd"
a = [1,2,3]
a = (1,2)
```
函数也是数据，也是值。函数区别于变量的关键在于函数后面的括号`( )`。既然函数也是数据，也是值，那么我们就可以用赋值语句把一个函数赋值给一个变量，但我们不能直接使用`名字 = 函数名（ ）`这样的的格式。而要用`名字 = 函数名`这样的格式，也就是我们在赋值的时候，需要把函数区别于变量的括号`( )`去掉才行。

而`logged_greeting = log_decorator(greeting)`之所以成立是因为后者返回的是一个函数名，而不是一个函数，因为`return wrapper`而不是`return wrapper ( )`。刚试了（如下图），如果改成`return wrapper( )`代码也可以运行，只是赋值语句`logged_greeting = log_decorator(greeting)`之后，再使用`logged_greeting( )`会报错，因为返回的不是函数名，而是函数名+括号，即，`return wrapper( )`。

结论就是：函数是数据，是一个值，可以赋值给变量，但必须是函数名才行，加括号不可以，这样理解对吧？

疑问：为什么是`return wrapper`，而不是`return wrapper( )`，函数的调用不应该是函数名+括号的形式吗？为什么只写函数名`return wrapper`就能调用？
<img width="1440" alt="截屏2020-02-23下午12 09 41" src="https://user-images.githubusercontent.com/57254889/75103441-974eca00-5635-11ea-9689-e0d834c87b9c.png">

**Comment by neolee** [comment]
`func(...)` 这样的语法并不是函数 `func` 本身，而是“用参数 (...) 去调用函数 func”的意思。

`func` 才代表函数对象本身。

`logged_greeting = log_decorator` 和 `logged_greeting = log_decorator(greeting)` 都是给变量 `logged_greeting` 赋值的语句，区别在于右边的值不一样：

* `logged_greeting = log_decorator` 右边的值是一个函数对象 `log_decorator`，这个赋值语句相当于给函数对象 `log_decorator` 一个（新的）名字 `logged_greeting`。
* `logged_greeting = log_decorator(greeting)` 右边是一个函数调用，用参数 `greeting` 去调用了函数 `log_decorator`，这个函数调用的返回值是一个处理过之后的新函数，整个赋值语句就是把这个新的函数赋给了变量 `logged_greeting`。

最后，为啥装饰器返回的是 `wrapper` 而不是 `wrapper(...)`，根据上面的解释，你能自己找到答案了么？

**Comment by gaoteng-pro** [comment]
`return`语句后面返回什么，其实是独立的。可以返回和函数体内相关的内容，也可以返回和函数体完全无关的内容，当然还可以返回`None`。也就是说装饰器可以返回`wrapper`也可以返回`wrapper(...)`这在解释器看来都是可以执行的。相应的，赋值语句之后调用函数就不同了（如下图）。
>`logged_greeting = log_decorator `和 `logged_greeting = log_decorator(greeting) `都是给变量 `logged_greeting `赋值的语句，区别在于右边的值不一样。
而`logged_greeting = log_decorator(greeting)`之后，依然可以使用`logged_greeting( )`来执行`wrapper`的函数体，就是因为装饰器的调用之后返回的是函数（即，函数名），而不是加括号的函数调用。

结论就是：装饰器可以返回`wrapper`也可以返回`wrapper( )`，但根据返回的不同，赋值之后变量的使用也不同。前者是需要在变量名后面加括号，而后者不需要加括号（加括号反而会报错）。
<img width="1440" alt="截屏2020-02-23下午8 13 08" src="https://user-images.githubusercontent.com/57254889/75111974-68a71280-567a-11ea-8f37-c90853498350.png">
<img width="1440" alt="截屏2020-02-23下午8 04 06" src="https://user-images.githubusercontent.com/57254889/75111976-6f358a00-567a-11ea-910d-94ccc8d88e37.png">

**Comment by neolee** [comment]
不，装饰器必须返回 `wrapper`，因为装饰器需要返回被装饰之后的**函数本身**，而不是“被装饰之后的函数的**调用结果**”。

**Comment by gaoteng-pro** [comment]
那单就`return`语句来说，后面具体返回什么，是独立的，可以和函数体完全没关系，可以这样理解吧？

**Comment by neolee** [comment]
`return` 后面就是个值，只要能求值的，都可以放在 `return` 后面。
