### ISSUE TITLE
Homebrew 安装问题

### ISSUE THREAD

**Issue by muse1171** [neolee/pilot#1142]
<img width="911" alt="截屏2020-02-2213 58 26" src="https://user-images.githubusercontent.com/26201194/75094289-c4af5f80-55c4-11ea-9660-543c9b881297.png">
usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
curl: (7) Failed to connect to raw.githubusercontent.com port 443: Connection refused
为啥失败呢？

**Comment by neolee** [comment]
网络问题。

**Comment by muse1171** [comment]
https://www.jianshu.com/p/68efabd2e32b  不是网络问题，已经找到解决办法。

**Comment by neolee** [comment]
这就是网络问题，反馈信息里那么清楚的写着 connection refused。

网络问题也有很多种，也有不同的解决办法，可以通过合理的尝试和推测来了解真相。如果是你后来补充资源里描述的，可以用浏览器访问而不能用 curl 访问安装文件的地址，可能是命令行下需要正确配置 HTTPS 代理。

你问的这个问题在这里已经被问过很多次了，再网上也可以搜到很多类似问题。可以自己搜索解决就好。
