### ISSUE TITLE
对话机器人的疑问

### ISSUE THREAD

**Issue by Gittplayer** [neolee/pilot#1143]
```python
class Garfield:
    
    def __init__(self, wait=1):
        Bot.wait = wait
        self.bots = []
```

李老师我有几个疑问：

1. 在class Garfield的时候并没有定义类变量，我理解是否定义类变量是根据实际需要来的，是这样吗？

2. 方法中的参数：

(1) 函数中没定义，但下面的具体方法有用到
```python
def __init__(self):
        self.q = ''
        self.a = ''
```

(2) 函数中定义了，下面的方法也用到了
```python
def _think(self, s):
        return s
```

(3) 函数中只定义了1个，但下面的具体方法实际用了2个
```python
def __init__(self, wait=1):
        Bot.wait = wait
        self.bots = []
```
以上这类情况有什么原则吗？什么时候参数该定义完整？什么时候只定义一部分？什么时候不用定义？

3.
```python
class Garfield:
def __init__(self, wait=1):
    Bot.wait = wait
    self.bots = []
```
这里初始化函数中的wait为什么要赋值呢？因为这个wait是实例变量，在下面创建garfield = Garfield(1)实例对象时会再次赋值，感觉没有wait提前赋值没有意义

4. 三个聊天机器人HelloBot，GreetingBot，FavoriteColorBot，为什么并没有创建实例对象也可以运行呢？

**Comment by neolee** [comment]
1. 类变量不是必须的，根据需要使用；其实实例变量、方法也都不是必须的，都是根据你的需要来的。

2. 我看不懂你这部分的问题，我猜你对很多概念的理解是不对的，所以存在“乱用（自己并未理解的）名词”的问题。比如“函数”和“方法”，其实方法是函数，只不过是写在“类定义”里的函数。

然后，我猜测你可能对 `self` 这个东西有些迷惑，上课时我专门讲过，`self` 实在类定义期间对未来要实例化的对象的一种“前置引用”。类本身并不是实体，要实例化为对象才能真正运行，那么实例化之后的对象（是个变量）在类定义的时候怎么引用呢？就用 `self` 这个特殊的变量来代表。所以在定义对象方法时每个方法的第一个参数都必须是 `self`，这样在这个方法的定义体里面可以使用它；而在实例化之后调用这个方法时，则会使用 `obj.xxx()` 这样的语法，输入参数里就没有 self 了——因为已经有具体实例化的对象 `obj` 了。这个语法设计是 Python 一个颇具争议的点，我个人就不是很喜欢，但也没有大问题，理解就行了。

3. `wait=1` 不是一个赋值语句，这是函数定义中的“带缺省值的参数”的语法。S2 课程最开始有详细介绍，如果你刚学到 S1 最后这个课程练习，可以看课程练习的视频讲解（Wiki 里有链接），里面有说明。

另外，`self.wait` 是实例变量（属性），而 `wait` 只是局部变量（含输入参数的情况），是不一样的，这也是课上多次提过的。

4. 你从哪里看出“没有实例化却也能运行”的？

综上，建议你好好重新温习面向对象部分的课程，尤其是音频课和机器人课程练习的视频讲解。

以及，对概念的理解要更扎实一些，如果用词不准确，甚至交流都会很低效。
