### ISSUE TITLE
jupyter lab 打开pilot-sutdent课件，里面的代码缺失

### ISSUE THREAD

**Issue by Shawnnn** [neolee/pilot#1144]
如下图，原本老师课件中Cell那里应该有代码，都是都缺失了。我打开其他的ipynb 也是一样
![image](https://user-images.githubusercontent.com/15227825/75099594-ad23a700-55c3-11ea-8358-cc46358d55cb.png)

**Comment by neolee** [comment]
所谓学习用书，就是空着让你去填的啊，你到底有没有仔细看课程最开始的指引文档啊……

**Comment by Shawnnn** [comment]
> 所谓学习用书，就是空着让你去填的啊，你到底有没有仔细看课程最开始的指引文档啊……

我错了π_π ，发布了没多久突然醒悟了，但不知道怎么remove issue。。所以只是close了

**Comment by neolee** [comment]
> 我错了π_π ，发布了没多久突然醒悟了，但不知道怎么 remove issue 所以只是 close 了

这种情况下应该写一条简短的回复，说已经找到答案，然后再 close。
