### ISSUE TITLE
scoop install python37@3.7.4 不成功

### ISSUE THREAD

**Issue by yiguo-hu** [neolee/pilot#1145]
![image](https://user-images.githubusercontent.com/51398930/75104261-f9153100-5641-11ea-817f-e84c9265c0eb.png)

**Comment by neolee** [comment]
执行下面的命令，让我看看结果：

```powershell
scoop bucket list
scoop search python37
```

**Comment by yiguo-hu** [comment]
> 执行下面的命令，让我看看结果：
> 
> ```powershell
> scoop bucket list
> scoop search python37
> ```

![image](https://user-images.githubusercontent.com/51398930/75126348-7dc08780-56f4-11ea-9b1f-419fdd956893.png)

**Comment by neolee** [comment]
网络有点问题，你需要执行 `scoop update` 成功更新本地的软件数据库，然后 `scoop search python37` 能找到对应的软件包，才能安装成功。

多试几次或者换网络，或者试试代理。

**Comment by yiguo-hu** [comment]
> 网络有点问题，你需要执行 `scoop update` 成功更新本地的软件数据库，然后 `scoop search python37` 能找到对应的软件包，才能安装成功。
> 
> 多试几次或者换网络，或者试试代理。



search 到 3.7.6，安装这个也可以吧？

**Comment by neolee** [comment]
如果你可以 search 到 python37 这个包，那么就可以用 `scoop install python37@3.7.4` 安装要求的版本。
