### ISSUE TITLE
Scoop 安装时出现此问题怎么解决

### ISSUE THREAD

**Issue by gongchengyong** [neolee/pilot#1147]
iwr : 基础连接已经关闭: 发送时发生错误。
所在位置 行:1 字符: 1
+ iwr -useb get.scoop.sh | iex
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest]，WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

**Comment by gongchengyong** [comment]
请李老师帮助解决！以前从来没接触过编程

**Comment by neolee** [comment]
网络问题。这个问题被问过多次，可以搜索下 issues。

**Comment by neolee** [comment]
另外，你一直用邮件在回复别人提的另外一个 issue，这个很不好，你的问题已经提在这里，就在这里解决，不要干扰别人的问答。

而且，最好用 GitHub 网站来访问 issues，邮件经常看不清上下文，你就一直没搞清楚，在那边几次说你都没看见。

**Comment by gongchengyong** [comment]
对不起

**Comment by gongchengyong** [comment]
PS C:\Users\hffwg> Get-ExecutionPolicy
RemoteSigned
PS C:\Users\hffwg> iwr -useb get.scoop.sh | iex
iwr : 基础连接已经关闭: 发送时发生错误。
所在位置 行:1 字符: 1
+ iwr -useb get.scoop.sh | iex
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest]，WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

**Comment by neolee** [comment]
是的，这个一般是网络问题，无法正常访问 Scoop 的服务网站，换网络或者换时间再试，或者使用网络代理，具体可以网上搜索下。

**Comment by duojicaidan** [comment]
大神，我是小白中的小白，可以说是什么都不懂的，我也是遇到这样的问题，麻烦问下怎么解决呢？我觉得这个软件还有服务器没有什么关系，就是电脑和网络的问题，就是不知道从哪里解决这个问题，麻烦大神出招，谢谢！！！

**Comment by gongchengyong** [comment]
没解决，试了好多次都解决不了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "duojicaidan"<notifications@github.com&gt;; 
发送时间: 2020年3月13日(星期五) 凌晨2:42
收件人: "neolee/pilot"<pilot@noreply.github.com&gt;; 
抄送: "太阳正当头"<164272909@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [neolee/pilot] Scoop 安装时出现此问题怎么解决 (#1147)





 
大神，我是小白中的小白，可以说是什么都不懂的，我也是遇到这样的问题，麻烦问下怎么解决呢？我觉得这个软件还有服务器没有什么关系，就是电脑和网络的问题，就是不知道从哪里解决这个问题，麻烦大神出招，谢谢！！！
