### ISSUE TITLE
GitHub 网页加载图片失败

### ISSUE THREAD

**Issue by MarScorpio** [neolee/pilot#1148]
刚开始编程环境配置，但是网页中图片加载不出来，百度了之后修改hosts文件但没有效果。当然了，也可能是我修改的不对，想请问有没有解决办法

**Comment by neolee** [comment]
有时候，有些地区的网络会无法访问 GitHub 网站里的图片和一些附件，这个是国情，需要使用网络代理。

**Comment by MarScorpio** [comment]
谢谢，我找代理试一试





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Neo Lee"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月23日(星期天) 晚上8:04
收件人:&nbsp;"neolee/pilot"<pilot@noreply.github.com&gt;;
抄送:&nbsp;"马泽元"<49968318@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [neolee/pilot] GitHub网页加载图片失败 (#1148)




有时候，有些地区的网络会无法访问 GitHub 网站里的图片和一些附件，这个是国情，需要使用网络代理。
