### ISSUE TITLE
7zip install failed issue

### ISSUE THREAD

**Issue by wangxsh06** [neolee/pilot#1149]
不知信息提供是否充分，谢谢！

**Comment by wangxsh06** [comment]
PS C:\Users\wangxx95> scoop list
Installed apps:

  7zip 19.00 *failed*

PS C:\Users\wangxx95> scoop uninstall 7zip
Uninstalling '7zip' (19.00).
'7zip' was uninstalled.
PS C:\Users\wangxx95> scoop install 7zip
Installing '7zip' (19.00) [64bit]
7z1900-x64.msi (1.7 MB) [===========================================================>                                         ]  59%
Checking hash of 7z1900-x64.msi ... ERROR Hash check failed!
App:         main/7zip
URL:         https://7-zip.org/a/7z1900-x64.msi
First bytes: D0 CF 11 E0 A1 B1 1A E1
Expected:    a7803233eedb6a4b59b3024ccf9292a6fffb94507dc998aa67c5b745d197a5dc
Actual:      c6743719d354082efc071d84682ba1eb8d0606a6612e0aa83c9a81c3e719fb0c
git : The term 'git' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the n ame, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ git config --get remote.origin.url
+ ~~~
    + CategoryInfo          : ObjectNotFound: (git:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException


Please try again or create a new issue by using the following link and paste your console output:

**Comment by neolee** [comment]
网络问题。

**Comment by wangxsh06** [comment]
谢谢李老师，已解决。
