### ISSUE TITLE
无法将“scoop”项识别为 cmdlet、函数

### ISSUE THREAD

**Issue by Weijing14** [neolee/pilot#115]
在输入scoop list 等命令时，这样显示

**Comment by neolee** [comment]
Scoop 没有安装成功，点击这个页面上面的 Wiki，按照“重新安装 Scoop”的指引操作。

**Comment by Weijing14** [comment]
> Scoop 没有安装成功，点击这个页面上面的 Wiki，按照“重新安装 Scoop”的指引操作。

按照Wiki里的命令是卸载Scoop吗，还需要按照配置指南里的操作安装是吗？

**Comment by neolee** [comment]
Wiki 里的命令式“重装 Scoop”，也就是“清理之前安装的残骸然后重新安装 Scoop”的意思。

没安装成功之前不要继续，安装好了 Scoop 再按照 指南 继续后面的操作。
