### ISSUE TITLE
安装 mysql57 出错，输出 ERROR Exit code was -1073741515!

### ISSUE THREAD

**Issue by LazzaroneS** [neolee/pilot#1150]
按照老师的 MySQL 环境准备文档，执行：

> scoop bucket add versions

> scoop install mysql57

结果就出现了 ERROR Exit code was -10737415151

重复卸载安装了几次、也试了 mysql 8.0 的版本，都出现同样的错误;

![Error of mysql](https://user-images.githubusercontent.com/41162617/75129873-3f33c880-5706-11ea-99c0-4f6ed4adc877.jpg)

安装后执行 mysqld --install 直接就跳转到下一行，没有任何输出。Services 管理程序里面也没有看到 MySQL 这样的服务，输入 mysql -uroot 没有反应。

Google 搜索类似的问题，也没有找到获得投票的答案，没能解决问题，也可能是因为我英文不是很好，自己没看懂。

**Comment by LazzaroneS** [comment]
为了能尽可能靠自己解决问题，我也在持续学习英文中……
希望能得到大家的帮助，阿里嘎多~

**Comment by neolee** [comment]
这类问题是比较麻烦的，如果花费了太多时间不太值得，所以实在搞不定可以跳过，以后再说。

因为 Windows 环境一般比较复杂，影响因素众多，如果不是坐在你的电脑边，也很难给出很准确的诊断和方案，所以目前只有几点思路上的建议，供你参考：

1. 打开你的任务管理器，看看里面有没有叫做 mysqld 的进程，如果有的话，可能你的 MySQL Server 已在运行，可以试试在命令行运行 mysql 命令来连接进去；如果没有，你的首要任务是看看如何让 mysqld（也就是 MySQL 的服务程序）运行起来。在后面的尝试中如果看到有 mysqld 这个进程，但是无法用 mysql 命令连接进去，你需要在任务管理器中杀掉 mysqld 这个进程，再尝试别的办法。

2. 要运行 mysqld，最直接的办法是执行 `mysqld --standalone`，而不是 `mysqld install`，因为前者可以直接运行 MySQL 服务程序，而后者是尝试将 MySQL 服务注册成 Windows 服务，后者依赖的东西更多，更容易出问题。所以先试前一个，成功了在考虑后一个。

3. 你看到的出错代码（`1073741515`）不是 MySQL 的出错代码，而是与 Windows 文件系统有关的，我目前看到最可能有关的信息是下面这篇：

http://community.sqlbackupandftp.com/t/error-1073741515-solved/1305

**Comment by LazzaroneS** [comment]
安装了一下 Visual Studio 2019，果然好了，虽然不知其所以然，问题没了还是很开心，哈哈，感谢老师！

**Comment by LazzaroneS** [comment]
搞不定，跳过了，感谢老师！
