### ISSUE TITLE
请问为什么 bark 后面需要加 () 而 name 后面不用

### ISSUE THREAD

**Issue by PanChuang2019** [neolee/pilot#1151]
![image](https://user-images.githubusercontent.com/48653618/75132903-aad06280-5713-11ea-8f32-d2895eaaec94.png)
请问老师，这里为甚么bark后面要多打一个（），而不能直接用a.bark  获取返回值。

**Comment by neolee** [comment]
`a.bark` 得到的是一个函数对象，而 `a.bark()` 是调用 `a` 对象的 `bark` 方法得到其返回值。

**Comment by PanChuang2019** [comment]
可是为什么name那个属性，就可以直接用`a.name`的形式获取，是不是这样理解：name对应的是作为属性，是可以直接用`object.attribute`的形式获取返回值，但是下面那个bark是作为方法，方法对应的是函数，函数的话必须加`()`，因为`()`意味着要调取参数才能获得返回值。

**Comment by neolee** [comment]
`name` 是属性（也叫**对象变量**），所以用 `obj.name` 来访问这个变量；

`bark` 是对象的**方法**，也可以看做一个函数类型的**对象变量**，你也可以用 `obj.bark` 来得到合格函数类型的变量（注意，函数也是一种对象）；如果你要调用这个函数得到返回值，就要在后面加上括号和输入参数值。
