### ISSUE TITLE
我加了两行求对应实例属性的 cell 却只返回其中一个值

### ISSUE THREAD

**Issue by PanChuang2019** [neolee/pilot#1152]
![image](https://user-images.githubusercontent.com/48653618/75135261-f555dd00-571b-11ea-8853-23e0f0eb4fa2.png)

```
a =Animal('キュゥべえ')
c =Cat('Garfield')
d =Dog('Snoopy')

d.name
c.name
```
```
'Garfield'
```

**Comment by neolee** [comment]
如果你要显示一个值，最好用 `print(...)`。

在 Python 解释器和 Jupyter Notebook 中，可以在一个 cell 里写一个值，然后执行，解释器会显示这个值，但如果你在一个 cell 里写上几个值，就只会显示最后一个（有一些 Jupyter 的 magic command 可以让你看到多个值，但这么做的意义不大）。

在课程一开始我们就讲了运行 Python 程序的几种方法，从长远来看，你以后运行 Python 程序主要将是在命令行执行类似这样的命令：`python xxx.py`，所以养成习惯，想看啥就用 `print()`，是比较好的。
