### ISSUE TITLE
运行 pip install jupyterlab 报错

### ISSUE THREAD

**Issue by de-cheng** [neolee/pilot#1153]
......
......
Collecting terminado>=0.8.1
  Downloading terminado-0.8.3-py2.py3-none-any.whl (33 kB)
ERROR: Could not find a version that satisfies the requirement pyzmq>=17 (from notebook>=4.3.1->jupyterlab) (from versions: none)
ERROR: No matching distribution found for pyzmq>=17 (from notebook>=4.3.1->jupyterlab)

**Comment by de-cheng** [comment]
这是一台 Surface pro4

**Comment by neolee** [comment]
常规检查：

```powershell
$env:Path

scoop checkup
scoop update

which python
python -V
pip -V
pip list
```

**Comment by BlackSocrates** [comment]
我也遇到了一样的问题，问题显示为“找不到合适版本的……”。所以可能是网络暂时不通找不到，你再试试可能就好了。我就是再试一次好了的。
