### ISSUE TITLE
install python37@3.7.4 失败

### ISSUE THREAD

**Issue by wangxsh06** [neolee/pilot#1154]
不确定是不是网络问题，请李老师帮忙看一下，谢谢。
PS C:\Users\wangxx95> scoop update
Updating Scoop...
Updating 'main' bucket...
Updating 'versions' bucket...
Scoop was updated successfully!
PS C:\Users\wangxx95> scoop bucket list
main
versions
PS C:\Users\wangxx95> scoop search python37
'versions' bucket:
    python37 (3.7.6)

PS C:\Users\wangxx95> scoop install python37@3.7.4
WARN  Given version (3.7.4) does not match manifest (3.7.6)
WARN  Attempting to generate manifest for 'python37' (3.7.4)
Autoupdating python37
Searching hash for python-3.7.4.exe in https://www.python.org/downloads/release/python-374/
Found: md5:33cc602942a54446a3d6451476394789 using Extract Mode
Searching hash for python-3.7.4-amd64.exe in https://www.python.org/downloads/release/python-374/
Found: md5:a702b4b0ad76debdb3043a583e563400 using Extract Mode
Writing updated python37 manifest
Installing 'python37' (3.7.4) [64bit]
The remote server returned an error: (403) Forbidden.
URL https://www.python.org/ftp/python/3.7.4/python-3.7.4-amd64.exe#/py3.exe is not valid
PS C:\Users\wangxx95>

**Comment by wangxsh06** [comment]
又试了一次是这样。

PS C:\Users\wangxx95> scoop install python37@3.7.4
WARN  Given version (3.7.4) does not match manifest (3.7.6)
WARN  Attempting to generate manifest for 'python37' (3.7.4)
Autoupdating python37
Searching hash for python-3.7.4.exe in https://www.python.org/downloads/release/python-374/
Found: md5:33cc602942a54446a3d6451476394789 using Extract Mode
Searching hash for python-3.7.4-amd64.exe in https://www.python.org/downloads/release/python-374/
The operation has timed out
URL https://www.python.org/downloads/release/python-374/ is not valid
Could not find hash in https://www.python.org/downloads/release/python-374/
Downloading python-3.7.4-amd64.exe to compute hashes!
The operation has timed out
URL https://www.python.org/ftp/python/3.7.4/python-3.7.4-amd64.exe#/py3.exe is not valid
Could not find hash!
Could not install python37@3.7.4

**Comment by neolee** [comment]
你能访问 https://www.python.org/downloads/release/python-374/ 这个页面吗？

这个挺奇怪的。你试试 `scoop install python37`，这样会安装 3.7.6 版本，也没问题的。

**Comment by wangxsh06** [comment]
李老师，网页可以访问（显示3.7.4版本的python）证明网络应该是没问题。不过安装还是不行，不行我换个时间再试试吧。

PS C:\Users\wangxx95> scoop install python37
Installing 'python37' (3.7.6) [64bit]
The remote server returned an error: (403) Forbidden.
URL https://www.python.org/ftp/python/3.7.6/python-3.7.6-amd64.exe#/py3.exe is not valid

**Comment by wangxsh06** [comment]
终于搞定了，我把这个网址加到internet 的trust list里面就行了。

**Comment by neolee** [comment]
哦，防火墙和防病毒软件经常会带来奇怪的现象……
