### ISSUE TITLE
关于类实例的属性

### ISSUE THREAD

**Issue by gaoteng-pro** [neolee/pilot#1155]
<img width="1440" alt="截屏2020-02-24下午6 58 23" src="https://user-images.githubusercontent.com/57254889/75148626-0d892480-573b-11ea-9dc6-72e401bd3bd8.png">

如上图，`a`是`Dog`类的实例，`kind`是类变量，`a.name`是实例变量，也是实例属性。`a.kind`和`a.name`的这些操作可以理解，但`apple`是`Dog`类里没有的，在赋值之后居然也可以当实例属性使用，有些不解。

**Comment by neolee** [comment]
Python 是一种非常动态的语言，很多东西都可以在运行时更改，包括对象的变量、方法，都可以在运行时添加和修改。

课上没有讲这个，因为对初学者来说并不推荐这么做，但 Python 完全支持这样的操作，在有些场合还挺好用。
