### ISSUE TITLE
code . 无法运行 VSCode（开始是可以直接打开的）

### ISSUE THREAD

**Issue by wangxsh06** [neolee/pilot#1156]
PS C:\Users\wangxx95\Code> code . （code 和.之间应该是有空格哈）
code : The term 'code' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the  name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ code .
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (code:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by neolee** [comment]
> 开始是可以直接打开

这是什么意思？之前 `code` 命令可以正常打开 Visual Studio Code？

**Comment by lxj376169569** [comment]
用管理员模式打开

**Comment by lxj376169569** [comment]
powershell admin

**Comment by wangxsh06** [comment]
李老师不好意思表达不清楚，是在电脑左下角-开始里面直接打开可以，但是用ConEmu打不开。

**Comment by wangxsh06** [comment]
多谢战友，我就是在powershell admin中操作的，报了一楼描述的错误。

**Comment by wangxsh06** [comment]
多谢各位，重启电脑再试就好了。
