### ISSUE TITLE
学习用书填空时，前面序列号未按数字顺序显示

### ISSUE THREAD

**Issue by dongua20** [neolee/pilot#1157]
<img width="441" alt="捕获" src="https://user-images.githubusercontent.com/61374512/75227282-d7a27980-57e8-11ea-9f84-361485e3f252.PNG">

**Comment by neolee** [comment]
那个序号是你执行的代码 cell 的次序，有时候你在同一个 cell 执行了多次，这个序号就升上去了。

你可以动手试试就知道咋回事了。
