### ISSUE TITLE
迭代器：平方数序列如何计算？

### ISSUE THREAD

**Issue by wangkai-china1993** [neolee/pilot#1159]
```python
class squares:
    def __init__(self, high):
        self.base = 0
        self.high = high
        
    def __iter__(self):
        return self
    
    def __next__(self):
        self.base += 1
        if self.base > self.high:
            raise StopIteration
        else:
            return self.base * self.base
        
        next = __next__
        
iter = squares(3)

for n in squares(3):
    print(n)
```
运行结果：

1
4
9

打扰了，老师朋友们。虽然是小问题，可是我就是不懂，squraes(3)在定义的函数中是如何计算的？对计算过程还不是很清晰，还有好多问题可以发在Issues吗？

**Comment by neolee** [comment]
问题都可以在 issues 系统里提。

不过在提之前我有一些建议：

1. 从头开始按部就班的学习课程，每一课的学习包括：自学教材 notebook -> 带着问题听音频录播课 -> 再次自学对应的 notebook 并照其内容自己在学习用书中输入和执行一遍，思考和搞懂每个例子。

2. 遇到不明白的部分，先温习对应的章节，比如你问的这个问题和函数、对象定义以及迭代器的章节有关，仔细的再读一遍。

3. 如果还有问题那就需要提问了，提问前一定要理清你的问题到底是什么；关于编程的典型问题是这样的：

> 下面这段代码，我预期它会这样这样，给出这样的结果，但实际上给出了那样的结果，这是为什么呢？

> 关于 XXX 的概念/操作，我没搞懂，我在网上找到了这样的例子，似乎解决了我的问题，我猜想可能是因为 OOXX，那么到底是不是呢？

在课程最开始的指引中我给出了如何正确提问的引文，可以好好学习下。

回到你这个问题，类似于”虽然小问题但我就是不懂“这样的提问，是没法回答也没什么欲望去回答的，你最好能先自己思考，然后提出你具体的问题点在哪里。

最后，Wiki 里有一些支线课程，其中关于 Visual Studio Code 的一课里有介绍如何单步调试自己的代码，可以学习，然后自己去调试一下，就知道程序是怎么执行的了。

**Comment by wangkai-china1993** [comment]
谢谢老师的指点，我明白了。
