### ISSUE TITLE
无法在学习用书中输入代码

### ISSUE THREAD

**Issue by hailinsu** [neolee/pilot#116]
仓库里的教材在线打开，学习用书里的代码被清空了，需要手动输入，但是我没有找到输入代码的地方
![Uploading KTGO[8QIVV17$S4G7AODP]E.png…]()

**Comment by neolee** [comment]
上传图片需要等 Uploading... 那个提示变成 `<img src=...>` 之后再提交。

**Comment by hailinsu** [comment]
能说的具体点吗，听不明白，没有见到updownloding

**Comment by neolee** [comment]
点这个页面上方的 Wiki，里面有说明。

**Comment by hailinsu** [comment]
![J32GPNB@ $~JB8)}HGJB9P](https://user-images.githubusercontent.com/48571418/67618784-57620c80-f826-11e9-973c-d74c27fb9b69.png)
哦哦 原来说的是issues，我还以为是ConEmu呢，不过确实没有注意到这个问题，现在知道了，那现在帮我看一下吧

**Comment by hailinsu** [comment]
![J32GPNB@ $~JB8)}HGJB9P](https://user-images.githubusercontent.com/48571418/67618811-9001e600-f826-11e9-9fd8-9f61859ecf4c.png)

**Comment by neolee** [comment]
你打开的这个不是学习用书，是完整教材。

你需要 fork 和 clone 的是学习用书的仓库： https://github.com/neolee/pilot-student
