### ISSUE TITLE
关于类的继承

### ISSUE THREAD

**Issue by gaoteng-pro** [neolee/pilot#1160]
老师，类的**继承**是不是可以简单地理解为，**子类把父类的类定义体里的所有代码，完全复制粘贴到子类的类定义体中，然后子类再根据需要去覆盖一些代码**。子类和父类代码一样的部分，不用再写，直接用，**就相当于这些代码已经写在了子类中一样**，这样理解可以吗？

**Comment by neolee** [comment]
……差不多吧。

**Comment by gaoteng-pro** [comment]
期待老师今晚的课，奥利给
