### ISSUE TITLE
定义类貌似不用加 () 但我加了还是可以运行

### ISSUE THREAD

**Issue by PanChuang2019** [neolee/pilot#1162]
![image](https://user-images.githubusercontent.com/48653618/75305277-a1b0d400-5880-11ea-8ef3-b67c9bef0287.png)

greeting后面貌似不用加（），但是我加了以后依然可以运行出来，请问加不加（），关系大吗？老师

**Comment by neolee** [comment]
括号里是想继承的父类名字，不写的话等于没有继承特定父类，可以省略括号。

所以类定义完整的语法其实是写括号的……
