### ISSUE TITLE
cell写好代码，按ctr + 回车，显示不出效果（也没有错误提示，只在代码行前面出现*）。

### ISSUE THREAD

**Issue by PanChuang2019** [neolee/pilot#1163]
![image](https://user-images.githubusercontent.com/48653618/75305629-9dd18180-5881-11ea-8391-e979ceef0570.png)

遇到很多次了，写好代码后，按ctr + 回车，却啥也没有显示（连错误都没有），请问老师这如何理解。

**Comment by neolee** [comment]
去看支线课程中关于 Jupyter Lab 的一课。
