### ISSUE TITLE
请问 _think(self,a) 和 self._think(a) 是不是等价的？

### ISSUE THREAD

**Issue by PanChuang2019** [neolee/pilot#1164]
![image](https://user-images.githubusercontent.com/48653618/75309195-4801d700-588b-11ea-8df7-a044428749b7.png)

老师，这里有个问题，上面定义的_think 函数是这样写`think(self,a)`，但是下面print ，却是`self.think(a)` 的形式， 所以想问一下，这两种写法是不是等价的。

**Comment by neolee** [comment]
没听课吧？重新去听一边关于面向对象的部分。
