### ISSUE TITLE
运行 pip install jupyterlab 报错（pyzmq）

### ISSUE THREAD

**Issue by shixiaodu** [neolee/pilot#1165]
![image](https://user-images.githubusercontent.com/59480593/75327297-17d02d80-58b7-11ea-9306-00e32f774ed5.png)
![image](https://user-images.githubusercontent.com/59480593/75327308-1ef73b80-58b7-11ea-8b25-f58dccbbb959.png)
图1是在命令行界面运行pip install jupyterlab报错，图2是看其他同学的问题的解答，做的常规检查，但是还是不知道是什么原因出错，请老师帮忙看下，谢谢

**Comment by neolee** [comment]
Duplicate of #1166
