### ISSUE TITLE
pip install jupyterlab 时出现错误提示（pyzmq）

### ISSUE THREAD

**Issue by pylsky** [neolee/pilot#1166]
win10系统，安装的是python3.7.4，在配套学习用书阶段进行到执行‘’pip install jupyterlab‘代码过程中，尝试了多次，都是同样的结果，代码执行了大段的白色代码后，突然出现大段红色代码报错，已经参照issues中同学们类似问题的老师解答的办法，把python卸载后重新安装（也是python3.7.4），但进行到‘’pip install jupyterlab‘时还是出现同样的报错，请老师同学们帮助指导一下怎么解决这个问题，感谢！
图片1至6是我最后一次执行‘’pip install jupyterlab‘代码过程中从输入代码到结果的全部内容的按顺序截图，图7是按照老师在其他同学提问中要求做的常规检查代码执行结果。

![1](https://user-images.githubusercontent.com/61292033/75329948-83b49500-58bb-11ea-87f3-27f62fd4a043.jpg)
图1

![2](https://user-images.githubusercontent.com/61292033/75329997-9202b100-58bb-11ea-80d5-7a16bc41b870.jpg)
图2

![3](https://user-images.githubusercontent.com/61292033/75330017-99c25580-58bb-11ea-86b8-13798fd7c615.jpg)
图3

![4](https://user-images.githubusercontent.com/61292033/75330046-a3e45400-58bb-11ea-81a2-6f90ecf031e7.jpg)
图4

![5](https://user-images.githubusercontent.com/61292033/75330070-acd52580-58bb-11ea-8b73-a2f56d262355.jpg)
图5

![6](https://user-images.githubusercontent.com/61292033/75330161-b2cb0680-58bb-11ea-8d60-2c3526ea13ac.jpg)
图6

![7](https://user-images.githubusercontent.com/61292033/75331581-ec9d0c80-58bd-11ea-8604-5d1586ac26c5.jpg)
图7

**Comment by pylsky** [comment]
补充一下：我的机器装的是win10

**Comment by shixiaodu** [comment]
我也遇到同样的错误，在线等解答

**Comment by pylsky** [comment]
报错里面有一段内容提示说需要微软Visual C++ 14，是不是意味着要让我们安装微软Visual C++ 14才行呢？还等老师一并指导一下。

**Comment by neolee** [comment]
是的，安装 Jupyter Lab 依赖于一个叫 pyzmq 的包，这个包刚刚升级，还没有现成的编译好的 Windows 版本，所以需要在你的电脑上编译一些 C 的库，而做这个编译需要 Visual C++ Build Tools，如果你的系统里没有就需要自行安装下。

https://visualstudio.microsoft.com/visual-cpp-build-tools/

**Comment by pylsky** [comment]
> 是的，安装Jupyter Lab依赖于一个叫pyzmq的包，这个包刚刚升级，还没有现成的编译好的Windows版本，所以需要在你的电脑上编译一些C的库，而做这个编译需要Visual C ++ Build工具，如果你的系统里没有就需要自行安装下。
> 
> https://visualstudio.microsoft.com/visual-cpp-build-tools/

您好老师，我现在已经可以通过浏览器进入图1这个页面了，是代表我已经按照您的指南把学习用书安装成功了是吧？另外我想再补充请教一下，昨天我通过您上面提供的Visual C ++ Build工具链接https://visualstudio.microsoft.com/visual-cpp-build-tools/进入的是图2图3的页面，好多个应用，半年没弄清楚要下载安装哪个应用，就装了Visual Studio 2019以及Community，我也不清楚两个具体是做什么的，但装完后运行pip install jupyterlab还是同样报错就都卸载了，然后在网上搜了一下找到https://www.microsoft.com/en-us/download/confirmation.aspx?id=48159这个地址（图4），然后下载了里面的那个软件，装好后居然pip install jupyterlab代码就一次性通过了。我就想补充请教一下，图4里面这个Microsoft Build Tools 2015和图2图3里面的C++ 生成工具这些软件有什么区别呢？为何装图2图3的代码还是报错，装了图4的就成功了？

![1](https://user-images.githubusercontent.com/61292033/75427608-cb9def80-5981-11ea-999f-a58e7451c04b.jpg)
图1

![2](https://user-images.githubusercontent.com/61292033/75428817-baee7900-5983-11ea-83ba-c82c1d9a3287.jpg)
图2

![3](https://user-images.githubusercontent.com/61292033/75428840-c0e45a00-5983-11ea-81a6-3cbd1a6b3cad.jpg)
图3

![4](https://user-images.githubusercontent.com/61292033/75428855-c641a480-5983-11ea-9109-00e21f9157fa.jpg)
图4

**Comment by neolee** [comment]
能打开浏览器进入 Jupyter Lab、能打开学习用书的 notebooks 就可以了。

Microsoft 的那几个下载，前面的是最新版本的 Visual Studio（2019），你后面成功的是早一些的 2015 版本，看来只有 2015 的版本是可以的，我已经改了前面回复里的链接，多谢你提供的信息。

另外，编译 Python 的一些 C 语言扩展，并不需要安装 Visual Studio 这样的大部头，只要安装里面的很小的一个组件（C++ Build Tools）就可以了，所以后面那个链接是比较好的。

**Comment by pylsky** [comment]
> 能打开浏览器进入 Jupyter Lab、能打开学习用书的 notebooks 就可以了。
> 
> Microsoft 的那几个下载，前面的是最新版本的 Visual Studio（2019），你后面成功的是早一些的 2015 版本，看来只有 2015 的版本是可以的，我已经改了前面回复里的链接，多谢你提供的信息。
> 
> 另外，编译 Python 的一些 C 语言扩展，并不需要安装 Visual Studio 这样的大部头，只要安装里面的很小的一个组件（C++ Build Tools）就可以了，所以后面那个链接是比较好的。

好的，谢谢老师解答。
