### ISSUE TITLE
关于组合原子与数量操作符的疑问

### ISSUE THREAD

**Issue by bennet569** [neolee/pilot#1169]
str = 'error wonderer severeness'
re.findall(r'[er]+', str)

代码如上，数量操作符‘+’只对之前的一个原子起作用，其定义为之前的那一个原子至少出现一次，是不是意味着结果一定是连个一样的原子？我认为应该是'ee'或者'rr'，str中没有前者，那结果应该是['rr']才对呀。

为什么教材中是['err', 'r', 'erer', 'e', 'ere', 'e']

**Comment by neolee** [comment]
正则表达式 `[er]` 的意思是，匹配字母 `e` **或者** `r`。

正则表达式 `[er]+` 的意思是，连续一个或多个字符，要么是 `e` 要么是 `r`。缺省配置下尽可能匹配最长的子串。
