### ISSUE TITLE
Jupyter Lab 无法打开学习用书

### ISSUE THREAD

**Issue by wangxsh06** [neolee/pilot#1170]
不知道是不是我的路径有问题，在ConEmu中执行Code或者pilot-sdudent 路径打开的Jupyter lab网页都是空白的，没有目录内容。

**Comment by wangxsh06** [comment]
不好意思刚才问题没编辑完就被快捷键发出去了。

在ConEmu的Code或者pilot-student 目录下打开的Jupyter lab网页都是空白的，没有目录内容。我确定书籍已经下载在Code 的student-pilot文件夹中。

**Comment by wangxsh06** [comment]
PS C:\Users\wangxx95> cd Code
PS C:\Users\wangxx95\Code> jupyter lab
[I 03:37:03.521 LabApp] JupyterLab extension loaded from c:\users\wangxx95\scoop\apps\python37\current\lib\site-packages\jupyterlab
[I 03:37:03.521 LabApp] JupyterLab application directory is c:\users\wangxx95\scoop\apps\python37\current\share\jupyter\lab
[I 03:37:04.670 LabApp] Serving notebooks from local directory: C:\Users\wangxx95\Code
[I 03:37:04.670 LabApp] The Jupyter Notebook is running at:
[I 03:37:04.670 LabApp] http://localhost:8888/?token=65e160e462a03fca49248ad3b57d303eb2063c8f73d82d83
[I 03:37:04.670 LabApp]  or http://127.0.0.1:8888/?token=65e160e462a03fca49248ad3b57d303eb2063c8f73d82d83
[I 03:37:04.671 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 03:37:04.736 LabApp]

    To access the notebook, open this file in a browser:
        file:///C:/Users/wangxx95/AppData/Roaming/jupyter/runtime/nbserver-13908-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=65e160e462a03fca49248ad3b57d303eb2063c8f73d82d83
     or http://127.0.0.1:8888/?token=65e160e462a03fca49248ad3b57d303eb2063c8f73d82d83
[I 03:39:53.065 LabApp] 302 GET /?token=65e160e462a03fca49248ad3b57d303eb2063c8f73d82d83 (127.0.0.1) 0.96ms

**Comment by dongua20** [comment]
因为你的学习用书是放在 pilot-student目录里，你在Code根目录打开jupyter lab 肯定是空白的
正确的做法：在输入cd Code 命令之后，再输入 cd pilot-student ， 然后再打开 jupyter lab

**Comment by neolee** [comment]
基本上应该是 @dongua20 同学说的问题吧。

建议 @wangxsh06 同学先看看支线课程里面向新手的几课，尤其是支线第一讲里关于命令行和“当前工作路径”的概念。

**Comment by wangxsh06** [comment]
谢谢二位，支线课程我会去学习。不过按照如下路径还是不行，实在不知道怎么回事了。。。

PS C:\Users\wangxx95> cd Code
PS C:\Users\wangxx95\Code> cd pilot-student
PS C:\Users\wangxx95\Code\pilot-student> jupyter lab
[I 20:24:16.620 LabApp] The port 8888 is already in use, trying another port.
[I 20:24:17.694 LabApp] JupyterLab extension loaded from c:\users\wangxx95\scoop\apps\python37\current\lib\site-packages\jupyterlab
[I 20:24:17.694 LabApp] JupyterLab application directory is c:\users\wangxx95\scoop\apps\python37\current\share\jupyter\lab
[I 20:24:19.008 LabApp] Serving notebooks from local directory: C:\Users\wangxx95\Code\pilot-student
[I 20:24:19.102 LabApp] The Jupyter Notebook is running at:
[I 20:24:19.106 LabApp] http://localhost:8889/?token=0b64c5b7ebb89fa81e695efc8a92a0912b7bc60f5612b316
[I 20:24:19.106 LabApp]  or http://127.0.0.1:8889/?token=0b64c5b7ebb89fa81e695efc8a92a0912b7bc60f5612b316
[I 20:24:19.107 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 20:24:19.207 LabApp]

    To access the notebook, open this file in a browser:
        file:///C:/Users/wangxx95/AppData/Roaming/jupyter/runtime/nbserver-1640-open.html
    Or copy and paste one of these URLs:
        http://localhost:8889/?token=0b64c5b7ebb89fa81e695efc8a92a0912b7bc60f5612b316
     or http://127.0.0.1:8889/?token=0b64c5b7ebb89fa81e695efc8a92a0912b7bc60f5612b316

**Comment by neolee** [comment]
咋不对？打开的页面啥样子？

**Comment by wangxsh06** [comment]
页面是空白的，没有任何内容。复制网址到浏览器一样的结果。

PS C:\Users\wangxx95> cd Code
PS C:\Users\wangxx95\Code> cd pilot-student
PS C:\Users\wangxx95\Code\pilot-student> jupyter lab
[I 19:30:29.993 LabApp] JupyterLab extension loaded from c:\users\wangxx95\scoop\apps\python37\current\lib\site-packages\jupyterlab
[I 19:30:29.994 LabApp] JupyterLab application directory is c:\users\wangxx95\scoop\apps\python37\current\share\jupyter\lab
[I 19:30:31.147 LabApp] Serving notebooks from local directory: C:\Users\wangxx95\Code\pilot-student
[I 19:30:31.148 LabApp] The Jupyter Notebook is running at:
[I 19:30:31.148 LabApp] http://localhost:8888/?token=e34494f433d96387b1b453cc9e056ac863782ad51283165c
[I 19:30:31.148 LabApp]  or http://127.0.0.1:8888/?token=e34494f433d96387b1b453cc9e056ac863782ad51283165c
[I 19:30:31.148 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 19:30:31.224 LabApp]

    To access the notebook, open this file in a browser:
        file:///C:/Users/wangxx95/AppData/Roaming/jupyter/runtime/nbserver-11572-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=e34494f433d96387b1b453cc9e056ac863782ad51283165c
     or http://127.0.0.1:8888/?token=e34494f433d96387b1b453cc9e056ac863782ad51283165c
[I 19:32:27.053 LabApp] 302 GET /?token=e34494f433d96387b1b453cc9e056ac863782ad51283165c (127.0.0.1) 1.00ms
[I 19:32:46.751 LabApp] 302 GET /?token=e34494f433d96387b1b453cc9e056ac863782ad51283165c (127.0.0.1) 0.00ms
[I 19:36:43.060 LabApp] 302 GET /?token=e34494f433d96387b1b453cc9e056ac863782ad51283165c (127.0.0.1) 0.99ms

**Comment by neolee** [comment]
你用的是 IE 吧？Jupyter Lab 不支持老的 IE，换用别的浏览器吧。

**Comment by wangxsh06** [comment]
谢谢老师，换浏览器就好了。以后有问题我尽量先google。
