### ISSUE TITLE
求助 nbviewer 网站无法登陆时的替代方案

### ISSUE THREAD

**Issue by moonwmh** [neolee/pilot#1171]
老师，
今天nbviewer无法登陆，提示服务器没反应，造成无法打开教材。

想了替代方案，把pilot教材clone到本地，然后用jupyter lab 打开，但是似乎download speed 太慢。

**问题：**
- 其他的打开pilot教材方式？
- 添加nbviewer网站的hosts时的网址和IP？

**谢谢**

<img width="768" alt="截屏2020-02-29上午8 27 18" src="https://user-images.githubusercontent.com/48578043/75596890-7111aa00-5acd-11ea-9fae-3d2527fc1dd8.png">

**Comment by neolee** [comment]
如果 nbviwer 打不开，那就说明你的网络问题挺大的，干啥都不会太顺吧？还是等换个时间试试吧。

**Comment by moonwmh** [comment]
打开那啥，果然就那啥了。
不打开那啥，还有打开教材ipynb的方案不？
