### ISSUE TITLE
自动化视频课里提到的那些 Excel 表是放在哪个仓库的？

### ISSUE THREAD

**Issue by xiaoerhai** [neolee/pilot#1172]

**Comment by neolee** [comment]
来自 Office 官方的模板，可以自己制作。

**Comment by xiaoerhai** [comment]
嗯嗯，下午自己简单地制作了2个，当时是想节省时间所以提了issue。听完视频的讲解，并试着实操后遇到了好多报错，都是VScode提示我的，目前只剩下一个没有解决了，实在找不出是什么问题，麻烦李骏老师再帮忙解答下。具体报错如下图：
![image](https://user-images.githubusercontent.com/48662601/75606823-ad73f300-5b2b-11ea-982f-8cedde9ac075.png)

**Comment by neolee** [comment]
你装了 xlwt 这个包吗？如果装了的话应该没问题。

**Comment by xiaoerhai** [comment]
装了的：
![image](https://user-images.githubusercontent.com/48662601/75618599-b1475a00-5bab-11ea-9d02-99cdf62aba0c.png)


但vscode提示还是有错误。

**Comment by neolee** [comment]
把代码和运行代码时出的错发来看看。

**Comment by xiaoerhai** [comment]
我今天输入对应的参数运行后没有任何报错的提示，命令行编译器当作什么都没发生过直接换行了，如下截图所示：
![image](https://user-images.githubusercontent.com/48662601/75640456-22e8dc00-5c70-11ea-8aae-b601f74a6abc.png)

我看了发件箱和收件箱都没有对应的邮件生成。

**Comment by neolee** [comment]
把那个程序文件作为附件发出来。

**Comment by xiaoerhai** [comment]
import pandas as pd

import smtplib
import ssl
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email.mime.text import MIMEText
from email.utils import formatdate
from email import encoders

from pathlib import Path


def read_excel_data(path):
    df = pd.read_excel(path,header=None)
    row = {}
    row['ID'] = df.iloc[1,0]
    total = df.loc[df[0] == '总计']
    row['酒店'] = total.iloc[0,1]
    row['交通费'] = total.iloc[0,2]
    row['餐饮'] = total.iloc[0,3]
    row['总计'] = total.iloc[0,4]
    return row


def send_mail(send_from, send_to, subject, text, file_path, server, port, username='', password='', tls=True):
    msg = MIMEMultipart()
    msg['From'] = send_from
    msg['To'] = send_to
    msg['Date'] = formatdate(localtime = True)
    msg['Subject'] = subject
    msg.attach(MIMEText(text))

    part = MIMEBase('application', 'octet-stream')
    part.set_payload(open(file_path, 'rb').read())
    encoders.encode_base64(part)
    part.add_header('Content-Disposition', f'attachment; filename="{file_path.name}"')
    msg.attach(part)
    
    smtp = smtplib.SMTP(server, port)
    if tls:
        smtp.starttls()
    
    smtp.login(username, password)
    smtp.sendmail(send_from, send_to, msg.as_string())
    smtp.quit()


def main():
    CWD = './assets'
    SEND_FROM = '360248165@qq.com'
    SEND_TO = 'erhai@dudu.com'
    SMTP_SERVER = 'smtp.exmail.qq.com'
    SMTP_PORT = 25
    SMTP_USERNAME = 'erhai@dudu.com'
    SMTP_PASSWORD = '123456'

    p = Path(CWD)
    rows = []
    for q in p.glob('**/[!All]*.xlsx'):
        rows.append(read_excel_data(q))
    df = pd.DataFrame(rows)
    writer = pd.ExcelWriter(p / 'All.xls', engine='xlwt')
    df.to_excel(writer)
    writer.save() 

    send_mail(SEND_FROM, SEND_TO,'每月费用报销汇总表', '请查看附件表格', p / 'All.xls',  SMTP_SERVER, SMTP_PORT, username=SMTP_USERNAME, password=SMTP_PASSWORD)


    if __name__ == '__main__':
        main()

**Comment by xiaoerhai** [comment]
为了避免暴露个人隐私，main方法里的6个参数都不是真实的。

**Comment by neolee** [comment]
所以这个执行没报错，那么你收到邮件了吗？

**Comment by xiaoerhai** [comment]
没有收到，我怀疑是发件服务器相关的问题造成的。Foxmail里的发件服务器端口是465，不是视频教材里提到的25；另外，我输入的password的是客户端专用密码。

**Comment by neolee** [comment]
这个例子最好一步一步做，不要一上来就全部一起。每一步可以独立地验证，没问题了再组合起来，这样就知道问题在哪里。

**Comment by xiaoerhai** [comment]
嗯嗯，上周我实操了以下3个子过程：
1）读写Excel格式；2）访问文件系统；3）发送邮件。
前面2个子过程没有问题，第3个子过程`发邮件`我是按[菜鸟教程](https://www.runoob.com/python3/python3-smtp.html)上的`使用第三方 SMTP 服务发送`教程完成的。另外，在践行群同学的帮助下，解决了上周反馈的问题（输入对应的参数运行后没有任何报错的提示，命令行编译器当作什么都没发生过直接换行了），原因是最后一段代码`if __name__ == '__main__'`缩进了，放进了函数main里面。纠正后，我把3个子过程全部合在一起执行了，出现了一下报错：
![image](https://user-images.githubusercontent.com/48662601/76136755-21eceb80-6070-11ea-9710-244984f9a9c5.png)


但是我当时在jupyter lab里执行是没问题的：
![image](https://user-images.githubusercontent.com/48662601/76136723-c4f13580-606f-11ea-9408-92adc5b705b1.png)
