### ISSUE TITLE
聊天机器人循环计算结果 print 前面不需要加 else 这样的条件限定语句吗？

### ISSUE THREAD

**Issue by PanChuang2019** [neolee/pilot#1173]
![image](https://user-images.githubusercontent.com/48653618/75603618-1b5bf280-5b0b-11ea-930a-f11a67d873b4.png)

老师，请问这里print前面 我记得是不是应该有个else：的格式的。

**Comment by neolee** [comment]
为啥要有 else 啊？

**Comment by PanChuang2019** [comment]
> 为啥要有 else 啊？

因为if...else 是配套的吧，以上的代码，我理解为 如果（if）输入语句中有那些特定字符，就打断，跳出循环。除此之外的情况（else）就 print 后面的返回值。还是说 else 有时候可以省掉不写。

**Comment by neolee** [comment]
你理解的不对。

`if` 不一定要有 `else`。

`break` 跳出 `while` 循环。

**Comment by qixinsame** [comment]
我在学习到这儿的时候脑子里也顿了一下，后来查了Python官方文档，发现else是optional的。
https://docs.python.org/3.7/tutorial/controlflow.html

带else的语句块，如if...elif...elif...else，思维的重心是在“对一个有效条件集合的遍历”。
而不带else的语句，思维的重心是“我这么个条件需要check一下”。

回到这个case，其实你非要用else也是可以的，但是这个“语感”就不对了，显得啰嗦。
