### ISSUE TITLE
Use case of __init__.py

### ISSUE THREAD

**Issue by ALONSOlkp89** [neolee/pilot#1177]
When reading the lecture session 2, lesson 3, there is a file called _ _init_ _.py, could you please clarify more about how to use this file? when shall I add this file in the directory?
When I tried the below examples of the textbook, I found out it both works well with or without __init__.py. Thus, I am confused about the use case of _ _init_ _.py.
~/Code/some_project:
├── modules/
│   ├── _ _init_ _.py
│   ├── auth.py
│   ├── helper.py
│   ├── math/
│   │   ├── calculus.py
│   │   ├── logic.py
│   └── string/
│       ├── codec.py
│       └── l10n.py
├── setup.py
└── main.py

**Comment by neolee** [comment]
涉及到 Python 的包的沿革，参见 #775
