### ISSUE TITLE
GPU 属于计算机 CPU 吗？

### ISSUE THREAD

**Issue by Yao-Jing-2020** [neolee/pilot#1179]
复习理解编程语言的时候，注意到：
计算机包括：CPU、内存和外设；
然而计算机又有很多芯片：CPU，GPU……；那么GPU属于计算机CPU吗？不属于计算机CPU，属于什么？
我的理解：按GPU的功能算，也是CPU的部分，执行计算机的命令；但是GPU又与CPU不同，一个擅长整数运算一个浮点数，这就又不是CPU？

**Comment by neolee** [comment]
GPU 也是一种芯片，可以通过“主板”和 CPU 连在一起，扩展了 CPU 能力的芯片。架构上比外设离 CPU 近一些，但也是需要操作系统调用特定的驱动程序才能工作的。
