### ISSUE TITLE
字符串如何比较大小

### ISSUE THREAD

**Issue by chengfeng195** [neolee/pilot#1182]

**Comment by neolee** [comment]
为啥一样的问题发了三次？

**Comment by chengfeng195** [comment]
第一次发问，怕问的不清楚，第二个问题我给撤了啊，请老师见谅，第一次发问就收到老师回复，正是莫大的鼓励，编程我的较慢，但收获很大，每一次重复学习就加深了好多

**Comment by neolee** [comment]
你其实可以反复修改你的问题，你的标题和内容都是可以编辑的，不需要重提。
