### ISSUE TITLE
安装 python 失败

### ISSUE THREAD

**Issue by liuy8088** [neolee/pilot#1184]
![图片1](https://user-images.githubusercontent.com/32415073/75756428-9c192980-5d6b-11ea-9dac-091f1101b055.png)

**Comment by neolee** [comment]
这个指南里说了呀，安装失败的 git 和 python 都需要删掉重装，直至成功。

```shell
scoop uninstall git python37
scoop install git python37@3.7.4
```

**Comment by liuy8088** [comment]
好的，我再试试
谢谢老师
