### ISSUE TITLE
无法在命令行调出VSCode

### ISSUE THREAD

**Issue by michelle8708** [neolee/pilot#1185]
之前已经在VSCode 里面install 'code' command in PATH了，刚刚安装的时候，在命令行输入 code 可以调出 VSCode.
等到第二天重新打开电脑，启动命令行，输入 code 显示 command not found .
于是我又重新安装了一次，这次输入code又可以调出VSCode
第三天又不行了
请问是要在电脑启动了VSCode的前提之下， 才能在命令行调出吗？

**Comment by neolee** [comment]
你是 macOS？没有把 VSCode 拷贝到 Applications 目录吧？
