### ISSUE TITLE
在“逻辑的判断与分支”那节，举例定义 type_0() 函数，运行时出现异常！

### ISSUE THREAD

**Issue by fzs1136199440** [neolee/pilot#1186]
![image](https://user-images.githubusercontent.com/48565470/75768691-ca086900-5d7f-11ea-941e-d6513af8b63a.png)
如图所见，为什么 type_0(True) 的返回值是 ’int‘呢？

**Comment by neolee** [comment]
你没听课吧？这个专门在课上讲过。

**Comment by fzs1136199440** [comment]
是的，老师，还没学到那一课，看了您的提醒然后我去翻了践行群的语音课，往后翻在第四课找到了，谢谢老师。我就应该先去看看issues的，但是当时死活找不到原因，心里一慌，就只想到问老师了，看来还是自学经验太少，经历得不够多，需要多多践行啊！
