### ISSUE TITLE
Iterator 课后练习运行结果有点问题

### ISSUE THREAD

**Issue by zhangSen1987** [neolee/pilot#1187]
![prime](https://user-images.githubusercontent.com/53714512/75988805-1e048080-5f2d-11ea-8e0a-b03433ae9620.png)
如图，为什么会扔出27这个数字，我用Google没找到答案。我这个问题，该从哪里入手去查找错误呢...

**Comment by neolee** [comment]
你这个实现逻辑上不对呀，其实之前有几个同学有类似的问题，比如这个 #849 你可以先看看，然后类似我在里面的回复的思路，检查下自己的代码。
