### ISSUE TITLE
list 转化为 DataFrame 列顺序调整方法

### ISSUE THREAD

**Issue by sxuya** [neolee/pilot#1188]
## 情况
自动化的课程。
老师的 bilibili 视频里面，list 转化为 DataFrame 后，顺序是正常的。

但是自己的结果却是混乱、打乱的。

## 目的
将 DataFrame 的数据的列进行调整

## 方法
直接在后面加入抬头的 list 就好。
如下：
```python
df_all = pd.DataFrame([row])[['员工ID', '员工姓名', '开始时间', '结束时间', '网络', '住宿', '交通', '餐饮', '招待', '其他', '总计']]
```
参考连接：https://www.cnblogs.com/huahuayu/p/8324755.html

## 尝试的错误的方法
如下：
```python
df_all = pd.DataFrame([row]).reindex(['员工ID', '员工姓名', '开始时间', '结束时间', '网络', '住宿', '交通', '餐饮', '招待', '其他', '总计'])
```

## 接下来的困惑
像这个问题，完全不是 method 的问题，看了文档里面所有的 method 就是没有找到解决的方法，最后就直接搜索中文了。
像这种，是方向完全找错的情况，如何在英文世界里进行重新分析？

**Comment by neolee** [comment]
能看看你的完整代码么？仅凭这里的信息无法判断到底发生了什么。
