### ISSUE TITLE
pandas 读取 mysql 里的字符串数据

### ISSUE THREAD

**Issue by iceberg-yuan** [neolee/pilot#1189]
pandas读取mysql里的表，字符串型的数据显示好像是内存地址？数值型的没问题。

![pandas_read_sql](https://user-images.githubusercontent.com/57003256/76096201-a738b780-6000-11ea-9a9f-c82cc15292ed.png)

**Comment by neolee** [comment]
这个要看你的数据库里字符串是什么编码了，如果不是 utf-8 可能会需要做处理才行。
