### ISSUE TITLE
到安装 git To get Git to recognise OpenSSH, you will need to run  scoop install openssh

### ISSUE THREAD

**Issue by Weijing14** [neolee/pilot#119]
Creating shim for 'tig'.
Creating shim for 'git-bash'.
Creating shortcut for Git Bash (git-bash.exe)
Running post-install script...
'git' (2.23.0.windows.1) was installed successfully!
Notes
-----
To get Git to recognise OpenSSH, you will need to run

scoop install openssh
[environment]::setenvironmentvariable('GIT_SSH', (resolve-path (scoop which
ssh)), 'USER')

and then restart powershell.
PS C:\Users\炜婧> scoop.update
scoop.update : 无法将“scoop.update”项识别为 cmdlet、函数、脚本文件或可运行程
序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ scoop.update
+ ~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (scoop.update:String) [], Comman
   dNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by neolee** [comment]
看清楚指南里的命令，以及你实际输入的命令……

**Comment by neolee** [comment]
至于那句提示，目前可以不管它。

**Comment by Weijing14** [comment]
老师辛苦了~汗~~~~~

**Comment by myhappylife2002** [comment]
To get Git to recognise OpenSSH, you will need to run

scoop install openssh
[environment]::setenvironmentvariable('GIT_SSH', (resolve-path (scoop which
ssh)), 'USER')

and then restart powershell.
老师所说的那句提示，是指以上文字吗？翻遍了所有问题，才找到与我目前遇到的问题一样的，实在不好意思，还是要麻烦老师。

**Comment by neolee** [comment]
@myhappylife2002 

你目前是啥问题，可以另开 issue 说明。
