### ISSUE TITLE
git commit 然后怎么退出呢？

### ISSUE THREAD

**Issue by yiguo-hu** [neolee/pilot#1190]
![image](https://user-images.githubusercontent.com/51398930/76135316-d41cb700-6060-11ea-8809-f76a8fb90321.png)

**Comment by neolee** [comment]
你没有按照教程里做好使用 git 前的配置，没有指定用于编辑 commit message 的编辑器，所以使用了却省的 vi 编辑器，这个编辑器可不是一会就能学会的。

目前你需要按 ESC 键，然后输入 `:wq` 然后回车，可以保存信息并完成提交。

然后你还是要仔细看教程照做。
