### ISSUE TITLE
随机整数在 while 循环体外面时出现无限循环？

### ISSUE THREAD

**Issue by zorahong57** [neolee/pilot#1191]
```python
from random import randrange

while True:
    n = randrange(-2, 4)
    if n < 0:
        break
    elif n % 2 == 0:
        print(n, "is an even number.")
    else:
        print(n, "is an odd number.")
```
在上面的函数中，`n = randrange(-2, 4)` 如果在循环体里面，就不会无限循环；而在循环体外面，则会出现无限循环。

不明白的是，同样是随机取一个数来做循环，为什么这个数在循环体里面，就不会导致无限循环；在循环体外面，就会无限循环，这是什么原因呢？

![Annotation 2020-03-07 164102](https://user-images.githubusercontent.com/60477266/76140168-8ae55b00-6092-11ea-83c5-b82932920497.jpg)

**Comment by neolee** [comment]
如果 `n = randrange(-2, 4)` 在循环体外，n 取到一个值之后就再也不会变了，比如你这个取到了 3，n 就一直是 3 了；进入循环之后永远也不会触发 `break`，那么这个循环由于条件是固定的 `True`，就一直执行下去了。

而那句代码写到 while 里面就不同了，每循环一次都会给 n 一个新的随机数，总有随机到一个负数的情况，从而触发 `break` 而终止循环。

你需要好好的运用一下元认知能力，看看这个问题你为啥自己没有想明白，你是不理解循环的概念，还是不理解 `while` 的工作机制，还是不理解 `while True` 还是不理解随机数，还是不理解 `break` 呢？

**Comment by zorahong57** [comment]
是while True没弄明白，现在搞清楚了，谢谢老师
