### ISSUE TITLE
Windows 无法启动 Redis 问题

### ISSUE THREAD

**Issue by wangcyber** [neolee/pilot#1194]
redis安装成功
![03](https://user-images.githubusercontent.com/60456753/76155634-6ee0c880-6129-11ea-82c2-44738f3581f7.PNG)

电脑环境变量path路径如图
![0033](https://user-images.githubusercontent.com/60456753/76155662-dd258b00-6129-11ea-9d31-c660b52eb3b1.PNG)

启动redis时，如图所示出现拒绝访问。
![REDIS](https://user-images.githubusercontent.com/60456753/76155551-6e93fd80-6128-11ea-8247-cab03bc233a4.PNG)

**Comment by neolee** [comment]
参考 #881 和 #740

**Comment by wangcyber** [comment]
问题已经解决
