### ISSUE TITLE
执行：  scoop install nodejs 时显示远程主机关闭了现有连接，重新安装安装不上了。

### ISSUE THREAD

**Issue by houliang007** [neolee/pilot#1196]
![微信截图_20200308122118](https://user-images.githubusercontent.com/57027487/76156629-0d742600-6138-11ea-89a8-b671cef4dcd9.png)
请问这种情况接下来怎么办？

**Comment by neolee** [comment]
这问题问过多次了，Wiki 里也有写，先 `scoop uninstall xxx` 然后 `scoop install xxx`。
