### ISSUE TITLE
启动 jupyter lab 浏览器里啥也没有是咋回事？

### ISSUE THREAD

**Issue by houliang007** [neolee/pilot#1197]
![微信截图_20200308143339](https://user-images.githubusercontent.com/57027487/76157856-0bb35e00-614a-11ea-84f2-a07ce4db1fbf.png)
启动 jupyter lab 浏览器里啥也没有是咋回事？挣扎了半天也没搞明白。

**Comment by neolee** [comment]
这个问题也被问过很多次了，比如 #1126
