### ISSUE TITLE
启动 jupyter lab 后浏览器弹出的窗口里什么也没有咋回事？

### ISSUE THREAD

**Issue by houliang007** [neolee/pilot#1199]
![1](https://user-images.githubusercontent.com/57027487/76158234-ae6ddb80-614e-11ea-8c0c-fead8f7a3919.png)
![2](https://user-images.githubusercontent.com/57027487/76158237-af9f0880-614e-11ea-8b96-e51c814fb6c0.png)
启动 jupyter lab 后浏览器弹出的窗口里什么也没有咋回事？谁能帮帮我，谢谢。

**Comment by neolee** [comment]
你发的 issue 都是可以反复修改的（标题和内容），不要关了一个又开一个。尤其是之前那个我已经回了（ #1197 ），所以你说这咋办呢？要我再抄一次过来么……

**Comment by houliang007** [comment]
我把默认浏览器设置成谷歌浏览器了，现在应该好了，谢谢老师。
