### ISSUE TITLE
运行 Homebrew 自检命令：brew doctor   提示警告

### ISSUE THREAD

**Issue by tsao86** [neolee/pilot#12]
Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libD4P11_CCB.dylib
  /usr/local/lib/libD4PinPad_CCB.dylib
  /usr/local/lib/libD4Token_CCB.dylib

**Comment by neolee** [comment]
这个是说你的 /usr/local/lib 下面有它不认识的文件，如果是你另外安装的就没啥问题，可以不管它。
