### ISSUE TITLE
VSCode 安装完毕后出现的问题 code 命令无效

### ISSUE THREAD

**Issue by tigersummer** [neolee/pilot#120]
![Cutter_2019-10-26 000003](https://user-images.githubusercontent.com/48619978/67619448-63ea6300-f82e-11e9-9630-add4d325bed0.png)

**Comment by tigersummer** [comment]
由于第一次下载VScode时，下载的是User 版本，担心这个引发了上述错误，于是卸载，然后重新下载VScode System版本，再次安装，可还是无法解决这个问题！

**Comment by neolee** [comment]
Visual Studio Code  User Setup 版本是没问题的。你这个不知道为啥，可以试试重启 Windows 看看？

**Comment by wangbingfeng** [comment]
should restart PowerShell, then re-execute the command.

**Comment by zechenglu** [comment]
> 
> 
> Visual Studio Code User Setup 版本是没问题的。你这个不知道为啥，可以试试重启 Windows 看看？
我也遇到了同样的问题，怎么解决。 code. 不能执行

**Comment by neolee** [comment]
@zechenglu 上面不是说了么，重启 PowerShell 界面或者重启 WIndows 都可以试试。
