### ISSUE TITLE
运行jupyter lab后让输入令牌

### ISSUE THREAD

**Issue by 1137337921** [neolee/pilot#1201]
Token authentication is enabled
If no password has been configured, you need to open the notebook server with its login token in the URL, or paste it above. This requirement will be lifted if you enable a password.
The command:
jupyter notebook listwill show you the URLs of running servers with their tokens, which you can copy and paste into your browser. For example:
Currently running servers:
http://localhost:8888/?token=c8de56fa... :: /Users/you/notebooks
or you can paste just the token value into the password field on this page.
See the documentation on how to enable a password in place of token authentication, if you would like to avoid dealing with random tokens.
Cookies are required for authenticated access to notebooks.
Setup a Password
You can also setup a password by entering your token and a new password on the fields below:

**Comment by wangfeiyang-github** [comment]
你好，我也遇到了同样的问题，我是在启动jupyter的时候,如果用root用户就不会出现此种情况，要是换成其它用户就会出现这种情况，这种问题怎么解决呀？烦请赐教一下😊
