### ISSUE TITLE
运行 jupyter lab 后让输入令牌

### ISSUE THREAD

**Issue by 1137337921** [neolee/pilot#1202]
运行 jupyter lab 后让输入令牌，输入 token= 后面的内容也不对，不知道哪个是令牌或者密码。

Token authentication is enabled
If no password has been configured, you need to open the notebook server with its login token in the URL, or paste it above. This requirement will be lifted if you enable a password.
The command:
jupyter notebook listwill show you the URLs of running servers with their tokens, which you can copy and paste into your browser. For example:
Currently running servers:
http://localhost:8888/?token=c8de56fa... :: /Users/you/notebooks
or you can paste just the token value into the password field on this page.
See the documentation on how to enable a password in place of token authentication, if you would like to avoid dealing with random tokens.
Cookies are required for authenticated access to notebooks.
Setup a Password
You can also setup a password by entering your token and a new password on the fields below:

**Comment by neolee** [comment]
为什么同一个问题要问两次呢？你开的 issue 你是可以反复修改的，不需要关一个再开一个新的。

你这个问题，正常情况下你在命令行运行 `jupyter lab` 之后会自动打开 Lab 的页面，也会自动传 token 进去，所以不需要专门登录验证。现在似乎你遇到了问题，不过你目前提供的信息不够，你需要告诉我：

1. 你运行 `jupyter lab` 的命令行界面上发生了什么，最好给一个截图；
2. 你的浏览器有没有自动打开？如果是自动打开，出现的页面什么样子，最好给一个截图；如果不是自动打开的，那么你后面做了什么，又得到一个什么样的页面，最好也给一个截图。

GitHub issues 里面可以上传截图，把你的截图拖到这里的输入框里，等待 'Uploading...' 那句话消失，插入图片的代码出现，再提交就可以了（这个具体在上面的 Wiki 链接里也有说）。

**Comment by 1137337921** [comment]
![8149a3c56626d69e6a3df0df0f5e94f](https://user-images.githubusercontent.com/56952532/76199558-0b3ec400-622b-11ea-88ec-5a3bc6d8fafd.png)
![17abce1558292561672e334863442e2](https://user-images.githubusercontent.com/56952532/76199562-0c6ff100-622b-11ea-86f0-c7ca39b3c9a4.png)
![76ac5491a9bd55d48631ab4e9379e4d](https://user-images.githubusercontent.com/56952532/76199570-1134a500-622b-11ea-8df4-55e03179b183.png)

老师：我S1 课程那时候克隆的时候应该克隆的您的学习用书，应该在c  盘，那时候直接运行（jupyter lab）可以直接打开页面，S2课程我好像直接克隆到D 盘了，克隆的我的学习用书，克隆好后运行jupyter lab 就会出现上面的空白页面，我就把http://localhost:8888/lab粘贴到浏览器上也能打开jupyter lab学习用书 ，还做了2节的S2课程，然后放假我上班后照着之前的步奏就出现了让输入“令牌的”页面

**Comment by neolee** [comment]
第一，Jupyter Lab 不支持 IE，用 IE 只会看到空白页面；你用 Chrome 之类的浏览器就没问题。

第二，使用 Chrome 可以直接修改系统的缺省浏览器设置，那样自动打开的就是 Chrome；如果不想这样，那就手动打开 Chrome，然后贴地址进去，地址是你运行 `jupyter lab` 的那个命令行里，`http://localhost:8888/?token=...` 的那一整行，包括因为显示不下自动换行了的那几个字符也要一起。你在 ComEnu 窗口里用鼠标选中那一整串地址，ConEmu 就自动帮你拷贝了，你去 Chrome 地址栏粘贴就行了。
