### ISSUE TITLE
git 创建新的 commit

### ISSUE THREAD

**Issue by sooolinw** [neolee/pilot#1203]
命令行 git commit之后，waiting for your editor to close the file, 但紧接着这行提示消失，又提示aborting commit due to empty commit message; VS Code也正常打开了，按照指引操作，无法正常进行
![QQ图片20200309185022](https://user-images.githubusercontent.com/48663234/76209715-81e4bd00-623d-11ea-9542-16fe66c1b36c.png)

**Comment by neolee** [comment]
执行 `git config -l` 给我看看，多半是你的 `core.editor` 配置不对。

**Comment by sooolinw** [comment]
![QQ截图20200309230941](https://user-images.githubusercontent.com/48663234/76228128-45c05500-625b-11ea-9730-72eee924c82e.jpg)

**Comment by neolee** [comment]
仔细看 Git 教程，`core.editor` 的值是 `code -w` 而不是 `code`。
