### ISSUE TITLE
【求助】在运行“pip3 install jupyterlab”之后出现大量的红字。

### ISSUE THREAD

**Issue by Bora-ST** [neolee/pilot#1204]
![截屏2020-03-0920 25 01](https://user-images.githubusercontent.com/56573638/76212959-937d9300-6244-11ea-889f-760b1a203e74.png)

![截屏2020-03-0920 32 39](https://user-images.githubusercontent.com/56573638/76213239-3afac580-6245-11ea-9e67-d93944d3a4ca.png)
老师您好，小白求助，以上是截屏。我的系统是MAC。
我该怎么办呢？

**Comment by neolee** [comment]
网络问题，需要换时间或者换网络重试，或者试试网络代理。

**Comment by Bora-ST** [comment]
好的，非常感谢老师，我知道了。我由于不会操作而发了两次问题，我很抱歉。
