### ISSUE TITLE
键入命令 “pip install jupyter” 后出现大量红字

### ISSUE THREAD

**Issue by Bora-ST** [neolee/pilot#1205]
以下是我的MAC的配置截图，以及问题部分的截图，新手小白，还请老师多多指点。
![截屏2020-03-0920 32 39](https://user-images.githubusercontent.com/56573638/76219039-266ffa80-6250-11ea-9f20-1ab9e84bcf2b.png)
![截屏2020-03-0921 46 35](https://user-images.githubusercontent.com/56573638/76219043-27a12780-6250-11ea-925c-91e34208e237.png)

**Comment by neolee** [comment]
不要一个问题问两次，你发的 issue 都可以反复编辑，重发是无意义的。

我已经在你另一个问题里给出了答复 #1204
