### ISSUE TITLE
对 pandas 下的数据类型不理解

### ISSUE THREAD

**Issue by powerzhengh** [neolee/pilot#1207]
**目标：**
通过转化列数据类型，按月、按年统计供应商、品牌销售情况。

**原始数据类型：**
![Snipaste_2020-03-10_09-25-22](https://user-images.githubusercontent.com/58015512/76270976-0f61f480-62b2-11ea-99a9-734d8094dafd.png)
**google查询方法：**
to_datetime()
**对日期列进行转换后：**
![Snipaste_2020-03-10_09-24-56](https://user-images.githubusercontent.com/58015512/76271003-1db01080-62b2-11ea-900c-a17fb8dc1652.png)
**问题:**
通过type检测后依然为pandas.core.series.Series，无法获取年，月数据。

**Comment by neolee** [comment]
从你的描述看，你已经把你的数据装进了 pandas 的 DataFrame，有 14 个列和十万多行数据。

在 DataFrame 中，每个列都是一个 Series 类型的对象，这个类型本质上就是个 numpy 数组。我在 Scientific Python 这个支线课程中讲过，numpy 数组和 Python 的列表有个区别，就是 numpy 数组里元素的数据类型必须一致，可以用 `dtype` 这个属性看到数组元素的数据类型。

所以你要分清楚“容器”和“容器内元素”的数据类型。你抽出的某一列数据，这是个容器，其类型是 Series（本质是 numpy Array）；然后你看这个列的输出，最下面有个 `dtype`，那里显示的是容器内 元素的数据类型，是 `datetime64`。

然后你的目标是按照年月来统计数据，这里比较好的办法是从销售时间这一列出发，构造出两个新的列，分别是“年”和“年+月”这样的字符串，然后用新的列做 group 就可以了。

本周三会发布新一期的实践案例，主要是关于网页上的数据抓取和清洗，里面会有相关的例子，可以借鉴。
