### ISSUE TITLE
配置学习用书时 pip install jupyterlab 报错

### ISSUE THREAD

**Issue by xllxl886** [neolee/pilot#1208]
执行pip install jupyterlab时报错
已采用代理科学上网

- [ ]![image](https://user-images.githubusercontent.com/62001733/76293569-45bc6580-62ec-11ea-9cfd-48f5feb7997b.png)

**Comment by xllxl886** [comment]
![image](https://user-images.githubusercontent.com/62001733/76295142-0d6a5680-62ef-11ea-8c9d-4e044cfe44a7.png)
自检如上图

**Comment by neolee** [comment]
这个还是网络问题，有的代理需要在命令行做些配置才会有效。

不过你既然已经到了这一步，其实就好办了，因为 PyPi 有很好的国内镜像，比如清华的这个：

https://mirror.tuna.tsinghua.edu.cn/help/pypi/

按照这里的提示用这个镜像下载安装通常就没问题了。
