### ISSUE TITLE
'er' 是不是少了一个

### ISSUE THREAD

**Issue by PanChuang2019** [neolee/pilot#1209]
![image](https://user-images.githubusercontent.com/48653618/76310937-cf7b2b80-630a-11ea-80af-0434162a20f1.png)
老师，请问这里的‘er’ 是不是少了一个，应该是4个吧？抑或我理解错。

**Comment by neolee** [comment]
是三个，不是四个。

Python 的正则表达式匹配时缺省是比较“贪”的模式，就是有多个就匹配多个，所以第二个词里的 `erer` 算一个匹配（但只会返回 `()` 里面捕获的一个 `er`）。
