### ISSUE TITLE
学习用书好像出现了一些改变 能还原吗？

### ISSUE THREAD

**Issue by bianka727** [neolee/pilot#121]
![屏幕快照 2019-10-26 下午9 21 50](https://user-images.githubusercontent.com/48577672/67620195-cd6e6f80-f836-11e9-8fcc-373336a17a38.png)
好像有些代码没了？

**Comment by neolee** [comment]
主仓库首页的说明中有介绍 [提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md)，不妨先从这里开始，学会把问题问对、问清楚。

**Comment by bianka727** [comment]
我的意思是我第一次用jupyter lab打开学习用书的时候有一些代码（给我们抄写用的），但后来我不知道进行了什么操作，那些代码现在看不见了。我在nbviewer里面打开的教材里面有，对比如下：
![屏幕快照 2019-10-26 下午11 33 58](https://user-images.githubusercontent.com/48577672/67622085-26470380-f849-11e9-99cc-d4228c00b05e.png)

**Comment by bianka727** [comment]
我好像修改过code markdown选项，并删除过，但我不知道怎么恢复。我希望能还原最初的页面。

**Comment by neolee** [comment]
有代码的是教材，学习用书里的代码被去掉，让你自己填。

[这个指南](https://github.com/neolee/pilot/blob/master/x2-students-book.md) 里有说明（也附有视频）。

**Comment by Xiaoxiaokangkang** [comment]
![微信图片_20191027154224](https://user-images.githubusercontent.com/48579605/67631413-18d55c00-f8d1-11e9-89a0-2f3217b4b299.png)
