### ISSUE TITLE
Installation of nodejs failed

### ISSUE THREAD

**Issue by sooolinw** [neolee/pilot#1210]
试过很多遍了，一直是安装失败。网速也还可以，用scoop install 其他软件都没问题；上nodejs官网下载手动安装，显示成功，但用scoop list查看，依然显示failed。
![0](https://user-images.githubusercontent.com/48663234/76312529-3ea64f00-630e-11ea-8d87-47dac8d1dc88.jpg)

**Comment by neolee** [comment]
如果运行 `node -v` 能正常输出版本信息，就可以了。

**Comment by sooolinw** [comment]
正常输出版本信息了，但toc的插件还是无法正常安装。
ValueError: "@jupyterlab/toc" is not a valid npm package

**Comment by neolee** [comment]
目前 @jupyterlab/toc 不支持最新的 Jupyter Lab，先等等吧。

**Comment by sodexx7** [comment]
怪不得，我试了半天一直加不上。
