### ISSUE TITLE
安装 busybox 和 nodejs 报错

### ISSUE THREAD

**Issue by xuexu23** [neolee/pilot#1211]
安装busybox 和 nodejs 时，都报一样错误。

Couldn't find manifest for 'busybox'.
Couldn't find manifest for 'nodejs'.

请问这是什么情况？

**Comment by neolee** [comment]
你执行 `scoop update` 是什么结果？

**Comment by xuexu23** [comment]
scoop update 成功也一样报错。

 
![1](https://user-images.githubusercontent.com/24616195/76413441-678f1880-63d0-11ea-90d3-623633c26fc5.JPG)

**Comment by neolee** [comment]
Scoop 没装好，按照 Wiki 里的指引重装。
