### ISSUE TITLE
Mac OS 下 MySQL Workbench 怎么导入数据到数据库？

### ISSUE THREAD

**Issue by cpx2222** [neolee/pilot#1212]
Mac下界面和教程的不同，找不到Schemas

**Comment by neolee** [comment]
Mac 下用 Sequel Pro 吧，比官方的好用：

https://www.sequelpro.com/

**Comment by cpx2222** [comment]
换Sequel Pro后导入CSV时出现‘There have been errors!’

<img width="951" alt="截屏2020-03-1202 12 13" src="https://user-images.githubusercontent.com/19421181/76449772-9ffe1900-6407-11ea-8f0f-e7708c4eaef3.png">

**Comment by neolee** [comment]
说 key 重复了，你需要在导入时做正确的设置。

导入的CSV是什么数据？

**Comment by cpx2222** [comment]
就是按照Mysql教程里的fifa19解压成data.csv，老师能不能添加一节MAC os 的添加教程，或者是否可以用终端指令的形式导入？

**Comment by neolee** [comment]
如下图，导入界面，两个地方需要填入，内容其实你可以输入你自己喜欢的，表格里是新建表的第一个列的名字（不要和下面的重了就行），上面是要新建的表的名字。然后回车就行了。

<img width="1319" alt="Sequel Pro" src="https://user-images.githubusercontent.com/24796/76593985-c53b7600-6532-11ea-9034-925e46524b58.png">

**Comment by cpx2222** [comment]
貌似已经解决了，谢谢老师
