### ISSUE TITLE
聊天机器人视频课程第5课

### ISSUE THREAD

**Issue by Gittplayer** [neolee/pilot#1213]
李老师，聊天机器人视频课程第5课中，Bot这个基类的初始化方法中增加了runtype这个参数后，
子类的初始化方法中增加的
```python
super().__init__(runtype)  这段代码是什么意思呢？

super().__init__(runtype)  等效于  self.runtype = runtype吗？

**Comment by neolee** [comment]
这个我在课上不是讲过么……

**Comment by Gittplayer** [comment]
我没有看完所有的课程，是践行群里还是B站的视频课

**Comment by qixinsame** [comment]
> 我没有看完所有的课程，是践行群里还是B站的视频课

是在践行群的第五课最后一张图的内容。
在这个case中，子类机器人的初始化方法init定义本质上是对父类init方法的override，如果不用super()把父类更新后的init跑一遍，新加如的runtype属性就不能被子类继承。

**Comment by Gittplayer** [comment]
好的谢谢 @qixinsame
