### ISSUE TITLE
安装 jupyter 插件不成功

### ISSUE THREAD

**Issue by xllxl886** [neolee/pilot#1214]
![image](https://user-images.githubusercontent.com/62001733/76483439-fee88000-6451-11ea-9ffe-a4c4009575aa.png)
在命令行输入上图命令
![image](https://user-images.githubusercontent.com/62001733/76483520-2ccdc480-6452-11ea-8f0b-539ba56f3755.png)
jupyter还是显示以前的目录

**Comment by xllxl886** [comment]
scoop已安装nodejs 13.10.1

**Comment by neolee** [comment]
Jupyter 最近升级，好像这个插件还没升级跟上，等等吧。

**Comment by xllxl886** [comment]
谢谢老师，明白了，我以为是我自己哪出错了
