### ISSUE TITLE
安装和运行 Jupyter Lab 报错

### ISSUE THREAD

**Issue by jomi0820** [neolee/pilot#1217]
执行如下代码
python -m pip install --upgrade pip
pip install jupyterlab
出现提示：
/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: No module named pip

修改为执行：
python3 -m pip install --upgrade pip
pip3 install jupyterlab
开始下载后提示：
Collecting pip
  Using cached https://files.pythonhosted.org/packages/54/0c/d01aa759fdc501a58f431eb594a17495f15b88da142ce14b5845662c13f3/pip-20.0.2-py2.py3-none-any.whl
ERROR: Could not find a version that satisfies the requirement install (from versions: none)
ERROR: No matching distribution found for install

根据已有人提交的issue里老师提到的，输入：
which python which python3 python -V python3 -V pip -V pip3 -V
出现如下提示：
/usr/bin/python
/usr/bin/which
/usr/local/bin/python3
/usr/bin/python
/usr/local/bin/python3
/usr/local/bin/pip3

切换了不同的网络和链接途径，尝试了几次提示都是一样，

**Comment by neolee** [comment]
你要运行的诊断命令是下面的，一个个运行，一次一行，不是一下子都扔上去：

```shell
which python
which python3
python -V
python3 -V
pip -V
pip3 -V
```

然后 `python3 -m pip install --upgrade pip` 是对的，如果你是 Mac，`pip3 install -U pip` 也没问题。失败的原因很像是网络不好。

这一步成功后再试 `pip3 install jupyterlab`。

另外，如果反复尝试网络都不给力，可以试试国内的镜像，Wiki 里有说明。
