### ISSUE TITLE
布尔值运算

### ISSUE THREAD

**Issue by wxz20200228** [neolee/pilot#1219]
在P1-3 -structure-2.ipynd学习用书中有这样一句话：
两个布尔值如果都是“真”，他们的 与 运算结果也为“真”，其他情况下结果都是“假”

我的理解是两个布尔值如果都是“真”，与运算为“真”，或运算应该也为真，否运算为假

请问这样理解正确吗？

**Comment by neolee** [comment]
那句话的意思是，两个“真”的与运算结果是真，“真”和“假”以及两个“假”之间的与运算结果是“假”。

**Comment by wxz20200228** [comment]
原来我的理解有误！
谢谢您的解答，我知道了。
