### ISSUE TITLE
安装 Scoop 时报错

### ISSUE THREAD

**Issue by xueqin8321bg** [neolee/pilot#1220]
我在安装Scoop时为什么显示无法连接到远程服务器？

**Comment by neolee** [comment]
因为无法连接到服务器啊。

**Comment by xueqin8321bg** [comment]
运行iwr -useb get.scoop.sh |  iex后显示以下信息，其中包括"已经安scoop",  让我更新，我输入scoop
 update 运行后，还是报错。这还是连不上服务器么的问题么？
![L)_IUEK}FPDBD5~JN%7P0B4](https://user-images.githubusercontent.com/61619087/76697678-ecca4400-66d4-11ea-89a7-2f47d3fff92d.png)

**Comment by neolee** [comment]
这种情况是你的 Scoop 没装好，需要删了重装，Wiki 里有方法。
