### ISSUE TITLE
P2-2 is_prime 函数问题

### ISSUE THREAD

**Issue by yongbowa** [neolee/pilot#1221]
![image](https://user-images.githubusercontent.com/56637457/76698163-b099e200-66da-11ea-9a88-2c128d3e21a7.png)
如图所示，按教材抄写了is_prime函数，但是运行is_prime(23)和help(is_prime)都没有结果输出,希望老师抽空能帮忙指点下，万分感谢！

**Comment by neolee** [comment]
1. 这个函数返回 True 或者 False，你要看结果可以 `print(is_prime(23))`。这个问题课上讲过好多次。

2. 你没写代码文档，自然没有 `help()`。

**Comment by yongbowa** [comment]
谢谢老师，后面重启之后确实正常了！
