### ISSUE TITLE
jupyter lab 启动后界面不正常

### ISSUE THREAD

**Issue by ALONSOlkp89** [neolee/pilot#1224]
运行环境: Ubuntu 18.04
命令行启动jupyterlab: Jupyter lab
浏览器打开如下页面后， 无法继续打开任何notebook。但是如果运行jupyter notebook, 却可以正常使用。
![image](https://user-images.githubusercontent.com/33852003/76710838-16896800-66e1-11ea-81d5-dacb22c5d888.png)

谢谢老师解答。

**Comment by neolee** [comment]
运行 `jupyter lab` 的命令行界面有什么信息？最好截个图看看。

以及，你用的是什么浏览器？版本？

**Comment by ALONSOlkp89** [comment]
500 GET /lab/api/settings/?1584360783634 (127.0.0.1) 5.91ms referer=http://localhost:8888/lab/workspaces/auto-P?clone

用的是chrome, 应该是最新的版本：Version 80.0.3987.132 (Official Build) (64-bit)

**Comment by neolee** [comment]
浏览器无问题。是 Jupyter Lab 这边的问题，看你的命令行提示似乎安装的有问题，试试重装下 Jupyter Lab？

**Comment by ALONSOlkp89** [comment]
用了下面的命令来重装jupyterlab, 还是一样的结果。
pip uninstall jupyterlab
pip install jupyterlab

**Comment by neolee** [comment]
安装中没有报什么错误吧？

另外你有没有使用一些防火墙或者实时防病毒工具？有的话暂时禁用下看是不是它们的影响。

**Comment by ALONSOlkp89** [comment]
没有看到报错。也没有使用任何防火墙或防病毒工具。
![Screenshot from 2020-03-16 21-50-52](https://user-images.githubusercontent.com/33852003/76814175-7579da80-67d0-11ea-87c4-856b804badb5.png)
![Screenshot from 2020-03-16 21-51-32](https://user-images.githubusercontent.com/33852003/76814178-77dc3480-67d0-11ea-8ea3-7c1b15139fae.png)

**Comment by neolee** [comment]
有点奇怪，我有台机器也是 Ubuntu 18.04 LTS，没发现问题。来看看你的系统环境先：

```shell
which python
python -V
pip -V
pip list
```

**Comment by ALONSOlkp89** [comment]
![Screenshot from 2020-03-17 20-15-08](https://user-images.githubusercontent.com/33852003/76913017-30b37980-688c-11ea-932b-0eafa6450779.png)
![Screenshot from 2020-03-17 20-15-39](https://user-images.githubusercontent.com/33852003/76913038-3a3ce180-688c-11ea-8fe7-86dd3ea2fb2e.png)
![Screenshot from 2020-03-17 20-15-50](https://user-images.githubusercontent.com/33852003/76913045-3dd06880-688c-11ea-8778-ebc859cc09f8.png)

**Comment by neolee** [comment]
如果你运行 `python3 -m jupyter lab` 会怎样？

**Comment by ALONSOlkp89** [comment]
还是一样的结果。

![Screenshot from 2020-03-18 08-03-19](https://user-images.githubusercontent.com/33852003/76958932-f3cc9e80-68ee-11ea-98da-761e911806c2.png)

**Comment by neolee** [comment]
从出错提示看，你的 Jupyter Lab 的客户端和服务端存在不兼容，这通常是安装了不兼容的包或者需要重新编译，也可能是系统上的 nodejs 版本有问题。我看到 SO 一个问题和你这个很像：

https://stackoverflow.com/questions/57260338/what-is-a-failed-validating-schema-jupyterlab-apputils-extensionpackage-in

你可以尝试：

1. 更新你的 nodejs 到尽可能新的版本；然后——
2. 按照上面链接里的建议，执行 `jupyter lab clean && jupyter lab build`。

**Comment by ALONSOlkp89** [comment]
谢谢老师的解答，终于解决了，长舒一口气，哈哈。
看来nodejs得是最新版本才行，之前是 v8, 然后运行jupyter lab build总是出错， 然后更新到了v13, 然后就可以jupyter lab build. 然后就恢复正常了，非常感谢！
