### ISSUE TITLE
赋值 c += 2

### ISSUE THREAD

**Issue by sooolinw** [neolee/pilot#1225]
![fuzhicaozuofu](https://user-images.githubusercontent.com/48663234/76767282-52512a00-67d4-11ea-9357-1e5faa8bab59.jpg)
这里第一次执行结果是40而不是38；删除后重新操作，结果一直是在之前的返回结果继续往上加，行数也没有按顺序排下去，是之前的操作隐藏了么，请问应该如何正确删除返回38呢

**Comment by neolee** [comment]
Jupyter Notebook 会记录你执行的每一行代码，即使执行完删掉了它也记得。要想从零开始可以从菜单中选择 Restart kernel。
