### ISSUE TITLE
在定义对象实例过程中对象实例本身是 a 还是 Dog('Fido')？

### ISSUE THREAD

**Issue by pylsky** [neolee/pilot#1226]
教材第十章《字符与字符串章节》里面第21行代码：’42’.isdigit() 的运行结果是True，根据教材的知识解析，因为’42’这个字符串对象实例归属于字符串类，所以字符串类的类方法.isdigit()可以被’42’ 这个字符串直接引用。

根据以上结论，尝试了对教材第九章《理解对象与类：Python 篇》里面第1、2行代码进行增改：
class Dog:

    kind = ''

    def __init__(self, name):
        self.name = name
        
    def bark(self):
        return 'woof-woof'

a = Dog('Fido')
b = Dog('Buddy')

Dog.kind = 'canidae'
a.kind
以上代码是教材第1、2行代码，运行结果是：'canidae'

我在以上代码的的前提下运行以下代码：
Dog('Fido').kind 
运行结果也是：'canidae'

在学习第九章时看见教材基本都是以a.***的方法来引用对象实例的属性或方法，所以我一直以为在定义某个对象的过程中（比如教材第九章的第1、2行代码），a所代表的就是对象实例本身。但实际上是否应该理解为：Dog('Fido') 这样的定义对象实例的表达式才能代表对象实例本身，所以Dog('Fido')这个表达式可以直接引用对象实例所适用的属性或方法（比如Dog('Fido').kind），而a只是作为一个变量而存在，因为被a = Dog('Fido')这个语句赋值了Dog('Fido') 这个对象实例的内容，所以a这个变量才视为Dog('Fido')这个对象实例，并可以引用对象实例所适用的属性或方法。

请问以上这样理解是否正确？感谢解答~

**Comment by neolee** [comment]
在你的例子里可以这么理解：`Dog('Fido')` 创建了一个 `Dog` 类的实例变量，这是一个拥有 `Dog` 类型的值，而 `a` 这个变量经过赋值指向了上述值，可以看做该值的一个名字或者标签（label）。所以 `a` 和 `Dog('Fido')` 是同一个东西，没区别，你可以用 `id()` 函数看下它们的的对象 ID，应该是一样的。

前面代码里的类变量理论上只属于类对象，也就是 `Dog` 这个对象（是的，Python 里类型本身也是对象），所以只有 `Dog.kind` 是有意义的；不过 Python 也允许写 `a.kind`，这个实际上可以看做 `Dog.kind` 的一种特殊写法，但这个特殊写法其实挺让人迷惑，我个人不太喜欢 Python 这个细节。

**Comment by qixinsame** [comment]
老师，假设Python没有这个细节的处理（说类变量只能被类对象调用），是否意味着用a. kind 应该报错？但是这个实例a确实是也有kind这个属性啊？

**Comment by neolee** [comment]
严格从概念上说，只有 Dog 类才有 kind 属性，实例对象 a 并没有。

不过 Python 给了 a 这个属性，这带来一个逻辑问题：kind 到底是类变量还是实例变量？所以我说这很 confusing。不过没办法，目前 Python 就是这么处理的。我的建议是：

1. 如果没有绝对必要，不必使用类变量，很少必须用。
2. 如果必须用类变量，也避免用实例对象去引用它。
