### ISSUE TITLE
JSON 数据运行报错

### ISSUE THREAD

**Issue by onefacebig** [neolee/pilot#1229]
![屏幕快照 2020-03-17 下午11 49 53](https://user-images.githubusercontent.com/48744991/76875605-bc88ce00-68ab-11ea-9ea2-dee45a894e2f.png)
网上搜了些关于SSL的处理方法也不行。

**Comment by neolee** [comment]
我连错误信息都没看到，咋给建议咧……

**Comment by onefacebig** [comment]
![屏幕快照 2020-03-18 下午10 56 20](https://user-images.githubusercontent.com/48744991/76974892-bd356900-696c-11ea-87fa-20eaa7c2f3f9.png)
![屏幕快照 2020-03-18 下午10 56 53](https://user-images.githubusercontent.com/48744991/76975955-397c7c00-696e-11ea-9e46-cee327470cfb.png)
![屏幕快照 2020-03-18 下午10 57 12](https://user-images.githubusercontent.com/48744991/76975980-3f725d00-696e-11ea-959d-2f16a6ad1b68.png)
![屏幕快照 2020-03-18 下午10 57 35](https://user-images.githubusercontent.com/48744991/76975997-44371100-696e-11ea-88d4-67072fb9c21c.png)
![屏幕快照 2020-03-18 下午10 57 55](https://user-images.githubusercontent.com/48744991/76976014-4c8f4c00-696e-11ea-8d3d-dbae491031a3.png)

**Comment by neolee** [comment]
你在浏览器里能打开那个 URL 吗？

**Comment by onefacebig** [comment]
![屏幕快照 2020-03-19 下午10 24 46](https://user-images.githubusercontent.com/48744991/77077675-845ec800-6a30-11ea-8d38-e2069e550b52.png)
打开是这样的

**Comment by neolee** [comment]
你是 macOS 的系统是吧？而且我看你的出错信息，似乎你的 Python 系统也不是按照我的配置指南用 Homebrew 安装的对吧？

在 macOS 的某些环境下，Python 使用的 SSL 库会有问题，就会产生你的这个问题。

**Comment by onefacebig** [comment]
谢谢老师，用的是macOS，配置的是python3.7.2，网络不好装了几次都装不上，就用着以前装的3.7.2了。
