### ISSUE TITLE
Jupyter Lab 安装成功后输入 jupyter lab 命令没有打开一个浏览器

### ISSUE THREAD

**Issue by xiaoatang** [neolee/pilot#123]
按照教程“在克隆好的目录里运行 jupyter lab ↩︎ 来启动 Jupyter Lab 的服务程序，并打开一个浏览器页面”执行后，并没有打开一个浏览器（此处打开浏览器是指输入命令后，会自动打开一个浏览器，还是需要手动打开一个浏览器？）

**Comment by neolee** [comment]
正常来说会自动打开浏览器并打开 Jupyter Lab 的首页，但是也有些情况下没法自动打开，你可以参考 issue #20

**Comment by xiaoatang** [comment]
已解决，原因是被腾讯电脑管家默认限制了，谢谢

**Comment by zhenrany** [comment]
请问你是怎么解除电脑管家限制的，笔记本安装也打不开，粘贴地址可以用，谢谢！
