### ISSUE TITLE
'NoneType' object has no attribute 'find_all'

### ISSUE THREAD

**Issue by bigbigblock** [neolee/pilot#1231]
```python
data_raws = []
for tr in table.tbody.find_all('tr'):
    
    raw = [td.text for td in tr.find_all('td')]
    data_raws.append(raw)

data_raws
```

报错为
```
**### ---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-35-21c62a2a142c> in <module>
      1 data_raws = []
----> 2 for tr in table.tbody.find_all('tr'):
      3 
      4     raw = [td.text for td in tr.find_all('td')]
      5     data_raws.append(raw)

AttributeError: 'NoneType' object has no attribute 'find_all'**
```

下为源代码，读取column_names 还正常，
```python
import requests
from bs4 import BeautifulSoup

response = requests.get('https://coinmarketcap.com/currencies/ethereum/historical-data/?start=20130429&end=20200318')
payload = response.content

soup = BeautifulSoup(payload, 'html.parser')
table = soup.find('div', class_="cmc-table__table-wrapper-outer").find_all('table')[0]

import pandas as pd
column_names = [th.text for th in table.thead.tr.find_all('th')]
column_names

data_raws = []
for tr in table.tbody.find_all('tr'):
    
    raw = [td.text for td in tr.find_all('td')]
    data_raws.append(raw)

data_raws
```

**Comment by neolee** [comment]
我看了下你的目标页面，你的搜索规则没找对，`class` 为 `cmc-table__table-wrapper-outer` 有好几个，似乎第三个才是你的目标表格（可能你要自己 double check 一下）。

**Comment by bigbigblock** [comment]
老师好，我试了下第二个和第三个表格都是 IndexError: list index out of range， 应该不是那个问题，因为 column_names = [th.text for th in table.thead.tr.find_all('th')]
这个是对的。

下面是程序

soup = BeautifulSoup(payload, 'html.parser')
table = soup.find('div', class_="cmc-table__table-wrapper-outer").find_all('table')[1]

报出
IndexError                                Traceback (most recent call last)
<ipython-input-40-8ff9de46eb5b> in <module>
      1 soup = BeautifulSoup(payload, 'html.parser')
----> 2 table = soup.find('div', class_="cmc-table__table-wrapper-outer").find_all('table')[1]
      3 
      4 print(table)

IndexError: list index out of range

网页结构如下图，thead 的 内容 ['Date', 'Open*', 'High', 'Low', 'Close**', 'Volume', 'Market Cap']

![image](https://user-images.githubusercontent.com/35882024/77030215-e7247500-69d8-11ea-82cb-4a7aa89f8ac6.png)

**Comment by neolee** [comment]
不是，你的 `soup.find('div', class_="cmc-table__table-wrapper-outer")` 这个就错了啊，再在其下找 `<table>` 当然更没戏了。你应该试试的是：

```python
soup.find_all('div', class_="cmc-table__table-wrapper-outer")[2]
```

把这个 print() 出来看看，下面是不是有你要的 `<table>`，如果这一步对了，再继续：

```python
soup.find_all('div', class_="cmc-table__table-wrapper-outer")[2].find('table')
```

**Comment by bigbigblock** [comment]
谢谢老师的回答，感谢感谢，大牛回答小白问题，但确实每一个小问题都是小白最难的。

**Comment by neolee** [comment]
> 谢谢老师的回答，感谢感谢，大牛回答小白问题，但确实每一个小问题都是小白最难的。

所以最关键的是，每个问题搞定之后是不是能自己搞定一批类似问题，那就可以小白变(●—●)大白啦！
