### ISSUE TITLE
用 Python 画图形界面

### ISSUE THREAD

**Issue by sodexx7** [neolee/pilot#1232]
李俊老师可不可以讲下用Python怎么画一些界面，有些不同地方的信息源我想要按照我想要的方式进行组合与展示，要是一会切换到页面查看，一会切换到某个app查看就比较麻烦，我想将这些信息聚合到一起。 比如，我画的一个界面既可以看到BOX的历史走势，又可以看到我用处理的excel信息。

**Comment by neolee** [comment]
1. 这个问题为啥不可以直接用“在桌面上良好地摆放窗口”来实现呢？
2. 学完课程的话，自己学习一个 GUI 的 Python 库应该不难，不过实话说 Python 不适合干这个；也可以考虑自己写一个网页来做这事儿，我们本周的实践案例会讲相关入门内容；
3. 名字写错了，还不如不写……

**Comment by sodexx7** [comment]
李骏老师，实在不好意思，我竟然把名字写错了。
不通过“在桌面上良好地摆放窗口”来实现，是因为我不想把某个app所有的内容都展示出来，只想看到自己想看的内容，比如某个app中其中一小部分内容。
网页的话，我感觉没有本地化图形应用用起来爽，本地跑的话，我直接在本地点击运行就开始工作了，网页的话如果要有交互数据还得再弄个后台。
谢谢李骏老师的回答。

**Comment by neolee** [comment]
绝大部分程序的本质都一样：从某处获取数据并加工，然后用需要的方式展现出来。

命令行、GUI 和页面是三种不同的用户界面，或者说展现方式。

所以关键是，你想要展现的数据在哪里，如何取得；至于取得之后在哪里展现，其实挺自由的；而展现方式里，最简单也最方便的，还是页面（还跨平台）。
