### ISSUE TITLE
如何理解 p2-a-tree 代码中 isinstance 的参数 TreeNode？

### ISSUE THREAD

**Issue by qixinsame** [neolee/pilot#1233]
首先，我目前在阅读一个class的定义的时候，有一个习惯：”想象我创建了一个这个class的instance object(e.g. t = TreeNode() ），那基于这个class的定义我这个实力对象获得了哪些“属性”和“方法”。这个习惯在我阅读教材其余本分的class的定义的时候都挺管用的，能帮我快速建立对这个class的“直观”印象。

然后在用相同的习惯阅读下面代码的时候就卡壳了，具体问题是：

在这个实例对象初始化的时候(进行时ing)，会执行到“assert isinstance(parent, **TreeNode**)”，其中TreeNode正是自己正在定义的一个自定义数据类型。给我的印象就好像是“在生产一把尺子的过程中需要先用这把尺子”。

我知道上面的理解肯定哪儿是错的，但是就是绕不出来，请求大神指教。
```python
class TreeNode:
    def __init__(self, name='root', data=None, parent=None, children=None):
        self.name = name
        self.data = data
        
        if parent:
            assert isinstance(parent, TreeNode)
            parent.add_child(self)
        self.parent = parent
        
        self.children = []
        if children:
            for child in children:
                self.add_child(child)
                
    def add_child(self, node):
        assert isinstance(node, TreeNode)
        node.parent = self
        self.children.append(node)
```

**Comment by neolee** [comment]
这是个好问题，你的思维挺细致的。

我其实上课时说过，`def` 和 `class` 关键字，其实都是在“定义”一些东西，而不是“创建”或者“运行”一些东西，实际“创建”和“运行”其实是在调用函数和实例化时才进行。

所以这里在 `TreeNode` 类的定义中引用了 `TreeNode` 类本身，是没有问题的，你可以把 `TreeNode` 看做一个名字，然后那一条 `assert` 是保证特定对象必须是 `TreeNode` 类型。而这一切实际运行都会在 `TreeNode` 对象实例化之后，那时 `TreeNode` 已是完整定义过的类。

**Comment by qixinsame** [comment]
明白了，谢谢老师！
