### ISSUE TITLE
命令行输入“git config --list”显示2次邮箱，是否操作有误？

### ISSUE THREAD

**Issue by xllxl886** [neolee/pilot#1234]
![image](https://user-images.githubusercontent.com/62001733/77021921-22b44480-69c3-11ea-9734-89ac2d999692.png)
在命令行输入“git config --list”显示2遍邮箱-如上图，我是否操作有误？
1：命令行操作步骤如下:
git config --global user.name "xllxl886"
git config --global user.emial "510576127@qq.com"
git config --global core.editor "code -w"
git config --list
2：xllxl886是注册git时的用户名
"510576127@qq.com"是注册git时用的邮箱

**Comment by xllxl886** [comment]
![image](https://user-images.githubusercontent.com/62001733/77035201-00342280-69e7-11ea-9e83-6713d878557a.png)
找到git config的源文件，删除了一个邮箱，如上图
命令行输入git config --list，如下图
![image](https://user-images.githubusercontent.com/62001733/77035307-41c4cd80-69e7-11ea-841e-fb5fadec46e0.png)

**Comment by neolee** [comment]
其中有一个 email 拼错了。

**Comment by xllxl886** [comment]
哎！犯这种低级错误，真不应该，元认知要加强
