### ISSUE TITLE
教材 p2-a-tree 中，TreeNode 定义中 children 属性的初始化方法为何要通过 add_child() 去实现？

### ISSUE THREAD

**Issue by qixinsame** [neolee/pilot#1235]
如题，教材中初始化 self.children 的方法是先创建一个空 list ，再用自定义的 add_child() 方法将一个个child node添加进去。我能理解做的一个用处是可以用到add_child()里的assert函数去检查每个node是否是TreeNode类型

self.children = []
        if children:
            for child in children:
                self.add_child(child)

如果是基于这样的理解，将这部分代码改成下面这样好像也能实现这个功能。

if children:
        for child in children:
             assert isinstance(child, TreeNode)
        self.children = children

所以思考后还是不理解教材中这样初始化children的方法根本的好处是什么了？

**Comment by neolee** [comment]
好处是，可以复用 `self.add_child` 里的逻辑呀。

你的版本里，既没有省事（还是要对 `children` 参数来一次遍历），又包含了和 `add_child` 里重复的逻辑，如果以后做 assert 的逻辑要修改，你还得该两边，有啥好？

**Comment by qixinsame** [comment]
谢谢老师，我可能没问对问题，试着换个方式：

就是老师你在写这个class的时候（无中生有过程中），写到children的定义的时候是如何会想到先停下来，另起一行写个add_child的方法来完成这个功能。

我现在阅读这段代码的时候，因为add_child已经写好了，读起来逻辑是可以理解的，但是如果是自己写的话，写到这儿我能想到的需求也仅仅限于“需要像parent一样检查下类型”，所以才有了我这段代码，但是老师是如何想到的，中间感觉有个leap，但是自己抓不住，才想请教

**Comment by neolee** [comment]
你听了这一讲的课程回放吗？其实这一章的关键是分析树型结构的特点，设计出我们可以对树型结构可以做的事情，这些事情就是 `TreeNode` 类里的方法。所以在实现之前我就已经提前设计好了这个类应该有哪些方法。这个设计的过程才是这一课的关键——当然把这些方法实现出来对你们来说也是极好的练习，可以把之前所学都用上。

**Comment by qixinsame** [comment]
老师，不怕你笑话，这一课的课程音频我倍速和常速各听了两遍。
代码实现前的内容感觉自己都明白了，包括代码实现也能读明白。
问题在于关上书后，想象如果是自己无中生有地写的话会怎么写下每一行代码，发现基于之前的理解自己只能写出下面两段：

1 class TreeNode():  
##树这个结构(脑子里出现一副树形图)是由两个要素构成的：node和node的上下关系, 只要每一个node的上下关系是明确的，这个图就可以画出来，所以class的名字不应该是Tree()，而是用TreeNode更贴切

2 def __init__(self, name, parent, children)：
##基于上述理解，初始化一个TreeNode的实例关键要明确parent和children的关系，最好再有个易读的标签能指向它，name。
      self.name = name #八股
      self.parent = parent #在看了教材提示要检验parent/children node的类型(我自己是绝无可能想到的），所以才会添加assert语句
      self.children = children

上述思路就是我提问前的心路历程。通过跟老师交流后，发现了自己理解和思路有如下问题：

1）虽然课程中有讲到软件的设计是对domain的数据结构的"表达"+提供"处理"这个数据结构的方法。自己也听到了这部分内容，但是思维还是锚定在前一小节（对树的概念的抽象），重心还是停留在对树这个数据结构的表达(脑子里只抽象出了节点和边这两个静态要素）。
直到刚才看到老师回答后，又去查询了Data Structure的定义，才反应过来数据结构不仅仅是一个静态的结构(如建筑结构中的要素和关系)，还包括了动态的功能(开门，开窗，开空调)
<img width="619" alt="1" src="https://user-images.githubusercontent.com/43022624/77137503-3a65f880-6aa9-11ea-9134-3cdf5f50a5b6.PNG">

2）这时候我才对老师讲的“application driven”有了点感觉：从功能为起点和抓手去无中生有，这样就能理解为什么会先有add_child()这个方法，甚至在初始化的代码块里面就要提前用到add_child()。而在这之前我写代码的思维路径还是“循序”结构——被书写的顺序框定的，所以只能写出上面两行代码就丢了头绪。即使听了讲解说要application drive，听的时候也感觉自己都明白，可写的时候还是不行。也许这就是知道和做到的距离吧。

谢谢讲解。

**Comment by neolee** [comment]
感谢你贡献了非常好的元认知解析，这个心路历程挺重要的，相信也会给你未来学习带来很多收益。
