### ISSUE TITLE
赋值 c += c

### ISSUE THREAD

**Issue by Renalxn** [neolee/pilot#1236]
<img width="279" alt="微信图片_20200319223556" src="https://user-images.githubusercontent.com/61861937/77078886-2af79880-6a32-11ea-90a1-f261a1d13e73.png">
请问老师，前面已经算出来c=21.98，后面的c为什么不是43.96，而是又多了一倍呢？

**Comment by neolee** [comment]
从你单元格前面的编号推测，你的第二个代码单元格应该执行了两次。

**Comment by Renalxn** [comment]
好像是的，我先用c = c + c 运算了一次，然后在单元格里直接改成 c += c 又运算了一次，那请问老师我能让编号34的单元格也显示出来么？

还有就是如果单元格已经执行过一次了，想要修改的话是不能在原来的单元格里直接改的是吗？程序会在原来的基础上累计运算对吗？

正确的修改方法是要把原来这的单元格删掉再新建一个吗？

**Comment by neolee** [comment]
最简单的办法是在初学时不要删除和修改任何单元格，要试新的想法就加新的单元格，这样就会看得比较清楚。

**Comment by Renalxn** [comment]
好的，我知道啦~谢谢老师~！
