### ISSUE TITLE
‘aaa’ 和 ‘aab’ 代表什么？

### ISSUE THREAD

**Issue by Renalxn** [neolee/pilot#1237]
![image](https://user-images.githubusercontent.com/61861937/77079322-cd178080-6a32-11ea-95c8-b4d7d91cf13f.png)
![image](https://user-images.githubusercontent.com/61861937/77079339-d4d72500-6a32-11ea-983d-be0a56b9ad75.png)

请问老师，这里的 ‘aaa’ < 'aab' 是 ‘666’ < '6630' 的意思么？

**Comment by neolee** [comment]
逐个字符比较， 在字母表上 `a` 在 `b` 前面，所以……

**Comment by Renalxn** [comment]
所以这里的'aaa' 和 'aab' 是因为加了'' 代表两个字符串，跟前面的赋值就没关系了对吗？

**Comment by neolee** [comment]
当然。`'aaa'` `'aab'` 是字符串值（values），而前面的 `a` `b` 都是变量（variables）。

**Comment by Renalxn** [comment]
明白了，谢谢老师！
