### ISSUE TITLE
Cannot find whole table！beautiful soup failed first time!

### ISSUE THREAD

**Issue by moonwmh** [neolee/pilot#1238]
based on some reasons you knew, failed to login in wikipedia .
I chose this address National Data** http://data.stats.gov.cn/tablequery.htm?code=AA130O**

my codes as follow:
``` python
import requests #获取文件
response = requests.get('http://data.stats.gov.cn/tablequery.htm?code=AA130O')

payload = response.content#网页内容,放入变量

from bs4 import BeautifulSoup
soup = BeautifulSoup(payload, 'html.parser')#用html.parser引擎来解析payload内容

table = soup.find('div', class_='table-container').find('table')

table

```

response in the jupyterLab:
```python

<table border="0" cellpadding="0" cellspacing="0" class="tabledata" id="tabledata" style="width:100%">
</table>
```

Actually, what I want is as follow:
![截屏2020-03-20上午7 04 15](https://user-images.githubusercontent.com/48578043/77122694-49cd4d80-6a79-11ea-8051-8951c8be141b.jpg)

So, My question is :
** Neo, Why? Thx.**

**Comment by neolee** [comment]
我看了下，这个页面的表格里的数据是用 JavaScript 动态写入的，使用案例二里的方法没法抓到表格里的数据。换个别的页面玩玩吧。

**Comment by moonwmh** [comment]
如何区分 JavaScript 及其他？

**Comment by neolee** [comment]
> 如何区分 JavaScript 及其他？

不是很明白你的问题。
