### ISSUE TITLE
安装 git dark 和 innounp 失败

### ISSUE THREAD

**Issue by feelingchi** [neolee/pilot#1239]
本人上班族，初学python。win7、32位笔记本 ，ConEmu、Scoop安装成功，安装git时总是报错？checkup后运行“Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1”仍然不行，试了多次，不知如何解决？感谢老师宝贵的时间！谢谢！

![3 21-1](https://user-images.githubusercontent.com/20626555/77183481-5a2d0900-6b09-11ea-989b-039516696daf.png)

![3 21-2](https://user-images.githubusercontent.com/20626555/77183516-69ac5200-6b09-11ea-8dd0-c09abcf30aee.png)

**Comment by neolee** [comment]
运行 `Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1` 有问题的话，可以尝试打开一个 Admin 权限的 PowerShell 界面来试。

另外的几个软件包安装问题都是网络的问题。

另外 Win 7 的问题会比较多些。
