### ISSUE TITLE
Mac 电脑安装 python 总是失败

### ISSUE THREAD

**Issue by Sean0932** [neolee/pilot#1240]
新生

老师你好，我在安装 python 是总是提示：

yangshaoyingdeMacBook-Pro:~ yangshaoying$ brew install git python
Updating Homebrew...
Warning: git 2.25.2 is already installed and up-to-date
To reinstall 2.25.2, run `brew reinstall git`
==> Installing dependencies for python: readline, sqlite and xz
==> Installing python dependency: readline
==> Downloading https://homebrew.bintray.com/bottles/readline-
==> Downloading from https://akamai.bintray.com/6a/6ae1c8e7c78
######################################################################## 100.0%
curl: (56) LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54
Error: Failed to download resource "readline"
Download failed: https://homebrew.bintray.com/bottles/readline-8.0.4.catalina.bottle.tar.gz
Warning: Bottle installation failed: building from source.

请问是什么原因导致的。

**Comment by Sean0932** [comment]
老师，经过反复尝试，python 安装成功了。版本是 Python 3.7.7 ，在使用上有影响码？

**Comment by neolee** [comment]
问题不大。
