### ISSUE TITLE
安装 Scoop 时出现问题

### ISSUE THREAD

**Issue by y19931027** [neolee/pilot#1241]
PS C:\Users\Hasee> Get-ExecutionPolicy
RemoteSigned
PS C:\Users\Hasee> iwr -useb get.scoop.sh | iex
Initializing...
Scoop is already installed. Run 'scoop update' to get the latest version.
PS C:\Users\Hasee> scoop update
scoop : 无法将“scoop”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检
查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ scoop update
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (scoop:String) [], ParentContain
   sErrorRecordException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\Hasee> scoop list
scoop : 无法将“scoop”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检
查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ scoop list
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (scoop:String) [], ParentContain
   sErrorRecordException

**Comment by neolee** [comment]
之前安装 Scoop 失败了，需要完全删除之后重装，Wiki 中有方法。

**Comment by y19931027** [comment]
是中文版的维基百科还是英文版的？

**Comment by y19931027** [comment]
搞定了，直接删除C盘下的scoop文件夹。

**Comment by neolee** [comment]
> 是中文版的维基百科还是英文版的？

本 repo 的 Wiki。
