### ISSUE TITLE
Markdown 的预览页面打不开

### ISSUE THREAD

**Issue by caochao-lei** [neolee/pilot#1242]
![Markdown](https://user-images.githubusercontent.com/59311022/77226947-00155d80-6b74-11ea-833d-517c169a4b7d.jpg)

**Comment by y19931027** [comment]
同上，我的也打不开， 说 command 'instantmarkdown.openBrowser' not found  说这个命令没找到.

**Comment by neolee** [comment]
在我这里没问题。不过这个插件有好一阵子没更新了，换个别的吧，在 VSCode 的插件面板搜索 markdown，有好多很好的选择，甚至于不用另外装，就用自带的也完全 OK。

**Comment by caochao-lei** [comment]
好的，我试试

---原始邮件---
发件人: "Neo Lee"<notifications@github.com&gt;
发送时间: 2020年3月25日(周三) 晚上7:36
收件人: "neolee/pilot"<pilot@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"caochao-lei"<1191971507@qq.com&gt;;
主题: Re: [neolee/pilot] Markdown 的预览页面打不开 (#1242)




 
在我这里没问题。不过这个插件有好一阵子没更新了，换个别的吧，在 VSCode 的插件面板搜索 markdown，有好多很好的选择，甚至于不用另外装，就用自带的也完全 OK。

**Comment by Createitv** [comment]
![markdown](https://user-images.githubusercontent.com/39019652/77546425-d26b4400-6ee6-11ea-9b9b-fd1e648d0412.PNG)可以试试这个！！
