### ISSUE TITLE
安装 Jupyterlab 出现异常

### ISSUE THREAD

**Issue by y19931027** [neolee/pilot#1244]
PS C:\Users\Hasee> pip install jupyterlab
Collecting jupyterlab
  Using cached jupyterlab-2.0.1-py3-none-any.whl (7.7 MB)
Collecting jupyterlab-server~=1.0.0
  Using cached jupyterlab_server-1.0.7-py3-none-any.whl (27 kB)
Collecting tornado!=6.0.0,!=6.0.1,!=6.0.2
  Using cached tornado-6.0.4-cp37-cp37m-win_amd64.whl (417 kB)
Collecting jinja2>=2.10
  Using cached Jinja2-2.11.1-py2.py3-none-any.whl (126 kB)
Collecting notebook>=4.3.1
  Downloading notebook-6.0.3-py3-none-any.whl (9.7 MB)
     |▌                               | 133 kB 10 kB/s eta 0:14:40ERROR: Except ion:
Traceback (most recent call last):
  File "c:\users\hasee\scoop\apps\python37\current\lib\site-packages\pip\_vendor\urllib3\response.py", line 425, in _error_catcher
    yield
  File "c:\users\hasee\scoop\apps\python37\current\lib\site-packages\pip\_vendor\urllib3\response.py", line 507, in read

**Comment by neolee** [comment]
网络问题，看看 Wiki 里关于 PyPi 国内镜像的说明。

**Comment by y19931027** [comment]
> 网络问题，看看 Wiki 里关于 PyPi 国内镜像的说明。

谢谢关照，PS C:\Users\Hasee> scoop install nodejs
Installing 'nodejs' (13.11.0) [64bit]
node-v13.11.0-win-x64.7z (16.1 MB) [============>                     ]  39%
无法从传输连接中读取数据: 远程主机强迫关闭了一个现有的连接。。
URL https://nodejs.org/dist/v13.11.0/node-v13.11.0-win-x64.7z is not valid
 这个也是网络问题吗？

**Comment by neolee** [comment]
是。

**Comment by y19931027** [comment]
谢谢指导，学习用书跟着描红一遍之后，怎么在 powershell 中运行一遍呢？PS C:\Users\Hasee\Code\learn-git> type(42)
type : 找不到路径“C:\Users\Hasee\Code\learn-git\42”，因为该路径不存在。
所在位置 行:1 字符: 1
 type（） 函数怎么使用？

**Comment by neolee** [comment]
呃，你先好好看看支线课程里的新手必读。

然后群里的录播课也要听。

**Comment by y19931027** [comment]
群里的录播课听到第四讲了，支线课程的新手必读在哪？没看到.....

**Comment by neolee** [comment]
点页面上面的 Wiki……

**Comment by y19931027** [comment]
嗯，看到了，谢谢老师，运行这个赋值语句说 a 没有被定义？

a = 12
b = 30
f = 3.14
s = 'abracadabra'
l = [1, 2, 3]
t = True
f = False
赋值之后变量就具有了相应的值，同时也具有了该值对应的类型，所以变量一经赋值就有了类型：


type(a)
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-8-6e04be549149> in <module>
----> 1 type (a)

NameError: name 'a' is not defined

**Comment by neolee** [comment]
前面的一堆赋值语句你运行了么？

**Comment by y19931027** [comment]
之前运行了也是出错，现在运行又好了。运行出错了是不是修改好了重新运行？可能之前是我输入的时候没有加空格键才出错，后来改了。

**Comment by neolee** [comment]
出错就等于没运行，运行成功才有效呀……

**Comment by y19931027** [comment]
File "p1-3-structure-2.ipynb" has unsaved changes, close without saving? 这个文件打不开了，页面一直在转圈圈，这个最后修改时间是 a day ago,其它都是2 day ago，

**Comment by neolee** [comment]
打不开的时候命令行里有什么错误提示？

**Comment by y19931027** [comment]
出现这个 [W 21:22:18.031 LabApp] 400 GET /api/contents/pilot-student/p1-3-structure-2.ipynb?type=notebook&content=1&1585056138026 (::1) 3.99ms referer=http://localhost:8888/lab

**Comment by neolee** [comment]
这个没啥问题，那不应该打不开。你有命令行和浏览器的截图吗？

**Comment by y19931027** [comment]
[W 21:34:32.813 LabApp] 400 GET /api/contents/Code/pilot-student/p1-3-structure-2.ipynb?type=notebook&content=1&1585056872811 (::1): Unreadable Notebook: C:\Users\Hasee\Code\pilot-student\p1-3-structure-2.ipynb NotJSONError('Notebook does not appear to be JSON: \'{\\n "cells": [\\n  {\\n   "cell_type": "m...')
[W 21:34:32.815 LabApp] Unreadable Notebook: C:\Users\Hasee\Code\pilot-student\p1-3-structure-2.ipynb NotJSONError('Notebook does not appear to be JSON: \'{\\n "cells": [\\n  {\\n   "cell_type": "m...')
[W 21:34:32.815 LabApp] 400 GET /api/contents/Code/pilot-student/p1-3-structure-2.ipynb?type=notebook&content=1&1585056872811 (::1) 3.02ms referer=http://localhost:8888/lab

**Comment by y19931027** [comment]
File "p1-3-structure-2.ipynb" has unsaved changes, close without saving?  点这个文件就 弹出这个选择，点OK 就关闭这个文件，点取消就好像没网络一样，页面中间就一个小圈一直转，好像在加载的样子，其他文件都能打开，就这个文件打不开。

**Comment by neolee** [comment]
`Unreadable Notebook`

这个错误信息是最重要的，这个文件确实损坏了。

你可以尝试恢复到原始状态（在 `pilot-student` 目录下）：

```shell
git checkout -- p1-3-structure-2.ipynb
```

或者更加简单粗暴的，直接从这里下载（不过还是前面那个方法最好）：

> https://raw.githubusercontent.com/neolee/pilot-student/master/p1-3-structure-2.ipynb

**Comment by y19931027** [comment]
运行上面那个命令了还是打不开，你给的这个网站打开了不知道咋下载。
![QQ浏览器截图20200324220334](https://user-images.githubusercontent.com/54001982/77435008-ab484000-6e1c-11ea-9790-542fac9f799e.png)

**Comment by y19931027** [comment]
命令写错了，好了，可以打开了，谢谢老师。
