### ISSUE TITLE
数据抓取和清洗中出现 AttributeError

### ISSUE THREAD

**Issue by moonwmh** [neolee/pilot#1245]
好不容易 解决了**网络**问题，

code 和 提示错误如下：

<img width="819" alt="截屏2020-03-22下午6 06 40" src="https://user-images.githubusercontent.com/48578043/77247639-f53ef380-6c6d-11ea-847b-b33f33dce68b.png">

**重新装了bs4，错误依然。**

Neo , What can I do ?

**Comment by neolee** [comment]
你都走到这里了，还不知道应该怎么做么？

首先你不应该一上来就写那么长一串代码，一步一步来。

这段代码里包含下载页面、用 soup 处理页面、用 soup 找到第一个标志 tag、找到第二个标志 tag、找到一大堆目标 tags 这么几步，先把这些步骤一个个分开，每一步都打印一下结果，看看是不是如你所设想。自然就能找到问题。

都学到这个阶段了，先做足自己的功课很重要。

**Comment by antarts** [comment]
好像是网络问题，页面加载完全就可能出现这个问题。
