### ISSUE TITLE
Notebook 运行不了程序，前面出现星号[*]

### ISSUE THREAD

**Issue by Endlessfly-oss** [neolee/pilot#1247]
<img width="644" alt="WechatIMG343" src="https://user-images.githubusercontent.com/53898706/77312759-9183fb80-6d3d-11ea-9719-75172c4346e5.png">

尝试过其他按键还是不能运行

**Comment by Endlessfly-oss** [comment]
<img width="644" alt="WechatIMG343" src="https://user-images.githubusercontent.com/53898706/77312962-ec1d5780-6d3d-11ea-8593-ab80fc19c390.png">

**Comment by neolee** [comment]
[*] 表示对应 cell 正在运行，后面的自然也无法运行。这有时候是因为后台的 Python kernel 挂掉了，不过你的情况不是这样。

你可以看到你的第一个挂着 [*] 的 cell 里面有个 `input()` 函数，这个函数需要用户输入些东西才能继续，所以 cell 下面有个请你输入的输入框等着你填。

想想从第一课开始我就讲的，要和计算机做朋友，你要理解你对它说了什么（你程序里的每一句），以及留意它对你说了什么（那个输入框）。如果做不到这个，就没法继续了哦。

**Comment by Endlessfly-oss** [comment]
> [*]表示对应单元正在运行，后面的自然也无法运行。这有时候是因为后台的Python内核挂掉了，不过你的情况不是这样。
> 
> 你可以看到你的第一个挂着[*]的单元格里面有个`input()`函数，这个函数需要用户输入些东西才能继续，所以cell下面有个请你输入的输入框等着你填。
> 
> 想想从第一课开始我就讲的，要和计算机做朋友，你要理解你对它说了什么（你程序里的每一句），以及留意它对你说了什么（那个输入框）。如果做不到这个，就没法继续了哦。

明白了！原本也依稀感觉出是这样的问题，在老师的解答下，更清晰了，也解决了！
