### ISSUE TITLE
配置 ConEmu 出错 Process was not attached to console

### ISSUE THREAD

**Issue by seven716** [neolee/pilot#1248]
Windows 10 操作系统
配置环境也是符合操作要求（插入不了图片）。
按提示步骤安装ConEmu，按提示设置powershell，运行后：

提示：（首行）Process was not attached to console.Is it GUI?
   （左下角） powershell.exe:14064 exit code 1
尝试方法：
1.百度搜索相关错误提示；
2.试过更改根文件的内容；
3.卸载重装了几次；
解决不了
（插入不了图片）

但是单独打开powershell.exe可执行，有高手能知道问题点在哪吗？感谢！

**Comment by neolee** [comment]
首先确认你的 PowerShell 和 ConEmu 版本都是合乎要求的。

如果上述版本无问题，很可能和防病毒软件有关。
