### ISSUE TITLE
安装 Scoop 时出错

### ISSUE THREAD

**Issue by aceb3748** [neolee/pilot#1249]
在powershell目录下，输入 iwr -useb get.scoop.sh | iex
之后，会出现如下：
iwr : 基础连接已经关闭: 发送时发生错误。
所在位置 行:1 字符: 2
+  iwr -useb get.scoop.sh | iex
+  ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebReq
   uest) [Invoke-WebRequest]，WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Comm
   ands.InvokeWebRequestCommand

**Comment by neolee** [comment]
这个是网络问题，换网络或者挂代理试试。

**Comment by aceb3748** [comment]
谢谢，老师指点。

**Comment by xiaohao462** [comment]
![image](https://user-images.githubusercontent.com/57126569/77613863-c3c47180-6f66-11ea-9cde-58c8fb266aed.png)
老师，scoop出错，安装好几次安装不上，如何处理？截图见上，谢谢老师

**Comment by neolee** [comment]
@xiaohao462 也是网络问题。另外不要在别人的问题下提问，自己开新 issue。

**Comment by aceb3748** [comment]
换了网络，已经解决，谢谢老师
