### ISSUE TITLE
运行程序前面出现*号是什么意思呢？

### ISSUE THREAD

**Issue by y19931027** [neolee/pilot#1250]
![QQ浏览器截图20200325212855](https://user-images.githubusercontent.com/54001982/77541688-f5dec080-6edf-11ea-8c2e-8c4a940a6a4f.png)
没运行成功，是哪里错了？

**Comment by neolee** [comment]
[*] 代表这个 cell 正在运行，如果时间长得不正常，可能是作为 kernel 的 Python 解释器出问题了，可以看看命令行有什么错误信息没有。

可以在页面上选择 Restart kernel 重启 kernel。

另外你这个 cell 里的代码有问题，try 和 except 没有对齐，而且 try 后面没有内容。

**Comment by y19931027** [comment]
麻烦老师了，这个提示错误说没声音这个属性？
![QQ浏览器截图20200325235128](https://user-images.githubusercontent.com/54001982/77556655-bfab3c00-6ef3-11ea-9ff3-d9cfc54b4c58.png)

**Comment by neolee** [comment]
那就是没有啊，你的 `Animal` 类咋定义的？

**Comment by y19931027** [comment]
![QQ浏览器截图20200326135727](https://user-images.githubusercontent.com/54001982/77615274-dd1aed00-6f69-11ea-9ad4-fc7259b34f46.png)
 前面运行的时候没出现问题呀

**Comment by neolee** [comment]
你还是没给我看到 Animal 类的实现，我怎么知道有没有问题。

然后，你在 Cat 和 Dog 类里定义的方法叫 `Voice`，而你调用时方法写的 `voice`。Python 是区分大小写的，这俩方法名字不一样。

Keep focus.

**Comment by y19931027** [comment]
老师太厉害了，一说就行了，我看半天都不知道哪里错了。像这个对话机器人，
![QQ浏览器截图20200326165627](https://user-images.githubusercontent.com/54001982/77628945-b5388300-6f83-11ea-8b1e-feaba60dcc70.png)

![QQ浏览器截图20200326165710](https://user-images.githubusercontent.com/54001982/77628965-bb2e6400-6f83-11ea-980b-dd4c3d427d9d.png)


![QQ浏览器截图20200326165739](https://user-images.githubusercontent.com/54001982/77628972-bf5a8180-6f83-11ea-9fa0-905984e62b17.png)
