### ISSUE TITLE
关于类对象的疑问？

### ISSUE THREAD

**Issue by gaoteng-pro** [neolee/pilot#1251]
```python

class Dog:
    def __init__(self,name):
        self.name = name
        
a = Dog(1)
b = Dog(2)
```
`Dog(1)`和`Dog(2)`是`Dog`类的对象，而后分别赋值给变量`a`和变量`b`，对象的格式是：**类名+括号以及括号里的参数**；我们也知道1和2也是对象，那1和2这种对象为什么不是**类名+括号**这种格式呢？

**Comment by neolee** [comment]
你可以理解为 `1` 是 `int(1)` 的简化版本，这些类型太常用了，所以解释器对其提供了简单的写法。
