### ISSUE TITLE
关于理解对象与类 Python 篇的疑问

### ISSUE THREAD

**Issue by gaoteng-pro** [neolee/pilot#1252]
>仔细看上面的代码，a c d 虽然是不同类的对象实例，但是因为它们都是 Animal 或其子类的对象实例，所以拥有 Animal 类所定义的标准接口（继承），从而可以在一个循环中一视同仁的处理，而且不同类的对象实例自动调用了各自类定义的 voice() 方法实现，产生各自正确的输出（多态）。

（如图1所示）

如图2，即使a c d不是Animal或其子类的对象实例，但运行结果依然如故。所以，在一个循环中可以一视同仁的处理，并不是因为a c d是Animal或其子类的对象的缘故，而是因为他们都有`.name`的属性和`.voice()`的方法，是这样吧？

同理，多态也和子类父类无关，那么多态到底是什么意思？不同的类对象在一个`for in`结构中输出给自的属性方法？多态和`for`循环有关？

(图1）
<img width="953" alt="截屏2020-03-26 下午1 17 47" src="https://user-images.githubusercontent.com/57254889/77613896-d9d23200-6f66-11ea-86bd-0a06d0e4ed16.png">
（图2）
<img width="717" alt="截屏2020-03-26 下午1 20 56" src="https://user-images.githubusercontent.com/57254889/77613904-e060a980-6f66-11ea-8bd8-0b6db917c708.png">

**Comment by neolee** [comment]
Emmm，这个问题稍微复杂，主要和我设计课程的理念有关。我尝试解释下。

1. 面向对象的思想是一种 paradigm，是一种思维模板，而不是具体的工具和实现，所以概念和具体语言的实现并不完全一样，不同的语言也会有稍微不同的实现。

2. 仅就 Python 语言来说，它采取的策略叫 “duck typing”，意思是“如果它长得像鸭子、叫起来也像鸭子，那么它就是鸭子”，这是不少动态语言普遍采用的方案，简单说，就是：一个对象只要有特定的方法，你就可以调用它，和它是什么类型关系不大。所以，确如你推测，在 Python 中，你完全可以定义几个完全没关系的类的对象，只要它们都有某些方法，你就可以把它们一致的处理，并不一定要做继承处理。

3. 虽然有第2点，但继承的概念在 Python 中还是很重要，因为它是一种保险机制：如果你继承了一个父类，那么父类定义的所有方法（我们讲课时也说过，这就是所谓的"接口"）就有了保底实现，你可以放心的去调用这些方法；如果你不作这样的继承，那么你调用对象时就要碰运气了，如果他没有定义相关方法，你的程序就会崩溃。所以我课上讲过，父类可以帮助我们统一接口，而多态保证了父类子类的实现可以差异化。

4. 很多其他语言，尤其是静态语言，多态是依赖于继承体系的，比如 C++、Java 等。

最后，我的课程设计原则是：讲一般性规律和通用概念，然后讲 Python 实现和一些特殊设计，如果没有必要，甚至也不会介绍 Python 的一些特殊之处。

**Comment by gaoteng-pro** [comment]
老师课程讲得很棒，能感受到老师心思细腻。自己就是小白（虽然以前上大一的时候接触过一点编程，但当初不懂珍惜，只求不挂科，内容早就还给老师了，而且一直没有练习），跟着老师一路学过来，虽然开始晚了一些，但现在可以用python做一点点事情，即使这样也比用自己的大脑做得又快又准，感觉很幸福，感谢李骏老师！

之所以会有这样的问题，是想搞明白问题的原因到底是哪个，尽量别犯归因谬误。老师也曾说过，我们犯的90%的错误都是归因错误，所以我就想弄明白造成这种结果的真正原因是哪个。确实，编程世界的猜想+验证的周期非常短。

最后，对象可以理解成是一个**袋子**吗？把一组数据（属性）和函数（方法）打包装到一块的大袋子，方便调用这些方法和数据（因为经常要用到）。毕竟如果要实现这样的功能，仅用一个函数是不行的，如果可以，那函数也太复杂了，不利于管理，不利于分而治之。

也就是，单个功能靠函数就可以，如果是一组功能，让一个函数来实现，每次调用这个函数，会把里面的一组功能都运行一遍，可我们又不想每一次把里面的所有功能都运行一遍；而零星地写几个相关的函数，虽然每个函数的功能单一，但毕竟不在一块，每次调用也很麻烦。于是对象这个**袋子**应运而生，不仅解决了一组功能写进一个函数的冗杂，也解决了一组功能分割成几个函数而后散落一地一盘散沙，每次挨个调用很麻烦的窘境。

所以，可以把对象理解成一个“袋子”吗？而我们真正需求的，其实就是里面的数据（属性）和打包好的一组功能（方法），只是函数不可以成为这样的袋子，可以这样理解吗？

**Comment by neolee** [comment]
是的，“袋子”这个理解完全没问题。

不过你最后一句话有点小问题，实际上函数也可以成为打包其他函数和数据的袋子，事实上 functional paradigm 就是这么干的。不过这种思维比面向对象的抽象程度高很多，理解起来更困难一些，入门从面向对象的 paradigm 开始挺好。

**Comment by gaoteng-pro** [comment]
functional paradigm是类似老师讲过的`map,ruduce`吗？

如果是的话，`map,ruduce`只是在传递参数的时候，第一个参数是函数，然后用第一个输入的参数（函数）来处理后面的参数。这也只是把一个函数装进了袋子里，而面向对象理论上可以装无穷个函数，一个和无穷个的区别还是挺大的。

单就打包一组功能的角度来看，functional 不如面向对象强大吧？

**Comment by neolee** [comment]
只是打包函数的话，一个文件（module）也可以做到，这不是什么了不得的事情。

重要的是实现模块化和良好的模块粘合。
