### ISSUE TITLE
在 jupyter 输入学习命令没有结果出来

### ISSUE THREAD

**Issue by LFN3399** [neolee/pilot#1253]
输入第一行时没有结果出来，继续全部输入完也是一样，是什么原因呢？
![1585224655(1)](https://user-images.githubusercontent.com/62497511/77645778-46b4ee80-6f9e-11ea-857d-031a4ecd238f.jpg)

**Comment by neolee** [comment]
你没有运行它们啊，看单元格前面的 [] 里面都是空的……

**Comment by LFN3399** [comment]
怎么运行它们呢？[]也无法输填空，我点击一下[] 输入数字 [] 就消失了

**Comment by LFN3399** [comment]
问题已经解决了，真应该多看Wiki，有问题先自己琢磨，最后不行才问老师
![1585463836(1)](https://user-images.githubusercontent.com/62497511/77842993-3766b880-71cb-11ea-819e-e7ccd9aef172.png)
