### ISSUE TITLE
运行jupyter lab 不自动跳转；在网页上面输入链接，显示错误

### ISSUE THREAD

**Issue by jsycoo1** [neolee/pilot#1255]
![微信截图_20200327223946](https://user-images.githubusercontent.com/59406051/77767404-fe6bfe00-707b-11ea-9063-6c66c176dbb7.png)

**Comment by jsycoo1** [comment]
![问题2](https://user-images.githubusercontent.com/59406051/77767442-0c218380-707c-11ea-8761-73a42c500927.png)

**Comment by neolee** [comment]
你输入的这啥地址啊……

应该输入命令行里的那个 `http://localhost:8888/...` 地址，注意要那一整行。
