### ISSUE TITLE
多台电脑如何配置 Git 仅使用一个 GitHub 账号

### ISSUE THREAD

**Issue by Sean0932** [neolee/pilot#1257]
老师你好：

有 2 台 Mac 电脑，请问可以配置 Git 仅使用一个 GitHub 账号吗？

**Comment by neolee** [comment]
当然，一般人都是这么干的，还能拿来做文件同步呢。

**Comment by Sean0932** [comment]
老师，我在按照[帮助文档](https://help.github.com/cn/github/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent)操作。

请问下面截图中的文字内容，我应该如何操作。没看懂。

![image](https://user-images.githubusercontent.com/48595129/77844292-207a9300-71d8-11ea-922d-853824b21a50.png)

**Comment by neolee** [comment]
你使用 GitHub 上的 repo 时，坚持用 https 的那个仓库地址，不要用 ssh 打头的那个。

只要按照这个规则去做，就不需要做你看到的哪些操作。

**Comment by Sean0932** [comment]
好的，谢谢！
