### ISSUE TITLE
操作符计算结果不对的问题

### ISSUE THREAD

**Issue by LFN3399** [neolee/pilot#1258]
红色框部分  a * g 得到结果是18.84  ，正确结果不是4.2吗？
                    g / f 得到结果是1.0 ，正确结果不是0.222吗？        
![1585474798(1)](https://user-images.githubusercontent.com/62497511/77845868-a00e5f00-71e4-11ea-9caa-c94ce3d8bd12.jpg)
![1585474852(1)](https://user-images.githubusercontent.com/62497511/77845871-a3094f80-71e4-11ea-9e72-a7828f13b949.jpg)

**Comment by neolee** [comment]
这要看你之前执行过什么，每个单元格前面的 [] 里是代码执行的顺序，和你写的顺序不一定一样。从你的截图可以推测你来来回回执行了很多代码，自己也不记得执行了哪些以及执行顺序如何。

如果你自己经常不是很清晰，我建议你把相关的代码写在一个单元格里，明确每个变量的值，比如这样：

```python
a = 7
g = 0.6
print(a * g)
```

这样不容易出问题。

**Comment by LFN3399** [comment]
问题解决了，是顺序问题，把填过的格都删掉从新黏贴上去就可以重新开始了
