### ISSUE TITLE
VS code  出现异常

### ISSUE THREAD

**Issue by nioben** [neolee/pilot#1259]
![QQ浏览器截图20200329220047](https://user-images.githubusercontent.com/62788868/77851014-00af9300-7209-11ea-89dd-771272ce9c2b.png)

这个是哪里出错了？

**Comment by nioben** [comment]
![QQ浏览器截图20200329222448](https://user-images.githubusercontent.com/62788868/77851589-90a30c00-720c-11ea-8b8a-1db9879fe0a5.png)

**Comment by neolee** [comment]
看上去你把你的用户根目录 init 成一个 git repo 了。

**Comment by nioben** [comment]
嗯，我是想修改一下提交的远程仓库，就胡乱的在根目录下init 了，要怎么操作恢复到之前呢？VS code 打不开了，我卸载了下一个还是这样。

**Comment by neolee** [comment]
把根目录下的 `.git` 目录删除，注意这个目录的名字最前面是个点，别漏了。

**Comment by nioben** [comment]
![QQ浏览器截图20200331202402](https://user-images.githubusercontent.com/62788868/78027963-d4268300-7390-11ea-9b3d-0268af51ea40.png)
![QQ浏览器截图20200331202722](https://user-images.githubusercontent.com/62788868/78027976-d983cd80-7390-11ea-953a-ee88b4007a17.png)
 单点测试，边上没有Debug 按钮，右边也没有运行代码的按钮。

**Comment by nioben** [comment]
我换了一个Github 账号，本地仓库推送上远程仓库失败，
![QQ浏览器截图20200331203624](https://user-images.githubusercontent.com/62788868/78028339-70e92080-7391-11ea-86be-9b20a0493df3.png)

![QQ浏览器截图20200331203913](https://user-images.githubusercontent.com/62788868/78028362-7cd4e280-7391-11ea-960b-f995a060275c.png)

![QQ浏览器截图20200331204420](https://user-images.githubusercontent.com/62788868/78028414-9544fd00-7391-11ea-97aa-7c1c36c50000.png)
 checkpoints 文件和pycached 这个缓存文件是什么呢？
我把VScode 卸载了重新下的，有些文件说要手动删除，重新下载存放地址是，
![QQ浏览器截图20200331202819](https://user-images.githubusercontent.com/62788868/78028845-3a5fd580-7392-11ea-8149-8533a7b9dcea.png)
以前没删除干净和重新下载存放在别处有影响没？总感觉有些地方有问题又不知道哪里有问题。2个问题，一个是换仓库了推送失败，另一个是VScode 删除了重新下载有问题没，耽误老师宝贵时间了哈。

**Comment by neolee** [comment]
整理一下你的思路先，你到底遇到的是什么问题？

首先，停止做“你自己都不知道会发生什么”的任何操作，那只会越来越乱。比如什么“胡乱创建仓库”啦，什么“换仓库”啦，你自己可能都不知道这是啥意思，乱操作干啥呢？

然后，你的 Visual Studio Code 没啥问题，除非你确定它有什么问题，就不要折腾它啦！

再然后，绝对不要在你的用户根目录或者一些系统目录或者某盘的根目录下执行 `git init`，你之前做过这样的操作的话，要优先解决这个问题，清理掉。方法是：

1. 执行 `cd C:\Users\Hasee` 进入用户根目录；
2. 执行 `ls -Hidden` 看看有没有 `.git` 这个目录，如果有的话——
3. 执行 `rm -Force .git` 删除上述目录，这样 git 就不会把这个根目录整个作为一个仓库了。

针对 **任何你可能错误操作过的目录** 都执行上述步骤。

最后，你可以创建一个干净的空目录，然后在这里面做尝试和学习，比如你可以：

```shell
mkdir C:\Users\Hasee\Code\learning
cd C:\Users\Hasee\Code\learning
git init
code .
```

后面可以参照教材去尝试（实际上到现在为止你也没说你到底在做啥，所以我也不知道你实际上是在学哪一章）。另外支线课程中有几讲建议你先看看，有个基本认知，对命令行环境、git、VS  Code 都有分开的支线课程可以看。

**Comment by nioben** [comment]
多谢老师了，我昨天删的不是根目录下隐藏目录  .git    而是 根目录下的 .gitconfig 。遇到问题就对命令执行环境蒙圈了，胡搞瞎搞，对git和命令执行环境还不熟悉，学了怎么使用 jupyter ,markdown的用法, 在学 VScode, 和 p2-2-docstrins. 有时候是按照教材和支线课学，学着学着就出现问题走不动了，然后就先跳过去学另外的章节了。做梦都开始在遐想什么命令是干什么用的了。

**Comment by nioben** [comment]
老师你用的是什么词典来着？我上次在视频里看到了一下忘记了，就是一个词除了有解释之外，还有科属分支，有个视频里你说 苹果和山楂是同属，和桃是同科来着，我当时有印象，但是没记住词典名字，现在想下一个词典。手机上是用有道词典。

**Comment by nioben** [comment]
我学了聊天机器人，bot.py  和 garfield.py 。然后推送到 Github 的远程仓库出现问题了，原因是我换了一个GitHub账号，提交，推送不上去了，然后一直折腾。胡搞瞎搞。

**Comment by neolee** [comment]
看得出，你这个人比较性急，问题很多很汹涌，这既好也不好，还是注意一下合适的节奏，学一个新东西的起步阶段，踩踏实了再前进会比较好，而且最后会更快。另外，学计算机和编程，一定要搞清楚你和计算机之间的对话的每一次来回，到底是什么意思，不然很容易事倍功半。

词典方面，我那次提的叫 AED（Advanced English Dictionary），客观地说，对大多数中国人它并不能替代一部好的英汉词典，但可以作为补充工具。

**Comment by nioben** [comment]
嗯，谨记老师的教诲，看一遍根本就记不住多少，甚至下次都不知道咋操作了，最少看三遍敲三遍，理解透彻，我才看一遍敲一遍，是有点步子迈大了容易扯着蛋。急于求成，急功近利。要回去把基础再夯实一点，特别是git . 换个仓库怎么提交 推送就把我难倒了。 和计算机对话它提示说什么地方出错了，但自己呢就是要么理解得不够准确，要么就是不知道咋操作才能解决问题。search the web  . read the manual 也搞不定。还需要努力。
