### ISSUE TITLE
Win 10 下安装 busybox 显示 Couldn't find manifest for 'busybox'

### ISSUE THREAD

**Issue by daohehu** [neolee/pilot#126]
![2019-10-27_002057](https://user-images.githubusercontent.com/20347203/67622762-fd763c80-f84f-11e9-97a2-a56497cfac7e.png)

**Comment by Oodonkey** [comment]
同样也遇到了这个问题，不过解决了。
我的解决方法是：再次 scoop update ,然后 scoop install busybox。试试看吧~
![批注 2019-10-27 015418](https://user-images.githubusercontent.com/38784378/67623859-ceb29300-f85c-11e9-828c-a64b7bbec0b3.png)
![1](https://user-images.githubusercontent.com/38784378/67623865-d8d49180-f85c-11e9-9426-1a39bf6df325.png)

**Comment by neolee** [comment]
如果 scoop update 成功的话，应该是没问题的。

**Comment by Winsi0n** [comment]
我upadte成功，但是一样报错

PS C:\Users\Winsion> scoop update
Updating Scoop...
Updating 'extras' bucket...
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
Updating 'main' bucket...
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
Updating 'versions' bucket...
Scoop was updated successfully!
PS C:\Users\Winsion> scoop install busybox
Couldn't find manifest for 'busybox'.

**Comment by neolee** [comment]
这个 update 没成功啊，一堆的 'fatal'。

感觉 Scoop 安装就没完整成功。

建议重装 Scoop。

**Comment by Winsi0n** [comment]
我只看到了“Scoop was updated successfully!”
hhh

**Comment by Winsi0n** [comment]
重新安装后正常了！

**Comment by neolee** [comment]
Nice!

**Comment by bing90740** [comment]
scoop 怎么重新安装啊？将文件夹手动删除重新安装吗？

**Comment by neolee** [comment]
@bing90740 点击页面上方的 Wiki，找到 “重新安装 Scoop”。

**Comment by daohehu** [comment]
已解决：`scoop update` 成功后 ，再`scoop install busybox`成功。

**Comment by xiaoyangren513** [comment]
先关闭翻墙软件在 更新就可以了
