### ISSUE TITLE
无法将本地仓库放到 GitHub 上

### ISSUE THREAD

**Issue by xiaodan-J** [neolee/pilot#1260]
![微信图片_20200330211935](https://user-images.githubusercontent.com/62880296/77916867-58630280-72cc-11ea-9628-fd4596fc2b9d.png)
![微信图片_20200330212312](https://user-images.githubusercontent.com/62880296/77917128-b8f23f80-72cc-11ea-8972-e172cda392c7.png)
刷新后无法出现Sandbox for learning git的界面

**Comment by neolee** [comment]
`git remote add origin ...` 和 `git push -u origin master` 这两个命令都只用执行一次，以后要 push 本地版本到 GitHub 只需要执行 `git push` 就可以了。

从你截图的内容看，应该是已经 push 到 GitHub 了，本地没有新的版本。你本地的版本提交了么？执行下面几个命令让我看看结果：

```shell
git status
git log
git remote -v
```
