### ISSUE TITLE
下载耶鲁公开课报错： ModuleNotFoundError: No module named 'six.moves.urllib'; 'six.moves' is not a package

### ISSUE THREAD

**Issue by zilin19** [neolee/pilot#1261]
李老师，我按照笑来老师发的链接地研究了公开课的下载方法，但每次都显示 *ModuleNotFoundError: No module named 'six.moves.urllib'; 'six.moves' is not a packagegoogle * google上有人答复是：#python的安装路径下缺少带有whl的后缀pygame脚本，但我试了好多次，都没有找到原因。
请老师指点！
![Screenshot (11)](https://user-images.githubusercontent.com/51396634/77928362-e47c2680-72da-11ea-8825-2fdfbbdd9ae1.png)

**Comment by jiangbei168** [comment]
看看微博上有
