### ISSUE TITLE
Git 没有做基本设置导致无法 commit 的问题

### ISSUE THREAD

**Issue by LFN3399** [neolee/pilot#1262]
因为我开始没有做Git的基本设置，后面 commit的时候出现下图情况。

![1585643219(1)](https://user-images.githubusercontent.com/62497511/78004294-7e3fe400-736c-11ea-8395-db132bb033bf.png)

老师 我是否可以在Code目录下 重新做Git的基本设置呢？否则我应该怎么解决。

**Comment by neolee** [comment]
没问题，随时都可以设置，这个设置用了 `--global` 参数，所以是对你的所有 git 仓库都生效的。

补上设置就可以正常继续了。

**Comment by LFN3399** [comment]
老师 如一图，设置成功了吗？commit的时候出现第二图情况，VSC弹出来了（三图）我在第一列和第10列做了备注 保存关闭后，命令行没有变化，是不是我哪一步做错了？
一图
![1585645978(1)](https://user-images.githubusercontent.com/62497511/78008977-f1e4ef80-7372-11ea-9548-cb277282f0da.jpg)

二图
![1585647170(1)](https://user-images.githubusercontent.com/62497511/78011294-fa8af500-7375-11ea-902e-a8b83799e29a.jpg)

三图
![1585647288(1)](https://user-images.githubusercontent.com/62497511/78011652-6f5e2f00-7376-11ea-9b9d-e7c927eb55a1.png)

**Comment by neolee** [comment]
当 Visual Studio  Code 弹出来的时候，你需要在文件的顶部写一句话，作为这次提交的说明信息（*commit message*），然后保存，关闭，就能正常完成提交了。这个提交信息只有写在顶部的才有效。

**Comment by LFN3399** [comment]
我在VSC的做法正确吗？在首行写（一图）？保存关闭后 命令界提示这样一句话Aborting commit due to empty commit message，是不是我哪里做错了

一图
![1585654478(1)](https://user-images.githubusercontent.com/62497511/78022305-4e520a00-7387-11ea-8433-54947cf29a8e.jpg)

**Comment by neolee** [comment]
这个不清楚，如图你保存这个文件然后关闭，应该是不会有问题的。出现 Aborting 的提示，要么是没有保存，要么是有其他问题。

**Comment by LFN3399** [comment]
老师 我运行 code .gitconfig 命令的时候并没有像老师视频里的一样有名称和邮箱等信息，我的是空的。（如一图是老师教程里的，二图是我的），是我的基本设置没有成功吗？

一图
![1585721343(1)](https://user-images.githubusercontent.com/62497511/78104856-76427b80-7422-11ea-9dd1-3bc3711beac4.jpg)
二图
![1585721260(1)](https://user-images.githubusercontent.com/62497511/78104877-80647a00-7422-11ea-9935-7ace53dc5fe5.jpg)

**Comment by neolee** [comment]
只要 `git config --list` 里面有就没问题。

**Comment by LFN3399** [comment]
问题一解决，名称和邮箱没有加双引号，重新设置一次再跟着老师的视频一步一步操作就好了
