### ISSUE TITLE
执行 code. 出错

### ISSUE THREAD

**Issue by llll0072** [neolee/pilot#1264]
使用命令code.的时候出错
![QQ浏览器截图20200401214229](https://user-images.githubusercontent.com/55533127/78144118-c5f46780-7461-11ea-9940-88f0b1b8feaa.png)

**Comment by neolee** [comment]
支线课程和主课里我都反复说过的，仔细看清楚你要输入的是什么，你实际输入的是什么。以及系统返回的信息是什么。

**Comment by llll0072** [comment]
是上面的一个命令，code.不能执行，我百度了一下，说是vs要设置为管理员权限，也设置了。还是不行。拼错了？

**Comment by neolee** [comment]
你在截图里输入的三个命令，没有一个是对的。

前两个命令和参数之间要有空格，最后一个拼写错误（大小写也不对，这个不算错但最好按照命令的大小写来）。

**Comment by llll0072** [comment]
搞明白了。是没有在执行程序所在目录。

**Comment by neolee** [comment]
哈？你就算在正确的目录下执行 `code.` 这个命令也不可能成功吧……
