### ISSUE TITLE
自动办公 read_excel() 出错说文件找不到

### ISSUE THREAD

**Issue by adela1987** [neolee/pilot#1265]
老师您好！pandas读取Excel 报文件找不到。路径看不出哪里出错了“ import pandas as pd
df=pd.read_excel('assets/expense/test.xlsx')”
![70E9789D-9658-4568-A9C5-E54EE7F1C7E1](https://user-images.githubusercontent.com/49184972/78229791-0526c500-7503-11ea-9576-269a37963dd8.png)

**Comment by neolee** [comment]
你这个 notebook 在哪里？

**Comment by adela1987** [comment]
记事本地址：C:\Users\adela\Code\pilot-student
excel文件：C:\Users\adela\Code\pilot-student\assets\expense

**Comment by adela1987** [comment]
> 你这个 notebook 在哪里？


记事本地址：C:\Users\adela\Code\pilot-student
excel文件：C:\Users\adela\Code\pilot-student\assets\expense

**Comment by adela1987** [comment]
> 你这个 notebook 在哪里？

啊，理解了。是文件相对于记事本的地址。谢谢
