### ISSUE TITLE
建一个自己的博客站要从哪开始呢

### ISSUE THREAD

**Issue by xiaowei0189** [neolee/pilot#1267]
我已经简单的学习和了解了 HTML CSS JS，跟着 django的入门教程走到第二遍但是还是很模糊。我希望能建一个像老师那样的博客站，能实现简单的写和管理功能。老师能给一些建议吗。

**Comment by neolee** [comment]
我 2000 年开始写博客用的是 [Wordpress](https://wordpress.org/)，后来用过（现在已经停止更新的）Octopress，现在个人站用的是 [Hugo](https://gohugo.io/)。

如果只是想要有个可以写东西和分享的站点，最简单的办法就是用 GitHub 提供的 [GitHub Pages](https://pages.github.com/) 服务，什么编程都不需要，会用 GitHub 和 Markdown 就行，在支线课程讲 Markdown 的那一讲里我讲过。
