### ISSUE TITLE
运行 git log 后不能回到 PS 命令行的原因

### ISSUE THREAD

**Issue by LFN3399** [neolee/pilot#1269]
老师 虽然知道用 q  可以结束命令再回到PS命令行，但还是想搞懂是什么原因造成无法像之前一样自动回到PS命令行（如一图），我是否可以用 git revert 命令来恢复？

一图
![1585901531(1)](https://user-images.githubusercontent.com/62497511/78338758-f05f3580-75c5-11ea-8de2-eafc27bbedaf.jpg)

**Comment by neolee** [comment]
因为很快 log 就会比较长，一屏显示不下，所以缺省情况下，`git log` 会调用 `less` 命令来显示，这样可以上下滚屏来查看很长的 log 列表。

如果不希望这样，可以用 `git --no-pager log`；还可以设置 alias 来定义自己喜欢的 log 样式，可以学习 Git Book 中的相关内容。

不过我看你折腾这个 git 好久了，这个不算是编程入门的关键知识点，是不是值得你自行判断。

**Comment by LFN3399** [comment]
运行  git --no-pager log  后显示出来的感觉才对了。一图是之前的样子，二图是运行  git --no-pager log 的样子。

一图
![1586066545(1)](https://user-images.githubusercontent.com/62497511/78468060-36db9e00-7746-11ea-8d27-9e847fe84d79.png)

二tu 
![1586066584(1)](https://user-images.githubusercontent.com/62497511/78468062-3ba05200-7746-11ea-8be6-21faf4dcc8e9.jpg)
