### ISSUE TITLE
无法在学习用书中输入代码

### ISSUE THREAD

**Issue by hailinsu** [neolee/pilot#127]
我发现还是不行，重复操作了好几次，看不见代码
![OC@QNXE )O`HCW6Y7O~IXJ](https://user-images.githubusercontent.com/48571418/67626318-1e548700-f87c-11e9-9910-8a892dcc39df.png)
下面是我的操作步骤，看哪儿有问题吗？
fork获取你的用书第一部的超链接，然后跳转到下面图片中的分支
![U9 8@UEQ W50$9MNM8I2D`5](https://user-images.githubusercontent.com/48571418/67626331-552a9d00-f87c-11e9-88e8-b7b2f7639df7.png)
复制粘贴新的repe，然后打开命令行界面进行操作
![KAQ97YVI(MK FB6}2J{Z9{F](https://user-images.githubusercontent.com/48571418/67626343-860ad200-f87c-11e9-8625-d15b4c73262a.png)
![3T}S(G FTHCNKEIJ7VPQ`7E](https://user-images.githubusercontent.com/48571418/67626344-902cd080-f87c-11e9-8e2f-9c5ded84d859.png)

**Comment by hailinsu** [comment]
![E~17UDA_2{LT72G8EOIQ2X2](https://user-images.githubusercontent.com/48571418/67626395-8c4d7e00-f87d-11e9-8f81-e903862419dc.png)
我看到了在里面书代码 但是那些字删不掉 不能更改 所以肯定是哪儿出问题了

**Comment by neolee** [comment]
所以你已经获取并打开了学习用书，目前的问题是打开 notebook 之后无法输入代码？你点击哪些代码 cell 格子会发生什么？

**Comment by hailinsu** [comment]
![KK~F~EDG~(`GZFV1G$Q4 AB](https://user-images.githubusercontent.com/48571418/67630701-e3c40c00-f8c6-11e9-8b8e-b5fff7a1741f.png)
![H)3X H}IUD6~3DW0H%8BW](https://user-images.githubusercontent.com/48571418/67630709-f3435500-f8c6-11e9-8ec6-8c78cd4d2493.png)
只有这两种情况

**Comment by hailinsu** [comment]
![H)3X H}IUD6~3DW0H%8BW](https://user-images.githubusercontent.com/48571418/67630725-30a7e280-f8c7-11e9-824f-ad62682a4e18.png)
![KK~F~EDG~(`GZFV1G$Q4 AB](https://user-images.githubusercontent.com/48571418/67630730-369dc380-f8c7-11e9-8d39-abadbce56bb3.png)

**Comment by neolee** [comment]
你用的是什么浏览器？

以前有否安装过 Python 和/或 Jupyter 相关软件？

另外请执行下面几个命令，让我看看返回的结果是啥：

python -V
python3 -V
pip3 -V
pip3 list

**Comment by hailinsu** [comment]
![4R%IK@LT{)FBR3O7S{1L%`0](https://user-images.githubusercontent.com/48571418/67631268-edea0880-f8ce-11e9-863e-6f9c5f1363a0.png)
![4T(VJ1Z}L38V~QP%5MESDLW](https://user-images.githubusercontent.com/48571418/67631269-f04c6280-f8ce-11e9-9025-402124deced6.png)
用的是火狐浏览器

**Comment by neolee** [comment]
从这些信息看，你的环境很正常，没有问题。Firefox 浏览器对 Jupyter Lab 支持也无问题，所以是个少见的问题，可能需要一点时间来排查。

首先执行下面的命令看看结果：
```powershell
jupyter --path
```

然后在你的 `C:\Users\海琳\Code\pilot-student` 目录下运行：
```powershell
gci | select FullName, IsReadOnly
git status
```

最后：
```powershell
jupyter lab
```

保持这个命令行窗口和浏览器窗口并排都开着，截屏给我看看。

**Comment by hailinsu** [comment]
![$FR%}2C$62EP_5K{X5IGHMV](https://user-images.githubusercontent.com/48571418/67634809-6961af00-f8fb-11e9-9a97-9b57bec476ba.png)

![85J~ZE0D7IC_O_JN~_6YQ3Y](https://user-images.githubusercontent.com/48571418/67634790-3f0ff180-f8fb-11e9-8300-dcd971d5b657.png)

**Comment by neolee** [comment]
为什么你浏览器里运行的是 nbviwer，这只是个阅读器，自然里面啥都不能改；

浏览器应该打开你本地的 Jupyter Lab，里面是你的学习用书。

如果命令行里运行 jupyter lab 没有自动打开浏览器，你可以从命令行里拷贝 `http://localhost:` 开始的完整一行，粘贴到你的浏览器的地址栏，然后回车。

**Comment by hailinsu** [comment]
![AQL)9IIZZO@A(BECP06F7R2](https://user-images.githubusercontent.com/48571418/67634965-c01bb880-f8fc-11e9-9ef5-0449d9242fbe.png)
我的问题已经解决了 搞了这么久终于可以看书了 真是不容易啊

**Comment by neolee** [comment]
Nice!
