### ISSUE TITLE
网络代理状态下 pip install pandas 失败

### ISSUE THREAD

**Issue by Gaomingzhao** [neolee/pilot#1270]
![image](https://user-images.githubusercontent.com/24623343/78421571-39c58880-768b-11ea-8dbc-970632aadd4e.png)

搜到了之前的 issue，https://github.com/neolee/pilot/issues/1073
李骏老师的回答是：安装失败是因为网络问题，可能需要代理。

不过我一直是在科学上网状态下的，是我对「代理」理解错了么。

**Comment by neolee** [comment]
1. 绝大部分代理都需要配置才会对命令行起效，可以咨询下你的服务提供者。

2. 如果是 pip install 的情况，可以考虑用国内的镜像，会更简单方便，详情参见 Wiki 里的相关问题。

**Comment by Gaomingzhao** [comment]
> 1. 绝大部分代理都需要配置才会对命令行起效，可以咨询下你的服务提供者。
> 2. 如果是 pip install 的情况，可以考虑用国内的镜像，会更简单方便，详情参见 Wiki 里的相关问题。

谢谢老师，问题解决了。顺便自己一路搜索还学到了很多其他东西
