### ISSUE TITLE
p2-8列表中执行print（list（））报错 SyntaxError:invalid syntax

### ISSUE THREAD

**Issue by Achaosj** [neolee/pilot#1272]
我在执行下面代码的时候报错，但明明和教材是一样，想请教下问题出在哪里？
print(list())

print(list('aeiou'))

print(list(('a','e','i','o','u'))

print(list({'a', 'e', 'i', 'o', 'u'}))
      

print(list({'a':1,'e':2,'i':3,'o':4,'u':5}))

  File "<ipython-input-18-a272f2b76295>", line 7
    print(list({'a', 'e', 'i', 'o', 'u'}))
        ^
SyntaxError: invalid syntax

**Comment by neolee** [comment]
为啥提了俩一模一样的问题？

Duplicate of #1271
