### ISSUE TITLE
scoop 安装出错，相关疑难里中的方法无法解决

### ISSUE THREAD

**Issue by maodandandan** [neolee/pilot#1273]
PS C:\Users\chaoqun_wu> scoop list
Installed apps:

  7zip  *failed*
  dark  *failed*
  git 2.26.0.windows.1 *failed*
  innounp  *failed*

PS C:\Users\chaoqun_wu> scoop install git
Scoop uses Git to update itself. Run 'scoop install git' and try again.
ERROR It looks like a previous installation of git failed.
Run 'scoop uninstall git' before retrying the install.
WARN  'git' (2.26.0.windows.1) is already installed.
Use 'scoop update git' to install a new version.
PS C:\Users\chaoqun_wu> scoop uninstall git
Uninstalling 'git' (2.26.0.windows.1).
'git' was uninstalled.
PS C:\Users\chaoqun_wu> scoop install git
Scoop uses Git to update itself. Run 'scoop install git' and try again.
Installing 'git' (2.26.0.windows.1) [64bit]
Loading PortableGit-2.26.0-64-bit.7z.exe from cache
Checking hash of PortableGit-2.26.0-64-bit.7z.exe ... ok.
Extracting dl.7z ... Invoke-ExternalCommand : 无法对参数“FilePath”执行参数验证。参数为 Null 或空。请提供一个不为 Nul
l 或空的参数，然后重
试该命令。
所在位置 C:\Users\chaoqun_wu\scoop\apps\scoop\current\lib\decompress.ps1:81 字符: 38
+     $Status = Invoke-ExternalCommand $7zPath $ArgList -LogPath $LogPa ...
+                                      ~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Invoke-ExternalCommand]，ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Invoke-ExternalCommand

git : 无法将“git”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确
，然后再试一次。
所在位置 行:1 字符: 1
+ git config --get remote.origin.url
+ ~~~
    + CategoryInfo          : ObjectNotFound: (git:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Failed to extract files from C:\Users\chaoqun_wu\scoop\apps\git\2.26.0.windows.1\dl.7z.
Log file:
  ~\scoop\apps\git\2.26.0.windows.1\7zip.log

Please try again or create a new issue by using the following link and paste your console output:
https:////
PS C:\Users\chaoqun_wu> scoop checkup
ERROR '7-Zip' is not installed! It's required for unpacking most programs. Please Run 'scoop install 7zip' or 'scoop install 7zip-zstd'.
ERROR 'Inno Setup Unpacker' is not installed! It's required for unpacking InnoSetup files. Please run 'scoop install innounp'.
ERROR 'dark' is not installed! It's required for unpacking installers created with the WiX Toolset. Please run 'scoop install dark' or 'scoop install wixtoolset'.
WARN  Found 3 potential problems.

**Comment by maodandandan** [comment]
老师，好像并不是网络问题，我从新换了代理，scoop跟git能下载下来但是，不能安装

**Comment by neolee** [comment]
你安装 scoop 和几个基础性的软件包都没有成功，建议按照 Wiki 里的指引，删掉残骸重新安装。

根据以往其他同学的经验，这基本上都还是网络不顺引起的。

**Comment by maodandandan** [comment]
PS C:\Users\chaoqun_wu> iwr -useb get.scoop.sh | iex
Initializing...
Downloading scoop...
Extracting...
Creating shim...
Downloading main bucket...
Extracting...
Adding ~\scoop\shims to your path.
'lastupdate' has been set to '2020-04-05T21:37:42.6975453+08:00'
Scoop was installed successfully!
Type 'scoop help' for instructions.
PS C:\Users\chaoqun_wu> scoop list
There aren't any apps installed.
老师您好，我今天试了很久卸载了安装错误的scoop，但是 scoop list显示我没有安装任何scoop工具，这是什么原因啊？

**Comment by neolee** [comment]
首先执行 `scoop update` 看看是不是可以正确地更新本地的软件信息库。

如果上一步没有问题，试试 `scoop checkup` 并解决系统提出的问题。

**Comment by maodandandan** [comment]
老师您好，在每个未安装成功的应用都反复的uninstall、install后。终于安装好了。确实是网路问题，谢谢老师的耐心解答!

**Comment by YQQC-19** [comment]
![image](https://user-images.githubusercontent.com/96910374/147841487-0b1e74f3-5c8b-4176-8e32-d61a9c33b9c1.png)
我在安装 python时提示lessmsi 未安装成功 我用uninstall、install 试了好多遍都不可以

**Comment by neolee** [comment]
网络问题，Scoop 其实支持网络代理，可以搜索一下具体设置方法。
