### ISSUE TITLE
实践案例三 Web 项目 index.html 模板文件调用报错

### ISSUE THREAD

**Issue by best-way** [neolee/pilot#1274]
```python
class index:
    def GET(self):
        # return '<h1>Hello,world!</h1>'
        # data = web.input(name=None)
        return render.index()
        # return render.index()
```
index 类直接返回网页内容正常，一改成 return render.index()  浏览器访问就报错

后台报错代码
```
 File "C:\Users\86188\Code\learn-webpy\venv\lib\site-packages\web\template.py", line 1020, in compile_template
    compiled_code = compile(code, filename, "exec")
  File "C:\Users\86188\Code\learn-webpy\venv\lib\site-packages\web\debugerror.py", line 8
    def with (exception_type, exception_value, frames)
           ^
SyntaxError: invalid syntax

Template traceback:
    File 'C:\\Users\\86188\\Code\\learn-webpy\\venv\\lib\\site-packages\\web\\debugerror.py', line 8
        http://www.xfree86.org/3.3.6/COPYRIGHT2.html#5
```

网页报错图片：
![Uploading 微信截图_20200405105302.png…]()
sever.py 内容：
![Uploading 微信截图_20200405110051.png…]()
index.html 内容
<img width="580" alt="微信截图_20200405110133" src="https://user-images.githubusercontent.com/49242101/78465929-2fa89600-772e-11ea-8932-b124bc24d95c.png">
整个项目目录:
<img width="172" alt="微信截图_20200405110508" src="https://user-images.githubusercontent.com/49242101/78465931-3505e080-772e-11ea-8b3d-b07948cd8760.png">

报错是发生在把项目上传到github上之后（没部署前还是能调用的），然后用了老师给的html规范格式后就访问不了，然后把内容调整为最简单之后还是访问不了，网上也没查到解决方案

**Comment by best-way** [comment]
补充
网页报错图片：
<img width="490" alt="微信截图_20200405105302" src="https://user-images.githubusercontent.com/49242101/78465968-b78ea000-772e-11ea-936d-43926070f207.png">
sever.py 内容：
<img width="426" alt="微信截图_20200405110051" src="https://user-images.githubusercontent.com/49242101/78465961-ab0a4780-772e-11ea-8890-d635f6b37f38.png">

**Comment by best-way** [comment]
同样的sever.py和index.html 放到其他目录下用本地python 运行又可以调用了，就不知道之前那个目录下和在 venv环境下为啥就调用不了呢

**Comment by neolee** [comment]
你的表达非常的模糊和混乱，说实话我很难理解：在什么情况下会出错，什么情况下不会出错，基本上不太清楚。

这个项目，大致上目录结构是这样子的（里面有些文件和目录由于你还没做到那一步，暂时还没有，还有些我这里没列出的目录是临时文件可以不管它）：

```
❯ tree .
.
├── data
│   └── stars.db
├── server.py
├── star.py
├── static
│   ├── celestial.html
│   └── css
│       └── main.css
├── templates
│   └── index.html
└── venv
```

如果虚拟环境配置无误，在这个目录下运行 `source venv/bin/activate` 就可以激活虚拟环境，确认已经用 `pip install ...` 安装了所需的库，然后就可以用 `python server.py` 来运行了。

如果运行 `python server.py` 出现错误，把完整的错误提示拷贝过来，并把涉及到的 `server.py` 和 `index.html` 文件内容完整的拷贝过来。

至于其他的信息，比如你怎么折腾了一下又可以运行了，这个不是很重要，关键是怎么让错误可以复现，然后分析现场找到原因。不知道原因就解决了的问题，通常是没真正解决啥，肯定还会复发。

**Comment by neolee** [comment]
另外，学会在这里如何贴代码（我修改了你的顶楼，算是一个样例供你参考），这样你和别人都会省很多事。

**Comment by best-way** [comment]
谢谢李骏老师的建议，这个错误应该是index.html里面有代码或者规范错误，导致被调用失败，但是具体的报错信息不详细，我自己在摸索摸索代码吧

**Comment by neolee** [comment]
如果你的模板里只有 `<h1>...</h1>` 它怎么可能有错呀？

**Comment by best-way** [comment]
我开始也觉得奇怪，后面我把<h1>...</h1> 上下文的注释全删掉了，只留这一行，又可以了，原来注释内容也会有影响，具体哪行注释出了问题，还没详细查，感觉web领域自己还是需要实战做个小网站才行

**Comment by neolee** [comment]
实践案例三不就是做个小网站的起步么……

其实你遇到的问题完全正常，正确地解决掉它们你就学会了，但切记盲猜乱试，一定要一点点的推进，抓住一个问题搞明白和解决掉，是真正的解决掉——然后再下一个。乱试突然错误消失了，然后就继续下去，其实是很糟糕的，因为“你认知上的”问题其实没解决，迟早还会出来。

好像是列子讲过一个故事，说他某天射箭射中了靶心，很得意地去和师父炫耀，师父问他：你说说你是怎么射中靶心的？列子想了半天，发现自己完全不知道，说白了就是蒙的，顿时就从得意变成了焦虑……学任何东西，这个道理都是一样的。
