### ISSUE TITLE
爬取并打包公众号历史文章

### ISSUE THREAD

**Issue by Gaomingzhao** [neolee/pilot#1275]
最近一个月，把课程内容基本都学过了一遍，代码敲了两遍，非常粗糙地把 python tutorial 过了一遍。但是一直没敲出属于自己像样的代码——也不知道从何敲起，现在强烈希望能有一件事情可以把自己学过的一些基础技能串一串，用起来。

对数据分析感兴趣，但暂时没找到合适的项目去迈出第一步。

然后就是今天想起来了一个一直以来的需求，把一些优质公众号的文章爬取并打包下来，方便快速地阅读历史内容。其实之前用过某个开发者提供的类似服务，但目前暂停了。

所以这目前对我来说，是一个切实的需求。不知道做这么一件事情需要的技能包有哪些，以及具体的流程模块是怎样的？李骏老师可以简单指点一下吗，谢谢！

**Comment by neolee** [comment]
讲 web 基础的那一讲，还有实践案例2，这些深入搞明白是基础。

然后好好利用搜索引擎。

**Comment by Gaomingzhao** [comment]
嗯嗯好的 谢谢老师
