### ISSUE TITLE
git commit 命令出错

### ISSUE THREAD

**Issue by maodandandan** [neolee/pilot#1277]
老师，我在进行git commit命令时出错
PS C:\Users\chaoqun_wu\Code\Code\pilot-student> git commit

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'chaoqun_wu@chaoqun-wu.(none)')
PS C:\Users\chaoqun_wu\Code\Code\pilot-student> cd..
PS C:\Users\chaoqun_wu\Code\Code>  git config --global user.email "1335795322@qq.com"
PS C:\Users\chaoqun_wu\Code\Code>  git config --global user.name "maodandandan"
PS C:\Users\chaoqun_wu\Code\Code>  cd pilot-student
PS C:\Users\chaoqun_wu\Code\Code\pilot-student> git commit
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   p1-2-structure-1.ipynb
        modified:   p1-3-structure-2.ipynb
        modified:   p1-4-structure-3.ipynb

no changes added to commit (use "git add" and/or "git commit -a")

**Comment by maodandandan** [comment]
第一次运行错误后，我根据issues进行了用户名跟邮箱的设置，但是进行第二次git commit时出现了新的问题

**Comment by neolee** [comment]
第一次问题你已经解决了。

第二次问题，不是说得很清楚吗，你必须先把更改加入 staging area，然后才能 commit。仔细看教程和配套视频。

**Comment by maodandandan** [comment]
老师，我想我现在应该是把修改提交至暂存区域，但是现在跳到这个页面，不知道该怎么办了，没有ps什么什么的输入命令的东西了

# Please enter the commit message for your changes. Lines starting
# with '#' will be ignored, and an empty message aborts the commit.
#
# On branch master
# Your branch is up to date with 'origin/master'.
#
# Changes to be committed:
#       modified:   p1-2-structure-1.ipynb
#       modified:   p1-3-structure-2.ipynb
#       modified:   p1-4-structure-3.ipynb

**Comment by maodandandan** [comment]
应该是前面有#的缘故，字体变的很大
Please enter the commit message for your changes. Lines starting
 with '#' will be ignored, and an empty message aborts the commit.

# On branch master
 Your branch is up to date with 'origin/master'.

 Changes to be committed:
      modified:   p1-2-structure-1.ipynb
#       modified:   p1-3-structure-2.ipynb
       modified:   p1-4-structure-3.ipynb

**Comment by maodandandan** [comment]
好像是有#的缘故，字变得很大
Please enter the commit message for your changes. Lines starting
 with '#' will be ignored, and an empty message aborts the commit.

 On branch master
 Your branch is up to date with 'origin/master'.

 Changes to be committed:
       modified:   p1-2-structure-1.ipynb
       modified:   p1-3-structure-2.ipynb
       modified:   p1-4-structure-3.ipynb

**Comment by maodandandan** [comment]
![批注 2020-04-06 223604](https://user-images.githubusercontent.com/63174957/78570444-94134480-7857-11ea-80f7-4c81cb14003b.png)

**Comment by neolee** [comment]
你为什么不按照教程一步步操作呢？前面漏了用户名和邮箱配置，这里又没做 git 编辑器的配置。

在 commit 的时候 git 会打开你配置的一个编辑器，让你输入提交的说明信息，如果你没配置就会用缺省的一个叫 vi 的编辑器——也就是你看到的这个东西，这个东西一般人基本是不会用的，所以我建议配置编辑器使用 Visual Studio Code。

明显你也没看教程或者配套视频，里面都讲的清清楚楚。

最后，你在截图所示的界面，可以先按 ESC 键，然后输入 `:q!` 来退出编辑器。

**Comment by maodandandan** [comment]
老师，我编程环境配置指南看了，但是没看Git 与 GitHub 入门。Visual Studio Code我也装了，又可能是因为我那一步漏掉或者操作不当，没有跳转过去。
我现在可以不管这个学习用书上传的问题，去重新按照教材检查一下基本设置可以吗？这个已经完成的记录会丢失吗？
![批注111112020-04-06 231133](https://user-images.githubusercontent.com/63174957/78574037-02f29c80-785c-11ea-87e4-7178c046de48.png)

**Comment by neolee** [comment]
你在使用 git 那就要知道 git 的一些基本知识呀。你先去看看 Git 教程吧。不会影响你的 Python 源文件。

**Comment by maodandandan** [comment]
明天还要上班，确实有些着急了。我会把教程全都再看一遍的。谢谢老师的耐心回答。
