### ISSUE TITLE
重复执行代码时 方括号 出现 * 号

### ISSUE THREAD

**Issue by LFN3399** [neolee/pilot#1278]
老师 第一次执行代码时显示正常输入，如果重复执行2次代码的时候旁边的 方括号 出现 * 号是什么问题呢？还导致后面的代码执行也是出现 * 号。如一图

一图
![1586246875(1)](https://user-images.githubusercontent.com/62497511/78645594-56abc700-78ea-11ea-87a6-6f5fe98ab4c7.jpg)

**Comment by neolee** [comment]
建议你看看支线课程关于 JupyterLab 的一讲。

前面的 * 代表该单元格正在执行（比如正在等你输入也算正在执行），一个 notebook 背后是一个 Python 解释器，一个单元格正在执行时其他单元格也只能等待（都会是 * 号）。

**Comment by LFN3399** [comment]
看了视频知道解决方法了，但是老师 我的juptyer 没有工具栏，反复看了几次教程没看到讲这部分的，要怎么安装呢？

**Comment by neolee** [comment]
没有工具栏是什么意思？

**Comment by LFN3399** [comment]
下图红框部分的工具栏
一图是老师教程的juptyer，二图是我的 juptyer

一图
![1586751719(1)](https://user-images.githubusercontent.com/62497511/79091932-cbb34c80-7d81-11ea-9927-6eb64bad1bee.png)

二图
![1586751818(1)](https://user-images.githubusercontent.com/62497511/79091938-d241c400-7d81-11ea-964d-77f554408c16.jpg)

**Comment by neolee** [comment]
这个情况很神奇，从来没见过。你用的是什么浏览器，换个浏览器试试？

**Comment by LFN3399** [comment]
还是没显示出来，看我的左边界面跟老师的的界面是不是少了部分功能

![1586762738(1)](https://user-images.githubusercontent.com/62497511/79101868-1c37a380-7d9c-11ea-8260-1311165d6476.jpg)
