### ISSUE TITLE
安装 mysql 和 redis 安装后 code . 等命令出错

### ISSUE THREAD

**Issue by cheneyjian** [neolee/pilot#1280]
老师：我把 mysql 和 redis 安装完了，输入 code . 等命令都返回 The term 'scoop' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

接着按照wiki中的内容 del .\scoop -Force返回如下
![image](https://user-images.githubusercontent.com/41112569/78774624-81b81880-79c7-11ea-9179-5e7f6303ee36.png)
我在安装redis的时候修改了了path
![image](https://user-images.githubusercontent.com/41112569/78774862-de1b3800-79c7-11ea-9924-607f1e879e62.png)
是不是有影响

**Comment by neolee** [comment]
注意不要在标题里写太多东西，标题应该言简意赅，然后在内容里说清楚问题细节。

另外你的问题表述有一些地方不太好理解：

1. 你运行 `code .` 怎么会报 `scoop` 的错呢？这不科学。
2. 你安装 mysql 和 redis 和 后面的报错有啥关系？意思是，安装这俩之前没有问题，安装之后开始出错？
3. 如果之前都好好的，这时候为啥要急着删除 scoop 呢？
4. 你删除 scoop 的操作没有成功，因为 scoop 的目录下有些文件正在运行或者被系统占用（比如是不是 mysql 或者 redis 服务正在运行？）

总之目前状况有点 nasty，你需要想清楚到底在做什么……

**Comment by cheneyjian** [comment]
我在安装玩redis后
就出现在命令行运行code . scoop list等操作都出现类似以下的结果
![image](https://user-images.githubusercontent.com/41112569/78789493-cb146200-79df-11ea-8a00-3165c981222f.png)
但是在文件夹是可以打开例如VScode 软件可以打开
现在想在命令行能运行code . scoop list等
不知道怎么做

**Comment by neolee** [comment]
我前面说了啊，很可能是你把 PATH 改坏了，不过由于你尝试了删除 scoop，搞不好部分删了又留了部分，更乱了。

在命令行执行 `$env:Path` 把结果给我看看。

**Comment by cheneyjian** [comment]
![image](https://user-images.githubusercontent.com/41112569/78794065-d1a5d800-79e5-11ea-8040-a5929668427b.png)

**Comment by neolee** [comment]
在我的系统里 Path 环境变量的值是这样的：

```
C:\Program Files\PowerShell\7;C:\Program Files\ConEmu\ConEmu\Scripts;C:\Program Files\ConEmu;C:\Program Files\ConEmu\ConEmu;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Razer Chroma SDK\bin;C:\Program Files\Razer Chroma SDK\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\PowerShell\7\;C:\Users\trust\scoop\apps\nodejs\current\bin;C:\Users\trust\scoop\apps\nodejs\current;C:\Users\trust\scoop\apps\python37\current\scripts;C:\Users\trust\AppData\Local\Programs\Python\Launcher\;C:\Users\trust\scoop\shims;C:\Users\trust\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Microsoft VS Code\bin;C:\Users\trust\AppData\Local\hyper\app-3.0.2\resources\bin;C:\Users\trust\scoop\apps\redis\current;C:\Users\trust\AppData\Local\Microsoft\WindowsApps
```

你正确安装完 scoop 以及 Python 之后，下面这几个路径是一定在里面的：

```
C:\Users\trust\scoop\shims;
C:\Users\trust\scoop\apps\python37\current\scripts;
C:\Users\trust\AppData\Local\Programs\Python\Launcher\;
```

而你安装好 Visual Studio Code 之后，下面这个路径也应该在里面：

```
C:\Program Files\Microsoft VS Code\bin;
```

我不知道你做了什么使得 Path 里这些该有的路径都不见了，自然也就找不到那些你想运行的程序了。

**Comment by cheneyjian** [comment]
把路径误删了，我也复制提供路径还是无效，修复也是可能的但是太耗时间了，所以我还是重装系统吧。另外我提个建议：
![image](https://user-images.githubusercontent.com/41112569/78807288-6c0e1780-79f6-11ea-9c94-1ab7e60b24a8.png)
这部分添加个警示防止有小伙伴像我一样误删了环境值路径，最后不得不重装系统
