### ISSUE TITLE
日期时间转字符串时区乱码

### ISSUE THREAD

**Issue by nioben** [neolee/pilot#1281]
![QQ浏览器截图20200410220751](https://user-images.githubusercontent.com/62788868/78996933-385afb00-7b78-11ea-9d78-bc3513245606.png)
![QQ浏览器截图20200410220801](https://user-images.githubusercontent.com/62788868/78996946-3ee97280-7b78-11ea-9e13-3cae5e9837d5.png)

**Comment by neolee** [comment]
有过类似问题，我上课也讲过，可以搜索下。
