### ISSUE TITLE
scoop update指令报错

### ISSUE THREAD

**Issue by lori1989** [neolee/pilot#1283]
PS C:\Users\gzhpe> scoop update                                                 
& : 无法将“C:\Users\gzhpe\scoop\shims\..\apps\scoop\current\bin\scoop.ps1”项        
识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径                                     
，请确保路径正确，然后再试一次。                                                                
所在位置 C:\Users\gzhpe\scoop\shims\scoop.ps1:3 字符: 71                              
+ ... on.expectingInput) { $input | & $path  @args } else { & $path  @args  ... 
+                                                             ~~~~~             
    + CategoryInfo          : ObjectNotFound: (C:\Users\gzhpe\...t\bin\scoop.p  
   s1:String) [], CommandNotFoundException                                      
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by neolee** [comment]
Scoop 没装好，按照 Wiki 里的说明删了重装。

通常是网络问题导致的。

**Comment by lori1989** [comment]
> Scoop 没装好，按照 Wiki 里的说明删了重装。
> 
> 通常是网络问题导致的。

**老师，我按照wiki上指令重装，也报错**

PS C:\Users\gzhpe> scoop uninstall scoop
& : 无法将“C:\Users\gzhpe\scoop\shims\..\apps\scoop\current\bin\scoop.ps1”项
识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径
，请确保路径正确，然后再试一次。
所在位置 C:\Users\gzhpe\scoop\shims\scoop.ps1:3 字符: 71
+ ... on.expectingInput) { $input | & $path  @args } else { & $path  @args  ... +                                                             ~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\gzhpe\...t\bin\scoop.p
   s1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

然后，我按照提示执行第一个代码不成功时候的另一个方案，还是报错！真的不知道怎么办了，能直接把scoop文件夹删了，再重新安装么：
                                                                              
PS C:\Users\gzhpe> cd                                                         
PS C:\Users\gzhpe> del .\scoop -Force                                         
                                                                              
确认                                                                            
C:\Users\gzhpe\scoop 处的项具有子项，并且未指定 Recurse                                    
参数。如果继续，所有子项均将随该项删除。是否确实要继续?                                                  
[Y] 是(Y)  [A] 全是(A)  [N] 否(N)  [L] 全否(L)  [S] 暂停(S)  [?] 帮助                   
(默认值为“Y”):                                                                    
del : 传递给系统调用的数据区域太小。 (异常来自 HRESULT:0x8007007A)                               
所在位置 行:1 字符: 1                                                                
+ del .\scoop -Force                                                          
+ ~~~~~~~~~~~~~~~~~~                                                          
    + CategoryInfo          : NotSpecified: (:) [Remove-Item], COMException   
    + FullyQualifiedErrorId : System.Runtime.InteropServices.COMException,Micr
   osoft.PowerShell.Commands.RemoveItemCommand

**Comment by neolee** [comment]
随便用什么手段，把 C:\Users\gzhpe\scoop 这个目录完整的删除，然后重新尝试安装。

不过你运行第二个命令出的错还真奇怪……
