### ISSUE TITLE
Web 服务教程中 python server.py 没有任何服务启动提示

### ISSUE THREAD

**Issue by flytoam** [neolee/pilot#1285]
![1](https://user-images.githubusercontent.com/34652952/79129241-7013ae00-7dd7-11ea-8ff2-51651f55cd81.png)

如图，后面带别的端口，也没有任何提示，当然localhost对应端口，也打不开。
关键是无任何出错提示，排查问题无从下手，请教老师。

**Comment by neolee** [comment]
你的源代码呢？

**Comment by flytoam** [comment]
已经找到原因了，打错了一个name，谢谢
