### ISSUE TITLE
Redis 启动失败

### ISSUE THREAD

**Issue by nioben** [neolee/pilot#1286]
![QQ浏览器截图20200416202513](https://user-images.githubusercontent.com/62788868/79456226-b3ad2880-8020-11ea-8611-ec686778ede5.png)

**Comment by neolee** [comment]
可以搜索下以往的 issue，这个问题很多人碰到并解决了。

**Comment by nioben** [comment]
嗯，把 network service 改成 local service 就 启动成功了。
