### ISSUE TITLE
学习用书的每个文件阅读模式和编辑模式切换的问题

### ISSUE THREAD

**Issue by luyahong** [neolee/pilot#1287]
李老师好。

我在使用学习用书，即打开这些*.ipynb，然后对着一段文字双击鼠标左键后，发现这些文字可以被编辑了，同时显示也变了，没有双击鼠标前那么好看了。

我现在想把这一段退回到鼠标双击前的样子，否则觉得看着很丑。但我研究了很久，找到了一个方法，就是点击File-Reload Notebook from disk。

**Comment by luyahong** [comment]
第一次发issue，不太会。刚才没说完。
我想问，有没有更简单的方法，从编辑状态切换到阅读状态呢？
谢谢！

**Comment by neolee** [comment]
在 Markdown 文本单元格里按 Shift+Enter 就可以了，就像执行一个代码单元格一样。

**Comment by luyahong** [comment]
谢谢 李老师！

**Comment by luyahong** [comment]
另外，我发现 ctrl+enter 也可以。 好神奇。

**Comment by sammy388** [comment]
control+是执行当前，shift+还新建下一行
