### ISSUE TITLE
VS Code 中 workon jupyter 的意义及运行报错

### ISSUE THREAD

**Issue by sammy388** [neolee/pilot#1288]
老师您好，
最近在践行聊天机器人案例时候，发现第二段视频后半部分31分钟，当把Jupyter Lab编辑好的程序复制到VScode运行时候，为什么会在打开powershell后，输入workon jupyter? 请问这个命令的作用是什么？为什么不直接调用保存好的Bot.py运行？
希望老师或者各位同学能帮助解答。
谢谢大家。

**Comment by neolee** [comment]
`workon` 这个命令来自工具 [virtualenvwrapper](https://virtualenvwrapper.readthedocs.io/en/latest/)，这是我用来管理 Python 虚拟环境的小工具。

以后当我们学习越来越深入，用 Python 做越来越多事情的时候，你会发现用 `pip install` 安装的第三方 Python 软件包越来越多，而且不同的项目可能想用不同的包，这时候 Python 虚拟环境就会很有帮助。

在我们的课程中，除了最后的个别高级案例，我们都不推荐使用虚拟环境，因为用不着；但如果有兴趣，自己去学习和体验一下，完全没有问题，而且对愿意学习和会学习的同学来说，这东西也不难。

**Comment by sammy388** [comment]
谢谢老师回复，后面的课关于虚拟环境已经听过了，讲的非常棒！第一次只是听课了解，现在开始一步步践行了，先跟着视频敲代码做一遍。第二天再脱离视频，按照老师讲的思路自己思考复现。然后根据出问题的地方再去深入学习。

**Comment by neolee** [comment]
赞，按照这个模式学下去应该不会有问题 👍
