### ISSUE TITLE
scoop 安装出现问题

### ISSUE THREAD

**Issue by xingzou-huang** [neolee/pilot#1289]
PS C:\Users\xingzou> Get-ExecutionPolicy
RemoteSigned
PS C:\Users\xingzou> iwr -useb get.scoop.sh | iex
iwr : 未能解析此远程名称: 'raw.githubusercontent.com'
所在位置 行:1 字符: 1
+ iwr -useb get.scoop.sh | iex
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest]，WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

**Comment by xingzou-huang** [comment]
是网络的问题吗？之前的电脑用这个网络安装成功了。

**Comment by neolee** [comment]
可能网络不稳定，可以换个时间、多试几次看看。

**Comment by Thomas160116** [comment]
@neolee 李老师，我这边也出现同样的问题，换了网络试过好多遍，还是不行。有没有人提供远程控制的付费服务？折腾了两天还没配置好。

**Comment by lihuaiyu123** [comment]
你好 你的问题解决 了吗？也遇到了相同的情况。

**Comment by xingzou-huang** [comment]
过了一段时间又去安装，就可以了。可能网络不稳定。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"怀玉Mr"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月1日(星期一) 中午11:17
收件人:&nbsp;"neolee/pilot"<pilot@noreply.github.com&gt;;
抄送:&nbsp;"行走"<1609306852@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [neolee/pilot] scoop 安装出现问题 (#1289)





 
你好 你的问题解决 了吗？也遇到了相同的情况。
