### ISSUE TITLE
pandas 中的 loc 如何寻找某行中信息？

### ISSUE THREAD

**Issue by sammy388** [neolee/pilot#1290]
李老师您好，在实践自动化案例时候出现一个疑问，老师用pandas中的loc反向找到了“总计”行，当时写的代码是**df[1]==‘总计’**，老师说df[1]是numpy的数组，表示取第一列，为什么是第一列，如果想用loc的方法在某行中选怎么实现？问题可能比较小白，但是试了[:,1]或者一些其他方式，都没能解决，除非把数据转置，但是觉得肯定有简单的方法。
另外，我在搜索的时候看到有些数据库行号是数字，列号是字母，不知道这种是否也可以从xls文件读过来直接实现和在excel文件中相同的行列号。
希望老师百忙中能解答下。谢谢

**Comment by neolee** [comment]
要想系统地掌握 pandas 里定位和选择数据的方法，下面的官方文档是最好的资料：

https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html

你也可以用 pandas loc iloc 做关键字去搜索引擎做查找，有很多深入浅出的中、英文资料；注意有些可能过时或者不一定准确，但更简单清晰，也可以参考。有疑问就去上面的官方文档里查实。

**Comment by sammy388** [comment]
首先感谢李老师提示，之前虽然搜索了很久但是也没解决其实是搜索错方向了，看了官方的介绍，发现问题方向错了。参考官方例子，又搜索了一些终于知道原因了，现总结如下：
1. loc[df[1]]是相当于loc[['False','False','True']]，是用 loc的检索布尔列表。会把true对应的结果保存下来。因此，[df[1]=='总计']是输出了一个前11个false，第12个true的列表返还给loc。
2. 老师举例中的df[1]其中是输出列表第一个位置存储的结果，因此df[:,1]是无法输出我开始想的列信息的，如果按照array看待列表中的内容，需要用[x[1} for x in df] 来获得列信息。
3. 另外，关于倒入进来的数据标题的问题也提一下，应该是转进来都是数字作为标签的，但是也可以为了方便，自己用Index和Columns填加行列不同的标题。
再次感谢老师的耐心指点，归根结底还是概念混淆，下次好好看官方文档，也希望这个小白问题。能帮助到有同样疑问的小朋友们。
