### ISSUE TITLE
数据抓取异常

### ISSUE THREAD

**Issue by nioben** [neolee/pilot#1291]
![QQ浏览器截图20200425220227](https://user-images.githubusercontent.com/62788868/80281863-bdc9d800-8740-11ea-81ca-0eaa7d97f2f7.png)
![QQ浏览器截图20200425220236](https://user-images.githubusercontent.com/62788868/80281873-cb7f5d80-8740-11ea-8aeb-8e859ddbc9f1.png)

主机回应失败，是网络问题吗？老师

**Comment by neolee** [comment]
是网络问题，Wikipedia 需要科学上网才能访问。如果有困难，自己找一个别的网页来玩也不错。

**Comment by nioben** [comment]
我科学上网了，在谷歌浏览器安装了VPN插件，可以连上谷歌，它这个在命令行获取主机回应是通过浏览器进行吗？还是要在别的地方设置..，
![微信图片_20200426135051](https://user-images.githubusercontent.com/62788868/80299189-fe6b3500-87c4-11ea-91af-24c7d0ce95c5.png)
