### ISSUE TITLE
本地放到 github 失败

### ISSUE THREAD

**Issue by xingzou-huang** [neolee/pilot#1292]
PS C:\Users\Administrator\Code\learn-markdown> git add .
PS C:\Users\Administrator\Code\learn-markdown> git commit -a -m"init commit"
[master (root-commit) d75c031] init commit
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 README.MD

PS C:\Users\Administrator\Code\learn-markdown> git remote add origin https://github.com/xingzou-huang/learn-markdown.git

PS C:\Users\Administrator\Code\learn-markdown> git push -u origin master
fatal: unable to access 'https://github.com/xingzou-huang/learn-markdown.git/': Failed to connect to github.com port 443: Timed out

**Comment by neolee** [comment]
网络问题，你是不是使用了网络代理？

试试 `git config --global http.proxy` 看看返回是什么，如果有设置代理，可以用下面的命令取消：

`git config --global --unset http.proxy`

然后再试试 push。

**Comment by xingzou-huang** [comment]
PS C:\Users\Administrator\Code\learn-markdown> git config --global http.proxy

PS C:\Users\Administrator\Code\learn-markdown> git config --global --unset http.proxy

PS C:\Users\Administrator\Code\learn-markdown>  git remote add origin https://github.com/xingzou-huang/learn-markdown.git
fatal: remote origin already exists.

PS C:\Users\Administrator\Code\learn-markdown>  git push -u origin master
fatal: unable to access 'https://github.com/xingzou-huang/learn-markdown.git/': SSL certificate problem: unable to get local issuer certificate

用的不是代理网络。还是试了一下上面的操作，传不上去。

**Comment by neolee** [comment]
你这个问题很可能是是的 Windows 里缺失了一些重要的数字证书，导致无法确认 GitHub 的站点的可信性导致的。

可以暂时禁止 git 的证书检查试试，

```shell
git config --global http.sslVerify false
```

但比较不推荐这么做，因为会导致你的 git 变得更不安全。最好还是搞清楚系统为什么会缺少证书，GitHub 使用的是 DigiCert 根认证机构签发的证书，一般系统里是肯定有的：

<img width="470" alt="GitHub Cert" src="https://user-images.githubusercontent.com/24796/80942880-7ca88680-8e18-11ea-822a-20843edb3ce8.png">
