### ISSUE TITLE
如何卸载 jupyter lab  

### ISSUE THREAD

**Issue by LFN3399** [neolee/pilot#1293]
老师 因为我安装的jupyter 没有工具栏，想卸载重新安装，用什么命令卸载呢？我在网上找了些方法卸载，但是还是能打开 jupyter lab

**Comment by neolee** [comment]
参考这个问题里建议的几个方法：


https://stackoverflow.com/questions/33052232/how-to-uninstall-jupyter

**Comment by LFN3399** [comment]
用了里面的一些方法，成功卸载了jupyter ，再重装的时候打开jupyter 原来的练习内容还在，我想把前面练习的内容清空再练习，有什么方法清空吗？

**Comment by neolee** [comment]
可以回复你的学习用书到初始状态（重新 fork & clone），也可以手动选中单元格清除。
