### ISSUE TITLE
for loop 与 while loop 输出值为什么不同

### ISSUE THREAD

**Issue by Royhowtohack** [neolee/pilot#1295]
var x = 2;
while (x  < 10000){
x = x * 2;
console.log(x);
}

for (var x = 2; x < 10000; x = x * 2) {
  console.log(x);
}

第一个的输出值多了一个16384。这是为什么呢？第一眼看，他们两的输出值一样，运行之后发现不一样。 我尝试while (x *2  < 10000) 输出值就和第二个一样。

求大神解答。

**Comment by neolee** [comment]
你这个是 JavaScript 吧？

C、Java、JavaScript 等语言支持类似于 `for (var x = 2; x < 10000; x = x * 2)` 这样的 for 循环写法，这个写法其实是可以改写为 `while` 循环的，所以 Python 中就没支持这种语法，转而将 `for` 循环专用于是迭代器。那么上述 `for` 循环可以怎么改成 `while` 呢？

```javascript
for (var x = 2; x < 10000; x = x * 2) {
    console.log(x);
}
```

上面的代码等价于：

```javascript
var = 2
while (x < 10000) {
    console.log(x);
    x = x * 2
}
```

对比一下你写的 `while` 循环，能发现差别了吧？

**Comment by Royhowtohack** [comment]
多谢李老师，原来是因为顺序错了。学完Python之后我顺便开始学JavaScript，我记得您说过早晚要学的。我现在是用Chrome的console来练习代码，也用code.org 的App lab。我试了您的代码发现Chrome的 console最后一排会多一个数字16384。 前面有一个 <· 符号。我Google了半天没找到 <· 是什么意思。    用code.org 并没有出现这个数字。

**Comment by Royhowtohack** [comment]
多谢李老师，原来是因为顺序错了。学完Python之后我顺便开始学JavaScript，我记得您说过早晚要学的。我现在是用Chrome的console来练习代码，也用code.org 的App lab。我试了您的代码发现Chrome的 console最后一排会多一个数字16384。 前面有一个 <· 符号。我Google了半天没找到 <· 是什么意思。    用code.org 并没有出现这个数字。

**Comment by Royhowtohack** [comment]
我用别的代码试了试，我猜 <·  这个符号是返回值的意思吧？ 为什么会返回16384呢。

**Comment by neolee** [comment]
你的猜测是对的，DevTools 的 console 里最后那一行显示的是你运行的整段脚本的“值”，如果整段脚本是个函数，这里就是返回值，如果整段脚本不是函数，那就是这段脚本最后计算出的那个值。

顺便，你要学习 JS 的话，建议装个 nodejs，用它来跑你的程序，顺便也把 nodejs 的基础也学了。

**Comment by Royhowtohack** [comment]
太感谢了。🙏

**Comment by Royhowtohack** [comment]
太感谢了。🙏
