### ISSUE TITLE
Github 图片加载不出来

### ISSUE THREAD

**Issue by MoofersLAon** [neolee/pilot#1296]
李俊老师你好，首先，这个问题是我 Google 了之后，依然没有解决，所以才求助于你（我所用到的解决方法是，修改电脑的 hosts 文件）这是我用到的教程链接：https://blog.csdn.net/u010234516/article/details/52963954

![b5205dc48ec4e967036672d761e04d7](https://user-images.githubusercontent.com/49604516/80795499-41ffdd80-8bcf-11ea-8ea0-9296fe2d7bcc.png)

![fc9a6fbdeea61ad34a59713dfeb0ccb](https://user-images.githubusercontent.com/49604516/80795610-855a4c00-8bcf-11ea-92b2-b9c44f953823.png)

**Comment by neolee** [comment]
GitHub 图片加载不出来，通常是因为放图片的云服务无法访问。一般需要网络代理。
