### ISSUE TITLE
利用 requests 抓取数据时遇到数据抓不全的问题

### ISSUE THREAD

**Issue by wangBoZhengJuan** [neolee/pilot#1297]
![微信图片_20200502210350](https://user-images.githubusercontent.com/49601464/80864956-b2cef480-8cb8-11ea-9580-4479ed31f253.png)

**Comment by neolee** [comment]
抓回来是全的，但这是一个用了 iframe 的页面真正的内容在 iframe 标签里嵌套的 HTML 文档里。

**Comment by wangBoZhengJuan** [comment]
> 抓回来是全的，但这是一个用了 iframe 的页面真正的内容在 iframe 标签里嵌套的 HTML 文档里。

明白了。谢谢老师，太感谢您了。这个问题困扰了我很长时间。谢谢您

**Comment by neolee** [comment]
慢慢学习一点 HTML 的各种标签吧，怎么都有用的 😀

**Comment by wangBoZhengJuan** [comment]
嗯嗯...您的编程课，不管是音频还是视频抑或是教材和学习用书，这些不同形式的学习素材，我一个都不想“放过”。哈哈哈...因为里面的每一句话都能给我启发，引发我思考，您说的每一句话都是知识。特别是每一节课程之前的背景知识介绍和一步步引导我们理解问题，分析分解问题的环节。您讲课的严谨态度以及您的细心让我敬仰！
您能体察到编程小白的心态。哈哈哈哈哈...
您引导我们尝试去寻找初步的解决方案，然后在不知不觉中找到成熟解决方案。这个过程真的很珍贵！这个探索式的学习过程让我对学习这件事有了不同以往的认知：从知道的那一点点着手，一边试探一边摸索一边思考，不断地总结提炼，不怕犯错，也许错误能生出新的解决办法，就这样，无知无畏地向前，慢慢地靠近优秀的解决方案。到最后，我不仅知其然，我还知其所以然。这就是我从您那里学到的learning to learn.
说真的李老师，我对您很着迷。在其他地方买的编程课，那些老师活生生地能把编程课上成语文课。正所谓，没有对比就没有伤害，我能做到反反复复听您的课，却做不到听完那些老师的哪怕一节课。
没控制住，说多了。哈哈...
另外，李老师，我每天投入到编程课的学习时间是6个小时，目前把咱们两阶段的编程课重复学习了3遍。也完成了您布置的课程练习。在这之前独立啃完了python的官方文档和笑来老师的《自学是门手艺》。疫情使我失了业，所以接下来，我想找一份编程相关的工作。当然，写程序也是我喜欢干和乐意干的事，更是我的梦想。
老师，就我现在的水平，什么样的岗位适合我？渴望得到您的指引。我是个女孩，互联网公司是不是一般都只招男孩啊？心里很没谱。哈哈哈哈哈...
最后，再啰嗦一下。这是我第一次向您提问。您回答了我，好感动！以前遇到的编程老师经常说：“不要做伸手党，遇到问题自己解决”。当遇到问题问老师，老师一般不回复。所以我遇到问题就自己在网上找解决方案。不敢问。哈哈...

**Comment by wangBoZhengJuan** [comment]
> 慢慢学习一点 HTML 的各种标签吧，怎么都有用的 😀

嗯嗯...您的编程课，不管是音频还是视频抑或是教材和学习用书，这些不同形式的学习素材，我一个都不想“放过”。哈哈哈...因为里面的每一句话都能给我启发，引发我思考，您说的每一句话都是知识。特别是每一节课程之前的背景知识介绍和一步步引导我们理解问题，分析分解问题的环节。您讲课的严谨态度以及您的细心让我敬仰！
您能体察到编程小白的心态。哈哈哈哈哈...
您引导我们尝试去寻找初步的解决方案，然后在不知不觉中找到成熟解决方案。这个过程真的很珍贵！这个探索式的学习过程让我对学习这件事有了不同以往的认知：从知道的那一点点着手，一边试探一边摸索一边思考，不断地总结提炼，不怕犯错，也许错误能生出新的解决办法，就这样，无知无畏地向前，慢慢地靠近优秀的解决方案。到最后，我不仅知其然，我还知其所以然。这就是我从您那里学到的learning to learn.
说真的李老师，我对您很着迷。在其他地方买的编程课，那些老师活生生地能把编程课上成语文课。正所谓，没有对比就没有伤害，我能做到反反复复听您的课，却做不到听完那些老师的哪怕一节课。
没控制住，说多了。哈哈...
另外，李老师，我每天投入到编程课的学习时间是6个小时，目前把咱们两阶段的编程课重复学习了3遍。也完成了您布置的课程练习。在这之前独立啃完了python的官方文档和笑来老师的《自学是门手艺》。疫情使我失了业，所以接下来，我想找一份编程相关的工作。当然，写程序也是我喜欢干和乐意干的事，更是我的梦想。
老师，就我现在的水平，什么样的岗位适合我？渴望得到您的指引。我是个女孩，互联网公司是不是一般都只招男孩啊？心里很没谱。哈哈哈哈哈...
最后，再啰嗦一下。这是我第一次向您提问。您回答了我，好感动！以前遇到的编程老师经常说：“不要做伸手党，遇到问题自己解决”。当遇到问题问老师，老师一般不回复。所以我遇到问题就自己在网上找解决方案。不敢问。哈哈...

**Comment by neolee** [comment]
我只帮助新人，等你们的新手光环没有了，确实自己去找更好 😄

**Comment by wangBoZhengJuan** [comment]
> 我只帮助新人，等你们的新手光环没有了，确实自己去找更好 😄

老师，我想知道什么样的岗位适合现在水平的我？您指引我一下吧。😀

**Comment by wangBoZhengJuan** [comment]
> > 我只帮助新人，等你们的新手光环没有了，确实自己去找更好 😄
> 
> 老师，我想知道什么样的岗位适合现在水平的我？您指引我一下吧。😀

老师，我找到了解决方案。
1. 找到内嵌网页链接(按f12进入chrome开发者工具，选择network，点击Doc，浏览response会发现所需表格，打开headers，里面有Cookie，Host，User_Agent...)
2. 找到Cookie
3. 给get方法添加headers参数
成功获取表格数据。🙂

**Comment by wangBoZhengJuan** [comment]
> > > 我只帮助新人，等你们的新手光环没有了，确实自己去找更好 😄
> > 
> > 
> > 老师，我想知道什么样的岗位适合现在水平的我？您指引我一下吧。😀
> 
> 老师，我找到了解决方案。
> 
> 1. 找到内嵌网页链接(按f12进入chrome开发者工具，选择network，点击Doc，浏览response会发现所需表格，打开headers，里面有Cookie，Host，User_Agent...)
> 2. 找到Cookie
> 3. 给get方法添加headers参数
>    成功获取表格数据。🙂

![微信图片_20200505173638](https://user-images.githubusercontent.com/49601464/81053094-252d1800-8ef7-11ea-86b7-45594e37ae4d.png)
