### ISSUE TITLE
scoop 安装不了怎么办

### ISSUE THREAD

**Issue by zenglong031005** [neolee/pilot#1298]
老师能把解决的方法发在我的邮箱里面？我的邮箱ynzenglong@163.com       谢谢老师

**Comment by neolee** [comment]
为啥安装不了，出什么错？

**Comment by Ivyzhangjr** [comment]
我也碰到过这个情况，应该是网络问题，把scoop安装那个网址贴到浏览器里，那个能打开的话，再用课程里的方法来安就没问题了。

**Comment by angleo0217** [comment]
> 我也碰到过这个情况，应该是网络问题，把scoop安装那个网址贴到浏览器里，那个能打开的话，再用课程里的方法来安就没问题了。

scoop安装网址是什么

**Comment by Ivyzhangjr** [comment]
> > 我也碰到过这个情况，应该是网络问题，把scoop安装那个网址贴到浏览器里，那个能打开的话，再用课程里的方法来安就没问题了。
> 
> scoop安装网址是什么

get.scoop.sh

**Comment by Leebo1206677273** [comment]
安装不了，求解答

**Comment by neolee** [comment]
@Leebo1206677273 你在好几个别人的、已经完成的 issue 下提自己的问题，这样很不好。你可以参考别人的问题自己尝试，如果还解决不了就自己提 issue。真要在别人的（相关问题）下提也不需要提那么多次，而且就一句“我安装不了”让人怎么帮你？
