### ISSUE TITLE
scoop 无法安装是否会直接影响后续 Python 安装以及后续学习？

### ISSUE THREAD

**Issue by yabinyang0904** [neolee/pilot#1299]

**Comment by yabinyang0904** [comment]
![NJ 3D Z$MPB5(A5WV9YKYL](https://user-images.githubusercontent.com/64726827/80911613-ec136d00-8d69-11ea-8f6e-4c7fb6063c5c.png)

**Comment by neolee** [comment]
网络问题。

**Comment by yabinyang0904** [comment]
>

> 网络问题。

求解，我已经不同时间段都进行了尝试。不知道该怎么办了？“网络问题”究竟是何种问题？等老师回复，谢谢。

**Comment by neolee** [comment]
网络问题的意思是，就是：你需要在你的电脑上安装配置一些软件（比如 Python、git），但是你所在的网络环境无法顺利连接到提供这些软件的服务器（通常在国外）。

这种问题可能很严重，就是怎么都无法访问，也有可能是间断性的不稳定（这种情况下多尝试可能可以过去）。如果是前者，那只有使用网络代理（这个需要你自己解决），或者从别的地方下载你需要的软件（比如不使用 Scoop，直接用别的办法下载和安装好 Python）。

这个 Issues 系统里有不少相关问题，你可以试着搜索下，看看有没有和你类似的情况。

**Comment by yabinyang0904** [comment]
已经翻出去了，顺利完成环境配置。谢谢李老师的耐心。------------------ 原始邮件 ------------------
发件人: "Neo Lee"<notifications@github.com>
发送时间: 2020年5月4日(星期一) 下午2:52
收件人: "neolee/pilot"<pilot@noreply.github.com>;
抄送: "yabinyang0904"<1250881774@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [neolee/pilot] scoop 无法安装是否会直接影响后续 Python 安装以及后续学习？ (#1299)




 
网络问题的意思是，就是：你需要在你的电脑上安装配置一些软&#x4EF6;（比如 Python、git），但是你所在的网络环境无法顺利连接到提供这些软&#x4EF6;的&#x670D;务器（通常在国外）。
 
这种问题可能很严重，就是怎么都无法访问，也有可能是间断性的不稳定（这种情况下多尝试可能可以过去）。如果是前者，那只有使用网络代理（这个需要你自己解决），或者从别的地方下载你需要的软&#x4EF6;（比如不使用 Scoop，直接用别的办法下载和安装好 Python）。
 
这个 Issues 系统里有不少相关问题，你可以试着搜索下，看看有没有和你类似的情况。
 
&mdash;

**Comment by angleo0217** [comment]
> 已经翻出去了，顺利完成环境配置。谢谢李老师的耐心。------------------ 原始邮件 ------------------ 发件人: "Neo Lee"<notifications@github.com> 发送时间: 2020年5月4日(星期一) 下午2:52 收件人: "neolee/pilot"<pilot@noreply.github.com>; 抄送: "yabinyang0904"<1250881774@qq.com>;"Author"<author@noreply.github.com>; 主题: Re: [neolee/pilot] scoop 无法安装是否会直接影响后续 Python 安装以及后续学习？ (#1299) 网络问题的意思是，就是：你需要在你的电脑上安装配置一些软&#x4EF6;（比如 Python、git），但是你所在的网络环境无法顺利连接到提供这些软&#x4EF6;的&#x670D;务器（通常在国外）。 这种问题可能很严重，就是怎么都无法访问，也有可能是间断性的不稳定（这种情况下多尝试可能可以过去）。如果是前者，那只有使用网络代理（这个需要你自己解决），或者从别的地方下载你需要的软&#x4EF6;（比如不使用 Scoop，直接用别的办法下载和安装好 Python）。 这个 Issues 系统里有不少相关问题，你可以试着搜索下，看看有没有和你类似的情况。 &mdash; You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

请教如何解决

**Comment by yabinyang0904** [comment]
想办法连上外网，连接和安装相关程序都会比较顺利

**Comment by angleo0217** [comment]
> 想办法连上外网，连接和安装相关程序都会比较顺利

搭梯子吗？

**Comment by angleo0217** [comment]
> 想办法连上外网，连接和安装相关程序都会比较顺利

比如说什么办法，能具体讲讲吗

**Comment by yabinyang0904** [comment]
> > 想办法连上外网，连接和安装相关程序都会比较顺利
> 
> 比如说什么办法，能具体讲讲吗

https://www.zhixin66.com/aff.php?aff=5965
可以试一下这个链接哈，当然它是收费的哈。

**Comment by neolee** [comment]
> > 想办法连上外网，连接和安装相关程序都会比较顺利
> 
> 
> 
> 比如说什么办法，能具体讲讲吗

我们不在这里讨论这类问题。

**Comment by yabinyang0904** [comment]
> > 想办法连上外网，连接和安装相关程序都会比较顺利
> 
> 比如说什么办法，能具体讲讲吗

可以加我微信  yb09040901    我们单独交流哈。
