### ISSUE TITLE
git commit问题

### ISSUE THREAD

**Issue by yayuehuizi** [neolee/pilot#13]
根据git基本操作流程，我进入创建readme.md文件时，在git commit阶段，命令行界面出现“终止提交因为提交说明为空”的说明，我进入编辑器输入版本描述信息保存后，命令行还是没有变化，求大神指导

**Comment by yayuehuizi** [comment]
xman-2:learn-git xman$ git status
位于分支 master

尚无提交

未跟踪的文件:
  （使用 "git add <文件>..." 以包含要提交的内容）
	README.md

提交为空，但是存在尚未跟踪的文件（使用 "git add" 建立跟踪）
xman-2:learn-git xman$ git add README.md
xman-2:learn-git xman$ git status
位于分支 master

尚无提交

要提交的变更：
  （使用 "git rm --cached <文件>..." 以取消暂存）
	新文件：   README.md

xman-2:learn-git xman$ git commit
终止提交因为提交说明为空。

**Comment by neolee** [comment]
关于 git 使用，以后我会录个视频。既然你已经开始自己探索那更好。

关于你的问题，你在运行 git commit 时，应该会弹出你的缺省编辑器，让你编辑提交说明，如果没有那是未指定这个编辑器。

你安装 Visual Studio Code 了吗？你的系统是 macOS 对吧？

**Comment by yayuehuizi** [comment]
对的，我的是macos

**Comment by yayuehuizi** [comment]
安装了visual studio code，就是自动弹出这个编辑器的

**Comment by neolee** [comment]
1. 按照 [环境配置指南](https://github.com/neolee/pilot/blob/master/x1-setup.md) 中的指引安装好 Visual Studio Code，并在其中配置好 code 这个命令；
2. 按照 [Git 教程](https://nbviewer.jupyter.org/github/neolee/pilot/blob/master/x3-git-github.ipynb) 里的说明，配置好 git 缺省编辑器为 code：`git config --global core.editor code`

然后运行 `git commit` 时会弹出 Visual Studio Code，你要在里面最开始的地方输入提交说明文字，否则无法提交。在教程中有如此的说明。

**Comment by yayuehuizi** [comment]
我是安装教程一步步走的，就是自动打开编辑器后， 我在最开始的地方输入一些文字，然后关闭保存后，命令行里面还是没有变化，查看也没有东西，再次git commit还是重复刚才的提示

**Comment by neolee** [comment]
你输入提交信息之后先保存，然后关闭编辑窗口，之后发生了什么？

**Comment by neolee** [comment]
试试这样，运行 `git commit`，打开了 Visual Studio Code 窗口，你截个图，同时可以看到 VS 窗口和命令行窗口，发到这里给我看下。

**Comment by yayuehuizi** [comment]
我是关闭时它提示我保存，然后我保存。后面页面关闭没发生什么

**Comment by yayuehuizi** [comment]
图片怎么发送不了，显示错误

**Comment by neolee** [comment]
显示什么错误？截图用密信发给我（或者手机拍照拍清楚一点发给我）。

**Comment by neolee** [comment]
确认了是我的疏忽，抱歉。

配置 git 缺省编辑器的命令应该是：

`git config --global core.editor "code -w"`

你运行这个命令一次，然后再 `git commit` 就不会有问题了。

解释：`code -w` 命令是打开 Visual Studio Code 并等待其关闭的意思，如果没有 `-w` 参数，在 macOS 下 `git commit` 命令会立刻返回，不等 code 编辑完。在 Windows 下表现不一样，无论有没有 `-w` 参数，`git` 都会等 code 编辑完，我当时只在 Windows 下作了测试，所以没发现这个问题。

教程已经作了修正，非常感谢你的反馈。

**Comment by yayuehuizi** [comment]
成功了，感谢耐心指导

**Comment by neolee** [comment]
应该的。
