### ISSUE TITLE
查星星的类里表名和列名用下划线连接？

### ISSUE THREAD

**Issue by wangBoZhengJuan** [neolee/pilot#1300]
想不明白为什么查星星的类里会有这样的写法：`self.cons_name`,`self.cons_name_cn`
cons是表名，name和name_cn是列名
这个问题不知道怎么搜索了，所以想请教老师您解答一下。😄

**Comment by neolee** [comment]
不明白你的问题，self.xxxx 只是我给这个类的对象属性起的名字，具体值是调用 SQLite 的库从数据库查询得到的呀！

**Comment by wangBoZhengJuan** [comment]
> 不明白你的问题，self.xxxx 只是我给这个类的对象属性起的名字，具体值是调用 SQLite 的库从数据库查询得到的呀！

老师，是不是SQL语句里的变量语法书写有问题？
您看：
![微信图片_20200511151725](https://user-images.githubusercontent.com/49601464/81534537-c7874880-939a-11ea-9111-0bbded4e9b81.png)

**Comment by neolee** [comment]
这个肯定是代码里有语法错误，把你的源代码贴出来看看。

**Comment by neolee** [comment]
你的代码中 `sql = ...` 那一行没完整显示出来（其实要在这里展示代码最好是 copy 过来，然后用 Markdown 的代码显示标签来展示），但我猜问题在于你没有在引号前加上 `f`，正确的代码是这样的：

```python
sql = f'...'
```

**Comment by wangBoZhengJuan** [comment]
> 你的代码中 `sql = ...` 那一行没完整显示出来（其实要在这里展示代码最好是 copy 过来，然后用 Markdown 的代码显示标签来展示），但我猜问题在于你没有在引号前加上 `f`，正确的代码是这样的：
> 
> ```python
> sql = f'...'
> ```

```python
sql = f"SELECT bs.name_en, bs.name_cn, bs.magnitude, mer.cons, mer.name_cn FROM bs LEFT JOIN mer ON bs.cons = mer.iau WHERE bs.{colname} LIKE ? ORDER BY bs.top20 DESC, bs.commonly DESC, bs.magnitude"
```
加上f之后，
![微信图片_20200512152534](https://user-images.githubusercontent.com/49601464/81650949-ec47f280-9464-11ea-86c3-820a3210b270.png)
老师，这次好像是数据库有问题，数据库打开是乱码，但是合并后的csv文件和亮星csv文件都是没问题的。
我打开SQL，更改编码方式，但没用

**Comment by neolee** [comment]
看不到截图。

**Comment by wangBoZhengJuan** [comment]
> 这个错误信息说你的 SQLite 数据文件格式不对，你的数据文件哪里来的？是按照 case study 里那样抓取网页自己生成的么？

老师，因为我进不了Wikipedia，所以我的亮星数据和星座数据都来自香港天文馆网站，因为香港天文馆的星座信息里没有英文简写，所以我又抓了一个国外网站的星座数据，然后合并了起来。
不过，刚给您提交完issue，我的问题就解决了。目前我已经完整地依葫芦画瓢地完成了案例学习。其中遇到了很多很多做梦都想不到的问题，幸好自己死磕，都磕磕绊绊地解决了。当然最感恩的就是您了。您犹如灯塔，给我方向。🙂

**Comment by wangBoZhengJuan** [comment]
![微信图片_20200514164809](https://user-images.githubusercontent.com/49601464/81913673-de2fd880-9602-11ea-9ad1-5083e837befc.png)
![微信图片_20200513214734_wps图片](https://user-images.githubusercontent.com/49601464/81913735-f273d580-9602-11ea-8621-e1871bf11bc9.png)
