### ISSUE TITLE
不知道这个为什么搞不定

### ISSUE THREAD

**Issue by Liyongjun0209** [neolee/pilot#1301]
![微信图片_20200508000927](https://user-images.githubusercontent.com/56832905/81311317-37a67d80-90c0-11ea-9b1b-34faef28d6e4.jpg)

**Comment by neolee** [comment]
你 `mkdir Code` 建立文件夹成功了，`cd Code` 进入这个文件夹也没问题，出问题的是 `code .` 这个命令，注意 `code` 和 `.` 中间有个空格，这个命令的意思是启动 Visual Studio Code 并打开当前工作目录（`.` 代表命令行当前所在的目录）。这个命令执行失败是因为系统不认识 `code` 这个命令。

一般来说 Windows 10 下，只要你正确安装了最新版本的 Visual Studio Code（用 installer 也就是安装程序的方式安装），系统会自动帮你配置好 `code` 这个命令，让它指向你安装的 Visual Studio Code 程序，所以你需要确认：

- 装好 Visual Studio Code 了吗？从开始菜单能正常运行它吗？
- 系统是否完成了 `code` 这个命令配置？可以在命令行里执行 `$env:Path` 来查看系统的执行目录设置，里面应该有你安装 Visual Studio Code 的目录。 
- 装好 Visual Studio Code 之后，有的时候可能需要重启一下 Windows 才能让 `code` 这个命令生效。
