### ISSUE TITLE
迭代器章节中 i = iter(squares())报错

### ISSUE THREAD

**Issue by imSeaton** [neolee/pilot#1302]
![iterator](https://user-images.githubusercontent.com/56856685/81389337-3f136880-914c-11ea-8718-836d4d553902.png)
我是windows系统，在迭代器学习过程中，我发现执行“i=iter(squares())”语句时会出现‘squares’ object is not callable的错误，但是在执行"i = squares()"是可以正常运行的，也可以进一步执行"next(i)"语句。
不知该问题是由于系统的原因，还是我编写代码时没理解到位，还请老师解答。

**Comment by neolee** [comment]
前一个格子的执行序号是 9，后一个格子是 11，中间你还执行了什么？

从报的错看很可能你定义了别的东西然后取名叫 squares 了，在 Python 中如果 `squares` 是一个类或者是一个函数的话，才可以在后面加上 `()` 来完成一些事情（创建实例对象或者调用函数），这叫“callable”，如果你的 squares 不是类也不是函数，就没法这么做，也就是报的错。

**Comment by imSeaton** [comment]
谢谢老师，解决了
