### ISSUE TITLE
两个 pip 都找不到

### ISSUE THREAD

**Issue by Liyongjun0209** [neolee/pilot#1303]
![微信图片_20200508182730](https://user-images.githubusercontent.com/56832905/81392475-b3a0d400-9159-11ea-8ff5-786697152395.jpg)

**Comment by neolee** [comment]
仔细看指南，那两行命令别串在一起啊，先执行：

```
python -m pip install -U pip
```

然后执行：

```
pip install jupyterlab
```

从一开始我就一直强调，要搞清楚你对计算机说了啥，计算机又回答你了什么，不能搞不清楚就扔给计算机呀！
