### ISSUE TITLE
使用 sort 方法两次输出结果不同

### ISSUE THREAD

**Issue by PanChuang2019** [neolee/pilot#1308]
![1](https://user-images.githubusercontent.com/48653618/81569175-83fc0100-93d1-11ea-9746-99b8b65dd824.png)
![2](https://user-images.githubusercontent.com/48653618/81569182-865e5b00-93d1-11ea-8b6a-93da01a8c50f.png)
老师，为什么输入print（car.sort()）,结果是none？

**Comment by neolee** [comment]
想想 `print(car.sort())` 打印的是什么？是不是 `car.sort()` 的返回值？这个返回值是什么？

如果还不明白可以复习下第六讲。
