### ISSUE TITLE
friend_food 和 my_food 关系如何定义？

### ISSUE THREAD

**Issue by PanChuang2019** [neolee/pilot#1309]
![image](https://user-images.githubusercontent.com/48653618/81577379-ec4fe000-93db-11ea-964a-6410e78bf257.png)

从右往左，my_food 赋值给friend_food,请问为什么friend_food 变化之后，my_food 也会跟着变呢，不应该是friend_food随着my_food变化而变化吗？

**Comment by neolee** [comment]
两个变量指向的是同一个列表对象，该对象发生改变的话两个变量都会跟着变。

可以复习下第九课《列表》，尤其是最后讲作用域的部分。
