### ISSUE TITLE
为什么 ConEmu 运行 hello.py 的结果为空？

### ISSUE THREAD

**Issue by bright-xuexi** [neolee/pilot#131]
前面安装都已经OK，用VSCode创建hello.py文件和保存也OK。
在ConEmu 窗口，然后：
输入 ls ↩︎，应该可以看到刚才新建的文件 hello.py
输入 python hello.py ↩︎ 运行 hello.py 程序的结果为空，不知道为什么，请帮忙解答。
![print hello](https://user-images.githubusercontent.com/36670984/67629898-d4d65d00-f8b8-11e9-8a58-fbc8e6020762.jpg)
![python hello](https://user-images.githubusercontent.com/36670984/67629899-d9027a80-f8b8-11e9-9f87-a1637d5a5d4f.jpg)

**Comment by neolee** [comment]
你执行 which python 和 python -V 看看结果是啥。

**Comment by bright-xuexi** [comment]
你执行 which python 和 python -V 结果如下：
![which python](https://user-images.githubusercontent.com/36670984/67630884-4918fc80-f8c9-11e9-8e20-79e5ed36c340.jpg)

**Comment by bright-xuexi** [comment]
运行 hello.py 结果为空，是因为之前运行 python -V 结果为空，没有解决就继续下面的步骤导致的。
发现原因：在cmd下执行 python -V 会报错，如下图。
解决方案：Windows系统中 api-ms-win-crt-process-l1-1-0.dll 文件丢失，安装此文件之后就OK啦。
![Get-Command python 1](https://user-images.githubusercontent.com/36670984/67634187-85615280-f8f3-11e9-9b42-c03866334ece.jpg)
