### ISSUE TITLE
mac os 安装 mysql 的问题

### ISSUE THREAD

**Issue by Ceasar1978** [neolee/pilot#1311]
教程中的官网链接只有Windows系统的，没找到 mac 系统的安装文件。
后来改用命令行安装的方法，输入 brew install mysql@5.7 后，一直卡在 Updating Homebrew... 这个界面，大概至少有十几二十分钟了。请问老师是 Homebrew 程序需要更新吗？更新时间需要这么长吗？
@neolee

**Comment by neolee** [comment]
Homebrew 需要保持本地的信息是最新的才能正确处理安装程序，所以你安装一个软件包之前它会自动先进行一些必要的对自己的更新，一般是很快的，你这个情况基本是网络不太顺，可以换个时间试试，或者是是网络代理。

**Comment by Ceasar1978** [comment]
好的，谢谢老师！

**Comment by Ceasar1978** [comment]
经过科学上网解决了此问题。
