### ISSUE TITLE
输入 mysql -uroot -p 命令后，键盘无响应的问题

### ISSUE THREAD

**Issue by Ceasar1978** [neolee/pilot#1312]
输入 mysql -uroot -p 命令后，提示输入密码，但这时候键盘失效，无论按什么键都没反应。请问老师这是什么问题？
@neolee

**Comment by Ceasar1978** [comment]
但是之前设置的密码是 1，输入回车后没用，还是提示密码错误。

**Comment by Ceasar1978** [comment]
@neolee 能否请老师告知如何取消或充值密码。网上搜了很久，都没有找到可行的方法，通常都是命令输入进去后，显示 No such file or directory，可能是安装路径不对。因为密码的问题，导致无法进行下一步的学习。

**Comment by neolee** [comment]
去网上搜索重制 mysql 密码的方法，然后（你是 macOS 下用 Homebrew 装的 mysql 对吧？）你需要的命令都在 `/usr/local/opt/mysql@5.7/bin` 这个目录下，比如你搜到的文章说你要运行 `mysqld_safe ...`，那么你就运行 `/usr/local/opt/mysql@5.7/bin/mysqld_safe ...` 就行了。

**Comment by Ceasar1978** [comment]
@neolee 
我知道这样一步步追问老师很不好，但我确实为这个环境问题已经花了整整一晚时间，很希望能尽快解决从而进入下一步的学习，因此请老师赐教：
在运行 /usr/local/opt/mysql@5.7/bin/mysqld_safe --skip-grant-tables 命令后，报错
2020-05-18T14:31:34.6NZ mysqld_safe Logging to '/usr/local/var/mysql/192.168.0.100.err'.
2020-05-18T14:31:34.6NZ mysqld_safe A mysqld process already exists

但是之前已经关闭 mysql服务了。完整命令及反馈如下：

Last login: Mon May 18 22:20:09 on ttys000
Ceasar@192 ~ % /usr/local/opt/mysql@5.7/bin/mysql.server stop
Shutting down MySQL
.. SUCCESS! 
Ceasar@192 ~ % /usr/local/opt/mysql@5.7/bin/mysqld_safe --skip-grant-tables
2020-05-18T14:31:34.6NZ mysqld_safe Logging to '/usr/local/var/mysql/192.168.0.100.err'.
2020-05-18T14:31:34.6NZ mysqld_safe A mysqld process already exists
Ceasar@192 ~ %

**Comment by neolee** [comment]
再执行 `mysql_safe` 等命令之前必须确保 mysql 服务进程已经停止，按照下面的步骤进行：

```shell
brew services list
```

这会列出 Homebrew 安装和管理的所有服务进程，你应该看到一个 mysql@5.7，如果后面是 started，那么就运行：

```shell
brew services stop mysql@5.7
```

然后再次执行  `brew services list` 确认 mysql@5.7 后面显示 stopped。

然后就可以继续了。

如果你看到列表中 mysql@5.7 后面已经显示 stopped 了，但还是出现上面你 copy 的错误提示的话，试试运行：

```shell
killall mysqld
killall mysql_safe
```

如果以上都不成功，恐怕这个问题就不是可以远程帮你解决的了，我建议你先放放，这个问题对你学习课程影响其实不大，跳过所有 mysql 相关的练习并没有太大的损失。

**Comment by Ceasar1978** [comment]
@neolee 
我现在调整后的状态是 mysql@5.7 stopped，请问如何修改密码？网上找的方法还是无效。
网上找的的方法如下：

1 、关闭mysql服务器
sudo /usr/local/mysql/support-files/mysql.server stop
也可以在系统偏好里有个MySQL里关闭。

2、 cd /usr/local/mysql/bin 进入目录

3、sudo su 获取权限

4、./mysqld_safe --skip-grant-tables & 重启服务器

5、重开个终端，
配置短命令：
alias mysql=/usr/local/mysql/bin/mysql

6、输入mysql 进入mysql命令模式

7、use mysql进入mysql数据库

8、flush privileges;大概就是获取权限，要不他不让你改。

9、set password for 'root'@'localhost'=password('新密码'); 完成修改

但是完成第四步后显示的反馈是：
sh-3.2# /usr/local/opt/mysql@5.7/bin/mysqld_safe --skip-grant-tables &
[1] 2156
sh-3.2# 2020-05-18T15:28:27.6NZ mysqld_safe Logging to '/usr/local/var/mysql/192.168.0.100.err'.
2020-05-18T15:28:27.6NZ mysqld_safe Starting mysqld daemon with databases from /usr/local/var/mysql
2020-05-18T15:28:27.6NZ mysqld_safe mysqld from pid file /usr/local/var/mysql/192.168.0.100.pid ended

新开终端后，进行到第六步，就还是和之前没有任何区别，仍然显示密码错误拒绝访问的反馈：
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)
之后的步骤就无法继续了。

**Comment by Ceasar1978** [comment]
PS：我第5步用的是正确的路径：
alias mysql=/usr/local/opt/mysql@5.7/bin/mysql

**Comment by Ceasar1978** [comment]
@neolee 或者有没有办法能删除重装 mysql？谷歌到以下方法，不知道对我这种用 brew 安装的情况是否有效？

命令：

sudo rm /usr/local/mysql
sudo rm -rf /usr/local/mysql*
sudo rm -rf /Library/StartupItems/MySQLCOM
sudo rm -rf /Library/PreferencePanes/My*
vim /etc/hostconfig  

执行完上面命令后使用的是Vim指令，复制上述命令，保存，退出即可。

继续完成下列指令：


rm -rf ~/Library/PreferencePanes/My*
sudo rm -rf /Library/Receipts/mysql*
sudo rm -rf /Library/Receipts/MySQL*
sudo rm -rf /var/db/receipts/com.mysql.*
————————————————
版权声明：本文为CSDN博主「Jimmy.li」的原创文章，遵循CC 4.0 BY-SA版权协议，转载请附上原文出处链接及本声明。
原文链接：https://blog.csdn.net/u012721519/article/details/55002626

**Comment by neolee** [comment]
从显示的信息看和之前不一样了，这次是无法连接到本地 mysql 服务，也就是说 `mysqld_safe --skip-grant-tables` 这一步启动 mysql 服务失败了。前面也有提示，你可以看看 `/usr/local/var/mysql/192.168.0.100.err` 这个日志文件的内容，看看是什么原因没成功。

如果你是用 Homebrew 安装的 mysql，用 `brew uninstall mysql@5.7` 就可以删除，你查到的方法不行。

**Comment by Ceasar1978** [comment]
> 从显示的信息看和之前不一样了，这次是无法连接到本地 mysql 服务，也就是说 `mysqld_safe --skip-grant-tables` 这一步启动 mysql 服务失败了。前面也有提示，你可以看看 `/usr/local/var/mysql/192.168.0.100.err` 这个日志文件的内容，看看是什么原因没成功。
> 
> 如果你是用 Homebrew 安装的 mysql，用 `brew uninstall mysql@5.7` 就可以删除，你查到的方法不行。

请问如何删除？

**Comment by Ceasar1978** [comment]
@neolee 删除后重装，问题依旧。最终还是决定放弃了，感谢老师的耐心解答！
在这个环境问题上耗费整整一个晚上的时间，到最后也没解决，感觉很不甘心。更麻烦的是这还将成为一个隐患，以后这台电脑要用 mysql 的话，都绕不开这个麻烦。
建议老师在教材中提醒一下大家，慎重设置 mysql 的密码，以避免遇到我这个问题。

**Comment by neolee** [comment]
放心，没有解决不了的问题，只是现在不值得花太多时间在这里，等你必须用 mysql 时就能解决了。
