### ISSUE TITLE
pip install simpleeval 出现问题

### ISSUE THREAD

**Issue by ZhangKaiHua-CW** [neolee/pilot#1313]
pip3 install simpleeval，显示结果如下图，系统提示我现在的pip3版本是19.0.3，建议我更新到20.1
<img width="580" alt="截屏2020-05-19 下午12 04 51" src="https://user-images.githubusercontent.com/58540355/82283837-17cd5e80-99ca-11ea-8073-702a6f2976e9.png">

然后我更新了pip3，没有更新成功，显示结果如下图
<img width="563" alt="截屏2020-05-19 下午12 05 51" src="https://user-images.githubusercontent.com/58540355/82283895-3c293b00-99ca-11ea-87a7-ec542e951503.png">

我也检查了我的python版本是3.7.3
<img width="561" alt="截屏2020-05-19 下午12 09 12" src="https://user-images.githubusercontent.com/58540355/82283908-4814fd00-99ca-11ea-8e0b-465c4dab8916.png">

请问题老师问题出在哪儿？

**Comment by neolee** [comment]
第一个问题是说你没有权限安装软件包，因为你用的 Python 环境是安装在系统目录下的 `/Library/Python/3.7`，所以这个不是按照课程指南中建议的 Homebrew 安装的吧？

第二个问题，不存在 pip3 这个包，你要升级 pip 的话是执行 `pip install -U pip` 或者 `pip3 install -U pip`。

最后，你用的这是啥命令行？也不是课程指南建议的系统自带的 Terminal.app 吧？

**Comment by ZhangKaiHua-CW** [comment]
如果您指的是按照以下截图中这个步骤来操作，我确实是对着步骤来的，而且整个编程环境都是按照步骤一步步来的，自己是零基础，对这些操作都不明白的情况下，只能在课程指南下一步步来：
<img width="1050" alt="截屏2020-05-19 下午4 32 48" src="https://user-images.githubusercontent.com/58540355/82304005-52e18900-99ee-11ea-8fb1-f67eab41ab76.png">


“不存在pip3这个包”这个概念我现在懂了，我之前以为pip install -U pip 就是安装的pip包，pip3 install -U pip就是安装的pip3这个包：
<img width="716" alt="截屏2020-05-19 下午4 38 41" src="https://user-images.githubusercontent.com/58540355/82304554-13676c80-99ef-11ea-9dde-979431ca9aa7.png">


之前我执行 pip install -U pip，没有成功，显示[找不到命令：pip]：
<img width="589" alt="截屏2020-05-19 下午4 48 14" src="https://user-images.githubusercontent.com/58540355/82305594-6aba0c80-99f0-11ea-8037-164c60513600.png">
<img width="681" alt="截屏2020-05-19 下午4 48 51" src="https://user-images.githubusercontent.com/58540355/82307240-a655d600-99f2-11ea-89b9-4992bb9e147c.png">


然后我就执行了pip3 install -U pip：
<img width="710" alt="截屏2020-05-19 下午4 49 25" src="https://user-images.githubusercontent.com/58540355/82307284-b968a600-99f2-11ea-8ad1-ea1c575cfff7.png">


刚刚我又执行了一次pip3 install -U pip，显示如下结果：
<img width="681" alt="截屏2020-05-19 下午4 58 05" src="https://user-images.githubusercontent.com/58540355/82307314-c6859500-99f2-11ea-81cc-d4244b57f879.png">

“最后，你用的这是啥命令行？也不是课程指南建议的系统自带的 Terminal.app 吧？”
关于您的这个疑问，我不知道是不是因为我是在Terminal命令行新建命令后执行命令造成的？因为每一次打开jupyter后，我就不能在原来的Terminal命令行窗口执行命令，
<img width="828" alt="截屏2020-05-19 下午5 08 58" src="https://user-images.githubusercontent.com/58540355/82308628-a22ab800-99f4-11ea-9aa6-c3c1cdd6a20a.png">


然后您的课程指南里提到了解决方案，我发现这个方案是针对Windows用户的，然后我就尝试着在macOS里新建命令：
<img width="990" alt="截屏2020-05-19 下午5 12 50" src="https://user-images.githubusercontent.com/58540355/82308380-47915c00-99f4-11ea-9f26-f4bd2c4d7f89.png">

**Comment by neolee** [comment]
Terminal 不是这么用的，你启动 Terminal.app 之后会打开一个窗口，就在那里面输入命令交互就可以了，不是每次用“新建命令”去执行命令的，先学会用这个基本界面。

<img width="962" alt="Terminal" src="https://user-images.githubusercontent.com/24796/82317345-abba1d00-9a00-11ea-870e-9c13b76dc6bf.png">

熟悉 Terminal 之后，执行下面几个命令（每次输入一行，回车，看结果，然后下一行）：

```shell
which python
which python3
which pip
which pip3
pip -V
pip3 -V
```

把结果拷贝过来发到这里让我看看。

**Comment by ZhangKaiHua-CW** [comment]
那关于jupyter打开后无法在terminal 命令行执行命令应该怎么办？每次都要关掉再重启吗？怎么样保持jupyter打开的同时，在terminal 命令行执行新的命令？

**Comment by ZhangKaiHua-CW** [comment]
比如说我现在要在打开jupyter 同时执行which python：
<img width="599" alt="截屏2020-05-19 下午7 58 20" src="https://user-images.githubusercontent.com/58540355/82323710-0ce6ee00-9a0b-11ea-8275-190efc0a751c.png">
以上的操作肯定是不行的，我之前都是关掉Terminal后再执行新的操作，这样很麻烦，肯定有更便捷的方式，所以我尝试“新建命令”去执行命令，不知道这个尝试对不对？如果不对，有什么正确的方法？

**Comment by neolee** [comment]
> 启动 `jupyter lab` 之后怎么执行别的命令？
我讲过的啊，另外开个 terminal 窗口就行了，在 Terminal 的菜单里选 新建窗口 或者 新建 Tab 都可以，而“新建命令”是不好的。另外我有点好奇，你都可以运行 JupyterLab 了，说明 `pip install` 安装没问题，为啥装 `simpleeval` 会出错呢？你的 JupyterLab 咋装的？

然后看你执行那几个命令的结果，你 Homebrew 安装的 Python 应该在 `/usr/local/bin/python3`，但是目前你的命令行环境找不到这个位置，只能找到 `/usr/bin/` 下的 `python` 和 `python3`，这俩都是 macOS 自带的，一般情况下你不能改动，也不能随便在里面安装新的 Python 第三方包，这是你这个问题的根因。

现在的目标是让 Terminal 环境 能找到你用 Homebrew 安装的 Python。首先在命令行执行 `echo $PATH`，看看环境搜索路径里有没有 `/usr/local/bin`，且在 `/usr/bin` 的前面，以你的反馈看是肯定没有的，你需要保证这里面有 `/usr/local/bin` 且在 `/usr/bin` 的前面，可以执行：

```shell
export PATH=/usr/local/bin:$PATH
```
注意执行这个命令只影响你当前打开的这个 Terminal 窗口，如果你想以后每次打开 Terminal 都自动运行这一句，需要把它加入到 `~/.zshrc` 文件的最后。

执行完这一句，在此执行前面的那几个检测命令：
```shell
which python
which python3
which pip
which pip3
pip -V
pip3 -V
echo $PATH
```

然后可以尝试建立两个别名方便以后使用：
```shell
ln -s /usr/local/bin/python3 /usr/local/bin/python
ln -s /usr/local/bin/pip3 /usr/local/bin/pip
```

然后就应该 OK 了。

最后，你的基础需要补补，有一些支线课程可以先看看（尤其是标记新手必看的那几个）：
https://github.com/neolee/pilot/wiki/Video-Lectures

**Comment by ZhangKaiHua-CW** [comment]
<img width="607" alt="截屏2020-05-20 下午7 48 01" src="https://user-images.githubusercontent.com/58540355/82443003-4e42d080-9ad3-11ea-910a-600107c58cc2.png">
刚刚重新打开Terminal，再次执行pip3 install simpleeval，竟然成功了。我想上面的问题是不是因为我“新建命令”执行命令用的是macOS 自带的patron造成的？
