### ISSUE TITLE
VSCode 有时会出现类似红色的数字报错需要处理吗

### ISSUE THREAD

**Issue by PanChuang2019** [neolee/pilot#1316]
![image](https://user-images.githubusercontent.com/48653618/82985245-42509480-a026-11ea-9e19-a3327398ff6b.png)
就类似这样的红色数字，有时出现很多（比如8，9个错误），但是我在命令行是可以运行该程序的。请问是否要专门做处理？

**Comment by neolee** [comment]
这个应该是 pylint 的warning，也就是你的代码不符合 pylint 代码风格规范的提示，可以遵循 pylint 的提示做修改，也可以关掉 pylint。
