### ISSUE TITLE
安装 scoop 时出错

### ISSUE THREAD

**Issue by ruguo0080828** [neolee/pilot#1317]
> 
PS C:\Users\Administrator> iwr -useb get.scoop.sh | iex
iwr : The remote name could not be resolved: 'raw.githubusercontent.com'
At line:1 char:1
+ iwr -useb get.scoop.sh | iex
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

**Comment by neolee** [comment]
网络问题。

**Comment by Leebo1206677273** [comment]
老师好，我也是同样的问题。该如何处理呢？
