### ISSUE TITLE
 scoop install python37@3.7.4 时出现的问题

### ISSUE THREAD

**Issue by ruguo0080828** [neolee/pilot#1319]
PS C:\Users\Administrator\code\pilot-student> scoop install python37@3.7.4
WARN  Given version (3.7.4) does not match manifest (3.7.7)
WARN  Attempting to generate manifest for 'python37' (3.7.4)
Autoupdating python37
Searching hash for python-3.7.4.exe in https://www.python.org/downloads/release/python-374/
Found: md5:33cc602942a54446a3d6451476394789 using Extract Mode
Searching hash for python-3.7.4-amd64.exe in https://www.python.org/downloads/release/python-374/
Found: md5:a702b4b0ad76debdb3043a583e563400 using Extract Mode
Writing updated python37 manifest
Installing 'python37' (3.7.4) [64bit]
python-3.7.4-amd64.exe (25.4 MB) [=============================================================================================================================] 100%
Checking hash of python-3.7.4-amd64.exe ... ERROR Exception calling ".ctor" with "0" argument(s): "This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms."
ERROR Hash check failed!
App:         python37
URL:         https://www.python.org/ftp/python/3.7.4/python-3.7.4-amd64.exe#/py3.exe
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    a702b4b0ad76debdb3043a583e563400
Actual:

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Versions/issues/new?title=python37%403.7.7%3a+hash+check+failed

**Comment by ruguo0080828** [comment]
PS C:\Users\Administrator\code\pilot-student> scoop install innounp
Installing 'innounp' (0.49) [64bit]
innounp049.rar (137.6 KB) [====================================================================================================================================] 100%
Checking hash of innounp049.rar ... ok.
Extracting innounp049.rar ... done.
Linking ~\scoop\apps\innounp\current => ~\scoop\apps\innounp\0.49
Creating shim for 'innounp'.
'innounp' (0.49) was installed successfully!
PS C:\Users\Administrator\code\pilot-student> scoop install dark
Installing 'dark' (3.11.2) [64bit]
dark-3.11.2.zip (3.5 MB) [=====================================================================================================================================] 100%
Checking hash of dark-3.11.2.zip ... ok.
Extracting dark-3.11.2.zip ... done.
Linking ~\scoop\apps\dark\current => ~\scoop\apps\dark\3.11.2
Creating shim for 'dark'.
'dark' (3.11.2) was installed successfully!
PS C:\Users\Administrator\code\pilot-student> scoop install wixtoolset
Installing 'wixtoolset' (3.11.2) [64bit]
wix311-binaries.zip (33.1 MB) [================================================================================================================================] 100%
Checking hash of wix311-binaries.zip ... ok.
Extracting wix311-binaries.zip ... done.
Linking ~\scoop\apps\wixtoolset\current => ~\scoop\apps\wixtoolset\3.11.2
Creating shim for 'candle'.
Creating shim for 'dark'.
WARN  Overwriting shim to dark.exe installed from dark
Creating shim for 'heat'.
Creating shim for 'insignia'.
Creating shim for 'light'.
Creating shim for 'lit'.
Creating shim for 'lux'.
Creating shim for 'melt'.
Creating shim for 'nit'.
Creating shim for 'pyro'.
Creating shim for 'retina'.
Creating shim for 'shine'.
Creating shim for 'smoke'.
Creating shim for 'ThmViewer'.
Creating shim for 'torch'.
Creating shim for 'WixCop'.
'wixtoolset' (3.11.2) was installed successfully!

**Comment by ruguo0080828** [comment]
PS C:\Users\Administrator\code\pilot-student> scoop install python37@3.7.4
WARN  Given version (3.7.4) does not match manifest (3.7.7)
WARN  Attempting to generate manifest for 'python37' (3.7.4)
Autoupdating python37
Searching hash for python-3.7.4.exe in https://www.python.org/downloads/release/python-374/
Found: md5:33cc602942a54446a3d6451476394789 using Extract Mode
Searching hash for python-3.7.4-amd64.exe in https://www.python.org/downloads/release/python-374/
Found: md5:a702b4b0ad76debdb3043a583e563400 using Extract Mode
Writing updated python37 manifest
Installing 'python37' (3.7.4) [64bit]
python-3.7.4-amd64.exe (25.4 MB) [=============================================================================================================================] 100%
Checking hash of python-3.7.4-amd64.exe ... ERROR Exception calling ".ctor" with "0" argument(s): "This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms."
ERROR Hash check failed!
App:         python37
URL:         https://www.python.org/ftp/python/3.7.4/python-3.7.4-amd64.exe#/py3.exe
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    a702b4b0ad76debdb3043a583e563400
Actual:

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Versions/issues/new?title=python37%403.7.7%3a+hash+check+failed

**Comment by ruguo0080828** [comment]
通过网页访问https://www.python.org/downloads/release/python-374/
下载了：Windows x86-64可执行安装程序
并成功安装了python-3.7.4-amd64.exe，提示安装成功了
可是再去查安装情况
显示：
PS C:\Users\Administrator\code\pilot-student> scoop list
Installed apps:

  7zip 19.00
  busybox 3466-g53c09d0e1
  dark 3.11.2
  git 2.27.0.windows.1
  innounp 0.49
  nodejs 14.4.0
  python37 3.7.4 *failed*
  wixtoolset 3.11.2
仍然显示失败

**Comment by neolee** [comment]
scoop 安装一个软件包除了下载官网安装包并运行之外还会做一些系统配置工作，没有完成这些配置的话就不算完成，显示为 failed，你自己下载安装包安装就会出现这种情况。

你首先要保证 `scoop checkup` 显示的问题都解决掉，然后 `scoop update` 成功无错误信息。

然后就可以用 `scoop uninstall python37` 然后再 `scoop install python37@3.7.4` 来重新安装。

不过只是为了学习的话，只要你 `python -V` 返回 3.7.*，`pip install jupyterlab` 无问题，其实怎么安装 Python 都可以的。

**Comment by neolee** [comment]
前面都无问题，安装 python 那一步出错了，下载的文件不完整，可能是网络问题。换个时间再试试看。
