### ISSUE TITLE
为什么ConEmu运行hello.py的结果为空？

### ISSUE THREAD

**Issue by bright-xuexi** [neolee/pilot#132]
前面安装都已经OK，用VSCode创建hello.py文件和保存也OK。
在ConEmu 窗口，然后：
输入 ls ↩︎，应该可以看到刚才新建的文件 hello.py
输入 python hello.py ↩︎ 运行 hello.py 程序的结果为空，不知道为什么，请帮忙解答。
![print hello](https://user-images.githubusercontent.com/36670984/67629898-d4d65d00-f8b8-11e9-8a58-fbc8e6020762.jpg)
![python hello](https://user-images.githubusercontent.com/36670984/67629899-d9027a80-f8b8-11e9-9f87-a1637d5a5d4f.jpg)

**Comment by neolee** [comment]
Duplicate of #131
