### ISSUE TITLE
scoop 可以找到 7zip 但无法安装

### ISSUE THREAD

**Issue by xcb8488** [neolee/pilot#1320]
C:\WINDOWS\system32>scoop search 7zip
'versions' bucket:
    7zip-beta (18.03)
    7zip-zstd (19.00-v1.4.5-R2)

C:\WINDOWS\system32>scoop install -g 7zip-zstd
Couldn't find manifest for '7zip'.

**Comment by neolee** [comment]
你执行 `scoop update` 成功吗？有什么信息？

**Comment by xcb8488** [comment]
Thanks  so  much，I  make  it。Thank you so  much


发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Neo Lee<mailto:notifications@github.com>
发送时间: 2020年6月8日 12:34
收件人: neolee/pilot<mailto:pilot@noreply.github.com>
抄送: xcb8488<mailto:xcb8488@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [neolee/pilot] scoop 可以找到 7zip 但无法安装 (#1320)


你执行 scoop update 成功吗？有什么信息？

―

**Comment by okwh** [comment]
first run   scoop buket add main
