### ISSUE TITLE
安装 scoop 时提示错误

### ISSUE THREAD

**Issue by Hsiazl** [neolee/pilot#1321]
PS C:\Users\hsia> Invoke-Expression (New-Object System.Net.WebClient).DownloadString('https://get.scoop.sh')
使用“1”个参数调用“DownloadString”时发生异常:“未能解析此远程名称: 'raw.gith
ubusercontent.com'”
所在位置 行:1 字符: 1
+ Invoke-Expression (New-Object System.Net.WebClient).DownloadString('h ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException

自己在网上没找到解决方法，请大家指导！

**Comment by neolee** [comment]
网络问题，试试换网络或者换时间试试，或者使用网络代理。

**Comment by Hsiazl** [comment]
使用网络代理（v2rayN，网上找到的免费VPN）后，一切安装成功，谢谢李老师的指导，期待接下来的编程学习之旅。
