### ISSUE TITLE
安装 scoop 出现 InvalidOperation

### ISSUE THREAD

**Issue by nuoko** [neolee/pilot#1322]
老师我安装scoop，出现如下状况，也使用了代理，自己弄了半天了毫无头绪。还请您能给看看
iwr : 基础连接已经关闭: 连接被意外关闭。
所在位置 行:1 字符: 1
+ iwr -useb get.scoop.sh | iex
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:Htt
   pWebRequest) [Invoke-WebRequest]，WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShe
   ll.Commands.InvokeWebRequestCommand

**Comment by neolee** [comment]
这是网络问题，可以换个网络或者换个时间试试，或者尝试网络代理。

**Comment by nuoko** [comment]
老师我用了网络代理还是这个样子，网络可以正常访问YouTube，等国外网站，但是还是出现这种情况，

**Comment by nuoko** [comment]
老师我弄好了 ，谢谢老师非常感谢老师

**Comment by Hsiazl** [comment]
> 老师我弄好了 ，谢谢老师非常感谢老师

是如何弄好的？我装scoop时也是一直出问题，换网络换时间试后都不行

**Comment by nuoko** [comment]
> > 老师我弄好了 ，谢谢老师非常感谢老师
> 
> 是如何弄好的？我装scoop时也是一直出问题，换网络换时间试后都不行

我换了个ShadowsocksR，我不知道你用的是机场还是其他软件，我用的是机场，换成我刚给你说的那个，重新连上代理就好了

**Comment by Leebo1206677273** [comment]
我也是同样问题，还没处理好
