### ISSUE TITLE
 ConEmu 窗口在命令行界面操作运行 VSCode 遇到的问题

### ISSUE THREAD

**Issue by nuoko** [neolee/pilot#1324]
老师，按照说明分别运行运行后出现这样的问题不知道怎么解决，其他也都没有动

PS C:\Users\Administrator> mkdir Code

    目录: C:\Users\Administrator

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----         2020/6/9     17:06                Code

PS C:\Users\Administrator> cd Code
PS C:\Users\Administrator\Code> code .
code : 无法将“code”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路
径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ code .
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (code:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by neolee** [comment]
用 installer 安装正式版 VSCode 之后就自动可以使用 `code` 命令。

你执行 `$env:Path` 输出是啥？

**Comment by nuoko** [comment]
老师输出是这个
PS C:\Users\Administrator> $env:Path
C:\Program Files\ConEmu\ConEmu\Scripts;C:\Program Files\ConEmu;C:\Program Files\ConEmu\ConEmu;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\windows\System32\OpenSSH\;C:\Users\Administrator\scoop\apps\python37\current\scripts;C:\Users\Administrator\AppData\Local\Programs\Python\Launcher\;C:\Users\Administrator\scoop\shims;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;C:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\bin

**Comment by neolee** [comment]
你看看你的 `C:\Users\Administrator\AppData\Local\Programs\Microsoft VS Code\bin` 目录下面有没有一个 `code.cmd` 文件？这个就是 `code` 命令的本体。

**Comment by nuoko** [comment]
![11](https://user-images.githubusercontent.com/66421372/84237658-57501c00-ab2c-11ea-928c-7577246a2fe1.png)
老师这是截图

**Comment by neolee** [comment]
那你在命令行执行 code 命令应该没问题呀，你再试试？

**Comment by nuoko** [comment]
老师，好了，好奇怪哈哈哈哈哈哈哈，谢谢老师，感谢老师耐心解答，谢谢老师
