### ISSUE TITLE
import 自己写的 module 时的问题

### ISSUE THREAD

**Issue by tyler1zhang** [neolee/pilot#1327]
在当前目录下的各个文件的tree关系图如下：
```
.
├── main.py
└── modules
    ├── __init__.py
    ├── myutil.py
    ├── other.py
    ├── __pycache__
    │   ├── __init__.cpython-36.pyc
    │   └── myutil.cpython-36.pyc
    └── setup.py

```
其中`main.py`的code为：
```python
import sys
sys.path.append('./modules')
from modules.myutil import *
print(is_prime(47))
```
`setup.py`的code为：
```python
import sys
sys.path.append('../modules')
import myutil
print(myutil.is_prime(47))
```

我的问题是，
1. 为什么在`main.py`中加入`modules`的path的时候，可以写成`'../modules'`，或`'./modules'`， 或`'/modules'`, 或`'modules'`。这四种写法有什么差别么？为什么？（ps:竟然`'../modules'`也行，这个应该是指上一级目录呀。奇怪）
2. 为什么在`main.py`中import的时候要加`modules.myutil`，而不是`myutil`。 而`setup.py`中必须是`myutil`而不是`modules.myutil`？

提前感谢老师和同学。

**Comment by neolee** [comment]
1. 在 main.py 中，如果你写 `sys.path.append('./modules')` 意思是“将当前目录下的 modules 子目录加入库文件搜索路径”，因为 `.` 代表当前目录；如果你写 `sys.path.append('../modules')` 意思是“将当前目录的上一层目录下的 modules 子目录加入库文件搜索路径”，因为 `..` 代表当前目录的上一层目录；`modules` 的写法等价于 `./modules`，而 `/modules` 是根目录下的 modules 目录的意思。综上，你写 `./modules` 和 `modules` 都可以，其他的不对，会出错。如果没出错那那是有别的原因（见下）。

2. 如果你正确地将 `modules` 加入到了库搜索路径，那么 `import` 时不需要包含 `modules`，从它下面的目录开始就行了。

3. 最后，Python 缺省行为是会把当前目录放到库搜索路径中的。你 main.py 里的 `from modules.myutil import *` 实际上是从当前目录出发找到了 `modules/myutil.py` 这个 module，这种情况下前面的 `sys.path.append('./modules')` 是没用到的，这叫错进错出，两个错误叠加之后碰巧成了；而 setup.py 里的 `sys.path.append('../modules')` 没问题，它把 setup.py 的上一层目录下的 `modules` 目录加入搜索路径，然后在那个目录下找到了 `myutil.py` 这个 module，这算是正常的情况。
