### ISSUE TITLE
jupyter lab正常启动但是没有出现学习用书

### ISSUE THREAD

**Issue by Kokicoco** [neolee/pilot#1328]
路径应该是对的，在pilot-student目录下启动的，之前还是正常的，今天看支线课程跟着操作了一下，然后就变成现在这样了，请问是什么原因？
![截图](https://user-images.githubusercontent.com/57208219/84869683-f1760e00-b0b0-11ea-8538-b4d422ea0d8c.png)

**Comment by neolee** [comment]
点左边一排最上面的那个按钮呢？

**Comment by Kokicoco** [comment]
> 点左边一排最上面的那个按钮呢？

已经解决了，原来是被隐藏了，谢谢老师！
