### ISSUE TITLE
安装 scoop 网络问题如何解决？

### ISSUE THREAD

**Issue by Leebo1206677273** [neolee/pilot#1329]
PS C:\Users\LeeBo> iwr -useb get.scoop.sh | iex
iwr : 未能解析此远程名称: 'raw.githubusercontent.com'
所在位置 行:1 字符: 1
+ iwr -useb get.scoop.sh | iex
+ ~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo : InvalidOperation: (System.Net.
HttpWebRequest:HttpWebRequest) [Invoke-WebRequest]，WebEx
ception
+ FullyQualifiedErrorId : WebCmdletWebResponseException,
Microsoft.PowerShell.Commands.InvokeWebRequestCommand

**Comment by neolee** [comment]
网络问题，换个网络或者使用代理试试。

**Comment by Lan-Xuezhi** [comment]
换了几个网络，还是不能解析。你那边换个网络就解决了吗？

**Comment by Leebo1206677273** [comment]
好的，谢谢


 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Neo Lee"<notifications@github.com&gt;; 
发送时间: 2020年6月18日(星期四) 上午10:56
收件人: "neolee/pilot"<pilot@noreply.github.com&gt;; 
抄送: "ONLY"<1206677273@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [neolee/pilot] 安装scoop网络问题如何解决？ (#1329)





 
网络问题，换个网络或者使用代理试试。

**Comment by Leebo1206677273** [comment]
问题已解决，感觉特别兴奋。哈哈
 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Lan-Xuezhi"<notifications@github.com&gt;; 
发送时间: 2020年6月20日(星期六) 下午3:05
收件人: "neolee/pilot"<pilot@noreply.github.com&gt;; 
抄送: "ONLY"<1206677273@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [neolee/pilot] 安装 scoop 网络问题如何解决？ (#1329)





 
换了几个网络，还是不能解析。你那边换个网络就解决了吗？
