### ISSUE TITLE
Scoop 安装 git 老显示操作超时，自己从其他网站上下载 git 后续操作又跟老师的对不上

### ISSUE THREAD

**Issue by Lilidandan321** [neolee/pilot#133]
<img width="922" alt="11" src="https://user-images.githubusercontent.com/53359222/67630865-11aa5000-f8c9-11e9-80e1-b970cbacedce.png">

**Comment by neolee** [comment]
如果你已经用其他方法安装好了 git，可以执行 git --version 看看返回正常不。

如果正常，可以跳过指南中 scoop install git 这一步，直接执行 scoop update，然后继续后面的。

**Comment by wangbingfeng** [comment]
The solution is:

add 
192.30.253.112  github.com
192.30.253.113  github.com
to your hosts file
scoop install aria2
 install git
> scoop uninstall git
Uninstalling 'git' ().
'git' was uninstalled.
> scoop install git
 

repeat step 3 until the installation is successful,make sure your network is stable
 

another solution :

 download right PortableGit-2.23.0-32-bit.7z.exe for your computer
put it in your scoop/cache folder
> scoop uninstall git
Uninstalling 'git' ().
'git' was uninstalled.
> scoop install git

**Comment by Lilidandan321** [comment]
好啦，谢谢

**Comment by yejunhua123** [comment]
![image](https://user-images.githubusercontent.com/57058028/67633195-e6832900-f8e7-11e9-85e4-201049215709.png)
是用这个方法吗？我是个地道的小白，用上面的方法，第一步找到hosts文件夹，添加了192.30.253.112  github.com，192.30.253.113  github.com；第二步scoop install aria2又出错了。

![image](https://user-images.githubusercontent.com/57058028/67633300-39111500-f8e9-11e9-99c7-9c409585bdb3.png)
![image](https://user-images.githubusercontent.com/57058028/67633314-61990f00-f8e9-11e9-8af3-76fa529ef99f.png)

**Comment by Lilidandan321** [comment]
我是从腾讯软件中心上下载安装的git，然后按照老师的说的“
如果你已经用其他方法安装好了 git，可以执行 git --version 看看返回正常不。

如果正常，可以跳过指南中 scoop install git 这一步，直接执行 scoop update，然后继续后面的。”这个方法运行没有出错，就🆗了。你也可以从其他地方下载git试试

 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "yejunhua123"<notifications@github.com&gt;; 
发送时间: 2019年10月27日(星期天) 晚上6:41
收件人: "neolee/pilot"<pilot@noreply.github.com&gt;; 
抄送: "莫言心悸幽蓝"<2467764484@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [neolee/pilot] Scoop 安装 git 老显示操作超时，自己从其他网站上下载 git 后续操作又跟老师的对不上 (#133)





 是用这个方法吗？我是个地道的小白，用上面的方法，第一步找到hosts文件夹，添加了192.30.253.112  github.com，192.30.253.113  github.com；第二步scoop install aria2又出错了。
