### ISSUE TITLE
为什么我的 nteract 没有自动补全功能

### ISSUE THREAD

**Issue by leeyeep** [neolee/pilot#1330]
我看视频里老师的nteract能自动补全代码，但是我的没有，我搜索google找了一大堆资料把类Jupyter notebook用插件形式整的能自动补全了，但是Jupyter Lab还是没有自动补全，导致最终nteract也没有自动补全，想问下这个要如何设定才能让nteract有自动补全了

**Comment by neolee** [comment]
Jupyter Lab 是自带自动补全的——由于缺乏 Language Server 这一类高级特性，它的自动补全无法与 Visual Studio Code 相提并论，但确实是有的。

最新版本的 nteract 也支持自动补全，激活的快捷键是 Control+Space。

**Comment by leeyeep** [comment]
是不是因为我用的MAC版本的问题，MAC版的lab和nteract完全都没有补全，刚刚特意又试了下

**Comment by neolee** [comment]
nteract 的自动补全都是 Control+Space，如果你的 macOS 下这个快捷键用于别的事情了，就会有冲突，目前 nteract 还不支持自定义快捷键……

**Comment by leeyeep** [comment]
解决了，果然是快捷键冲突了！我把输入法快捷键换成其他的就好了
