### ISSUE TITLE
Your Command Line Tools are too outdated

### ISSUE THREAD

**Issue by Evayip007** [neolee/pilot#1331]
在设置编程环境时，执行brew doctor出现报错，
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Your Command Line Tools are too outdated.
Update them from Software Update in the App Store.

xcode版本为11.3.1（11C504)，找到一个方法试着解决，在https://developer.apple.com/download/下载最新版本的Xcode，再下载对应的Commond Line Tools ，更新mac系统后从官网复制命令安装brew输入密码后，出现

Press RETURN to continue or any other key to abort
==> Downloading and installing Homebrew...
remote: Enumerating objects: 159, done.
remote: Counting objects: 100% (126/126), done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 31 (delta 25), reused 16 (delta 13), pack-reused 0
Unpacking objects: 100% (31/31), done.
From https://github.com/Homebrew/brew
   fc98ef860..a89b56598  master     -> origin/master
HEAD is now at a89b56598 Merge pull request #7783 from Homebrew/dependabot/bundler/Library/Homebrew/parser-2.7.1.4

**Comment by neolee** [comment]
如果没有遇到其他问题，这个 warning 是可以忽略的。

**Comment by Evayip007** [comment]
> 如果没有遇到其他问题，这个 warning 是可以忽略的。
好的，发现执行brew doctor后又回到warning这，之前白忙了
