### ISSUE TITLE
执行 brew install git python 后显示 updating homebrew...

### ISSUE THREAD

**Issue by Evayip007** [neolee/pilot#1332]
执行brew install git python后显示updating homebrew...一直不动应该怎么办。crl+c退出后重复也是一样。

**Comment by neolee** [comment]
等它做完，如果时间太长应该就是网络的问题了。

**Comment by Evayip007** [comment]
网络问题是需要科学上网的意思吗？

**Comment by neolee** [comment]
是的，或者搜搜国内的 Homebrew 镜像。

**Comment by Evayip007** [comment]
谢谢~

**Comment by Evayip007** [comment]
用了网上建议的替换brew：
cd "$(brew --repo)"
git remote set-url origin https://mirrors.ustc.edu.cn/brew.git
cd "$(brew --repo)/Library/Taps/homebrew/homebrew-core"
git remote set-url origin https://mirrors.ustc.edu.cn/homebrew-core.git

执行brew install git python后出现：
Error: python: undefined method `undent' for #String:0x00007ff377b5cc60

**Comment by Evayip007** [comment]
老师，whoami老师帮我找到问题啦，执行python -m pip install --upgrade pip时出现No module named pip，推测python没有安装成功，他建议改成python3就不报错啦~谢谢~~！
