### ISSUE TITLE
安装好 scoop 安装 Python 出现问题

### ISSUE THREAD

**Issue by doriawq** [neolee/pilot#1333]
warn given version（3.7.4）does not match manifest()
warn attempting to generate manifest for 'python37'(3.7.4)
'python37' does not have autoupdate capability
couldn't find manifest for 'python37@3.7.4

**Comment by neolee** [comment]
仔细看环境配置指南：https://github.com/neolee/pilot/blob/master/x1-setup.md

你需要执行下面三个命令：

```powershell
scoop bucket add versions
scoop update
scoop install python37@3.7.4
```

都成功的话就装好了。

**Comment by doriawq** [comment]
老师，前两个命令都成功了
The main bucket was added successfully
Scoop was updated successfully
但是执行第三个，依然同样的结果

**Comment by neolee** [comment]
第一个命令要安装一个叫 versions 的 bucket，不是 main，看你写的提示不对呀……

**Comment by doriawq** [comment]
‘main'bucket:
   aws(1.18.44)-->includes 'python.exe'
   python(3.8.3)
   winpython(3.8.3.0)

**Comment by neolee** [comment]
你没有成功安装 versions 这个 bucket，也就是说 `scoop bucket add versions` 没有执行对或者没执行成功。

**Comment by doriawq** [comment]
原来是这样！终于成功了！谢谢老师

**Comment by doriawq** [comment]
PS：我是看的您的视频 里面没有GitHub这么详细 幸亏有您和同学加贝帮忙

**Comment by neolee** [comment]
永远是文档为主，视频为辅。
