### ISSUE TITLE
No module named pip

### ISSUE THREAD

**Issue by Evayip007** [neolee/pilot#1334]
执行python -m pip install --upgrade pip时出现
No module named pip
推测python没有安装成功，因为在执行brew install git python 时一直卡在Updating Homebrew...
现Homebrew 2.4.0-95-ga89b565
Homebrew/homebrew-core (git revision 624f; last commit 2017-02-06)
是否仍是网络问题？
找镜像的方法是？~

**Comment by neolee** [comment]
可能你执行的 python 不是你想的那个。

执行下面的测试命令看看结果：

```shell
which python
which python3
python -V
python3 -V
which pip
which pip3
pip -V
```

**Comment by neolee** [comment]
我看到你在另一 issue 下的说明了，以后一个问题就在一个 issue 下交互，不要乱跳，会让人摸不着头脑。

你这个问题已经解决，但你可以注意看看 [环境配置指南](https://github.com/neolee/pilot/blob/master/x1-setup.md) macOS 部分安装 Homebrew 的部分（接近最后部分），会有帮助。
