### ISSUE TITLE
输入 iwr -useb get.scoop.sh | iex 报错

### ISSUE THREAD

**Issue by chendong0** [neolee/pilot#1336]
输入 iwr -useb get.scoop.sh | iex
这一步出现错误。尝试以下办法均没能解决？请求帮助，谢谢。
方法1、尝试卸载、重装git，问题还是 scoop update failed
方法2、https://github.com/lukesampson/scoop/issues/1553#issuecomment-308721227 
方法3、 $env:SCOOP\apps\scoop\current and run scoop update 
方法4、 Go to <SCOOP_INSTALL_DIR>/buckets
remove everything in this directory  
方法5、卸载、重新安装conemu、安装 Git-2.27.0-64-bit.exe、重启电脑
![Image](https://user-images.githubusercontent.com/40737674/85375691-414d4d00-b569-11ea-92ac-d77c549b57ba.png)

**Comment by neolee** [comment]
你第一个命令显示你已经装好了 Scoop，只要 `scoop update` 就可以更新软件包信息，然后 `scoop install` 去安装你要的软件包了。

后面这个命令是安装 Scoop 用的，你遇到的错误一般是网络问题，可以换个网络换个时间试试。或者按照下面这个页面最后面的那个方法试试，有时候有奇效：

https://github.com/neolee/wop-community

**Comment by chendong0** [comment]
这个问也是网络问题。
![Image](https://user-images.githubusercontent.com/40737674/85520974-301e4200-b636-11ea-8a24-3f2561510649.png)
