### ISSUE TITLE
scoop update failed 已成功安装 Git 但更新一直不成功

### ISSUE THREAD

**Issue by chendong0** [neolee/pilot#1337]
尝试以下办法，未能正确解决。
![Image](https://user-images.githubusercontent.com/40737674/85376109-dcdebd80-b569-11ea-9c9c-205db375c5f7.png)

方法1、尝试卸载、重装git，问题还是 scoop update failed
方法2、卸载、重新安装conemu、安装 Git-2.27.0-64-bit.exe、重启电脑
stackoverflow中有相近问题，可能是git安装被打断，但已多次重装git，未能解决。
可能是网络代理问题，未能找到正确的解决入口，请大家帮忙，谢谢。

**Comment by neolee** [comment]
你为什么问了两个类似的问题，你目前的状况到底是这两个问题里的哪一个啊？

如果 Scoop 没有安装好，需要先删除 Scoop 然后重装，具体方法点这个页面上方 Wiki 链接，里面有。我在你另一个问题下面的回复中给了一个链接，可以消除一些访问 GitHub 可能的问题（安装 Scoop 需要使用 GitHub 上的资源）。

如果 Scoop 安装好了，但是 `scoop update` 有问题（或者安装 git 有问题），那通常是网络问题，可能要换网络或者用代理解决。

一般来说和你的 ConEmu 是没关系的。

**Comment by chendong0** [comment]
1、我使用的是windows to go 的win10系统。
2、我敲入代码ping 140.82.113.4  反应时间是正常的，已经尝试了解决scoop update failed，但是一直找不到是什么原因更新不了。一直被卡在update，没法下一步安装python。

**Comment by chendong0** [comment]
![Image](https://user-images.githubusercontent.com/40737674/85520710-dcabf400-b635-11ea-93f4-9f940fb44a32.png)
1、网络代理问题，已解决。
