### ISSUE TITLE
NameError 

### ISSUE THREAD

**Issue by Evayip007** [neolee/pilot#1339]
执行
```python
class Cat:
    
    kind = 'felidae'
    
    def __init__(self, name):
        self.name = name
        
    def mew(self):
        return 'meow-meow'
    
c = Cat('Garfield')

Cat.kind
```

出现

NameError                                 Traceback (most recent call last)
<ipython-input-8-d228ffb73297> in <module>
----> 1 Cat.kind

NameError: name 'Cat' is not defined

**Comment by neolee** [comment]
首先学会怎么在这里贴代码： https://github.com/neolee/wop-community

然后，代码看上去没问题，你是把争端代码保存为文件，然后 `python xxx.py` 这样执行的吗？如果是的话把完整的文件贴出来看看。

**Comment by Evayip007** [comment]
贴代码get，谢谢！
没有老师说的保存文件这一步，直接左边打开在线书本，右边是jupyter lab。刚刚到回去run又没报错了，奇怪

**Comment by Evayip007** [comment]
```python
class Cat(Animal):
    
    kind = 'felidae'
    
    def voice(self):
        return 'meow-meow'
    
    mew = voice
```
NameError                                 Traceback (most recent call last)
<ipython-input-21-6da325a170b3> in <module>
----> 1 class Cat(Animal):
      2 
      3     kind = 'felidae'
      4 
      5     def voice(self):

NameError: name 'Animal' is not defined

**Comment by neolee** [comment]
这个问题，你在 notebook 里面写的代码并不代表会被自动执行，只有你选择执行过的代码才会有效。如果你写了 `class Animal ...` 的定义，但是没有执行它，那系统里就不存在 Animal 这个 class 定义，你下面要用它就会报错。

在 notebook 里执行过的代码单元格前面的 `[]` 里会出现数字，代表这是本次会话中执行的第几个单元格。如果前面 `[]` 里空着或者显示一个 `*` ，那就是没执行过或者执行没完成。

**Comment by Evayip007** [comment]
明白，的确是这个问题，谢谢老师！
