### ISSUE TITLE
安装 git 出错怎么办？

### ISSUE THREAD

**Issue by yejunhua123** [neolee/pilot#134]
![image](https://user-images.githubusercontent.com/57058028/67631612-aade6400-f8d3-11e9-80e9-a76dafe68357.png)

**Comment by neolee** [comment]
之前安装 git 失败，需要先 scoop uninstall git，然后重装 git。

有不少类似问题，可以在 issues 里查找下。

p.s. 可以参考 issue #133

**Comment by yejunhua123** [comment]
![image](https://user-images.githubusercontent.com/57058028/67633349-d1a79500-f8e9-11e9-87eb-aa989a901a31.png)
是用上面这个方法吗？我是个地道的编程小白，第一步找到hosts文件夹输入了192.30.253.112  github.com 、192.30.253.113  github.com，第二步scoop install aria2又出现错误
![image](https://user-images.githubusercontent.com/57058028/67633381-3ebb2a80-f8ea-11e9-9613-33fc024595a2.png)
![image](https://user-images.githubusercontent.com/57058028/67633389-467acf00-f8ea-11e9-9868-2ef0ff70def3.png)

**Comment by neolee** [comment]
scoop uninstall git

然后 

scoop install git

**Comment by yejunhua123** [comment]
![image](https://user-images.githubusercontent.com/57058028/67633848-0cacc700-f8f0-11e9-92eb-0c73ffa40cb1.png)

**Comment by neolee** [comment]
不行，还是换个网络或者找个代理试试吧。
