### ISSUE TITLE
git config --global user.name "chen" 显示无权限修改

### ISSUE THREAD

**Issue by chendong0** [neolee/pilot#1340]
一、 git config --global user.name "chen"
报错error: could not lock config file C:/Program Files/Java/jdk1.8.0_241/.gitconfig: Permission denied无权限
尝试以下方法均无法解决权限问题：
1、到Git安装目录，设置git-bash.exe的属性，在兼容性属性页勾上“以管理员身份运行此程序”即可。没能解决
2、文件本身出现权限问题，去修改文件执行权限即可。chmod xx  /www/wwwroot/.gitconfig
3、git credential-manager uninstall
4、git credential--manager
git credential-manager uninstall
5、   Step by step:
      1. Windows search
     2. Type: Git Bash
     3. Second mouse button - Run as administrator
     4. Change dir to your project:
6、git config --system --unset credential.helper
error: could not lock config file C:/Program Files/Git/etc/gitconfig: Permission denied
![WeChat Screenshot_20200624155247](https://user-images.githubusercontent.com/40737674/85519004-71612280-b633-11ea-81a6-5ad5d7e99a66.png)

**Comment by chendong0** [comment]
关闭powershell 一个小时后，回来操作，配置git成功。如下次碰到同样的问题，如何解决？谢谢。
![Image](https://user-images.githubusercontent.com/40737674/85534692-20a5f580-b644-11ea-9a1a-5dcea5527c71.png)

**Comment by neolee** [comment]
你的 git 应该不是按照我的指南方式安装的，.gitconfig 也在一个奇怪的地方，难以判断。

**Comment by chendong0** [comment]
应该是电脑按《自学是门手艺》里面的方法配置了环境，有可能有多重环境了。安装了anaconda，手动安装了git bash等等，.gitconfig可能有多个。
现在都是直接用anaconda
```powershell 
$code .
````
来打开和使用了visual studio code
