### ISSUE TITLE
Mac 系统配置环境遇到问题

### ISSUE THREAD

**Issue by xiaoerhai** [neolee/pilot#1341]
如下图所示，操作  ```下载并执行 Homebrew 的安装脚本``` 时提示失败。
<img width="1200" alt="image" src="https://user-images.githubusercontent.com/48662601/85638480-9186f500-b6b8-11ea-9622-f00844401e34.png">

**Comment by neolee** [comment]
网络问题，换网络或者换时间试试，或者使用网络代理。或者试试下面这个页面里最后部分的方案：

https://github.com/neolee/wop-community

**Comment by xiaoerhai** [comment]
用别的网络可以下载了，但如第一个框框里的显示既有失败又有成功的；然后按教材执行下一步提示```not found : brew```,而且我发现我的账户后面多了一个数字2:
<img width="1257" alt="image" src="https://user-images.githubusercontent.com/48662601/85818534-71803000-b7a3-11ea-89ce-6063119c79ce.png">

**Comment by neolee** [comment]
没成功，我建议你试试我给你那个页面上的方案。

**Comment by xiaoerhai** [comment]
老师，我按页面上的方案更改hosts文件后，安装进度如下图所示。是不是还要继续等呀？我发现苹果下载东西是真的慢，同样的网windows下载速度快多了......
<img width="1100" alt="image" src="https://user-images.githubusercontent.com/48662601/85832437-a8b20980-b7c2-11ea-9d6d-241a3988c5cd.png">
<img width="1166" alt="image" src="https://user-images.githubusercontent.com/48662601/85832585-f464b300-b7c2-11ea-971c-c8d7d01d4ae4.png">

**Comment by neolee** [comment]
当然。

**Comment by neolee** [comment]
你每次都是 Homebrew 要从 GitHub clone 核心数据时很长时间？具体等了多久？出失败信息还是你关掉了？

**Comment by xiaoerhai** [comment]
```/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)``` 这一步，第一次需要3个小时左右，之后几次好像会快些，但每次都是既有失败又有成功。

```brew update```这一步，需要的时间每次都在1小时左右。

我一直没有关，是每次出失败信息：
<img width="1165" alt="image" src="https://user-images.githubusercontent.com/48662601/85911968-5c66d800-b85b-11ea-93a3-35bd21dd0498.png">

**Comment by neolee** [comment]
还是试试网络代理吧。

**Comment by xiaoerhai** [comment]
终于搞定了，我没有用网络代理，是在今天凌晨开始让它在下载的，醒来发现装好了。感谢老师，我要继续下一步了。
