### ISSUE TITLE
jupyter lab 抄代码的左侧由数字变成米字没出现运行结果

### ISSUE THREAD

**Issue by Evayip007** [neolee/pilot#1343]
<img width="904" alt="截屏2020-06-26 上午10 08 07" src="https://user-images.githubusercontent.com/24451875/85813109-f57eeb80-b794-11ea-9241-82b4c14964da.png">

**Comment by neolee** [comment]
星号表示这个单元格还在运行没有结束，时间较长的话是不正常的，看看运行 jupyter lab 的那个命令行窗口里有什么错误提示不？

**Comment by Evayip007** [comment]
<img width="574" alt="截屏2020-06-26 上午10 45 53" src="https://user-images.githubusercontent.com/24451875/85815149-4218f580-b79a-11ea-910b-d44952928fe7.png">
命令行窗口指的是终端吗？好像没报错

**Comment by neolee** [comment]
你去看看支线课程里讲 JupyterLab 那一讲吧，说的很清楚的。

**Comment by Evayip007** [comment]
好的，谢谢喽
