### ISSUE TITLE
如何在 list 里面的 tuple 的里面进行数值操作

### ISSUE THREAD

**Issue by Totie-O** [neolee/pilot#1348]
![图片](https://user-images.githubusercontent.com/53247740/86203400-7d9b3180-bb97-11ea-9eaa-bc0d5f41aab2.png)
在列表里，前面是（年级+班级名称），后面是期末考试的数目。
但是18级全体少算一门英语，所以要加还给他。

我自己写一段代码，我判断这个列表里面每一个元素在某个位置是否等于18，然后在后面的数值加上1
可以执行后，后面的数值还是没有改变，还是没有加1
![图片](https://user-images.githubusercontent.com/53247740/86203550-e387b900-bb97-11ea-9612-7a19dd0b94da.png)

**Comment by neolee** [comment]
你的那句 `i[1] + 1` 写的不对呀，应该是 `i[1] = i[1] + 1` 才对。

另外你的那句 `if str(i)[2:4] == '18':` 也不是很好，比较好的写法是：`if i[0].startswith('18'):`。

**Comment by wangnanqiang** [comment]
好难呀，那个list里面的tuple不能赋值，那我把tuple变成str再去掉（），变成字符串，可是字符串也不给赋值修改。
我应该如何办？
![图片](https://user-images.githubusercontent.com/53247740/86209053-4ed78800-bba4-11ea-859f-2701971d15ee.png)

**Comment by neolee** [comment]
哦对，我也没注意——问题是你为啥要用 tuple 呢？里面用 list 不是就简单了么……

当然了，如果它是 tuple 的话，也可以解决，不过你不能用原来的 list 了，要新创建一个，类似于（我没时间实际测试，但意思就是这样）：

```python
lst1 = [...] # 你原先的列表
lst2 = [] # 新创建一个列表来容纳你调整之后的数据

for item in lst1:
    if item[0].startswith('18'):
        lst2.append((item[0], item[1]+1))
    else:
        lst2.append(item)
```

**Comment by wangnanqiang** [comment]
十分感谢
![图片](https://user-images.githubusercontent.com/53247740/86222357-b4ce0a80-bbb8-11ea-86ea-ca675a07fc3c.png)

**Comment by neolee** [comment]
对头，你这个目标用 dict 是比较好的。

四种主要的容器，需要自己多用用才会有真正的心得。
