### ISSUE TITLE
关于 print() 与 list.sort() 的输出问题

### ISSUE THREAD

**Issue by Totie-O** [neolee/pilot#1350]
![图片](https://user-images.githubusercontent.com/53247740/86446128-153e8280-bd46-11ea-930b-728bc1c5c9e7.png)
我服了，我思路没错，分开输出有结果，为啥连接起来输出结果就返回None,是否是以前老师讲的那种情况，sort函数没有设置返回return，然后其结果设置为print.

```python
data.sort(key = lambda x:x['name'])
print(data)

print(data.sort(key = lambda x:x['name'])
```

**Comment by neolee** [comment]
`print(data)` 输出 data 的值；而 `print(data.sort(...))` 输出的是 `data` 对象的 `sort()` 方法的返回值，这俩本来就不一样啊，你为啥预期返回一样呢？

**Comment by wangnanqiang** [comment]
![Uploading 图片.png…]()
课程里面有没有关于这个的一些说明

**Comment by neolee** [comment]
贴图失败，要等 Uploading…… 那句变成 <img> 之后再提交。

**Comment by wangnanqiang** [comment]
![图片](https://user-images.githubusercontent.com/53247740/86484738-79cf0100-bd89-11ea-8dae-888ee445c3ae.png)

课程里面有没有关于这个的一些说明
