### ISSUE TITLE
有存在不能转换为布尔值的值吗？

### ISSUE THREAD

**Issue by xiaoerhai** [neolee/pilot#1351]
老师，出于好奇想问下：有存在不能转换为布尔值的值吗？
<img width="1063" alt="image" src="https://user-images.githubusercontent.com/48662601/86502620-b9bcd500-bdd7-11ea-8246-9a697dd46b5a.png">

**Comment by feifanruwo** [comment]
![image](https://user-images.githubusercontent.com/66456065/86599011-a032ad80-bfd0-11ea-9341-c1e476e1eac7.png)
测试了一下,没发现无法转换布尔值的情况.应该是Python软件本身有一些规定,使得几乎任何值都可以转换为布尔值吧.比如1是True,0是False

**Comment by xiaoerhai** [comment]
谢谢老师

**Comment by feifanruwo** [comment]
老铁，我是菜鸟级别。------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;卢张凯&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年7月8日(星期三) 上午9:47
收件人:&nbsp;&quot;neolee/pilot&quot;<pilot@noreply.github.com&gt;;
抄送:&nbsp;&quot;feifanruwo&quot;<724965054@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [neolee/pilot] 有存在不能转换为布尔值的值吗？ (#1351)
