### ISSUE TITLE
印象笔记与 Markdown 的问题

### ISSUE THREAD

**Issue by doriawq** [neolee/pilot#1352]
我是印象笔记的重度用户，平时写东西就用它。
看了老师讲的支线课程markdown之后，我想起印象笔记里也可以写这种文档，
功能很强大，但导出是html文件（Windows系统）。
这样的html文件可以直接push到GitHub吗？还是要转换一下？

**Comment by neolee** [comment]
我曾经是 EverNote 最早一批付费用户，不过已经很久没用了。我现在主要用 Markdown 格式，好处是便携，拿到哪里都可以编辑，大部分主流内容网站都支持。

Markdown 格式可以很容易的转换为 HTML，但反过来不太完美。所以看你的具体需求了。

如果是想用 GitHub 创建简单站点的话，HTML 也可以的，但是就没有 Markdown 带来的简洁和通用的好处了。

**Comment by doriawq** [comment]
那您就是在visual studio code里写MD文件吗，就像课程里演示的那样？还是用别的呢？

**Comment by neolee** [comment]
我在 Mac 和 iPhone 上用 Bear 这个 app，在 Windows 上用 VS Code（配合一个叫 Markdown All In One 的插件）。
