### ISSUE TITLE
安装 scoop 受阻

### ISSUE THREAD

**Issue by mixinboy** [neolee/pilot#1354]
新购买惠普光影精灵6，按安装指南安装到scoop受阻。
尝试过在wifi，手机热点下运行  iwr -useb get.scoop.sh | iex     安装命令，也在不同时间试过，没有成功。
下图中，第一条命令在全局模式下运行，第二条命令在PAC模式下运行。

![批注 2020-07-05 133932](https://user-images.githubusercontent.com/54926768/86526894-1f8a8900-becc-11ea-8052-46ecfbce0f3b.png)

想按照第一条命令的错误提示找出是什么软件阻止了操作。
请问老师，这思路是否正确？

**Comment by neolee** [comment]
第一个错误是你的防护软件组织了 Scoop 安装程序，暂时关闭你的防护就好了。

第二个错误是网络问题，可以换个时间或者换个网络试试，或者用网络代理。还有 https://github.com/neolee/wop-community 这个页面最下面也有个方法，有时候也能解决问题。

**Comment by mixinboy** [comment]
在关闭迈克菲防火墙后，执行安装命令，依然无法安装。
如图。
![批注 2020-07-05 234920](https://user-images.githubusercontent.com/54926768/86536609-8d11d600-bf1b-11ea-8738-11ac1d0b8046.png)

另外，下图的方案我操作到这一步，不知道下边该如何操作。
![批注 2020-07-05 235435](https://user-images.githubusercontent.com/54926768/86536771-c4cd4d80-bf1c-11ea-8295-43b021ac3d83.png)

**Comment by mixinboy** [comment]
在关闭迈克菲防火墙后，执行安装命令，依然无法安装。
如图。

![批注 2020-07-05 234920](https://user-images.githubusercontent.com/54926768/86536850-740a2480-bf1d-11ea-8c35-010fcf911b9e.png)




另外，下图的方案我操作到这一步，不知道下边该如何操作。用什么程序打开hosts文件把蓝色部分内容追加进去？

![批注 2020-07-06 001539](https://user-images.githubusercontent.com/54926768/86537009-a0727080-bf1e-11ea-8c7f-c3d1f03ca26e.png)

**Comment by neolee** [comment]
前一个问题，应该还是没关掉。我对 Windows 下的第三方防护软件没有概念，可以看看别的同学知道不。

第二个，最好先安装好 Visual Studio Code，然后用它来编辑 hosts 文件。

**Comment by mixinboy** [comment]
在修改hosts文件后，还是无法执行安装。请老师看一下我的添加是否正确。

![5](https://user-images.githubusercontent.com/54926768/86558881-262d0500-bf8d-11ea-824c-dea17fd15be9.png)

**Comment by mixinboy** [comment]
在修改hosts文件后，还是无法执行安装。请老师看一下我的添加是否正确。
第一条命令在全局模式下运行，第二条命令在PAC模式下运行。

![6](https://user-images.githubusercontent.com/54926768/86559194-f92d2200-bf8d-11ea-90aa-ffa9422f7844.png)

**Comment by neolee** [comment]
格式没错，但你没保存啊。

**Comment by mixinboy** [comment]
已经保存过，我打开该文件就已经是这样的。

**Comment by neolee** [comment]
那个文件的标签右边是个大圆点，表示尚未保存，你看到的只是 VS Code 帮你暂时保存的草稿状态。

**Comment by mixinboy** [comment]
如果这个保存正确，那么它遇到了同样的第三方防护软件问题。

![7](https://user-images.githubusercontent.com/54926768/86593823-8e4d0c80-bfc8-11ea-9c22-1845afd898a4.png)

我应该请教同学啦。

**Comment by neolee** [comment]
是的，现在碰到的是防病毒软件的问题。
