### ISSUE TITLE
第三章作业问题

### ISSUE THREAD

**Issue by doriawq** [neolee/pilot#1356]
1.为什么运行结果有两行呢？能不能只要第二行？
![1594006254(1)](https://user-images.githubusercontent.com/51192376/86553189-997a4b00-bf7c-11ea-940d-095f2d4294eb.png)
2.作业上传后，点保存作业还是提交作业？

**Comment by neolee** [comment]
1. 前面那一行是你用 `input()` 函数输入的记录，Jupyter Notebook 会将其也记录和显示出来，不能去掉。

2. 保存就是保存，避免退出后消失，提交才是提交到课程的服务器上，所以最终是以提交为标志才算完成的。

p.s. 我怎么不记得第三章有这个代码，是你自己编的吧？

**Comment by doriawq** [comment]
好的，谢谢老师。
就是最后两道，想知道如果输入了姓名会是什么结果。
还有有时运行会显示Python3 busy 这是什么原因

**Comment by neolee** [comment]
哪里显示 busy？

**Comment by doriawq** [comment]
左下角
![1594009051(1)](https://user-images.githubusercontent.com/51192376/86555526-35a75080-bf83-11ea-8e7c-af769248adfe.png)

**Comment by neolee** [comment]
Python 是解释运行，也就是一行行运行代码，前一行没运行完无法运行后面的，busy 就代表你这个 notebook 背后的引擎（Python 解释器）正在运行某一行代码（对应代码单元格前面会显示 [*]）。

一般不会很久，如果很久可能是有问题，可以重启 Kernel 解决——但你这个格子里有个 input()，所以也可能是在等你输入。

建议去看看支线课程里关于 Jupyter Lab 的那一讲。
