### ISSUE TITLE
执行 scoop install git 遇到问题

### ISSUE THREAD

**Issue by mixinboy** [neolee/pilot#1359]
![10](https://user-images.githubusercontent.com/54926768/86876728-ee9e9400-c117-11ea-8bbe-8f254b1d6723.png)

请老师解惑。

**Comment by neolee** [comment]
`scoop checkup` 检测出来的几个问题，尤其是前三个，需要解决，按照它的建议做（“consider running…” “enable it with running…”）。注意第三个命令需要用管理员权限运行。
