### ISSUE TITLE
Nteract运行结果和Jupyterlab不一致的问题

### ISSUE THREAD

**Issue by doriawq** [neolee/pilot#1360]
图片1为教材
![dd9d411289979bdfb33efa3345952e8](https://user-images.githubusercontent.com/51192376/86905538-c5e0c380-c144-11ea-8e0d-4b1b7b07f84a.png)
图片2为Nteract
![1463fb1a0628e76559014e13fca486d](https://user-images.githubusercontent.com/51192376/86905552-cf6a2b80-c144-11ea-8093-dd9ef1a2ceaf.png)
图片3为jupyterlab
![94dc38372422e9abe4629b2a0bff749](https://user-images.githubusercontent.com/51192376/86905578-d85afd00-c144-11ea-807f-6e6782115744.png)

以及为什么结果是black，这段不懂

**Comment by neolee** [comment]
1. 在我这里无论在什么环境下运行这段代码，结果都一样，即 `['black']`。

2. 为什么是这个结果？注意下面几点：
* `(?:)` 这个操作符的效果是匹配但不捕获，所以这个 pattern 里只有后面那个 group 是要捕获匹配结果的；
* `re.findall` 这个方法一般是返回所有匹配子串组成的 list，如果 pattern 里包含捕获的 group，那么只会返回捕获的部分。
