### ISSUE TITLE
执行 scoop install python37@3.7.4  时出现的问题。

### ISSUE THREAD

**Issue by mixinboy** [neolee/pilot#1362]
图片：

![13](https://user-images.githubusercontent.com/54926768/87054314-8cd44c00-c235-11ea-89dc-75cee78f939a.png)

烦请老师讲解一下这是什么情况。

**Comment by neolee** [comment]
你的操作完全没问题，问题就是下载 Python 安装包的时候网络断了，3% 就断了，所以下载下来的不完整，检查下载包的 hash（你可以理解为检查下载文件的完整性的一种测试）失败，于是就没装成功。

简单说，还是网络问题。
