### ISSUE TITLE
逻辑判断与分支作业第三题type()函数定义出错，如何处理？

### ISSUE THREAD

**Issue by huandoudou** [neolee/pilot#1364]
![image](https://user-images.githubusercontent.com/53413051/87219944-2dd81980-c392-11ea-9348-a39b66d16875.png)

**Comment by neolee** [comment]
你为啥要发两个一样的问题啊？而且你为啥不在 wop-community 提问呢？

你定义 `type_0` 函数的那个单元格每执行呀，那个格子前面的 [] 里都空着，Python 当然不认识这个函数了……
