### ISSUE TITLE
对话机器人示例代码运行错误

### ISSUE THREAD

**Issue by doriawq** [neolee/pilot#1367]
除了名字和老师的不一样，不知道哪里有问题

![1594644961(1)](https://user-images.githubusercontent.com/51192376/87307697-a2ef4e80-c54c-11ea-85b0-1b426c4ee271.png)

**Comment by neolee** [comment]
你的类名和创建的对象实例名重合了，你肯定之前执行了 `Doria = Doria(1)`，这样 `Doria` 这个名字就变成了一个普通的变量名字，不再是类名，也无法用它来创建新的对象了。
