### ISSUE TITLE
运行一行命令后前面显示为[*]，我自己搞定了

### ISSUE THREAD

**Issue by Will-Maxx** [neolee/pilot#1368]
count = 0
while count < 5:
    print(count)
    count += 1
    
print('loop ends.')

这行代码写完后，为了好玩，我改成count += 0 ，想看看有什么效果，结果就一直在print 0，然后我就改回count += 1，随后就前面就显示为[*]，无法执行了。后来发现左下角成了unkown状态，点击重连就ok了。哈哈

**Comment by Createitv** [comment]
```python3
count = 0
while count < 5:
    print(count)
    count += 1

print('loop ends.')
```
 @可以使用markdown引用代码块效果是这样的，看起来更好

**Comment by Will-Maxx** [comment]
> ```python
> count = 0
> while count < 5:
>     print(count)
>     count += 1
> 
> print('loop ends.')
> ```
> 
> @可以使用markdown引用代码块效果是这样的，看起来更好

收到，感谢感谢
