### ISSUE TITLE
运行"scoop update"失败

### ISSUE THREAD

**Issue by jianchi-wys** [neolee/pilot#137]
系统是Windows7，运行"scoop update"失败，进而运行命令“scoop install python37@3.7.4”也失败。
![image](https://user-images.githubusercontent.com/48576650/67631932-cea3a900-f8d7-11e9-92bf-8f57bbd1b56f.png)

**Comment by neolee** [comment]
按照指南操作时，千万注意，前一步没有成功不要（不必）继续。

你的问题出在第一步，scoop update 失败，原因是网络问题。可以稍晚再试，如果可能换个网络或者挂代理试试。

**Comment by jarodlong** [comment]
> 按照指南操作时，千万注意，前一步没有成功不要（不必）继续。
> 
> 你的问题出在第一步，scoop update 失败，原因是网络问题。可以稍晚再试，如果可能换个网络或者挂代理试试。

老师我使用代理也无法更新，提示也是一样的，换了日本的和香港的也是上面的提示，删除SCOOP 2次了，都是因为scoop update这里出错，然后整个程序不可用，然后再重新装，有可以直接下载安装的EXE文件吗？

**Comment by jarodlong** [comment]
![image](https://user-images.githubusercontent.com/54735562/67635283-09b9d280-f900-11e9-9528-950ae7327e2e.png)

**Comment by neolee** [comment]
前面是 OK 了，现在就是卡在 scoop update 了。建议继续尝试别的网络或者代理/VPN。

**Comment by jarodlong** [comment]
![image](https://user-images.githubusercontent.com/54735562/67635827-9fa42c00-f905-11e9-84d9-5ed5c7687280.png)
![image](https://user-images.githubusercontent.com/54735562/67635837-ac288480-f905-11e9-961f-20600c0e4b2f.png)
现在不能更新的减少了，但是我通过网页是可以访问这个地址的

> 前面是 OK 了，现在就是卡在 scoop update 了。建议继续尝试别的网络或者代理/VPN。

![image](https://user-images.githubusercontent.com/54735562/67635847-c95d5300-f905-11e9-95c0-d12f70ef092b.png)

**Comment by jarodlong** [comment]
![image](https://user-images.githubusercontent.com/54735562/67636107-fd397800-f907-11e9-9f00-045d738a3587.png)
这个命令可以解决问题吗？

**Comment by jarodlong** [comment]
昨天下午和晚上都无法使用scoop update 连接失败，可能是因为那个时候去国外的人太多，有拥堵，今天早上一下就更新了，所以时间最好选择在早上。

git config --global http.postBuffer 524288000  #可以增加缓存试试
#考虑可能原因2：网络下载速度缓慢
#解决方法：命令行输入
git config --global http.lowSpeedLimit 0  
git config --global http.lowSpeedTime 999999

**Comment by huozhebuhao** [comment]
![image](https://github.com/neolee/pilot/assets/79900170/4f44c679-29e9-4397-ad19-fc61cdfd7d2b)
![image](https://github.com/neolee/pilot/assets/79900170/34a491a8-dc39-42fe-ae5a-a6ef4efafa98)
大佬们，这个怎么解决啊
