### ISSUE TITLE
requests.post() 调用显示 SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by zanglei-80** [neolee/pilot#1371]
练习了一个制作钉钉机器人自动提示的程序，显示SyntaxError: invalid syntax，标点也用了英文输入法，空格也删了，还是无法解决。
![dingding](https://user-images.githubusercontent.com/60951614/87507816-9da31880-c6a0-11ea-90f4-4962c4629f58.PNG)

**Comment by neolee** [comment]
`requests.post()` 函数里的 `headers` 参数是个 dict 类型的值，你的 `headers` 变量赋值那句明显不对呀，你仔细看看，那个字符串值写的不对。
