### ISSUE TITLE
Mac 环境配置验证 python 版本

### ISSUE THREAD

**Issue by ray-zheng** [neolee/pilot#1375]
<img width="1792" alt="Screen Shot 2020-07-18 at 9 49 21 AM" src="https://user-images.githubusercontent.com/48572098/87842037-13df8f00-c8dc-11ea-9db0-e3935eb25fdd.png">
老师，git 和 python安装完成后，查询python3的版本结果出现了这么多东西，是怎么回事？

**Comment by neolee** [comment]
命令输错了呗，最后的 V 要大写。

**Comment by ray-zheng** [comment]
哦哦，原来是这样，谢谢老师
