### ISSUE TITLE
在 jupyter lab 里做完作业保存不到原作业文件

### ISSUE THREAD

**Issue by jszrli** [neolee/pilot#1377]
请问下老师，我下载作业后，上传到jupyter lab里做完作业，单击保存后发现我的作业原文件还是空的（没有做过的），请问是什么原因，是我哪里操作不对么

**Comment by neolee** [comment]
“上传到” Jupyter Lab 是啥意思呀？不是应该把下载好的作业文件放到一个目录里然后进入该目录运行 `juoyter lab` 吗？

可能需要更多信息才能判断，比如运行 `jupyter lab` 的命令行和浏览器窗口截图。

**Comment by jszrli** [comment]
我是先把作业下载到桌面，然后在命令行里运行jupyter lab在打开的jupyter lab在里面点击上传按钮，选择桌面路径作业文件打开做作业。做完以后点击保存，然后我重新打开作业发现还是原始文件（没有做过的）。
我估计上传的作业也是空的没做过的，所以今天特意打开看了下发现就是空的，稍等我上传下命令行和浏览器窗口截图

**Comment by jszrli** [comment]
![jupyter lab的浏览器界面截图](https://user-images.githubusercontent.com/50977728/87843952-1b5a6480-c8eb-11ea-9fc9-320eb3e8ad79.png)
![命令行界面的截图](https://user-images.githubusercontent.com/50977728/87843962-257c6300-c8eb-11ea-9fc0-277b0a2f7c6b.png)
zhe'ge'shi这个是命令行和浏览器截图

**Comment by neolee** [comment]
选上传的话，你在 Jupyter Lab 里编辑的就是上传到 Lab 服务端的文件，不是你放在桌面的文件。

既然不太清楚这里面的原理，还是老老实实按照课程指南来操作为好，自己创新是要有基础的。

**Comment by jszrli** [comment]
我没有想创新，就是简单的想把做完的作业保存好上传到课程里
我是想求教该怎么把做完的作业成功传上去，但是我找不到做完的作业去哪里了，我再看看课程指南吧，谢谢老师的时间

**Comment by neolee** [comment]
就是我前面说的呀，把下载的作业文件放到一个目录里（还可以改个名字便于记忆和处理），然后命令行进入该目录，执行 `jupyter lab`。

**Comment by neolee** [comment]
我说的指南是课程配套资源里的“如何使用配套学习用书”。

另外你为啥把问题发在这里啊？应该发到 https://github.com/neolee/wop-community/issues 啊。

**Comment by jszrli** [comment]
明白了，谢谢老师
