### ISSUE TITLE
运行 scoop checkup 后执行建议命令出错

### ISSUE THREAD

**Issue by kelvinqy** [neolee/pilot#138]
![1572167330(1)](https://user-images.githubusercontent.com/52500863/67632294-9357a900-f8dc-11e9-9484-b1b87fffe9d5.png)

**Comment by neolee** [comment]
你按照 checkup 的提示操作，是正确的，但是你的登录账号可能权限不够，禁止执行，这是个隐患，但并不一定有问题。你可以先搞定 checkup 的另外几个提示，也就是安装几个重要的包：

```powershell
scoop install 7zip-zstd innounp dark
```

然后按照配置指南的说明继续，如果 scoop update 和后面安装 Python 没问题，就不用管前面的问题了。

如果遇到问题，有同学的解决方案是：在 ConEmu 中打开一个 {{ PowerShell (Admin) }} 界面，然后在里面运行你前面执行失败的那行命令，然后再继续。你也可以试试。

**Comment by kelvinqy** [comment]
收到，谢谢老师详细解答。目前git的安装速度超级慢，应该是网络问题，是不是需要用代理？

**Comment by neolee** [comment]
如果很慢最好开代理试试。
