### ISSUE TITLE
JupyterLab 和 nteract 中无法运行代码

### ISSUE THREAD

**Issue by zanglei-80** [neolee/pilot#1382]
做作业时nteract中的代码都不能运行了，换了jupyterLab也是不能运行，在单元格前不是出现数字而是出现了“*”，选的是code，运行时就跳到了Markdown。
![issue](https://user-images.githubusercontent.com/60951614/88264064-b7c2a380-ccfd-11ea-91a9-a625e91b265a.PNG)

**Comment by neolee** [comment]
Jupyter Lab 里出现 [*] 就代表这个 notebook 背后的 kernel（Python 解释器）正在运行，还没运行完，这一般有几种可能性：

1. 执行了非常耗时的程序，甚至是死循环；
2. 执行了 input() 这样需要用户输入的函数，还没有完成输入，所以解释器在等待；
3. 解释器出现异常而不工作了（这时候你运行 `jupyter lab` 的命令行窗口通常会有错误提示）。

仅根据截图无法判断你到底遇到了什么情况，可以考虑选择菜单 'Kernel - Restart Kernel and Clear All Outputs' 来重置 kernel，再按照正确顺序一个一个执行代码单元格，一个没完全执行完不要动下一个，这样比较容易定位哪里有问题。

**Comment by zanglei-80** [comment]
按照老师回复说的方法操作了，重置以后第一个大约过了三秒中运行了，第二个代码格（就是我问题中给你发的图片的第二个需要自己运行的代码格）我就是运行了一次再没动，等了十分钟也没反应。在第一次用nteract写完程序时第二个代码格一直到构建父类以上的代码是能很快就正确运行的。就是写到构建公共父类的代码格就不能运行了，后来我就保存退出，再打开上面的代码也不能运行了。

**Comment by neolee** [comment]
老实说，你上面这段话我不太能理解……可以再整理下思路吗？然后提供几个截图说明下？另外你执行 `jupyter lab` 的命令行窗口里有什么提示？

我前面也说了，一件事一件事处理，遇到问题停下来搞清楚解决掉再继续。

**Comment by zanglei-80** [comment]
老师我就是说的同一个问题，郁闷啊！就是我用nteract写的第五次作业，运行到“构建父类”那时代码不动了，我就保存了已经写完的，想用jupyterlab打开已经保存的文件，看看是不是nteract的问题，结果还是不运行，既不报错也不运行，只在[ ]中出现了“*”字符，我就向您提问，您回复了我在jupyter中的解决办法，我认为两个软件在这个作业的运行原理应该是一样的，就先在nteract试了一下你给的解决方案，重置以后我就开始运行第一个自己写的代码格，可以运行，但是到第二个就不动了，您不是说让我一个一个运行，直到运行了再进行下一个的运行吗，第二个就不运行了，我也就没做别的操作，就给做了第二次提问（这次算第三次），不知道我说明白了没有，哈哈哈哈

![捕获1](https://user-images.githubusercontent.com/60951614/88454459-7f0fff00-cea2-11ea-8ff9-c430658e73a6.PNG)
![捕获2](https://user-images.githubusercontent.com/60951614/88454463-82a38600-cea2-11ea-8383-26c381830bbf.PNG)

**Comment by neolee** [comment]
看你截图，你没有在输入框里输入并回车吧？那些输入框都是空的，那 `input()` 这个函数确实就没执行完啊，在等你输入啊，也就是我前面说的第2中情况。

**Comment by zanglei-80** [comment]
我觉得是我的文件出问题了，我把文件删了重新下了又来了一遍，问题就解决了，谢谢老师。
