### ISSUE TITLE
myutil.py 路径相关问题

### ISSUE THREAD

**Issue by SZZ0722** [neolee/pilot#1385]
![image](https://user-images.githubusercontent.com/67678671/88406150-da8ab000-ce02-11ea-80ae-637a4a989b11.png)
请问老师我的路径该怎么写才能不报错？谢谢

**Comment by neolee** [comment]
你要搞清楚你的这个 notebook 在哪里，然后 myutil.py 和它放在一起，就不需要写 `sys.path.append()` 那句，直接就可以用啦。
