### ISSUE TITLE
fastnumbers 模块已安装，作业时提示没有此模块

### ISSUE THREAD

**Issue by SZZ0722** [neolee/pilot#1388]
![image](https://user-images.githubusercontent.com/67678671/88987937-0a0d5100-d30a-11ea-9a4d-8e18986a347d.png)

**Comment by SZZ0722** [comment]
![image](https://user-images.githubusercontent.com/67678671/88988745-53f73680-d30c-11ea-9218-227de48f2e09.png)

**Comment by neolee** [comment]
前面的截图说明你的 notebook kernel 不是你安装 fastnumbers 的那个 Python 环境，并且你的环境也不是按照课程提供的环境配置指南准备的。
