### ISSUE TITLE
执行 python -V 命令，没有任何结果

### ISSUE THREAD

**Issue by bright-xuexi** [neolee/pilot#139]
python37@3.7.4安装成功，但执行 python -V 命令，没有任何结果，见下图：
![install python](https://user-images.githubusercontent.com/36670984/67632409-ce0e1100-f8dd-11e9-946f-3bce90c09427.jpg)
![python -V](https://user-images.githubusercontent.com/36670984/67632378-71125b00-f8dd-11e9-9cd0-fe657f031bfa.jpg)

**Comment by neolee** [comment]
运行 scoop list 和 Get-Command python 两个命令看看。

**Comment by bright-xuexi** [comment]
运行 scoop list 和 Get-Command python 两个命令，如下图：
![Get-Command python](https://user-images.githubusercontent.com/36670984/67632803-6b1f7880-f8e3-11e9-80cb-768cd3b5f6ab.jpg)

**Comment by wangbingfeng** [comment]
在cmd上执行看一下结果

**Comment by neolee** [comment]
试试：

```powershell
C:\Users\Administrator\scoop\shims\python.exe -V
```

**Comment by bright-xuexi** [comment]
问题解决了，Windows系统中 api-ms-win-crt-process-l1-1-0.dll 文件丢失，安装此文件之后就OK啦。
![Get-Command python 1](https://user-images.githubusercontent.com/36670984/67634082-9b224800-f8f2-11e9-82e4-76b44527ff11.jpg)

**Comment by neolee** [comment]
Nice!

**Comment by tangwendong** [comment]
> 问题解决了，Windows系统中 api-ms-win-crt-process-l1-1-0.dll 文件丢失，安装此文件之后就OK啦。
> ![Get-Command python 1](https://user-images.githubusercontent.com/36670984/67634082-9b224800-f8f2-11e9-82e4-76b44527ff11.jpg)

我也遇到这个问题，请教一下：我在网上下载了这个缺失的dll文件，粘贴到C:\Users\Tang\scoop\shims这个文件夹，还是不行？应该如何操作的？需要重新安装Python？

**Comment by neolee** [comment]
@tangwendong 下载的文件应该放到 Windows 的系统目录下，具体说：
* 如果你的 Windows 是 32 bit 版本：你需要下载那个 DLL 的 32 bit 版本，放到 C:\Windows\System32
* 如果你的 Windows 是 64 bit 版本：
  * 如果你下载的 DLL 是 32 bit 版本：放到 C:\Windows\SysWOW64
  * 如果你下载的 DLL 是 64 bit 版本：放到 C:\Windows\System32
