### ISSUE TITLE
scoop update 失败怎么办？

### ISSUE THREAD

**Issue by Jacob-Xujibin** [neolee/pilot#1395]
我是才加入践行群没多久的新成员，目前正在听回放学习之前的课程，按照指引配置编程环境时，安装好scoop和git后，在执行scoop update时总是失败，提示超时，我想跳过安装Python也不行，请问有什么解决方法吗？
![image](https://user-images.githubusercontent.com/69385649/92718478-77de7b00-f394-11ea-941f-e1ec9cbe11a5.png)

**Comment by neolee** [comment]
网络问题。

可以先参考这个页面最后一部分的指引做一些配置试试：

https://github.com/neolee/wop-community

如果还不行可能需要换网络或者使用代理服务。

**Comment by Jacob-Xujibin** [comment]
这个方案是可行的，按照指引，找到了本机访问github.com的IP是140.82.114.3，也可以Ping到，添加到hosts文件后，已经可以进行scoop update和后续操作了，感谢李骏老师及时帮助！
