### ISSUE TITLE
Clone or download 按钮在哪里？

### ISSUE THREAD

**Issue by Jacob-Xujibin** [neolee/pilot#1396]
指引里说：在这个新的 repo 的首页上有个绿色的 Clone or download 按钮，点击它会打开一个小的下拉显示，里面有个文本框写有这个 repo 的访问地址，点击它右边的小按钮将其拷贝到系统剪贴板（后面会用）。

但我的界面里找不到，会是github改版升级调整路径了吗？求助，如图是我的界面看到的

![image](https://user-images.githubusercontent.com/69385649/92719534-dc4e0a00-f395-11ea-98bf-8b0d9a3de44e.png)

![image](https://user-images.githubusercontent.com/69385649/92719577-ef60da00-f395-11ea-93f0-19bfae0e6937.png)

**Comment by neolee** [comment]
是的，GitHub 改版之后文字变了，就是那个 Code 的绿色按钮。

**Comment by Jacob-Xujibin** [comment]
找到按钮和地址了，问题解决了，谢谢李骏老师！
