### ISSUE TITLE
安装 Python 的过程失败

### ISSUE THREAD

**Issue by Jacob-Xujibin** [neolee/pilot#1398]
配置学习环境过程中，到了scoop install python37@3.7.4环节，总是到百分之十几的进度时失败，提示py3.exe is not valid.我看之前还提示警告Given version(3.7.4) does not match manifest (3.7.9)，于是也试着输入scoop install python37@3.7.9，不过还是同样失败了，请教应该怎么解决？
![image](https://user-images.githubusercontent.com/69385649/92991810-ccaafe80-f518-11ea-859a-8084fabae58a.png)
![image](https://user-images.githubusercontent.com/69385649/92991826-d59bd000-f518-11ea-9fd0-e84b51e5bc74.png)

**Comment by neolee** [comment]
网络不稳定，换个网络或者使用代理服务试试。

或者到 Python 官网下载 3.7.x 版本的安装包安装也是可以的。

**Comment by Jacob-Xujibin** [comment]
我在官网下载安装了3.7.9，后面在scoop install busybox的过程中也失败了，所以也在网上找了个busybox.exe，不过双击后屏幕闪了下界面就消失了，不知道是否正常？
现在ConEmu的操作界面下查看Python的版本，以及list命令都找不到Python和busybox，不知道会不会影响后面的使用？
不过后面安装VisioCode以及生成hello.py文件都是可以操作的，我这样算是成功完成配置，可以后面的正常学习了吗？
![image](https://user-images.githubusercontent.com/69385649/93012627-7d2a0880-f5d4-11ea-8a28-26e402b5ab11.png)
![image](https://user-images.githubusercontent.com/69385649/93012670-b95d6900-f5d4-11ea-90f8-829d5d41d5cf.png)

**Comment by neolee** [comment]
busybox 不是必需，先跟着课程学起来吧。

**Comment by Jacob-Xujibin** [comment]
好的，谢谢。
