### ISSUE TITLE
无法commit

### ISSUE THREAD

**Issue by yayuehuizi** [neolee/pilot#14]
建立跟踪以后，git commit时显示“终止提交因为提交说明为空。”
代码如下：

xman-2:learn-git xman$ git status
位于分支 master

尚无提交

未跟踪的文件:
  （使用 "git add <文件>..." 以包含要提交的内容）
	README.md

提交为空，但是存在尚未跟踪的文件（使用 "git add" 建立跟踪）
xman-2:learn-git xman$ git add README.md
xman-2:learn-git xman$ git status
位于分支 master

尚无提交

要提交的变更：
  （使用 "git rm --cached <文件>..." 以取消暂存）
	新文件：   README.md

xman-2:learn-git xman$ git commit
终止提交因为提交说明为空。

**Comment by neolee** [comment]
Duplicate of #13
