### ISSUE TITLE
苹果系统下无法下载 homebrew

### ISSUE THREAD

**Issue by KirstenJun** [neolee/pilot#140]
李老师，我下载了很多次，换了好几个wifi环境，依然出现下面的情况。一般下载到7%左右就跳了。

Press RETURN to continue or any other key to abort
==> Downloading and installing Homebrew...

remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (7/7), done.
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
Failed during: git fetch origin master:refs/remotes/origin/master --tags --force
KirstendeAir:~ kirstenlu$ 

请问老师，有没有什么解决方法哈？

**Comment by neolee** [comment]
网络的问题，需要换网络或者挂代理试试，还有其他一些办法（比如用国内的 Homebrew 镜像），可以搜索下其他 issue 看看。

p.s. 例如这个 https://www.jianshu.com/p/6523d3eee50d
