### ISSUE TITLE
Jupyter Lab 运行不成功

### ISSUE THREAD

**Issue by Totie-O** [neolee/pilot#1401]
已经下载好了jupyter（pip install jupyterlab）
![图片](https://user-images.githubusercontent.com/53247740/93708991-538d5600-fb6d-11ea-9a7d-e206f9c6571e.png)

但是运行不成功
![图片](https://user-images.githubusercontent.com/53247740/93708965-2a6cc580-fb6d-11ea-89b8-1b2b8df2577a.png)

**Comment by neolee** [comment]
应该是 Jupyter Lab 没装好，安装过程有什么出错信息么？

**Comment by Totie-O** [comment]
jupyter安装了，看了老师的在哔哩哔哩的jupyter安装课程,没问题了
https://www.bilibili.com/video/BV17E411C7bv
