### ISSUE TITLE
如何 fork 学习用书？教材已经 fork

### ISSUE THREAD

**Issue by zhuzhaoli1980** [neolee/pilot#1405]
<img width="1024" alt="2020-10-07 下午10 12 32" src="https://user-images.githubusercontent.com/53135670/95343443-1ce46900-08eb-11eb-9698-4c5c202f3db3.png">

**Comment by neolee** [comment]
教材不需要 fork，在线看就可以，直接 clone 会本地看也没问题——反正你不需要去改教材。

既然教材已经 fork，那学习用书的 fork 一样办法啊，有啥问题灭？
