### ISSUE TITLE
macOS 的双显示屏

### ISSUE THREAD

**Issue by zhuzhaoli1980** [neolee/pilot#1406]
显示器双屏如何能够互不影响？想边看边写，可是一个屏幕改变内容另一个屏幕也在变，或者是一个屏幕显示另一个屏幕没有要显示的内容。

<img width="1024" alt="屏幕快照 2020-10-10 下午7 46 59" src="https://user-images.githubusercontent.com/53135670/95655653-717e2300-0b3b-11eb-9593-0ba0a7ef3851.png">

**Comment by neolee** [comment]
这个问题好像和课程没啥关系。

不过你要找的配置在系统设置下面的 Display（显示）里面，当你有两个显示屏的时候，Display 设置里会有一个 tab 叫 Arrangement（排列？）。
