### ISSUE TITLE
爬虫爬取小说链接为何只出现一个？

### ISSUE THREAD

**Issue by Totie-O** [neolee/pilot#1407]
![image](https://user-images.githubusercontent.com/53247740/96588539-59b25600-1316-11eb-90b4-ba92a4e6dad2.png)
我自己写的代码如下
![image](https://user-images.githubusercontent.com/53247740/96588621-76e72480-1316-11eb-9914-1111a4160d76.png)
但我返回的只有一个链接，想不清楚，希望给一点提示

**Comment by neolee** [comment]
你应该用 `find_all('dd')` ，在循环体里再取下面的 `a` 标签（想想为什么）。

**Comment by Totie-O** [comment]
感谢李骏老师，修改了。
![image](https://user-images.githubusercontent.com/53247740/96607756-41990180-132b-11eb-8008-85f279254f36.png)
