### ISSUE TITLE
机器人 from termcolor import colored 出现乱码

### ISSUE THREAD

**Issue by Totie-O** [neolee/pilot#1409]
安装完termcolor第三方库，
运行from termcolor import colored，
```python
def _say(self, s):
    time.sleep(self.wait)
    print(color(s, "blue"))
```
![image](https://user-images.githubusercontent.com/53247740/97377246-8d831200-18fa-11eb-82b3-e8d4085dc71a.png)
个人测试是因为**print(color(s, "blue"))**的问题，不打这句话不会出现下面这种情况。
![image](https://user-images.githubusercontent.com/53247740/97377413-ece12200-18fa-11eb-8c42-e57228c35de2.png)

**Comment by neolee** [comment]
换 ConEmu 或者 Windows Terminal 运行程序 `python bot.py` 试试？

**Comment by Totie-O** [comment]
奇怪了，在conemu可以打开
![image](https://user-images.githubusercontent.com/53247740/97381638-734e3180-1904-11eb-8f12-2ad5c8214888.png)
在vscode里面还是继续乱码
![image](https://user-images.githubusercontent.com/53247740/97381704-9c6ec200-1904-11eb-9300-e336afef558b.png)
bu'zhi'dao不知道咋解

**Comment by neolee** [comment]
你在 VS Code 里打开的终端需要设置为 powershell 终端才可以——请自行探索如何设置，如果实在搞不定可以先用 ConEmu 来运行程序，也挺好。

**Comment by Totie-O** [comment]
我记起来了，谢谢老师
