### ISSUE TITLE
打开学习用书时，到开启浏览器后没有了反应

### ISSUE THREAD

**Issue by liu-liang518** [neolee/pilot#141]

**Comment by neolee** [comment]
老版的 IE 不行，你需要使用 Microsoft Edge 或者其他较新的浏览器。

从命令行里把 http://localhost: 打头的一行 copy 下来，粘到浏览器地址栏。

**Comment by liu-liang518** [comment]
老师你好，怎样用谷歌浏览器？

**Comment by neolee** [comment]
如果你不知道怎么用就最好不用，用 Windows 10 自带的 Microsoft Edge 比较保险。
