### ISSUE TITLE
兰顿蚂蚁代码用 Python 运行语法错误？

### ISSUE THREAD

**Issue by chendong0** [neolee/pilot#1415]
![QQ截图20201109125320](https://user-images.githubusercontent.com/40737674/98501628-c15f1f80-228a-11eb-8747-28ae01c7fa18.jpg)
一、  File "<ipython-input-10-3c0fbd833d7f>", line 19
    print "Step %d" % (k + 1)
                  ^
SyntaxError: invalid syntax
此语法错误，一直搜索，找不到原因？使用在线python时，可以运行，单用jupyter或者powershell时，就是print "Step %d" % (k + 1)  同一个语法错误。

**Comment by neolee** [comment]
你这程序和课程有什么关系？

课程是基于 Python 3，你这里贴出来的代码一看就是 2 的。

**Comment by chendong0** [comment]
一、python 2 已更改为python 3。谢谢老师。
import os
import random
import time

periods = 11000
m = 60
n = 102
cells = [[0] * n for i in range(m)]

# 0 -x, 1 +y, 2 +x, 3 -y
direct = random.randint(0, 3)
cells = [[0] * n for i in range(m)]
i = random.randint(0, m - 1)
j = random.randint(0, n - 1)
cells[i][j] = 1

for k in range(periods):
	os.system('clear')
	print("Step %d" % (k + 1))
	if cells[i][j] == 1:
		direct = (direct - 1) % 4
		cells[i][j] = 0
	else:
		direct = (direct + 1) % 4
		cells[i][j] = 1
	if direct == 0:
		j = (j - 1) % n
	elif direct == 1:
		i = (i - 1) % m
	elif direct == 2:
		j = (j + 1) % n
	else:
		i = (i + 1) % m
	for x in range(m):
		for y in range(n):
			if cells[x][y] == 1:
				print('*', end=' ')
			else:
				print(' ', end=' ')
		print()
	time.sleep(0.05)
