### ISSUE TITLE
安装 SCOOP 后执行命令的时候无法使用

### ISSUE THREAD

**Issue by jarodlong** [neolee/pilot#142]
![image](https://user-images.githubusercontent.com/54735562/67633616-f5200f00-f8ec-11e9-9ed7-42e84969fb8d.png)
以前装过笑来老师的那个集成PYTHON包，现在卸载了，但是现在SCOOP无法使用。

**Comment by neolee** [comment]
退出 PowerShell 重进再试试 scoop checkup 和 scoop update。

如果还有问题考虑重新安装 Scoop，点击这个页面上方的 Wiki，按照“重新安装 Scoop”操作。

**Comment by jarodlong** [comment]
我删除了SCOOP  del .\scoop -force,希望这次关闭以后还可以使用命令。
