### ISSUE TITLE
用 code 命令打开 VSCode 失败

### ISSUE THREAD

**Issue by huangchangling800** [neolee/pilot#1421]
![image](https://user-images.githubusercontent.com/61343620/100194034-eb257100-2f2f-11eb-9872-027513e661d8.png)
![image](https://user-images.githubusercontent.com/61343620/100194149-232cb400-2f30-11eb-9cb5-cbc847c0f572.png)

**Comment by neolee** [comment]
为什么要反复提一样的问题？？

Duplicate of #1420

**Comment by huangchangling800** [comment]
应该是VSCODE没有添加环境变量的问题，但如何添加VSCode的环境变量，支线课程里也没有答案。
