### ISSUE TITLE
Python 内置函数为 True 而自己创造的函数返回 False?

### ISSUE THREAD

**Issue by CHANCYstone** [neolee/pilot#1423]
![image](https://user-images.githubusercontent.com/71212547/100536224-170b6400-325a-11eb-9c94-4bd35abec4ca.png)

![image](https://user-images.githubusercontent.com/71212547/100536344-f4c61600-325a-11eb-8b54-fc854b7e20e9.png)
这是我创造的函数
在复习，万物皆为布尔型中发现，自己创造的函数（返回值不是bool型的）似乎一律被判为错.

而且自己的函数返回值还被打印了出来
那么第一个运算：c_type(0)  return int
理论上 bool(int)应该也是False才对，可是，却意外的发现返回了True.

**Comment by neolee** [comment]
你的 `c_type()` 函数没有显式的返回值，按照 Python 的策略等于返回了一个 `None`，会被视为 `False`。

**Comment by CHANCYstone** [comment]
多谢老师解答
自己另做了一个验证如下：
![image](https://user-images.githubusercontent.com/71212547/100542383-826a2b80-3284-11eb-9199-9b76e878d9df.png)
