### ISSUE TITLE
学习问题——关于边学边忘

### ISSUE THREAD

**Issue by Totie-O** [neolee/pilot#1424]
老师，你好，想咨询一下学习问题。我之前学了python第三方库——pandas，记住了里面的基本操作，最近学习了sql,里面的基本操作，入门很简单，就是pandas里面的基本操作有一些遗忘了，我是需要重新回顾吗？还是需要用到的时候再学？有没有比较好的方法解决这个遗忘问题——之前所学知识点？

**Comment by neolee** [comment]
关键是要用，不用的东西很快就会忘掉。

记住，编程这事儿的一多半是手艺。
