### ISSUE TITLE
为什么类定义中的初始方法调用不需要加括号而调用对象实例方法需要加括号？

### ISSUE THREAD

**Issue by BensonHoll** [neolee/pilot#1426]
![image](https://user-images.githubusercontent.com/51362187/105463120-90f42280-5cca-11eb-967c-06d82871b53a.png)

**Comment by neolee** [comment]
`name` 不是方法，是属性，说白了就是个变量；

`bark` 是方法，说白了就是个函数，函数也是对象（变量），不带括号就是这个函数对象，后面加上括号就是调用这个函数。
