### ISSUE TITLE
第一次安装 scoop 遇到问题

### ISSUE THREAD

**Issue by qywhy1116** [neolee/pilot#1429]
各位老师，今天刚开始学习李骏老师的编程课，在进行到scoop安装出现的下面代码是什么意思呢，还有作为新人怎么去读懂“错误提示”呢，望各位老师不吝赐教，谢谢

PS C:\Users\wooyihe> iwr -useb get.scoop.sh | iex
iwr : 未能解析此远程名称: 'raw.githubusercontent.com'
所在位置 行:1 字符: 1
+ iwr -useb get.scoop.sh | iex
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest]，WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

**Comment by neolee** [comment]
参考这个页面最下面的解决方案：

https://github.com/neolee/wop-community

p.s. 你问了一个好问题：作为新人怎么去读懂“错误提示”。

这需要积累经验，怎么积累呢？可以这么起步：找到错误提示里你看得懂或者大致明白一点的关键词，然后去搜搜这个关键词，或者用来提问，通过搜素或者提问理解该关键词之后记住，下次就有经验了。比如你这个问题里的关键词有两个：“未能解析此远程名称”和“raw.githubusercontent.com”，后者是个域名，搜索下就会知道这是属于 GitHub 用来存放文件的域名；前者比较晦涩，其实是和互联网域名解析有关，类似“raw.githubusercontent.com”这样的域名就好比互联网上的门牌号码，无法解析就是指找不到这个门牌号码在哪里，也就没法从这个域名对应的服务下载我们需要的文件。

**Comment by qywhy1116** [comment]
谢谢老师的详细解答，很受用！
