### ISSUE TITLE
请问强迫关闭连接，是因为没有网络了吗

### ISSUE THREAD

**Issue by Miss-sun-moon** [neolee/pilot#143]
PS C:\Users\春起苗子> scoop install git
Scoop uses Git to update itself. Run 'scoop install git' and try again.
Installing 'git' (2.23.0.windows.1) [64bit]
PortableGit-2.23.0-64-bit.7z.exe (41.5 MB) [============================================================================>                                                            ]  56%
无法从传输连接中读取数据: 远程主机强迫关闭了一个现有的连接。。
URL https://github.com/git-for-windows/git/releases/download/v2.23.0.windows.1/PortableGit-2.23.0-64-bit.7z.exe#/dl.7z is not valid

之前试过好多次，还有说操作超时，

**Comment by neolee** [comment]
网络问题，已经有不少类似的 issue，你可以搜索下。

换网络或者挂代理，或者有些其他 issue 里同学成功的方案。
