### ISSUE TITLE
在定义可以生成素数的迭代器和生成器的参考答案中，这段代码什么意思？

### ISSUE THREAD

**Issue by zjlditto** [neolee/pilot#1439]
from math import sqrt
from itertools import islice

class primes:
    def __init__(self):
        self.next = 2

    def __iter__(self):
        return self

    def _is_prime(self, n):
        if n < 2:
            return False

        if n in (2, 3):
            return True

        for i in range(2, int(sqrt(n)) + 1):
            if n % i == 0:
                return False

        return True

    def __next__(self):
        n = self.next
        while not self._is_prime(n):
            n += 1

        self.next = n + 1
        return n

list(islice(primes(), 0, 10))
Out[12]:
[2, 3, 5, 7, 11, 13, 17, 19, 23, 29]

其中，以下这段代码：
    def __next__(self):
        n = self.next
        while not self._is_prime(n):
            n += 1
        self.next = n + 1
        return n

我看了很多遍，实在没有看懂。由于没看懂，导致后面做作业“...将上面这个 iterator 类改写为 generator 应该也不难，我们把这个作业留给你。”做不出来。 我觉得很难。有参考答案吗？
多谢各位高手指点一二~

**Comment by zjlditto** [comment]
我已改为：
from math import sqrt
from itertools import islice

def _is_prime(n):
    if n < 2:
        return False
        
    if n in (2, 3):
        return True
        
    for i in range(2, int(sqrt(n)) + 1):
        if n % i == 0:
            return False
        return True
        
def fob():
    n = 2
    while True:
        if _is_prime(n):
            yield n
        n += 1

f = fob()            
list(islice(f, 0, 10))
但结果是
[2, 3, 5, 7, 9, 11, 13, 15, 17, 19]
多了几个不是素数的答案。。。怎么回事？

**Comment by zjlditto** [comment]
问题解决了：
    for i in range(2, int(sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True
原来是 return True 的缩进错了。应该和for对齐的。和if对齐就错了。

**Comment by neolee** [comment]
先去这里学会在这里贴代码： https://github.com/neolee/wop-community

然后类似缩进的问题会更容易发现和解决。
