### ISSUE TITLE
Scoop Update Failed

### ISSUE THREAD

**Issue by eiyen** [neolee/pilot#1448]
### 问题

Scoop 更新失败：

![image](https://user-images.githubusercontent.com/52303623/114654374-a0f52e80-9d1c-11eb-8749-7a1814c520aa.png)

### 系统配置

Windows 10，PandaVPN（一款代理软件）

### 尝试排错

1. 网络问题

    按照之前的issue，推测是网络问题，但当我通过浏览器访问[报错的网址](https://github.com/lukesampson/scoop/)时，发现可以秒开。

2. 代理问题

    进一步推测，可能是因为浏览器能够走代理，但Scoop不行。

    所以，我修改并刷新了hosts（根据[这个网站](https://www.waite.top/266)，选择了访问Github延迟最低的IP，并修改和刷新了hosts），最后在关闭代理的情况下，重新执行`scoop update` ，并等待一段时间后，发现成功了！！！

    ![image](https://user-images.githubusercontent.com/52303623/114656732-31ce0900-9d21-11eb-9cf3-b9788368a870.png)

    P.S. 但中间还是会提示'Time out'，不知道是什么情况

### 结论

有些代理软件无法代理全部流量，哪怕是所谓全局模式。所以，这种情况下修改一下本地的host文件，就能成功更新sccop了。

**Comment by gaojie1201** [comment]
请问怎样修改host呢 您提供的超链接打不开了

**Comment by neolee** [comment]
> 请问怎样修改host呢 您提供的超链接打不开了

我有一个 guide，看这个网页最后一节： https://github.com/neolee/wop-community

**Comment by YQQC-19** [comment]
> > 请问怎样修改host呢 您提供的超链接打不开了
> 
> 我有一个指南，看这个网页最后一节： [https : / / github . com / neolee / - community](https://github.com/neolee/wop-community)

我用了 网络也刷新了好多次 就是不可以

**Comment by neolee** [comment]
Scoop 支持代理，可以搜索一下如何设置。
