### ISSUE TITLE
scoop 总安装不上

### ISSUE THREAD

**Issue by tianmiao831229** [neolee/pilot#1459]
scoop 总安装不上，各种方法尝试过了，请问如何解决呢？如果SCOOP 不能安装，能否有替代的软件，是否scoop 装不上就没办法继续进行呢？

![82d6f70c2d997cd12fb2f922cc51b3f](https://user-images.githubusercontent.com/40586247/128626890-1623ec37-08c2-48cc-be31-4e04aec93515.png)

**Comment by neolee** [comment]
不要重复发问，如果需要可以回复补充信息或者编辑原先的问题。

Duplicate of #1458
