### ISSUE TITLE
是未安装成功吧

### ISSUE THREAD

**Issue by ahui9** [neolee/pilot#146]
![360截图20191027194349998](https://user-images.githubusercontent.com/57027624/67634545-7b8e1e00-f8f8-11e9-95f6-a38fc05f56fd.jpg)

**Comment by Erika00** [comment]
是的

**Comment by ahui9** [comment]
![360截图20191026121307907](https://user-images.githubusercontent.com/57027624/67634585-fd7e4700-f8f8-11e9-8ac6-48abd962cdbe.jpg)
ConEmu安装后每次打开都报错是怎么回事

> 是的

请问是哪里出错了？
＃重复
