### ISSUE TITLE
support for password authentication was removed on august 13 2021. 

### ISSUE THREAD

**Issue by AndyZhou6688** [neolee/pilot#1460]
无法push修改内容到Git Hub，已生成Token，但在输入密码时无法粘贴Token到ConEmu命令行

**Comment by neolee** [comment]
git 会保存以前用过的密码，你需要把保存的密码删掉才能用新的 Personal Access Token 来登录，具体清除密码缓存的方法可以自己搜索下。

**Comment by AndyZhou6688** [comment]
收到，我再试试，谢谢老师！
