### ISSUE TITLE
清除git中缓存的账号密码后，仍无法使用Token将本地与远程git hub仓库连接

### ISSUE THREAD

**Issue by AndyZhou6688** [neolee/pilot#1461]
![1](https://user-images.githubusercontent.com/85618947/131244250-3dfd0262-0d61-44e5-9081-30b0c5da46f9.png)
第一步：用ConEmu进入本地learn-git目录
第二步：运行git config --global credential.helper wincred和git credential-manager uninstall清除缓存
第三步：运行git remote rm origin解决“remote origin already exists”的提示
第四步：运行git remote add origin https://github.com/AndyZhou6688/learn-git.git
git branch -M main
git push -u origin main关联本地和远程仓库
第五步：输入用户名
第六步：ConEmu提示输入密码，但是无法输入Git Hub的Token

**Comment by neolee** [comment]
可以输入的，只是系统为了安全在你输入的时候没有回显罢了，你把你的 token 贴上去就行。

> 第六步：ConEmu提示输入密码，但是无法输入Git Hub的Token

**Comment by AndyZhou6688** [comment]
搞定了，好开森，跟李老师学编程，简直太幸福啦~
