### ISSUE TITLE
python -v和pip -v后出现很多乱七八糟的东西

### ISSUE THREAD

**Issue by PATIEN** [neolee/pilot#147]
<img width="807" alt="001" src="https://user-images.githubusercontent.com/53363523/67634606-47ffc380-f8f9-11e9-84e9-85c01e5e021a.PNG">
<img width="943" alt="002" src="https://user-images.githubusercontent.com/53363523/67634611-54841c00-f8f9-11e9-9516-bf87e6060693.PNG">
<img width="815" alt="003" src="https://user-images.githubusercontent.com/53363523/67634614-5948d000-f8f9-11e9-8e28-4178c7d90102.PNG">

**Comment by neolee** [comment]
因为是 `python -V` 和 `pip -V`，大写的 V 不是小写的 v。
