### ISSUE TITLE
如何使用Python进行销售数据的智能分析？

### ISSUE THREAD

**Issue by AndyZhou6688** [neolee/pilot#1470]
李老师好，各位同学好，今天再次学习了李老师2019-11-28“学习问卷反馈及一些思考”的视频，想到：如果我能把工作中的数据分析表结合Python使用，不仅能促进我的编程学习，而且能够提升工作效率。下面我把工作中实际使用的数据分析表拿出来，结合使用过程中的问题，希望能有朋友提供具体的解决思路，也希望这个课题能帮助到和我一样从事销售行业的同学们。附件表格中的敏感信息已经处理过，大家可以随便玩，期待和大家一起完成这个课题。
1、背景：我的工作是负责两个4S店的销售管理，编程0基础。这里提供的附件是我每天都会用的一个Excel表，用它来观察每天的客流量和销售顾问的工作情况，但问题是这个表由于嵌套公式太多，每次打开以及更新都很卡，Excel显示有16个进程，公司的大部分电脑由于硬件老旧，无法运行这个表格，截图如下
![16线程](https://user-images.githubusercontent.com/85618947/136129139-dae1afd7-a297-44b5-ab2d-96d27e13392b.png)
2、课题
①这个表格是否可以通过Python进行优化，把Excel变成程序，实现更加轻量和高效的运行？
②当前Excel提供的数据分析结果多以列表形式呈现，通过学习课程了解到，这个Excel应该是可以通过图形呈现的，但是不知道如何操作。如果能够图像化，那么数据分析的结果将会更加直观。
③当前这个应用场景，是考虑用程序实现还是用网页实现？哪种方式更好？
3、附件介绍
①Excel中第一个工作表是在Excel中使用这个表格的方法以及各数据之间的逻辑关系；
②Excel中第二个工作表可以忽略，是用于打印的；
③Excel中第三个工作表是原始数据，靠人工录入每天的进店流量；
④Excel中第四个工作表“全店分析”是通过公式提取前面电子表的数据呈现的分析结果；
⑤Excel中第五个工作表“销售顾问战力”也是通过公式提取前面电子表的数据呈现的分析结果；
[9月展厅来店客户登记表-play.xlsx](https://github.com/neolee/pilot/files/7290447/9.-play.xlsx)

**Comment by neolee** [comment]
其实对不太复杂的数据进行分析和图形可视化展现，就在 Excel 里做是最简单方便的，不妨先用 Excel 的工具试试。

**Comment by AndyZhou6688** [comment]
明白啦，杀鸡不必用牛刀，感谢李老师解答~
