### ISSUE TITLE
前面已经引用了import random，运行出现错误提示：name 'random' is not defined

### ISSUE THREAD

**Issue by newzyb** [neolee/pilot#1471]
![捕获](https://user-images.githubusercontent.com/50261113/136895310-9b466e6f-5f9d-4cf9-b362-a42b4c0f3763.PNG)
老师，我在前面已经引用了import random，为什么运行时还出现错误提示：name 'random' is not defined？

**Comment by neolee** [comment]
仅看这段代码似乎没有问题，你可以这么试试：开一个新的 cell，在里面只写下面几行代码：

```python
import random

colors = ['red', 'orange', 'yellow', 'green', 'blue', 'indigo', 'purple']
random.choice(colors)
```

看看是什么输出。

另外你在命令行执行 python -V 是什么结果？

**Comment by newzyb** [comment]
测试了老师给的代码和执行命令的结果如下：

一、开了一个新的cell，是这样的结果。
![捕获](https://user-images.githubusercontent.com/50261113/137324988-d58b750b-71f7-4f8a-bfd1-ab34ffa34b13.PNG)

二、我在命令行执行 python -V ，输出的结果是这样的。
![捕获1](https://user-images.githubusercontent.com/50261113/137325105-891c531a-1725-4ce3-a277-5d8a13bac95a.PNG)

**Comment by neolee** [comment]
版本无问题。

新的 cell 里的代码运行成功，说明导入 `random` 库和运行里面的 `choice` 方法都无问题。

那么你的原来的程序应该是有别的问题，你可以把出错的那个代码在这里完整贴出来吗？

**Comment by newzyb** [comment]
老师，今天又经过我的几次测试发现了问题所在。代码是没有问题的，但是，写好之后立刻开始运行就会出现这种问题。如果等待一段时间后，再开始执行代码，这个问题就不会出现。看来是我电脑这方面的问题，我现在修改新的代码后，出现这种情况，就过会儿再测试。代码写的很正确，但就是运行出现问题这种情况困扰我有一段时间了，一直以为是写的代码错误造成的。比较神奇的是，现在运行正常了。谢谢老师！您辛苦了。
