### ISSUE TITLE
scoop update失败

### ISSUE THREAD

**Issue by xiong321123** [neolee/pilot#1473]
scoop update失败
<img width="716" alt="32" src="https://user-images.githubusercontent.com/91486483/138129523-083b72e1-833d-43d4-bcba-911e073013f1.png">

用网页浏览器我能正常访问网址https://github.com/lukesampson/scoop/

尝试1：运行 scoop checkup，并执行Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1
依然无效
<img width="814" alt="33" src="https://user-images.githubusercontent.com/91486483/138129854-c412b643-a762-4560-9cf0-bbe02791b8ae.png">

尝试2：scoop uninstall git
scoop install git
后，问题依然存在

尝试3：按照某issue中这个方法
<img width="483" alt="34" src="https://user-images.githubusercontent.com/91486483/138130075-8109fb2d-85ba-4693-9240-54e4cf315cbf.png">
<img width="878" alt="35" src="https://user-images.githubusercontent.com/91486483/138130136-2b17008d-279b-451a-9ecd-947a4f067527.png">
这个问题依然存在

**Comment by eva-sun** [comment]
Does this issue resolved?

**Comment by xiong321123** [comment]
> Does this issue resolved?

Yes. This issue has been resolved by turning off the network firewall
