### ISSUE TITLE
Scoop 安装后无法安装 git：不能解析 运行超时

### ISSUE THREAD

**Issue by wenwen-shan** [neolee/pilot#148]
老师，你好，下面是我安装时遇到的问题：
scoop list 已经有7zip 19.00,dark 3.11.2,innounp 0.49
1、运行scoop  install git后
Scoop uses Git to update itself.Run 'scoop install git' and try again .
Installing 'git'(2.23.0.windows.1)[64bit]
未能解析此远程名称：‘github-production-release-asset-2e65be.s3.amazonaws.com’
URL https://github.com/git-for-windows/git/releases/download/v2.23.0.windows.1/   PortableGit-2.23.0-64-bit.7z.exe#/d1.7z is not valid.

前面几次运行时经常发生进度条进展缓慢，最后运行超时结束。找不到什么原因

**Comment by neolee** [comment]
访问 git 官网的网络问题。已经有不少类似 issue，可以搜索一下解决方案。

**Comment by wenwen-shan** [comment]
好的，谢谢
