### ISSUE TITLE
jupyter lab 怎么恢复源文件格式?我发现双击cell，文字就变小了，对于强迫症来说，好难受，请问怎么恢复如初？

### ISSUE THREAD

**Issue by summercool2020** [neolee/pilot#1483]
![网页捕获_20-12-2021_221842_localhost](https://user-images.githubusercontent.com/75110622/146781585-4a82b369-89ab-479a-be56-4f16b40c5d3f.jpeg)

**Comment by neolee** [comment]
那是进入编辑状态了，Ctrl+Enter 提交就好了。

**Comment by summercool2020** [comment]
感谢老师的回复。
