### ISSUE TITLE
m1芯片的mac，按照安装顺序安装homedrew后，无法找到brew，所以无法执行brew update等后续操作

### ISSUE THREAD

**Issue by LSiying** [neolee/pilot#1486]
<img width="598" alt="截屏2021-12-29 下午3 44 51" src="https://user-images.githubusercontent.com/92238382/147639621-f5cd8bb1-5772-4212-8333-533856c0dfaf.png">

**Comment by neolee** [comment]
和 M1 无关，Homebrew 早就支持 Apple Silicon，我最新的电脑也是 M1 的。

你的 Homebrew 装在 `/opt` 下了，需要你自己把 /opt/homebrew/bin 加到系统的 `PATH` 环境变量中。

我不知道是不是现在缺省装在 `/opt` 下了，以前是装在 `/usr/local` 下，就不需要首攻设置了。

**Comment by LSiying** [comment]
> 和 M1 无关，Homebrew 早就支持 Apple Silicon，我最新的电脑也是 M1 的。
> 
> 你的 Homebrew 装在 `/opt` 下了，需要你自己把 /opt/homebrew/bin 加到系统的 `PATH` 环境变量中。
> 
> 我不知道是不是现在缺省装在 `/opt` 下了，以前是装在 `/usr/local` 下，就不需要首攻设置了。

谢谢Neo～
我这几天断断续续的在“蒙圈”的状态下（我记得是有出现'/pot‘的目录），看着应该是完成了环境设置。现在刚安装完jupyterlab。但是出现一串warning（更懵了，刚开始学，完全不明就里）如下：
WARNING: The scripts jupyter, jupyter-migrate and jupyter-troubleshoot are installed in '/Users/fayelee/Library/Python/3.8/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts jupyter-kernel, jupyter-kernelspec and jupyter-run are installed in '/Users/fayelee/Library/Python/3.8/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script send2trash is installed in '/Users/fayelee/Library/Python/3.8/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script jsonschema is installed in '/Users/fayelee/Library/Python/3.8/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script jupyter-trust is installed in '/Users/fayelee/Library/Python/3.8/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script jupyter-execute is installed in '/Users/fayelee/Library/Python/3.8/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script pygmentize is installed in '/Users/fayelee/Library/Python/3.8/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts jupyter-dejavu and jupyter-nbconvert are installed in '/Users/fayelee/Library/Python/3.8/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script wsdump is installed in '/Users/fayelee/Library/Python/3.8/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script jupyter-server is installed in '/Users/fayelee/Library/Python/3.8/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts iptest, iptest3, ipython and ipython3 are installed in '/Users/fayelee/Library/Python/3.8/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts jupyter-bundlerextension, jupyter-nbextension, jupyter-notebook and jupyter-serverextension are installed in '/Users/fayelee/Library/Python/3.8/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script jupyter-nbclassic is installed in '/Users/fayelee/Library/Python/3.8/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script pyjson5 is installed in '/Users/fayelee/Library/Python/3.8/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script normalizer is installed in '/Users/fayelee/Library/Python/3.8/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script pybabel is installed in '/Users/fayelee/Library/Python/3.8/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts jlpm, jupyter-lab, jupyter-labextension and jupyter-labhub are installed in '/Users/fayelee/Library/Python/3.8/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed MarkupSafe-2.0.1 Send2Trash-1.8.0 anyio-3.4.0 appnope-0.1.2 argon2-cffi-21.3.0 argon2-cffi-bindings-21.2.0 attrs-21.4.0 babel-2.9.1 backcall-0.2.0 bleach-4.1.0 certifi-2021.10.8 cffi-1.15.0 charset-normalizer-2.0.10 debugpy-1.5.1 decorator-5.1.1 defusedxml-0.7.1 entrypoints-0.3 idna-3.3 importlib-resources-5.4.0 ipykernel-6.6.1 ipython-7.31.0 ipython-genutils-0.2.0 jedi-0.18.1 jinja2-3.0.3 json5-0.9.6 jsonschema-4.3.3 jupyter-client-7.1.0 jupyter-core-4.9.1 jupyter-server-1.13.1 jupyterlab-3.2.6 jupyterlab-pygments-0.1.2 jupyterlab-server-2.10.3 matplotlib-inline-0.1.3 mistune-0.8.4 nbclassic-0.3.4 nbclient-0.5.9 nbconvert-6.4.0 nbformat-5.1.3 nest-asyncio-1.5.4 notebook-6.4.6 packaging-21.3 pandocfilters-1.5.0 parso-0.8.3 pexpect-4.8.0 pickleshare-0.7.5 prometheus-client-0.12.0 prompt-toolkit-3.0.24 ptyprocess-0.7.0 pycparser-2.21 pygments-2.11.2 pyparsing-3.0.6 pyrsistent-0.18.0 python-dateutil-2.8.2 pytz-2021.3 pyzmq-22.3.0 requests-2.27.1 sniffio-1.2.0 terminado-0.12.1 testpath-0.5.0 tornado-6.1 traitlets-5.1.1 urllib3-1.26.8 wcwidth-0.2.5 webencodings-0.5.1 websocket-client-1.2.3 zipp-3.7.0
WARNING: You are using pip version 20.2.3; however, version 21.3.1 is available.
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.

然后也没有google到一个靠谱的答案（环境设置是在lyric的提示下，边google边瞎猫碰上死耗子完成，我自己这么觉得）

**Comment by LSiying** [comment]
> 和 M1 无关，Homebrew 早就支持 Apple Silicon，我最新的电脑也是 M1 的。
> 
> 你的 Homebrew 装在 `/opt` 下了，需要你自己把 /opt/homebrew/bin 加到系统的 `PATH` 环境变量中。
> 
> 我不知道是不是现在缺省装在 `/opt` 下了，以前是装在 `/usr/local` 下，就不需要首攻设置了。
