### ISSUE TITLE
安装 Scoop 出现下面的问题

### ISSUE THREAD

**Issue by Erika00** [neolee/pilot#149]
PS C:\Users\86180> Get-ExecutionpolicyRestricted
PS C:\Users\86180> Set-ExecutionpolicyRemoteSigned-scopeCurrentUserSet-ExecutionpolicyRemoteSigned-scopeCurrentUser : 无法将“Set-ExecutionpolicyRemoteSigned-scopeCurrentUser”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。所在位置 行:1 字符: 1+ Set-ExecutionpolicyRemoteSigned-scopeCurrentUser+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~    + CategoryInfo          : ObjectNotFound: (Set-Executionpo...copeCurrentUs   er:String) [], CommandNotFoundException    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by neolee** [comment]
不要在标题里放那么多内容，看不清，我帮你拆到正文了。

但是你粘贴的内容还是比较混乱，有些地方搞不清原本显示的是啥。

不过我猜你输入的命令有问题，你需要输入的两个命令是：

```powershell
Get-ExecutionPolicy
Set-ExecutionPolicy RemoteSigned -scope CurrentUser
```

这两个命令（尤其是第二个）成功了，再用下面这个来安装 Scoop：

```powershell
iwr -useb get.scoop.sh | iex
```

**Comment by banshibao** [comment]
![捕获2](https://user-images.githubusercontent.com/24274761/67636862-c49d9c80-f90f-11e9-9d31-0a481df5f37f.JPG)
我遇到这个问题，不知怎么做了，scoop ckeckup,看不懂怎么操作，帮助指导一下呗，感谢

**Comment by neolee** [comment]
`scoop update` 那个是网络问题，多试几次，最好换网络或者挂代理试试。

**Comment by shengxia-0411** [comment]
老师在安装命令包Scoop的时候遇到这个问题：
![bc55800b97923fec69ad26956ae4f3e](https://user-images.githubusercontent.com/57080332/67649402-efb9d780-f973-11e9-90f9-fb3e4502dc3f.jpg)

**Comment by neolee** [comment]
前一个命令，RemoteSigned 和 -scope 之间缺了个空格。

后一个命令，iwr 和 -useb 之间缺了个空格。
