### ISSUE TITLE
MySQL Workbench 怎么导入数据到数据库出错！

### ISSUE THREAD

**Issue by zhenrany** [neolee/pilot#1494]
### 在运行MySQL Workbench 最后两步的时候出错，文档编码格式已经改为： UTF-8 ，如下图：
![截图3](https://user-images.githubusercontent.com/55627503/150906707-df655403-3c49-47d7-a866-39593a10ca0b.PNG)
![截图1](https://user-images.githubusercontent.com/55627503/150906722-9d648b3d-ed54-4314-b7e7-31373cd408c4.PNG)
![截图2](https://user-images.githubusercontent.com/55627503/150906736-b6bf7ba2-6559-45a9-abfa-99713f36949a.PNG)

**Comment by neolee** [comment]
Duplicate of https://github.com/neolee/wop-community/issues/322

**Comment by hope1324** [comment]
我也碰到这个问题，好几个月没有解决，今天解决了。我是win10系统，mysql-installer-community-8.0.29.0，用旧的版本mysql-workbench-community-8.0.19-winx64解决这个问题了。试了好几个版本，最后用旧版本8.0.19正常了。

**Comment by neolee** [comment]
> 我也碰到这个问题，好几个月没有解决，今天解决了。我是win10系统，mysql-installer-community-8.0.29.0，用旧的版本mysql-workbench-community-8.0.19-winx64解决这个问题了。试了好几个版本，最后用旧版本8.0.19正常了。

看来Workbench没事不要升级，8.0.20以后的版本出过不少怪问题……

**Comment by pyz610173878** [comment]
感谢
