### ISSUE TITLE
Github打开Code显示“Something went wrong"

### ISSUE THREAD

**Issue by chen921011** [neolee/pilot#15]
OS X系统打开Code显示“Something went wrong"，reload很多次都不管用。
公司和家的网络都会这样，开了科学上网走全局也会这样。

**Comment by neolee** [comment]
这是 GitHub 的bug，有时会出现，在 [指引](https://github.com/neolee/pilot/blob/master/README.md) 里对这个情况有说明，换用 Jupyter 的 nbviewer 就行了。
