### ISSUE TITLE
git 提交出现报错，什么原因，怎么处理

### ISSUE THREAD

**Issue by gongzhigao** [neolee/pilot#150]
PS C:\Users\龚志高\code\learn-git> git status
On branch master

No commits yet

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)
        new file:   README.md

PS C:\Users\龚志高\code\learn-git> git commit
hint: Waiting for your editor to close the file... internal/modules/cjs/loader.js:586
    throw err;
    ^

Error: Cannot find module 'C:\Users'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Function.Module._load (internal/modules/cjs/loader.js:510:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:746:12)
    at startup (internal/bootstrap/node.js:282:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:759:3)
error: There was a problem with the editor 'code -w'.
Please supply the message using either -m or -F option.
PS C:\Users\龚志高\code\learn-git>

**Comment by neolee** [comment]
好像你的 Visual Studio Code 有点问题，你在开始菜单找到 Visual Studio Code 运行下看看有没有问题，然后在命令行直接运行 `code` 试试？

**Comment by gongzhigao** [comment]
从开始菜单运行Visual Studia Code没有问题，命令行直接运行code也没有问题

**Comment by neolee** [comment]
运行 `git config --list` 给我看看。

**Comment by gongzhigao** [comment]
PS C:\Users\龚志高\code\learn-git> git config --list
core.symlinks=false
core.autocrlf=true
color.diff=auto
color.status=auto
color.branch=auto
color.interactive=true
help.format=html
http.sslcainfo=/ssl/certs/ca-bundle.crt
diff.astextplain.textconv=astextplain
rebase.autosquash=true
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge --skip -- %f
filter.lfs.process=git-lfs filter-process --skip
filter.lfs.required=true
credential.helper=helper-selector
credential.helper=manager
user.name=Zhigao Gong
user.email=zhigao.gong@gmail.com
core.editor=code -w
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
PS C:\Users\龚志高\code\learn-git>

**Comment by neolee** [comment]
那你在命令行运行 `code -w` 呢？

**Comment by gongzhigao** [comment]
运行了Visual Studia Code

**Comment by neolee** [comment]
此时命令行窗口里啥状态？

**Comment by gongzhigao** [comment]
在左端出现亮标，没有任何显示

**Comment by gongzhigao** [comment]
关闭Visual Studia Code后，出现
PS C:\Users\龚志高\code\learn-git>

**Comment by neolee** [comment]
感觉一切正常，你再试试 `git commit` ？

**Comment by gongzhigao** [comment]
![image](https://user-images.githubusercontent.com/38653158/67650119-a0c17180-f976-11e9-83ca-adc7c33645b3.png)

**Comment by neolee** [comment]
你执行 `scoop checkup` 有什么反馈？

**Comment by gongzhigao** [comment]
PS C:\Users\龚志高\code\learn-git> scoop checkup
WARN  Windows Defender may slow down or disrupt installs with realtime scanning.
  Consider running:
    sudo Add-MpPreference -ExclusionPath 'C:\Users\龚志高\scoop'
  (Requires 'sudo' command. Run 'scoop install sudo' if you don't have it.)
WARN  Windows Defender may slow down or disrupt installs with realtime scanning.
  Consider running:
    sudo Add-MpPreference -ExclusionPath 'C:\ProgramData\scoop'
  (Requires 'sudo' command. Run 'scoop install sudo' if you don't have it.)
WARN  LongPaths support is not enabled.
You can enable it with running:
    Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1
ERROR 'Inno Setup Unpacker' is not installed! It's required for unpacking InnoSetup files. Please run 'scoop install innounp'.
ERROR 'dark' is not installed! It's required for unpacking installers created with the WiX Toolset. Please run 'scoop install dark' or 'scoop install wixtoolset'.
WARN  Found 5 potential problems.
PS C:\Users\龚志高\code\learn-git>

**Comment by neolee** [comment]
有五个配置相关的建议，最好一一照做，方法是依次执行：

```powershell
scoop install sudo
sudo Add-MpPreference -ExclusionPath 'C:\Users\龚志高\scoop'
sudo Add-MpPreference -ExclusionPath 'C:\ProgramData\scoop'
Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1
scoop install innounp dark
```

**Comment by neolee** [comment]
这些都无问题的话，再试试 `git commit` 看看。

**Comment by gongzhigao** [comment]
PS C:\Users\龚志高> scoop install sudo
Updating Scoop...
Updating 'main' bucket...
 * d6301372 gitlab-runner: Update to version 12.4.1                      44 minutes ago
 * d9b0a0de trid: Update to version 2.24-19.10.28                        2 hours ago
 * 1a5efb15 imagemagick: Update to version 7.0.9-1                       2 hours ago
 * ba9f5f80 dnscrypt-proxy: Update to version 2.0.29                     2 hours ago
 * e3cbd313 v2ray: Update to version 4.21.2                              3 hours ago
 * 5f3388da coq: Update to version 8.10.1                                3 hours ago
 * 80d889e2 ffmpeg-nightly: Update to version 20191028-68f623d           4 hours ago
Updating 'versions' bucket...
Scoop was updated successfully!
Installing 'sudo' (0.2018.07.25) [64bit]
基础连接已经关闭: 连接被意外关闭。
URL https://raw.githubusercontent.com/lukesampson/psutils/3290c04d7653ea8183a5e11d3d5a4e46716035d1/sudo.ps1 is not valid
PS C:\Users\龚志高>

**Comment by neolee** [comment]
换个时间试试，看上去网络不太稳定。

**Comment by gongzhigao** [comment]
PS C:\Users\龚志高> scoop uninstall sudo
Uninstalling 'sudo' ().
'sudo' was uninstalled.
PS C:\Users\龚志高> scoop install sudo
Installing 'sudo' (0.2018.07.25) [64bit]
sudo.ps1 (2.0 KB) [==================================================================================================================================] 100%
Checking hash of sudo.ps1 ... ok.
Linking ~\scoop\apps\sudo\current => ~\scoop\apps\sudo\0.2018.07.25
Creating shim for 'sudo'.
'sudo' (0.2018.07.25) was installed successfully!
PS C:\Users\龚志高> sudo Add-MpPreference -ExclusionPath 'C:\Users\龚志高\scoop'
PS C:\Users\龚志高> sudo Add-MpPreference -ExclusionPath 'C:\ProgramData\scoop'
PS C:\Users\龚志高> Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1
Set-ItemProperty : 不允许所请求的注册表访问权。
所在位置 行:1 字符: 1
+ Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem'  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (HKEY_LOCAL_MACH...trol\FileSystem:String) [Set-ItemProperty], SecurityException
    + FullyQualifiedErrorId : System.Security.SecurityException,Microsoft.PowerShell.Commands.SetItemPropertyCommand

**Comment by gongzhigao** [comment]
![image](https://user-images.githubusercontent.com/38653158/67847166-58a07b80-fb3d-11e9-892f-94693ffa8cad.png)

**Comment by neolee** [comment]
试试开一个 {{ PowerShell (Admin) }} 命令行窗口，然后执行 Set-ItemProperty 那行命令。

或者在那行命令前加上 `sudo ` 也可以。

**Comment by gongzhigao** [comment]
scoop install sudo
sudo Add-MpPreference -ExclusionPath 'C:\Users\龚志高\scoop'
sudo Add-MpPreference -ExclusionPath 'C:\ProgramData\scoop'
Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1
scoop install innounp dark
这些依次执行完后，git commit 还是报错

**Comment by gongzhigao** [comment]
![image](https://user-images.githubusercontent.com/38653158/67865539-63213c00-fb62-11e9-9b19-c9ab4239c1dc.png)

**Comment by gongzhigao** [comment]
![image](https://user-images.githubusercontent.com/38653158/67865709-b1363f80-fb62-11e9-8cb9-269006cca2e3.png)

**Comment by neolee** [comment]
你这个问题已经排除了很多常见根源，进入比较少见的情况了……

你运行 git commit 的时候，Visual Studio Code 会打开吗？还是直接出错呢？如果可以打开 Code，请你截个屏，同时包含命令行窗口和 Visual Studio Code 窗口。

**Comment by gongzhigao** [comment]
运行git commit的时候，没有打开Code直接出错

**Comment by gongzhigao** [comment]
> 遇到相同问题，报错内容有所不同，但给出的解决方案都是 配置一样的五样东西。
> 运行第一段代码“scoop install sudo”时，出现报错，如下：“无法连接到远程服务器
> URL https://raw.githubusercontent.com/lukesampson/psutils/3290c04d7653ea8183a5e11d3d5a4e46716035d1/sudo.ps1 is not valid”
> 反复几此安装和卸载后，情况还是一样。

网络原因，找个代理可以解决，科学上网

**Comment by Lilidandan321** [comment]
求帮忙指点：我也是git commits 报错，错误提示跟150#号一样。
PS C:\Users\jll\Code\learn-git> git status
On branch master

No commits yet

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)
        new file:   README.md

PS C:\Users\jll\Code\learn-git> git commit
hint: Waiting for your editor to close the file... internal/modules/cjs/loader.js:586
    throw err;
    ^

Error: Cannot find module 'D:\D'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Function.Module._load (internal/modules/cjs/loader.js:510:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:746:12)
    at startup (internal/bootstrap/node.js:282:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:759:3)
error: There was a problem with the editor 'code -w'.
Please supply the message using either -m or -F option.

根据老师的提示我进行了以下操作，检验Visual Studio Code 正常，但就是提交不了
1.用菜单打开Visual Studio Code 运行没问题。在命令行 code .运行也没问题。
2.PS C:\Users\jll> git config --list
运行结果：PS C:\Users\jll> git config --list
user.name=Lilidandan321
user.email=2467764484@qq.com
core.editor=code -w
运行后这三项都有。
3.执行scoop checkup 也正常。
PS C:\Users\jll> scoop checkup
No problems identified!

**Comment by neolee** [comment]
@Lilidandan321 建议另开新 issue，你这个和别的不一样，你的  `scoop checkup` 里的几个问题都解决了，还出现这个错误比较独特。

**Comment by Lilidandan321** [comment]
> @Lilidandan321 建议另开新 issue，你这个和别的不一样，你的 `scoop checkup` 里的几个问题都解决了，还出现这个错误比较独特。

重新安装了一次就好了，谢谢老师。

**Comment by gongzhigao** [comment]
> > @Lilidandan321 建议另开新 issue，你这个和别的不一样，你的 `scoop checkup` 里的几个问题都解决了，还出现这个错误比较独特。
> 
> 重新安装了一次就好了，谢谢老师。

我的还没有处理好，你重装了哪些内容。

**Comment by Lilidandan321** [comment]
> > > @Lilidandan321 建议另开新 issue，你这个和别的不一样，你的 `scoop checkup` 里的几个问题都解决了，还出现这个错误比较独特。
> > 
> > 
> > 重新安装了一次就好了，谢谢老师。
> 
> 我的还没有处理好，你重装了哪些内容。

我还没学这次编程课前就安装了Visual Studia Code，，后面又卸载了估计没卸载干净，后面重新安装git commit时出现了那个问题，，我这电脑也没啥东西所以就恢复了出厂设置，之后又重新按照老师的步骤把所有的都重新装了一遍，就好了。

**Comment by gongzhigao** [comment]
重装解决了问题

**Comment by jiushijiushi** [comment]
> 重装解决了问题

我出现类似的问题，准备重装Visual Studia Code，你们是如何重装的呢
