### ISSUE TITLE
执行iwr -useb get.scoop.sh | iex报错

### ISSUE THREAD

**Issue by HUGO-BEIJING** [neolee/pilot#151]
PS C:\Users\hujf> iwr useb get.scoop.sh | iex
Invoke-WebRequest : A positional parameter cannot be found that accepts argumen t 'get.scoop.sh'.
At line:1 char:1
+ iwr useb get.scoop.sh | iex
+ ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Invoke-WebRequest], Parent
   ContainsErrorRecordException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell
   .Commands.InvokeWebRequestCommand

**Comment by neolee** [comment]
命令输错了，你实际执行的命令甚至不是你这个 issue 标题里写的命令……
