### ISSUE TITLE
找不到 pandas 包

### ISSUE THREAD

**Issue by Gittplayer** [neolee/pilot#1512]
p2-c中

```
import pandas as pd

data = pd.read_csv('assets/moma-artists.csv')
data.head(10)
```
运行报错：
ModuleNotFoundError                       Traceback (most recent call last)
c:\Users\wuzhe\Code\pilot-student\p2-c-database.ipynb Cell 56 in <cell line: 1>()
----> [1](vscode-notebook-cell:/c%3A/Users/wuzhe/Code/pilot-student/p2-c-database.ipynb#Y106sZmlsZQ%3D%3D?line=0) import pandas as pd
      [3](vscode-notebook-cell:/c%3A/Users/wuzhe/Code/pilot-student/p2-c-database.ipynb#Y106sZmlsZQ%3D%3D?line=2) data = pd.read_csv('assets/moma-artists.csv')
      [4](vscode-notebook-cell:/c%3A/Users/wuzhe/Code/pilot-student/p2-c-database.ipynb#Y106sZmlsZQ%3D%3D?line=3) data.head(10)

ModuleNotFoundError: No module named 'pandas'
试了issues中的方法还是没解决，请李老师看看呢

**Comment by neolee** [comment]
这个明确的说了是没找到 pandas 这个包，有否用 `pip install pandas` 在你的当前环境里安装 pandas 呢？

**Comment by Gittplayer** [comment]
装了的，李老师，而且我卸载重装也试过
PS C:\Users\wuzhe\Code> pip install pandas
Requirement already satisfied: pandas in c:\users\wuzhe\scoop\apps\python37\current\lib\site-packages (1.3.5)
Requirement already satisfied: pytz>=2017.3 in c:\users\wuzhe\scoop\apps\python37\current\lib\site-packages (from pandas) (2022.1)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\wuzhe\scoop\apps\python37\current\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.17.3 in c:\users\wuzhe\scoop\apps\python37\current\lib\site-packages (from pandas) (1.21.6)
Requirement already satisfied: six>=1.5 in c:\users\wuzhe\scoop\apps\python37\current\lib\site-packages (from python-dateutil>=2.7.3->pandas) (1.16.0)

**Comment by neolee** [comment]
这个比较像是你安装 pandas 的环境和运行教材 jupyter notebook 的环境不一致。

**Comment by neolee** [comment]
你在命令行运行 `python`，进入Python的交互式环境后，直接输入 `import pandas as pd`，看看有没有出错信息。

**Comment by Gittplayer** [comment]
李老师，1.你说在命令行中运行是指在conemu中吗？运行如下图，我感觉我没做对吧。2.刚测试在jupyter lab中运行正常，以上故障是在vsc中报的
![image](https://user-images.githubusercontent.com/57967597/183621000-32378534-54b5-4a96-829b-03e2453e7794.png)

**Comment by neolee** [comment]
所以就是了，你命令行、以及从命令行启动的JupyterLab都是同一个环境，也就是你用Scoop安装的那个环境，这个环境里安装了pandas，所以可以正常使用；但是VSCode缺省是自己会安装一个自己的Python环境的，而这个环境里你并没有安装pandas，所以就不行了。

**Comment by Gittplayer** [comment]
谢谢李老师，已经解决了，其实在vs新加一个cell 然后pip就可以了
