### ISSUE TITLE
p2-c中报IndexError: list index out of range

### ISSUE THREAD

**Issue by Gittplayer** [neolee/pilot#1513]
李老师好：
我在p2-c中运行代码时
`data['data']['items'][0]['clazzName']`
报如下错误：
IndexError                                Traceback (most recent call last)
c:\Users\wuzhe\Code\pilot-student\p2-c-database.ipynb Cell 77 in <cell line: 1>()
----> [1](vscode-notebook-cell:/c%3A/Users/wuzhe/Code/pilot-student/p2-c-database.ipynb#Y140sZmlsZQ%3D%3D?line=0) data['data']['items'][0]['clazzName']

IndexError: list index out of range
请李老师看看呢

**Comment by neolee** [comment]
这个例子用了某在线教育公司的页面上的服务，目前这个页面已经不工作了，所以取回的数据也空了，所以当然没法正确访问了。以后等我有空再更新这个例子吧。

**Comment by Gittplayer** [comment]
谢谢李老师
