### ISSUE TITLE
安装scoop错误

### ISSUE THREAD

**Issue by jackccbzhang** [neolee/pilot#1515]
没错，安装scoop确实有错误，我在网上都找不到解决办法 
<p style="color: red;background-color:black;">
iex : 使用“2”个参数调用“DownloadFile”时发生异常:“在 WebClient 请求期间发生异常。”
所在位置 行:1 字符: 26
+ iwr -useb get.scoop.sh | iex
+                          ~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-Expression], MethodInvocationException
    + FullyQualifiedErrorId : WebException,Microsoft.PowerShell.Commands.InvokeExpressionCommand
</p>
如果知道怎么解决的，请说出来
试过的方法，后来都没效果

* [x] 先执行 iwr -useb get.scoop.sh -outfile 'install.ps1' 再执行： .\install.ps1 -RunAsAdmin
* [x] [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

**Comment by pyz610173878** [comment]
你可以在issue问题集中找下，大概率有人跟你出现同样的情况。
地址 https://github.com/neolee/wop-ecnu-pub/wiki
