### ISSUE TITLE
p1-3中的引用链接404

### ISSUE THREAD

**Issue by staysimplecho** [neolee/pilot#1517]
解释“绝大部分十进制小数是没法用有限位数表示为二进制小数的”的文章不存在啦，可以替换一下
url: https://www.taowong.com/blog/2018/07/10/principle-of-computer-float-num.html

**Comment by neolee** [comment]
感谢指出！这个仓库以后可能不会更新了，我在最新的主仓库里已经更新了： https://github.com/neolee/wop
