### ISSUE TITLE
No module named pip 或 No module named pip3

### ISSUE THREAD

**Issue by bright-xuexi** [neolee/pilot#152]
![pip](https://user-images.githubusercontent.com/36670984/67635572-bb0e3780-f903-11e9-870a-244d2b95e935.jpg)
![pip3](https://user-images.githubusercontent.com/36670984/67635574-c2354580-f903-11e9-9309-4ad2af3cebc5.jpg)
提示没有 pip 或 pip3 的模块

**Comment by neolee** [comment]
本来就没有 pip3 这个 module。但是找不到 pip 这个 module 就没有道理了，你之前安装 Python 有什么错误信息吗？

**Comment by bright-xuexi** [comment]
解决方案：命令行输入 python -m ensurepip 运行之后，再输入 python -m pip install --upgrade pip即可
