### ISSUE TITLE
重装Homebrew

### ISSUE THREAD

**Issue by y60l** [neolee/pilot#153]
老师求助：
![image](https://user-images.githubusercontent.com/57059825/67635736-0248f800-f905-11e9-9217-03450110e754.png)
问题1：装成功了么？
问题2：最后一个警告 两个文件是不是该删掉 会不会有什么影响

ps：之前问题的解决 
![image](https://user-images.githubusercontent.com/57059825/67635842-bba7cd80-f905-11e9-85a0-a5c4b5475c3e.png)

解决方案：
好久没用mac 弄了一小天 系统一直在反复更新10.13.6 
用这个网址 https://itunes.apple.com/cn/app/macos-mojave/id1398502828?mt=12
跳过10.13.6  现在是最新版本了 没再遇到之前的问题

**Comment by neolee** [comment]
那个 `brew doctor` 的问题不大，你运行一下 `brew cleanup` 就可以了。

然后可以继续了。
