### ISSUE TITLE
我不理解 这段红色代码的意思，它有什么用，去掉它代码也可以正常跑起来

### ISSUE THREAD

**Issue by Totie-O** [neolee/pilot#1532]
![IMG_3184](https://github.com/neolee/pilot/assets/53247740/f9c36e5b-4947-4701-a0c2-51786950f38f)

**Comment by neolee** [comment]
如果你创建 `TreeNode` 实例的时候直接传一个 `children` 列表给 `__init__` 方法，就用到这一部分，你的测试代码没有这种用例，自然测不出它的作用。

看来你还没理解 `__init__` 方法和创建实例对象的机制。

**Comment by Totie-O** [comment]
树的思想我能理解，但对我来讲，代码实现直接抽象了两个层级不止

**Comment by Totie-O** [comment]
![IMG_3186](https://github.com/neolee/pilot/assets/53247740/98c5b528-8033-4985-af85-1b4cf5775134)

**Comment by Totie-O** [comment]
好吧，李老师我看懂了，理解代码的关键李老师确实写出来了，细看了好多遍才看出来，节点应该保存父节点和子节点的信息，从这个点出发，就可以看懂相关代码的实现，真的复杂，但是妙到家了。

**Comment by Totie-O** [comment]
![IMG_3217](https://github.com/neolee/pilot/assets/53247740/d9b80d13-8523-426f-8032-c4d4a83a7273)
李老师，这两句语句，有啥区别，我的理解是一样的。。。。

**Comment by Totie-O** [comment]
好吧，李老师我理解了为啥这两句代码的区别了，实例化完A且没有指定parent=root的情况下，使用add_child这个函数就能补上这个属性，有区别。。。。

**Comment by Totie-O** [comment]
![IMG_3256](https://github.com/neolee/pilot/assets/53247740/5c9e1214-8d5d-4bc2-bfee-77dc89e1b9f0)
李老师，那个tier的弯我绕不出来，我的想法是初始节点的tier设为1，要是有父节点，tier+1，然后继续迭代，但是我发现一个问题，我每次迭代tier又变成1，导致输出为2（正确的输出为3），请老师帮我指点一下

**Comment by Totie-O** [comment]
好吧，李老师，我采取了一个比较折中的方案，我先递归求出这个子节点的全部父辈节点，然后再定义一个函数再求出他的tier
![IMG_3260](https://github.com/neolee/pilot/assets/53247740/854d7943-71f2-4d61-a7fa-c9496f6bcbf1)

**Comment by Totie-O** [comment]
好吧，李老师，我好像绕出来了，我想错方向了，不应该是赋值，而是应该直接叠加
![IMG_3261](https://github.com/neolee/pilot/assets/53247740/079ebcc0-b672-48a9-ab96-6eb6ac88c201)
