### ISSUE TITLE
就业指点——关于数据运营

### ISSUE THREAD

**Issue by Totie-O** [neolee/pilot#1534]
李老师，我有一个工作问题想咨询您一下，我目前做的是商品专员，需要做很多报表，我成功把大部分表报都用python自动化了，做了几个小玩意出来，pandas算是基本入门了。同时我也用python批量处理了很多图片（python算是基本入门了，大部分都是李老师的功劳）
mysql基本使用也掌握了，也有用tableau做了两个小玩意

最近我想换工作，我的想法是往数据运营的方向发展，然后就遇到一个难题了，我如何把我所做的成果在简历上面表现出来
还有一个问题，就是我做的小玩意都是比较基础入门的，我在思考如何做出更具商业价值的报表呢，让我的简历看起来更具优势呢，这方面有什么好的建议吗？
我昨晚重新听了李老师在践行群最后一课讲的关于数据分析就业方向介绍，里面着重提到概率统计，最近想系统补一下这方面的知识，有没有好书推荐呀，或者视频，谢谢了

**Comment by neolee** [comment]
1. 关于换工作，需要针对你的目标公司和岗位做一些调查研究和针对性准备，如果没有特别的考虑，我个人的建议还是“实事求是”，你已经证明你有很好的自学能力和动手能力，对数据也有不错的基本理解，作为大部分公司的数据运营是不错的起点了，除非对方只招很有直接经验的，你把你做过的这些说清楚，展现你的主动性和动手能力，就够了。
2. 高质量的、通俗易懂的统计/概率论教科书，我也还在找……
