### ISSUE TITLE
print(f'...) SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by tyler1zhang** [neolee/pilot#155]
当运行书中的以下代码的时候出现语法错误提示
print(f'4 +9 = {4 +9}')
print('Hello world!')

错误提示如下。
 File "hello.py", line 3
    print(f'4 +9 = {4 +9}')
                         ^
SyntaxError: invalid syntax

根据stackoverflow网站的提示（链接 https://stackoverflow.com/questions/42126794/python-3-returns-invalid-syntax-when-trying-to-perform-string-interpolation ），似乎是python版本的问题。但我们现在的版本3.7.4不应该有这个问题。于是不知如何原因，所以在此提问。

**Comment by neolee** [comment]
执行 `python -V` 看看

**Comment by tyler1zhang** [comment]
Python 2.7.16

**Comment by tyler1zhang** [comment]
运行$ python3 -V结果是
Python 3.7.4
运行$ python -V结果是
Python 2.7.16

**Comment by neolee** [comment]
那你用 `python3 hello.py` 应该就对了。
