### ISSUE TITLE
error: RPC failed; curl 18 transfer closed with outstanding read data remaining

### ISSUE THREAD

**Issue by bill79927** [neolee/pilot#157]
安装homebrew，出现错误提示error: RPC failed; curl 18 transfer closed with outstanding read data remaining

**Comment by zhuwenmiao** [comment]
rror: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
Failed during: git fetch origin master:refs/remotes/origin/master --tags --force
 同样的问题，试了好多次了，还望李老师解决，前面李老师给的简书链接并没有解决到问题

**Comment by neolee** [comment]
网络的问题，只有换网络或者代理或者改用国内镜像这几个办法。

**Comment by jarodlong** [comment]
> 安装homebrew，出现错误提示error: RPC failed; curl 18 transfer closed with outstanding read data remaining

早上试试，晚上网络可能堵塞

**Comment by zhuwenmiao** [comment]
HEAD is now at 090259b97 Merge pull request #6644 from MikeMcQuaid/issue_template
李老师，换了个网络，现在显示是这样，还是安装不了，望李老师指导！

**Comment by neolee** [comment]
点击这个页面上方的 Wiki，按照“重装 Homebrew”的提示操作。

有问题的话给出完整的上下文截图，就一句话实在不知道发生了啥。

**Comment by bill79927** [comment]
> 点击这个页面上方的 Wiki，按照“重装 Homebrew”的提示操作。
> 
> 有问题的话给出完整的上下文截图，就一句话实在不知道发生了啥。

https://github.com/neolee/pilot/issues/157#issuecomment-546782661

**Comment by bill79927** [comment]
![image](https://user-images.githubusercontent.com/52498451/67687943-08f27080-f9d4-11e9-8f5a-675b3f3198e9.png)

**Comment by zhuwenmiao** [comment]
<img width="571" alt="截屏2019-10-31上午9 22 48" src="https://user-images.githubusercontent.com/31498197/67911067-153b2100-fbc0-11e9-8ee0-b23902aae90e.png">
李老师，homebrew一直安装不了，尝试了重装homebrew，还是遇到，是因为网络和代理问题才让数据一直无法传输吗？

**Comment by neolee** [comment]
是的，网络问题。
