### ISSUE TITLE
ConEmuC: Root process was alive less than 10 sec, ExitCode=0.

### ISSUE THREAD

**Issue by tyler1zhang** [neolee/pilot#159]
windows version 10.0.17134.1006
如果用powershell启动ConEmu就会有这个提示，Powershell admin也相同，如果改为cmd就没问题。
用cmd的powershell安装后续的git， python都没有问题。

**Comment by neolee** [comment]
看不太明白的你的意思，“用powershell启动ConEmu” 是什么意思？标题里的 ConEmuC 又是啥？

标题的那句话在哪里，什么上下文出现的？

**Comment by tyler1zhang** [comment]
这个error出现在安装完命令行界面ConEmu，在setting中选择{shell: powershell}之后。重启ConEmu，并没有出现以PS开头的提示符，而是“ConEmuC: Root process was alive less than 10 sec, ExitCode=0.”，然后按回车或者ESC退出。

**Comment by neolee** [comment]
你装的 ConEmu 是什么版本？

你有没有运行什么防病毒一类的第三方软件，安装和运行 ConEmu 有没有什么相关的提示？

其实直接用开始菜单里的 PowerShell 程序也是可以的，就是有时候麻烦一点。

**Comment by tyler1zhang** [comment]
ConEmu 191012 [64] {Preview}
如果用cmd或者开始菜单里的PowerShell也不影响学习的话，那就没问题了。可能是公司电脑上的一些设置导致的问题。

**Comment by show5717** [comment]
我也出现过这个问题。后来我把.NET Framework 4.5 or later   和
Windows Management Framework 5.x     这两个文件下载并安装后，就好了。可以去试试。有可能是你这两个文件没安装好。
