### ISSUE TITLE
在MAC安装GIT后，在terminal上使用git时显示warning: could not open directory，是正常的吗？

### ISSUE THREAD

**Issue by hongshuhai** [neolee/pilot#16]
老师好，请问在Mac安装git后，在terminal 上学习使用时，总是会显示
`
warning: could not open directory 'Pictures/照片图库.photoslibrary/': Operation not permitted
warning: could not open directory 'Library/Application Support/CallHistoryTransactions/': Operation not permitted
warning: could not open directory 'Library/Application Support/com.apple.TCC/': Operation not permitted
warning: could not open directory 'Library/Application Support/CallHistoryDB/': Operation not permitted
warning: could not open directory 'Library/IdentityServices/': Operation not permitted
warning: could not open directory 'Library/Messages/': Operation not permitted
warning: could not open directory 'Library/HomeKit/': Operation not permitted
warning: could not open directory 'Library/Mail/': Operation not permitted
warning: could not open directory 'Library/Safari/': Operation not permitted
warning: could not open directory 'Library/Suggestions/': Operation not permitted
warning: could not open directory 'Library/Containers/com.apple.VoiceMemos/': Operation not permitted
warning: could not open directory 'Library/Containers/com.apple.Home/': Operation not permitted
warning: could not open directory 'Library/Containers/com.apple.Safari/': Operation not permitted
warning: could not open directory 'Library/Containers/com.apple.iChat/': Operation not permitted
warning: could not open directory 'Library/Containers/com.apple.mail/': Operation not permitted
warning: could not open directory 'Library/Containers/com.apple.news/': Operation not permitted
warning: could not open directory 'Library/Containers/com.apple.stocks/': Operation not permitted
warning: could not open directory 'Library/PersonalizationPortrait/': Operation not permitted
warning: could not open directory 'Library/Metadata/CoreSpotlight/': Operation not permitted
warning: could not open directory 'Library/Cookies/': Operation not permitted
warning: could not open directory 'Library/Caches/CloudKit/com.apple.Safari/': Operation not permitted
warning: could not open directory 'Library/Caches/com.apple.Safari/': Operation not permitted
warning: could not open directory 'Library/Caches/com.apple.Safari.SafeBrowsing/': Operation not permitted`

**Comment by neolee** [comment]
这个问题非常像是你在你的用户根目录下运行了 `git init` 命令，打开命令行界面，运行下面的命令：

```
cd
ls -la
```

如果输出的文件列表里有 `.git` 这个目录，那就是我猜测的原因。你需要删除这个目录才行，运行下面的命令：

`rm -rf ~/.git`

**注意**：运行这个命令要非常小心，因为 `rm -rf` 会不提示也不可回退的删除文件和目录，一定不能输入错，`~/.git` 中间不能有任何空格。

**Comment by neolee** [comment]
另外，学习使用 git 和 GitHub 时，记得先在用户根目录下建立 Code/learn-git 这个子目录，然后在里面操作：

```
cd
mkdir -p Code/learn-git
cd Code/learn-git
git init
```

**Comment by hongshuhai** [comment]
谢谢李老师，的确如您说的，已安装您教的方法解决了。
