### ISSUE TITLE
老师，安装命令行界面 ConEmu不成功，提示如下

### ISSUE THREAD

**Issue by 111xiaochao111** [neolee/pilot#161]
输入 Get-ExecutionPolicy ↩︎时系统返回的是RemoteSigned
PS C:\Users\a> Get-ExecutionPolicy
RemoteSigned
PS C:\Users\a> Set-ExecutionPolicy RemoteSigned -scope CurrentUser
PS C:\Users\a> iwr -useb get.scoop.sh | iex
Initializing...
Scoop is already installed. Run 'scoop update' to get the latest version.
PS C:\Users\a> scoop update
Scoop uses Git to update itself. Run 'scoop install git' and try again.
PS C:\Users\a>

Scoop 就安装好了，运行第一个命令的结果：
PS C:\Users\a> scoop list
Installed apps:

  7zip 19.00
  busybox 3244-g48128b9aa
  git  *failed*

**Comment by neolee** [comment]
你这个不是安装 ConEmu 有问题，是 Scoop 安装有问题。

具体说，是安装 Scoop 过程中需要安装 git，这个安装失败了。你需要重装 git。

```powershell
scoop uninstall git
scoop install git
```
