### ISSUE TITLE
老师，搭建环境一直不成功，提示如下

### ISSUE THREAD

**Issue by 111xiaochao111** [neolee/pilot#162]
输入 Get-ExecutionPolicy ↩︎时系统返回的是RemoteSigned
PS C:\Users\a> Get-ExecutionPolicy
RemoteSigned
PS C:\Users\a> Set-ExecutionPolicy RemoteSigned -scope CurrentUser
PS C:\Users\a> iwr -useb get.scoop.sh | iex
Initializing...
Scoop is already installed. Run 'scoop update' to get the latest version.
PS C:\Users\a> scoop update
Scoop uses Git to update itself. Run 'scoop install git' and try again.
PS C:\Users\a>

Scoop 就安装好了，运行第一个命令的结果：
PS C:\Users\a> scoop list
Installed apps:

  7zip 19.00
  busybox 3244-g48128b9aa
  git  *failed*

**Comment by XueAE** [comment]
git没安装成功，删了重装试试，你去看看#33问题。

**Comment by 111xiaochao111** [comment]
运行scoop的安装命令碰到这个问题，该如何解决呢

PS C:\Users\a> Get-ExecutionPolicy
RemoteSigned
PS C:\Users\a> iwr -useb get.scoop.sh | iex
iwr : 无法连接到远程服务器
所在位置 行:1 字符: 1
+ iwr -useb get.scoop.sh | iex
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:Htt
   pWebRequest) [Invoke-WebRequest]，WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShe
   ll.Commands.InvokeWebRequestCommand

PS C:\Users\a>

**Comment by focusgrowth** [comment]
I have the same issue
