### ISSUE TITLE
cannot create file in Visual studio code

### ISSUE THREAD

**Issue by Jenny0523** [neolee/pilot#163]
![微信图片_20191028110320](https://user-images.githubusercontent.com/48664589/67649115-afa62500-f972-11e9-8370-08b674895204.png)
![微信图片_20191028110331](https://user-images.githubusercontent.com/48664589/67649117-b03ebb80-f972-11e9-9ce3-dd1ab8d1d6d4.png)
![微信图片_20191028110338](https://user-images.githubusercontent.com/48664589/67649118-b03ebb80-f972-11e9-84cf-1a6eec0196e2.png)

**Comment by Jenny0523** [comment]
老师，可以简单说下安装这些软件的底层逻辑吗，或者分享下脑图，我现在没有理论知识，一个人操作好慌乱。谢谢

**Comment by neolee** [comment]
第一个错误，提示其实很明确，你要创建一个目录叫 Code，但这个目录已经存在，用 `cd Code` 进入目录开始干活就好了。

第二个错误，想用 Python 运行一个程序文件 hello.py，但是当前目录下并没有这个文件（看你的 VSCode 截图，这个文件应该在 Code 子目录下）。

你可以点击这个页面上方的 Wiki，然后在支线课程里的第一讲，可能对你有帮助。

关于环境配置，下次上课会讲讲。
