### ISSUE TITLE
运行 jupyter lab 打不开，运行 jupyter notebook 可以打开，有问题吗？

### ISSUE THREAD

**Issue by Guochangyan** [neolee/pilot#164]
老师好，运行jupyter notebook 写完代码运行上传命令，pilot-student 没有更新

**Comment by neolee** [comment]
你觉得有问题没有？为什么呢？

以及，你做了哪些事，你希望得到什么结果，实际上是什么结果？

**Comment by Guochangyan** [comment]
现在除了不能把新的变化同步到 GitHub 上的远程仓库，其他没问题，不知道是不是这个原因，谢谢老师。

**Comment by neolee** [comment]
首先分析一下你的问题，把问题分解开，不要缠绕在一起；你的标题和内容以及后续回复实际上涉及两个彼此独立的问题：

问题1：jupyter lab 打不开，jupyter notebook 可以
很可能是你只安装了 `pip install jupyter`，而没有 `pip install jupyterlab`；这个对学习影响不很大，尤其是如果你对环境比较熟悉的话。

问题2：修改本地的 notebook 之后无法同步到 GitHub 上
这个问题你提供的信息太少，难以判断，比如：你 GitHub 上的 repo 是哪一个？clone 到本地、在本地提交、向 GitHub 同步分别是怎么做的，有什么提示信息，等等。

p.s. 我觉得你需要学会让你的问题更专一、更清晰，这样才更容易得到有价值的答案，你的人生效率也会提升。
