### ISSUE TITLE
scoop updata 持续出错

### ISSUE THREAD

**Issue by kelvinqy** [neolee/pilot#165]
![1572236924(1)](https://user-images.githubusercontent.com/52500863/67652112-87bcbe80-f97e-11e9-9e26-346e7cf9cc7d.png)

**Comment by neolee** [comment]
首先，你的问题是执行 `scoop update` 出错，不是 `git update` 出错。标题和内容矛盾。

然后，你碰到的是网络问题，可以换网络或者挂代理试试。
