### ISSUE TITLE
安装 scoop 时一直提示 '7zip' install failed previously

### ISSUE THREAD

**Issue by Panchunlan** [neolee/pilot#167]
PS C:\Users\Administrator> scoop install git
Scoop uses Git to update itself. Run 'scoop install git' and try again.
'7zip' install failed previously. Please uninstall it and try again.

**Comment by neolee** [comment]
先 `scoop uninstall 7zip` 然后 `scoop install 7zip`；成功后再 `scoop install git`。

或者直接尝试重装 Scoop，参照这个页面上方 Wiki 链接里的“重新安装 Scoop”。
