### ISSUE TITLE
McBook 安装不了 Xcode

### ISSUE THREAD

**Issue by loisewu** [neolee/pilot#168]
MAcBook 安装不了Xcode

**Comment by neolee** [comment]
为啥要安装 Xcode？

**Comment by loisewu** [comment]
电脑显示masos版本太低了

**Comment by loisewu** [comment]
在terminal上按照教程指示运行xcode-select --install  之后就自动弹出安装Xcode，但是又无法安装

**Comment by loisewu** [comment]
<img width="907" alt="屏幕快照 2019-10-28 下午3 37 38" src="https://user-images.githubusercontent.com/56998788/67660156-09214a80-f999-11e9-8510-9bdb6f748862.png">

**Comment by neolee** [comment]
点击“安装”会出错？什么错误？

**Comment by neolee** [comment]
你的 macOS 什么版本？

**Comment by loisewu** [comment]
10.13.4

**Comment by loisewu** [comment]
<img width="1187" alt="屏幕快照 2019-10-28 下午3 56 01" src="https://user-images.githubusercontent.com/56998788/67661196-88178280-f99b-11e9-8637-3115fbc36a87.png">

**Comment by loisewu** [comment]
刚刚又可以安装Xcode了，但是往下按教程操作下一步的时候又出错了，没有“password”提示

**Comment by neolee** [comment]
你需要运行的安装命令是如下完整的一行，你上面没有贴完整：

```shell
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
```

**Comment by loisewu** [comment]
![Uploading 屏幕快照 2019-10-28 下午5.26.49.png…]()

**Comment by loisewu** [comment]
李老师，刚把这一整行的代码贴上去运行了，但是没有任何反应，试了几次都是没有任何反应，不知道是什么问题？

**Comment by neolee** [comment]
没反应是指？

**Comment by loisewu** [comment]
<img width="1191" alt="屏幕快照 2019-10-28 下午5 26 49" src="https://user-images.githubusercontent.com/56998788/67668743-7ccc5300-f9ab-11e9-9fb0-60512f047b8c.png">

**Comment by loisewu** [comment]
就是这样，输完代码按enter键没有任何回应

**Comment by neolee** [comment]
这是在下载安装文件呢，不过似乎比较慢，也许需要挂个代理试试。

**Comment by loisewu** [comment]
<img width="1229" alt="屏幕快照 2019-10-28 下午6 27 46" src="https://user-images.githubusercontent.com/56998788/67671324-ab006180-f9b0-11e9-86d8-a263c3fa21ae.png">
挂代理是什么意思呢？是要用翻墙吗？
刚看运行结果显示好像是链接失败了。

**Comment by neolee** [comment]
是的。

**Comment by loisewu** [comment]
李老师，挂了代理试了几遍还是链接失败，有什么其他办法吗？

**Comment by neolee** [comment]
暂时没有什么办法。只能换别的网络试试。

**Comment by loisewu** [comment]
好的，谢谢李老师的耐心解答，我再多试试
