### ISSUE TITLE
一直卡在scoop下载

### ISSUE THREAD

**Issue by Erika00** [neolee/pilot#169]
李老师昨天安装的scoop下载时间太长最终失败，今天重新安装ScooP，Scoop第一命令返回的不是Restricted
而是RemoteSigned是怎么回事？
PS C:\Users\86180> Get-Executionpolicy
RemoteSigned
PS C:\Users\86180>

**Comment by neolee** [comment]
因为你昨天已经把它设置为 RemoteSigned 了。

继续运行 Scoop 安装命令就好。

**Comment by Erika00** [comment]
李老师 scoop更新出现这个问题，也是网络的问题？
S C:\Users\86180> Set-ExecutionPolicy RemoteSigned -scope CurrentUser
PS C:\Users\86180> iwr -useb get.scoop.sh | iex
Initializing...
Scoop is already installed. Run 'scoop update' to get the latest version.
PS C:\Users\86180> scoop update
scoop : 无法将“scoop”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查
名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ scoop update
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (scoop:String) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by neolee** [comment]
这是你之前安装 Scoop 没有成功，需要重装。‘

点击这个页面上方的 Wiki。按照其中“重装 Scoop”的指引操作。
