### ISSUE TITLE
安装 Scoop 时出错 `调用“SetEnvironmentVariable”时发生异常：尝试执行未经授权的操作`

### ISSUE THREAD

**Issue by ellenxh18** [neolee/pilot#17]
iex : 使用“3”个参数调用“SetEnvironmentVariable”时发生异常:“尝试执行未经授权的操作。” 所在位置 行:1 字符: 1 + iex (new-object net.webclient).downloadstring('https://ge
t.scoop.sh') + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~     + CategoryInfo          : NotSpecified: (:) [Invoke-Expression], MethodInvocationException     + FullyQualifiedErrorId : UnauthorizedAccessException,Microsoft.PowerShell.Commands.InvokeExpressionCommand

**Comment by neolee** [comment]
这是权限错误。在配置指南中有说明：

* 先运行 `Get-ExecutionPolicy` 看结果，一般来说系统应该返回 Restricted；这时候要——
* 运行 `Set-ExecutionPolicy RemoteSigned -scope CurrentUser`，运行无误就拥有了所需权限，然后再——
* 运行 `iex (new-object net.webclient).downloadstring('https://get.scoop.sh')`

如果照此执行还有问题，截图发到这里。

**Comment by ellenxh18** [comment]
运行 Get-ExecutionPolicy结果是RemoteSigned，怎么办？

**Comment by neolee** [comment]
尝试运行 `iex (new-object net.webclient).downloadstring('https://get.scoop.sh') `，把返回结果截屏发到这里给我看看。

**Comment by ellenxh18** [comment]
Initializing...
Downloading scoop...
Extracting...
Creating shim...
Downloading main bucket...
Extracting...
Adding ~\scoop\shims to your path.
iex : 使用“3”个参数调用“SetEnvironmentVariable”时发生异常:“尝试执行未经授权的操作。”
所在位置 行:1 字符: 1
+ iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-Expression], MethodInvocationException
    + FullyQualifiedErrorId : UnauthorizedAccessException,Microsoft.PowerShell.Commands.InvokeExpressionCommand

**Comment by neolee** [comment]
如果运行这个呢：iwr -useb get.scoop.sh | iex

**Comment by ellenxh18** [comment]
Initializing...                                                                                                 
Downloading scoop...                                                                                            
Extracting...                                                                                                   
Creating shim...                                                                                                
Downloading main bucket...                                                                                      
Extracting...                                                                                                   
Adding ~\scoop\shims to your path.                                                                              
iex : 使用“3”个参数调用“SetEnvironmentVariable”时发生异常:“尝试执行未经授权的操作。”                                                    
所在位置 行:1 字符: 26                                                                                                 
+ iwr -useb get.scoop.sh | iex                                                                                  
+                          ~~~                                                                                  
    + CategoryInfo          : NotSpecified: (:) [Invoke-Expression], MethodInvocationException                  
    + FullyQualifiedErrorId : UnauthorizedAccessException,Microsoft.PowerShell.Commands.InvokeExpressionCommand

**Comment by ellenxh18** [comment]
windows10,  返回5

**Comment by neolee** [comment]
我猜想你的 Windows 登录账号可能权限不足，可以试试下面的方法：

1. 在 C 盘根目录下创建目录 C:\Code\scoop
2. 打开一个 PowerShell 窗口，运行 `Set-ExecutionPolicy RemoteSigned -scope CurrentUser`
3. 然后运行 `[environment]::setEnvironmentVariable('SCOOP','C:\Code\scoop','User')`
4. 然后 `$env:SCOOP='C:\Code\scoop'`
5. 上面两步把 Scoop 的安装目录设置为你之前建立的目录（你有权限访问的），然后再尝试安装 Scoop：`iwr -useb get.scoop.sh | iex`

这个方案我自己没试过，你试过之后告诉我结果。

**Comment by ellenxh18** [comment]
PS C:\Users\ellen> [environment]::setEnvironmentVariable('SCOOP','C:\Code\scoop','User')
使用“3”个参数调用“SetEnvironmentVariable”时发生异常:“尝试执行未经授权的操作。”
所在位置 行:1 字符: 1
+ [environment]::setEnvironmentVariable('SCOOP','C:\Code\scoop','User')
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : UnauthorizedAccessException

**Comment by neolee** [comment]
你能截个图吗？

**Comment by ellenxh18** [comment]
是不是因为我的Windows10是家庭版，无法设置管理员权限？

**Comment by neolee** [comment]
说实话我对 Windows 不是特别熟悉，但是你的问题非常像是你的登录账号权限不足，但我理解即使家庭版也应该有管理员（Administrator）账号才对呀；而且我后面给你的办法，其实并不需要管理员账号，因为修改的都是普通的、你自己刚刚创建的目录而已……

另外，你需要运行的是 [environment]::SetEnvironmentVariable('SCOOP','C:\Code\scoop','User')

有两个方括号的。

**Comment by neolee** [comment]
有同学通过在 ConEmu 中打开一个管理员权限的 PowerShell (Admin) 窗口，在其中安装 Scoop 而解决这个问题，有类似错误提示的同学可以试一下。

**Comment by summercool2020** [comment]
> 我猜想你的 Windows 登录账号可能权限不足，可以试试下面的方法：
> 
> 1. 在 C 盘根目录下创建目录 C:\Code\scoop
> 2. 打开一个 PowerShell 窗口，运行 `Set-ExecutionPolicy RemoteSigned -scope CurrentUser`
> 3. 然后运行 `[environment]::setEnvironmentVariable('SCOOP','C:\Code\scoop','User')`
> 4. 然后 `$env:SCOOP='C:\Code\scoop'`
> 5. 上面两步把 Scoop 的安装目录设置为你之前建立的目录（你有权限访问的），然后再尝试安装 Scoop：`iwr -useb get.scoop.sh | iex`
> 
> 这个方案我自己没试过，你试过之后告诉我结果。
