### ISSUE TITLE
这是错在哪里了呢

### ISSUE THREAD

**Issue by zouwenxi** [neolee/pilot#170]
PS C:\Users\Administrator\Code> code.
code. : 无法将“code.”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检
查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ code.
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (code.:String) [], CommandNotFou
   ndException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by zouwenxi** [comment]
Windows PowerShell
版权所有 (C) Microsoft Corporation。保留所有权利。

PS C:\Users\Administrator> cd Code
PS C:\Users\Administrator\Code> code.
code. : 无法将“code.”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检
查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ code.
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (code.:String) [], CommandNotFou
   ndException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\Administrator\Code> PS C:\Users\Administrator\Code> code. code. : 无 法将“code.”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检 查名称的拼写，如
果包括路径，请确保路径正确，然后再试一次。 所在位置 行:1 字符: 1 + code. + ~~~~~
    + CategoryInfo          : ObjectNotFound: (code.:String) [], CommandNotFou
  ndException     + FullyQualifiedErrorId : CommandNotFoundException

**Comment by neolee** [comment]
`code` 和 `.` 之间需要一个空格。
