### ISSUE TITLE
运行python -v后出现问题。请老师指导

### ISSUE THREAD

**Issue by zhangxuelian1984** [neolee/pilot#171]
下载过两次Python 第一次写错命令了。但是下载了一部分。
后来又下载了一次。
然后就这样了。
![QQ图片20191028142707](https://user-images.githubusercontent.com/56957795/67657455-c4de7c00-f991-11e9-83aa-d7113a6078fb.png)
![QQ图片20191028142719](https://user-images.githubusercontent.com/56957795/67657459-c8720300-f991-11e9-8af4-82c1eb1708a5.png)

**Comment by zhangxuelian1984** [comment]
第一次下载Python命令写成了scoop install python@3.7.4    缺个37  后来发现了。不知道怎么退出就直接把窗口关闭了。后来又重新下载的不知道是不是成功了？
老师需要把之前下载的错误的版本删除掉吗？怎么操作

**Comment by neolee** [comment]
上面你其实已经进入 Python 的交互式编程界面了，可以输入 `exit()` 回车退出，然后运行 'python -V' 大写的 V，会看到 Python 的版本号。

看上去应该是没啥问题的。

**Comment by zhangxuelian1984** [comment]
![QQ图片20191028151751](https://user-images.githubusercontent.com/56957795/67658972-27397b80-f996-11e9-91eb-6442a2fd16a7.png)

**Comment by zhangxuelian1984** [comment]
版本号出来了。谢谢老师

**Comment by zhangxuelian1984** [comment]
![QQ图片20191028152002](https://user-images.githubusercontent.com/56957795/67659067-74b5e880-f996-11e9-8949-59f26aa7769a.png)

**Comment by neolee** [comment]
先运行 scoop update，成功之后再安装 busybox。

**Comment by zhangxuelian1984** [comment]
哦哦。明白了。十分感谢老师的解答。
