### ISSUE TITLE
安装 Scoop 时出现的这个问题怎么解决

### ISSUE THREAD

**Issue by yuzanzan** [neolee/pilot#172]
![image](https://user-images.githubusercontent.com/54825122/67658690-4683d900-f995-11e9-8789-cbb68358bddc.png)

**Comment by neolee** [comment]
网络问题，你能打开 [Scoop 主页](https://scoop.sh/) 吗？

**Comment by yuzanzan** [comment]
![image](https://user-images.githubusercontent.com/54825122/67659103-8ac3a900-f996-11e9-8b08-d6211b52f785.png)
是这个吗？

**Comment by yuzanzan** [comment]
> 网络问题，你能打开 [Scoop 主页](https://scoop.sh/) 吗？

![image](https://user-images.githubusercontent.com/54825122/67659468-5997a880-f997-11e9-9870-8ae4b3823f1d.png)
是这个吗？

**Comment by yuzanzan** [comment]
> 网络问题，你能打开 [Scoop 主页](https://scoop.sh/) 吗？

![image](https://user-images.githubusercontent.com/54825122/67659746-125de780-f998-11e9-9239-fd42b9a4732f.png)
这个地方返回的不是Restricted

**Comment by neolee** [comment]
已经是 RemoteSigned 没问题，继续执行安装命令就好。

**Comment by yuzanzan** [comment]
> 已经是 RemoteSigned 没问题，继续执行安装命令就好。

![image](https://user-images.githubusercontent.com/54825122/67660916-d37d6100-f99a-11e9-9d2d-08069bb213f8.png)
还是不行

**Comment by yuzanzan** [comment]
> > 已经是 RemoteSigned 没问题，继续执行安装命令就好。
> 
> ![image](https://user-images.githubusercontent.com/54825122/67660916-d37d6100-f99a-11e9-9d2d-08069bb213f8.png)
> 还是不行

请问一下这个问题要怎么解决了，现在就在这里卡住了，无法往下进行了，谢谢！

**Comment by yuzanzan** [comment]
> > 已经是 RemoteSigned 没问题，继续执行安装命令就好。
> 
> ![image](https://user-images.githubusercontent.com/54825122/67660916-d37d6100-f99a-11e9-9d2d-08069bb213f8.png)
> 还是不行

请问一下这个问题要怎么解决呢，现在在这里卡住了，无法往下进行了，谢谢！

**Comment by neolee** [comment]
这是网络问题，链接 Scoop 服务器出错，换网络或者挂代理试试。

**Comment by yuzanzan** [comment]
> 这是网络问题，链接 Scoop 服务器出错，换网络或者挂代理试试。

我第一次安装scoop时候是装起了的，但是在更新scoop数据库时候出现了问题，后来我把scoop卸载了重新安装，就出现了无法连接到远传服务器的问题，我开4G连热点也不行。

**Comment by beihaichenxiong** [comment]
网络问题。我解决了。

**Comment by yuzanzan** [comment]
> 网络问题。我解决了。

请问一下怎么解决

**Comment by trayoung** [comment]
多尝试了几次之后可以了，可能还是网络问题
