### ISSUE TITLE
Python 安装失败

### ISSUE THREAD

**Issue by Guochangyan** [neolee/pilot#173]
Windows PowerShell
版权所有 (C) Microsoft Corporation。保留所有权利。

尝试新的跨平台 PowerShell https://aka.ms/pscore6

PS C:\Users\guocy> scoop install python37
Installing 'python37' (3.7.5) [64bit]
Loading python-3.7.5-amd64.exe from cache
Checking hash of python-3.7.5-amd64.exe ... ok.
Running installer... done.
Linking ~\scoop\apps\python37\current => ~\scoop\apps\python37\3.7.5
Creating shim for 'python'.
Can't shim 'python.exe': File doesn't exist.
PS C:\Users\guocy> scoop list
Installed apps:

  7zip 19.00
  busybox 3244-g48128b9aa
  git 2.23.0.windows.1
  lessmsi 1.6.91
  python37 3.7.5 *failed*

PS C:\Users\guocy>

**Comment by neolee** [comment]
首先运行 `scoop checkup`，按照提示操作，然后卸载并重装 python37。

可以参考 #32

**Comment by Guochangyan** [comment]
PS C:\Users\guocy> scoop list
Installed apps:

  7zip 19.00
  dark 3.11.2
  git 2.23.0.windows.1
  innounp 0.49
  python37 3.7.5 [versions]
  sudo 0.2018.07.25
成功了，谢谢老师。

**Comment by neolee** [comment]
Nice!
