### ISSUE TITLE
python 安装遇到这个版本问题怎么办？

### ISSUE THREAD

**Issue by Erika00** [neolee/pilot#175]
李老师python 安装遇到以下问题怎么办？
PS C:\Users\86180> scoop install python37@3.7.4
WARN  Given version (3.7.4) does not match manifest ()
WARN  Attempting to generate manifest for 'python37' (3.7.4)
'python37' does not have autoupdate capability
couldn't find manifest for 'python37@3.7.4'

**Comment by neolee** [comment]
你成功运行了 `scoop bucket add versions` 和 `scoop update` 了么？

**Comment by Erika00** [comment]
PS C:\Users\86180> scoop bucket add version
Unknown bucket 'version'. Try specifying <repo>.
usage: scoop bucket add <name> [<repo>]
PS C:\Users\86180> scoop update
Updating Scoop...
Updating 'main' bucket...
Checking repo... ok
The main bucket was added successfully.
Scoop was updated successfully!
到这里应该都成功了

**Comment by Erika00** [comment]
![image](https://user-images.githubusercontent.com/52418630/67670883-ce76dc80-f9af-11e9-819f-07fc90a37959.png)

**Comment by neolee** [comment]
```
PS C:\Users\86180> scoop bucket add version
Unknown bucket 'version'. Try specifying .
usage: scoop bucket add []
```

这一个命令失败了，这里告诉你了，不认识 `version` 这个 bucket，其实应该是 `versions`。

从这个开始都重新来一遍。

**Comment by neolee** [comment]
哈哈，不会的。你的 Python 好了，可以继续了。
