### ISSUE TITLE
 python -m pip install --upgrade pip

### ISSUE THREAD

**Issue by Jenny0523** [neolee/pilot#176]
cannot update 
![QQ图片20191028174137](https://user-images.githubusercontent.com/48664589/67668189-67a2f480-f9aa-11e9-9509-9b945eb56b22.png)
python -m pip install --upgrade pip

**Comment by Jenny0523** [comment]
![微信图片_20191028174455](https://user-images.githubusercontent.com/48664589/67668320-ad5fbd00-f9aa-11e9-8bcc-da68a8ede4de.png)

**Comment by neolee** [comment]
网络问题，下载 pip 包出错了。换网络或者挂代理试试。
