### ISSUE TITLE
运行 pip install 出现红字

### ISSUE THREAD

**Issue by wenwen-shan** [neolee/pilot#177]
![图片](https://user-images.githubusercontent.com/57054269/67668663-58707680-f9ab-11e9-88e6-8019d2cdd873.png)
![图片](https://user-images.githubusercontent.com/57054269/67668826-a84f3d80-f9ab-11e9-898f-3b5d51044b79.png)

![图片](https://user-images.githubusercontent.com/57054269/67668692-6a521980-f9ab-11e9-9429-9577f536074e.png)
![图片](https://user-images.githubusercontent.com/57054269/67668714-7342eb00-f9ab-11e9-9383-fcf37550e322.png)
![图片](https://user-images.githubusercontent.com/57054269/67668742-7ccc5300-f9ab-11e9-94ee-764036621c28.png)

**Comment by neolee** [comment]
网络问题，下载更新 pip 和安装 jupyterlab 包都失败了。需要重新尝试，最好换换网络或者挂代理。

**Comment by Oodonkey** [comment]
老师，我也是这个问题，试了很多回（好几个晚上），切换代理都不行，还有没有别的方法安装啊？

**Comment by neolee** [comment]
@Oodonkey 如果是能够访问国外网络的有效代理，应该是可以解决这类问题的。

**Comment by wenwen-shan** [comment]
好的，谢谢老师，已经下载成功




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Neo Lee"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月29日(星期二) 晚上11:20
收件人:&nbsp;"neolee/pilot"<pilot@noreply.github.com&gt;;
抄送:&nbsp;"1156276431"<1156276431@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [neolee/pilot] 运行 pip install 出现红字 (#177)




可以尝试下增加 pip 下载时的超时限制：python -m pip install -U pip --default-timeout 100 以及 pip install jupyterlab --default-timeout 100
 
不过有些时候是你所在的网络封掉了某些我们需要访问的服务器（甚至整个国外的网络），这种就没办法了，必须使用有效的 VPN 或者代理服务才行。

**Comment by Oodonkey** [comment]
谢谢老师，非常有用，增加了下载时的超时限制就好了。（不过有个疑惑的地方，我在运行pip install jupyterlab --default-timeout 100后，才发现''timeout''打错了，打成了‘’timeou‘’，像这样单词打错误pip是可以识别出来的吗？）

**Comment by neolee** [comment]
@Oodonkey 应该是不能识别的，也许是你运行时网络较好就成功了吧。
