### ISSUE TITLE
在 Visual Studio Code 中新建 hello.py 后安装 Python 插件出错 `error: invalid command 'bdist_wheel'`

### ISSUE THREAD

**Issue by tonylauyu** [neolee/pilot#18]
PS C:\Users\刘浩宇\Documents\code\Test> & C:/Users/刘浩宇/scoop/apps/python/current/python.exe -m pip install -U pylint --user
Collecting pylint
  Using cached https://files.pythonhosted.org/packages/ea/f1/758de486e46ea2b8717992704b0fdd968b7cbc2bc790b976fae4a35a212c/pylint-2.4.3-py3-none-any.whl
Collecting mccabe<0.7,>=0.6 (from pylint)
  Using cached https://files.pythonhosted.org/packages/87/89/479dc97e18549e21354893e4ee4ef36db1d237534982482c3681ee6e7b57/mccabe-0.6.1-py2.py3-none-any.whl
Collecting colorama; sys_platform == "win32" (from pylint)
  Using cached https://files.pythonhosted.org/packages/4f/a6/728666f39bfff1719fc94c481890b2106837da9318031f71a8424b662e12/colorama-0.4.1-py2.py3-none-any.whl
Collecting astroid<2.4,>=2.3.0 (from pylint)
  Using cached https://files.pythonhosted.org/packages/64/d3/4ba68bd56297556c9c2e5072d71d1664feaa86d9726c237a9fe496d440f4/astroid-2.3.2-py3-none-any.whl
Collecting isort<5,>=4.2.5 (from pylint)
  Using cached https://files.pythonhosted.org/packages/e5/b0/c121fd1fa3419ea9bfd55c7f9c4fedfec5143208d8c7ad3ce3db6c623c21/isort-4.3.21-py2.py3-none-any.whl
Collecting lazy-object-proxy==1.4.* (from astroid<2.4,>=2.3.0->pylint)
  Using cached https://files.pythonhosted.org/packages/36/39/d9b7d05775c3d12fe49c1119f53e20adf81757bfd3840f30961a0d57e6d1/lazy-object-proxy-1.4.2.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\刘浩宇\scoop\apps\python\current\python.exe' 'C:\Users\刘浩宇\scoop\apps\python\current\lib\site-packages\pip\_vendor\pep517\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\刘浩宇\AppData\Local\Temp\tmpbbu2mgus'
         cwd: C:\Users\刘浩宇\AppData\Local\Temp\pip-install-r3cdy6rf\lazy-object-proxy
    Complete output (12 lines):
    running dist_info
    creating C:\Users\刘浩宇\AppData\Local\Temp\pip-install-r3cdy6rf\lazy-object-proxy\pip-wheel-metadata\lazy_object_proxy.egg-info
    writing C:\Users\刘浩宇\AppData\Local\Temp\pip-install-r3cdy6rf\lazy-object-proxy\pip-wheel-metadata\lazy_object_proxy.egg-info\PKG-INFO
    writing dependency_links to C:\Users\刘浩宇\AppData\Local\Temp\pip-install-r3cdy6rf\lazy-object-proxy\pip-wheel-metadata\lazy_object_proxy.egg-info\dependency_links.txt
    writing top-level names to C:\Users\刘浩宇\AppData\Local\Temp\pip-install-r3cdy6rf\lazy-object-proxy\pip-wheel-metadata\lazy_object_proxy.egg-info\top_level.txt
    writing manifest file 'C:\Users\刘浩宇\AppData\Local\Temp\pip-install-r3cdy6rf\lazy-object-proxy\pip-wheel-metadata\lazy_object_proxy.egg-info\SOURCES.txt'
    reading manifest file 'C:\Users\刘浩宇\AppData\Local\Temp\pip-install-r3cdy6rf\lazy-object-proxy\pip-wheel-metadata\lazy_object_proxy.egg-info\SOURCES.txt'
    writing manifest file 'C:\Users\刘浩宇\AppData\Local\Temp\pip-install-r3cdy6rf\lazy-object-proxy\pip-wheel-metadata\lazy_object_proxy.egg-info\SOURCES.txt'
    creating 'C:\Users\刘浩宇\AppData\Local\Temp\pip-install-r3cdy6rf\lazy-object-proxy\pip-wheel-metadata\lazy_object_proxy.dist-info'
    Error in sitecustomize; set PYTHONVERBOSE for traceback:
    SyntaxError: (unicode error) 'utf-8' codec can't decode byte 0xc1 in position 0: invalid start byte (sitecustomize.py, line 7)
    error: invalid command 'bdist_wheel'
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Users\刘浩宇\scoop\apps\python\current\python.exe' 'C:\Users\刘浩宇
\scoop\apps\python\current\lib\site-packages\pip\_vendor\pep517\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\刘浩宇\AppData\Local\Temp\tmpbbu2mgus' Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 19.3.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

**Comment by neolee** [comment]
打开一个 PowerShell 窗口，运行下面几个命令，把结果告诉我（最好截图）：

```shell
$PSVersionTable.PSVersion.Major

scoop checkup
scoop update

which python
python -V
pip -V
pip list
```

**Comment by tonylauyu** [comment]
![python1](https://user-images.githubusercontent.com/56103453/67361776-2c648800-f59c-11e9-97b0-fc21c7d2084d.PNG)
![python2](https://user-images.githubusercontent.com/56103453/67361774-2bcbf180-f59c-11e9-9ad9-a374ea4cbd26.PNG)

**Comment by tonylauyu** [comment]
之前安装python是看视频装的，所以装成3.8最新版本了，

**Comment by neolee** [comment]
几点哈，第一，按照 `scoop checkup` 的建议，运行下面几个命令：

```shell
Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1
scoop install innounp
```

第二，Python 3.8 太新了，很多第三方库还不兼容，所以目前不能用它，你需要删掉它然后严格按照 [配置指南](https://github.com/neolee/pilot/blob/master/x1-setup.md) 操作：

```shell
scoop uninstall python
scoop bucket add versions
scoop update
scoop install python37
```

然后运行下面的命令来测试下：

```shell
python -V
python
```

在打开的 Python REPL 中简单运行些代码试试，比如直接 `exit()` 退出。

**Comment by eiyen** [comment]
我下载的也是 python3.8 ，但在卸载的时候有问题：
![image](https://user-images.githubusercontent.com/52303623/67377809-d3efb380-f5b8-11e9-85fc-dc5d401330b4.png)
上网查询，感觉可能是环境变量的问题，因为我之前操作时不小心把 path 清空了。之后又添了一些，这是我的 path ：
![image](https://user-images.githubusercontent.com/52303623/67378005-216c2080-f5b9-11e9-8f3e-527c8a706455.png)
