### ISSUE TITLE
终端打不开Visual Studio Code

### ISSUE THREAD

**Issue by y60l** [neolee/pilot#180]
安装完Visual Studio Code 之后 显示
![Snip20191028_4](https://user-images.githubusercontent.com/57059825/67671513-0d596200-f9b1-11e9-9ffd-b4cf67fdbcfb.png)
上网查找 得到的解决方案 
![Snip20191028_5](https://user-images.githubusercontent.com/57059825/67671563-27934000-f9b1-11e9-9143-abc7adf63f0d.png)
点仍要打开 能打开了 

接着在终端里输入 code .的时候 报错
![Snip20191028_1](https://user-images.githubusercontent.com/57059825/67671634-498cc280-f9b1-11e9-964a-4af1dfceb670.png)

**Comment by neolee** [comment]
macOS 下 Visual Studio Code 需要配置才能使用命令行里的 code 来打开，具体在配置指南里有说明。
