### ISSUE TITLE
安装 jupyterlab

### ISSUE THREAD

**Issue by y60l** [neolee/pilot#182]
![Snip20191028_6](https://user-images.githubusercontent.com/57059825/67673622-77740600-f9b5-11e9-94b7-d1870054cfa7.png)
![Snip20191028_7](https://user-images.githubusercontent.com/57059825/67673808-eea99a00-f9b5-11e9-8b1c-9d1b06e206c0.png)
![Snip20191028_8](https://user-images.githubusercontent.com/57059825/67673811-f0735d80-f9b5-11e9-9e4d-b687e3aea709.png)
![Snip20191028_9](https://user-images.githubusercontent.com/57059825/67673816-f23d2100-f9b5-11e9-94bc-7fb1477e1cdd.png)

**Comment by neolee** [comment]
你的系统里 python 这个命令指向的是系统自带的 Python 2.7，你可以通过 `python -V` 查看版本来确认这一点。

如果你安装 Homebrew 成功，用 `brew install python` 也成功了的话，你的系统里也安装好了 Python 3.7.4，但需要用 `python3` 来使用，你可以用 `python3 -V` 查看版本来确认；同理，安装 Python 软件包也要用 `pip3`。所以，你可以试试下面的命令：

```shell
pip3 install -U pip
pip3 jupyterlab
```

**Comment by banshibao** [comment]
![捕获4](https://user-images.githubusercontent.com/24274761/67695330-d2225780-f9df-11e9-8b96-6852e50bfd49.JPG)
![捕获3](https://user-images.githubusercontent.com/24274761/67695334-d2baee00-f9df-11e9-900f-574d48c8793d.JPG)
安装和运行 Jupyter Lab的出现如上问题，请求如何处理？感谢

**Comment by neolee** [comment]
执行下面几个命令看看：

```powershell
python -V
python3 -V
pip -V
pip3 -V
pip3 list
```

**Comment by y60l** [comment]
![Snip20191029_10](https://user-images.githubusercontent.com/57059825/67752222-98982d80-fa6d-11e9-96ec-38ad23cd67b8.png)

**Comment by y60l** [comment]
卡住了

**Comment by neolee** [comment]
@y60l  不是让你运行那几个命令么？另外几个的结果呢？

**Comment by y60l** [comment]
![image](https://user-images.githubusercontent.com/57059825/67768018-95f90080-fa8c-11e9-9788-412513d1765b.png)
这三个都运行了

**Comment by neolee** [comment]
你仔细看看我前面请你执行的命令是哪些。

**Comment by y60l** [comment]
![Snip20191029_12](https://user-images.githubusercontent.com/57059825/67768542-bb3a3e80-fa8d-11e9-9fe3-6e5c8fef8bf1.png)
抱歉 老师 我没有看清楚 你说的是这些么

**Comment by neolee** [comment]
是上面我发的这个：

<img width="802" alt="Issue Screen" src="https://user-images.githubusercontent.com/24796/67768885-6e0a9c80-fa8e-11e9-8720-aa054ea2a9d7.png">

**Comment by y60l** [comment]
![Snip20191029_14](https://user-images.githubusercontent.com/57059825/67769263-1c164680-fa8f-11e9-8ea5-a48215bec770.png)
哦哦 我以为你在和另一个人说 TAT

**Comment by neolee** [comment]
你这个 Python / pip 不是 Homebrew 装的呀，用的是 /Library/Developer 下面的版本。

你之前怎么安装的？

**Comment by y60l** [comment]
Python / pip 应该是 Homebrew 装的 
![Snip20191028_1](https://user-images.githubusercontent.com/57059825/67770411-4ec13e80-fa91-11e9-8007-3a79fb101f54.png)
这是我昨天的截图 


VScode 装的时候遇到点问题 不知道有没有关系
![Snip20191028_4](https://user-images.githubusercontent.com/57059825/67770552-921bad00-fa91-11e9-9c5f-b29699e5bc37.png)

**Comment by neolee** [comment]
咱能一个问题一个问题来么……前面你的 pip3 -V 输出已经说明了不是 Homebrew 的了。

后面这个问题你需要在系统设置的隐私安全里允许 Visual Studio Code 运行才行。

p.s. 为啥你刚才没在听课而是发 issue 呀？

**Comment by y60l** [comment]
我试着重装了一下 

![Snip20191029_16](https://user-images.githubusercontent.com/57059825/67772524-263b4380-fa95-11e9-9c7b-c209bfee1fd1.png)
![Snip20191029_17](https://user-images.githubusercontent.com/57059825/67772526-28050700-fa95-11e9-95b7-236d1bdcefc1.png)

p.s. 我一般都是第二天早起听回放 要不就起不来的说

**Comment by neolee** [comment]
为啥你命令最后还带着一个 `↩︎` 尾巴？

**Comment by neolee** [comment]
不用，这是有装好的。你的系统里有多套 Python，可以参考下 #67 里我最后一个回复。

你这里要盯着的是 /Library/Developer/CommandLineTools... 那一串。

**Comment by y60l** [comment]
我觉得我在你眼里已经变成了一个二货，你已经说的很明白了，我还是有点懵

我明白的 我的电脑里有多套python 应该调用某一套 只要不调用另一套就没问题 对吧

我不明白的 我和他的选择一样么 

尝试运行pip install jupyterlab 

![Snip20191029_19](https://user-images.githubusercontent.com/57059825/67778362-08261100-fa9e-11e9-887a-1041224067d4.png)

尝试运行~/.bash_profile 

![image](https://user-images.githubusercontent.com/57059825/67778389-1411d300-fa9e-11e9-88f0-ff02c11a9826.png)

**Comment by logdazy** [comment]
哈哈哈 我看乐了。仿佛看到了自己

**Comment by neolee** [comment]
@y60l 

你的系统里没有 pip，只有 pip3，所以需要用 `pip3 install -U pip` 和 `pip3 install jupyter lab`。但在此之前需要先搞定清理旧 Python 环境，否则会越搞越乱。

清理的方法有二：1. 搞清楚之前怎么装的，找到卸载方法，完整卸载；2. 用 `code ~/.bash_profile` 打开命令行配置文件，找到 PATH 变量设置，看看里面有没有那个可疑路径，有的话去掉。

后面这个方法对你有一定要求，没有把握的话建议慎重。

**Comment by y60l** [comment]
我之前应该是没装过python2

好像是系统自带的 

平常都是用Windows系统 

mac小白yi'mz

**Comment by neolee** [comment]
系统自带的 2.7 的 Python 不碍事，它的优先级低于你在 Homebrew 安装的 3.7.4，现在的问题出在  /Library/Developer/CommandLineTools... 下面那个来历不明 Python。

**Comment by y60l** [comment]
是这个么 我直接删可以么

![Snip20191031_25](https://user-images.githubusercontent.com/57059825/67905786-83c2b380-fbad-11e9-927e-d948f5f6f2eb.png)

**Comment by neolee** [comment]
直接删除比较危险，但如果实在没办法了，把这个目录移动到别的地方试试吧。

**Comment by y60l** [comment]
我把名改了 
![Snip20191031_26](https://user-images.githubusercontent.com/57059825/67941813-6fb09d80-fc11-11e9-83ea-a14ae0a90cb0.png)
![Snip20191031_27](https://user-images.githubusercontent.com/57059825/67941819-7212f780-fc11-11e9-940d-dad99ecfe1a0.png)

**Comment by y60l** [comment]
![image](https://user-images.githubusercontent.com/57059825/67942886-d6cf5180-fc13-11e9-988e-207e28ee53df.png)

我好像成功了 感谢老师细心指导

**Comment by y60l** [comment]
遇到了新的问题 好像是之前的遗留

![Snip20191031_30](https://user-images.githubusercontent.com/57059825/67943820-e2237c80-fc15-11e9-9acd-73870d95234f.png)

改成 python3 hello.py
![Snip20191031_31](https://user-images.githubusercontent.com/57059825/67943877-01220e80-fc16-11e9-9997-0fcfd9c58ade.png)

**Comment by neolee** [comment]
用 `python3` 运行，不要用 `python`；还有你输入的 python 前面那是些啥，搞清楚你输入的命令，像我周二课上讲的。

**Comment by y60l** [comment]
![image](https://user-images.githubusercontent.com/57059825/67945855-ebfbae80-fc1a-11e9-8410-6a2f4902461f.png)
找到原因了 我是直接照着JupyterLab里操作的 一点就变成这样了

**Comment by neolee** [comment]
这个前面说了啊，你的系统里 `python` 是老的，所以只能用 `python3`。
