### ISSUE TITLE
'openssh' doesn't support 32bit architecture!&

### ISSUE THREAD

**Issue by myhappylife2002** [neolee/pilot#183]
与119#类似。
相较于119#问题，我的这个问题可能更具体一点：我理解为不支持32位系统，不知该如何解决。
![微信图片1](https://user-images.githubusercontent.com/57083738/67674606-ef433000-f9b7-11e9-8864-969abea76c90.jpg)
![微信图片2](https://user-images.githubusercontent.com/57083738/67674609-f23e2080-f9b7-11e9-9311-da8ba37d77e8.jpg)
第一天用github,不知这样问老师问题方式是否正确。

**Comment by myhappylife2002** [comment]
很纳闷：图片为什么是倒着的

**Comment by myhappylife2002** [comment]
不好意思，图片本来是正着的，不知为什么上传上来成倒着的了

**Comment by neolee** [comment]
你并不需要安装 openssl，我们用不到这个包。

你直接按照配置指南继续就好了。

**Comment by myhappylife2002** [comment]
好的  谢谢李老师
