### ISSUE TITLE
自检 scoop 出现如下红字

### ISSUE THREAD

**Issue by jiucaidejianxing** [neolee/pilot#185]
![image](https://user-images.githubusercontent.com/56495862/67677890-2ae1f800-f9c0-11e9-9808-a404d7d1d301.png)

**Comment by neolee** [comment]
自检建议你运行这么几个命令：

```powershell
Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1
scoop install innounp dark
```

你运行第一行的时候出现了权限不足的错误，没有运行成功。有同学碰到一样的问题，说开一个 {{ PowerShell (Admin) }} 的 tab，可以运行成功，但我没有试过，你可以试一下。

而上面第二行应该是可以成功的，你可以试着执行下。

然后就可以按照指南继续了。
