### ISSUE TITLE
安装python37@3.7.4时出错，请看图

### ISSUE THREAD

**Issue by kelvinqy** [neolee/pilot#187]
![1572269802(1)](https://user-images.githubusercontent.com/52500863/67682846-3b4ba000-f9cb-11e9-9e0c-950d82069feb.png)

**Comment by neolee** [comment]
你有添加 versions bucket 吗？配置指南里有说明如何操作。

**Comment by kelvinqy** [comment]
> 你有添加 versions bucket 吗？配置指南里有说明如何操作。

已安装好，多谢~~~
