### ISSUE TITLE
教材章节无法打开，提示出了问题。

### ISSUE THREAD

**Issue by zsqiang001** [neolee/pilot#188]
#网络正常，反复点击教材章节无法显示，提示出了问题。笑来老师的自学是门手艺也是如此。这是github网站的问题吗？

**Comment by neolee** [comment]
什么样的提示？

**Comment by zsqiang001** [comment]
提示：Sorry, something went wrong.Reload? Reload 之后还是打不开。笑来老师的自学是门手艺的章节也是这个提示。

**Comment by neolee** [comment]
[主仓库说明](https://github.com/neolee/pilot/blob/master/README.md) 里有说明，参看“重要的附注”一节。

**Comment by zsqiang001** [comment]
好的，谢谢。惭愧，看书还是不仔细。问题解决了。
