### ISSUE TITLE
Scoop 安装时出错 `The remote name could not be resolved: 'get.scoop.sh'`

### ISSUE THREAD

**Issue by zechenglu** [neolee/pilot#19]
Exception calling "DownloadString" with "1" argument(s): "The remote name could  not be resolved: 'get.scoop.sh'"
At line:1 char:1
+ iex (new-object net.webclient).downloadstring('https://get.scoop.sh')
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException

**Comment by neolee** [comment]
这个看上去是网络问题，你能成功打开 [Scoop 的主页](https://scoop.sh/) 吗？如果可以，就多试几次那个安装命令。

**Comment by zechenglu** [comment]
打不开， 这个还需要翻墙吗？

**Comment by zechenglu** [comment]
如果需要翻墙，是否可以推荐或提供翻墙软件呢

**Comment by neolee** [comment]
一般来说是不需要的，可能和你的网络服务提供商有关。

**Comment by zechenglu** [comment]
除了换网络别的还有什么办法往下进行吗？

**Comment by neolee** [comment]
可以使用网络代理试试，需要你自己找一下。
