### ISSUE TITLE
老师，装了多少次都不行，不知道自己哪一步出错了，求指教。

### ISSUE THREAD

**Issue by tonychen87** [neolee/pilot#191]
![image](https://user-images.githubusercontent.com/51992507/67690208-7227b300-f9d7-11e9-92fb-2bd2cfe02333.png)

**Comment by neolee** [comment]
RemoteSigned 和 -scope 之间漏了一个空格。

**Comment by tonychen87** [comment]
好的，我试试看，谢谢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Neo Lee"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月28日(星期一) 晚上11:09
收件人:&nbsp;"neolee/pilot"<pilot@noreply.github.com&gt;;
抄送:&nbsp;"Tony"<568647619@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [neolee/pilot] 老师，装了多少次都不行，不知道自己哪一步出错了，求指教。 (#191)




RemoteSigned 和 -scope 之间漏了一个空格。

**Comment by tonychen87** [comment]
老师，还是不行，不知道什么回事。难受





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Neo Lee"<notifications@github.com&gt;;
发送时间:&nbsp;2019年10月28日(星期一) 晚上11:09
收件人:&nbsp;"neolee/pilot"<pilot@noreply.github.com&gt;;
抄送:&nbsp;"Tony"<568647619@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [neolee/pilot] 老师，装了多少次都不行，不知道自己哪一步出错了，求指教。 (#191)




RemoteSigned 和 -scope 之间漏了一个空格。
