### ISSUE TITLE
pip 安装 jupyterlab 出错：could not find a version safisfies...

### ISSUE THREAD

**Issue by tigersummer** [neolee/pilot#192]
![Cutter_12](https://user-images.githubusercontent.com/48619978/67694024-ab632180-f9dd-11e9-91b4-d1d0167d8005.png)

**Comment by neolee** [comment]
执行下面两个命令看看：

```powershell
pip -V
pip list
```

**Comment by hbfphqt** [comment]
![image](https://user-images.githubusercontent.com/37977479/67929863-63204b00-fbf9-11e9-8a3f-f99e020559af.png)

**Comment by neolee** [comment]
你的 pip 似乎没有装好，试试 `python -m ensurepip` 然后 `python -m pip install --upgrade pip`。
