### ISSUE TITLE
Git Commit 出错-- please tell me who you are

### ISSUE THREAD

**Issue by imagelan** [neolee/pilot#194]
出错提示：

![image](https://user-images.githubusercontent.com/48951128/67726408-bef99280-f9b3-11e9-810e-75f340ce55de.png)

之后我按照提示， 输入 Git config

![image](https://user-images.githubusercontent.com/48951128/67726436-da649d80-f9b3-11e9-8a09-1e7b699e7225.png)

![image](https://user-images.githubusercontent.com/48951128/67726449-e5b7c900-f9b3-11e9-8247-916e9fde6958.png)

我是在退出Jupyter Lab 之后进行如上操作。但是不成功。
谢谢

**Comment by neolee** [comment]
Duplicate of #34
