### ISSUE TITLE
git clone 过程网络中断后重试显示如下信息

### ISSUE THREAD

**Issue by kelvinqy** [neolee/pilot#196]
![1572323403(1)](https://user-images.githubusercontent.com/52500863/67737957-e732d100-fa47-11e9-94a7-b3b13c788e16.png)

**Comment by neolee** [comment]
先把本地残留的目录删掉：

```powershell
del -Force pilot-student
```

然后再重试 clone。以后如果出现这个问题也是类似的原因。

**Comment by kelvinqy** [comment]
收到，已删除，正在重新安装，多谢。
del -Force pilot-student
强力删除，哈
再请教您一下，我看您的字母大小写都很规范，这个是必须的吗？

**Comment by neolee** [comment]
不算必须，但在计算机里，尤其写程序，很多时候是大小写敏感的，养成习惯比较好。

**Comment by kelvinqy** [comment]
收到，谢谢老师~
