### ISSUE TITLE
3-structure-2前面运行正常，此部分突然显示C未赋值

### ISSUE THREAD

**Issue by wenwen-shan** [neolee/pilot#197]
前面运行正常，a,b都已赋值，可以正常运算，在向C赋值时，无输出结果，也无错误显示，将a,b 在同一部分重新赋值，也无结果，后期运算显示C未赋值，是否是输入代码框错误，如何调整呢？

![图片](https://user-images.githubusercontent.com/57054269/67738031-282ae580-fa48-11e9-9d46-f6e7b30844fe.png)

![图片](https://user-images.githubusercontent.com/57054269/67738041-2bbe6c80-fa48-11e9-980f-e0ab097de845.png)

**Comment by neolee** [comment]
因为 Python 是区分大小写的，大写的 C 和小写的 c 不一样，你前面用的都是小写的，大写 C 这个变量确实没定义呀。
