### ISSUE TITLE
老师，一直报错。请教是什么原因

### ISSUE THREAD

**Issue by xiaofeidong2028** [neolee/pilot#198]
![无标题1](https://user-images.githubusercontent.com/56985358/67745955-6fbd6b80-fa60-11e9-9605-d26b2a3b2d17.png)

**Comment by neolee** [comment]
你这个也太后面了吧……

这里出错应该是前面有些代码每执行或者没做对，光看这个片段无法判断。

**Comment by xiaofeidong2028** [comment]
好的，谢谢！我再研究研究发自我的华为手机-------- 原始邮件 --------主题：Re: [neolee/pilot] 老师，一直报错。请教是什么原因 (#198)发件人：Neo Lee 收件人：neolee/pilot 抄送：xiaofeidong2028 ,Author 你这个也太后面了吧……

这里出错应该是前面有些代码每执行或者没做对，光看这个片段无法判断。
