### ISSUE TITLE
启动 jupyterlab  浏览器不显示学习用书怎么办？

### ISSUE THREAD

**Issue by Erika00** [neolee/pilot#199]
之前安装好了，启动jupyterlab  浏览器能看到跟老师视频讲解的一样页面内容，退出来，重新再来就出问题了
![fd7d485601ee046027d1050ef95afcbe](https://user-images.githubusercontent.com/52418630/67746639-d8f1ae80-fa61-11e9-95e4-f84ed6560629.jpg)
![$T$M`X`4RE5D}之前安装好了，启动jupyterlab  浏览器能看到跟老师视频讲解的一样页面内容，退出来，重新再来就出问题了
![fd7d485601ee046027d1050ef95afcbe](https://user-images.githubusercontent.com/52418630/67746639-d8f1ae80-fa61-11e9-95e4-f84ed6560629.jpg)
 C45G_L](https://user-images.githubusercontent.com/52418630/67746658-e018bc80-fa61-11e9-81fc-fc6a1f815a43.png)
![Y$U%GZ N29GJMTNVVLOH18O](https://user-images.githubusercontent.com/52418630/67746663-e3ac4380-fa61-11e9-8f78-d62ebaff6aa5.png)

**Comment by neolee** [comment]
因为你跑到别的目录下去了啊，你要在你 clone 回来的学习用书目录下执行 `jupyter lab` 才行。

p.s. 点击这个页面上方的 Wiki，里面支线课程第一讲里有些基础知识，你可以先看看。

**Comment by Erika00** [comment]
好的，谢谢老师，非常感谢
