### ISSUE TITLE
homebrew安装失败

### ISSUE THREAD

**Issue by maaluakong** [neolee/pilot#2]
安装过程中，提示fatal: unable to access 'https://github.com/Homebrew/brew/': LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54

请问怎么解决

**Comment by maaluakong** [comment]
> 这个是网络问题，访问 Homebrew 的服务失败，可能需要换个网络或者使用 https 代理。

正在解决中，谢谢

**Comment by neolee** [comment]
中科大有 Homebrew 的镜像，我还在测试，你也可以试试看：

https://lug.ustc.edu.cn/wiki/mirrors/help/brew.git
https://lug.ustc.edu.cn/wiki/mirrors/help/homebrew-bottles

**Comment by neolee** [comment]
你可以试试这个：

https://www.jianshu.com/p/6523d3eee50d

**Comment by moonwmh** [comment]
> 你可以试试这个：
> 
> https://www.jianshu.com/p/6523d3eee50d

小白，看不懂，一顿操作还是失败啊

**Comment by moonwmh** [comment]
一整往终端里猛粘贴，神奇的事情发生了，装好了！
编程确实是提高自学能力的最好方式。

**Comment by maaluakong** [comment]
已安装成功 ！

**Comment by xiaoerdege** [comment]
> 一整往终端里猛粘贴，神奇的事情发生了，装好了！
> 编程确实是提高自学能力的最好方式。

你是怎么粘贴的？每一个都回车了吗？我的也是复制粘贴没反应啊！
