### ISSUE TITLE
输入 jupyter lab 不能自动打开浏览器

### ISSUE THREAD

**Issue by tonylauyu** [neolee/pilot#20]
![jupyter](https://user-images.githubusercontent.com/56103453/67365646-954ffe00-f5a4-11e9-8596-191df9ecc116.PNG)

**Comment by neolee** [comment]
试试选择 http://localhost:8889 打头的那行，拷贝并贴到浏览器的地址栏，能打开吗？

**Comment by tonylauyu** [comment]
能打开

**Comment by neolee** [comment]
那么 JupyterLab 工作是正常的，你可以继续。

不能自动打开浏览器原因很多，可能是你的系统里没有设置打开 http 网址的缺省浏览器，或者安全规则受限。
