### ISSUE TITLE
 jupyter lab 打开的浏览器里，没有内容，请教~

### ISSUE THREAD

**Issue by kelvinqy** [neolee/pilot#200]
![1572335429(1)](https://user-images.githubusercontent.com/52500863/67747548-ef990500-fa63-11e9-8fac-c7e3095900cc.png)

**Comment by neolee** [comment]
Jupyter Lab 不支持老的 IE，用 Windows 10 自带的 Microsoft Edge，或者 Chrome、Firefox 或者其他比较新的浏览器都可以。

**Comment by kelvinqy** [comment]
我日常用的是Chrome，这个IE是输入命令后自动跳出来的。我该如何调整
纯小白，给老师添麻烦了~

**Comment by kelvinqy** [comment]
老师，我找到了，设置了默认浏览器，Chrome。哈哈

**Comment by neolee** [comment]
Nice!
