### ISSUE TITLE
安装 homebrew 出现 curl: (7) Failed to connect to raw.githubusercontent.com port 443: Operation timed out

### ISSUE THREAD

**Issue by xiaoerdege** [neolee/pilot#202]
李老师安装homebrew 出现这个提示：curl: (7) Failed to connect to raw.githubusercontent.com port 443: Operation timed out
这个是什么情况呢？Macos现在是最新的版本啦

**Comment by getjake** [comment]
由于网络原因造成的，请自行Google 搜索科学上网方法。 若使用代理而非VPN，还需 "Copy HTTP Proxy Shell Commandline"

**Comment by ganyixin** [comment]
@getjake 您好，我也遇到了这个问题，我现在使用代理后能正常使用科学上网，但继续安装 homebrew再一次出现curl: (7) Failed to connect to raw.githubusercontent.com port 443: Operation timed out
的提示。 我尝试了一下通过Chrome能浏览任何一个网页，但Safari不能打开google。请告知一下您说的还需 "Copy HTTP Proxy Shell Commandline"如何设置呢？ 非常感谢

**Comment by liuleis** [comment]
> 由于网络原因造成的，请自行Google 搜索科学上网方法。 若使用代理而非VPN，还需 "Copy HTTP Proxy Shell Commandline"

求教：我已经是科学上网了，为啥还有同样的错误提示？

**Comment by liuleis** [comment]
> > 由于网络原因造成的，请自行Google 搜索科学上网方法。 若使用代理而非VPN，还需 "Copy HTTP Proxy Shell Commandline"
> 
> 求教：我已经是科学上网了，为啥还有同样的错误提示？

Copy HTTP Proxy Shell Command Line 到终端后解决了。

**Comment by wenlittleoil** [comment]
> > > 由于网络原因造成的，请自行Google 搜索科学上网方法。 若使用代理而非VPN，还需 "Copy HTTP Proxy Shell Commandline"
> > 
> > 
> > 求教：我已经是科学上网了，为啥还有同样的错误提示？
> 
> Copy HTTP Proxy Shell Command Line 到终端后解决了。

你好，我也是科学上网后还有这样的错误提示，请问具体如何Copy HTTP Proxy Shell Command Line，我用的科学上网工具是GoogleHelper插件走代理。
