### ISSUE TITLE
Jupyter 填令牌过后没反应

### ISSUE THREAD

**Issue by MoofersLAon** [neolee/pilot#204]
![微信图片_20191029193110](https://user-images.githubusercontent.com/49604516/67763967-d30cc500-fa83-11e9-9e75-c8c66010b467.png)
![微信图片_20191029193132](https://user-images.githubusercontent.com/49604516/67763969-d3a55b80-fa83-11e9-88e7-bea2606aebe4.png)

**Comment by neolee** [comment]
直接从运行 jupyter lab 的命令行窗口里拷贝 `http:localhost:` 开头的那一整行到浏览器地址栏，回车。

**Comment by MoofersLAon** [comment]
> 直接从运行jupyter lab的命令行窗口里拷贝`http:localhost:`开头的那一整行到浏览器地址栏，回车。

试了一下，但这次计算机直接跳转到Jupyter Lab学习用书的文件里去了，现在我该怎么办呢，是已经好了吗？
![微信图片_20191029203826](https://user-images.githubusercontent.com/49604516/67767969-84175d80-fa8c-11e9-954a-48a981d228bc.png)

**Comment by neolee** [comment]
左边目录列表的显示怎么乱糟糟的，是你开了什么翻译软件么？

其他没啥，这就行了，你可以打开对应章节学习了。

**Comment by MoofersLAon** [comment]
> 左边目录列表的显示怎么乱糟糟的，是你开了什么翻译软件么？
> 
> 其他没啥，这就行了，你可以打开对应章节学习了。

好嘞，谢谢老师。虽然有点懵，但我多试试吧...
