### ISSUE TITLE
运行 pip install jupyterlab 时出现问题

### ISSUE THREAD

**Issue by banshibao** [neolee/pilot#205]
在执行pip install jupyterlab已经执行过：
python -V
python3 -V
pip -V
pip3 -V
pip3 list
但还是出现问题，如下图：
![2019-10-29_202009](https://user-images.githubusercontent.com/24274761/67766683-f0449200-fa89-11e9-84c4-9a4191e6f2d9.jpg)
请求如何解决？

**Comment by neolee** [comment]
首先，因为安装 Jupyter Lab 没有成功（`pip install jupyterlab`），所以后面运行 `jupyter lab` 自然不行。

然是 Jupyter Lab 不成功的原因还不清楚，报出来的错误信息是是说找不到某个依赖的包，但这是不应该发生的，你试试用下面的命令：

```powershell
pip --no-cache-dir install jupyterlab
```

p.s. 刚才我在讲课呀，为什么你没听课而是在发 issue 呢？

**Comment by wangbingfeng** [comment]
pip install jupyterlab --default-timeout 100

ps: 后面的100 意思是超时设置为100秒，默认是15秒。

**Comment by yayuehuizi** [comment]
可以试试安装pip3 install jupyterlab，我之前安装pip不行，就试了几次pip3成功的，不过有时也要看网速
