### ISSUE TITLE
ConEmu主页如何找Alpha版本?  只找到Preview版本

### ISSUE THREAD

**Issue by Merezhu** [neolee/pilot#206]
> 进入 ConEmu 首页，点击 Download 按钮，选择下载 “ConEmu Alpha, Installer (32-bit, 64-bit)” 这个安装器版本；

老师，根据指南，点击指南链接进入ConEmu主页并点击Download之后，只有Preview版本，整个Site没有找到Alpha版本的下载链接。 请问怎么操作呢?

![image](https://user-images.githubusercontent.com/36255603/67769465-83cc9180-fa8f-11e9-8a7a-9eb6706c9ee0.png)

**Comment by neolee** [comment]
可以就下这个 Preview 版本的，有时候他们把 Alpha 改为 Preview 版本，然后还没有新的 Alpha 版本，就会这样……

**Comment by Merezhu** [comment]
已解决，点击“Download” 之后，点击 ”OLDER VERSIONS” 就可以找到Alpha版本（注： 这竟然是个链接。。而不只是个标题）

![image](https://user-images.githubusercontent.com/36255603/67770120-b62abe80-fa90-11e9-99cf-9d5efa6b900f.png)

谢谢老师修改：标题中英文之间要有空格

**Comment by Merezhu** [comment]
![image](https://user-images.githubusercontent.com/36255603/67770205-e4a89980-fa90-11e9-95da-ecd088d73821.png)

**Comment by neolee** [comment]
@Merezhu 不需要去找这个，如果下载页只有 Preview，那个就是最新的。
