### ISSUE TITLE
一直没有找到 nbviewer 的连接地址

### ISSUE THREAD

**Issue by MoofersLAon** [neolee/pilot#207]
为什么我照抄老师视频里的链接依然不行呢？
![image](https://user-images.githubusercontent.com/49604516/67770172-d490ba00-fa90-11e9-8582-9d797c20006c.png)

**Comment by MoofersLAon** [comment]
为什么我照抄老师视频里的链接依然不行呢？
![image](https://user-images.githubusercontent.com/49604516/67770125-b88d1880-fa90-11e9-8b16-8f370edfb300.png)

**Comment by neolee** [comment]
这个地址是： https://nbviewer.jupyter.org/

然后把你打开有问题的那个 ipynb 的网址贴到上面页面的输入框里回车就好。

你其实不需要照着视频抄地址，在我们主仓库的 README 里就有，你找“重要的附注”一节就可以了。

**Comment by MoofersLAon** [comment]
好嘞，刚刚听了老师讲的课，太棒了！
