### ISSUE TITLE
安装 scoop 之后 scoop update 不了

### ISSUE THREAD

**Issue by beihaichenxiong** [neolee/pilot#208]
PS C:\Users\lenovo> Get-ExecutionPolicy
RemoteSigned
PS C:\Users\lenovo> iwr -useb get.scoop.sh | iex
Initializing...
Scoop is already installed. Run 'scoop update' to get the latest version.
PS C:\Users\lenovo> scoop list
scoop : 无法将“scoop”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ scoop list
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (scoop:String) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\lenovo> scoop install git
scoop : 无法将“scoop”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ scoop install git
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (scoop:String) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\lenovo> iwr -useb get.scoop.sh | iex
Initializing...
Scoop is already installed. Run 'scoop update' to get the latest version.
PS C:\Users\lenovo> scoop update
scoop : 无法将“scoop”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ scoop update
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (scoop:String) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\lenovo>

**Comment by wangbingfeng** [comment]
在安装完成scoop后，先关闭powershell, 再打开powershell, 执行你的命令。如果直接执行，会出现你截图类似问题
