### ISSUE TITLE
打开学习用书时，浏览器总是加载不了，要复制那些网址到谷歌打开？或者是如何启动谷歌打开学习用书？

### ISSUE THREAD

**Issue by liu-liang518** [neolee/pilot#209]
![image](https://user-images.githubusercontent.com/57051523/67775825-6f41c680-fa9a-11e9-90fb-775ad421eb99.png)

**Comment by neolee** [comment]
是的，Jupyter Lab 不知道旧的 IE，用 Windows 10 自带的 Edge 或者 Chrome 或者其他较新的浏览器都可以。

可以把 http://localhost: 那一行完整 copy 到浏览器地址栏打开就行。

要想省事，把系统缺省浏览器换成更新的浏览器。
