### ISSUE TITLE
请问电脑之前装有Python3.7.4需要卸载吗？

### ISSUE THREAD

**Issue by Jared-Gong** [neolee/pilot#21]
![1571813877(1)](https://user-images.githubusercontent.com/56901849/67366200-9c2b4080-f5a5-11e9-99b4-63a6ea72a339.png)
scoop会默认之前安装的python
![1571814048(1)](https://user-images.githubusercontent.com/56901849/67366434-15c32e80-f5a6-11e9-99e4-c8ad98efaae0.png)
不懂安装Jupyter Lab是直接这样运行安装吗？

**Comment by neolee** [comment]
先不用删除，如果 Jupyter Lab 装成功，就可以继续了。

否则建议清干净重来。

**Comment by neolee** [comment]
不过我看你的截图，scoop 说之前安装 python37 失败，最好你重装一下：

scoop uninstall python37
scoop install python37

再：

pip install jupyterlab

**Comment by Jared-Gong** [comment]
好的  我试试

**Comment by Jared-Gong** [comment]
> 不过我看你的截图，scoop 说之前安装 python37 失败，最好你重装一下：
> 
> scoop uninstall python37
> scoop install python37
> 
> 再：
> 
> pip install jupyterlab
老师  我下午重新试了下 下载到70%又提醒下载失败了，早上也是下载到75%就跳出了这种图，请问是网络问题吗？
![1571822356962_E5BA9135-1849-47ad-89BE-D92A09EABDB7](https://user-images.githubusercontent.com/56901849/67378241-8d4e8900-f5b9-11e9-98c4-7dd7139dc07d.png)

**Comment by neolee** [comment]
是的，网络不太好，多试几次吧。
