### ISSUE TITLE
Scoop 安装成功了吗？

### ISSUE THREAD

**Issue by beihaichenxiong** [neolee/pilot#210]
PS C:\Users\lenovo> cd
PS C:\Users\lenovo> del .\scoop -Force

确认
C:\Users\lenovo\scoop 处的项具有子项，并且未指定 Recurse 参数。如果继续，所有子项均将随该项删除。是否确实要继续?
[Y] 是(Y)  [A] 全是(A)  [N] 否(N)  [L] 全否(L)  [S] 暂停(S)  [?] 帮助 (默认值为“Y”): y
PS C:\Users\lenovo> y
y : 无法将“y”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ y
+ ~
    + CategoryInfo          : ObjectNotFound: (y:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\lenovo> Set-ExecutionPolicy RemoteSigned -scope CurrentUser
PS C:\Users\lenovo> iwr -useb get.scoop.sh | iex
Initializing...
Downloading scoop...
Extracting...
Creating shim...
Downloading main bucket...
Extracting...
Adding ~\scoop\shims to your path.
'lastupdate' has been set to '2019-10-29T22:19:36.5566735+08:00'
Scoop was installed successfully!
Type 'scoop help' for instructions.
PS C:\Users\lenovo> scoop list
There aren't any apps installed.
PS C:\Users\lenovo> scoop install git
Installing '7zip' (19.00) [64bit]
7z1900-x64.msi (1.7 MB) [============================================================================================================================] 100%
Checking hash of 7z1900-x64.msi ... ok.
Extracting 7z1900-x64.msi ... done.
Linking ~\scoop\apps\7zip\current => ~\scoop\apps\7zip\19.00
Creating shim for '7z'.
Creating shortcut for 7-Zip (7zFM.exe)
'7zip' (19.00) was installed successfully!
Installing 'git' (2.23.0.windows.1) [64bit]
PortableGit-2.23.0-64-bit.7z.exe (41.5 MB) [=======================>                                                                                 ]  23%
从传输流收到意外的 EOF 或 0 个字节。
URL https://github.com/git-for-windows/git/releases/download/v2.23.0.windows.1/PortableGit-2.23.0-64-bit.7z.exe#/dl.7z is not valid
PS C:\Users\lenovo>

**Comment by neolee** [comment]
Scoop 本身装好了，但是再装必需的 git 时失败了。需要重新安装 git：

```powershell
scoop uninstal git
scoop install git
```

有其他 issue 提供了别的解决方案，你可以搜索下。
