### ISSUE TITLE
Visual Studio Code 编辑 Python 程序提示 Linter Pylint not installed 以及 No Python Interpreter

### ISSUE THREAD

**Issue by Merezhu** [neolee/pilot#211]
输入指令后，VS Code右下角提示如下：

![image](https://user-images.githubusercontent.com/36255603/67778235-ddd45380-fa9d-11e9-8d6f-d64ce7c084ed.png)

但在ConEmu里面运行又顺利（与指南一致），请问需要安装 Linter Pylint 和 Interpreter 吗?

![image](https://user-images.githubusercontent.com/36255603/67778361-06f4e400-fa9e-11e9-8316-a8f8deddf416.png)

**Comment by neolee** [comment]
那两个提示只是 Visual Studio Code 提示你安装和设置它自己的环境，以便你写程序更爽，可以选择，以及按提示去配置，目前不理它也不要紧。
