### ISSUE TITLE
brew doctor 的 warning 提示 是否需要全部解决

### ISSUE THREAD

**Issue by Gaomingzhao** [neolee/pilot#212]
<img width="602" alt="WechatIMG4927" src="https://user-images.githubusercontent.com/24623343/67780854-a2d41f00-faa1-11e9-81ca-45e9b0c6d8ea.png">
不知道这些问题如何处理，是否可以略过？

**Comment by neolee** [comment]
这个要看具体问题，你这里这几个，第一个和最后一个都比较不好，需要解决，中间一个不好说。

第一个是你安装 Anaconda 来的，很可能和你用 Homebrew 安装的 Python 冲突，最好按照 Anaconda 的而官方指南先完整的删掉。

第三个是说你 Homebrew 安装的 Python 没有 link 好（link 这个操作比较复杂几句话说不清），建议你运行 `brew link python`，你最好在彻底删掉 Anaconda 之后在执行这个命令。

第二个是说 /usr/local/lib 下面有几个 Homebrew 不认识的运行库，估计你也不知道什么时候装的以及干啥用吧？保险起见，我建议你的找个目录把它们 mv 过去，看看是不是影响你机器运行，不影响就搁在那儿：

```shell
mkdir ~/Backup
mv /usr/local/lib/libnnz11.dylib /usr/local/lib/libociei.dylib /usr/local/lib/libocijdbc11.dylib ~/Backup/
```
