### ISSUE TITLE
用 Scoop 安装 git 总是卡在下载界面不动然后提示连接超时

### ISSUE THREAD

**Issue by Oliver747** [neolee/pilot#213]
![image](https://user-images.githubusercontent.com/37108566/67781851-eed39380-faa2-11e9-9192-89fc6a3ba7fe.png)

**Comment by zcwlive** [comment]
解决了吗，兄弟。我也遇到了一样的问题

**Comment by Oliver747** [comment]
> 解决了吗，兄弟。我也遇到了一样的问题

还没有啊，应该是网络的问题

**Comment by Panchunlan** [comment]
我也遇到了这个问题，已经试了N遍了！很慢很慢！有一次两小时下了68%最后又卡死了，问题还是没解决。

**Comment by Oliver747** [comment]
我也试了好久，换了各种网络还是不行啊，下载速度极慢，可能需要挂代理吧，今晚回去试一下

**Comment by Oliver747** [comment]
> 我也遇到了这个问题，已经试了N遍了！很慢很慢！有一次两小时下了68%最后又卡死了，问题还是没解决。

需要挂v.p.n
