### ISSUE TITLE
运行 code 命令为什么有错误

### ISSUE THREAD

**Issue by beihaichenxiong** [neolee/pilot#216]
PS C:\Users\lenovo\Code> mkdir Code

    目录: C:\Users\lenovo\Code

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       2019/10/29     23:38                Code

PS C:\Users\lenovo\Code> cd Code
PS C:\Users\lenovo\Code\Code> code .
code : 无法将“code”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ code .
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (code:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\lenovo\Code\Code> code .
code : 无法将“code”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ code .
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (code:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\lenovo\Code\Code>

**Comment by beihaichenxiong** [comment]
应该是创建成功code了。而且文件code里又创建了一个code，但是为什么命令code .的时候有这些错误跟老师操作结果不一样呢？

**Comment by neolee** [comment]
你安装 Visual Studio Code 了么？

**Comment by beihaichenxiong** [comment]
我安装了visual studio code了。

**Comment by neolee** [comment]
那 code 命令就应该可以工作，退出命令行界面重进试试，不行重启下 Windows。
