### ISSUE TITLE
Scoop 安装出错

### ISSUE THREAD

**Issue by guansheji** [neolee/pilot#217]
![批注 2019-10-29 235136](https://user-images.githubusercontent.com/55250000/67784654-10367e80-faa7-11e9-9e49-6105bb68ce6a.png)

**Comment by neolee** [comment]
之前安装 Scoop 失败了，需要删了重装，在上方链接 Wiki 里找“重新安装 Scoop”。

**Comment by guansheji** [comment]
重装也装不了
