### ISSUE TITLE
git commit 打开编辑器之后出问题

### ISSUE THREAD

**Issue by banshibao** [neolee/pilot#219]
![git commit](https://user-images.githubusercontent.com/24274761/67790118-2c8ae900-fab0-11e9-8a16-ab9e5a9f2013.JPG)
输入：git commit后，打开文本编辑器，还没保存并关闭编辑器窗口就出现如上问题。
貌似在说README.md文件是空的，我又打开README.md的文件,随意输入一点东西保存
，并git add README.md,再次执行git  commit 指令，还是出现上述问题。
![修改](https://user-images.githubusercontent.com/24274761/67790771-437e0b00-fab1-11e9-8e9e-3249b0032071.JPG)
没有看到执行结果：
[master (root-commit) 7451a00] Init commit
 1 file changed, 3 insertions(+)
 create mode 100644 README.md

**Comment by neolee** [comment]
看上去你 git config 时有问题，配置 core.editor 应该是 "code -w"，小写的 w，你好像用了大写。

所以没有输入提交信息 commit 就继续了，然后因为没有提交信息而中止。

把 config 改正之后再试试。

**Comment by jinglong-py** [comment]
![捕获](https://user-images.githubusercontent.com/55208211/67846625-7d482380-fb3c-11e9-8eed-efae9637a7aa.PNG)
试过了，还是这种情况

**Comment by jinglong-py** [comment]
是版本信息输入有误吗？还是？

**Comment by neolee** [comment]
执行 `git config --list` 给我看看。

**Comment by jinglong-py** [comment]
![捕获](https://user-images.githubusercontent.com/55208211/67847350-addc8d00-fb3d-11e9-84d4-19c5ff796f01.PNG)

**Comment by neolee** [comment]
你这个应该是别的方法安装的 git 吧，这么多 config……

这里 core.editor 配置无误，所以应该是别的问题，执行 `git commit` 之后应该弹出 Visual Studio Code，这时候请你截一个图，包括此时命令行窗口和 Visual Studio Code 两个窗口。

**Comment by jinglong-py** [comment]
对，前面安装过一次
![捕获](https://user-images.githubusercontent.com/55208211/67847934-ac5f9480-fb3e-11e9-849e-8c3460dbe373.PNG)

**Comment by neolee** [comment]
然后你在编辑器最上面一行输入一些说明文字，然后保存并关闭编辑器，会怎样？

**Comment by jinglong-py** [comment]
“在提示光标处输入我们对这个版本的描述信息，保存并关闭编辑器窗口之后 git 才会执行 commit 指令。版本信息非常重要，应该准确、扼要的概括我们所做的修改，这样后续我们管理历史版本时会少很多麻烦。”
这段没有理解清楚。
问题解决了

**Comment by neolee** [comment]
点这个页面上方的 Wiki，支线课程里有 Git 入门的视频，可以参考。
