### ISSUE TITLE
mac book 安装homebrew 出错

### ISSUE THREAD

**Issue by Zoe201306** [neolee/pilot#22]
运行到在终端输入：sudo xcodebuild -license accept后，password后面的密码无法输入，就是输入字母终端没有反应。盲输入之后回车显示tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance。请问怎么解决？

**Comment by neolee** [comment]
跳过这一步，直接安装 Homebrew 试试？

**Comment by Zoe201306** [comment]
1、直接输入install Homebrew,显示如下：
usage: install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 file2
       install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 ... fileN directory
       install -d [-v] [-g group] [-m mode] [-o owner] directory ...
2、再输入：brew update
显示：-bash: brew: command not found
3、再输入：brew install git python
显示：-bash: brew: command not found
请问这是没安装好吧？

**Comment by Zoe201306** [comment]
终端输入：/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
==> This script will install:
/usr/local/bin/brew
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew
/usr/local/Homebrew
==> The following existing directories will be made group writable:
/usr/local/bin
/usr/local/sbin
==> The following existing directories will have their owner set to zoe:
/usr/local/bin
/usr/local/sbin
==> The following existing directories will have their group set to admin:
/usr/local/bin
/usr/local/sbin
==> The following new directories will be created:
/usr/local/etc
/usr/local/include
/usr/local/lib
/usr/local/share
/usr/local/var
/usr/local/opt
/usr/local/share/zsh
/usr/local/share/zsh/site-functions
/usr/local/var/homebrew
/usr/local/var/homebrew/linked
/usr/local/Cellar
/usr/local/Caskroom
/usr/local/Homebrew
/usr/local/Frameworks

Press RETURN to continue or any other key to abort
zoedeMacBook-Air:~ zoe$ RETURN
-bash: RETURN: command not found
zoedeMacBook-Air:~ zoe$ brew install git python
-bash: brew: command not found
如果还是显示not found，是不是还没有安装好Homebrew？谢谢老师解答。

**Comment by neolee** [comment]
前面都没问题，当出现 Press RETURN to continue or any other key to abort 提示时，其实是要你按回车键继续安装，其他任何键都是中止退出安装。

所以你再运行一次 Homebrew 的安装命令，出现这个提示时按回车键继续就好了。

**Comment by Zoe201306** [comment]
太感谢大神老师了，专业的老师就是不一样，优秀！我已经安装好了，谢谢老师！

**Comment by neolee** [comment]
不客气，keep going!
