### ISSUE TITLE
指南中的指导图片无法点击开

### ISSUE THREAD

**Issue by lvdan0129** [neolee/pilot#221]
![微信图片_20191030070429](https://user-images.githubusercontent.com/50976076/67816088-cd46cc00-fae3-11e9-8b54-e70e1a874197.png)

**Comment by ahui9** [comment]
网络问题

**Comment by lvdan0129** [comment]
请问网络问题我又该如何解决？我用的是联通的宽带，我需要换宽带吗？




------------------ 原始邮件 ------------------
发件人: "ahui9"<notifications@github.com>; 
发送时间: 2019年10月30日(星期三) 上午9:51
收件人: "neolee/pilot"<pilot@noreply.github.com>; 
抄送: "ldsimple0129"<962924142@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [neolee/pilot] 指南中的指导图片无法点击开 (#221)




网络问题

**Comment by neolee** [comment]
先试试别的网络会不会好，比如工作单位的，或者外面的 Wifi，甚至手机热点，如果可以，那就是网络问题，你可以找运营商要求支持。

**Comment by kobeyyn** [comment]
我也遇到了这个问题，有解决方案吗？
