### ISSUE TITLE
Scoop 相关排错后又提出错误

### ISSUE THREAD

**Issue by lvdan0129** [neolee/pilot#222]
![微信图片_20191030071510](https://user-images.githubusercontent.com/50976076/67816532-311dc480-fae5-11e9-8f7f-9cf09777e320.png)

**Comment by neolee** [comment]
1. 退出 PowerShell 然后再进；

2. `Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1` 这一句因为权限原因没成功，可以开一个 {{ PowerShell (Admin) }} 试试。

3. Scoop 没有安装成功，需要删了重装，点页面上方 Wiki，按照“重新安装 Scoop”操作。
