### ISSUE TITLE
git 提交 README.md 之后 git status 出现一个新文件

### ISSUE THREAD

**Issue by dongjin936** [neolee/pilot#224]
<img width="480" alt="0000" src="https://user-images.githubusercontent.com/56923938/67824125-77cce800-fb00-11e9-8e6f-5122b6a462aa.png">

**Comment by neolee** [comment]
用 code package.json 打开这个未知文件看看，应该能猜出是哪儿来的。

**Comment by XueAE** [comment]
同样问题。做了如下步骤：
1. add package. jason 
2. git status 发现README和该文件一起处于待提交状态。
3. git commit 出现如下界面
![问题2](https://user-images.githubusercontent.com/57041578/67916979-7ec42b00-fbd2-11e9-9a06-c4598e5be133.png)
4. code package.json 后弹出visual studio弹出如下
![问题1](https://user-images.githubusercontent.com/57041578/67917063-bf23a900-fbd2-11e9-9a92-c7acb7f54704.png)

**Comment by neolee** [comment]
package.json 内容空的，这个文件一般是 JavaScript 的一些工具用的，不知道为啥会出现。

然后 git commit 出的那个错，issue #150 与此类似，但是目前还没搞清是怎么回事。

**Comment by dongjin936** [comment]
我打开知道是在Visual studio code里面，但是我不知道它为何出现？以及应该怎么处理它。

> 用 code package.json 打开这个未知文件看看，应该能猜出是哪儿来的。

我打开知道是在Visual studio code里面，但是我不知道它为何出现？以及应该怎么处理它。

**Comment by XueAE** [comment]
是的，我也有删过，但是删掉后，检查 git status, 还是存在

**Comment by dongjin936** [comment]
我也是先把这个新文件添加了

**Comment by neolee** [comment]
在命令行下执行 `git rm package.json` 可以删除这个文件，既从文件系统删除，也从 git 版本里删除。

**Comment by XueAE** [comment]
> 在命令行下执行 `git rm package.json` 可以删除这个文件，既从文件系统删除，也从 git 版本里删除。

删除操作后，执行 git status 还是可见该文档处于待提交状态。
![批注 2019-11-01 141905](https://user-images.githubusercontent.com/57041578/68006425-7e4f9100-fcb3-11e9-9f91-95df2e7f8801.png)

**Comment by XueAE** [comment]
是否可以卸载git和visual studio，然后重装。但一直有个担心就是，怕操作不当，未能卸载干净。

**Comment by neolee** [comment]
@XueAE 执行 `git rm --cached package.json` 然后 `git rm package.json`。

**Comment by XueAE** [comment]
> @XueAE 执行 `git rm --cached package.json` 然后 `git rm package.json`。

已执行，仍无效，既然是零字节文件，不管它，会影响系统正常运行吗？
![image](https://user-images.githubusercontent.com/57041578/68087063-22d8fb00-fe8d-11e9-82c7-cf184e770da7.png)

**Comment by neolee** [comment]
那个文件还是要删掉啊，`rm package.json`。

另外，上面的出错信息里可以看出，你配置 git 编辑器也写错了，不是 `core -w`，是 `code -w`：

```powershell
git config --global core.editor "code -w"
```
