### ISSUE TITLE
课程练习 input2 input3

### ISSUE THREAD

**Issue by peakerzhu** [neolee/pilot#226]
(base) peakzhueMacBook:Code peakzhu$ python good.py
How are you today?
good
Traceback (most recent call last):
  File "good.py", line 2, in <module>
    feeling = input()
  File "<string>", line 1, in <module>
NameError: name 'good' is not defined
(base) peakzhueMacBook:Code peakzhu$ python good.py
How are you today?
sad
Traceback (most recent call last):
  File "good.py", line 2, in <module>
    feeling = input()
  File "<string>", line 1, in <module>
NameError: name 'sad' is not defined

**Comment by neolee** [comment]
这肯定你的程序里有问题呀，光看执行结果没法判断。

这个是很后面的课程了，先不急。

**Comment by peakerzhu** [comment]
谢谢老师回复，我已经解决了，所有程序我都已经练习完了，但是最后的那个实操，真的很难理解。










在 2019-10-30 12:18:43，"Neo Lee" <notifications@github.com> 写道：


这肯定你的程序里有问题呀，光看执行结果没法判断。

这个是很后面的课程了，先不急。

**Comment by neolee** [comment]
噢，那也好，这样才有听课的动力啊（雾

**Comment by peakerzhu** [comment]
是的，期待老师的课程，等待老师帮我建立新思维！🙏

> 在 2019年10月30日，下午1:18，Neo Lee <notifications@github.com> 写道：
> 
> 这肯定你的程序里有问题呀，光看执行结果没
