### ISSUE TITLE
安装python37出现Couldn't find manifest for 'python37'.

### ISSUE THREAD

**Issue by michaelmakun** [neolee/pilot#23]
![6](https://user-images.githubusercontent.com/19246142/67370737-d00a6400-f5ad-11e9-8ab5-0344b2d79d3a.jpg)

具体如图，搜了搜，没找到相应的解决办法

**Comment by michaelmakun** [comment]
电脑系统是 win8.1

**Comment by neolee** [comment]
按照配置指南所述，正确操作是：

```shell
scoop bucket add versions
scoop update
scoop install python37
```

**Comment by michaelmakun** [comment]
好了，谢谢老师~

**Comment by ds-dog** [comment]
哈哈哈我昨晚也是这个问题，老师回答过我，然后python可以了，但是busybox不行了
![图片](https://user-images.githubusercontent.com/49094749/67373261-e74b5080-f5b1-11e9-99d0-230f413c4aad.png)

**Comment by neolee** [comment]
@ds-dog 你试试 scoop update 然后再 scoop search busybox。

**Comment by ds-dog** [comment]
> 
> 
> @ds-dog 你试试 scoop update 然后再 scoop search busybox。

no matches found

**Comment by ds-dog** [comment]
> 
> 
> @ds-dog 你试试 scoop update 然后再 scoop search busybox。

![图片](https://user-images.githubusercontent.com/49094749/67394428-bdf0eb80-f5d6-11e9-9531-ae254c169de7.png)

**Comment by neolee** [comment]
@ds-dog 你这个很诡异，需要的话另开 issue 吧，不在这里继续了
