### ISSUE TITLE
安装软件包管理工具 Scoop时出错

### ISSUE THREAD

**Issue by lvdan0129** [neolee/pilot#230]
![QQ图片20191030144037](https://user-images.githubusercontent.com/50976076/67834865-824ca900-fb23-11e9-9f58-05eb10cdd295.jpg)
![QQ图片20191030144044](https://user-images.githubusercontent.com/50976076/67834877-8678c680-fb23-11e9-9741-c5c260a86897.png)

**Comment by neolee** [comment]
不要重复发一样的 issue，如果需要补充信息，可以编辑或者回复之前的 issue。另外那个我已经恢复了。

Duplicate of #229
