### ISSUE TITLE
执行“Set-ItemProperty......"出现错误

### ISSUE THREAD

**Issue by suifeng20192** [neolee/pilot#232]
执行”Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1“后出现：

不允许所请求的注册表访问权。 所在位置 行:1 字符: 1 + Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem
'  ... + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~     + CategoryInfo          : PermissionDenied: (HKEY_LOCAL_MACH...trol\FileSystem:String) [Set-ItemProperty], SecurityException     + FullyQualifiedErrorId : System.Security.SecurityException,Microsoft.PowerShell.Commands.SetItemPropertyCommand

**Comment by neolee** [comment]
有很多类似的问题了，可以搜索下 “Set-ItemProperty”，比如这个 #222
