### ISSUE TITLE
为什么我的python版本是3.7.1呢？

### ISSUE THREAD

**Issue by bianka727** [neolee/pilot#234]
![屏幕快照 2019-10-30 下午5 47 48](https://user-images.githubusercontent.com/48577672/67847223-6eae3c00-fb3d-11e9-8f40-18b0e0b1881a.png)

**Comment by MonsterWong** [comment]
试试用 update 指令来升级一下呢？

**Comment by bianka727** [comment]
完整的命令 就是 update吗？

**Comment by neolee** [comment]
brew update

然后

brew upgrade python
