### ISSUE TITLE
在字符与字符串章节执行代码出现的结果与教科书上的结果不同

### ISSUE THREAD

**Issue by hailinsu** [neolee/pilot#236]
出现的差距如下
![YJO(NJ4(E()6UXA(B`EAFQF](https://user-images.githubusercontent.com/48571418/67857353-8b546f00-fb51-11e9-8615-f7cdd055514a.png)
![VH8`S$NKLX9L AV)KFK%MM4](https://user-images.githubusercontent.com/48571418/67857347-85f72480-fb51-11e9-896c-b86608e22e46.png)

**Comment by hailinsu** [comment]
![YJO(NJ4(E()6UXA(B`EAFQF](https://user-images.githubusercontent.com/48571418/67857479-e0908080-fb51-11e9-9fa9-247db5c043a0.png)

**Comment by neolee** [comment]
`import string`

这个 cell 你没有运行呀。
