### ISSUE TITLE
git命令

### ISSUE THREAD

**Issue by jinglong-py** [neolee/pilot#237]
![捕获](https://user-images.githubusercontent.com/55208211/67857439-c22a8500-fb51-11e9-9e05-44564923a37a.PNG)
![捕获](https://user-images.githubusercontent.com/55208211/67857502-ee460600-fb51-11e9-9d0e-e6491da93651.PNG)
这两个命令原理一样吗？我的电脑里没有 git checkout 命令
PS C:\Users\fly59\Code\learn-git> git --help
usage: git [--version] [--help] [-C <path>] [-c <name>=<value>]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]

These are common Git commands used in various situations:

start a working area (see also: git help tutorial)
   clone     Clone a repository into a new directory
   init      Create an empty Git repository or reinitialize an existing one

work on the current change (see also: git help everyday)
   add       Add file contents to the index
   mv        Move or rename a file, a directory, or a symlink
   restore   Restore working tree files
   rm        Remove files from the working tree and from the index

examine the history and state (see also: git help revisions)
   bisect    Use binary search to find the commit that introduced a bug
   diff      Show changes between commits, commit and working tree, etc
   grep      Print lines matching a pattern
   log       Show commit logs
   show      Show various types of objects
   status    Show the working tree status

grow, mark and tweak your common history
   branch    List, create, or delete branches
   commit    Record changes to the repository
   merge     Join two or more development histories together
   rebase    Reapply commits on top of another base tip
   reset     Reset current HEAD to the specified state
   switch    Switch branches
   tag       Create, list, delete or verify a tag object signed with GPG

collaborate (see also: git help workflows)
   fetch     Download objects and refs from another repository
   pull      Fetch from and integrate with another repository or a local branch
   push      Update remote refs along with associated objects

'git help -a' and 'git help -g' list available subcommands and some
concept guides. See 'git help <command>' or 'git help <concept>'
to read about a specific subcommand or concept.
See 'git help git' for an overview of the system.
PS C:\Users\fly59\Code\learn-git>

**Comment by neolee** [comment]
这个问题是因为在课程已经上线之后 git 新版改了命令，增加了 restore 这个指令，两个版本的命令都可用。

我想想怎么改下教材。

**Comment by jinglong-py** [comment]
![捕获](https://user-images.githubusercontent.com/55208211/67858903-49c5c300-fb55-11e9-80fa-5ee95ae90714.PNG)
![捕获](https://user-images.githubusercontent.com/55208211/67858976-74178080-fb55-11e9-83b5-e1cbfcba7e06.PNG)
哦哦！还有这个都用restore命令代替了
