### ISSUE TITLE
在 Jupyter Lab 中抄写教材里面的代码内容不出现输出结果

### ISSUE THREAD

**Issue by tsao86** [neolee/pilot#238]
<img width="462" alt="屏幕快照 2019-10-30 下午8 19 18" src="https://user-images.githubusercontent.com/49138260/67857841-be4b3280-fb52-11e9-81c2-90f5edfc5392.png">
<img width="432" alt="屏幕快照 2019-10-30 下午8 19 25" src="https://user-images.githubusercontent.com/49138260/67857863-cacf8b00-fb52-11e9-9635-cc845d8516f5.png">
第一个屏幕截图是教材的内容，输出的结果会有值的类型 ，第二个屏幕截图是用Jupyter 抄写的，没有输出结果。这种抄写不会输出值的类型吗？

**Comment by neolee** [comment]
你写完代码在那个格子里按 Control+回车 了吗？

**Comment by tsao86** [comment]
谢谢，问题已解决。程序小白，零基础。
