### ISSUE TITLE
这是否安装好 Jupyter Lab

### ISSUE THREAD

**Issue by chepeiling** [neolee/pilot#239]
![RLY~$L45180 I79MQI6M_PR](https://user-images.githubusercontent.com/56923109/67859166-dbcdcb80-fb55-11e9-8201-1d123bb569e1.png)

**Comment by neolee** [comment]
显然没有啊，那么一大堆红字错误呢。下载中的网络问题。

**Comment by chepeiling** [comment]
![PUFQ0F45Z0T}Q43(CSVF%{C](https://user-images.githubusercontent.com/56923109/67861990-4255e800-fb5c-11e9-90ca-c964c3956d5d.png)
老师我运行安装Jupyter lab 的两个指令成功后，在克隆好的目录里运行 jupyter lab ，就如此，该怎么解决

**Comment by neolee** [comment]
需要安装 nodejs，运行 `scoop install nodejs`，然后再试。

**Comment by neolee** [comment]
你这个 Jupyter Lab 已经跑起来了，正常情况应该会打开浏览器并打开 Jupyter Lab 页面，如果你的浏览器没打开，可以把截图里 http://localhost:... 开头的那一整行拷贝下来，贴到你的浏览器地址栏打开，注意不能用老的 IE 浏览器，新的 Edge、Chrome、Firefox 等都可以。
