### ISSUE TITLE
Pip成功安装完成，但是运行pip install jupyterlab是出现问题

### ISSUE THREAD

**Issue by ray-zheng** [neolee/pilot#24]
在按照命令进行环境设置时候，出现几十行代码，有一半白色，一半红色，最后一行的代码是这个
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full comma

**Comment by neolee** [comment]
你是不是装了 Python 3.8？

打开一个 PowerShell 窗口，运行下面几个命令，把结果告诉我（最好截图）：

```shell
$PSVersionTable.PSVersion.Major

scoop checkup
scoop update

which python
python -V
pip -V
pip list
```

**Comment by ray-zheng** [comment]
![image](https://user-images.githubusercontent.com/48572098/67373323-021dc500-f5b2-11e9-977f-8036ff63c64b.png)

**Comment by ray-zheng** [comment]
是的，我安装了3.8

**Comment by neolee** [comment]
Python 3.8 太新了，第三方库不能保证兼容，我们不能用它，你需要卸掉它然后严格按照 [指南](https://github.com/neolee/pilot/blob/master/x1-setup.md) 操作：

```shell
scoop uninstall python
scoop bucket add versions
scoop update
scoop install python37
```

然后再装 Jupyter Lab 应该就没问题了。

**Comment by ray-zheng** [comment]
那我如何卸载掉3.8？然后重新安装3.7？

**Comment by ray-zheng** [comment]
哦哦哦，好的，太感谢了，第一次使用github提问功能，迅速收到回复，非常感谢

**Comment by neolee** [comment]
另外， 最好按照 scoop checkup 的提示，运行下这两个命令：

```shell
Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1
scoop install innounp
```

**Comment by ray-zheng** [comment]
是重新安装完成python37后运行哈？好的，感谢
