### ISSUE TITLE
 notebook 修改完后，git commit是在命令行界面提交吗，ctrl+c关闭 jupyter lab后，提交git commit不对呢

### ISSUE THREAD

**Issue by Lilidandan321** [neolee/pilot#242]
[I 23:00:09.107 LabApp] Kernel shutdown: 5f145574-c04e-42a3-814c-aa51423c69d1
[I 23:00:09.108 LabApp] Kernel shutdown: f0610d37-807c-4757-bfe1-6f407b0e7246
[I 23:00:09.109 LabApp] Kernel shutdown: 96de59dd-8aa4-4993-bb80-0054e26c9ebe
PS C:\Users\jll\code\pilot-student>  git commit

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

**Comment by neolee** [comment]
1. 一次提一个问题，不要贪；
2. 标题和内容基本没啥关系；
3. 下不为例。

对于你提到的几个问题：
1. 你在执行 git commit 之前没有做 git 配置，如果你认真看我们的 Git 教程和视频，就不会这样；
2. 你在 Jupyter Lab 里修改并保存 notebook 之后，可以 git commit 将其提交为一个版本；
3. 是的，git 的所有命令都在命令行里执行；
3. 你当然可以 Control+C 停掉 Jupyter Lab 然后执行 git 命令，但这样你就没法用 Jupyter Lab 了，所以更好的办法是：另开一个命令行 tab（ConEmu 就是干这个的），然后进入你的工作目录，然后执行 git 命令，这样 `jupyter lab` 在原先的 tab 里继续运行，两不误。

**Comment by Lilidandan321** [comment]
好的，谢谢老师。
 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Neo Lee"<notifications@github.com&gt;; 
发送时间: 2019年10月31日(星期四) 中午12:47
收件人: "neolee/pilot"<pilot@noreply.github.com&gt;; 
抄送: "莫言心悸幽蓝"<2467764484@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [neolee/pilot]  notebook 修改完后，git commit是在命令行界面提交吗，ctrl+c关闭 jupyter lab后，提交git commit不对呢 (#242)



 
一次提一个问题，不要贪；
 
标题和内容基本没啥关系；
 
下不为例。
  
对于你提到的几个问题：
  
你在执行 git commit 之前没有做 git 配置，如果你认真看我们的 Git 教程和视频，就不会这样；
 
你在 Jupyter Lab 里修改并保存 notebook 之后，可以 git commit 将其提交为一个版本；
 
是的，git 的所有命令都在命令行里执行；
 
你当然可以 Control+C 停掉 Jupyter Lab 然后执行 git 命令，但这样你就没法用 Jupyter Lab 了，所以更好的办法是：另开一个命令行 tab（ConEmu 就是干这个的），然后进入你的工作目录，然后执行 git 命令，这样 jupyter lab 在原先的 tab 里继续运行，两不误。
