### ISSUE TITLE
提示scoop已经安装，但无法运行scoop update

### ISSUE THREAD

**Issue by trayoung** [neolee/pilot#244]
提示scoop已经安装，但无法运行scoop update
![安装scoop失败](https://user-images.githubusercontent.com/39803462/67879626-3ed05a00-fb78-11e9-8399-07e666d7701d.JPG)

**Comment by trayoung** [comment]
看系统返回的信息可以判定，Scoop被系统误认为已经安装了，但实际的情况是没有正常安装，请问李骏老师，这种问题该尝试那些方法？

**Comment by zhengzhigang1975** [comment]
遇到过类似，我的操作思维是归零，即使用uninstall命令删除原有现在程序，重新下载安装。

**Comment by neolee** [comment]
点击上方的 Wiki，按照“重新安装 Scoop”操作。

**Comment by trayoung** [comment]
已经解决了，通过删除本地用户目录下的scoop文件夹，再尝试安装就成功了，感谢李骏老师和zhengzhigang1975同学的耐心解答。
