### ISSUE TITLE
章节”3-structure-2.ipynb"中，定义了g=0.7,f=3.14，运算 g % f 时结果为什么是 0.7 ？

### ISSUE THREAD

**Issue by denzii818** [neolee/pilot#246]
章节”3-structure-2.ipynb"中，定义了g=0.7，f=3.14，运算 g % f 时结果为什么是 0.7 ？
![image](https://user-images.githubusercontent.com/56942127/67910401-83321900-fbbd-11e9-8fe6-123ef16bc057.png)

**Comment by denzii818** [comment]
想明白了，0.7 % 3.14，不够除，余数还是0.7.
我认为是：0.7 / 3.14 = 0.22293，认为结果是0.22293了！
低级错误，低级错误，低级错误！

**Comment by logdazy** [comment]
你好，为什么我输入代码后运行没有结果返回呢？

**Comment by denzii818** [comment]
> 你好，为什么我输入代码后运行没有结果返回呢？
你点一下上面的小三角进行运行才行。如下图：
![image](https://user-images.githubusercontent.com/56942127/67915582-6d791f80-fbce-11e9-9b2e-08491a718e6e.png)

**Comment by neolee** [comment]
@denzii818 你需要理解 / 和 % 的差异，前者是除法，后者是“整除”，Python 把我们一般理解的整除的概念扩展到了小数领域。

@logdazy 在一个格子输入代码之后按 Control+回车 来执行它。
