### ISSUE TITLE
安装 Windows Management Framework 5.x 问题

### ISSUE THREAD

**Issue by kofzhaobin** [neolee/pilot#247]
安装Windows Management Framework 5.x，点击进入链接后，应该选择哪个呢，我是win7 64位系统，每个我都试了，都是报错 “安装程序遇到错误0x8024037”

**Comment by neolee** [comment]
Windows 7 64-bit 系统应该下载安装 Win7AndW2K8R2-KB3191566-x64.zip 这个文件。

**Comment by neolee** [comment]
多说一句，搞不清的时候切忌乱试，很多时候会有副作用，宁可先问清楚。

你目前需要在 Windows 设置的卸载项目下找找，如果有 Windows Management Framework 先删除或者修复，然后再尝试安装正确的那个文件。

**Comment by kofzhaobin** [comment]
> 多说一句，搞不清的时候切忌乱试，很多时候会有副作用，宁可先问清楚。
> 
> 你目前需要在 Windows 设置的卸载项目下找找，如果有 Windows Management Framework 先删除或者修复，然后再尝试安装正确的那个文件。

我重新装了framework, 但安装这个还是报错，我的powershell版本目前还是2

**Comment by neolee** [comment]
报什么错？

**Comment by kofzhaobin** [comment]
我应该是以前错误的安装了x86的powershell V1.0版，现在还不知道怎么卸载这个版本。

**Comment by kofzhaobin** [comment]
我按照这个链接的方法安装成功了
https://blog.csdn.net/m0_37397536/article/details/79271709#commentsedit

**Comment by neolee** [comment]
Nice，是个奇怪的问题，亏得还有人碰到和解决了。
