### ISSUE TITLE
执行 pip install jupyterlab 报错 ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

### ISSUE THREAD

**Issue by eiyen** [neolee/pilot#25]
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
这是报错的最后一段，整个报错非常长。

Win10 64位
pip也已成功安装：
![image](https://user-images.githubusercontent.com/52303623/67379889-1e266400-f5bc-11e9-902d-741c82017614.png)

推测出现这个问题可能有两个原因：

1.我安装的是Python3.8。
之后想要换成Python37，但是卸载的时候出现了问题：
![image](https://user-images.githubusercontent.com/52303623/67379556-abb58400-f5bb-11e9-916d-3e562043cb99.png)

2.之前的操作误将环境变量里的path清空，这是添加一部分path后的结果：
![image](https://user-images.githubusercontent.com/52303623/67380370-c9cfb400-f5bc-11e9-8edb-7de8f549fa33.png)

**Comment by neolee** [comment]
你的第一个推测是对的，Python 3.8 太新，不能和所有需要的第三方库兼容，所以需要卸载然后按照 [配置指南](https://github.com/neolee/pilot/blob/master/x1-setup.md) 重新安装 python37。

第二个问题是系统路径设置有问题，找不到 Scoop 的程序了，我建议你彻底删除 C:\Users\corror\scoop ，然后再按照指南重新安装一次 Scoop。（之后安装 python37 然后 Jupyter Lab）

**Comment by eiyen** [comment]
谢谢老师，顺利运行了

**Comment by neolee** [comment]
赞，keep going

**Comment by eiyen** [comment]
现在 jupyter lab 也支持 python 3.8 了
![image](https://user-images.githubusercontent.com/52303623/68006370-595b1e00-fcb3-11e9-8bd7-4f00d5b00052.png)

**Comment by neolee** [comment]
@eiyen 风险自担就行。
