### ISSUE TITLE
怎么理解“第一个参数 self 解释器会自动放进去（就是刚刚创建好的实例对象）”

### ISSUE THREAD

**Issue by xiaoerhai** [neolee/pilot#250]
解释器会在内存中创建这个实例对象，然后用参数 'Fido' 调用类的 __init__(self, name) 方法，第一个参数 self 解释器会自动放进去（就是刚刚创建好的实例对象），而 name 参数就是 'Fido'，__init__() 方法运行完毕就会把这个对象的 self.name 实例变量设为 'Fido'
-----------
这里，‘（就是刚刚创建好的实例对象）’中的‘实例对象’不就是‘Fido’吗？

**Comment by neolee** [comment]
Duplicate of #248
