### ISSUE TITLE
可以直接进入pilot-student，不用打cd code 再cd pilot-student再 jupyter lab然后学习吗？

### ISSUE THREAD

**Issue by beihaichenxiong** [neolee/pilot#251]
PS C:\Users\lenovo> jupyter lab
[I 10:47:33.902 LabApp] JupyterLab extension loaded from c:\users\lenovo\scoop\apps\python37\current\lib\site-packages\jupyterlab
[I 10:47:33.902 LabApp] JupyterLab application directory is c:\users\lenovo\scoop\apps\python37\current\share\jupyter\lab
[I 10:47:34.390 LabApp] Serving notebooks from local directory: C:\Users\lenovo
[I 10:47:34.390 LabApp] The Jupyter Notebook is running at:
[I 10:47:34.390 LabApp] http://localhost:8888/?token=7d78d8d79254402f1784350931d9519ccb61f79e36459702
[I 10:47:34.390 LabApp]  or http://127.0.0.1:8888/?token=7d78d8d79254402f1784350931d9519ccb61f79e36459702
[I 10:47:34.390 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 10:47:34.600 LabApp]

    To access the notebook, open this file in a browser:
        file:///C:/Users/lenovo/AppData/Roaming/jupyter/runtime/nbserver-1928-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=7d78d8d79254402f1784350931d9519ccb61f79e36459702
     or http://127.0.0.1:8888/?token=7d78d8d79254402f1784350931d9519ccb61f79e36459702
[I 10:47:38.816 LabApp] Build is up to date
[W 10:47:39.057 LabApp] 404 GET /api/contents/3-structure-2.ipynb?content=0&1572490058996 (::1): No such file or directory: 3-structure-2.ipynb
[W 10:47:39.057 LabApp] No such file or directory: 3-structure-2.ipynb
[W 10:47:39.057 LabApp] 404 GET /api/contents/3-structure-2.ipynb?content=0&1572490058996 (::1) 4.99ms referer=http://localhost:8888/lab
[W 10:47:39.062 LabApp] 404 GET /api/contents/1-understanding-programming-languages.ipynb?content=0&1572490058995 (::1): No such file or directory: 1-understanding-programming-languages.ipynb
[W 10:47:39.063 LabApp] No such file or directory: 1-understanding-programming-languages.ipynb
[W 10:47:39.064 LabApp] 404 GET /api/contents/1-understanding-programming-languages.ipynb?content=0&1572490058995 (::1) 8.98ms referer=http://localhost:8888/lab
[W 10:47:39.066 LabApp] 404 GET /api/contents/2-structure-1.ipynb?content=0&1572490059000 (::1): No such file or directory: 2-structure-1.ipynb
[W 10:47:39.067 LabApp] No such file or directory: 2-structure-1.ipynb
[W 10:47:39.069 LabApp] 404 GET /api/contents/2-structure-1.ipynb?content=0&1572490059000 (::1) 12.97ms referer=http://localhost:8888/lab
[I 10:48:38.068 LabApp] Build is up to date
[I 10:49:29.606 LabApp] Interrupted...
[I 10:49:29.616 LabApp] Shutting down 0 kernels
PS C:\Users\lenovo> cd pilot-student
cd : 找不到路径“C:\Users\lenovo\pilot-student”，因为该路径不存在。
所在位置 行:1 字符: 1
+ cd pilot-student
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\lenovo\pilot-student:String) [Set-Location], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.SetLocationCommand

PS C:\Users\lenovo> cd code
PS C:\Users\lenovo\code> cd pilot-student
PS C:\Users\lenovo\code\pilot-student> jupyter lab
[I 10:53:21.632 LabApp] JupyterLab extension loaded from c:\users\lenovo\scoop\apps\python37\current\lib\site-packages\jupyterlab
[I 10:53:21.632 LabApp] JupyterLab application directory is c:\users\lenovo\scoop\apps\python37\current\share\jupyter\lab
[I 10:53:22.105 LabApp] Serving notebooks from local directory: C:\Users\lenovo\code\pilot-student
[I 10:53:22.105 LabApp] The Jupyter Notebook is running at:
[I 10:53:22.105 LabApp] http://localhost:8888/?token=c7c5930edcc6c822bd6bed78ffda4a024941fe01a44db1d6
[I 10:53:22.105 LabApp]  or http://127.0.0.1:8888/?token=c7c5930edcc6c822bd6bed78ffda4a024941fe01a44db1d6
[I 10:53:22.105 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 10:53:22.311 LabApp]

    To access the notebook, open this file in a browser:
        file:///C:/Users/lenovo/AppData/Roaming/jupyter/runtime/nbserver-2280-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=c7c5930edcc6c822bd6bed78ffda4a024941fe01a44db1d6
     or http://127.0.0.1:8888/?token=c7c5930edcc6c822bd6bed78ffda4a024941fe01a44db1d6
[I 10:53:26.372 LabApp] Build is up to date

**Comment by neolee** [comment]
不是很明白你的问题，你需要在你的学习用书所在的目录运行 jupyter lab，命令行里的“当前工作目录”的概念很重要，你可以看看支线课程第一讲。
