### ISSUE TITLE
Jupyter 运行 cell 中的代码，不显示运行结果

### ISSUE THREAD

**Issue by logdazy** [neolee/pilot#252]
![image](https://user-images.githubusercontent.com/48935745/67915829-e6787700-fbce-11e9-9e4b-a8dad3060b9f.png)

**Comment by denzii818** [comment]
去掉#号

**Comment by beihaichenxiong** [comment]
这个是在网页操作还是在命令窗口操作，我跟着打，没有见什么结果反映呀。

**Comment by logdazy** [comment]
> 去掉#号

搞定了 谢谢。还需要小写，也没有空格。一字一句阅读能力真的是需要提高

**Comment by logdazy** [comment]
> 这个是在网页操作还是在命令窗口操作，我跟着打，没有见什么结果反映呀。

这个就是jupyter notbook，命令窗口执行jupyter lab，自动弹出的浏览器。前提是你把李老师让克隆到自己仓库的学习用书克隆过来了。如果没有就返回第一章按步骤操作吧。
