### ISSUE TITLE
安装完 Scoop，再运行“scoop checkup”后，后续不会操作了

### ISSUE THREAD

**Issue by Kokicoco** [neolee/pilot#253]
PS C:\Users\Administrator> scoop checkup
WARN  Windows Defender may slow down or disrupt installs with realtime scanning.
  Consider running:
    sudo Add-MpPreference -ExclusionPath 'C:\Users\Administrator\scoop'
  (Requires 'sudo' command. Run 'scoop install sudo' if you don't have it.)
WARN  Windows Defender may slow down or disrupt installs with realtime scanning.
  Consider running:
    sudo Add-MpPreference -ExclusionPath 'C:\ProgramData\scoop'
  (Requires 'sudo' command. Run 'scoop install sudo' if you don't have it.)
WARN  LongPaths support is not enabled.
You can enable it with running:
    Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1
WARN  Found 3 potential problems.

----------------------------------------------------------------------------------------
以上，请李老师看一下， 我运行了“scoop install sudo”之后重新自检还是这样；
然后“Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1
scoop install innounp dark”这个不知道怎么运行，请李老师帮忙看一下，谢谢！

**Comment by neolee** [comment]
checkup 建议你运行下面几个命令：

```powershell
sudo Add-MpPreference -ExclusionPath 'C:\Users\Administrator\scoop'
sudo Add-MpPreference -ExclusionPath 'C:\ProgramData\scoop'
Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1
scoop install innounp dark
```

依次执行这几行命令就行了（一次一行）。

**Comment by Kokicoco** [comment]
感谢李老师，已解决。
