### ISSUE TITLE
按照原来的方式重新打开自己编辑过的学习用书没有得到原来的结果

### ISSUE THREAD

**Issue by hailinsu** [neolee/pilot#255]
.按照原来发过的 issue #127 的操作过程，并不能够再次进入到学习作业中，而且会出现途中的问题，导致我今天没有学习编程。
![2H52`{914ZB5KN5(ST{5 W1](https://user-images.githubusercontent.com/48571418/67929216-c1e4c500-fbf7-11e9-896c-dc2cc602dbf2.png)
![$ `WQL8E6K)Y3}N968DM~87](https://user-images.githubusercontent.com/48571418/67929302-f6f11780-fbf7-11e9-9e3f-65350a078dc3.png)

**Comment by hailinsu** [comment]
![QJ @`QYJA8)4NZ9RUK6@ OS](https://user-images.githubusercontent.com/48571418/67929394-2ef85a80-fbf8-11e9-810d-101deb13302d.png)
z这个是按照原来的路径进入的结果

**Comment by neolee** [comment]
我发现你在 #127 里的问题还没解决，你对 nbviewer 的理解还是不对的。

我们推荐的学习方式包含两个部分：

1. [主仓库](https://github.com/neolee/pilot) 里是内容完整的教材，可以直接在 GitHub 中打开看；如果 GitHub 抽风打开 ipynb 文件出错，可以用 [nbviewer](https://nbviewer.jupyter.org/) 来查看。也就是说 nbviewer 可以作为 GitHub 的 notebook 查看器来用，nbviewer 可以从你给出的 GitHub 上的地址找到某个教材章节，然后显示给你看。

2. [学习用书](https://github.com/neolee/pilot-student) 里面放的学习用书和教材不一样，去掉了所有代码，空出来格子给你自己填写。你需要 fork 然后 clone 到你的电脑，然后用你电脑上的 `jupyter lab` 命令来打开编辑。这些学习用书已经在你的电脑上，你不可能用 nbviwer 来看这些，因为 nbviewer 访问不了你的电脑呀（要是能够的话那才吓人）。

所以你现在要做的是：在你的学习用书目录下执行 `jupyter lab`，它会自动打开浏览器列出所有学习用书，如果没有自动打开，你可以拷贝 `http://localhost:...` 那一整行地址到浏览器地址栏，访问这个地址即可。

**Comment by hailinsu** [comment]
1.找不到hppt://localhost的地址了，在conenm运行的时候出现问题。问题就是执行图片中的代码，会直接退出
![RVS7@WDI2BAP1KR$YQO6F6Y](https://user-images.githubusercontent.com/48571418/67946518-81e40900-fc1c-11e9-9453-9848ee7283f4.png)

**Comment by neolee** [comment]
执行 `jupyter lab` 有什么错，发来看看？

**Comment by hailinsu** [comment]
没有错误，直接退出解释器，需要重新打开解释器。

**Comment by neolee** [comment]
退出解释器？什么解释器？

**Comment by hailinsu** [comment]
我还是打不开，
![G0{J24T8QC MWARQWN{DR`L](https://user-images.githubusercontent.com/48571418/68072159-52203700-fdbd-11e9-943f-fac8679c24cd.png)
在我的学习目录下输入，jupyter lab,直接退出，找不到hppt://localhost····这个网址

**Comment by neolee** [comment]
首先我建议你：
1. 不要急，一个一个问题解决；
2. 努力更专注和细心一点，把每个字都写对。

你现在的表达，说实话我很难理解发生了什么。下面是我的一些问题和猜测：
1. 你打不开 ConEmu？具体现象是什么？你下载的是哪个安装程序，如何安装的？安装之后双击 ConEmu 发生了什么？
2. 如果你无法打开 ConEmu，你是在哪里输入 `jupyter lab` 的？你尝试执行 `jupyter lab` 之后发生了什么？可以截图给我看看吗？不要只截一两行，把整个窗口全部信息都给我看看。

**Comment by hailinsu** [comment]
1.打得开ConEmu，那个程序安装，不太懂，上周末就是按照教程安装的。这个软件可以运行。
![SAZ4 8F@2%OFNHQ2L735}S5](https://user-images.githubusercontent.com/48571418/68080544-c0eea600-fe38-11e9-8788-d3ec430c7849.png)
2.我在我的学习目录下输入的，
![VL${J6{Z3KWKZ ZP 5BE}DQ](https://user-images.githubusercontent.com/48571418/68080550-00b58d80-fe39-11e9-9213-5389a623719c.png)
因为我试过好几次了，在这张图片下一步之前先截图，然后再输入jupyter lab，然后那个软件直接退出了。再打开这个软件就是新的页面，也可以输入东西，但是无法执行jupyter lab，我就没办法使用学习用书。

**Comment by neolee** [comment]
从症状上看比较像你的安全软件直接干掉了试图执行 jupyter lab 的会话，否则一般不会出现这种现象。

尝试关掉你的安全/防病毒软件试试。

**Comment by hailinsu** [comment]
问题已经解决了，因为我已经把防病毒软件卸载了。

**Comment by neolee** [comment]
Nice! Keep going!
