### ISSUE TITLE
git 命令行的提示是中文，如何切换为英文

### ISSUE THREAD

**Issue by sunshangyi** [neolee/pilot#256]
![image](https://user-images.githubusercontent.com/26279532/67931884-c613e100-fbfd-11e9-8288-089fa1ba42b3.png)

**Comment by neolee** [comment]
跟着你的操作系统语言走的。你可以执行：

```shell
export LANG=en_US.UTF-8
```

然后再试试。

**Comment by sunshangyi** [comment]
> 跟着你的操作系统语言走的。你可以执行：
> 
> ```shell
> export LANG=en_US.UTF-8
> ```
> 
> 然后再试试。

可以了，thx
但，每次进入Terminal都要输入该命令吗？
能否设置一下，一劳永逸？

**Comment by neolee** [comment]
那就需要把上述命令放到命令行的配置文件里，你目前用的是 zsh，这个配置文件可能是 `~/.zshrc`。

**Comment by sunshangyi** [comment]
> 那就需要把上述命令放到命令行的配置文件里，你目前用的是 zsh，这个配置文件可能是 `~/.zshrc`。

done!
谢谢老师
