### ISSUE TITLE
克隆分叉 repo 成功后找不到 Code\pilot-student 路径

### ISSUE THREAD

**Issue by Weijing14** [neolee/pilot#257]
PS C:\Users\炜婧\Code> cd pilot-student
cd : 找不到路径“C:\Users\炜婧\Code\pilot-student”，因为该路径不存在。
所在位置 行:1 字符: 1
+ cd pilot-student
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\炜婧\Code\pilot-student
:    String) [Set-Location], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.SetLo
   cationCommand

**Comment by neolee** [comment]
你有做 git clone 吗？clone 到哪里了？

**Comment by Weijing14** [comment]
git clone做了，也显示成功了，然后我重新做，这样显示：

PS C:\Users\炜婧\Code> git clone https://github.com/Weijing14/pilot.git
fatal: destination path 'pilot' already exists and is not an empty directory.

我去电脑C盘\Users\炜婧\Code 下面找，在名为“pilot"文件夹下，有这些资料
![image](https://user-images.githubusercontent.com/57029069/67933943-cdd58480-fc01-11e9-846a-6e237c979d26.png)

也就是我把文件克隆在了文件夹名为”pilot“，而非”pilot-student"这个文件夹下是吗？

**Comment by Weijing14** [comment]
> 你有做 git clone 吗？clone 到哪里了？

git clone做了，也显示成功了，然后我重新做，这样显示：

PS C:\Users\炜婧\Code> git clone https://github.com/Weijing14/pilot.git
fatal: destination path 'pilot' already exists and is not an empty directory.

我去电脑C盘\Users\炜婧\Code 下面找，在名为“pilot"文件夹下，有这些资料
image

也就是我把文件克隆在了文件夹名为”pilot“，而非”pilot-student"这个文件夹下是吗？

**Comment by Weijing14** [comment]
> 你有做 git clone 吗？clone 到哪里了？

git clone做了，也显示成功了，然后我重新做，这样显示：

PS C:\Users\炜婧\Code> git clone https://github.com/Weijing14/pilot.git
fatal: destination path 'pilot' already exists and is not an empty directory.

我去电脑C盘\Users\炜婧\Code 下面找，在名为“pilot"文件夹下，有这些资料
![image](https://user-images.githubusercontent.com/57029069/67934823-923bba00-fc03-11e9-89bb-e3d740c9ca36.png)
也就是我把文件克隆在了文件夹名为”pilot“，而非”pilot-student"这个文件夹下是吗？

**Comment by neolee** [comment]
是啊，因为你 clone 的不是学习用书而是主仓库的教材啊。你应该 fork & clone 的是：

https://github.com/neolee/pilot-student
