### ISSUE TITLE
安装 scoop 后出现 scoop is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by hbfphqt** [neolee/pilot#258]
我之前环境配置好了，但是安装不了jupyter lab，打算重新配置环境后，出现问题
![无标题](https://user-images.githubusercontent.com/37977479/67933107-24da5a00-fc00-11e9-9579-ed2d9c19425c.png)

**Comment by neolee** [comment]
Scoop 没装好，奇怪，这样的话你前面怎么装的 Python？

现在你需要重装 Scoop，点页面上方的 Wiki，按照“重新安装 Scoop”操作。

**Comment by hbfphqt** [comment]
我电脑之前安装过。
新问题
![image](https://user-images.githubusercontent.com/37977479/67934707-61f41b80-fc03-11e9-9f7f-e2adf2607922.png)

**Comment by hbfphqt** [comment]
Scoop is already installed. Run 'scoop update' to get the latest version
第一次安装scoop时很顺利，一直到安装jupyter lab
![image](https://user-images.githubusercontent.com/37977479/67935127-30c81b00-fc04-11e9-8e03-5a10f5be48b7.png)

**Comment by hbfphqt** [comment]
![image](https://user-images.githubusercontent.com/37977479/67935786-8f41c900-fc05-11e9-9aaa-ecf4f67393bb.png)

**Comment by neolee** [comment]
因为不太清楚你之前做过的操作，看上去环境有点乱，可以确定的一点是配置 Scoop 的路径应该是失败了，所以找不到安装的 Scoop 命令。试试重启下 Windows，然后按照 Wiki 里的“重新安装 Scoop”操作。
