### ISSUE TITLE
运行 brew doctor 时出现很多 warning

### ISSUE THREAD

**Issue by Yoursman** [neolee/pilot#260]
![Screen Shot 2019-10-31 at 7 29 26 PM](https://user-images.githubusercontent.com/48610146/67943364-d4b9c280-fc14-11e9-87cf-081262a871f5.png)

这种情况用不用管呢？我之前安装过 git、Xcode和 Jupyter

**Comment by neolee** [comment]
截图里的几个不影响，是你以前装的别的软件的。

**Comment by Yoursman** [comment]
> 截图里的几个不影响，是你以前装的别的软件的。
