### ISSUE TITLE
安装插件TOC还需要安装nodejs。

### ISSUE THREAD

**Issue by jarodlong** [neolee/pilot#262]
老师的视频安装TOC插件，需要安装nodejs
https://nodejs.org/en/
我选择的是12.13版本的。
然后再安装toc.
jupyter labextension install @jupyterlab/toc

**Comment by neolee** [comment]
没问题的。

**Comment by keepgrowing27** [comment]
安装 Jupyter Lab 插件 TOC , 我这里除了提示要安装 nodejs 外，还提示需要安装 5+ 和npm:

**Comment by keepgrowing27** [comment]
安装 Jupyter Lab 插件 TOC , 我这里除了提示要安装 nodejs 外，还提示需要安装 5+ 和npm :
ValueError: Please install nodejs 5+ and npm before continuing installation. nodejs may be installed using conda or directly from the nodejs website.

**Comment by keepgrowing27** [comment]
安装 Jupyter Lab 插件 TOC , 我这里除了提示要安装 nodejs 外，还提示需要安装 5+ 和 npm :
ValueError: Please install nodejs 5+ and npm before continuing installation. nodejs may be installed using conda or directly from the nodejs website.
5+ 和 npm 的安装也是使用 scoop install 这个命令就可以么？

**Comment by neolee** [comment]
不是，那句话的意思是，要安装 nodejs 5 以上版本和 npm，npm 是 nodejs 的一部分。所以装 nodejs 就行了。我已经更新了 “准备学习用书” 的相关段落。

**Comment by zhangfei002** [comment]
安装了nodejs了，却无法安装toc？
  7zip 19.00
  busybox 3329-gcf0fa4d13
  git 2.26.0.windows.1
  nodejs 13.12.0
  python37 3.7.4 [C:\Users\张飞\scoop\workspace\python37.json]

PS C:\Users\张飞> jupyter labextension install @jupyterlab/toc
An error occured.
IndexError: list index out of range
See the log file for details:  C:\Users\张飞\AppData\Local\Temp\jupyterlab-debug
-hkshmvi_.log
PS C:\Users\张飞>
