### ISSUE TITLE
我之前下载了 Xcode，又卸载了，一定要先下载安装 Xcode 才能进行下一步吗？

### ISSUE THREAD

**Issue by Yoursman** [neolee/pilot#263]
![Screen Shot 2019-10-31 at 8 58 52 PM](https://user-images.githubusercontent.com/48610146/67948727-4ac42680-fc21-11e9-9790-d234cfadb7bf.png)

**Comment by neolee** [comment]
说说你对 guide 中这段话的理解，你觉得答案应该是什么呢？

**Comment by Yoursman** [comment]
我理解的是不用，然后我尝试了一下进行下一步，到目前为止，一切正常。不用先下载xcode。

发自我的iPhone

**Comment by neolee** [comment]
Well done.

所以其实这对你来说本来就不是问题，相信自己的理解和判断，探索、尝试和验证是编程必备的过程和能力。

**Comment by Yoursman** [comment]
嗯嗯，努力探索。

发自我的iPhone
