### ISSUE TITLE
我的pip是不是已经装好了

### ISSUE THREAD

**Issue by guansheji** [neolee/pilot#264]
![112](https://user-images.githubusercontent.com/55250000/67950950-9547a200-fc25-11e9-8c5a-723399c0a937.png)

**Comment by neolee** [comment]
当然没有啊，红字说了找不到你要安装的包，因为你拼错了。

**Comment by guansheji** [comment]
![222](https://user-images.githubusercontent.com/55250000/67953128-8236d100-fc29-11e9-8511-fe9fbd6e8c04.png)
老师这是装好了吗？

**Comment by neolee** [comment]
看截图没结束吧？好像还在安装？
