### ISSUE TITLE
运行 jupyter lab 命令时报错

### ISSUE THREAD

**Issue by qiaoshuai18** [neolee/pilot#265]
ValueError: Please install nodejs 5+ and npm before continuing installation. nodejs may be installed using conda or directly from the nodejs website.

**Comment by qiaoshuai18** [comment]
![image](https://user-images.githubusercontent.com/57203396/67953054-56b3e680-fc29-11e9-84d8-56b2747d3bec.png)

**Comment by neolee** [comment]
需要安装 nodejs，先执行 `scoop install nodejs`，然后再试 `jupyter lab`。

**Comment by qiaoshuai18** [comment]
![image](https://user-images.githubusercontent.com/57203396/67959329-85cf5580-fc33-11e9-9cea-41aeb55d3ffb.png)

**Comment by qiaoshuai18** [comment]
![image](https://user-images.githubusercontent.com/57203396/67962169-b1543f00-fc37-11e9-86ac-9c3adb6e54c0.png)

**Comment by qiaoshuai18** [comment]
李老师，那现在怎么解决呢？

**Comment by denzii818** [comment]
李老师，我今天学习时，运行 jupyter lab 命令后，启动的浏览器界面和昨天不一样了，无法进行代码运行学习，不知道怎么回事？帮忙看一下，谢谢。
powershell下的命令操作如下：
![image](https://user-images.githubusercontent.com/56942127/67994259-46c6f180-fc7f-11e9-9b0f-0f609305b5f6.png)
启动到浏览器界面如下：
![image](https://user-images.githubusercontent.com/56942127/67994286-68c07400-fc7f-11e9-97e6-a53654aac8b7.png)
昨天fork了其他文件，不会有影响吧？刚才重新安装了nodejs，显示成功！

**Comment by neolee** [comment]
@denzii818 不要在别人的 issue 下提不相关的问题。你的问题，点左边一列按钮里最上面一个打开文件列表就能看到你的文件了。先搞清楚 Jupyter Lab 这个页面各个部分的作用和意义吧。

**Comment by qxnatalie** [comment]
![image](https://user-images.githubusercontent.com/36719487/68043617-a7523f00-fd10-11e9-9878-ddb86fef562b.png)

**Comment by jinglong-py** [comment]
标题错了吧 jupyter..

**Comment by neolee** [comment]
@qxnatalie 不要在别人的 issue 下问不同的问题，建议另开一个新 issue。

你的问题比较奇怪，很像 Python 或者 Jupyter Lab 没装全。
