### ISSUE TITLE
使用 git commit 和 git push 不能将学习用书的内容推到网络仓库中

### ISSUE THREAD

**Issue by wenshizhe** [neolee/pilot#267]
使用git commit 显示的内容如下：
PS C:\Users\wensh\Code\pilot-student> git commit
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
        modified:   2-structure-1.ipynb
        modified:   3-structure-2.ipynb

no changes added to commit

使用git push 出现了如下对话框：
![image](https://user-images.githubusercontent.com/36652131/67959212-54568a00-fc33-11e9-899a-0469a11f39ca.png)

**Comment by neolee** [comment]
git commit 之前需要把变化先加入到 staging area；

git push 需要你输入 GitHub 的用户名密码，那个弹出的是问你用什么机制保存用户名和密码，我自己没见过这个窗口，你用的什么工具？

**Comment by baichaogang** [comment]
我也遇到同样的问题。
“git commit 之前需要把变化先加入到 staging area”，这个怎么操作？

**Comment by baichaogang** [comment]
经过支线课程学习，已经能push到自己的GitHub，但自己输入的命令没有执行是怎么回事啊

**Comment by reasonbox** [comment]
git commit之前需要把变化先加入staging area;
用git add 文件名
