### ISSUE TITLE
安装 jupyter 插件出现错误

### ISSUE THREAD

**Issue by wenwen-shan** [neolee/pilot#268]
安装插件，选择哪个文件夹更合适，还是都可以呢？对于运行错误，不知道如何修正，进行的尝试都有错误。
![@NBNYF)( S33YU}5J`ODDJX](https://user-images.githubusercontent.com/57054269/67955286-53225e80-fc2d-11e9-881e-1772cac82c7f.png)
![}ZDLGOKXGGALBN7WU2QTO(8](https://user-images.githubusercontent.com/57054269/67955294-54ec2200-fc2d-11e9-9504-9ef2acaec463.png)
![9B~RMYA XQES52$8XOH9T03](https://user-images.githubusercontent.com/57054269/67955299-56b5e580-fc2d-11e9-9213-7ce1ddffc755.png)
在Node.js网站下载软件安装后：关闭重新运行后
![图片](https://user-images.githubusercontent.com/57054269/67959344-8bc53680-fc33-11e9-9164-16ae5bae1ac6.png)
之前的程序运行是否对jupyter有影响，最后一个显示的npm如何解决

**Comment by neolee** [comment]
最好的办法使用 scoop install nodejs 来安装 nodejs。

然后你遇到的问题是 nodejs 的某个需要的包没装好。具体出错信息在最后那个 .log 文件里，你可以用 code 打开那个 log 文件看看具体啥问题。

这个插件不是必须的。
