### ISSUE TITLE
scoop list 显示

### ISSUE THREAD

**Issue by Pony-2019** [neolee/pilot#27]
7zip 19.00
  busybox 3244-g48128b9aa
  git  *failed*
  python37 3.7.5 [versions]

git 是我单独安装的，scoop git 安装不成功。

**Comment by neolee** [comment]
你运行下 git --version 结果是啥？

**Comment by Pony-2019** [comment]
unknown option: --vesion
usage: git [--version] [--help] [-C <path>] [-c <name>=<value>]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]

**Comment by neolee** [comment]
你仔细看看，你输入的拼写错了……

**Comment by Pony-2019** [comment]
git version 2.23.0.windows.1
sorry

**Comment by neolee** [comment]
没问题，这样你只是以后要手工维护 git 的安装，scoop 帮不了你，其他的都 OK 了，可以继续往下走了。

**Comment by Pony-2019** [comment]
谢谢，老师。
