### ISSUE TITLE
关于继承的一点疑问

### ISSUE THREAD

**Issue by johnxie1225** [neolee/pilot#270]
老师好，我在学习类别里面的继承的章节，在您的范例中增加了一些例子试验，但发现在Miumiu这个子类无法将属性bark再次进行重新定义，代码和结果如下，还请老师可以 抽空看一下，谢谢

代码:
class Animal:
    kind = ''
    def __init__(self, name):
        self.name = name
    def voice(self):
        return '...'
class Dog(Animal):
    kind = 'canidae'
    def voice(self):
        return 'woof-woof'
    bark = voice
class Miumiu(Dog):
    kind = 'Teddy'
    def bark(self):
        return 'wan-wan'
    angry = bark
a = Animal('dddd')
b = Dog('Snoopy')
c = Miumiu('my love')
for Animal in [a, b, c]:
    print(Animal.name, ':', Animal.voice(), ':', Animal.kind)
![捕获](https://user-images.githubusercontent.com/56942215/67990282-6b679d00-fc70-11e9-8b15-1ae85dba76e3.PNG)

**Comment by neolee** [comment]
你在 Miumiu 类里定义了 bark 方法，但是并没有在任何地方调用过它。

p.s. 下次贴代码最好截图，或者使用类似这样的格式：

<pre>
```python
你的代码粘贴到这里，保持原有格式
```
</pre>

**Comment by best-way** [comment]
![image](https://user-images.githubusercontent.com/49242101/68030717-13bf4500-fcf5-11e9-8fc3-ea3d55125f06.png)
你应该是这句话的理解有歧义，这个赋值语句的意思应该是新定义了一个方法bark实现的效果和voice方法一样
![微信截图_20191101222100](https://user-images.githubusercontent.com/49242101/68031152-048cc700-fcf6-11e9-840c-b8cb142b5461.png)
你这里只是重写了父类（Dog）的bark方法，并没有重写voice方法

而最后调用的是voice方法，Miumiu类并没有voice方法，所以就调用了父类（Dog）的方法

![微信截图_20191101222502](https://user-images.githubusercontent.com/49242101/68031351-77963d80-fcf6-11e9-8934-852fddcaea06.png)

**Comment by johnxie1225** [comment]
谢谢李老师和热心的小伙伴

**Comment by johnxie1225** [comment]
> ![image](https://user-images.githubusercontent.com/49242101/68030717-13bf4500-fcf5-11e9-8fc3-ea3d55125f06.png)
> 你应该是这句话的理解有歧义，这个赋值语句的意思应该是新定义了一个方法bark实现的效果和voice方法一样
> ![微信截图_20191101222100](https://user-images.githubusercontent.com/49242101/68031152-048cc700-fcf6-11e9-840c-b8cb142b5461.png)
> 你这里只是重写了父类（Dog）的bark方法，并没有重写voice方法
> 
> 而最后调用的是voice方法，Miumiu类并没有voice方法，所以就调用了父类（Dog）的方法
> 
> ![微信截图_20191101222502](https://user-images.githubusercontent.com/49242101/68031351-77963d80-fcf6-11e9-8934-852fddcaea06.png)

谢谢热心的伙伴解答  我有个疑问，按照我的设想，miumiu类不是继承了dog类么，而在dog类的定义中，不是voie已经被定义为bark了么  那到miumiu类这里的时候不是应该就没有voice了而仅有bark的定义了么  那我在miumiu类这里才重新对bark进行了定义
![image](https://user-images.githubusercontent.com/56942215/68060041-bdc0c080-fd39-11e9-8e95-a396745bfde3.png)

**Comment by johnxie1225** [comment]
> 你在 Miumiu 类里定义了 bark 方法，但是并没有在任何地方调用过它。
> 
> p.s. 下次贴代码最好截图，或者使用类似这样的格式：
> 
> ```python
> 你的代码粘贴到这里，保持原有格式
> ```

好的  谢谢老师。。。

**Comment by best-way** [comment]
在dog类的定义中，bark=voice是一个赋值语句（也可以相当于给voice方法取了一个别名），结果是dog类其实有两个方法了，一个voice,一个bark；而miumiu类重写的只是bark方法，没有重写voice方法，所以调用的时候还是用父类dog的voice方法，我上个回复里最后一张图就是一个测试，你也可以自己测试一下

**Comment by johnxie1225** [comment]
明白了 原来是这样子 我一直以为赋值之后 在dog类里面voice就成为bark了 然后继承dog的miumiu类里面也就仅有bark的方法而没有voice


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: best-way <notifications@github.com&gt;
发送时间: 2019年11月2日 08:40
收件人: neolee/pilot <pilot@noreply.github.com&gt;
抄送: johnxie1225 <1281991939@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[neolee/pilot] 关于继承的一点疑问 (#270)




在dog类的定义中，bark=voice是一个赋值语句（也可以相当于给voice方法取了一个别名），结果是dog类其实有两个方法了，一个voice,一个bark；而miumiu类重写的只是bark方法，没有重写voice方法，所以调用的时候还是用父类dog的voice方法，我上个回复里最后一张图就是一个测试，你也可以自己测试一下

**Comment by neolee** [comment]
@johnxie1225 

1. 当你继承一个父类，你确实得到它的一切，`voice` 方法和 `bark` 方法；
2. 父类里用 `bark = voice` 来建立了 voice 方法的的一个别名 `bark`，但当你改写（override） `bark` 方法之后，相当于建立了一个新的 `bark` 并覆盖了父类中的定义，它就不是 voice 的别名而是你定义的新方法了；
3. 如果你想一次改变这两个方法，最简单的方法就是在子类 override `voice` 这个方法，保持 `bark` 作为它的别名，这样子类里这俩就都变成你新定义的方法了。

**Comment by johnxie1225** [comment]
> @johnxie1225
> 
> 1. 当你继承一个父类，你确实得到它的一切，`voice` 方法和 `bark` 方法；
> 2. 父类里用 `bark = voice` 来建立了 voice 方法的的一个别名 `bark`，但当你改写（override） `bark` 方法之后，相当于建立了一个新的 `bark` 并覆盖了父类中的定义，它就不是 voice 的别名而是你定义的新方法了；
> 3. 如果你想一次改变这两个方法，最简单的方法就是在子类 override `voice` 这个方法，保持 `bark` 作为它的别名，这样子类里这俩就都变成你新定义的方法了。

清楚了  谢谢老师  我理解的更加透彻了
