### ISSUE TITLE
Can't shim 'python.exe': File doesn't exist.

### ISSUE THREAD

**Issue by hbfphqt** [neolee/pilot#271]
![image](https://user-images.githubusercontent.com/37977479/67991971-feef9c80-fc75-11e9-810b-6b24fdf6c4c1.png)

**Comment by neolee** [comment]
先运行 `scoop checkup`，按照提示操作，然后在尝试重新安装 Python：

```powershell
scoop uninstall python37
scoop install python37@3.7.4
```
