### ISSUE TITLE
Unable  to read data from the transport connection

### ISSUE THREAD

**Issue by hbfphqt** [neolee/pilot#272]
网络中断后只能重新安装吗？
![image](https://user-images.githubusercontent.com/37977479/67992448-afaa6b80-fc77-11e9-9376-1cc01668ee61.png)

**Comment by neolee** [comment]
安装 Scoop 是网络出错了（在安装 git 的步骤），需要删掉 git 再重装：

```powershell
scoop uninstall git
scoop install git
```
