### ISSUE TITLE
安装 Scoop 出现问题

### ISSUE THREAD

**Issue by reasonbox** [neolee/pilot#273]
运行iwr -useb get.scoop.sh | iex 提示
Initializing...
Scoop is already installed. Run 'scoop update' to get the latest version.

但是，运行PS C:\Users\WXP> scoop list
scoop : 无法将“scoop”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再
试一次。
所在位置 行:1 字符: 1
+ scoop list
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (scoop:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\WXP> scoop checkup
scoop : 无法将“scoop”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再
试一次。
所在位置 行:1 字符: 1
+ scoop checkup
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (scoop:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by reasonbox** [comment]
PS C:\Users\WXP> scoop update
scoop : 无法将“scoop”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再
试一次。
所在位置 行:1 字符: 1
+ scoop update
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (scoop:String) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by neolee** [comment]
Scoop 没装成，需要清掉重装。参考 Wiki 里的“重新安装 Scoop”操作。

**Comment by zerols** [comment]
if i have install and use for a long time how shold i do ？ 
this is error：
PS C:\Users\19890> scoop
& : 无法将“C:\Users\19890\scoop\shims\..\apps\scoop\current\bin\scoop.ps1”项识别为
cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 C:\Users\19890\scoop\shims\scoop.ps1:3 字符: 71
+ ... on.expectingInput) { $input | & $path  @args } else { & $path  @args  ...
+                                                             ~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\19890\...t\bin\scoop.ps1:String) [], ParentContainsErrorRecord
   Exception
    + FullyQualifiedErrorId : CommandNotFoundException
