### ISSUE TITLE
用什么指令删除scoop 中已安装软件？

### ISSUE THREAD

**Issue by qiaoshuai18** [neolee/pilot#274]
![image](https://user-images.githubusercontent.com/57203396/67996350-eb4e3100-fc89-11e9-9bff-1b9ce5fd6311.png)

**Comment by weidong3597** [comment]
我想应该是：scoop uninstall git 。教程中有说重新下载软件包，可以执行：scoop install xxxx（xxxx是软件包的名称）install是安装的意思，那我想把其换成uninstall（卸载）就是卸载软件包吧，因为我当前没有下载成功任何的软件包，所以也没有去尝试是否可行。

**Comment by neolee** [comment]
用 `scoop help` 可以看到所有 Scoop 支持的命令，卸载是 `scoop uninstall`。不过你的截图里没啥好删除的，都是要用的。
