### ISSUE TITLE
scoop update 失败，是网络问题吗？

### ISSUE THREAD

**Issue by qiaoshuai18** [neolee/pilot#276]
![image](https://user-images.githubusercontent.com/57203396/67997716-5f8bd300-fc90-11e9-8b8e-201c8dd71d5e.png)

**Comment by qixinsame** [comment]
我的报错提示是一样的。我使用的是VPN的服务，上Google，GitHub，YouTube都没有问题，请问如果是VPN的问题的话有什么解决办法吗？

**Comment by neolee** [comment]
@qixinsame 有些代理对命令行需要特定设置，可以咨询下你的服务商。
