### ISSUE TITLE
安装 Scoop 时提示先运行 `scoop install git`

### ISSUE THREAD

**Issue by azheng526** [neolee/pilot#28]
![image](https://user-images.githubusercontent.com/50059311/67389320-f55a9a80-f5cc-11e9-9a3f-7c63881926d1.png)

**Comment by neolee** [comment]
尝试运行下面两个命令：

```shell
scoop uninstall git
scoop install git
```

结果截给我看看。

**Comment by azheng526** [comment]
![image](https://user-images.githubusercontent.com/50059311/67389666-a6613500-f5cd-11e9-87dc-dcd1a26c3011.png)

**Comment by azheng526** [comment]
老师，这步是不是可以了！！

**Comment by neolee** [comment]
应该是可以了，你可以继续往下试试了 👍

**Comment by chepeiling** [comment]
你好，我可以请问一下，提问的时候怎么添加截图吗?

**Comment by neolee** [comment]
@chepeiling 把图片拖进编辑窗口就行了。
