### ISSUE TITLE
Win 10 找不到 Command Prompt

### ISSUE THREAD

**Issue by oneisonly** [neolee/pilot#280]
点击桌面左下角的搜索按钮，输入 cmd ，只显示一个cmd，没有命令行界面（Command Prompt）；

**Comment by neolee** [comment]
能截个图看看吗？就是你在搜索框输入 cmd 之后的桌面。

**Comment by oneisonly** [comment]
![53073fd6c764cbcd656c39e3c3d8799](https://user-images.githubusercontent.com/53245383/68005027-c5875300-fcae-11e9-8985-ad79749c905b.jpg)

**Comment by neolee** [comment]
就点那个就行了。

你这个 WIndows 看着好别致……
