### ISSUE TITLE
给函数赋值之后，查看赋值类型出现报错

### ISSUE THREAD

**Issue by RENXINPAN** [neolee/pilot#281]
a = 12
type(a)
运行之后就出现报错，'int' object is not callable
百度之后给出的答案都说是 名称冲突，改名即可。
但改来改去都没办法。

其次，在第一个代码行赋值之后，重新在下一个代码行运行的话也会出现报错，name 't' is not defined

**Comment by neolee** [comment]
你应该前面执行了 type = xxx 这样的代码，把内置函数 type 变成一个变量了。

给出完整的代码才好判断。
