### ISSUE TITLE
安装 scoop 出错：Unable to connect to the remote server

### ISSUE THREAD

**Issue by wscjxmm** [neolee/pilot#282]
![U{0 %BVS0OP7){HN9C`11NM](https://user-images.githubusercontent.com/57230651/68004389-4a24a200-fcac-11e9-853d-b73735c71a94.png)

**Comment by tianzhansheng321** [comment]
换了好多网络，好像不是网速的问题，一次偶然成功了，安装GIT又连接不上，将SCOOP删掉后，现在又装不上了，哎，好像要设置VPN，这方面这两天各种搜索，过程纠结啊

**Comment by reasonbox** [comment]
这个要保持科学上网稳定，用时间比较久。我估计安装了快一个小时呢
