### ISSUE TITLE
Mac 中重新运行 jupyter lab 后无法看见教材文件

### ISSUE THREAD

**Issue by bill79927** [neolee/pilot#283]

**Comment by neolee** [comment]
没有更多信息的话，完全不知道发生了什么。

**Comment by bill79927** [comment]
> 没有更多信息的话，完全不知道发生了什么。

就是左边栏本来应该是教材目录，但是目前是我桌面文件夹的内容

**Comment by bill79927** [comment]
简单的说就是重新运行jutyper lab的流程是啥？我单一输入运行后目前看不到教材目录，是不是要重新clone一下链接，再运行才可以？

**Comment by neolee** [comment]
你需要在你的学习用书的目录下运行 `jupyter lab`。
