### ISSUE TITLE
用 git restore --staged + 文件名 将文件移出”暂存区“时出现错误提示

### ISSUE THREAD

**Issue by zhangSen1987** [neolee/pilot#284]
![问题描述](https://user-images.githubusercontent.com/53714512/68014634-186f0380-fccb-11e9-8a88-dd5ddaf6c1f3.jpg)
运行这个命令的时候提示的。

**Comment by neolee** [comment]
你创建文件时错误的用了 `.README.md` 而不是 `README.md`，所以就找不到了。
