### ISSUE TITLE
scoop 安装时显示无法连接远程服务器

### ISSUE THREAD

**Issue by zhangfei002** [neolee/pilot#285]
C:\Users\baivictoryai> iwr -useb get.scoop.sh | iex
iwr : 无法连接到远程服务器
所在位置 行:1 字符: 1
+ iwr -useb get.scoop.sh | iex
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:
   HttpWebRequest) [Invoke-WebRequest]，WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.Power
   Shell.Commands.InvokeWebRequestCommand

**Comment by iceberg-yuan** [comment]
我的也是，你最后解决了吗？

**Comment by iceberg-yuan** [comment]
1.把杀毒软件关了。2.wifi换成手机热点。3.scoop.sh也能登上去。怎么就不行呢

**Comment by reasonbox** [comment]
科学上网，360卫士等杀毒软件关闭

**Comment by piandong** [comment]
我遇到了同样的问题。解决方法：打开一个管理员权限的 PowerShell 界面，再进行安装。之后的操作都在管理员权限界面进行
![scoop安装](https://user-images.githubusercontent.com/52729587/68064803-400dac80-fd5b-11e9-8e0e-f2526f12f52e.png)

**Comment by xunfeng333** [comment]
我也遇到同样问题试过几十次   最后科学上网 得到解决

**Comment by xunfeng333** [comment]
不会科学上网联系我

**Comment by zhangfei002** [comment]
谢谢各位关注和帮助，“无法远程连接服务器”的问题以及解决。
https://www.txvpn.net/可以用这个网址下载一个加速器
![image](https://user-images.githubusercontent.com/49616309/68067527-005abb00-fd83-11e9-8033-49fcd0640e0f.png)用手机号注册，可以试用几个小时，如果以后需要长期试用，可以付费

**Comment by neolee** [comment]
@zhangfei002 我们不允许贴这类信息。

**Comment by zhangfei002** [comment]
好的，以后不发了发自我的华为手机-------- 原始邮件 --------发件人： Neo Lee <notifications@github.com>日期： 2019年11月2日周六 傍晚6:31收件人： neolee/pilot <pilot@noreply.github.com>抄送： zhangfei002 <fhzl_jz@126.com>, Mention <mention@noreply.github.com>主    题： Re: [neolee/pilot] scoop 安装时显示无法连接远程服务器 (#285)@zhangfei002 我们不允许贴这类信息。
