### ISSUE TITLE
写代码的时候不同类型的值组成语句是一般都会加 一个空格键，是一定要还是为了美观？

### ISSUE THREAD

**Issue by lidewen-yue** [neolee/pilot#288]
while True:
    n = randrange(-2, 5) # randrange 返回一个给定范围的随机整数
    if n < 0:
        break
    elif n % 2 == 0:
        print(n, 'is even')
    else:
        print(n, 'is odd')

例如：n = randrange中n和=号中就有一个空格或者n % 2 == 0(n与%与2之前都有空格），但是我尝试过即使没有空格也不影响运行，请老师指教。

**Comment by neolee** [comment]
不是语法要求的必须，但好看一点。
