### ISSUE TITLE
Scoop 安装 git 失败显示 `ERROR It looks like a previous installation of git failed`

### ISSUE THREAD

**Issue by wangnanqiang** [neolee/pilot#29]
![图片](https://user-images.githubusercontent.com/53247740/67391079-75363400-f5d0-11e9-98e1-041ff5977228.png)
![图片](https://user-images.githubusercontent.com/53247740/67391099-7f583280-f5d0-11e9-886d-ece96216d2e3.png)

**Comment by neolee** [comment]
先 scoop uninstall git 然后再 scoop install git 试试。
