### ISSUE TITLE
scoop如何管理事先安装好的软件

### ISSUE THREAD

**Issue by imSeaton** [neolee/pilot#294]
![1](https://user-images.githubusercontent.com/56856685/68030246-f5a51500-fcf3-11e9-9c79-a47eac82f3d2.png)
![2](https://user-images.githubusercontent.com/56856685/68030247-f5a51500-fcf3-11e9-951a-3c4d93d0e381.png)
老师您好，我之前已经安装过git，在本地能成功运行（环境变量也自己设置好了），到那时现在使用scoop list时，scoop却没法列出之前已经安装过的软件。请问现在如何用scoop管理之前已经安装好的软件（例如git、anaconda)?是否只能够用scoop卸载再重新安装？

**Comment by neolee** [comment]
配置指南主要是给干净系统用的，之前装过相关软件的话，只有假定你完全清楚如何使用这些软件。

Scoop 对于那些非自己安装和管理的软件是无能为力的，自然也不会列出。
