### ISSUE TITLE
无法安装 git

### ISSUE THREAD

**Issue by zhipingyang120** [neolee/pilot#296]
问题已经重新编辑：
李老师看，我输入scoop install git后，
PS C:\Users\Administrator> scoop install git
Installing '7zip' (19.00) [64bit]
7z1900-x64.msi (1.7 MB) [=============================================] 100%
Checking hash of 7z1900-x64.msi ... ok.
Extracting 7z1900-x64.msi ... done.
Linking ~\scoop\apps\7zip\current => ~\scoop\apps\7zip\19.00
Creating shim for '7z'.
Creating shortcut for 7-Zip (7zFM.exe)
'7zip' (19.00) was installed successfully!
Installing 'git' (2.23.0.windows.1) [64bit]
PortableGit-2.23.0-64-bit.7z.exe (41.5 MB) [>                         ]   0%
操作已超时。
URL https://github.com/git-for-windows/git/releases/download/v2.23.0.windows.1/PortableGit-2.23.0-64-bit.7z.exe#/dl.7z is not valid

我通过迅雷下载了PortableGit-2.23.0-64-bit.7z.exe (41.5 MB)这个文件，
并将文件移动到scoop/cache文件夹里，
scoop uninstall git
Uninstalling 'git' ().
'git' was uninstalled.

scoop install git

仍旧无法安装。
于是我直接安装，然后执行git --version
git : 无法将“git”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名
称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ git --version
+ ~~~
    + CategoryInfo          : ObjectNotFound: (git:String) [], CommandNotFound
   Exception
    + FullyQualifiedErrorId : CommandNotFoundException
显示还是不行，我该怎么办？

**Comment by Lilidandan321** [comment]
这个应该是网络不好，我之前也下载不了，然后自己下载了个git，按照老师的提示
“如果你已经用其他方法安装好了 git，可以执行 git --version 看看返回正常不。
如果正常，可以跳过指南中 scoop install git 这一步，直接执行 scoop update，然后继续后面的。”
运行还可以，你也可以自己下载个git试试。参照133#提问

**Comment by zhipingyang120** [comment]
我自己通过迅雷下载了这个软件，PortableGit-2.23.0-64-bit.7z.exe (41.5 MB)
但是我不知道应该安装在哪里，我就安装在D/Program Files里面
执行 git --version
得到：PS C:\Users\Administrator> git --version
git : 无法将“git”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名
称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ git --version
+ ~~~
    + CategoryInfo          : ObjectNotFound: (git:String) [], CommandNotFound
   Exception
    + FullyQualifiedErrorId : CommandNotFoundException
还是无法scoop update

**Comment by whxzhou** [comment]
你的问题解决了吗？我也遇到了这个问题不知道怎么搞

**Comment by zhipingyang120** [comment]
没有解决。
我参考了133#提问
The solution is:

add 
192.30.253.112  github.com
192.30.253.113  github.com
to your hosts file
scoop install aria2
3. install git
scoop uninstall git
Uninstalling 'git' ().
'git' was uninstalled.
scoop install git
 

repeat step 3 until the installation is successful,make sure your network is stable
 
another solution :

download right PortableGit-2.23.0-32-bit.7z.exe for your computer
put it in your scoop/cache folder
scoop uninstall git
Uninstalling 'git' ().
'git' was uninstalled.

scoop install git

使用上述两种方法，仍旧无法安装GIT
Windows PowerShell
版权所有 (C) 2016 Microsoft Corporation。保留所有权利。

PS C:\Users\Administrator> scoop install aria2
Scoop uses Git to update itself. Run 'scoop install git' and try again.
ERROR It looks like a previous installation of aria2 failed.
Run 'scoop uninstall aria2' before retrying the install.
WARN  'aria2' () is already installed.
Use 'scoop update aria2' to install a new version.
PS C:\Users\Administrator> scoop uninstall aria2
Uninstalling 'aria2' ().
'aria2' was uninstalled.
PS C:\Users\Administrator> scoop install aria2
Scoop uses Git to update itself. Run 'scoop install git' and try again.
Installing 'aria2' (1.35.0-1) [64bit]
aria2-1.35.0-win-64bit-build1.zip (2.1 MB) [>                         ]   0%
无法从传输连接中读取数据: 远程主机强迫关闭了一个现有的连接。。
URL https://github.com/aria2/aria2/releases/download/release-1.35.0/aria2-1.35.0-win-64bit-build1.zip is not valid
PS C:\Users\Administrator> scoop install git
Scoop uses Git to update itself. Run 'scoop install git' and try again.
ERROR It looks like a previous installation of git failed.
Run 'scoop uninstall git' before retrying the install.
WARN  'git' () is already installed.
Use 'scoop update git' to install a new version.
PS C:\Users\Administrator> scoop  uninstall git
Uninstalling 'git' ().
'git' was uninstalled.
PS C:\Users\Administrator> scoop install git
Scoop uses Git to update itself. Run 'scoop install git' and try again.
Installing 'git' (2.23.0.windows.1) [64bit]
PortableGit-2.23.0-64-bit.7z.exe (41.5 MB) [>                         ]   0%
无法从传输连接中读取数据: 远程主机强迫关闭了一个现有的连接。。
URL https://github.com/git-for-windows/git/releases/download/v2.23.0.windows.1/PortableGit-2.23.0-64-bit.7z.exe#/dl.7z is not valid
PS C:\Users\Administrator> git --version
git : 无法将“git”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名
称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ git --version
+ ~~~
    + CategoryInfo          : ObjectNotFound: (git:String) [], CommandNotFound
   Exception
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by zhipingyang120** [comment]
我采用了第二种解决办法，通过迅雷下载了PortableGit-2.23.0-64-bit.7z.exe (41.5 MB) 这个文件，并将文件移动到scoop/cache文件夹里，
scoop uninstall git
Uninstalling 'git' ().
'git' was uninstalled.

scoop install git

仍旧无法安装，我该怎么办啊？

**Comment by neolee** [comment]
报什么错？

**Comment by zhipingyang120** [comment]
PS C:\Users\Administrator> scoop uninstall git
Uninstalling 'git' ().
'git' was uninstalled.
PS C:\Users\Administrator> scoop install git
Scoop uses Git to update itself. Run 'scoop install git' and try again.
Installing 'git' (2.23.0.windows.1) [64bit]

继续下载，可是下载不下来。

**Comment by neolee** [comment]
是啊，这就是网络的问题啊，还是没解决。

**Comment by stones-zhang** [comment]
> 没有解决。
> 我参考了133#提问
> The solution is:
> 
> add
> 192.30.253.112 github.com
> 192.30.253.113 github.com
> to your hosts file
> scoop install aria2
> 3. install git
> scoop uninstall git
> Uninstalling 'git' ().
> 'git' was uninstalled.
> scoop install git
> 
> repeat step 3 until the installation is successful,make sure your network is stable
> 
> another solution :
> 
> download right PortableGit-2.23.0-32-bit.7z.exe for your computer
> put it in your scoop/cache folder
> scoop uninstall git
> Uninstalling 'git' ().
> 'git' was uninstalled.
> 
> scoop install git
> 
> 使用上述两种方法，仍旧无法安装GIT
> Windows PowerShell
> 版权所有 (C) 2016 Microsoft Corporation。保留所有权利。
> 
> PS C:\Users\Administrator> scoop install aria2
> Scoop uses Git to update itself. Run 'scoop install git' and try again.
> ERROR It looks like a previous installation of aria2 failed.
> Run 'scoop uninstall aria2' before retrying the install.
> WARN 'aria2' () is already installed.
> Use 'scoop update aria2' to install a new version.
> PS C:\Users\Administrator> scoop uninstall aria2
> Uninstalling 'aria2' ().
> 'aria2' was uninstalled.
> PS C:\Users\Administrator> scoop install aria2
> Scoop uses Git to update itself. Run 'scoop install git' and try again.
> Installing 'aria2' (1.35.0-1) [64bit]
> aria2-1.35.0-win-64bit-build1.zip (2.1 MB) [> ] 0%
> 无法从传输连接中读取数据: 远程主机强迫关闭了一个现有的连接。。
> URL https://github.com/aria2/aria2/releases/download/release-1.35.0/aria2-1.35.0-win-64bit-build1.zip is not valid
> PS C:\Users\Administrator> scoop install git
> Scoop uses Git to update itself. Run 'scoop install git' and try again.
> ERROR It looks like a previous installation of git failed.
> Run 'scoop uninstall git' before retrying the install.
> WARN 'git' () is already installed.
> Use 'scoop update git' to install a new version.
> PS C:\Users\Administrator> scoop uninstall git
> Uninstalling 'git' ().
> 'git' was uninstalled.
> PS C:\Users\Administrator> scoop install git
> Scoop uses Git to update itself. Run 'scoop install git' and try again.
> Installing 'git' (2.23.0.windows.1) [64bit]
> PortableGit-2.23.0-64-bit.7z.exe (41.5 MB) [> ] 0%
> 无法从传输连接中读取数据: 远程主机强迫关闭了一个现有的连接。。
> URL https://github.com/git-for-windows/git/releases/download/v2.23.0.windows.1/PortableGit-2.23.0-64-bit.7z.exe#/dl.7z is not valid
> PS C:\Users\Administrator> git --version
> git : 无法将“git”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名
> 称的拼写，如果包括路径，请确保路径正确，然后再试一次。
> 所在位置 行:1 字符: 1
> 
> * git --version
> * ```
>     + CategoryInfo          : ObjectNotFound: (git:String) [], CommandNotFound
>    Exception
>     + FullyQualifiedErrorId : CommandNotFoundException
>   ```

我这两天安装一直也是这个提示，我不断的重复scoop uninstall git 和 scoop install git .刚刚安装好了，速度很快。你现在试一下。
PS C:\Users\stones> scoop uninstall git
Uninstalling 'git' ().
'git' was uninstalled.
PS C:\Users\stones> scoop install git
Scoop uses Git to update itself. Run 'scoop install git' and try again.
Installing 'git' (2.23.0.windows.1) [64bit]
PortableGit-2.23.0-64-bit.7z.exe (41.5 MB) [==========================] 100%
Checking hash of PortableGit-2.23.0-64-bit.7z.exe ... ok.
Extracting dl.7z ... done.
Linking ~\scoop\apps\git\current => ~\scoop\apps\git\2.23.0.windows.1
Creating shim for 'git'.
Creating shim for 'gitk'.
Creating shim for 'git-gui'.
Creating shim for 'tig'.
Creating shim for 'git-bash'.
Creating shortcut for Git Bash (git-bash.exe)
Running post-install script...
'git' (2.23.0.windows.1) was installed successfully!
Notes
-----
To get Git to recognise OpenSSH, you will need to run

scoop install openssh
[environment]::setenvironmentvariable('GIT_SSH', (resolve-path (scoop which
ssh)), 'USER')

and then restart powershell.
PS C:\Users\stones> scoop list
Installed apps:

  7zip 19.00
  git 2.23.0.windows.1

PS C:\Users\stones>

**Comment by zhipingyang120** [comment]
我重装了系统，使用VPN重新安装，结果还是有问题：
从传输流收到意外的 EOF 或 0 个字节。
这个要怎么处理？
PS C:\Users\90522> scoop install git
Installing '7zip' (19.00) [64bit]
7z1900-x64.msi (1.7 MB) [=============================================] 100%
Checking hash of 7z1900-x64.msi ... ok.
Extracting 7z1900-x64.msi ... done.
Linking ~\scoop\apps\7zip\current => ~\scoop\apps\7zip\19.00
Creating shim for '7z'.
Creating shortcut for 7-Zip (7zFM.exe)
'7zip' (19.00) was installed successfully!
Installing 'git' (2.23.0.windows.1) [64bit]
PortableGit-2.23.0-64-bit.7z.exe (41.5 MB) [>                         ]   6%
从传输流收到意外的 EOF 或 0 个字节。
URL https://github.com/git-for-windows/git/releases/download/v2.23.0.windows.1/PortableGit-2.23.0-64-bit.7z.exe#/dl.7z is not valid
PS C:\Users\90522>

**Comment by neolee** [comment]
@zhipingyang120  我不知道你是怎么配置网络代理的，但是很多代理并不能直接对命令行发挥作用，需要进行一些配置，具体可以咨询你的代理提供者。

**Comment by zhipingyang120** [comment]
李老师，问题解决了，客服叫我重启系统，重启VPN，再次连接就可以下载了。
这么简单的问题，困扰了我将近9个小时，但解决后，感觉自己的英语和计算机能力又进步了一点点。
真开心！
感谢！

**Comment by neolee** [comment]
Nice! Keep going!
