### ISSUE TITLE
python37安装失败，请问如何解决

### ISSUE THREAD

**Issue by tangtql** [neolee/pilot#3]
PowerSheel中执行scoop install python37，返回“Couldn't find manifest for 'python37'.”

**Comment by neolee** [comment]
先运行：scoop bucket add versions

然后：scoop uodate

再：scoop install python37

就可以了，原来的配置指引漏了这一步，昨晚已经更新过。

**Comment by tangtql** [comment]
收到，感谢。




------------------ 原始邮件 ------------------
发件人: "Neo Lee"<notifications@github.com>;
发送时间: 2019年10月23日(星期三) 上午9:48
收件人: "neolee/pilot"<pilot@noreply.github.com>;
抄送: "小汤"<317372322@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [neolee/pilot] python37安装失败，请问如何解决 (#3)




先运行：scoop bucket add versions
 
然后：scoop uodate
 
再：scoop install python37
 
就可以了，原来的配置指引漏了这一步，昨晚已经更新过。

**Comment by neolee** [comment]
如果成功请回来这里说一声，我好关闭 issue 😃
