### ISSUE TITLE
学习用书中的代码按了‘shift+enter’之后没有反应是怎么回事？

### ISSUE THREAD

**Issue by xiaoerhai** [neolee/pilot#301]

**Comment by Lilidandan321** [comment]
应该是ctrl+enter

**Comment by neolee** [comment]
Control+回车 执行
Alt+回车 执行并在下方新开一个代码 cell

**Comment by xiaoerhai** [comment]
奇怪，都不行，在其他章节都是可以的。没有反应的特征是：最左边的[]里是‘*’，而不是数字。

**Comment by neolee** [comment]
那个 * 表示还在运行没出结果，很可能 notebook 背后的 Python kernel 挂了，或者在执行无限循环，你可以点 notebook 工具条里的“Restart kernel”来重启 kernel，然后再试。

p.s. Wiki 里支线课程第三讲可以看看。
