### ISSUE TITLE
退出 ConEmu，发现进入不了了。

### ISSUE THREAD

**Issue by zhipingyang120** [neolee/pilot#304]
我按照李老师的步骤
退出 ConEmu 然后重新运行它，结果发现，哪里都找不到ConEmu了。
后来发现在C盘里。
可是每次打开ConEmu，都要去C盘里很深的一个文件夹里找。
我后来想到复制一个快捷方式到桌面，可是重启之后，就发现快捷方式不能用了

**Comment by zhipingyang120** [comment]
不好意，是我下载错了，我下载了第一个，压缩格式的，应该下载第二个，就可以安装了。

**Comment by hermionepei1029** [comment]
我遇到了同样的问题，谢谢你！
就是点击下载后，排序第一的是一个内含很多文件的压缩文件；但是其实应该下载的是排序在第二的那个，直接就是一个可以安装的.exe格式~
