### ISSUE TITLE
git依赖包gettext提示信息是否影响以后使用

### ISSUE THREAD

**Issue by spring-ap** [neolee/pilot#305]
![image](https://user-images.githubusercontent.com/57279823/68066088-78b68180-fd6d-11e9-82ac-71eb2e982ca8.png)

**Comment by neolee** [comment]
那段提示不影响 git 使用，这个问题涉及 *nix 系统中多个版本的库或者可执行程序并存时的处理办法，以后有机会可以专门讲讲。
