### ISSUE TITLE
安装 scoop install python37@3.7.4 出现这个错误提示该怎么操作

### ISSUE THREAD

**Issue by yuzanzan** [neolee/pilot#306]
<img width="630" alt="image" src="https://user-images.githubusercontent.com/54825122/68066605-8bcd4f80-fd75-11e9-9b43-309dd3163a7c.png">

**Comment by neolee** [comment]
这个问题也算多发了，有不少 issue 与此有关，总体思路是先 `scoop checkup` 并解决其提出的问题，然后重装 Python：

```powershell
scoop uninstall python37
scoop install python37@3.7.4
```

可以参考 #32
