### ISSUE TITLE
输入 python -m pip install --upgrade pip 显示 /usr/bin/python: No module named pip

### ISSUE THREAD

**Issue by TheTreeTree** [neolee/pilot#307]
[
![WeChatfaa3b381e0884fa034f3b2165ed67522](https://user-images.githubusercontent.com/50830915/68066938-b53caa00-fd7a-11e9-84c5-ce8b9ec9075e.png)
](url)

**Comment by neolee** [comment]
如果你用 Homebrew 安装的 Python，不太会有这个问题。

首先用 `python -V` 确认你的 Python 版本是 3.7.4，然后尝试 `python -m ensurepip` 来补安装 pip。

**Comment by spring-ap** [comment]
建议python修改为python3
即 python3 -m pip install --upgrade pip
我的mac上就是这样用的。

**Comment by TheTreeTree** [comment]
@neolee 李骏老师我检查版本的时候是2.7.10
输入python3 却显示：
Python 3.7.4 (default, Oct 12 2019, 18:55:28) 
[Clang 11.0.0 (clang-1100.0.33.8)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

**Comment by TheTreeTree** [comment]
@neolee 输入python3 -V显示：
Python 3.7.4

**Comment by TheTreeTree** [comment]
@spring-ap 
用你的方法 会这样好像是在下载了，到一半不动了，然后就出现一大片的橙色的字
![WeChatdcf08cdb9fe0924eeb569debb69bb093](https://user-images.githubusercontent.com/50830915/68070805-19c52c80-fdae-11e9-834a-9d3923ec3bf1.png)

**Comment by TheTreeTree** [comment]
![WeChat34436460bbb40599810ce3c2b96a159a](https://user-images.githubusercontent.com/50830915/68070928-acb29680-fdaf-11e9-8544-b702a21ced37.png)
再试了第二遍好像好了 @spring-ap

**Comment by neolee** [comment]
是的，你的系统里要用 python3 和 pip3 来使用对应功能，然后你可以 `pip3 install jupyterlab` 来继续安装 Jupyter Lab 了。

前面倒数第二个截图是网络错误，后面你重试就成了。

**Comment by tangwendong** [comment]
我的C:\Users\Tang\scoop\shims文件夹里有python.exe、python3.exe，还有python37.exe。
我也遇到这个问题，即“输入 python -m pip install --upgrade pip”显示××××××: No module named pip‘’，安装李老师的第一条回复使用“python -m ensurepip 来补安装 pip”成功了。
