### ISSUE TITLE
在jupyter 写入代码练习时 代码怎么不执行

### ISSUE THREAD

**Issue by hongshuhai** [neolee/pilot#31]
老师您好，我按照教程里在jupyter写入代码

例如
# tpye (42)

然后按使用“crtl + enter "执行代码，代码没有反应。

而在mac里的terminal里打开Python执行是正常的。会显示
>>> type(42)
<class 'int'>

**Comment by neolee** [comment]
能把你的打开的 Notebook 截个图发到这里看看吗？

**Comment by hongshuhai** [comment]
![Uploading abc.png…]()

**Comment by hongshuhai** [comment]
老师 您能看到截图吗

**Comment by hongshuhai** [comment]
![abc](https://user-images.githubusercontent.com/36213253/67401206-6441ee80-f5e1-11e9-9b78-4c7c3cb3670c.png)

**Comment by neolee** [comment]
代码前面的 # 的作用是让其后的内容成为“代码注释”，也就是程序不会运行的说明性文字，所以你要把这些 # 删掉才行。

**Comment by hongshuhai** [comment]
![bcd](https://user-images.githubusercontent.com/36213253/67402135-b46d8080-f5e2-11e9-8f9e-d3e71f062923.png)
谢谢老师，问题已解决。
