### ISSUE TITLE
教学用书中类，继承中运行的疑问

### ISSUE THREAD

**Issue by Jared-Gong** [neolee/pilot#310]
![1572682475](https://user-images.githubusercontent.com/56901849/68068091-1faa1600-fd8c-11e9-9a9a-03855885d476.png)
![1572682840(1)](https://user-images.githubusercontent.com/56901849/68068125-c55d8500-fd8c-11e9-900b-a81f7f93bb52.png)

老师，上面的例子上，我分别在三个cell中运行了三组代码，发现后面两个只运行最后一条代码，而第一组中，赋值语句确有运行。请问老师，这怎么情况呢？

**Comment by neolee** [comment]
`d.name` 这样的代码，其实就是一个 Python 里的变量，单独执行，Python 解释器会显示它的值，但是和其他代码一起执行则不会专门显示什么了。

`d.bark()` 则不同，它里面调用了 `print()` 函数，无论如何都会在标准输出界面打印内容出来。

所以你看到的现象完全正常。如果要向看到 `d.name` 的结果，要么单独一行（cell）执行它，要么用 `print(d.name)`，还有个办法是用 Jupyter Notebook 提供的 InteractiveShell 接口（这个会使得 notebook 的表现和 Python 解释器出现差异，我并不是很推荐）：

```python
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
```

**Comment by Jared-Gong** [comment]
在第二个和第三个cell中 ，我只是换了一下d.name和d.bark（）的位置呢，从结果中看，第三个cell中的d.bark（）也并没有被执行。两个cell执行的都是第一条代码。

**Comment by Jared-Gong** [comment]
> `d.name` 这样的代码，其实就是一个 Python 里的变量，单独执行，Python 解释器会显示它的值，但是和其他代码一起执行则不会专门显示什么了。
> 
> `d.bark()` 则不同，它里面调用了 `print()` 函数，无论如何都会在标准输出界面打印内容出来。
> 
> 所以你看到的现象完全正常。如果要向看到 `d.name` 的结果，要么单独一行（cell）执行它，要么用 `print(d.name)`，还有个办法是用 Jupyter Notebook 提供的 InteractiveShell 接口（这个会使得 notebook 的表现和 Python 解释器出现差异，我并不是很推荐）：
> 
> ```python
> from IPython.core.interactiveshell import InteractiveShell
> InteractiveShell.ast_node_interactivity = "all"
> ```

在第二个和第三个cell中 ，我只是换了一下d.name和d.bark（）的位置呢，从结果中看，第三个cell中的d.bark（）也并没有被执行。两个cell执行的都是第一条代码。

**Comment by neolee** [comment]
是我记错了，`bark()` 里也没有调用 `print()` 函数，所以和 `d.name` 是一样的性质，那就只有最后一个会显示出来。我修改了前面的一个 comment，以免误导。
