### ISSUE TITLE
5-structure-4中对range()函数的第2个版本描述是不是笔误

### ISSUE THREAD

**Issue by Maxuanrui** [neolee/pilot#311]
5-structure-4中对range()函数的第2个版本描述是不是笔误
“[start,start+step,start_step*2,...]”，应是“[strat,start+step,start+step*2,...]”
![1572685560(1)](https://user-images.githubusercontent.com/53324687/68068742-4881d980-fd93-11e9-8f3b-67be0240d383.jpg)

**Comment by neolee** [comment]
这个之前已经修复了，你可以阅读线上的最新版本。

学习用书不适合频繁更新，所以一些不严重的错误暂时不会修。
