### ISSUE TITLE
运行 jupyter lab 浏览器中不自动出现学习用书目录，提示手动复制粘贴链接

### ISSUE THREAD

**Issue by Weijing14** [neolee/pilot#312]
![image](https://user-images.githubusercontent.com/57029069/68068934-2d17ce00-fd95-11e9-9d8b-d88455f4a039.png)

**Comment by neolee** [comment]
你的问题到底是 `jupyter lab` 命令没有打开浏览器（这问题支线课程第三讲里讲了），还是打开了浏览器但没有显示 Jupyter Lab 界面（这问题第三讲也讲了，是浏览器兼容性问题），还是打开了界面但是没出现学习用书（这问题多数是你运行命令的工作目录有问题）？

至于命令行提示里那句话，说的是可以打开 Jupyter Lab 的几种方式，如果能自动打开就可以无视，否则手工拷贝 `http://localhost:` 打头那一行到浏览器地址栏打开就好了。

另外，此类问题也很多了，可以先搜索 issues 再问。
