### ISSUE TITLE
Scoop 安装和 scoop update 出错

### ISSUE THREAD

**Issue by yuzanzan** [neolee/pilot#313]
<img width="791" alt="image" src="https://user-images.githubusercontent.com/54825122/68069130-0c507800-fd97-11e9-968a-ef0e8aa9d268.png">

**Comment by yuzanzan** [comment]
![Uploading image.png…]()
因为上面的问题我回顾了前面的安装步骤，发现下图这个红框处没有勾选，还有箭头处另存为无法点击，影不影响呢？

**Comment by yuzanzan** [comment]
<img width="575" alt="image" src="https://user-images.githubusercontent.com/54825122/68069264-e88e3180-fd98-11e9-9ab5-832645ed7b10.png">

因为上面的问题我回顾了前面的安装步骤，发现下图这个红框处没有勾选，还有箭头处另存为无法点击，影不影响呢？

**Comment by neolee** [comment]
那个设置项没啥关系，Save Settings 灰着可能是因为你没修改什么设定，无需保存。

你真正的问题是运行那行命令的权限不够，你试试打开一个 {{ PowerShell (Admin) }} 的管理员权限界面执行，应该就可以了。

**Comment by yuzanzan** [comment]
<img width="433" alt="image" src="https://user-images.githubusercontent.com/54825122/68069802-45411a80-fda0-11e9-8e69-b9f67087140d.png">
选择管理员权限以后无法保存，设置不了

**Comment by neolee** [comment]
你现在 ConEmu 主窗口，绿色 + 号按钮打开一个 {{ PowerShell (Admin) }} 的 tab 试试。

**Comment by yuzanzan** [comment]
<img width="803" alt="image" src="https://user-images.githubusercontent.com/54825122/68070049-b0402080-fda3-11e9-9d4d-860bd381cf87.png">
按老师说的操作以后是这样的，还是不行

**Comment by neolee** [comment]
这不是进了一步么，第一个命令已经成功了，后面一个错误是网络问题，下载安装 Scoop 失败。这个需要换网络或者代理。

**Comment by yuzanzan** [comment]
<img width="469" alt="image" src="https://user-images.githubusercontent.com/54825122/68070161-9f90aa00-fda5-11e9-9236-e517b228cdd3.png">
<img width="473" alt="image" src="https://user-images.githubusercontent.com/54825122/68070163-a61f2180-fda5-11e9-95f4-1fdd21ea1af5.png">
换了网络，又出现了上面的问题，用管理员身份运行也不行

**Comment by neolee** [comment]
你的 Scoop 没装好，按照 Wiki 里“重新安装 Scoop”操作，重新安装。

**Comment by yuzanzan** [comment]
<img width="958" alt="image" src="https://user-images.githubusercontent.com/54825122/68071038-dc15d300-fdb0-11e9-97a6-6d02678f38dc.png">
重装scoop以后还是不能update

**Comment by neolee** [comment]
从前面看 Scoop 本身装好了，也可以安装一般的包了。

`scoop update` 出错是访问 Scoop 的软件包数据出错，还是网络的问题，这一步是安装 Python 3.7 需要的，所以建议你多试几次，你的网络可能时好时坏；也可以换网或者挂代理试试。
