### ISSUE TITLE
异常处理中的例子多次尝试不能得到书中结果，在 juptyer 中运行正常

### ISSUE THREAD

**Issue by myhappylife2002** [neolee/pilot#314]
![1](https://user-images.githubusercontent.com/57083738/68069955-7a4e6c80-fda2-11e9-9c56-4bb54c62becc.png)
![2](https://user-images.githubusercontent.com/57083738/68069957-7c183000-fda2-11e9-84a8-eee6c2311c7a.png)
![3](https://user-images.githubusercontent.com/57083738/68069958-7e7a8a00-fda2-11e9-89ee-b40daaa6487b.png)

**Comment by neolee** [comment]
`print('Your number is:', x)` 那一行的缩进错了，应该顶格，它在 while 循环的外面。

另外猜测由于你多次运行，x 已经带了前面得到的值，所以在输错的时候仍然打印出 67 这个数字。

在 Jupyter Lab 外运行这样的代码，最好用 Visual Studio Code 将其完整保存为一个 xxx.py 的文件，然后用 `python xxx.py` 来运行，这样环境比较干净。

**Comment by myhappylife2002** [comment]
![1](https://user-images.githubusercontent.com/57083738/68070730-036aa100-fdad-11e9-9bd7-79bac00c84ed.png)
还是不可以；不知为何ValueError:中的:下有一个波浪线

**Comment by myhappylife2002** [comment]
line5中:下的波浪线应该就是问题所在

**Comment by myhappylife2002** [comment]
找到问题所在了，应该是缩进多了一位
