### ISSUE TITLE
关于 git 的问题

### ISSUE THREAD

**Issue by ahui9** [neolee/pilot#315]
git是安装成功了没怎么还写不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by ahui9** [comment]
![360截图20191102192839461](https://user-images.githubusercontent.com/57027624/68070281-8983e900-fda7-11e9-8083-ccde9faeb6ac.jpg)

**Comment by neolee** [comment]
可能需要重新启动命令行界面试试，有的环境下需要重启 Windows。

**Comment by ahui9** [comment]
还是这样
![360截图20191102194624613](https://user-images.githubusercontent.com/57027624/68070461-8db10600-fda9-11e9-90cd-f7dfb51620ad.jpg)

**Comment by neolee** [comment]
你执行 `git --version` 可有结果？

如果这个也找不到 git，那就是之前没装好，建议删除 Scoop 完整地重装一遍，参见 Wiki 中“重新安装 Scoop”的说明。

**Comment by ahui9** [comment]
git --version可以找到，但是scoop update还是
![360截图20191103100342195](https://user-images.githubusercontent.com/57027624/68079223-89283400-fe21-11e9-818a-f62d961d2d6d.jpg)
'git' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by ahui9** [comment]
老师除了git其它都能在ConEmu执行,还用重新下载scoop吗？
![360截图20191103103809780](https://user-images.githubusercontent.com/57027624/68079562-8da31b80-fe26-11e9-8ee2-f25b3e0a3919.jpg)

**Comment by neolee** [comment]
通过搜索我找到了这个页面： https://github.com/lukesampson/scoop/issues/2252

这个人通过重新安装 git 解决了问题： `scoop uninstall git` 和 `scoop install git` 

你可以试试。另外，问之前先搜索下我们的 issue 以及整个互联网，通常会有帮助。

**Comment by ahui9** [comment]
好的 谢谢！
