### ISSUE TITLE
git-version2.23更新命令git restore而文档x3-git-github.ipynb描述为git checkout

### ISSUE THREAD

**Issue by spring-ap** [neolee/pilot#316]
![image](https://user-images.githubusercontent.com/57279823/68070368-36f6fc80-fda8-11e9-80ef-482e93b3ab38.png)

![image](https://user-images.githubusercontent.com/57279823/68070375-49713600-fda8-11e9-95f7-a51591dc1de2.png)

**Comment by spring-ap** [comment]
已修改

**Comment by neolee** [comment]
这个是已知问题，今天已经更新过了，多谢指出。
