### ISSUE TITLE
执行 git commit 没有弹出 vscode

### ISSUE THREAD

**Issue by qiaoshuai18** [neolee/pilot#317]
请问怎么设置呢？

**Comment by neolee** [comment]
你执行 `git commit` 的表现是？

之前有执行过教程里给出的几个 `git config` 命令吗？

**Comment by qiaoshuai18** [comment]
![image](https://user-images.githubusercontent.com/57203396/68071890-55fe8a00-fdba-11e9-82f8-976093f5d669.png)

**Comment by qiaoshuai18** [comment]
执行过了

**Comment by qiaoshuai18** [comment]
![image](https://user-images.githubusercontent.com/57203396/68071918-9f4ed980-fdba-11e9-8ae9-9d3e3769434d.png)

**Comment by neolee** [comment]
你配错了，应该是 `git config --global core.editor="code -w"`。

仔细看，你配成了 `user.editor`，应该是 `core.editor`。
