### ISSUE TITLE
学习用书中，执行代码时碰到问题：Control+回车 执行时没有反应。

### ISSUE THREAD

**Issue by xiaoerhai** [neolee/pilot#318]
正常操作：
Control+回车 执行
Alt+回车 执行并在下方新开一个代码 cell（这里新开的代码cell怎么删除？）

但我今天碰到2个次都没法执行，特征是：
最左边的方括号[]里变成了星号*，而不是一般执行时的数字。

**Comment by neolee** [comment]
Duplicate of #301
