### ISSUE TITLE
如何在提交 issue 时配上对应的图片？

### ISSUE THREAD

**Issue by xiaoerhai** [neolee/pilot#319]
1）找了好几次都没看到上传图片的入口；
2）如果直接截图复制粘贴的话总是失败，进入死循环：点击‘try again’→上传图片→失败，点击‘try again’。

**Comment by spring-ap** [comment]
我就是直接粘贴过来的，会提示上传，等传完后，会显示提示文字提交后才能看到图片。

**Comment by neolee** [comment]
Wiki 里有说明。
