### ISSUE TITLE
下载不了jupyterlab

### ISSUE THREAD

**Issue by echo20190807** [neolee/pilot#321]
当输入 pip install jupyterlab，刚开始有下载，但到了
Collecting notebook>=4.3.1 (from jupyterlab)                                    
  Downloading https://files.pythonhosted.org/packages/f3/a1/1e07cedcb554408fefe4
a7d32b2a041c86517167aec6ca8251c808ef6c1e/notebook-6.0.1-py3-none-any.whl (9.0MB)
                                                                                
    4% |█▌                              | 440kB 178kB/s eta 0:00:49Exception:   
Traceback (most recent call last):                                              
  File "c:\users\echo\scoop\apps\python37\3.7.4\lib\site-packages\pip\_vendor\ur
llib3\response.py", line 360, in _error_catcher                                 
    yield                                                                       
  File "c:\users\echo\scoop\apps\python37\3.7.4\lib\site-packages\pip\_vendor\ur
llib3\response.py", line 442, in read                                           
    data = self._fp.read(amt)                                                   
  File "c:\users\echo\scoop\apps\python37\3.7.4\lib\site-packages\pip\_vendor\ca
checontrol\filewrapper.py", line 62, in read                                    
    data = self.__fp.read(amt)                                                  
  File "c:\users\echo\scoop\apps\python37\3.7.4\lib\http\client.py", line 457, i
n read                                                                          
内容还有一些没有复制下来
最后出现以下的提示
You are using pip version 19.0.3, however version 19.3.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
请问是需要更新吗？在哪里输入更新命令？谢谢

**Comment by neolee** [comment]
这问题已经出现过无数个 issue 了，可以搜索一下。

你碰到的是网络问题，过一会儿再试试吧，或者换网络或挂代理。

升级 pip 本身不是必须，但是推荐升以下 `python -m pip install --upgrade pip`。
