### ISSUE TITLE
jupyterlab 安装 toc 需要额外安装其他软件

### ISSUE THREAD

**Issue by delakeming120** [neolee/pilot#323]
PS C:\Users\Administrator\Code\pilot-student> jupyter labextension install @jupyterlab/toc
An error occured.
ValueError: Please install nodejs 5+ and npm before continuing installation. nodejs may be installed using conda or directly from the nodejs website.
See the log file for details:  C:\Users\ADMINI~1\AppData\Local\Temp\jupyterlab-debug-oi2n3k_d.log

**Comment by neolee** [comment]
需要先装个 nodejs，原视频已经更新了说明。

在 Windows 下先执行 `scoop install nodejs`。

p.s. 这个插件不是必须的。
