### ISSUE TITLE
输入“import math math.spart(16)”，运行后报错

### ISSUE THREAD

**Issue by long2017freedom** [neolee/pilot#324]
输入“import math math.spart(16)”，运行后报错为： 

AttributeError                            Traceback (most recent call last)
<ipython-input-107-99af9d98a052> in <module>
      1 import math
----> 2 math.spart(16)

AttributeError: module 'math' has no attribute 'spart'

请问怎么解决，谢谢

**Comment by neolee** [comment]
这代码哪儿来的？你确定没有写错什么吗？
