### ISSUE TITLE
运行 Scoop 的安装命令时，网络不行

### ISSUE THREAD

**Issue by 111xiaochao111** [neolee/pilot#326]
PS C:\Users\a> Get-ExecutionPolicy
RemoteSigned
PS C:\Users\a> iwr -useb get.scoop.sh | iex
iwr : 无法连接到远程服务器
所在位置 行:1 字符: 1
+ iwr -useb get.scoop.sh | iex
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:H
   ttpWebRequest) [Invoke-WebRequest]，WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerS
   hell.Commands.InvokeWebRequestCommand

已进行一下操作：
1、更换网络，结果不行
 2,、尝试挂代理（或者说是科学上网），多次更换软件最后在 智游代理上找到一些IP地址，接着进行如下操作：打开网络和共享中心”--“Internet选项--“连接”--“局域网设置”--为LAN使用代理服务器”选--输入代理IP地址，端口后输入代理IP的端口--点击“确定”。
再回头运行Scoop 的安装命令，结果依然提示“ 无法连接到远程服务器”
哪位朋友碰见这类问题，你是如何解决的，烦请留言告知，谢谢
我的微信号：zc8939

**Comment by fpeace168** [comment]
我也是遇到这个问题，卡在这里了。

**Comment by neolee** [comment]
确定是网络问题的，不必在这里提问，通过其他方式想办法解决。

**Comment by fpeace168** [comment]
好的，明白了，谢谢李老师指点。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Neo Lee"<notifications@github.com&gt;; 
发送时间: 2019年11月3日(星期天) 中午12:43
收件人: "neolee/pilot"<pilot@noreply.github.com&gt;; 
抄送: "维和"<58391834@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [neolee/pilot] 运行 Scoop 的安装命令时，网络不行 (#326)




确定是网络问题的，不必在这里提问，通过其他方式想办法解决。
