### ISSUE TITLE
brew doctor warnings

### ISSUE THREAD

**Issue by Gaomingzhao** [neolee/pilot#327]
这个要看具体问题，你这里这几个，第一个和最后一个都比较不好，需要解决，中间一个不好说。

第一个是你安装 Anaconda 来的，很可能和你用 Homebrew 安装的 Python 冲突，最好按照 Anaconda 的官方指南先完整删掉。

第三个是说你 Homebrew 安装的 Python 没有 link 好（link 这个操作比较复杂几句话说不清），建议你运行 `brew link python`，你最好在彻底删掉 Anaconda 之后再执行这个命令。

第二个是说 /usr/local/lib 下面有几个 Homebrew 不认识的运行库，估计你也不知道什么时候装的以及干啥用吧？保险起见，我建议你的找个目录把它们 mv 过去，看看是不是影响你机器运行，不影响就搁在那儿：

```shell
mkdir ~/Backup
mv /usr/local/lib/libnnz11.dylib /usr/local/lib/libociei.dylib /usr/local/lib/libocijdbc11.dylib ~/Backup/
```

_Originally posted by @neolee in https://github.com/neolee/pilot/issues/212#issuecomment-547479126_

----------
根据上述提示操作后，

最好按照 Anaconda 的官方指南先完整删掉。—— Anaconda 目前貌似删掉了，但操作过程中，删除了大量其他文件...... 好吧这个暂时先不管。

目前，仍然有 warning 提示，具体是：

![image](https://user-images.githubusercontent.com/24623343/68080249-91d53600-fe32-11e9-8a90-f29206829719.png)

红框里的内容已经减少了，但没有完全删掉.....

下面一个warning，暂时还没操作，因为是说需要先解决上面一个问题。

**Comment by neolee** [comment]
你可以继续在那个 issue 里继续讨论，不需要另开；你可以 Reopen 那个 issue，如果你觉得需要。不过这次就算了，在这里继续吧，这样的坏处是，同一个人的同一个问题，分开了两处，对照看起来比较麻烦。

回到你的问题：
1. `brew doctor` 的输出不是一定有问题，如果你其他操作没遇到问题，其实可以不管它。

2. 我觉得你可以把 `/Library/Frameworks/Python.framework` 这个目录完全移除（mv 到你的备份目录下）。

3. 你的 `/usr/local/bin` 下面遗留了一组 Python 的可执行文件，一般情况下是这些（如果部分文件你那里没有也没关系）：
<img width="831" alt="Python Links" src="https://user-images.githubusercontent.com/24796/68080411-da422300-fe35-11e9-92a9-97d78e7957bd.png">

建议你把这些文件也都移除（mv 到你的备份目录）。

然后可以尝试安装 Python 了 `brew install python`。

**Comment by Gaomingzhao** [comment]
谢谢，已操作完成
