### ISSUE TITLE
 运行 code .\hello.py 错误

### ISSUE THREAD

**Issue by tianan66** [neolee/pilot#328]
![批注 2019-11-03 121839](https://user-images.githubusercontent.com/56901820/68080363-09a46000-fe35-11e9-8d4f-4b38515ea111.png)

**Comment by neolee** [comment]
不认识 code 这个命令，要么是你没有安装好 Visual Studio Code，要么你需要重启下命令行界面或者重启下 Windows。

**Comment by qingyix** [comment]
配置最后一步python hello.py 不是直接出hello world！
![hello](https://user-images.githubusercontent.com/48583363/68281634-11713800-00b3-11ea-83aa-71cb31cd7307.png)

**Comment by neolee** [comment]
@qingyix 不要在别人的 issue 下面问不相关的问题。另外你的问题是这个括号不对，用了中文括号。

**Comment by tianan66** [comment]
已解决

**Comment by qingyix** [comment]
下回会注意的，小白问题已通过。谢谢！
