### ISSUE TITLE
运行 jupiter lab 时跳出警告然后所有页面的代码都无法运行了

### ISSUE THREAD

**Issue by lidewen-yue** [neolee/pilot#329]
一开始的时候跳出这个警告

然后右上角标红的地方变成了no kernel！
<img width="1082" alt="image" src="https://user-images.githubusercontent.com/56989072/68080588-cbf60600-fe39-11e9-91be-d6027878891d.png">

今天早些时候出现过一次，当时是通过关掉网页重开解决的，但是我想知道具体是什么原因造成的，避免下次在误操作。麻烦老师指教。

**Comment by neolee** [comment]
跳出了什么警告？

No kernel 就是 notebook 背后的那个 Python 解释器没跑起来。这时候运行 jupyter lab 的命令行窗口里有什么显示？

**Comment by lidewen-yue** [comment]
这就是警告的图片

![image](https://user-images.githubusercontent.com/56989072/68080765-acaca800-fe3c-11e9-9b1b-1f6feae2419a.png)


命令行的图片状态是这样的


<img width="1438" alt="image" src="https://user-images.githubusercontent.com/56989072/68080758-94d52400-fe3c-11e9-964a-d646695cb20f.png">

![image](https://user-images.githubusercontent.com/56989072/68080761-9d2d5f00-fe3c-11e9-960e-3095eecf7dbc.png)

**Comment by neolee** [comment]
尝试执行 `ulimit -n` 和 `ulimit -u`，这两个命令返回的数，是系统允许最多打开的文件数，前一个是总数，后一个是单个进程（你可以理解为单一程序）能打开的。

很可能你的系统里这两个数里至少有一个太小了（这是最新版本 macOS 的一个已知的问题），你需要提高这个设置，方法比较复杂，我简单写在下面，你可以参考。

在 `/Library/LaunchDaemons/` 目录下创建两个文件 `limit.maxfiles.plist` `limit.maxproc.plist`，内容分别如下（里面的数值可以修改，不太过分就行）：

limit.maxfiles.plist:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
          "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>Label</key>
    <string>limit.maxfiles</string>
    <key>ProgramArguments</key>
    <array>
      <string>launchctl</string>
      <string>limit</string>
      <string>maxfiles</string>
      <string>200000</string>
      <string>200000</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>ServiceIPC</key>
    <false/>
  </dict>
</plist>
```

limit.maxproc.plist:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple/DTD PLIST 1.0//EN"
          "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>Label</key>
      <string>limit.maxproc</string>
    <key>ProgramArguments</key>
      <array>
        <string>launchctl</string>
        <string>limit</string>
        <string>maxproc</string>
        <string>2048</string>
        <string>2048</string>
      </array>
    <key>RunAtLoad</key>
      <true />
    <key>ServiceIPC</key>
      <false />
  </dict>
</plist>
```

然后确认这两个文件的 owner 为系统 root 账号：

```shell
sudo chown root:wheel /Library/LaunchDaemons/limit.maxfiles.plist
sudo chown root:wheel /Library/LaunchDaemons/limit.maxproc.plist
```

最后重启令之生效。

**注意**：这个过程中可能遇到的问题是碰到系统文件保护（SIP）禁止你创建那俩文件，这时候你需要先禁用系统文件保护（SIP），具体操作可以参考[这篇文章](https://www.imore.com/how-turn-system-integrity-protection-macos)。
