### ISSUE TITLE
关于 Scoop 安装的疑难杂症

### ISSUE THREAD

**Issue by xbq1022** [neolee/pilot#33]
老师好。
scoop之前已经成功安装，并安装好了3个软件，但是进入到第二课，准备复制自己页面的链接，运行git clone 链接 时显示出错。
截图如下：
  
![1](https://user-images.githubusercontent.com/56924543/67401544-e0d4cd00-f5e1-11e9-98c2-96c3f0c269db.png)
![image](https://user-images.githubusercontent.com/56924543/67401652-0cf04e00-f5e2-11e9-8b49-79e6da9b14f1.png)
感谢！

**Comment by xbq1022** [comment]
图一为后面出错后，我返回查看scoop 安装的情况，显示已经安装，但是运行“scoop upddate”出错，是哪里没做对呢？

**Comment by BraveheartHu** [comment]
先执行scoop checkup，然后再执行scoop update，试下。

**Comment by BraveheartHu** [comment]
还是不行，你可以看看第30个问题，里面有老师讲解重新安装 Scoop的步骤。
https://github.com/neolee/pilot/issues/30

**Comment by neolee** [comment]
这里显示 scoop 已安装，但是似乎并没有装好，试试上面 @BraveheartHu 的建议先。

**Comment by xbq1022** [comment]
> 还是不行，你可以看看第30个问题，里面有老师讲解重新安装 Scoop的步骤。
> #30

按#30问题操作了，仍然出错。
![image](https://user-images.githubusercontent.com/56924543/67407499-2b5a4780-f5ea-11e9-8d0b-9fabdb6b2d4e.png)

**Comment by xbq1022** [comment]
![2](https://user-images.githubusercontent.com/56924543/67407554-41680800-f5ea-11e9-9172-5ff153cbf88e.png)

**Comment by neolee** [comment]
请检查一下 C:\Users\house\scoop\shims 这个目录是否存在，下面是否有 scoop 为名字的几个文件；

然后在命令行运行 `$env:Path` 把结果给我看下。

**Comment by xbq1022** [comment]
shims 文件存在，有3个文件。
![image](https://user-images.githubusercontent.com/56924543/67409740-8fcad600-f5ed-11e9-9fa9-94d0890bebe8.png)
我将ConEmu安装到D盘，有影响么？
![image](https://user-images.githubusercontent.com/56924543/67409843-b4bf4900-f5ed-11e9-8a4d-316e1724d799.png)

**Comment by neolee** [comment]
遇到这个问题的同学，首先完全清除已经安装的 Scoop（由于某种原因，安装没有完成，但是留下了垃圾）：

```shell
cd
del .\scoop -Force
```

然后尝试重新安装 Scoop：

```shell
Set-ExecutionPolicy RemoteSigned -scope CurrentUser
iwr -useb get.scoop.sh | iex
```

把这个过程的截图发上来。

然后按照前一条说的，确认两件事，把结果也发过来：

1. 检查 C:\Users\<你的用户名>\scoop\shims 这个目录是否存在，下面是否有 scoop 为名字的几个文件；
2. 在命令行运行 `$env:Path` 把结果发过来。

**Comment by dongjin936** [comment]
![微信图片_20191023233537](https://user-images.githubusercontent.com/56923938/67409921-d91b2580-f5ed-11e9-8a92-91821ef22655.jpg)

**Comment by dongjin936** [comment]
重新开始，先是遇到这个问题。

**Comment by neolee** [comment]
@xbq1022 你的 Path 中没有 C:\Users<你的用户名>\scoop\shims 这个目录，所以找不到 scoop 了。你需要依序打开：控制面板 -> 系统与安全 -> 系统 -> 高级系统设置 -> 环境变量，然后双击编辑 Path 这个变量，把 C:\Users\house\scoop\shims 这个路径加进去。

然后再试试 `scoop update` 看。

**Comment by dongjin936** [comment]
![Uploading 00841264ba00c87b4ff9f96d9217636.jpg…]()
![Uploading 912c1d85346b6680371e308a547228b.jpg…]()
![Uploading dca06118ef55abfd485a642965d4f17.jpg…]()

**Comment by dongjin936** [comment]
![dca06118ef55abfd485a642965d4f17](https://user-images.githubusercontent.com/56923938/67410771-2e0b6b80-f5ef-11e9-8de8-a05daa5669e1.jpg)

**Comment by xbq1022** [comment]
@neolee 原有这个路径。
![image](https://user-images.githubusercontent.com/56924543/67410781-32d01f80-f5ef-11e9-893a-18e1a3463f95.png)

**Comment by dongjin936** [comment]
![00841264ba00c87b4ff9f96d9217636](https://user-images.githubusercontent.com/56923938/67410787-35327980-f5ef-11e9-9a7d-6ca5344f96aa.jpg)

**Comment by dongjin936** [comment]
![912c1d85346b6680371e308a547228b](https://user-images.githubusercontent.com/56923938/67410800-3bc0f100-f5ef-11e9-93fd-032c6271a0c4.jpg)

**Comment by dongjin936** [comment]
![4d931852712a91b481f22cbaaa83e97](https://user-images.githubusercontent.com/56923938/67410831-41b6d200-f5ef-11e9-8c86-e772d5515713.jpg)

**Comment by dongjin936** [comment]
明天我再换笔记本电脑试试看，李老师您也早休息。谢谢您费心指导我们。

**Comment by neolee** [comment]
@xbq1022 从你这里看有几个问题比较“可疑”：

1. 你的 `$env:Path` 里面没有 C:\Users\house\scoop\shims，你后面截图出来的那些目录是哪里来的呢？
2. 你的 `$env:Path` 里面有一个 WindowsPowerShell\v1.0 ，这是很古老的一个版本的 PowerShell，你确定目前运行的是 PowerShell 5 以上的版本吗？

问题可能就在这几个点，但是怎么解决，还没有头绪，需要继续摸一下……

**Comment by neolee** [comment]
@dongjin936 你目前的问题已经和 @xbq1022 非常类似了，简单说，就是这个逻辑：

1. Scoop 如果安装好了，就在 `C:\Users\<你的用户名>\scoop\shims` 下面有几个 scoop.* 的文件，运行 `scoop` 命令就靠这几个文件；
2. `#env:Path` 里面的目录，是 PowerShell 能找到的可运行文件的地方，上述目录必须在里面才行。

现在你们的问题是一样的，就是 scoop 程序存在，但是 PowerShell 找不到它，因为`#env:Path` 里面没有 `C:\Users\<你的用户名>\scoop\shims` 这个目录（还有其他一些目录也缺失）。

**Comment by xbq1022** [comment]
@neolee @BraveheartHu @dongjin936 
按老师的方法全部测试一遍，是否有缺失。我试过后文件都是完整的，无奈之下，尝试了重启，重新运行 scoop update，出现以下提示，应该是可以了，可以尝试下重启......
@neolee 老师辛苦了！
![image](https://user-images.githubusercontent.com/56924543/67412600-2bf6dc00-f5f2-11e9-8414-1fe865632378.png)
![image](https://user-images.githubusercontent.com/56924543/67412618-30bb9000-f5f2-11e9-81d1-b7a201a4f68e.png)

**Comment by dongjin936** [comment]
好的，明天我再按照李老师和xbq1022说的试一下，谢谢🙏

**Comment by neolee** [comment]
居然要重启的么……这算个新 tips……其他有类似问题的也可以试试。我把具体操作再整理一次写在下面供参考。

### 运行 `scoop update` 时遇到红字错误 `Scoop uses Git to update itself...`

解决方案：按照提示，运行 `scoop install git`，成功后再 `scoop update`。

### 安装 Scoop 或者运行任何 `scoop` 命令都遇到红字错误 `无法将 scoop 识别为 cmdlet、函数、脚本文件...` 

解决方案：首先删除已经安装但坏掉的 Scoop：
```shell
cd
del .\scoop -Force
```
然后重新安装 Scoop：
```shell
Set-ExecutionPolicy RemoteSigned -scope CurrentUser
iwr -useb get.scoop.sh | iex
```
如果还有错误，确认：
* `C:\Users\<你的用户名>\scoop\shims` 目录下面有几个 `scoop.*` 的文件；
* 在命令行输入 `$env:Path` 并确认输出中包含 `C:\Users\<你的用户名>\scoop\shims` 目录；
* 依序打开：控制面板 -> 系统与安全 -> 系统 -> 高级系统设置 -> 环境变量，然后双击编辑 Path 这个变量，确认 `C:\Users\<你的用户名>\scoop\shims` 这个目录在里面（没有就加进去）。

再次尝试 `scoop update`，如果还不行，重启试试。

### `scoop` 命令可以运行（没有前一个错误）但有其他错误

解决方案：运行 `scoop checkup` 并按照提示操作，通常是下面两行命令：

```shell
Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1
scoop install innounp
```

**Comment by xbq1022** [comment]
> @xbq1022 从你这里看有几个问题比较“可疑”：
> 
> 1. 你的 `$env:Path` 里面没有 C:\Users\house\scoop\shims，你后面截图出来的那些目录是哪里来的呢？
> 2. 你的 `$env:Path` 里面有一个 WindowsPowerShell\v1.0 ，这是很古老的一个版本的 PowerShell，你确定目前运行的是 PowerShell 5 以上的版本吗？
> 
> 问题可能就在这几个点，但是怎么解决，还没有头绪，需要继续摸一下……

回答1，就是按老师给的路径找到的，在原path设置里面有这个路径。
2，可能是以前安装的程序残留。

重启后，问题解决了，后面需要重新安装3个软件。感谢老师的指导，晚安。

**Comment by soulpanda1985** [comment]
![image](https://user-images.githubusercontent.com/48625427/67445200-9b92b880-f63e-11e9-82f3-186fc7006ebb.png)
老师，遇到这样的问题怎么解决？

**Comment by neolee** [comment]
@soulpanda1985 网络问题，多试试或者尝试代理

**Comment by Vincent-box** [comment]
> @xbq1022 从你这里看有几个问题比较“可疑”：
> 2. 你的 `$env:Path` 里面有一个 WindowsPowerShell\v1.0 ，这是很古老的一个版本的 PowerShell，你确定目前运行的是 PowerShell 5 以上的版本吗？
> 
> 问题可能就在这几个点，但是怎么解决，还没有头绪，需要继续摸一下……

我也是有 WindowsPowerShell\v1.0 ，請問要如何才能運行 PowerShell 5 以上的版本?

**Comment by neolee** [comment]
@Vincent-box 在你的命令行界面执行 $PSVersionTable.PSVersion.Major 给出的数字大于等于 5 就可以了。否则需要按照 [配置指南](https://github.com/neolee/pilot/blob/master/x1-setup.md) 的说明安装。

**Comment by zouwenxi** [comment]
运行“scoop upddate”出错，是哪里没做对呢？按照老师上面教的方法了试过了，还是显示 scoop update failed

**Comment by neolee** [comment]
@zouwenxi 另开 issue，把出错的截图出来。

**Comment by HNUrookie1** [comment]
image
Please ask why this is?It's is diffuculity.Thank you!
