### ISSUE TITLE
python 版本问题

### ISSUE THREAD

**Issue by Gaomingzhao** [neolee/pilot#331]
![image](https://user-images.githubusercontent.com/24623343/68081148-285e2300-fe44-11e9-94a5-4d3aa9fa533e.png)

已经用 homebrew 更新 python 版本到 3.7.5，但用 python -V，检查出来的版本是 2.7.10，可能是之前安装的。

另外还有此类报错，不知道是否是跟 python 版本问题有关。
192:~ zhaogaoming$ python -m pip install --upgrade pip
/usr/bin/python: No module named pip

**Comment by neolee** [comment]
你的系统中需要使用 python3 和 pip3，因为 python 指向的是 Python 2.7 的老版本。

所以尝试：`python3 -m pip install -U pip` 然后 `pip3 install jupyterlab`。

**Comment by Gaomingzhao** [comment]
的确，按照指导内容操作已经搞定啦，我之前尝试过把 pip 改成 pip3 ，没想到 python 这边也要改。谢谢老师

**Comment by zhuwenmiao** [comment]
<img width="1440" alt="截屏2019-11-04下午8 22 19" src="https://user-images.githubusercontent.com/31498197/68122159-aefa2980-ff44-11e9-99e3-b64e3c6fd659.png">
按照上面的指示，后面在安装jupyterlab的时候不知道为什么版本还是对应系统自带的python，新安装的python版本是python3.7.5，安装的时候应该怎么样对应新版本的python3.7.5，谢谢李老师
