### ISSUE TITLE
运行 pip install jupyterlab 命令出现 Could not find a version that satisfies the requirement decorator 错误

### ISSUE THREAD

**Issue by zhigang-he** [neolee/pilot#332]
输入命令情况：
![图片](https://user-images.githubusercontent.com/49590371/68081247-e3d38700-fe45-11e9-9429-9afc8792cdd6.png)

错误代码请参见下图：
![图片](https://user-images.githubusercontent.com/49590371/68081211-5a23b980-fe45-11e9-80ef-acba8339a0a6.png)
win10 64位系统，之前未安装过python。

**Comment by neolee** [comment]
环境 OK 的，可能是网络问题，重新尝试 `pip install jupyterlab`。

**Comment by zhigang-he** [comment]
的确是网络问题，通过代理连接网络之后安装完成。谢谢！
