### ISSUE TITLE
jupyter lab 这一步没法往下进行？

### ISSUE THREAD

**Issue by hermanxie** [neolee/pilot#336]
jupyter lab这一步没法往下进行？好像没有安装完成
![image](https://user-images.githubusercontent.com/48776732/68083335-6cf8b700-fe62-11e9-991c-2c480cd00e96.png)
![image](https://user-images.githubusercontent.com/48776732/68083340-7eda5a00-fe62-11e9-9717-20777cb345d2.png)

**Comment by hermanxie** [comment]
> jupyter lab这一步没法往下进行？

PS C:\Users\zs\code\pilot-student> pip install jupyerlab
Collecting jupyerlab
  ERROR: Could not find a version that satisfies the requirement jupyerlab (from versions: none)
ERROR: No matching distribution found for jupyerlab
WARNING: You are using pip version 19.2.3, however version 19.3.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
PS C:\Users\zs\code\pilot-student> jupyter lab
jupyter : 无法将“jupyter”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确
保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ jupyter lab
+ ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (jupyter:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\zs\code\pilot-student> jupyter lab
jupyter : 无法将“jupyter”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确
保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ jupyter lab
+ ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (jupyter:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\zs\code\pilot-student>

**Comment by hermanxie** [comment]
![question1](https://user-images.githubusercontent.com/48776732/68083170-c19b3280-fe60-11e9-8422-e869a6071389.png)

**Comment by neolee** [comment]
你安装 jupyterlab 那一步出错了呀，那么多红字不看看么？

安装失败的原因，因为没有完整的信息，无法判断。

**Comment by hermanxie** [comment]
OK了，谢谢老师

**Comment by Haibagu** [comment]
你好，我碰到同样的问题，想请教一下最后怎么解决的。
尝试过的方案，
1，下载并尝试安装 MICROSOFT VISUAL  C++ REDISTRIBUTABLE（x64）- 14.0.23026，结果显示已安装过改软件或其他版本。
2，下载并完成安装 Microsoft Visual C++ Build Tools，在ConEmu中 尝试安装 jupyter lab，还是报错，限制同样的问题
附，已升级号好pip
附图
![image](https://user-images.githubusercontent.com/48606700/68386658-656a4280-01c1-11ea-8ad3-df8beaed9f96.png)
麻烦了

**Comment by neolee** [comment]
从出错信息来看就是需要安装 Microsoft Visual C++ Build Tools，不知道有没有具体版本要求，我没碰到这问题，所以不太好判断。

**Comment by Haibagu** [comment]
老师你回复真快，我查了别的同学的issue，结论是我安装了python3.8，然后我按照你的回复重装了python，结果装了个python3.7.5，最后是成功安装了jupyter lab， 但是在最后有warning 说没安装在PATH 上。我截图给你看看
![image](https://user-images.githubusercontent.com/48606700/68388724-28ed1580-01c6-11ea-95f7-d79d1d3fdcbd.png)
下图是我的环境设置
![image](https://user-images.githubusercontent.com/48606700/68389292-76b64d80-01c7-11ea-95c3-673ab70714e3.png)
还有一个问题是我试图运行 
Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1
但是返回的结果如下图
![image](https://user-images.githubusercontent.com/48606700/68389403-b846f880-01c7-11ea-8f7d-6a701d49f7a3.png)
谢谢老师

**Comment by neolee** [comment]
第一张截图，这个不应该，因为它说的那个目录应该在 PATH 里才对，你可以手动加进去。

第二张，你按照它说的一个个做就可以了，大致是：
```powershell
Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1
scoop install sudo
sudo Add-MpPreference -ExclusionPath 'C:\Users\woqul\scoop'
sudo Add-MpPreference -ExclusionPath 'C:\ProgramData\scoop'
```

第三张，权限问题，可以试试打开一个管理员权限的命令行界面（{{ PowerShell (Admin) }}）运行。
