### ISSUE TITLE
scoop 的安装命令运行有误

### ISSUE THREAD

**Issue by V-git3** [neolee/pilot#338]
![报错](https://user-images.githubusercontent.com/57316065/68084363-881df380-fe6f-11e9-92e2-47d7dfdc8b51.JPG)

**Comment by neolee** [comment]
已有几个类似的 issue，比如——

Duplicate of #73

**Comment by V-git3** [comment]
> 
> 
> 已有几个类似的 issue，比如——
> 
> Duplicate of #73

与#73情况不同，虽然我的返回也是2，但我是按照配置指南安装了支持软件的。

**Comment by neolee** [comment]
安装了那两个软件还是 2？这不可能吧……

**Comment by V-git3** [comment]
> 安装了那两个软件还是 2？这不可能吧……

是的，当时我这边安装了再测试了一下还是2也觉得纳闷？下班后我回去再去试一下再说嘛，先谢谢李老师及时回复🙂

**Comment by V-git3** [comment]
> > 安装了那两个软件还是 2？这不可能吧……
> 
> 是的，当时我这边安装了再测试了一下还是2也觉得纳闷？下班后我回去再去试一下再说嘛，先谢谢李老师及时回复

李老师，我知道原因了，是我下载了，但是似乎忘记点安装了，是说昨天安装后没有提示需要重新启动计算机😂。但又有新的问题，无法连接到远程服务器😓，我先去找找有没类似的issue再说🙂

**Comment by neolee** [comment]
"无法连接到远程服务器"是网络问题，需要换网络或者挂代理试试。
