### ISSUE TITLE
终端输入 jupyter lab 无法运行

### ISSUE THREAD

**Issue by wuzhi7** [neolee/pilot#341]
1. 上一次jupyter lab可以运行完好，但电脑关机后再次在终端输入jupyter lab，出现以下代码
![Snip20191103_1](https://user-images.githubusercontent.com/25902261/68085669-65470b80-fe7e-11e9-8ab5-c1fcdd6d227f.png)

2. 分析问题：
在最开始安装jupyter lab不成功，出现以下错误提示：
`ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Permission denied: '/usr/local/share/jupyter/kernels/python3' Consider using the `--user` option or check the permissions.`

在网上找解决办法，如下：
```
python3 -m venv env
source ./env/bin/activate
python -m pip install jupyterlab
```
安装并运行jupyter lab成功，问题解决

3. 这次解决办法：
再次在终端输入
```
python3 -m venv env
source ./env/bin/activate
python -m pip install jupyterlab
```
安装并运行jupyter lab成功

4. 希望得到帮助
如果每次开机，都得运行一遍如下代码，太繁琐，希望老师能给出更好的解决办法
```
python3 -m venv env
source ./env/bin/activate
python -m pip install jupyterlab
```

**Comment by neolee** [comment]
你提供的信息有限，我猜测你应该是 macOS 系统，大致情况如下：

1. 第一张截图里的问题说找不到 jupyter-lab 这个命令，这个一般是 Jupyter Lab 没有装好；

2. 第二张截图尝试安装 Jupyter Lab 失败，说的是 `/usr/local/share` 下没有写的权限；一般来说 `/usr/local/` 下面的大部分子目录，包括 `/usr/local/bin` `/usr/local/share` 等，都是你的登录账户有完整权限的（假定你的登录账户是 Admin 类型），如果没有是很不方便的，你可以通过类似 `sudo chown -R liyangbin /usr/local/share` 这样的命令来解决；

3. 你在网上找到的这个解决方案，应该说不是个好方案，因为：
* 它回避了问题的本质，走了一条别的路线，虽然能解决问题，但你就失去了深入理解前面问题的机会；
* 这个方案是让你在自己用户目录下配置一个 Python 的虚拟环境，这个方法是 Python 老手经常用的，但对于新手来说，有点不必要的复杂。

4. 在你执行了 你的第3点 中描述的命令后，以后并不需要每次都执行，你只要在执行 `jupyter lab` 之前激活你已经配置好的虚拟环境就行了，方法是运行 `source ~/env/bin/activate`——这里我假定你的虚拟环境配置在 `~/env` 下面，因为我不知道你之前是在哪里运行的 `python3 -m venv env`；

5. 如果你希望每次进入命令行自动进入这个虚拟环境，把 `source ~/env/bin/activate` 这句加到你的 shell 的初始配置文件里就行了：如果你的 shell 是 Bash 那么就是 `~/.bash_profile`，如果你的 shell 是 zsh 那么就是 `~/.zshrc`。

**Comment by zhuwenmiao** [comment]
<img width="1440" alt="截屏2019-11-04下午8 22 19" src="https://user-images.githubusercontent.com/31498197/68120713-03030f00-ff41-11e9-81d0-3c366a9dfd91.png">
将 python改成python3后前一个命令可以执行，后面输入pip3 install jupyterlab后还是用了系统自带的版本，这个原因不知道在那里？辛苦李老师

**Comment by neolee** [comment]
@zhuwenmiao 不要在别人的 issue 下问不同的问题，请另开一个 issue。

**Comment by zhuwenmiao** [comment]
好的，李老师，看到jupyterlab无法运行是关于版本对应不上，就发到这里，不好意思，李老师。

**Comment by wuzhi7** [comment]
感谢李俊老师，用下面这条命令解决了
`sudo -H pip3 uninstall -y jupyterlab && sudo -H pip3 install jupyterlab`

**Comment by neolee** [comment]
@wuzhi7 严格来说，这个方法很不好，它强迫你以后维护 Jupyter Lab 安装必须使用 root 权限，这是安全隐患。我在前面给你的方案要好很多。不过，anyway……
