### ISSUE TITLE
不能使用 git push 把学习用书发到 GitHub

### ISSUE THREAD

**Issue by MSliang-803** [neolee/pilot#342]
PS C:\Users\Administrator\code\pilot-student> git status
On branch master
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        Untitled.ipynb

nothing added to commit but untracked files present (use "git add" to track)
PS C:\Users\Administrator\code\pilot-student> git push
remote: Permission to neolee/pilot-student.git denied to MSliang-803.
fatal: unable to access 'https://github.com/neolee/pilot-student.git/': The requested URL returned error: 403

**Comment by neolee** [comment]
你当然不能直接向我的 repo 推送，这也是为啥我建议先 fork 我们的官方仓库到你的账号下，然后再 clone 你自己 fork 出来的那个 repo，那是你的，你才可以 push。
