### ISSUE TITLE
终端输入code . 不会打开vscode

### ISSUE THREAD

**Issue by iliujixiang** [neolee/pilot#343]
mac系统，也安装了vscode，输入code . 怎么不启动 vscode？

**Comment by neolee** [comment]
有没有按照配置指南在 VSCode 中配置好命令行命令呢？

**Comment by iliujixiang** [comment]
> 有没有按照配置指南在 VSCode 中配置好命令行命令呢？这一步骤在 Windows 是不需要的，但在 macOS 下是必需的。

竟然忘了这关键的一步了 -_-!!!  现在好了，谢谢老师
