### ISSUE TITLE
编程环境设置的相关问题

### ISSUE THREAD

**Issue by hejunmei** [neolee/pilot#344]
使用装有专业视频剪辑软件的电脑 来学习编程，是否会对原先的系统或插件构成什么影响？

**Comment by neolee** [comment]
虽然说具体情况具体分析，但是专业视频软件和编程所需的工具交集很少，我自己一直使用 Final Cut / Motion 等软件，没遇到过问题。

如果你是 Windows 系统，我不太熟悉，但一般来说问题不大。如果对你来说这个问题很重要（如果出问题后果很严重），那么不妨把你用的专业软件发出来，网络搜索下是不是有可能的风险。
