### ISSUE TITLE
ERROR Hash check failed!

### ISSUE THREAD

**Issue by zhipingyang120** [neolee/pilot#345]
安装 python37@3.7.4时
PS C:\Users\90522> scoop install python37@3.7.4
WARN  Given version (3.7.4) does not match manifest (3.7.5)
WARN  Attempting to generate manifest for 'python37' (3.7.4)
Autoupdating python37
Searching hash for python-3.7.4.exe in https://www.python.org/downloads/release/python-374/
Found: md5:33cc602942a54446a3d6451476394789 using Extract Mode
Searching hash for python-3.7.4-amd64.exe in https://www.python.org/downloads/release/python-374/
Found: md5:a702b4b0ad76debdb3043a583e563400 using Extract Mode
Writing updated python37 manifest
Installing 'python37' (3.7.4) [64bit]
python-3.7.4-amd64.exe (25.4 MB) [============>                       ]  35%
Checking hash of python-3.7.4-amd64.exe ... ERROR Hash check failed!
App:         python37
URL:         https://www.python.org/ftp/python/3.7.4/python-3.7.4-amd64.exe#/py3.exe
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    a702b4b0ad76debdb3043a583e563400
Actual:      f5f3bc496800ab288adbb39d7a698692

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Versions/issues/new?title=python37%403.7.5%3a+hash+check+failed

李老师，这是网络问题吗？重试了好几次，都无效。

**Comment by neolee** [comment]
是网络问题，下载 python37 的安装包没成功，可能需要换网络或者用代理试试。

**Comment by zhipingyang120** [comment]
已经成功安装，的确是网络问题。
