### ISSUE TITLE
安装 Jupyter Lab报错

### ISSUE THREAD

**Issue by mzjimmy** [neolee/pilot#346]
1，按“安装和运行 Jupyter Lab”的步骤，先是PIP安装报错：
![image](https://user-images.githubusercontent.com/57100669/68088425-1c9d4b80-fe9a-11e9-912f-3ebb7cd5ca99.png)

2，在网上查找解决方案
用 easy_install -U pip命令成功安装PIP
![image](https://user-images.githubusercontent.com/57100669/68088456-6423d780-fe9a-11e9-9b92-30eb9f9663e5.png)

3，尝试了pip install jupyterlab和pip3 install jupyterlab，但是都没有成功安装Jupyter Lab，
不知道是PIP安装的版本问题还是网络问题，报错提示：
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='pypi.org', port=443): Read timed out. (read timeout=15)")': /simple/jupyerlab/
ERROR: Could not find a version that satisfies the requirement jupyerlab (from versions: none)
ERROR: No matching distribution found for jupyerlab

**Comment by piandong** [comment]
跟我遇到的情况一样，也是解决了第一步报错后，卡在pip install jupyterlab和pip3 install jupyterlab上面。我的报错是：
Traceback (most recent call last):
  File "c:\users\scoop\apps\python37\3.7.4\lib\runpy.py", line 193, in _r
un_module_as_main
    "__main__", mod_spec)
  File "c:\users\scoop\apps\python37\3.7.4\lib\runpy.py", line 85, in _ru
n_code
    exec(code, run_globals)
  File "C:\Users\scoop\apps\python37\current\scripts\pip3.exe\__main__.py
", line 9, in <module>
TypeError: 'module' object is not callable

**Comment by piandong** [comment]
一种解决方法：使用anaconda安装。教程：https://github.com/selfteaching/the-craft-of-selfteaching/blob/fe364e73c70204e832223a60fc9a7bf2cb44e7db/T-appendix.jupyter-installation-and-setup.ipynb

**Comment by neolee** [comment]
@piandong Anaconda 并不是我们推荐的方法，当然它是可以用的，但我们不会提供支持。具体可以参见我在 #67 里的最后一个长回复。

@mzjimmy 主要问题是网络，最好使用代理，注意很多代理要作用于命令行，还需要一定额外配置，可以咨询你的服务商。

**Comment by piandong** [comment]
感谢您花宝贵的时间为我提供指导！
________________________________
发件人: Neo Lee <notifications@github.com>
发送时间: 2019年11月4日 13:01
收件人: neolee/pilot <pilot@noreply.github.com>
抄送: piandong <piandong@hotmail.com>; Mention <mention@noreply.github.com>
主题: Re: [neolee/pilot] 安装 Jupyter Lab报错 (#346)


@piandong<https://github.com/piandong> Anaconda 并不是我们推荐的方法，当然它是可以用的，但我们不会提供支持。具体可以参见我在 #67<https://github.com/neolee/pilot/issues/67> 里的最后一个长回复。

@mzjimmy<https://github.com/mzjimmy> 主要问题是网络，最好使用代理，注意很多代理要作用于命令行，还需要一定额外配置，可以咨询你的服务商。

―
