### ISSUE TITLE
安装 Homebrew 时 password 无法输入

### ISSUE THREAD

**Issue by lieiei** [neolee/pilot#349]

**Comment by lieiei** [comment]
Press RETURN to continue or any other key to abort
==> /usr/bin/sudo /bin/mkdir -p /usr/local/bin /usr/local/etc /usr/local/include /usr/local/lib /usr/local/sbin /usr/local/share /usr/local/var /usr/local/opt /usr/local/share/zsh /usr/local/share/zsh/site-functions /usr/local/var/homebrew /usr/local/var/homebrew/linked /usr/local/Cellar /usr/local/Caskroom /usr/local/Homebrew /usr/local/Frameworks
Password:
Sorry, try again.
Password:
Sorry, try again.
Password:
sudo: 3 incorrect password attempts
Failed during: /usr/bin/sudo /bin/mkdir -p /usr/local/bin /usr/local/etc /usr/local/include /usr/local/lib /usr/local/sbin /usr/local/share /usr/local/var /usr/local/opt /usr/local/share/zsh /usr/local/share/zsh/site-functions /usr/local/var/homebrew /usr/local/var/homebrew/linked /usr/local/Cellar /usr/local/Caskroom /usr/local/Homebrew /usr/local/Frameworks
liyingyingdeMacBook-Air:~ liyingying$ lieiei12345
-bash: lieiei12345: command not found
liyingyingdeMacBook-Air:~ liyingying$

**Comment by neolee** [comment]
不存在无法输入的问题，只是你输入的时候不会回显而已。提示时输入你的登录密码并回车就可以了。

**Comment by rightyes** [comment]
请问老师这个登录密码是任意设置吗

**Comment by neolee** [comment]
@rightyes 不要在别人的 issue 下问新问题（你还在还几个 issue 下问），自己提新的 issue 就好。这次就算了，下不为例。

这个密码是你进入桌面也就是登录 macOS 的密码。
