### ISSUE TITLE
安装Homebrew时password无法输入

### ISSUE THREAD

**Issue by lieiei** [neolee/pilot#350]
Press RETURN to continue or any other key to abort
==> /usr/bin/sudo /bin/mkdir -p /usr/local/bin /usr/local/etc /usr/local/include /usr/local/lib /usr/local/sbin /usr/local/share /usr/local/var /usr/local/opt /usr/local/share/zsh /usr/local/share/zsh/site-functions /usr/local/var/homebrew /usr/local/var/homebrew/linked /usr/local/Cellar /usr/local/Caskroom /usr/local/Homebrew /usr/local/Frameworks
Password:
Sorry, try again.
Password:
Sorry, try again.
Password:
sudo: 3 incorrect password attempts
Failed during: /usr/bin/sudo /bin/mkdir -p /usr/local/bin /usr/local/etc /usr/local/include /usr/local/lib /usr/local/sbin /usr/local/share /usr/local/var /usr/local/opt /usr/local/share/zsh /usr/local/share/zsh/site-functions /usr/local/var/homebrew /usr/local/var/homebrew/linked /usr/local/Cellar /usr/local/Caskroom /usr/local/Homebrew /usr/local/Frameworks
liyingyingdeMacBook-Air:~ liyingying$ lieiei12345
-bash: lieiei12345: command not found
liyingyingdeMacBook-Air:~ liyingying$

**Comment by lieiei** [comment]
不好意思，已解决。

**Comment by neolee** [comment]
不要重复发一样的 issue。

Duplicate of #349
