### ISSUE TITLE
执行代码的时候找不到 python

### ISSUE THREAD

**Issue by zhuwenmiao** [neolee/pilot#351]
<img width="564" alt="截屏2019-11-04上午9 09 37" src="https://user-images.githubusercontent.com/31498197/68095273-fc45af00-fee2-11e9-8959-1e226cda28a8.png">

**Comment by zhuwenmiao** [comment]
<img width="571" alt="截屏2019-11-04上午9 50 12" src="https://user-images.githubusercontent.com/31498197/68095958-8ba19100-fee8-11e9-8e31-5c4005705065.png">
在后面试试，就变成这样了

**Comment by zhuwenmiao** [comment]
安装和运行 Jupyter Lab也遇到此类问题
<img width="1440" alt="截屏2019-11-04上午11 51 44" src="https://user-images.githubusercontent.com/31498197/68098753-8ac52b00-fef9-11e9-94fe-16df2f3b276a.png">

**Comment by neolee** [comment]
你的系统里 python 指向系统自带的 Python 2.7，而你用 Homebrew 安装的 python 包是 3.7，你需要用 python3 和 pip3 命令才行。类似问题在这里已经被提出很多次了，搜索一些就能找到一堆，比如这个 #331 可以参考。
