### ISSUE TITLE
在一个类的方法中，为啥会有两个print（）

### ISSUE THREAD

**Issue by xiaoerhai** [neolee/pilot#353]
（图片还是上图不了，一直没有出现那个提示语，所以直接复制文本了）
class Garfield:
    
    def __init__(self, wait=1):
        Bot.wait = wait
        self.bots = []

    def add(self, bot):
        self.bots.append(bot)

    def _prompt(self, s):
        print(s)
        print()

**Comment by neolee** [comment]
这个问题，你自己试试就可以很容易的得到答案。

在 notebook 中随便开一个新的 cell，然后试试在里面写上：
```python
print('hello')
print('world')
```
运行一下，然后再试试：
```python
print('hello')
print()
print('world')
```
Python 和 notebook 的优势就是尝试运行一些代码特别简单，特别没成本，不要浪费了这样的好处。

p.s. 上传图片是很简单同时很有用的事情，不要这么轻易放弃，否则走不远。
