### ISSUE TITLE
在函数中 return 和 print 能互相代替吗？

### ISSUE THREAD

**Issue by xiaoerhai** [neolee/pilot#355]
class HelloBot(Bot):
    def __init__(self):
        self.q = "Hi, what is your name?"

    def _think(self, s):
        return f"Hello {s}"

**Comment by neolee** [comment]
这是完全不同的两个东西。print() 是一个内建函数；而 `return` 是一个特殊语句，仅用在函数定义内部，表示终止当前函数的运行并把后面的值作为返回值返回。
