### ISSUE TITLE
window系统，也安装了vscode，输入code . 不启动 vscode，重新安装然后重启还是没有反应

### ISSUE THREAD

**Issue by h140** [neolee/pilot#356]
<img width="960" alt="2019-11-04 (1)" src="https://user-images.githubusercontent.com/54472184/68097225-c7d8ef80-fef0-11e9-8b7c-1917b9501737.png">

**Comment by h140** [comment]
再次重新下载，重启，现在输入code，可以正常启动vscode

**Comment by neolee** [comment]
你的截图里并没有看到你执行 `code` 命令啊，反复在执行的都是 `cd`。专注。

最后解决了就好，可以继续。
