### ISSUE TITLE
安装 scoop 显示无法连接到远程服务器

### ISSUE THREAD

**Issue by oneisonly** [neolee/pilot#357]

**Comment by oneisonly** [comment]
PS C:\Users\Administrator> iwr -useb get.scoop.sh | iex
iwr : 无法连接到远程服务器
所在位置 行:1 字符: 1
+ iwr -useb get.scoop.sh | iex
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:Htt
   pWebRequest) [Invoke-WebRequest]，WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShe
   ll.Commands.InvokeWebRequestCommand

**Comment by oneisonly** [comment]
PS C:\Users\Administrator> scoop checkup
scoop : 无法将“scoop”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检
查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ scoop checkup
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (scoop:String) [], CommandNotFou
   ndException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by oneisonly** [comment]
![QzpcVXNlcnNcQWRtaW5pc3RyYXRvclxBcHBEYXRhXFJvYW1pbmdcRGluZ1RhbGtcMTEyMDQwOTYxX3YyXEltYWdlRmlsZXNcMTU3MjgzNzAxODE0MV9FQzAyMDM3RC0wQThCLTQwOTAtQjhCQi05OTAzQzM3Qzc3N0EucG5n](https://user-images.githubusercontent.com/53245383/68097900-906c4200-fef4-11e9-9771-b0ce15ec21a1.jpg)

**Comment by neolee** [comment]
截图中第一步（安装 Scoop）失败了，原因是网络问题，需要重试，最好换网络或者挂代理。

Scoop 既然没安装成功，那么第二部要用它自然也不会成功。
