### ISSUE TITLE
安装 scoope 过程中报错 iwr : 无法连接到远程服务器，请问如何解决

### ISSUE THREAD

**Issue by Ceasar1978** [neolee/pilot#358]
报错信息为红字：
iwr : 无法连接到远程服务器
所在位置 行:1 字符: 1
+ iwr -useb get.scoop.sh | iex
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebR
   equest) [Invoke-WebRequest]，WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Co
   mmands.InvokeWebRequestCommand

**Comment by Ceasar1978** [comment]
原来是联网不畅，架梯子就解决了，真晕

**Comment by bennet569** [comment]
> 原来是联网不畅，架梯子就解决了，真晕

你好，请问架梯子是什么意思？
