### ISSUE TITLE
Scoop checkup 时报的潜在问题

### ISSUE THREAD

**Issue by weiwei886** [neolee/pilot#359]
PS C:\Users\siwei> scoop checkup
WARN  Windows Defender may slow down or disrupt installs with realtime scanning.
  Consider running:
    sudo Add-MpPreference -ExclusionPath 'C:\Users\siwei\scoop'
  (Requires 'sudo' command. Run 'scoop install sudo' if you don't have it.)
WARN  Windows Defender may slow down or disrupt installs with realtime scanning.
  Consider running:
    sudo Add-MpPreference -ExclusionPath 'C:\ProgramData\scoop'
  (Requires 'sudo' command. Run 'scoop install sudo' if you don't have it.)
WARN  LongPaths support is not enabled.
You can enable it with running:
    Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1
WARN  Found 3 potential problems.
scoop install sudo已经安装完了，还是这个结果。

**Comment by neolee** [comment]
它上面不是说了吗，你需要运行下面几个命令：

```powershell
sudo Add-MpPreference -ExclusionPath 'C:\Users\siwei\scoop'
sudo Add-MpPreference -ExclusionPath 'C:\ProgramData\scoop'
Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1
```

照做就好。
