### ISSUE TITLE
执行print(f'4 + 9 = {4 + 9}')显示SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by wongpu** [neolee/pilot#36]
老师您好，
提示是这样的
    print(f'4 + 9 = {4 + 9}')
                                        ^
SyntaxError: invalid syntax
后面那个单引号错误，从教程直接复制过来代码也是这样的。

**Comment by neolee** [comment]
你在什么地方运行的这个代码？

另外你在命令行运行 `python -V` 的结果是什么？

**Comment by wongpu** [comment]
在Mac的终端里运行的，python的版本是3.7.4。

**Comment by neolee** [comment]
你在命令行运行：

```shell
python -V
python
```

然后输入你上面的程序代码执行，然后截屏给我看。

**Comment by wongpu** [comment]
李老师，打扰您休息了，不好意思，我想应该是我把python的版本搞错了，用python3 hello.py执行就正确了。

**Comment by neolee** [comment]
果然是这样子呀，那就好了。

**Comment by wongpu** [comment]
谢谢李老师了，😊



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Neo Lee <notifications@github.com&gt;
发送时间: 2019年10月24日 00:06
收件人: neolee/pilot <pilot@noreply.github.com&gt;
抄送: wongpu <wongpu@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[neolee/pilot] 执行print(f'4 + 9 = {4 + 9}')显示SyntaxError: invalid syntax (#36)




果然是这样子呀，那就好了。

**Comment by wongpu** [comment]
发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Neo Lee <notifications@github.com&gt;
发送时间: 2019年10月23日 23:43
收件人: neolee/pilot <pilot@noreply.github.com&gt;
抄送: wongpu <wongpu@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[neolee/pilot] 执行print(f'4 + 9 = {4 + 9}')显示SyntaxError: invalid syntax (#36)




你在命令行运行：
 python -V python
 
然后输入你上面的程序代码执行，然后截屏给我看。
