### ISSUE TITLE
环境配置的时候出现了几处小白问题

### ISSUE THREAD

**Issue by DorisChenWen** [neolee/pilot#361]
brew doctor 的时候出现了 warning 内容如下：
Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and which additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew-provided
script of the same name. We found the following "config" scripts:
  /Library/Frameworks/Python.framework/Versions/2.7/bin/python2-config
  /Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7-config
  /Library/Frameworks/Python.framework/Versions/2.7/bin/python-config

install git python 出现了 error 内容如下：
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/2to3
Target /usr/local/bin/2to3
already exists. You may want to remove it:
  rm '/usr/local/bin/2to3'

To force the link and overwrite all conflicting files:
  brew link --overwrite python

To list all files that would be deleted:
  brew link --overwrite --dry-run python

Possible conflicting files are:
/usr/local/bin/2to3 -> /Library/Frameworks/Python.framework/Versions/2.7/bin/2to3

之后在输入 code. 的步骤出现了 如下内容：

Wenwens-MacBook-Pro:Code wenwenchen$ code.
-bash: code.: command not found

最后在VSCode里 输入 print('Hello world!')想保存的时候显示：

unable to write file (Nopermissions(FileSystemError): Error: EACCE: permission denied, open'/hello.py')

**Comment by neolee** [comment]
第一个问题，我需要一些信息，执行下面几个命令，截图给我看看结果：

```shell
uname -a
echo $PATH
```

关于安装 Python 的警告信息，可以执行下面的命令来解决 `brew link --overwrite python`。

关于执行 `code` 命令的错误，是因为你在 `code` 和 `.` 之间少了一个空格，应该是 `code .`。注意这一步的前提是你要安装好 Visual Studio Code 并运行它，然后按照配置指南在里面配置好命令行命令 `code` 才行。

最后一个问题是你打开了你计算机的根目录 `/`，这个目录你是不可以写的，你应该在你的用户根目录 `/Users/wenwenchen` 下面创建你的程序子目录，比如：

```shell
mkdir -p ~/Code/test
cd ~/Code/test
code .
```

然后在打开的 VSCode 中编辑新文件并保存为 `hello.py`，就不会有问题了。

**Comment by DorisChenWen** [comment]
![Screen Shot 2019-11-04 at 15 06 02](https://user-images.githubusercontent.com/48721070/68126818-e7820f00-ff14-11e9-9fbb-09e3c8492f40.png)

**Comment by neolee** [comment]
那么第一个问题的解决方案是，执行 `code ~/.bash_profile` ，这个命令会用 VSCode 打开你的命令行配置文件，找找里面有没有 `PATH=...` 的一行，截图给我看看，我再告诉你怎么改。

**Comment by DorisChenWen** [comment]
![Screen Shot 2019-11-04 at 15 25 35](https://user-images.githubusercontent.com/48721070/68128101-611afc80-ff17-11e9-8f1e-013a7d18b4d1.png)

**Comment by neolee** [comment]
执行：

```shell
cp ~/.bash_profile.pysave ~/.bash_profile
```

然后第一个问题就解决了；其他问题按照我前面的回复，一个个处理就好。
