### ISSUE TITLE
关于 python 版本问题

### ISSUE THREAD

**Issue by zhuwenmiao** [neolee/pilot#362]
<img width="1440" alt="截屏2019-11-04下午8 22 19" src="https://user-images.githubusercontent.com/31498197/68124293-018a1480-ff4a-11e9-8d84-a65576fc9266.png">
在安装jupyterlab的时候系统默认为python2.7，通过网上给出的方法，改变python的软连接，但是系统不需要改变，此外，搜索的方法改变默认python版本是否对于jupyterlab的安装有帮助呢？李老师。
了解到python对应pip，python2 对应pip2，python3对应pip3，在运行pip3 安装jupyterlab为什么还是变成默认的python2.7版本，这个不是很理解，望李老师解答

**Comment by neolee** [comment]
执行下面几个命令看看结果：

```shell
which python
which python3
python -V
python3 -V

which pip
which pip3
pip -V
pip3 -V

echo $PATH
```

**Comment by zhuwenmiao** [comment]
<img width="1438" alt="截屏2019-11-04下午10 01 33" src="https://user-images.githubusercontent.com/31498197/68126421-bb837f80-ff4e-11e9-8563-961d34ce973e.png">
李老师，请您查看。

**Comment by neolee** [comment]
继续，截图来看：

```shell
cd /usr/local/bin
ls -l pip*
```

**Comment by zhuwenmiao** [comment]
<img width="473" alt="截屏2019-11-04下午10 06 15" src="https://user-images.githubusercontent.com/31498197/68126720-5d0ad100-ff4f-11e9-8cfb-bb1a90dae893.png">
李老师，辛苦您了

**Comment by neolee** [comment]
就在上面这个目录下执行 `ls -l` 结果如何？

**Comment by zhuwenmiao** [comment]
<img width="980" alt="截屏2019-11-04下午10 09 43" src="https://user-images.githubusercontent.com/31498197/68127013-f0440680-ff4f-11e9-9dc4-a1042b964c07.png">
<img width="1440" alt="截屏2019-11-04下午10 10 10" src="https://user-images.githubusercontent.com/31498197/68127016-f20dca00-ff4f-11e9-9013-6981d44be85e.png">
有点长，分成了两部分

**Comment by neolee** [comment]
知道了，我不知道为啥，但是你的 `/usr/local/bin` 下面有些捣乱分子，所有你看到第三列是 `root` 而不是 `wenmiaozhu` 的文件就是。这些文件的 owner 是系统 `root` 用户，所以你做任何操作（比如用 Homebrew 安装 Python 时）都没法动这些捣乱的文件，结果是你这个目录下的 `pip` 和 `pip3` 等文件都没有指向正确的文件。解决方案是这样：

```shell
cd /usr/local/bin
sudo chown wenmiaozhu *
brew unlink python
brew link python
```

然后：
```shell
cd
which pip
which pip3
pip -V
pip3 -V
```

确认下修复之后的结果。

最后，你的 PATH 变量里的第一个路径，是个麻烦之源，最好干掉。执行 `code ~/.bash_profile` 打开命令行配置文件，看看里面有没有 `PATH=...` 的一行，截屏给我看看，我再告诉你怎么改。

**Comment by zhuwenmiao** [comment]
<img width="651" alt="截屏2019-11-04下午10 25 46" src="https://user-images.githubusercontent.com/31498197/68128140-1ec2e100-ff52-11e9-81d3-90b4944df798.png">
<img width="950" alt="截屏2019-11-04下午10 24 46" src="https://user-images.githubusercontent.com/31498197/68128151-21bdd180-ff52-11e9-91bb-d5d02b305aaa.png">
李老师，前面命令执行的时候还是有个错误呢。

**Comment by neolee** [comment]
你执行 `brew link --overwrite python` 应该就可以了，再执行那几个确认的命令看看。

然后你执行下 `echo $SHELL` 给我看看结果。

你的这个 bash 配置文件说明你这个机器以前装过不少东西啊，什么 Anaconda，还有 RVM……

**Comment by zhuwenmiao** [comment]
<img width="741" alt="截屏2019-11-04下午10 34 36" src="https://user-images.githubusercontent.com/31498197/68128798-5d0cd000-ff53-11e9-91ec-c10f385885ca.png">
是的，李老师，确实安装了不少东西，看来都没有卸载干净，非常感谢您花了那么多时间解答，自己尝试通过谷歌查找答案，非常感恩李老师。

**Comment by neolee** [comment]
好了，你的 pip3 总算是对了，你可以用 `pip3 install jupyterlab` 来装 Jupyter Lab 了。

你可以清理一下 `~/.bash_profile` 的内容，不少不需要的东西被加到 PATH 变量里去了。

**Comment by zhuwenmiao** [comment]
好的，非常感谢李老师您！
