### ISSUE TITLE
提示

### ISSUE THREAD

**Issue by dahuan123** [neolee/pilot#364]
Python 3.7.3 (default, Mar 27 2019, 17:13:21) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32
Warning:
This Python interpreter is in a conda environment, but the environment has
not been activated.  Libraries may fail to load.  To activate this environment
please see https://conda.io/activation

这个咋回事儿啊老师

**Comment by neolee** [comment]
你装过 Anaconda，现在这个环境已经损坏，你运行 python 时就出错了。最好彻底删掉 Anaconda，然后按照我们的配置指南操作。

**Comment by dahuan123** [comment]
老师，我在电脑本地的命令行里运行 python 的时候，会出现这种情况，但是在 Anaconda自带的那个命令行运行的时候，又没有出现这种情况。

**Comment by neolee** [comment]
对于 Anaconda 环境，我没法提供支持，你可以自己研究和探索。

**Comment by dahuan123** [comment]
好的老师，我自己研究研究，谢谢老师
