### ISSUE TITLE
安装 Python 时 scoop install python37@3.7.4 出现警告

### ISSUE THREAD

**Issue by tianzhansheng321** [neolee/pilot#365]
PS C:\Users\Administrator> scoop install python37@3.7.4
WARN  Given version (3.7.4) does not match manifest (3.7.5)
WARN  Attempting to generate manifest for 'python37' (3.7.4)
Autoupdating python37
Searching hash for python-3.7.4.exe in https://www.python.org/downloads/release/python-374/
然后就很慢，好像找不到需要的文件，找到之后加载到1%一直等就连接超时了

**Comment by neolee** [comment]
前面的 WARNING 没啥问题，只是因为你要装的不是最新版本而已。后面还是网络的问题。

**Comment by tianzhansheng321** [comment]
嗯，刚才才学会问题搜索功能，看到之前也有同学跟我的问题一样，明白了警告没问题。但是网速也挺好，并且之前scoop  和 git安装都出现问题(远程连接不上），之后找了代理，然后都装上了，现在装Python试了好多回，每次加载都很慢，最多到5%，然后连接就超时了，难道是代理的网络有时间因素，不稳定？我再找别的时间段试试，感谢老师的耐心回答，搜索出问题之后一直在找怎么删除这个问题，然后看见老师都回复了，竟然没有生气，感动！

**Comment by tianzhansheng321** [comment]
还有想问老师，可不可以在网站上直接下载python到scoop文件夹里，不用代码下载可以吗？

**Comment by tianzhansheng321** [comment]
> 前面的 WARNING 没啥问题，只是因为你要装的不是最新版本而已。后面还是网络的问题。
嗯，刚才才学会问题搜索功能，看到之前也有同学跟我的问题一样，明白了警告没问题。但是网速也挺好，并且之前scoop 和 git安装都出现问题(远程连接不上），之后找了代理，然后都装上了，现在装Python试了好多回，每次加载都很慢，最多到5%，然后连接就超时了，难道是代理的网络有时间因素，不稳定？我再找别的时间段试试，感谢老师的耐心回答，搜索出问题之后一直在找怎么删除这个问题，然后看见老师都回复了，竟然没有生气，感动！


还有想问老师，可不可以在网站上直接下载python到scoop文件夹里，不用代码下载可以吗？

**Comment by tianzhansheng321** [comment]
> 前面的 WARNING 没啥问题，只是因为你要装的不是最新版本而已。后面还是网络的问题。

嗯，刚才才学会问题搜索功能，看到之前也有同学跟我的问题一样，明白了警告没问题。但是网速也挺好，并且之前scoop 和 git安装都出现问题(远程连接不上），之后找了代理，然后都装上了，现在装Python试了好多回，每次加载都很慢，最多到5%，然后连接就超时了，难道是代理的网络有时间因素，不稳定？我再找别的时间段试试，感谢老师的耐心回答，搜索出问题之后一直在找怎么删除这个问题，然后看见老师都回复了，竟然没有生气，感动！


还有想问老师，可不可以在网站上直接下载python到scoop文件夹里，不用代码下载可以吗？

**Comment by neolee** [comment]
网络问题就这样，时灵时不灵……

不知道你的代理怎么配置，一般来说代理需要做特定配置才能对命令行生效，你可以咨询下服务商。
