### ISSUE TITLE
安装 nodejs 遇到的问题

### ISSUE THREAD

**Issue by Dreamzd** [neolee/pilot#366]
![IMG_20191104_234736R](https://user-images.githubusercontent.com/46898702/68134806-9ea27880-ff5d-11e9-935a-02651e9a4b4c.jpg)
安装nodejs，发现scoop包里显示"nodejs failed"。

**Comment by neolee** [comment]
安装碰到网络问题，重装试试：`scoop uninstall nodejs` 再 `scoop install nodejs`。
