### ISSUE TITLE
第六章 异常处理程序思考问题

### ISSUE THREAD

**Issue by Winsi0n** [neolee/pilot#367]
自己想看看课程案例中的 ‘err’ 是什么类型，于是在最后加上 type(err) 希望能输出类型，结果输出结果并未改变；
想着是不是解释器一次只能跑一条指令，于是试着在程序前加入 type(0) 进行验证，输出还是没有改变；

请教老师这是什么原因呢？

type(0)
​
def this_fails():
   x = 1/0
    
try:
    this_fails()
except ZeroDivisionError as err:
    print('Handling run-time error:', err)
    type(err)
--------------------------------------------------------    

Handling run-time error: division by zero

**Comment by neolee** [comment]
如果你要输出 `type(err)`，就需要把它打印出来 `print(type(err))`。

**Comment by Winsi0n** [comment]
哦哦，那第二章一开始调用type（）能看到输出只是jypeter协助输出的，是这样理解吗？

**Comment by neolee** [comment]
Python 解释器有个特性，就是你输入单独的一个变量或者表达式时，会显示它的值，其实只是方便你调试而已。在真正的程序里，要显示什么的话，还是需要使用能实现“显示”这个功能的函数，比如 print()。

**Comment by Winsi0n** [comment]
OK，明白！

**Comment by xiaoerhai** [comment]
> Python 解释器有个特性，就是你输入单独的一个变量或者表达式时，会显示它的值，其实只是方便你调试而已。在真正的程序里，要显示什么的话，还是需要使用能实现“显示”这个功能的函数，比如 print()。

这里的【真正的程序里】具体是指哪里？另，我在Python里输入：`type(err)`后，显示error：‘NameError: name 'err' is not defined’

**Comment by neolee** [comment]
@xiaoerhai 这两个问题应该都能自己想出答案来。

**Comment by xiaoerhai** [comment]
1、这里【真正的程序里】是指 在 jupyter lab 中执行代码，今早我按以上步骤试了下，发现输出确实没有改变；
2、`type(err)`   里的`err`，在Python中并不是对象，而是一个普通的没有赋值的变量名称。

**Comment by neolee** [comment]
@xiaoerhai 不太对。
1. 这里真正的程序是指把程序写在一个 .py 的源文件里，然后用 `python xxx.py` 去运行，这是最原生的运行方式。

2. 你看题主的代码，`err` 是在异常处理结构里的：
```python
try:
    ...
except ZeroDivisionError as err:
    print('Handling run-time error:', err)
```

这个 `err` 是 `except` 语句里定义的一个变量，只在 `except` 语句及其下面缩进的代码块里有效，离开这个语句单独去看它的 type，自然会出错。
