### ISSUE TITLE
关于Scopp之后运行三个安装包的问题？

### ISSUE THREAD

**Issue by Rudy2019** [neolee/pilot#37]
安装好 Scoop 之后我们建议立刻安装三个软件包，运行：

scoop bucket add versions
scoop update
scoop install busybox git python37

![微信截图_20191023230826](https://user-images.githubusercontent.com/48624529/67407484-26959380-f5ea-11e9-8f20-782fea1af3f8.png)

此安装包运行不了

**Comment by neolee** [comment]
这个似乎是 Scoop 没有完全装好。

在运行这三个之前，先运行 `scoop install git` 试试。

**Comment by xbq1022** [comment]
按提示的做，试试先运行“scoop install git”，在运行上面的

**Comment by Rudy2019** [comment]
![2](https://user-images.githubusercontent.com/48624529/67409779-9b1e0180-f5ed-11e9-8adc-6362bf3077ab.png)

卸载重新安装后，您请看是否正确

**Comment by Xiaoxiaokangkang** [comment]
怎么放照片上来呀?系统提示说是scoop已经安装好，‘’Scoop is already installed. Run 'scoop update' to get the latest version.‘’三个软件也没安装好，
scoop : 无法将“scoop”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请
检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ scoop update
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (scoop:String) [], ParentConta
   insErrorRecordException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by neolee** [comment]
@Rudy2019 是这样的，等它下载和安装好 git，再依次运行：

```shell
scoop bucket add versions
scoop update
scoop install python37
```

**Comment by neolee** [comment]
@Xiaoxiaokangkang 你这个问题和这个 issue 没关系，请你另外去提一个 issue。

顺便，你这个问题很可能和 #33 类似，也可以参考下。

**Comment by qxnatalie** [comment]
执行第三个命令，装了一半，结果显示失败。请解答。
![image](https://user-images.githubusercontent.com/36719487/67428241-548dce80-f610-11e9-88c3-cf0b2654218d.png)

**Comment by neolee** [comment]
@qxnatalie 试试卸载 python37 然后再装一次：

scoop uninstall python37
scoop install python37

**Comment by qxnatalie** [comment]
卸载然后重装，结果一样
![image](https://user-images.githubusercontent.com/36719487/67449601-47430500-f64d-11e9-818e-3cbd23b3fbd5.png)

**Comment by neolee** [comment]
你现在运行下面两个命令结果如何：

```shell
python -V
pip -V
```

**Comment by qxnatalie** [comment]
敲完命令，直接黑屏了


------------------ 原始邮件 ------------------
发件人: Neo Lee <notifications@github.com&gt;
发送时间: 2019年10月23日 20:05
收件人: neolee/pilot <pilot@noreply.github.com&gt;
抄送: qxnatalie <1502208063@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[neolee/pilot] 关于Scopp之后运行三个安装包的问题？ (#37)




你现在运行下面两个命令结果如何：
 python -V pip -V

**Comment by neolee** [comment]
这个肯定不正常，可能 Windows 系统本身存在一些问题，或者你是不是有运行一些防病毒软件？

**Comment by qxnatalie** [comment]
敲入 python -V, 就出现黑屏，三次，均按F10恢复。第四次输入两个命令，出错如下：
![image](https://user-images.githubusercontent.com/36719487/67451276-8a53a700-f652-11e9-936b-5fe1df23447a.png)

**Comment by neolee** [comment]
由于不明的原因，Python 包没有安装好，我比较倾向于系统有一些保护机制干扰了 Scoop 的安装过程。建议你暂停所有防病毒或者类似的软件进行下面的操作来测试下：

```shell
scoop uninstall python37
scoop install python37@3.7.4
```

**Comment by neolee** [comment]
@qxnatalie 另外，建议你另开一个 issue。

**Comment by ZhaiGuangkai** [comment]
![图片](https://user-images.githubusercontent.com/54047618/67492635-493ab180-f6a9-11e9-8f97-7064f1657e4e.png)
Can't shim 'Lib\idlelib\idle.bat': File doesn't exist.提示这个内容。之前我安装好了Python3.7.4，然后升级成了Python3.7.5，之后想把版本改回Python3.7.4。重复多次仍然出错（清理过注册表，之前单独安装过Python3.8然后此次卸载，用scoop重装）
还有提示过
PS C:\Users\Administrator> scoop install python37@3.7.4
WARN  Given version (3.7.4) does not match manifest (3.7.5)
WARN  Attempting to generate manifest for 'python37' (3.7.4)
Autoupdating python37
Searching hash for python-3.7.4.exe in https://www.python.org/downloads/release/python-374/
Found: md5:33cc602942a54446a3d6451476394789 using Extract Mode
Searching hash for python-3.7.4-amd64.exe in https://www.python.org/downloads/release/python-374/
Found: md5:a702b4b0ad76debdb3043a583e563400 using Extract Mode
Writing updated python37 manifest
Installing 'python37' (3.7.4) [64bit]
Loading python-3.7.4-amd64.exe from cache
Checking hash of python-3.7.4-amd64.exe ... ok.
Running installer... error.
ERROR Exit code was 1638!
Installation aborted. You might need to run 'scoop uninstall python37' before trying again.
以上内容，反复卸载重装仍然出错

**Comment by neolee** [comment]
@ZhaiGuangkai 请参考这个 issue #32 #43 ，如果还未解决请另开新 issue。

**Comment by ygrdkl** [comment]
这一节省了我很多时间
