### ISSUE TITLE
未以管理员身份安装 scoop 如何补救

### ISSUE THREAD

**Issue by oneisonly** [neolee/pilot#371]
![0e47c22702bca7a484f00c610e65190](https://user-images.githubusercontent.com/53245383/68174631-b3acf500-ffb9-11e9-84a8-d62515630114.jpg)

**Comment by oneisonly** [comment]
操作时没有选择管理员，安装后，运行scoop list显示里面什么都没有

**Comment by neolee** [comment]
你这个问题和管理员权限无关，一般情况下并不需要管理员权限就可以完成我们全部安装配置。

你的问题是安装 Scoop 根本没成功，红字说的很清楚“无法连接到远程服务器”，所以是网络问题。

后面自然肯定也不会成功了。

**Comment by oneisonly** [comment]
老师，下面说scoop is already installed，意思不是已经安装了吗？

**Comment by neolee** [comment]
不是，你的 Scoop 没安装好，需要重装，参考 Wiki 里“重新安装 Scoop”一节。

**Comment by oneisonly** [comment]
![caa55144fb9d09377266b3ccd3a7cdb](https://user-images.githubusercontent.com/53245383/68220925-8ac14a00-0023-11ea-8b19-5787d9830f2c.jpg)

**Comment by oneisonly** [comment]
老师，这个步骤是不是意味着已经卸载scoop？明天找个代理服务器直接输入iwr -useb。。。iex，安装就行了？

**Comment by neolee** [comment]
是的。

**Comment by oneisonly** [comment]
老师，挂代理是不是改dns的配置？
