### ISSUE TITLE
安装pip install jupyterlab提示以下错误，已挂代理网络应该没有问题

### ISSUE THREAD

**Issue by weidong3597** [neolee/pilot#372]
![报错图片一](https://user-images.githubusercontent.com/48782455/68175584-ae9d7500-ffbc-11e9-9158-b70b58170b8a.png)
![报错图片二](https://user-images.githubusercontent.com/48782455/68175588-bb21cd80-ffbc-11e9-897d-e3b09030687f.png)

**Comment by neolee** [comment]
没看到有错误，应该是之前装过，所以没啥需要修正的。

**Comment by weidong3597** [comment]
但是在输入：scoop list 并没有看到有pip install jupyterlab安装成功的提示，如图所示
![报错三](https://user-images.githubusercontent.com/48782455/68182977-072d3c00-ffd6-11e9-8e94-0831b180e7ff.png)

**Comment by neolee** [comment]
Scoop 安装的是各种命令行程序，比如 git、Python；pip 安装的是 Python 的第三方软件包，比如 Jupyter Lab，这俩不一样。

你要看 Jupyter Lab 的安装成果应该用 pip list 这个命令。

**Comment by weidong3597** [comment]
输入 pip list命令后，如下图所示，这意味着我是安装好了Jupyter Lab吗？
![反馈四](https://user-images.githubusercontent.com/48782455/68196233-41f19d00-fff3-11e9-8a6f-e54f33dee5be.png)

**Comment by neolee** [comment]
你去到你的学习用书目录，执行 `jupyter lab` 试试，要是正常打开了 Jupyter Lab 那就没问题了啊。

**Comment by weidong3597** [comment]
在我打开学习用书的时候，提示说找不到该路径，我以为我没有cole,当我cole又提示学习用书已经存在，以下是提示，还有我cole的地址，老师您看
![反馈五](https://user-images.githubusercontent.com/48782455/68198963-0b6a5100-fff8-11e9-9af7-0e257256ab96.png)
![反馈六](https://user-images.githubusercontent.com/48782455/68198967-0efdd800-fff8-11e9-8e7b-7daa9395db47.png)

**Comment by weidong3597** [comment]
当我执行jupyter lab 出现了一个网址，我到浏览器打开，看到以下界面，这样jupyter lab应该是下载好了的吧，嘻嘻
![反馈七](https://user-images.githubusercontent.com/48782455/68200933-ccd69580-fffb-11e9-8f1b-4b3f19cc30f0.png)

**Comment by neolee** [comment]
没问题了，keep going!
