### ISSUE TITLE
移动端无法完全展示文章

### ISSUE THREAD

**Issue by BobbyLH** [neolee/pilot#373]
移动端UI右侧文字无法完全显示，详见下图，希望能修复。

![3631572928189_ pic](https://user-images.githubusercontent.com/25814873/68178910-9f242900-ffc8-11e9-85c8-2fe5555b9e2a.jpg)

**Comment by neolee** [comment]
我好像第一次课就说过，学编程需要桌面电脑，notebook 的渲染目前是不支持手机那么小的屏幕的（pad 横屏应该可以）。

**Comment by neolee** [comment]
我自己看技术书，一般用 iPad mini 或者 Kindle。

**Comment by jinglong-py** [comment]
关闭竖屏锁定，横屏可以观看
