### ISSUE TITLE
想学习命令行有什么好的教材或者学习方法推荐吗

### ISSUE THREAD

**Issue by sunshangyi** [neolee/pilot#374]

**Comment by neolee** [comment]
我觉得 Zed Shaw 的这个入门教程不错（他的原版在修，修好了会重新上架，下面链接是别人转的稍老版本）：

http://cglab.ca/~morin/teaching/1405/clcc/book/cli-crash-course.html

**Comment by sunshangyi** [comment]
> 我觉得 Zed Shaw 的这个入门教程不错（他的原版在修，修好了会重新上架，下面链接是别人转的稍老版本）：
> 
> http://cglab.ca/~morin/teaching/1405/clcc/book/cli-crash-course.html

多谢！
