### ISSUE TITLE
scoop checkup 遇到的问题

### ISSUE THREAD

**Issue by fengsuizhi** [neolee/pilot#375]
PS C:\Users\Administrator> scoop checkup
WARN  LongPaths support is not enabled.
You can enable it with running:
    Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1
ERROR 'Inno Setup Unpacker' is not installed! It's required for unpacking InnoSetup files. Please run 'scoop install innounp'.
WARN  Found 2 potential problems.
PS C:\Users\Administrator> scoop install innounp
ERROR It looks like a previous installation of innounp failed.
Run 'scoop uninstall innounp' before retrying the install.
WARN  'innounp' () is already installed.
Use 'scoop update innounp' to install a new version.
PS C:\Users\Administrator> scoop uninstall innounp
Uninstalling 'innounp' ().
'innounp' was uninstalled.
PS C:\Users\Administrator> scoop install innounp
Installing 'innounp' (0.49) [64bit]
无法连接到远程服务器
URL https://raw.githubusercontent.com/ScoopInstaller/Binary/master/innounp/innounp049.rar is not valid
PS C:\Users\Administrator> Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1
Set-ItemProperty : 不允许所请求的注册表访问权。
所在位置 行:1 字符: 1
+ Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem'  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (HKEY_LOCAL_MACH...trol\FileSystem:String) [Set-ItemProperty], SecurityException
    + FullyQualifiedErrorId : System.Security.SecurityException,Microsoft.PowerShell.Commands.SetItemPropertyCommand

**Comment by neolee** [comment]
和配置指南一样，需要你执行这几个命令：

```powershell
Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1
scoop install innounp 
```

前一个执行失败是因为权限，你可以试试打开一个管理员权限的命令行 {{ PowerShell (Admin) }} 来执行试试。

后一个执行失败是之前有装过 innounp 包，但可能没装好，试试：

```powershell
scoop uninstall innounp
scoop install innounp
```

**Comment by fengsuizhi** [comment]
谢谢老师，第一个问题解决了，第二个在我执行了那两个命令后任然显示为：
无法连接到远程服务器
URL https://raw.githubusercontent.com/ScoopInstaller/Binary/master/innounp/innounp049.rar is not valid

**Comment by neolee** [comment]
多试几次，或者换网或者挂代理试试。
