### ISSUE TITLE
安装 Visual Studio Code，输入code.时遇到的问题

### ISSUE THREAD

**Issue by fengsuizhi** [neolee/pilot#377]
![image](https://user-images.githubusercontent.com/53424045/68211333-56915d80-0012-11ea-8f55-8ec44e6e03d1.png)

**Comment by tianzhansheng321** [comment]
如果安装好的话，关掉conemu然后再打开，在输入cd code，回车后再输入code . 应该就可以了。你试试，我的就是这样的。

**Comment by neolee** [comment]
`code` 和 `.` 之间漏了个句号。这是之间完全可以解决的问题。
