### ISSUE TITLE
执行 scoop update 和 scoop install git 不成功 `Cannot validate argument on parameter 'FilePath'`

### ISSUE THREAD

**Issue by banshibao** [neolee/pilot#38]
运行scoop update和安装三个软件包情况截图如下：

![2019-10-23_235034](https://user-images.githubusercontent.com/24274761/67411326-0a94f080-f5f0-11e9-9c43-923a83c8edee.jpg)

**Comment by Dreamzd** [comment]
我也是

**Comment by xbq1022** [comment]
可以看下#33号问题，个人建议先重启试试。

**Comment by xbq1022** [comment]
@banshibao 你这个是要先运行“scoop install git”

**Comment by neolee** [comment]
请参考 #33

**Comment by JS-luo** [comment]
> 请参考[＃33](https://github.com/neolee/pilot/issues/33)

老师，我安装 scoop install git 一直超时，能在网页上直接下载一个安装包吗？

**Comment by neolee** [comment]
可以试试。
