### ISSUE TITLE
重新做的系统，也用了科学上网，还是显示连接不到远程服务器！

### ISSUE THREAD

**Issue by yaoce** [neolee/pilot#380]

**Comment by yaoce** [comment]
不知道如何发图片。
就是安装scoop的时候。
PS C:\Users\yaoce> iwr -used get.scoop.sh | iex
iwr : 无法连接到远程服务器
所在位置 行:1 字符: 1
+ iwr -used get.scoop.sh | iex
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest)
    [Invoke-WebRequest]，WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.
   InvokeWebRequestCommand

**Comment by neolee** [comment]
首先这个命令没写对，自己仔细核对下吧。

然后发图片的方法 Wiki 里有。
