### ISSUE TITLE
录入type(42）后，没有运行结果！

### ISSUE THREAD

**Issue by tigersummer** [neolee/pilot#381]
![Cutter_2019-11-05 10_22_](https://user-images.githubusercontent.com/48619978/68216321-ae809200-001b-11ea-926a-e9a4cd811076.png)

**Comment by bustlion** [comment]
运行是在 visual studio code 里面输入， 然后做你需要的各种测试。

print(type(42))

**Comment by tigersummer** [comment]
我想表达的意思是：我在jupyterlab中打开学习用书，可在输入指令时，没有出现对应的运行结果。
例如;我输入了type（42），随后应该会自动生成“int”，但我输入后，没有自动生成任何结果。

**Comment by Kokicoco** [comment]
这个问题我可以试着回答：
你以为在学习用书里面输入type(42)之后应该自动出现“int”，但实际上是需要你先在VSCode中输入print(type(42))，然后到ConEmu窗口去运行，具体步骤如下：
运行VSCode（从开始菜单或者命令行都可以）， ⌃+N 打开一个新文件，输入print(type(42))，然后按 ⌃+S 保存，文件命名为例如structure-1.py，回到 ConEmu 窗口，运行：python structure-1.py

新手，不知道回答的是否足够准确。

**Comment by neolee** [comment]
@tigersummer 1. 在单元格里输入代码之后需要按 Control+回车 才会执行代码给出结果；
2. 似乎括号不太对，是不是用了中文括号？
