### ISSUE TITLE
续问：环境配置的时候出现了几处小白问题 (#361)

### ISSUE THREAD

**Issue by DorisChenWen** [neolee/pilot#382]
不好意思，老师，单亲妈妈在德国“丧偶式”带一岁半娃，以至于没有足够的时间连续操作直到问题结束，昨天提的问题除了第一个问题其他都解决了。输入 cp ~/.bash_profile.pysave ~/.bash_profile，出现了如下问题。不知是否跟我曾经执行过一个删除命令有关。这个命令是这样的：rm '/usr/local/bin/2to3'  执行这个命令是因为安装python的时候出现警告，然后我看到它弹出来的建议我就照做了，隐隐觉得好像做错了的样子。

![Screen Shot 2019-11-05 at 15 40 46](https://user-images.githubusercontent.com/48721070/68217302-ac4e1180-ffe2-11e9-9e4c-0b3080b10a30.png)

**Comment by neolee** [comment]
你完全可以接着 #361 继续，超过一天无回应的 issue 我会关闭，如果还有问题你再打开就行了。

你说的这个问题，按照你的 `.bash_profile` 里的内容，说有一个备份的文件叫 `.bash_profile.pysave`，但你实际执行的时候并没有这个备份文件。不过问题不大，你可以直接把 `.bash_profile` 改个名字就行了，比如 `mv ~/.bash_profile ~/.bash_profile.backup`。

**Comment by DorisChenWen** [comment]
谢谢老师，这样一来第一个问题也解决了。
