### ISSUE TITLE
差点没挺过来！同志们加油！！！

### ISSUE THREAD

**Issue by tangwendong** [neolee/pilot#384]
刚开始按照“编程环境配置指南”做的时候挺顺利的，power shell搞定了，ConEmu装好了，scoop也装好了，看起来一切正常。紧接着安装好了python，输入python -V后没有任何反应，我找到了这个issue

https://github.com/neolee/pilot/issues/139

在C:\Users\Tang\scoop\shims文件中找到python.exe双击之后出现提示：“无法启动此程序，因为计算机中丢失api-ms-win-crt-runtime|1-1-0.dll。尝试重新安装该程序以解决此问题。”

我花了不少时间在网上下载了这个文件，放在“C:\Windows\System32”里面（我是win7的64位系统），试了下还是不行。

我以为是提供下载的网站不靠谱（下载的时候没得选，不知道是给64位系统用还是给32位系统用），所以文件不对。因此又花了很长时间找可以下载的网址。我找到了微软官网上的下载链接，但链接已经失效。

准备放在“C:\Windows\SysWOW64”里试一下，结果发现这个文件夹中本来就有api-ms-win-crt-runtime|1-1-0.dll文件。于是我把这个.dll文件复制了一份放在C:\Windows\System32中。

竟然就这样成功了。然鹅，只成功了一次。

当我再次使用powershell输入python -V后依然没有反应。

重新双击C:\Users\Tang\scoop\shims文件夹中python.exe，弹出提示："应用程序无法正常启动0xc000007b"。一番翻来复去搜索之后，发现网友给出的解决办法比刚才的dll缺失还复杂。安装了DirectX，没用。

其实这个时候我应该问在这里来提问。

网友写的文章对我来说有点儿复杂了，但有文章说win7系统的补丁中自带api-ms-win-crt-runtime|1-1-0.dll文件。我想，虽然dll文件缺失已经解决了，兴许这个0xc000007b也可以这样解决。

使用windows update，我搜到了68个重要更新。全部安装之后，真的OK 了。

说起来好像不复杂，但解决起来真的不简单。我现在已经开始正式学习了。

还有个问题：scoop install innounp命令始终执行不成功，innounp也没安装成功，但到目前为止似乎不影响其他功能的使用；这个innounp可以不安装吗？

**Comment by neolee** [comment]
innounp 不是必须，但是最好装上。
