### ISSUE TITLE
小白问题：输入命令安装Scoop 显示“无法连接远程服务器”

### ISSUE THREAD

**Issue by meiwuduedu** [neolee/pilot#385]
老师好：
    我刚开始学编程，这个问题可能太小白了，可是我真不知道是什么原因，谢谢老师！
      1. 动作：
在ConEmu 的 PowerShell 命令行界面下输入 PS C:\Users\84185> iwr -useb get.scoop.sh | iex 

     2.报错显示如下：
iwr : 无法连接到远程服务器
所在位置 行:1 字符: 1
 + iwr -useb get.scoop.sh | iex
 + ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebReques
  t:HttpWebRequest) [Invoke-WebRequest]，WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.Pow
   erShell.Commands.InvokeWebRequest

Command

**Comment by neolee** [comment]
网络问题，换个网络或者挂代理试试。
