### ISSUE TITLE
iwr : 未能解析此远程名称: 'get.scoop.sh'

### ISSUE THREAD

**Issue by bennet569** [neolee/pilot#386]
安装scoop时 ，一开始报错 无法连接远程服务器，后来我修改了电脑的“远程设置”，更改为“允许远程连接到此计算机”，然后重启，出现了iwr : 未能解析此远程名称: 'get.scoop.sh'，图片如下：

iwr : 未能解析此远程名称: 'get.scoop.sh'
所在位置 行:1 字符: 1
+ iwr -useb get.scoop.sh | iex
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:Htt
   pWebRequest) [Invoke-WebRequest]，WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShe
   ll.Commands.InvokeWebRequestCommand

**Comment by neolee** [comment]
你改的那个设置和问题没啥关系，你其实不应该打开那个开关，那个是允许别的机器远程控制你的电脑，通常最好不开。

你的问题就是网络的问题，你的网络没法顺利访问安装 Scoop 所需要的服务，换网络或挂代理试试。

**Comment by scil** [comment]
I encouter similar error, I use another powershell installed from microsoft store, and `iwr -useb baidu.com` worked well, and scoop     works well.
