### ISSUE TITLE
while 循环语句中，“while True 的循环语句是固定真值”应该如何理解呢？

### ISSUE THREAD

**Issue by bustlion** [neolee/pilot#387]
from random import randrange # 章节：程序的基本结构（四）：循环

**while True:**

    n = randrange(-2, 5) 
    if n < 0:
        break
    elif n % 2 == 0:
        print(n, 'is even')
    else:
        print(n, 'is odd')

### 不理解的地方是：“注意上面 while 的循环条件是**固定真值**，所以后面的循环体会一直循环执行。” 这句话。  
问题1： 固定真值应该如何理解呢？ # 查询百度得知：数的形式值就不等于真正的数值，带符号位的机器数对应的数值称为机器数的真值。 —— 我理解不了这段话。

感谢李老师~

**Comment by best-way** [comment]
百度那句话我也不是特别理解；固定真值我的理解是判断的表达式的结果已经是固定的了，比如表达式直接是单个bool值（true或者false），或者类似4>3（返回值是一定确定是true的）这种表达式；
while true 我的理解是，循环的判断条件永远正确，是一个死循环，只用执行到break这个语句才会跳出循环，就上面那个例子来说，随机数要随到负数，就会进入if里执行break跳出死循环；可以和while false对比来理解，while false 就是while后面的条件永远为假，程序根本不会进入到while这个循环体
