### ISSUE TITLE
安装 Visual Studio Code 后执行 code . 出错

### ISSUE THREAD

**Issue by imagelan** [neolee/pilot#39]
你好！
code . 运行出错。

![image](https://user-images.githubusercontent.com/48951128/67447210-cb0eda00-f5d8-11e9-8cb9-ea0021ab505d.png)

**Comment by neolee** [comment]
`code` 和后面的 `.` 之间要有空格。

`code <目录或者文件>`

`.` 是个特殊目录，代表当前的目录。
