### ISSUE TITLE
运行 python -m pip install --upgrade pip 时出现问题

### ISSUE THREAD

**Issue by DorisChenWen** [neolee/pilot#390]
![Screen Shot 2019-11-05 at 23 25 54](https://user-images.githubusercontent.com/48721070/68251555-b2b0ad80-0023-11ea-89c4-c9fc36a1d7ac.png)

**Comment by neolee** [comment]
跑一下下面几个命令：

```shell
which python
which python3
which pip
which pip3
pip -V
pip3 -V
```

很可能你需要执行的是：

```shell
python3 -m pip install -U pip
pip3 install jupyterlab
```

上面有个 SSL 证书问题，不过先解决上面几个再说。

**Comment by DorisChenWen** [comment]
跑了上面六行命令，又跑了老师预测的可能需要执行的命令，全中！环境配置成功啦，去jupyter lab看书去了～谢谢老师。
