### ISSUE TITLE
安装 toc 插件报错信息

### ISSUE THREAD

**Issue by wulemon78** [neolee/pilot#391]
Building jupyterlab assets (build:prod:minimize)
An error occured.
RuntimeError: JupyterLab failed to build
See the log file for details:  C:\Users\ADMINI~1\AppData\Local\Temp\jupyterlab-debug-uuqs94o9.log

启动jupyterlab，发现插件已经有了，这是安装成功了吗

**Comment by neolee** [comment]
不确定，可能有点问题，你打开上面给出的那个 log 文件看看：

`code C:\Users\ADMINI~1\AppData\Local\Temp\jupyterlab-debug-uuqs94o9.log`
