### ISSUE TITLE
macOS 因为版本低不能安装 Xcode 

### ISSUE THREAD

**Issue by yuanhui20190909** [neolee/pilot#392]
<img width="559" alt="屏幕快照 2019-11-05 下午11 40 21" src="https://user-images.githubusercontent.com/57423228/68260335-b2da9880-0077-11ea-87d3-9075066a9669.png">
<img width="571" alt="屏幕快照 2019-11-05 下午11 40 34" src="https://user-images.githubusercontent.com/57423228/68260341-b9691000-0077-11ea-95e9-e7de411d7fc3.png">
<img width="371" alt="屏幕快照 2019-11-06 上午9 29 51" src="https://user-images.githubusercontent.com/57423228/68260441-05b45000-0078-11ea-81fc-f85aabd87e18.png">

试过了Mac升级，下载了10.14.1说要求要10.14以上；是不是要去下载和10.12对应的版本

**Comment by neolee** [comment]
如果决定升级 macOS，就去 App Store 搜 macOS，直接下载最新的安装器。

10.12 三年前的，其实按理说应该还行，但是确实 Homebrew 不提供官方支持了，所以如果可能还是升吧。
