### ISSUE TITLE
‘学习用书和教材的区别只有一个：教材中所有写着程序代码的段落都被清空了，等着你自己动手填进去。’→‘学习用书和教材的区别只有一个：学习用书中所有写着程序代码的段落都被清空了，等着你自己动手填进去。’

### ISSUE THREAD

**Issue by xiaoerhai** [neolee/pilot#393]
具体定位：
进入编程世界的第一课  中的   自学

（没记错的话我应该是第三次从头再看了（说明李骏老师写的内容真的很值得重复看），标题中的这句话我反复读了好几次，当时的目的是想搞清楚什么是‘学习用书’和什么是‘教材’，前面2次觉得懂大意了就直接跳过了。这次我想我是弄明白了。）

提交这个issue的时候又读了几遍这句话，好像也没什么问题。。。

**Comment by neolee** [comment]
嗯，这句话确实有歧义，我想想怎么改好一点，多谢指出~
