### ISSUE TITLE
‘记得选择 question 这个 label（如果提的是关于课程教材中的错误或者改进建议可以选择 bug 或者 enhancement 这样的 label）。’这句话实际操作是什么样的？

### ISSUE THREAD

**Issue by xiaoerhai** [neolee/pilot#395]
实操后得知：
1）先点【New issue】 的话是没有label可选的；
2）先点【labels】的话即使是选了对应的类型，提交issue之后也不会打上对应的标签。

**Comment by neolee** [comment]
是么？我这里是可以的，不知道是不是只有 contributor 才能这么操作……

<img width="1066" alt="New Issue" src="https://user-images.githubusercontent.com/24796/68265605-80d13280-0087-11ea-8406-8f531c0bd30c.png">
