### ISSUE TITLE
8-oo-2章-“多态”小节有一句“可以 override 这个方法的实现”似应改为“可以 override 这个方法来实现”为宜

### ISSUE THREAD

**Issue by zhigang-he** [neolee/pilot#396]
如下图：

![图片](https://user-images.githubusercontent.com/49590371/68263133-2aacc100-0080-11ea-9d38-7d4e1e73a9e8.png)

**Comment by neolee** [comment]
这句话就是它字面的意思，当然你改的那句也对，意思不太一样。
