### ISSUE TITLE
如何在 Issues 中贴图？

### ISSUE THREAD

**Issue by xiaoerhai** [neolee/pilot#397]
wiki里是的答案：
拷贝图片，直接在输入框中粘贴；或者将图片文件拖到输入框中。输入框中会显示 “Uploading pic...”，等这句话变成 <img src=...> 的一串再提交。

昨天我操作成功过一次，当时以为是一定要保存后再复制粘贴，不能截图粘贴。但今天又碰到无法贴图的问题了。输入框一直没有变成 <img src=...> 的一串：
1）不做任何动作，输入框一直显示‘Leave a comment’;
2）如果把图片拖进去，会出现：![Uploading issue.png…]()  ，然后等会就消失了。一直这样进入死循环。

**Comment by neolee** [comment]
按理那句 Uploading 的提示不应该消失，而应该变成自动生成的插入图片的代码，如果没有，不知道是不是上传没成功，我没碰到过。

**Comment by MonsterWong** [comment]
![image](https://user-images.githubusercontent.com/40250312/68312421-51381f80-00b3-11ea-8cb1-b725aca7f6da.png)
无法复现你描述的问题，看描述像是网络连接出了问题，导致图片上传失败。你看我截图中你上传的图片，都失败了。

**Comment by xiaoerhai** [comment]
> 换个浏览器试一下 如 google
> 
> 今天也遇到了同样的问题，一开始用的是safari 浏览器，然后我想换Google浏览器试一下看是不是浏览器的问题。结果用google果然可以贴图了。

我一直用的是谷歌，我已经找到问题了，是网络的原因。谢谢解答哈。
