### ISSUE TITLE
关于__init__ 函数疑惑

### ISSUE THREAD

**Issue by Winsi0n** [neolee/pilot#398]
在网上搜索学习__init__函数时，在CSDN 上看到以下这段代码：

class TelePhone():
      
    def __init__(self):
        self.lag='english'
        print ('默认语言是英文') 
              
    def __init__(self, lag):
        self.lag=lag
        print ('默认语言设置为',lag)
           
TelePhone()

------------------------------------------------------------------------

个人理解是想在没有输入参数时，默认为英语。自己试着跑了下并不能实现。会提示缺失参数。

请教老师：

    一个方法里能不能有两个__init__？
    这段代码有什么问题呢？

**Comment by neolee** [comment]
这段代码的品味糟透了，1. 代码风格（空格等）不符合 PEP8 的要求；2. “语言”，应该是 *language*，简单点可以用 *lang*，从来没见过用 *lag* 的，*lag* 的意思是“延迟”；3. 如果要实现你设想的功能，最简单的办法是用带缺省值的参数，一个版本的 `__init__` 就可以了：

```python
def __init__(self, lang='english'):
    self.lang = lang
    print('默认语言设置为', lang)
```

回到你的问题，一个类里能不能有两个 `__init__`？答案是：不可以，只能有一个。

**Comment by Winsi0n** [comment]
学到了！！！刚好对应昨晚课的内容——品味很重要！

>_<
