### ISSUE TITLE
git push 失败

### ISSUE THREAD

**Issue by onthebus98** [neolee/pilot#399]
在家里的mac电脑push 成功了。在办公室配置好的win10电脑里执行git push 命令时总是失败。过程如下：
S C:\Users\lm\code\pilot-student> git add 5-structure-4.ipynb
warning: LF will be replaced by CRLF in 5-structure-4.ipynb.
The file will have its original line endings in your working directory
PS C:\Users\lm\code\pilot-student> git commit 5-structure-4.ipynb
warning: LF will be replaced by CRLF in 5-structure-4.ipynb.
The file will have its original line endings in your working directory
[master c89f974] ver。1.1
 1 file changed, 3 insertions(+), 2 deletions(-)

PS C:\Users\lm\code\pilot-student> git push 5-structure-4.ipynb
fatal: invalid gitfile format: 5-structure-4.ipynb
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by neolee** [comment]
`git push` 后面不需要文件名，push 的是 git 的数据（分支），所以你执行 `git push` 就行了。
