### ISSUE TITLE
执行 scoop update 的 `error: RPC failed` 错误

### ISSUE THREAD

**Issue by kevinlmmx** [neolee/pilot#4]
安装好scoop后，运行scoop update指令，系统给出如下提示：

PS C:\Users\29164> scoop update
scoop : 无法将“scoop”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检
查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ scoop update
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (scoop:String) [], CommandNotFou
   ndException
    + FullyQualifiedErrorId : CommandNotFoundException

已尝试在系统变量的 Path 中添加了以下3条指令：
C:\Users\29164\AppData\Local\Programs\Python\Python37\python.exe
C:\Users\29164\AppData\Roaming
C:\Users\29164\scoop

问题依然存在，请问该如何解决？谢谢。

**Comment by neolee** [comment]
如果 scoop 安装成功，是不需要自己添加路径的，请问你安装 scoop 时有报什么错误吗？

**Comment by kevinlmmx** [comment]
删除 scoop 重新安装后，运行 scoop update 指令又出现新的问题：

PS C:\Users\29164> scoop update
Updating Scoop...
error: RPC failed; curl 56 OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 10054
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
Scoop update failed.

求教该如何解决，谢谢。

**Comment by neolee** [comment]
这个是网络问题，你可以等一下再试试。

**Comment by neolee** [comment]
Duplicate of #7
