### ISSUE TITLE
安装 Scoop 和 git 出现 `fatal: open /dev/null or dup failed`

### ISSUE THREAD

**Issue by zhangSen1987** [neolee/pilot#40]
PS C:\Users\Administrator> Get-ExecutionPolicy
RemoteSigned
PS C:\Users\Administrator> Set-ExecutionPolicy RemoteSigned -scope CurrentUser
PS C:\Users\Administrator> iwr -useb get.scoop.sh | iex
Initializing...
Scoop is already installed. Run 'scoop update' to get the latest version.
PS C:\Users\Administrator> scoop update
scoop : 无法将“scoop”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径
，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ scoop update
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (scoop:String) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\Administrator>

**Comment by neolee** [comment]
首先，遇到 Scoop 的问题，一般都和 ConEmu 无关，除非 ConEmu 运行不起来，否则都不用折腾它，运行 ComEmu，进入 PowerShell 的界面（行提示符最开始有 PS 字样）就行了——注意 PowerShell 的版本要大于等于 5。

然后，你的 Scoop 没有装好，需要重装，依次运行下面四行命令：
```shell
cd
del .\scoop -Force
Set-ExecutionPolicy RemoteSigned -scope CurrentUser
iwr -useb get.scoop.sh | iex
```

然后运行 `scoop update` 无错误，才可以继续。

**Comment by zhangSen1987** [comment]
![update 错误](https://user-images.githubusercontent.com/53714512/67450710-e0274f80-f650-11e9-902a-e5a15199bbf9.jpg)
谢谢马老师，现在成了这个错误

**Comment by neolee** [comment]
你是按照我前面给你的四个命令一个个执行的吗？过程中有没有什么错误？

截屏里有一个 git 的错误（`fatal: open /dev/null or dup failed`）。

**Comment by zhangSen1987** [comment]
> 你是按照我前面给你的四个命令一个个执行的吗？过程中有没有什么错误？
> 
> 截屏里有一个 git 的错误（`fatal: open /dev/null or dup failed`）。

李老师，我刚才Google了一下，说是系统的null,sys 文件损坏了，让下了个null.sys 文件替换了，现在update成功了，正在安装Python37，不知道这样行不行。

**Comment by neolee** [comment]
这个问题似乎在老一点的 Windows 上还比较多见，比如：

https://blog.csdn.net/zhouyingge1104/article/details/79433257

如果你 update 无误，应该就是好了，先继续吧。

**Comment by zhangSen1987** [comment]
> 这个问题似乎在老一点的 Windows 上还比较多见，比如：
> 
> https://blog.csdn.net/zhouyingge1104/article/details/79433257
> 
> 如果你 update 无误，应该就是好了，先继续吧。

![Python安装错误](https://user-images.githubusercontent.com/53714512/67453489-5f208600-f659-11e9-9032-6b2a797e15d6.jpg)
麻烦李老师指导下，谢谢！

**Comment by neolee** [comment]
网络问题，Python 安装包没下完，重新试。

**Comment by zhangSen1987** [comment]
![lab错误](https://user-images.githubusercontent.com/53714512/67456652-0d312d80-f664-11e9-967a-f2fe331402dd.jpg)
李老师，安装jupyterlab 老是安装一点就出错，用 pip3 install jupyterlab 命令安装 也是一样，这个怎么解决？

**Comment by neolee** [comment]
你的 Scoop Python 和 pip 都是好的，这个错误应该是网络问题，下载 Jupyter Lab 包没成功，多试几次吧。

**Comment by neolee** [comment]
原问题已经解决，如果还有新的问题请新开 issue。
