### ISSUE TITLE
对话机器人主程序中的各个 Bot 的调用问题

### ISSUE THREAD

**Issue by Jared-Gong** [neolee/pilot#400]
![1573011107(1)](https://user-images.githubusercontent.com/56901849/68266261-8760a980-0089-11ea-8dc3-66c9a4d827e8.png)
问题1、为啥不能使用return 呢？用return后面的print语句也不能执行。
问题2、jenny=Jenny()括号中的参数 是不是任意参数都可以？
问题3、各个Bot是如何调用进主流程Jenny中的?老师可以详细的说下吗？

**Comment by neolee** [comment]
下面是教材中最基本的版本：

```python
class Garfield:
    
    def __init__(self, wait=1):
        Bot.wait = wait
        self.bots = []

    def add(self, bot):
        self.bots.append(bot)

    def _prompt(self, s):
        print(s)
        print()

    def run(self):
        self._prompt("This is Garfield dialog system. Let's talk.")
        for bot in self.bots:
            bot.run()
```

在开始自己尝试改动之前，一定要先充分理解这个基础版本。你的几个问题：
1. 你需要理解 `_prompt()` 这个方法是做什么的，它的目的就是输出一句提示，并且空一行，所以必然是通过 `print()` 函数来实现，`return` 做不到呀；
2. 类实例化时传入的是 `wait` 这个变量，它会用来初始化 `Bot` 类的类变量 `Bot.wait` 的值，这个值控制每次 bot 说话前的延迟时间（这个延迟时间是为了让对话看起来更像真人）；好的程序里每个变量都是由自己的含义和作用的，不可能存在“任意参数都可以”这种情况吧；
3. 这个就涉及到这个程序设计时的总体结构了，到时候听课吧。

**Comment by Jared-Gong** [comment]
1、我明白_prompt()方法的作用，后面还print（中文）。我只是依照前面_think()函数下return f"{s}试下能否通过return输入一句提示语就好，不要空行其他的。截图中应该是return f"{s}”但试过，也不行。
2、在Jenny（）中输入10的时候，感觉还是1秒的感觉（刚刚试试居然可以10秒了）。另外我是想提示英文之后，各几秒再说个中文，这个时间间隔是自己再定义的。
3、好的，再理解琢磨下吧。

**Comment by Jared-Gong** [comment]
第一个问题，我想明白了，return的返回值要靠print输出，_think()下面的return 再class Bot里面有执行print，而_prompt没有，所以用了return是显示不出来的，要用print()才行。另外我发现，一个函数体内有print 而没有return，结果会print出一个None。算是解开了疑惑，哈哈哈哈哈。
