### ISSUE TITLE
安装环境

### ISSUE THREAD

**Issue by qianduoduo712616** [neolee/pilot#404]
老师，我的电脑是window 6的版本，没办法安装management framework 5，是不是最低版本都要win7的？谢谢您！

**Comment by neolee** [comment]
最好用 Windows 10。

**Comment by qianduoduo712616** [comment]
好的，谢谢您，李老师！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Neo Lee"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月6日(星期三) 下午3:33
收件人:&nbsp;"neolee/pilot"<pilot@noreply.github.com&gt;;
抄送:&nbsp;"陌上花开"<55937940@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [neolee/pilot] 安装环境 (#404)




最好用 Windows 10。
