### ISSUE TITLE
下载并执行 Homebrew 的安装脚本时出错，小白求救

### ISSUE THREAD

**Issue by huangzhangwei** [neolee/pilot#405]
配置环境时，在输入：/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" ↩︎后，半天没反应，过一会出现以下内容。
curl: (7) Failed to connect to raw.githubusercontent.com port 443: Operation timed out
请问是啥原因？零基础小白第一配置卡在这里了。

**Comment by neolee** [comment]
网络问题。换网或者挂代理。

**Comment by huangzhangwei** [comment]
怎么挂代理啊？
