### ISSUE TITLE
输入 jupyter lab 之后提示 command not found

### ISSUE THREAD

**Issue by maomaomizi** [neolee/pilot#406]
图还是没法贴 屏幕快照 2019-11-06 下午2.16.56    文件夹没有选错 也成功的下载学习用书到了本地 就是在输入jupyter lab 之后显示命令未发现

**Comment by neolee** [comment]
没有系统环境的说明，没有截图，无法判断。

**Comment by maomaomizi** [comment]
查看了 别人提出的类似的问题，发现可能是自己 jupyter lab 没有装好，又重新装了一下 终于可以了 ，这次吸取的教训是，在做每一步的时候都不能含糊，否则后面早晚会出现问题，之前装lab环境的时候 出现了红字 也没有注意 以为装好了，就往后面流程继续了，结果就卡住了。

**Comment by neolee** [comment]
Nice. Keep going.
