### ISSUE TITLE
Windows 系统 jupyterlab 安装 toc 插件失败

### ISSUE THREAD

**Issue by jiaowagn** [neolee/pilot#408]
![screencapture-file-C-Users-ADMINI-1-AppData-Local-Temp-jupyterlab-debug-wm2l8fwu-log-2019-11-06-17_36_13](https://user-images.githubusercontent.com/24514390/68286696-7b420f80-00bc-11ea-99a2-1675751ecad0.png)

![image](https://user-images.githubusercontent.com/24514390/68287654-0b348900-00be-11ea-88f0-c370fee9049d.png)

**Comment by jiaowagn** [comment]
google 搜索 ‘Error: spawnSync webpack ENOENT’，没有发现解决办法。李骏老师，您觉得我可以按照什么思路去解决这个问题？

**Comment by neolee** [comment]
截图最后给出的那个 log 文件内容是什么？（可以用 `code C:\Users...` 来打开那个文件看看）

**Comment by jiaowagn** [comment]
![928835571](https://user-images.githubusercontent.com/24514390/68352184-98b8bd00-0140-11ea-9a77-5dec056e4c72.jpg)

**Comment by jiaowagn** [comment]
![1667003058](https://user-images.githubusercontent.com/24514390/68352701-3eb8f700-0142-11ea-90fd-aa0534b676be.jpg)

**Comment by jiaowagn** [comment]
李老师，以上是 log 内容

**Comment by neolee** [comment]
这个问题有点怪，我需要研究下，晚些答复。

**Comment by neolee** [comment]
我找到一个可能有关的 issue：https://github.com/jupyterlab/jupyterlab/issues/7425

首先，主要错误信息是 `spawnSync webpack ENOENT`，而这个错误可能的原因非常多，我们需要排除几个可能性：

1. 你的 Windows 是 32 还是 64 位？用 `wmic OS get OSArchitecture` 命令可以看到；

2. 执行下面几个命令可以显示 Jupyter Lab 主要组件的版本：
```powershell
jupyter --version
pip list --outdated
```

**Comment by jiaowagn** [comment]
![image](https://user-images.githubusercontent.com/24514390/68367890-b05c6980-0171-11ea-9278-be65c214def4.png)

**Comment by jiaowagn** [comment]
我的电脑是 Windows 7,64 位。您提到的相关 issue，之前我看到过，不过没有找到相关解决办法。

**Comment by neolee** [comment]
看上去一切都 OK，目前 Jupyter Lab 运行正常么？如果正常就先不要安装那个插件了吧，并非必须。
感觉比较像 Jupyter Lab 某些特定情况下的 bug。

**Comment by jiaowagn** [comment]
好的，谢谢李老师。 Jupyter Lab 目前运行正常。

而且，通过 jupyter lab 打开学习用书，在页面弹出的提示框选择 build toc 插件之后，页面 toc 插件功能也可以用。

只是每次执行安装 toc 插件命令之后，就会提示之前那个信息。 

![image](https://user-images.githubusercontent.com/24514390/68374064-14d1f580-017f-11ea-82ca-b663e8ddf51f.png)

**Comment by neolee** [comment]
先不管它，说不定 Jupyter 以后升级就好了……
