### ISSUE TITLE
类定义与对象创建，kind类变量 结果与教材不符

### ISSUE THREAD

**Issue by reganhsl** [neolee/pilot#409]
<img width="649" alt="图片2" src="https://user-images.githubusercontent.com/48468031/68295073-8604a080-00cc-11ea-947b-4f4960931f14.png">

代码和教材相同的情况下，得出的结果是两个上引号，图上。
可能是哪些问题？要做哪些修正？

**Comment by reganhsl** [comment]
找到原因了！Dog类定义的时候，kind = ‘ ’，引号里面要加上 canidae 。

**Comment by Yoursman** [comment]
我也遇到了一样的问题，按照你的方法还是没有解决，请问能解释的更详细一些吗？

**Comment by Yoursman** [comment]
我也遇到了一样的问题，按照你的方法还是没有解决，请问能解释的更详细一些吗？

**Comment by reganhsl** [comment]
这章的第一段代码中，class Dog：下面一行是kind = ‘canidae’。
