### ISSUE TITLE
运行 python hello.py 出错：can't open file 'hello.py'

### ISSUE THREAD

**Issue by imagelan** [neolee/pilot#41]
你好！
hello.py 存在 thisPC > MY ROOM (D:) 下面。不知道是不是这个原因ConEmu 不能运行。
谢谢！

![image](https://user-images.githubusercontent.com/48951128/67447374-41134100-f5d9-11e9-880a-96546223a3d4.png)

![image](https://user-images.githubusercontent.com/48951128/67447474-9b140680-f5d9-11e9-9976-6d8b3c794cc9.png)

**Comment by neolee** [comment]
一些基本概念：

1. ConEmu 只是个命令行界面，一般问题都不会和它有关，除非它本身运行不起来。
2. 列出当前目录下的所有内容的命令是 `ls`，两个英文小写字母，是 *list* 的缩写，不是 `1s`。
3. `python <文件名.py>` 这个命令的意思是，让 Python 运行后面的这个源代码文件，所以 Python 要找得到这个文件呀，你在 `C:\Users\kun\code` 下面运行 `python hello.py`，但是当前目录（PS 提示符后面就是当前目录，`C:\Users\kun\code`）下并没有这个文件，那就出错了（`No such file or directory`）。

你有两个办法运行这个程序，第一个是进入它所在的目录，然后运行：
```shell
cd 'D:\10 Peng\Coding'
python hello.py
```

第二个办法是在任何地方运行，但是指定完整的文件路径：
```shell
python 'D:\10 Peng\Coding\hello.py'
```

一般来说在你的工作目录里干活比较好，所以第一个方案较好。
