### ISSUE TITLE
无法 update scoop

### ISSUE THREAD

**Issue by wendyyouthbaby** [neolee/pilot#410]
'git' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
Scoop update failed.
ERROR It looks like a previous installation of dark failed.
Run 'scoop uninstall dark' before retrying the install.
WARN  'dark' () is already installed.
Use 'scoop update dark' to install a new version.

**Comment by neolee** [comment]
先试着吧问题说清楚：你做了什么，期望得到什么结果，实际上除了什么错？

最好有截图。

**Comment by jiushijiushi** [comment]
安装编程环境过程中，我进行到“安装Scoop”中的三个命令：
1、scoop list
2、scoop install git
3、scoop update
运行命令3时，显示update失败。于是我输入“scoop checkup”排错。
反馈如下：
![image](https://user-images.githubusercontent.com/57130322/68310824-9d06bb00-00eb-11ea-979f-a4c447a922d2.png)
我输入程序给的建议“Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1”，得到红字反馈：不允许所请求的注册表访问权。图如下：
![image](https://user-images.githubusercontent.com/57130322/68311026-e5be7400-00eb-11ea-9d3c-7f97ec21bb9a.png)
请问接下来要如何解决呢？

**Comment by neolee** [comment]
可以开一个管理员权限的命令行界面 {{ PowerShell (Admin) }}，然后运行上面那个失败的命令就可以了。

**Comment by jiushijiushi** [comment]
打开管理员权限，运行之后，重新“checkup”，发现没有问题。然后继续“update”，但是还是出错了（出错原因可能如图，没有记录下来），然后觉得可能是scoop出问题了，然后运行“iwr -useb get.scoop.sh | iex”想要重装。  

重装过程中网断了，重装失败。结果导致“check up”都出现问题……出现这种问题怎么解决，继续自由上网重装么：
![image](https://user-images.githubusercontent.com/57130322/68360715-10481580-015c-11ea-8bea-2afa163650fa.png)

**Comment by jiushijiushi** [comment]
已经搜到以往的教程解决，重装之后就没这个问题了
