### ISSUE TITLE
安装 dark 包 failed：无法连接到远程服务器

### ISSUE THREAD

**Issue by wendyyouthbaby** [neolee/pilot#412]
PS C:\Users\Administrator> scoop uninstall dark
Uninstalling 'dark' ().
'dark' was uninstalled.
PS C:\Users\Administrator> scoop install dark
Updating Scoop...
'git' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
Scoop update failed.
Installing 'dark' (3.11.2) [64bit]
无法连接到远程服务器
URL https://raw.githubusercontent.com/ScoopInstaller/Binary/master/dark/dark-3.11.2.zip is not valid

**Comment by neolee** [comment]
先试着吧问题说清楚：你做了什么，期望得到什么结果，实际上除了什么错？

最好有截图。
