### ISSUE TITLE
git commit 出错

### ISSUE THREAD

**Issue by keleyuan** [neolee/pilot#415]
已对git做了基本配置
![image](https://user-images.githubusercontent.com/31580283/68299015-cd435f00-00d5-11ea-987b-22a0b4acec30.png)
进行commit操作时出错
![image](https://user-images.githubusercontent.com/31580283/68299253-4c389780-00d6-11ea-8ba8-dbdad41d2c62.png)

**Comment by xiaoatang** [comment]
@keleyuan 解决了么，我也遇到了同样的问题

**Comment by neolee** [comment]
之前有一些类似的 issue 可以搜下，两个方向可以尝试，一个是 `scoop checkup`，尤其是注意启用 LongPath 这个设置；另一个是清理和重新安装 VSCode。

**Comment by xiaoatang** [comment]
@neolee 分别尝试了你的两个办法，`scoop checkup` 正常，还是会报同样的错误

**Comment by neolee** [comment]
你执行下面命令的返回是什么：

 ```powershell
Get-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled'
```

如果是 `0`，那么需要执行：

```powershell
Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1
```

**Comment by keleyuan** [comment]
按照老师的做法进行了重新安装VSCode，和scoop checkup检查，没有成功。
![image](https://user-images.githubusercontent.com/31580283/68851128-3fd4c000-0710-11ea-8275-36597e7b28f1.png)
返回值是1

**Comment by neolee** [comment]
@keleyuan @xiaoatang 

这个问题我研究了一阵子了，还是没啥进展，所以目前建议直接用 `git commit -m '提交说明信息'` 的方法来绕过。
