### ISSUE TITLE
Mac 系统下载安装 Visual Studio Code 后按照配置内容说明配置了 >install 然后终端输入code . 无法打开 VScode

### ISSUE THREAD

**Issue by tsao86** [neolee/pilot#418]
<img width="637" alt="屏幕快照 2019-11-06 下午9 56 34" src="https://user-images.githubusercontent.com/49138260/68304551-eef61380-00e0-11ea-9893-6b8b4a5ffe7a.png">

**Comment by neolee** [comment]
执行 `code .` 后出现什么提示？

**Comment by tsao86** [comment]
<img width="580" alt="屏幕快照 2019-11-07 上午7 02 27" src="https://user-images.githubusercontent.com/49138260/68345597-aa906500-012c-11ea-99ea-80aa54d741ca.png">

**Comment by neolee** [comment]
执行下面几个命令看看：

```shell
echo $PATH
ls -l /usr/local/bin/code*
```

**Comment by tsao86** [comment]
<img width="537" alt="屏幕快照 2019-11-08 下午3 05 32" src="https://user-images.githubusercontent.com/49138260/68456642-4909ec80-0239-11ea-844d-9d6dfe52c0ae.png">

**Comment by neolee** [comment]
你这个 VSCode 怎么在这么奇怪的地方，一般应该在 /Application 下面啊，你确定 VSCode 安装没问题么？

**Comment by tsao86** [comment]
1.从VScode官网下载的MAC版，VScode安装后还执行过“Hello World”命令，运行通畅。
2.跟苹果客服打过电话，第三方下载的软件都会放在用户名下的‘下载’文件夹，用户名下的Application文件夹是空的，所有AppStore下载的软件放在了Macintosh HD的‘应用程序’下。
3.查看过VScode.app应用程序，是在个人用户下的‘下载’文件夹里面。

**Comment by neolee** [comment]
你需要把 VSCode.app 拖到 Applications 目录下，才能正常工作。

**Comment by nanadu-tech** [comment]
vsc里显示code已经成功安装。但在terminal命令行里输入code显示NameError
<img width="760" alt="屏幕快照 2019-11-12 下午11 17 33" src="https://user-images.githubusercontent.com/57665028/68685035-7392d700-05a4-11ea-82d4-2be266126fbf.png">

<img width="594" alt="屏幕快照 2019-11-12 下午11 16 58" src="https://user-images.githubusercontent.com/57665028/68685417-121f3800-05a5-11ea-93d3-da5674d98021.png">

**Comment by neolee** [comment]
@nanadu-tech 不要在别人的 issue 下面问不一样的问题。

你的问题是，你为啥在 Python 解释器里输入 `code` 这个命令，这个命令要在命令行环境下输入。
