### ISSUE TITLE
安装 scoop 出错

### ISSUE THREAD

**Issue by mj19871987mj** [neolee/pilot#419]
![QQ截图20191106222104](https://user-images.githubusercontent.com/56118483/68305976-9b38f980-00e3-11ea-8b56-71a3276a8ecb.png)

**Comment by neolee** [comment]
仔细看看你输入的有什么问题。

另外这个问题也不止一次出现过了，搜 issues 也可以找到。

**Comment by bennet569** [comment]
“RemoteSigned”与“-”之间应该有一个空格，是不是这个原因
