### ISSUE TITLE
Scoop 安装后安装软件包失败并提示 Run `scoop install git`

### ISSUE THREAD

**Issue by chepeiling** [neolee/pilot#42]
![MZL29GWO@02`NZG1M0HE}(N](https://user-images.githubusercontent.com/56923109/67447977-380d8880-f648-11e9-9d4c-b8329e717101.png)

**Comment by neolee** [comment]
先运行 `scoop install git`，成功后再运行那几个命令。

**Comment by chepeiling** [comment]
好的，老师运行scoop install git 是不是要好长时间的

**Comment by neolee** [comment]
这个看你的网络，有的网络比较快，有的很慢而且容易断，如果后者的情况，可以尝试换网络或者挂代理试试。

**Comment by chepeiling** [comment]
![WBU{EYJMH$XPS}%@9B2`HSS](https://user-images.githubusercontent.com/56923109/67477723-40d47d80-f68d-11e9-8fd2-0e70fab988a6.png)
你好啊，从下午五点多到现在，一个多小时了，才进度4%，可是网络是可以正常用的

**Comment by neolee** [comment]
因为你的网络访问 git 安装包所在的服务很慢，所以可能需要使用代理或者类似办法。
