### ISSUE TITLE
安装 dark nodejs busybox 等出现 Couldn't find manifest for 'xxxxx'

### ISSUE THREAD

**Issue by cheneyjian** [neolee/pilot#422]
![image](https://user-images.githubusercontent.com/41112569/68344903-15d93780-012b-11ea-8573-1d94a657feb4.png)

**Comment by alittlewhy** [comment]
你执行这个scoop update了么？感觉你前期安装的不够

**Comment by neolee** [comment]
这个现象是 `scoop update` 每执行或者没成功。

**Comment by cheneyjian** [comment]
推到重来以上问题解决了
