### ISSUE TITLE
scoop checkup 说发现3个潜在问题

### ISSUE THREAD

**Issue by nxiaolian** [neolee/pilot#423]
scoop list 排错没问题 ，scoop checkup 排错 说有WARN发现3个潜在问题。但不是红字，可以继续装吗？如果3个潜在问题解决，应该运行什么命令？

PS C:\Users\ASUS> scoop list
Installed apps:

  7zip 19.00
  dark 3.11.2
  git 2.23.0.windows.1
  innounp 0.49
  sudo 0.2018.07.25

PS C:\Users\ASUS> scoop checkup
WARN  Windows Defender may slow down or disrupt installs with realtime scanning.
  Consider running:
    sudo Add-MpPreference -ExclusionPath 'C:\Users\ASUS\scoop'
  (Requires 'sudo' command. Run 'scoop install sudo' if you don't have it.)
WARN  Windows Defender may slow down or disrupt installs with realtime scanning.
  Consider running:
    sudo Add-MpPreference -ExclusionPath 'C:\ProgramData\scoop'
  (Requires 'sudo' command. Run 'scoop install sudo' if you don't have it.)
WARN  LongPaths support is not enabled.
You can enable it with running:
    Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1
WARN  Found 3 potential problems.

 有按要求运行：Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1   

结果提示：
PS C:\Users\ASUS> Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1
Set-ItemProperty : 不允许所请求的注册表访问权。
所在位置 行:1 字符: 1
+ Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem'  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (HKEY_LOCAL_MACH...trol\Fil
   eSystem:String) [Set-ItemProperty], SecurityException
    + FullyQualifiedErrorId : System.Security.SecurityException,Microsoft.P
   owerShell.Commands.SetItemPropertyCommand

**Comment by alittlewhy** [comment]
你选择管理员模式在运行一遍就好了

**Comment by nxiaolian** [comment]
选择管理员模式后，重新运行“安装软件包管理工具 Scoop“  这之后的每一步吗？

**Comment by alittlewhy** [comment]
选择管理员模式后运行Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1
之后进行下面的步骤就行

**Comment by nxiaolian** [comment]
好的，谢谢
