### ISSUE TITLE
李老师，我这里网速太慢了，访问python官网下载软件速度每秒只有几KB，咋办啊？

### ISSUE THREAD

**Issue by xianyuyufang** [neolee/pilot#426]

**Comment by xianyuyufang** [comment]
到现在环境都还没搞定！我请别人帮我下载了一个Python 3.7.4 装到了电脑上，可是运行scoop list 时却显示该文件没有没装好。

另外，请问如何挂代理呢？我在农村，这里的网速相当不好，访问国外的网站慢得像蜗牛！

**Comment by neolee** [comment]
感觉是需要一个代理，具体可以自己上网找一下，这个我们没法提供支持，抱歉。

**Comment by xianyuyufang** [comment]
谢谢李老师，我去试试看。
