### ISSUE TITLE
安装 Scoop 显示无法连接远程服务器是什么情况

### ISSUE THREAD

**Issue by buguoruci1211** [neolee/pilot#427]
安装Scoop显示无法连接远程服务器是什么情况

**Comment by neolee** [comment]
就是……无法连接到服务器啊，换网络或者挂代理再试。

**Comment by buguoruci1211** [comment]
> 就是……无法连接到服务器啊，换网络或者挂代理再试。

正在试，谢谢

**Comment by buguoruci1211** [comment]
> 就是……无法连接到服务器啊，换网络或者挂代理再试。

未果，电脑网络正常，怎么挂代理还没弄懂

**Comment by qixinsame** [comment]
就是尝试换一下VPN的网络线路试试，我自己的VPN之前走新加坡线用Scoop一直有网络问题，换到日本线就一切正常了
