### ISSUE TITLE
更新pip出错

### ISSUE THREAD

**Issue by xbq1022** [neolee/pilot#43]
老师，您好。
在运行 python -m pip install --upgrade pip 出现如下错误，因为之前安装过AMESinm15这个软件，后面删除了，但是这里显示路径还在，这个怎么解决呢？
![image](https://user-images.githubusercontent.com/56924543/67448583-039acc00-f64a-11e9-8ea3-283e79afe732.png)

**Comment by neolee** [comment]
把 AMESim15 那个目录从系统的 Path 环境变量里删除试试？

**Comment by xbq1022** [comment]
> 把 AMESim15 那个目录从系统的 Path 环境变量里删除试试？

用户变量里面的AMESim15删除了，系统环境变量里面没有，但是运行后仍出错。
![image](https://user-images.githubusercontent.com/56924543/67450190-267baf00-f64f-11e9-85e2-90fa0ecd237e.png)

**Comment by xbq1022** [comment]
用户环境变量Path
![image](https://user-images.githubusercontent.com/56924543/67450311-8c683680-f64f-11e9-9cf5-13ee89b35260.png)
系统环境变量Path
![image](https://user-images.githubusercontent.com/56924543/67450338-a6a21480-f64f-11e9-9603-e8bb03feb404.png)

**Comment by neolee** [comment]
先做几个尝试：

1. 执行 `$env:Path` 看看 Path 里面是不是真的没有那个目录了，如果还有可以考虑重启一次试试；
2. 找到 `C:\Users\house\scoop\shims` 目录下的 `python.ps1` 这个文件，用 Visual Studio Code 打开它，看看里面内容是啥。

然后，如果 `$env:Path` 里确认没有那个遗留目录了，而 `python.ps1` 有的话，你当然可以自己改 `python.ps1` 文件，但这样不是很好，因为这个本应该睡 Scoop 维护的东西，所以建议用 Scoop uninstall 然后在 install 一次 python37（我建议装 3.7.4 版本）：

```shell
scoop uninstall python37
scoop install python37@3.7.4
```

**Comment by xbq1022** [comment]
1、应该是没有这个目录了。
![image](https://user-images.githubusercontent.com/56924543/67451076-f7b30800-f651-11e9-809e-f19c927e661b.png)
2、在这个目录下没有找到这个文件.....
![image](https://user-images.githubusercontent.com/56924543/67451098-08fc1480-f652-11e9-823b-fb5198ea1d29.png)
3、卸载Scoop时出错。
![image](https://user-images.githubusercontent.com/56924543/67451195-57a9ae80-f652-11e9-95f0-10d5d754c159.png)

**Comment by neolee** [comment]
卸载是 `scoop uninstall python37` 呀，你漏了最后的 app 名。

**Comment by xbq1022** [comment]
![image](https://user-images.githubusercontent.com/56924543/67451368-b96a1880-f652-11e9-885e-d9d344ad6a55.png)

**Comment by neolee** [comment]
执行一下 `scoop list` 和 `scoop checkup` 看看。

**Comment by xbq1022** [comment]
![image](https://user-images.githubusercontent.com/56924543/67451871-2b8f2d00-f654-11e9-8a79-70620ba36942.png)

**Comment by neolee** [comment]
按照 checkup 的提示，运行这几个命令：

```shell
Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1
scoop install innounp dark
```

然后再试试：

```shell
scoop uninstall python37
scoop install python37@3.7.4
```

**Comment by xbq1022** [comment]
没有注册表访问权 =。=
![image](https://user-images.githubusercontent.com/56924543/67452136-f0d9c480-f654-11e9-9fc1-5590aec74498.png)

**Comment by xbq1022** [comment]
![image](https://user-images.githubusercontent.com/56924543/67452225-1e267280-f655-11e9-9762-0d3e8f118877.png)

**Comment by neolee** [comment]
你的这个用户没有管理权限的么……这个不应该啊，一般 Windows 的主账户都是可以做这个操作的。

**Comment by xbq1022** [comment]
也确实的管理员权限的账户呀。
![image](https://user-images.githubusercontent.com/56924543/67452636-6e520480-f656-11e9-9617-7e17876e2406.png)

**Comment by xbq1022** [comment]
这个“0”看着不太妙。
![image](https://user-images.githubusercontent.com/56924543/67452681-8de92d00-f656-11e9-907b-0edd2bea30eb.png)

**Comment by neolee** [comment]
是的，这个要变成 1 才好，不知道为啥这一句不成功：

```powershell
Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1
```

另外无法卸载 python37 也比较奇怪，我查了下，根据 [这个页面的信息](https://github.com/lukesampson/scoop/issues/2947)，你可以去 Windows 的卸载那里找找有没有 Python 参与，尝试修复然后卸载掉，然后再试试 Scoop。

**Comment by xbq1022** [comment]
悲剧了。
![image](https://user-images.githubusercontent.com/56924543/67453110-1ae0b600-f658-11e9-8f77-be9dd9927dd0.png)

**Comment by neolee** [comment]
有木有“修复”的选项？

我的感觉是你的系统已经有点乱了，如果可能的话，重装个干净的 Windows 10 可能会一下子都好了。

**Comment by xbq1022** [comment]
是挺乱的。我下了个卸载软件，修复了下。又重新执行了命令，貌似可以了，先用着，电脑上还有其他软件，重装挺麻烦的。但愿后面顺利，谢谢老师了。
![image](https://user-images.githubusercontent.com/56924543/67453637-d8b87400-f659-11e9-8711-ec23cdd98117.png)

**Comment by neolee** [comment]
哈你终于过去了，恭喜，keep going.
