### ISSUE TITLE
为什么安装的python版本总是3.6.2，明明已经显示3.7.4成功了的。

### ISSUE THREAD

**Issue by yzt001** [neolee/pilot#433]
老师，为什么安装的python版本总是3.6.2，明明已经显示3.7.4成功了的。

编码如下：

---------------------------------------------------------------------

Windows PowerShell
版权所有 (C) 2016 Microsoft Corporation。保留所有权利。

PS C:\Users\Administrator> python -V
Python 3.6.2
PS C:\Users\Administrator> scoop install python37@3.7.4
'python37' (3.7.4) is already installed.
Use 'scoop update python37' to install a new version.
PS C:\Users\Administrator> python -V
Python 3.6.2
PS C:\Users\Administrator> scoop update python37
python37: 3.7.4 (latest version)
Latest versions for all apps are installed! For more information try 'scoop status'
PS C:\Users\Administrator> python -V
Python 3.6.2

**Comment by neolee** [comment]
看上去应该是你以前安装过，而那个老 Python 所在的目录也在系统 PATH 设置中，而且优先级比你 Scoop 安装的 Python 高。去系统 PATH 设置里找找。

**Comment by yzt001** [comment]
> 看上去应该是你以前安装过，而那个老 Python 所在的目录也在系统 PATH 设置中，而且优先级比你 Scoop 安装的 Python 高。去系统 PATH 设置里找找。

嗯嗯，之前确实装过别的编译器的python

**Comment by yzt001** [comment]
> 看上去应该是你以前安装过，而那个老 Python 所在的目录也在系统 PATH 设置中，而且优先级比你 Scoop 安装的 Python 高。去系统 PATH 设置里找找。

把原来装的python编译器删了，好用了，谢谢老师
