### ISSUE TITLE
iwr:无法连接远程服务器

### ISSUE THREAD

**Issue by zhenrany** [neolee/pilot#434]
![image](https://user-images.githubusercontent.com/55627503/68435688-e98aed00-01f6-11ea-9042-d128fbdfa21c.png)

请问 iwr:无法连接远程服务器，是网络的原因？还是被拦截的原因？怎么解决？
之前在台机上配置环境的时候没出现这个问题
现在在笔记本上配置环境出现问题

**Comment by bennet569** [comment]
我也遇到这个问题，老师之前给的答复都是“换网络”或者“挂代理”。
我用的是公司电脑，没法换网络，我在这也想问一下，“挂代理”怎么操作？有谁能给解答一下吗？

**Comment by zhenrany** [comment]
可是我台机和笔记本的网络都是单位的网，是同一个网络，台机没问题，只有笔记本出问题了.

**Comment by yzt001** [comment]
需要搭梯子，我昨晚搞了好久才明白到底是啥意思。

**Comment by zhenrany** [comment]
没有做处理，多试几次，已经解决。
