### ISSUE TITLE
删除实例变量‘Bot.wait = wait’之后为什么会进入无限循环？

### ISSUE THREAD

**Issue by xiaoerhai** [neolee/pilot#435]
class Garfield:
    
    def __init__(self):
        self.bots = []

    def add(self, bot):
        self.bots.append(bot)

    def _prompt(self, s):
        print(s)
        print()

    def run(self):
        self._prompt("This is Garfield dialog system. Let's talk.")
        for bot in self.bots:
            bot.run()

和我预想的不一样，我以为会没有延迟回复了；但实际上不仅有延迟回复，而且还进入了无限循环。

**Comment by neolee** [comment]
1. 你去掉 `Bot.wait = wait`，这个并不会“没有延迟”，因为 Bot 类里给 Bot.wait 的缺省值是 1，也就是延迟 1s，你做的只不过让你没法在创建 Garfield 类是修改这个设置值罢了。

2. 你要希望去掉延迟，创建 Garfield 类是指定延迟 0 就好了，类似 `g = Garfield(0)`。

3. 你遇到了什么问题，是运行挂起一直不结束？这个和你去掉 `Bot.wait = wait` 应该没关系，可能别的地方代码有问题。

**Comment by xiaoerhai** [comment]
第1、2 两点明白了；
第3点：
我遇到的问题：进入了循环的对话（正常是对话到最后一个bot就结束了）。应该是别的代码出问题了，可惜没法还原问题本身了。
