### ISSUE TITLE
garfield = Garfield(1) 中的 1 为什么默认赋值给了 wait 而不是赋值给 add() 方法中的 bot 或者 _prompt() 方法中的 s

### ISSUE THREAD

**Issue by xiaoerhai** [neolee/pilot#436]
class Garfield:
    
    def __init__(self, wait=1):
        Bot.wait = wait
        self.bots = []

    def add(self, bot):
        self.bots.append(bot)

    def _prompt(self, s):
        print(s)
        print()

    def run(self):
        self._prompt("This is Garfield dialog system. Let's talk.")
        for bot in self.bots:
            bot.run()

**Comment by neolee** [comment]
这个 `1` 赋给 Bot.wait 因为这本来就是个类变量而不是实例变量，你可以复习一下这两个概念。

至于  _prompt() 方法中的 s，那是个打印输出的提示信息字符串，和这个 wait 有啥关系？

**Comment by xiaoerhai** [comment]
明白了
1.  wait 是Bot的类变量；如果它只在方法__init__（）里，它就是实例变量；
2.  s只是一个参数，既不是类变量，也不是实例变量。

**Comment by neolee** [comment]
很对！
