### ISSUE TITLE
关于 Garfield 类中的 Bot.wait = wait

### ISSUE THREAD

**Issue by xiaoerhai** [neolee/pilot#437]
Bot.wait = wait 中的 Bot 应该就是指上文创建的 Bot 这个类吧？

也就是说，类（Garfield）定义中也可以引用其他类（Bot））的？

**Comment by neolee** [comment]
当然。

p.s. 看看我怎么给你改的标题和内容，不要写太长的标题，努力把自己的句子写得更加清晰和易懂。
