### ISSUE TITLE
学习用书克隆好，jupyterlab也安装好，命令行输入jupyterlab回车，无法打开学习用书

### ISSUE THREAD

**Issue by weidong3597** [neolee/pilot#438]
反馈如下图（一）所示，一直不动了，根据提示提供了两个网址，我逐一复制到谷歌浏览器打开，提示拒绝访问该网站，
猜想会不会时浏览器的问题于是换到火狐，依然如此，在想会不会网址复制错了，最后提示依然拒绝访问（图二）

进一步排查：1）会不会时网络的问题，网络已经挂代理，访问其他网站比较顺畅，可能性不大
2）会不会学习用书没有clone好，显示已经存在了（如图三，提示没有问题）
3）会不会时（jupyterlab）没有安装好，执行pip list如图四显示（之前请教过，成功的）
4）会不会时名称错误，路径错误（jupyterlab仔细核对过了没有问题，根据提示我之前把jupyterlab放在了C盘，而当前的工作目录在D盘，会不会这个原因，
根据执行jupyterlab反馈的地址，输入：python c:\users\陈伟东\scoop\apps\python37\3.7.4\lib\site-packages\jupyterlab
回馈的截图，跟图一保持一致）
![Jupyter Lab反馈的问题](https://user-images.githubusercontent.com/48782455/68445638-6af17800-0215-11ea-8173-e222ce813be2.png)
![拒绝访问](https://user-images.githubusercontent.com/48782455/68445658-7a70c100-0215-11ea-84a1-7cda90ac2a6e.png)

![学习用书提示成功](https://user-images.githubusercontent.com/48782455/68445691-970cf900-0215-11ea-8da0-75d62517da4c.png)
![反馈四](https://user-images.githubusercontent.com/48782455/68445704-9e340700-0215-11ea-838e-94d9199e3d93.png)

**Comment by neolee** [comment]
首先，`python c:\users\陈伟东\scoop\apps\python37\3.7.4\lib\site-packages\jupyterlab` 这个是没啥意义的，你只要运行 `jupyter lab` 就可以了。

然后你运行 `jupyter lab` 没有问题，就是那样的，也没有报错，应该一切 OK。

你的问题应该是用浏览器访问 Jupyter Lab（也就是上述命令提供的服务，如果理解这句话有疑问可以看看支线课程三），这里几点注意：

1. 理论上你运行 `jupyter lab` 可以自动打开缺省浏览器的，如果没有，极可能是被你的安全软件拦截了；
2. 把  `http://localhost:...` 那一整行拷贝到浏览器地址栏打开，应该是不会有问题的，如果有问题也会在命令行界面（你运行 `jupyter lab` 命令那个窗口）显示出错信息；你的浏览器说无法打开，很像是这个请求都没到 Jupyter Lab，所以比较可能是你的防火墙设置禁止浏览器访问这个地址。

所以我的猜测是：你的 Jupyter 安装应无问题，但是系统有些安全设置组织了浏览器访问。

**Comment by weidong3597** [comment]
有在百度了解到，到防火墙里面可以为浏览器设置权限，电脑是windown10的，打开防火墙如图一所示，唯一能够看到为应用程序授权的只有圈起来的那一栏，授权后命令行输入 jupyterlab依然无法自动打开jupyterlab，即使是网址复制也是提示：如果您的计算机或网络受到防火墙或者代理服务器的保护，请确认 Firefox 已被授权访问网络
![授权一](https://user-images.githubusercontent.com/48782455/68472881-7f0c9800-025c-11ea-963c-cff7ce64b05d.png)
![授权二](https://user-images.githubusercontent.com/48782455/68472889-82a01f00-025c-11ea-98f7-72456c3eb923.png)

**Comment by weidong3597** [comment]
问题应该解决了，现在在命令行输入：Jupyter Lab,复制出现的网址到浏览器中打开，可以正常操作了，为了验证，我ctrl+c,从新运行Jupyter Lab，同样可行，当前不知道具体发生了什么，我先把练习跟上去，后面在看，老师谢谢

**Comment by neolee** [comment]
Keep going!
