### ISSUE TITLE
安装好了 Scoop 之后不能正常运行

### ISSUE THREAD

**Issue by zhangshuzhong** [neolee/pilot#439]
![M$}SK6 W2LILE71JE7DMHLU](https://user-images.githubusercontent.com/48702747/68447775-16053000-021c-11ea-8a60-75bfc7540363.png)
最开始安装完成之后输入scoop list可以显示已安装的软件，但是使用scoop update后就卡住了，然后关闭了软件再重启。之后再输入scoop list就显示如图片的错误，输入其他代码也一样。请问如何解决？

**Comment by neolee** [comment]
Scoop 没装好，删了重来，看 Wiki 里“重新安装 Scoop”一节。

**Comment by zhangshuzhong** [comment]
好的，已经解决！
谢谢！
