### ISSUE TITLE
软件包安装失败 openssh 7.6p1 *failed*

### ISSUE THREAD

**Issue by Frank1217626** [neolee/pilot#44]
![图片](https://user-images.githubusercontent.com/52859765/67452891-4020f480-f657-11e9-86fe-c62647b38b57.png)
scoop list 中
openssh 7.6p1***failed*** 失败

我重新安装后，显示已经安装完成

**Comment by neolee** [comment]
没明白，你尝试过 `scoop uninstall openssh` 和 `scoop install openssh` 了对吧？目前状态是好了还是依旧 `failed`？

**Comment by Frank1217626** [comment]
![图片](https://user-images.githubusercontent.com/52859765/67453719-27fea480-f65a-11e9-8fe9-2c9c3d055d47.png)
重新安装后是这种情况

**Comment by neolee** [comment]
网络问题，安装包没下完整，重试。

**Comment by Frank1217626** [comment]
老师，这个问题已经解决，谢谢您
