### ISSUE TITLE
运行 git push后要求输入Github账户密码，账户可以输入，输密码时光标不动，没法输入

### ISSUE THREAD

**Issue by Guochangyan** [neolee/pilot#440]
PS C:\Users\guocy> cd code
PS C:\Users\guocy\code> cd pilot-student
PS C:\Users\guocy\code\pilot-student> git push
Username for 'https://github.com': guojing2960@gmail.com
Password for 'https://guojing2960@gmail.com@github.com':

**Comment by neolee** [comment]
就是这样的，Unix 工具里输入密码通常都不回显，这是为了安全性。你就输入密码回车就行了。
