### ISSUE TITLE
疑似 Scoop 安装失败

### ISSUE THREAD

**Issue by oneisonly** [neolee/pilot#441]
![1](https://user-images.githubusercontent.com/53245383/68448837-d6d8de00-021f-11ea-957e-1cffa00d5543.jpg)

**Comment by oneisonly** [comment]
![2](https://user-images.githubusercontent.com/53245383/68448841-ddffec00-021f-11ea-9a92-166540f351f2.jpg)

**Comment by oneisonly** [comment]
![3](https://user-images.githubusercontent.com/53245383/68448852-e3f5cd00-021f-11ea-951d-d47d6fa05cef.jpg)

**Comment by oneisonly** [comment]
找了个网络，之前打不开的图都打开了，但安装scoop成功后，输入list，还是显示没有任何app，但之后的安装也都成功了，所以我下一步怎么做？

**Comment by neolee** [comment]
Scoop 应该是好了，但是安装 git 有问题，所以很多关键的比如 `scoop update` 都会失败。先把 git 装好吧 `scoop install git`

**Comment by oneisonly** [comment]
成功了，谢谢，网络不好的小伙伴可以下载fei tu（汉语）
