### ISSUE TITLE
NameError: name 'type_0' is not defined

### ISSUE THREAD

**Issue by myhappylife2002** [neolee/pilot#444]
![1](https://user-images.githubusercontent.com/57083738/68465981-79a85100-024e-11ea-9e13-d04e2acee274.png)
![2](https://user-images.githubusercontent.com/57083738/68465987-7ad97e00-024e-11ea-976f-8b43358020ae.png)
麻烦老师帮助看一下问题出在什么地方

**Comment by michaelmakun** [comment]
嗯。。。我觉得你应该先保存，再运行，我看上面110802.py还有点，没保存，电脑不认识你这个type_0。所以报错没定义

**Comment by myhappylife2002** [comment]
这些都是保存后再运行出来的结果。刚才又保存了一下重新运行还是显示这种结果

**Comment by myhappylife2002** [comment]
谢谢老师，遇到的一些问题可能属于笑来老师所说的“提前引用”性质的。既然如此，有些问题就先放到那里不管了，学完后面的再说吧。因为您说的这两个解决方案我反复试了多次，依然没有任何改变。这个问题在我这里先挂起来了，继续后面的

**Comment by myhappylife2002** [comment]
每行代码运行一遍后，解决了。刚开始还是没有真正理解老师的回复。反复多读多试后，才恍然大悟。
谢谢老师！
