### ISSUE TITLE
变量，参数，属性都有什么区别？

### ISSUE THREAD

**Issue by michaelmakun** [neolee/pilot#445]
def __init__(self):
    self.q = ''
    self.a = ''

这里q和a 我最开始认为是初始化对象的属性，看到下面发现老师说这两个是实例变量。

后来，我写成了 
def __init__(self,q,a)
    self.q = ""
    self.a = ""

发现也能正常运行，这里面的q和a应该是函数的参数。

所以就有点糊涂了，还是说在这里这几个是同一个意思？

**Comment by michaelmakun** [comment]
还有一个  print(self._think(self.a))  意思是输出自己的_think方法，这个_think方法调用自己的属性(变量？参数？)

**Comment by neolee** [comment]
广义的变量（*variables*）就是值（*values*）的名字。而在类定义中，变量分为“类变量（*class variables*）”和“实例变量（*instance variables*）”两种。

在 Python 里，实例变量和属性基本是同义词，只不过用“类变量（*class variables*）”和“实例变量（*instance variables*）”更清晰。

参数是函数的输入。

`print(self._think(self.a))` 的执行过程是：
1. 求值 self.a，这是一个实例变量，这里用实例对象里的实际 a 值代替就行了；
2. 用上一步得到的值作为输入参数调用类方法 self._think()，得到这个方法的返回值（是一个字符串）；
3. 用上一步得到的返回值作为输入参数调用内置函数 `print()`，打印出这个值。

**Comment by neolee** [comment]
如果你把初始化方法定义为：

```python
def __init__(self,q,a)
    self.q = q
    self.a = a
```

这样可以在类实例化的时候指定创建的实例对象里的属性 q 和 a 的初始值。其中：

```python
    self.q = q
```
`=` 右边的 q 是 `__init__` 方法的输入参数，替换为输入的参数值；左边的 `self.q` 则是实例变量 q，过着叫“属性 q”也可以。

**Comment by michaelmakun** [comment]
多谢老师~
