### ISSUE TITLE
VSCode 中缺少 Python 扩展

### ISSUE THREAD

**Issue by oneisonly** [neolee/pilot#449]
首先我是李老师和笑来老师的编程同时进行，由于怕冲突，所以卸载了之前的软件，在按李老师的要求装完所有软件后，运行中发现viscode没有python扩展，按以前方法在vscode中把python又装了一次，但发现打印出来发现是乱码。1.请问该如何操作？2.两个课程的操作方法会不会互相冲突，是不是需要先学完一个再学另一个？

**Comment by oneisonly** [comment]
![2](https://user-images.githubusercontent.com/53245383/68492728-5b5e4780-0286-11ea-8e2d-3b1f1376d728.jpg)
![Uploading 2.jpg…]()

**Comment by oneisonly** [comment]
![3](https://user-images.githubusercontent.com/53245383/68493059-b42de000-0286-11ea-8349-c0e1c32618c4.png)

**Comment by neolee** [comment]
这两个课程是一脉相承的，基本可以看做是 2.0 版本。

使用工具上其实也没区别，都是 Python + Jupyter Lab + VSCode。按照配置指南做好准备，两个课程都可以的。

如果你用 Scoop 装好了 Python，打开 VSCode，安装 Python 插件就行了，不会有问题。

乱码这个，原因不明，你试试在有乱码的 Terminal 窗口敲 `clear` 回车看看。
