### ISSUE TITLE
Couldn't find manifest for 'python37'

### ISSUE THREAD

**Issue by Frank1217626** [neolee/pilot#45]
![图片](https://user-images.githubusercontent.com/52859765/67453055-eff66200-f657-11e9-8c3f-8d743196f5d7.png)
将代码中的 python37改为python可以安装python3.8

**Comment by neolee** [comment]
我们不能使用 3.8，太新了，一些软件包不兼容。

你问题的解答是，需要先在 Scoop 中加入一些配置，仔细看配置指南。
