### ISSUE TITLE
谢谢分享！我想知道这个教程针对的主要受众定位是什么？

### ISSUE THREAD

**Issue by cnukaus** [neolee/pilot#450]

**Comment by michaelmakun** [comment]
我猜你没听老师的第一课。
先说我的观点，针对对编程有兴趣的人，或者想改善自己思维的人。

麻省理工学院在新工科改革计划里面说了，新工科人才的十二项重要思维能力，这十二项重要的思维能力，除了非常通用的一些思维，其他基本上都可以通过编程来训练来提升。

十二项能力分别是
1. Learning to learn
2.making
3.discovering
4.personal
5.interpersonal
6.systems
7.creative
8.critical and metacogntive
9.analytic
10.computational
11.experimental
12.humanistic
