### ISSUE TITLE
内建函数print()和特殊语句return什么情况下能互相代替？

### ISSUE THREAD

**Issue by xiaoerhai** [neolee/pilot#451]
回顾老师之前的回答：
return 是一个特殊语句，仅用在函数定义内部，表示终止当前函数的运行并把后面的值作为返回值返回。
但如下 return s ，运行时为什么没有返回对应的值？

class Garfield:
    def __init__(self,wait=1):
        Bot.wait = wait
        self.bots = []
        
    def add(self,bot):
        self.bots.append(bot)
        
    def _prompt(self,s):
        return s
        return
        
    def run(self):
        self._prompt("This is a Garfield dialog system. Let's talk.")
        for bot in self.bots:
            bot.run()

**Comment by neolee** [comment]
我觉得你没有理解函数和 return 的概念，建议再仔细读一读关于函数的章节。

**Comment by xiaoerhai** [comment]
昨晚看了之后今早敲完确认理解了，总结下：
1. return 必须在函数内，print（）在函数内外都行；
2. return 是返回值，print（）函数是打印值或者是输出值，返回值如果要打印必须用print（），否则无法输出。

所以，已上方法我可以修改为：
class Garfield:
    
    def __init__(self,wait=1):
        Bot.wait = wait
        self.bots = []
        
    def add(self,bot):
        self.bots.append(bot)
        
    def _prompt(self,s):
        return s
        
    def run(self):
        print(self._prompt("This is a Garfield dialog machine. Let's talk."))
        print()
        for bot in self.bots:
            bot.run()

**Comment by neolee** [comment]
有进步，但是还不透彻。

`return` 和 `def`、`if`、`while` 等都是 Python 语言的“关键字”或者叫“保留字”，是语言的固有表达法；这些表示法用来做语言里最本质最核心、不可替代的一些事情，比如，`def` 用来定义函数，`return` 用来定义函数的返回值并终止函数，这些都不是你自己可以实现的事情，是语言本身。
 
而 `print` 只不过是一个函数，虽然是 Python 语言内置编写好的函数，但和你用 `def` 定义的函数没有什么区别，如果你愿意完全可以自己写一个 `print` 出来。

p.s. 在文本中嵌入 Python 代码用这样的写法：

<pre>
```python
def add(a, b):
    return a + b
```
</pre>
