### ISSUE TITLE
 输入 python hello.py 后显示 ERRNO

### ISSUE THREAD

**Issue by wendyyouthbaby** [neolee/pilot#452]
1、已经在 VSCode 建立新文件，并保存，但不知道自己操作对不对
2、回到 ConEmu 窗口，然后：
•输入 ls ↩︎，应该可以看到刚才新建的文件 hello.py；显示如下：
PS C:\Users\Administrator\code>  ls

    目录: C:\Users\Administrator\code

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----  2019/11/9 星期六  上午 11             21 ^+N
                              :29
-a----  2019/11/9 星期六  上午 11              8 ^+S
                              :29
3、输入指令“python hello.py ”后显示如下错误：
PS C:\Users\Administrator\code>  python hello.py
C:\Scoop\apps\python37\current\python.exe: can't open file 'hello.py': [Errno 2] No such file or directory
PS C:\Users\Administrator\code>
4、请问以上问题怎么解决？

**Comment by michaelmakun** [comment]
嗯。。。。 你的hello.py没有在code文件夹里。所以有这样的情况出现。

理论上，你需要执行的文件需要在你的目录下。

**Comment by michaelmakun** [comment]
你可以这样执行：

cd code   (切换到code文件夹下)
touch hello.py   （新建一个hello.py文件）
code hello.py   （如果安装正确，这个命令用VS打开hello.py文件，刚开始是空的，可以填写一些东西，比如print("Hello world"),然后保存）
python hello.py  （在命令行执行这个命令，就会出现Hello world的字样）
