### ISSUE TITLE
Type Error: Dog() takes no arguments

### ISSUE THREAD

**Issue by imagelan** [neolee/pilot#453]
查了一下没有类似的issue。希望老师解答：

![image](https://user-images.githubusercontent.com/48951128/68523185-30bac180-027b-11ea-9a2a-88188fa71912.png)

**Comment by michaelmakun** [comment]
嗯。。。。
class 里面初始化"init"前后  **有两个 下划线**   "_和_" 是在一起的，我看你写的好像只有一个下划线。
def __init__(self,name)

你再试试

**Comment by neolee** [comment]
@imagelan 

应该就是 @michaelmakun 同学说的问题。你的 `__init__()` 方法名字写错了，Python 解释器找不到这个方法，于是认为这个 `Dog()` 类没有自定义的初始方法，这种情况下创建实例对象时不能有输入参数，只能 `a = Dog()` 这样子。

**Comment by imagelan** [comment]
真是奇怪，我平时用英文输入。难道在英文输入时用 shift +_ 不可以输入下划线吗？ 我直接在书的文字行拷贝这个函数，结果就可以运行啦。不知道如果在英文输入时如何可以输入下划线？

**Comment by imagelan** [comment]
谢谢！
