### ISSUE TITLE
将教材里的程序run 出现错误 错误如图，在student版本里自己键入时出现同样的错误

### ISSUE THREAD

**Issue by Yukiwly** [neolee/pilot#454]
![image](https://user-images.githubusercontent.com/48648174/68525776-0c5cf480-0310-11ea-990d-e547d77c65ab.png)

**Comment by neolee** [comment]
你需要先运行上面的定义 a、b 等变量的那个 cell。

**Comment by Yukiwly** [comment]
> 你需要先运行上面的定义 a、b 等变量的那个 cell。

谢谢已经解决了
