### ISSUE TITLE
执行 Get-ExecutionPolicy 命令时报错

### ISSUE THREAD

**Issue by xiaobin919** [neolee/pilot#456]
执行Get-ExecutionPolicy命令时报错
这个位置是不是描述错误，我在执行执行Get-ExecutionPolicy命令时，直接跳到下一步，结果是错误的，而后我在得到RemoteSigned结果后，仍然执行Set-ExecutionPolicy RemoteSigned -scope CurrentUser 命令，则成功了。

![执行Get-ExecutionPolicy报错](https://user-images.githubusercontent.com/53881702/68527127-8b592980-031e-11ea-9d52-6c6096aa6d47.png)

**Comment by neolee** [comment]
这个表述没有问题，如果你在命令行执行 `Get-ExecutionPolicy` 得到结果是 `RemoteSigned`，那么就可以直接去安装 Scoop 了。
