### ISSUE TITLE
下载 Scoop 时出错

### ISSUE THREAD

**Issue by heidi310** [neolee/pilot#457]
在powershell中下载Scoop时输入iwr -useb get.scoop.sh | iex 时就出现下面地错误，下面应该怎么处理呢？

Windows PowerShell
版权所有 (C) Microsoft Corporation。保留所有权利。

PS C:\Users\Administrator> Get-Executionpolicy
RemoteSigned
PS C:\Users\Administrator> iwr -useb get.scoop.sh | iex
iwr : 无法连接到远程服务器
所在位置 行:1 字符: 1
+ iwr -useb get.scoop.sh | iex
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:Htt
   pWebRequest) [Invoke-WebRequest]，WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShe
   ll.Commands.InvokeWebRequestCommand

PS C:\Users\Administrator>

**Comment by neolee** [comment]
网络问题。

**Comment by heidi310** [comment]
现在好像scoop已经安装好了，但在运行下面这几个命令时出现问题，
scoop list
scoop install git
scoop update
请老师指导

Windows PowerShell
版权所有 (C) Microsoft Corporation。保留所有权利。

PS C:\Users\Administrator> iwr -useb get.scoop.sh | iex
Initializing...
Scoop is already installed. Run 'scoop update' to get the latest version.
PS C:\Users\Administrator> scoop list
scoop : 无法将“scoop”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检
查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ scoop list
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (scoop:String) [], ParentContain
   sErrorRecordException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\Administrator>

**Comment by neolee** [comment]
Scoop 没装好，删掉重装，参考 Wiki 里“重装 Scoop”一节。

**Comment by nancy3457** [comment]
同样的问题scoop装不上
PS C:\Users\Administrator> iwr -useb get.scoop.sh | iex
iwr : Unable to connect to the remote server
At line:1 char:1
+ iwr -useb get.scoop.sh | iex
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:Htt
   pWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShe
   ll.Commands.InvokeWebRequestCommand
从昨天晚上到现在，开始以为是网络堵塞，今早6点爬起来弄，还是连不上，在网上搜了“下载scoop”没找到啥可用的，scoop在github上的网页，也没找到能下载的，是我哪里弄错了吗？vpn一直开着呢。

**Comment by neolee** [comment]
就是网络问题。不知道你的具体环境，不过很多代理都需要特定操作才能对命令行起效，你可以咨询下服务商。

**Comment by nancy3457** [comment]
安装上了，网络咋好使的不知道，这是我学计算机以来一直的痛点，咋不好使的不知道，咋好使的也不怎么知道。还是谢谢老师！

**Comment by neolee** [comment]
网络这个问题比较诡异，经常时灵时不灵，倒也罢了；学编程还是要努力搞清楚行和不行的原因才好。

继续加油。

**Comment by ygrdkl** [comment]
”Wiki 里“重装 Scoop”“具体是在哪里呢
