### ISSUE TITLE
python 代码运行报错

### ISSUE THREAD

**Issue by Gaomingzhao** [neolee/pilot#459]
![image](https://user-images.githubusercontent.com/24623343/68528369-bfd3e200-032c-11ea-9dfa-f95a500676c8.png)
![image](https://user-images.githubusercontent.com/24623343/68528372-ca8e7700-032c-11ea-944c-3fe9ece9bc7a.png)

在学习第一课的过程中，尝试用命令行运行学习用书中的代码。
按照顺序操作后，报错。
起初以为是自己代码敲错了，但直接复制代码进去还是报错。

**Comment by neolee** [comment]
你的 Python 版本是？ `python -V`

**Comment by Gaomingzhao** [comment]
Python 2.7.10
