### ISSUE TITLE
安装好 Scoop 之后安装软件包出错

### ISSUE THREAD

**Issue by jianqingchen** [neolee/pilot#46]
![image](https://user-images.githubusercontent.com/24488183/67453807-76ac3e80-f65a-11e9-8b74-663c15add74a.png)
电脑配置
![image](https://user-images.githubusercontent.com/24488183/67452382-a3aa2280-f655-11e9-80a6-50dbff43930c.png)
安装 Scoop成功
![image](https://user-images.githubusercontent.com/24488183/67452439-ce947680-f655-11e9-962e-85c0724840cb.png)
运行 scoop bucket add versions、scoop update、scoop install busybox git python37时出错

**Comment by neolee** [comment]
你这个是 git 访问 /dev/null 出错了，影响了所有 Scoop 功能，网上有不少解决方案，参考 Issue #40

**Comment by neolee** [comment]
Duplicate of #40
