### ISSUE TITLE
Scoop 开始安装 git 软件包时总是出现执行不下去的问题

### ISSUE THREAD

**Issue by zhangjd0905** [neolee/pilot#460]
Scoop 就安装好了，我们接着运行下面这几个命令：
scoop install git
然后执行如下：
Windows PowerShell
Copyright (C) 2016 Microsoft Corporation. All rights reserved.

PS C:\Users\Administrator> scoop list
Installed apps:

  7zip 19.00
  dark 3.11.2
  git  *failed*
  innounp 0.49

PS C:\Users\Administrator> scoop uninstall git
Uninstalling 'git' ().
'git' was uninstalled.
PS C:\Users\Administrator> scoop install git
Installing 'git' (2.24.0.windows.2) [64bit]
PortableGit-2.24.0.2-64-bit.7z.exe (41.8 MB) [>                                                                                                                ]   0%
The operation has timed out.
URL https://github.com/git-for-windows/git/releases/download/v2.24.0.windows.2/PortableGit-2.24.0.2-64-bit.7z.exe#/dl.7z is not valid
PS C:\Users\Administrator>
请问如何解决
（

**Comment by zhangjd0905** [comment]
![Image 2](https://user-images.githubusercontent.com/57305219/68529108-fb26de80-0335-11ea-8966-1d5b8eb981b0.jpg)

**Comment by neolee** [comment]
目前需要重装 git 直至成功，目前看到的是网络访问有问题。

**Comment by zhangjd0905** [comment]
是的，是网络问题，今天早上重新操作已经全部安装成功，谢谢您！
