### ISSUE TITLE
安装 Scoop 中反复出现如下提示

### ISSUE THREAD

**Issue by 111xiaochao111** [neolee/pilot#462]
PS C:\Users\A> scoop list
Installed apps:

  7zip 19.00
  git  *failed*
  innounp 0.49

PS C:\Users\A> scoop install git
Scoop uses Git to update itself. Run 'scoop install git' and try again.
ERROR It looks like a previous installation of git failed.
Run 'scoop uninstall git' before retrying the install.
WARN  'git' () is already installed.
Use 'scoop update git' to install a new version.
PS C:\Users\A> scoop update
Scoop uses Git to update itself. Run 'scoop install git' and try again.
PS C:\Users\A>

**Comment by 111xiaochao111** [comment]
PS C:\Users\A> scoop list
Installed apps:

  7zip 19.00
  dark 3.11.2
  git  *failed*
  innounp 0.49

PS C:\Users\A> scoop install git
Scoop uses Git to update itself. Run 'scoop install git' and try again.
ERROR It looks like a previous installation of git failed.
Run 'scoop uninstall git' before retrying the install.
WARN  'git' () is already installed.
Use 'scoop update git' to install a new version.
PS C:\Users\A> scoop update
Scoop uses Git to update itself. Run 'scoop install git' and try again.
PS C:\Users\A>

**Comment by neolee** [comment]
列表中 `git` 后面有个 `failed` 看到吧？

然后提示你先 `scoop uninstall git` 然后再装，也看到了吧？
