### ISSUE TITLE
这个返回错在哪？

### ISSUE THREAD

**Issue by sbiwgu** [neolee/pilot#463]
>>> count=0
>>> while count<5:
...     print(count)
...     count+=1
...     print('Loop ends.')
...
0
Loop ends.
1
Loop ends.
2
Loop ends.
3
Loop ends.
4
Loop ends.

**Comment by xiaoerhai** [comment]
print('Loop ends.')   对应的那行不需要缩进。建议温习下函数关于缩进的内容。

**Comment by sbiwgu** [comment]
>>> count=0
>>> while count<5:
...   print(count)
...   count+=1
... print('Loop ends.')
  File "<stdin>", line 4
    print('Loop ends.')
        ^
SyntaxError: invalid syntax
>>>

**Comment by xiaoerhai** [comment]
这样：
count=0
while count<5:
    print(count)
    count+=1

print('Loop ends.')

**Comment by xiaoerhai** [comment]
这样：
count=0
while count<5:
    print(count)
    count+=1
print('Loop ends.')

**Comment by neolee** [comment]
@sbiwgu 你可能没有理解 @xiaoerhai 说的意思。其实很简单，你仔细的盯着你的代码看，到底和教材里的有啥区别？找不出区别的话，就不要继续往下了，直到你找到为止。

**Comment by sbiwgu** [comment]
好的，谢谢



---原始邮件---
发件人: "Neo Lee"<notifications@github.com&gt;
发送时间: 2019年11月10日(星期日) 中午1:50
收件人: "neolee/pilot"<pilot@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"sbiwgu"<972131254@qq.com&gt;;
主题: Re: [neolee/pilot] 这个返回错在哪？ (#463)



@sbiwgu 你可能没有理解 @xiaoerhai 说的意思。其实很简单，你仔细的盯着你的代码看，到底和教材里的有啥区别？找不出区别的话，就不要继续往下了，直到你找到为止。

**Comment by sbiwgu** [comment]
还是弄不明白，他多一个空行的，不理解是怎么弄的


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Neo Lee"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月10日(星期天) 中午1:50
收件人:&nbsp;"neolee/pilot"<pilot@noreply.github.com&gt;;
抄送:&nbsp;"鑫月电脑"<972131254@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [neolee/pilot] 这个返回错在哪？ (#463)




@sbiwgu 你可能没有理解 @xiaoerhai 说的意思。其实很简单，你仔细的盯着你的代码看，到底和教材里的有啥区别？找不出区别的话，就不要继续往下了，直到你找到为止。
