### ISSUE TITLE
代码的颜色有什么含义？

### ISSUE THREAD

**Issue by xiaoerhai** [neolee/pilot#465]

**Comment by neolee** [comment]
所谓程序代码的编辑器，和普通的文本编辑器的一大区别，是可以给代码“上色”，这个叫做 *syntax highlighting*，着色是和语法有关的，具体颜色的含义与你使用的配置（叫做 *color theme*）有关，比如下面这个是 VSCode 缺省的 *color theme*：

<img width="1596" alt="Color" src="https://user-images.githubusercontent.com/24796/68539645-88634500-03c1-11ea-9c9b-7a4c8e3aa39d.png">

这里紫色是一般的语言关键字，红色是字符串，等等。

事实上你可以自定义自己的 `color theme`，这里有个 [例子](https://github.com/Microsoft/vscode-extension-samples/tree/master/theme-sample)。
