### ISSUE TITLE
isinstance(False,int) 返回值为啥是 True?

### ISSUE THREAD

**Issue by tiger595** [neolee/pilot#466]

**Comment by neolee** [comment]
这真是一个好问题，为你的发现能力点赞。

实际上，Python 里 int 也好 bool 也好，都是 class，[而 bool 是 int 的子类](https://docs.python.org/3/library/functions.html#bool)，至于为啥这么设计，我猜测是为了兼容老的 C 语言代码。

**Comment by tiger595** [comment]
哈哈，明白了，谢谢老师夸奖，好开心。

**Comment by bennet569** [comment]
> 哈哈，明白了，谢谢老师夸奖，好开心。

为你点个赞

**Comment by tyler1zhang** [comment]
> 这真是一个好问题，为你的发现能力点赞。
> 
> 实际上，Python 里 int 也好 bool 也好，都是 class，[而 bool 是 int 的子类](https://docs.python.org/3/library/functions.html#bool)，至于为啥这么设计，我猜测是为了兼容老的 C 语言代码。

按照我的理解，计算机在存储False的时候为0， True的时候是1。所以False和True是int的子集。于此同时，所有的数据在计算机中的存储都是0和1的组合，只要不是0或空，这个值对于if这种判断语句都为True
---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-3-3c4378fe36ab> in <module>
      1 # 请在这里输入代码
----> 2 a= 1/False
      3 a

ZeroDivisionError: division by zero
