### ISSUE TITLE
如何更换 Python 的安装位置？

### ISSUE THREAD

**Issue by nancy3457** [neolee/pilot#467]
如何更换Python的安装位置？
我的C盘要满了，处理了也不行，D盘原本就装了python3.7和Visual Studio Code。
如何让scoop 连接上D盘python3.7？
如何删除scoop已经安装在C盘上的Python?
我的问题有点儿多哈，先谢谢老师，谢谢同学们！

**Comment by neolee** [comment]
Scoop 并不能“连接”你已经安装的 Python，它是一个软件包管理工具，负责安装和管理*自己安装的*软件包。

我觉得对你来说比较好的选择是完全删除 C 盘上的 Scoop，然后在 D 盘安装 Scoop，并且让 Scoop 安装软件包时都装在 D 盘。当然了，这个会带来一些潜在的麻烦，比如我的所有教程为了简明起见，都假定 Scoop 是安装在缺省位置的。

具体办法是，首先卸掉目前的 Scoop（参考 Wiki 里的“重新安装 Scoop”一节）：

```powershell
cd
del .\scoop -Force
```

然后在 D 盘重装 Scoop，假定装在 D:\scoop 这个目录下（你可以自己换）：
```powershell
$env:SCOOP='D:\scoop'
[environment]::setEnvironmentVariable('SCOOP',$env:SCOOP,'User')
iwr -useb get.scoop.sh | iex
```

可以参考 [Scoop 官方指南](https://github.com/lukesampson/scoop/wiki/Quick-Start)。

上述操作如果无问题，从此以后你的 Scoop 以及它安装的软件统统都在 D 盘了。然后你可以继续按照配置指南操作，安装 git Python 等。

至于你以前安装过的 Python，最好不要混用，因为我也不知道你之前的安装啥情况，有没有潜在问题。
