### ISSUE TITLE
学习用书的运行异常

### ISSUE THREAD

**Issue by whxzhou** [neolee/pilot#468]
![image](https://user-images.githubusercontent.com/48576143/68542489-17835380-03e8-11ea-9975-a670f8bcfb7e.png)
是我在哪个地方输错了吗？

**Comment by whxzhou** [comment]
![image](https://user-images.githubusercontent.com/48576143/68542586-2f0f0c00-03e9-11ea-85ec-d0de2f7c400c.png)这里也是这个问题

**Comment by neolee** [comment]
上面不是说了么，先要在命令行运行 `pip install termcolor simpleeval` 才可以。

**Comment by whxzhou** [comment]
谢谢老师，已经可以了。
