### ISSUE TITLE
使用 Instant Markdown: Open Broweser 提示找不到该命令

### ISSUE THREAD

**Issue by eiyen** [neolee/pilot#469]
出现的问题：
使用如题命令：
![image](https://user-images.githubusercontent.com/52303623/68542748-caed4780-03ea-11ea-9187-669c5bf33c7b.png)

会提示找不到该命令：
![image](https://user-images.githubusercontent.com/52303623/68542684-3be02f80-03ea-11ea-9c0d-fa34293f68cf.png)

电脑环境：
64位 windows 电脑

已安装 instant markdown:
![image](https://user-images.githubusercontent.com/52303623/68542725-a7c29800-03ea-11ea-8489-6fbf9dedb7be.png)

默认浏览器是 chrome:
![image](https://user-images.githubusercontent.com/52303623/68542970-85317e80-03ec-11ea-9f5e-cc1007648f57.png)

**Comment by neolee** [comment]
这个不知道为啥，你重启下 VSCode 试试？

**Comment by eiyen** [comment]
噗，重启一下就能正常了（笑哭）
估计是因为刚刚在关闭 VSCode 的时候有更新一下。

**Comment by neolee** [comment]
有些插件装完是要 reload 一下的（有的不用）。
