### ISSUE TITLE
安装 jupyterlab 出现  `Could not find a version that satisfies the requirement pyzmq>=17`

### ISSUE THREAD

**Issue by Jared-Gong** [neolee/pilot#47]
![1571891666(1)](https://user-images.githubusercontent.com/56901849/67455455-351e9200-f660-11e9-9604-d85223f8bbf5.png)

**Comment by neolee** [comment]
运行下面几个命令，结果截屏发到这里：

```powershell
which python
python -V

which pip
pip -V
pip list
```

**Comment by Jared-Gong** [comment]
![1571894585(1)](https://user-images.githubusercontent.com/56901849/67455861-7c595280-f661-11e9-948f-3b8bf57b7bfc.png)
运行后是这样的

**Comment by azheng526** [comment]
![image](https://user-images.githubusercontent.com/50059311/67458629-4324e080-f669-11e9-831c-9879ec9f9f5e.png)
李老师，我这个也可以按照上面同学的解决办法吗？

**Comment by neolee** [comment]
@azheng526 你这个是别的问题，请另开 issue

**Comment by neolee** [comment]
@Jared-Gong 你这个 pip 不是 Scoop 安装的吧，你之前装过 Python 是吗？这两个环境似乎有冲突。

**Comment by Jared-Gong** [comment]
是的，3.7.4版本

**Comment by Jared-Gong** [comment]
3.7.5也安装成功了，需要卸载3.7.4版本后重装 jupyterlab吗？

**Comment by neolee** [comment]
不是版本问题，看上去是有两个 Python 系统交叉冲突。执行下面的两个命令，把结果发过来这里：

```powershell
Get-Command python
Get-Command pip
```

**Comment by Jared-Gong** [comment]
> 不是版本问题，看上去是有两个 Python 系统交叉冲突。执行下面的两个命令，把结果发过来这里：
> 
> ```powershell
> scoop list
> 
> Get-Command python
> Get-Command pip
> ```
> 
> p.s. 你怎么同时装 3.7.4 和 3.7.5 的？

哈 不是的，3.7.4是之前安装的 pycharm上用

**Comment by neolee** [comment]
嗯，确实如此，你需要把安装在 `C:\Users\AAA\AppData\Local\Programs\` 下面的 Python 去掉，然后用 Scoop 重新装 python37@3.7.4。

或者如果你都用过 PyCharm 了，应该不是新手，似乎应该能自己搞定的呀。

**Comment by azheng526** [comment]
我是正宗小白一枚，老师误会了：）我只是看到上面同学的问题和我的类似就想去试试。--    发自新浪邮箱客户端
在 10月24日 14:37，Neo Lee <notifications@github.com> 写道：
嗯，确实如此，你需要把安装在 C:\Users\AAA\AppData\Local\Programs\ 下面的 Python 去掉，然后用 Scoop 重新装 python37@3.7.4。

或者如果你都用过 PyCharm 了，应该不是新手，似乎应该能自己搞定的呀。



&mdash;

**Comment by neolee** [comment]
你之前装的 Python 不是 Scoop 装的，自然也不能通过 Scoop 删除，你可以试试：

1. 到 Windows 的应用下载里找找有没有，从那里删除；
2. 到 Windows 的 控制面板 -> 系统与安全 -> 系统 -> 高级设置 -> 环境变量，找到 Path 这个环境变量，看看里面有没有上面那个目录，有的话先去掉。

**Comment by Jared-Gong** [comment]
![1571908806(1)](https://user-images.githubusercontent.com/56901849/67471801-98212080-f682-11e9-9128-e26862fc5a63.png)
我太难了  老师，还有其他办法吗？

**Comment by neolee** [comment]
去 Windows 设置里面的卸载，找 Python，修复然后卸载，再尝试 `scoop install python37@3.7.4`。

Issue #32 #43 都有类似情况，最后都搞定了。

**Comment by Jared-Gong** [comment]
![1571911282(1)](https://user-images.githubusercontent.com/56901849/67475202-53988380-f688-11e9-8b07-c9af6fd4e127.png)
![1571911282(1)](https://user-images.githubusercontent.com/56901849/67475211-598e6480-f688-11e9-9c23-51d00494e129.png)
老师 我删除了这个Python的路径，运行安装后的结果

**Comment by Jared-Gong** [comment]
老师 我重装了之后按以下执行 出现如图：
![1571913702(1)](https://user-images.githubusercontent.com/56901849/67478104-fef80700-f68d-11e9-82cd-1914e9d40946.png)

scoop install git
scoop update
scoop install python37@3.7.4

**Comment by neolee** [comment]
你需要重新安装 Scoop，因为它还没装好，所以用 Scoop 安装 python 是不可能成功的。

按照 [Wiki](https://github.com/neolee/pilot/wiki) 里 “如何重装 Scoop” 的指引去做。

**Comment by Jared-Gong** [comment]
我重装scoop并成功了 重新开了界面update就是这样了

**Comment by Jared-Gong** [comment]
老师  scoop update遇到了以下报错
![1571964916(1)](https://user-images.githubusercontent.com/56901849/67535461-4bcaf480-f705-11e9-82cc-a010dbe218c5.png)
![1571964943(1)](https://user-images.githubusercontent.com/56901849/67535511-8765be80-f705-11e9-8dfc-add4daf84ff0.png)

**Comment by Jared-Gong** [comment]
老师  貌似以上是网络问题。我想用另一台电脑 再试试，但也装有Python3.7.4，为避免之前的问题，我需要做哪些操作呢？

**Comment by neolee** [comment]
是网络问题，网络问题换电脑似乎没有用处呀，需要换网络或者使用网络代理。

**Comment by Jared-Gong** [comment]
嗯呢  准备用家里的网络再试试。家里的笔记本也装有Python3.7.4，为避免之前的问题，我需要做哪些操作呢？

**Comment by neolee** [comment]
最好是完全卸载之前装的，然后按照指南一步步操作。当然，如果之前装的 Python 是完整可用的，也可以直接用之前的，但以后遇到问题，可能需要你自己研究解决了。

**Comment by Jared-Gong** [comment]
老师 我终于成功了，I made it！谢谢您！
![1572020385(1)](https://user-images.githubusercontent.com/56901849/67589339-c1c56f00-f78a-11e9-9486-3ceb9876715e.png)
![1572022128(1)](https://user-images.githubusercontent.com/56901849/67589343-c68a2300-f78a-11e9-8e01-c1d6c6307f76.png)

**Comment by neolee** [comment]
哈哈，恭喜，keep going!
