### ISSUE TITLE
Windows 10 试图装 python37 时 scoop update 失败

### ISSUE THREAD

**Issue by yanhan569046480** [neolee/pilot#470]
前面的步骤都照实做了。

在装python37时输入的命令如下：

`scoop bucket add versions`

`scoop update`在这一步每次都会卡住。

后面再执行
`pip install jupyterlab`
也总是失败。

**Comment by yanhan569046480** [comment]
重复了

**Comment by neolee** [comment]
`scoop update` 不成 Python 就装不了，Python 不成后面的自然也不行。

`scoop update` 出什么错？
