### ISSUE TITLE
换了电脑重新 fork，打开 jupylerlab 发现以前做过的程序没有了，有办法同步吗？

### ISSUE THREAD

**Issue by bennet569** [neolee/pilot#472]
我在家里和单位都想要练习，有同步的办法吗？

**Comment by neolee** [comment]
我不知道你怎么做的，但是假定你只有一个 GitHub 账号，你可以这么干：

1. 你只用 fork 学习用书一次，就在你自己账号下有了 pilot-student 这个 repo；
2. 然后你 clone 你自己的这个 repo 到你的各台计算机上；
3. 在任何计算机上做了功课之后就 commit 然后 push 到你的 repo；
4. 在其他计算机上做功课之前先 git pull 一下，就能从你的 GitHub repo 得到最新的版本。

在 Git & GitHub 教程里有介绍，其实就是很多机器都从一个共享 repo 克隆，有了修改就 git push 回共享 repo，其他机器 git pull 就能同步。

**Comment by onthebus98** [comment]
这个问题我也是琢磨了半天.
那是因为你之前做的工作只是保存在本地,还没有push到仓库里.每次做完功课你需要用git命令将你在本地分支上的工作提交到远程仓库.然后无论在哪一台电脑上你都可以获取最新版本了.主要命令如下:
git status
git add ..
git commit
git push
git pull

**Comment by bennet569** [comment]
> 这个问题我也是琢磨了半天.
> 那是因为你之前做的工作只是保存在本地,还没有push到仓库里.每次做完功课你需要用git命令将你在本地分支上的工作提交到远程仓库.然后无论在哪一台电脑上你都可以获取最新版本了.主要命令如下:
> git status
> git add ..
> git commit
> git push
> git pull

是的，git commit和git push就像是保存到了云，然后在任何计算机都能下载pull回来
