### ISSUE TITLE
这里是不是写错啦，执行命令应该是“^” + “enter”吧

### ISSUE THREAD

**Issue by bennet569** [neolee/pilot#473]
![微信截图_20191111105745](https://user-images.githubusercontent.com/57402562/68557957-742b5080-0472-11ea-95b9-41965864489b.png)

**Comment by jiaowagn** [comment]
![image](https://user-images.githubusercontent.com/24514390/68559185-0afa0c00-0477-11ea-801d-5407fdf88f03.png)

这些快捷键都可以执行所选 cell

**Comment by neolee** [comment]
都可以，Shift+Enter 是执行当前 cell 然后 advance 到下一个 cell；Control+Enter 是执行当前 cell 但停在原地；Alt-Enter 是执行当前 cell 然后在下面开一个新 cell 并进入新的 cell。
