### ISSUE TITLE
执行jupyter lab命令没有打开本地学习用书是什么原因？

### ISSUE THREAD

**Issue by xiaobin919** [neolee/pilot#474]
![执行jupyter lab命令没有打开本地学习用书是什么原因1？](https://user-images.githubusercontent.com/53881702/68558231-8e196300-0473-11ea-8d47-f1baa48ac418.png)
这个运行界面是正常的吗？

**Comment by jiaowagn** [comment]
看起来正常，你可以直接使用命令行返回的网址 （即贴图中底部 http 开头的网址）打开网页

**Comment by xiaobin919** [comment]
> 看起來正常，你可以直接使用命令行返回的網址（即貼圖示底部http開頭的網址）打開網頁

谢谢，复制网址直接在浏览器打开可以使用。

**Comment by neolee** [comment]
Wiki 里支线课程三有提到这个问题。

**Comment by xiaobin919** [comment]
> Wiki裡支線課程三有提到這個問題。
收到，谢谢老师。看了支线课程三，讲的很清晰明了，终于可以开始正式学习了。附:支线课程三的链接，有同样问题的小伙伴可以直接打开看。https://www.bilibili.com/video/av74039311/
