### ISSUE TITLE
关于git push的疑问

### ISSUE THREAD

**Issue by zhangshuzhong** [neolee/pilot#475]
我用了两台电脑来进行学些，一台是mac系统，一台是win10。昨天晚上用Mac系统安装教程上的说明，成功push了。今天用win10 进行相同的操作，没有能成功push。我个人理解的原因是我本地的数据库没有成功的更新到最新版本，所以我将数据库删除了，重新下载后，可以正常push了。之后我输入git log输出的结果如下：
![~I0B9813SDJR4YPQ6(~BR@K](https://user-images.githubusercontent.com/48702747/68560154-beb0cb00-047a-11ea-9755-c16e3607c116.png)
我的疑问是，我之后在操作的时候，是不是可以按照教程中表述的，先输入git fetch origin（同步所有的branch及commit），如果之前用mac电脑进行了push，在使用win10系统，就需要先git merge origin/HEAD（反之用win10系统先push，再使用mac时就先git merge origin/master）。然后再进行win10 系统的push。

**Comment by neolee** [comment]
你说的流程是多人协作时的做法，因为多人协作，互相不知道对方什么时候有新的修改和 push，所以不管咋样拿回来再 merge 总是可以的。

但你自己的多台电脑之间同步，其实不需要这么麻烦，因为你绝对不可能同时在两台机器上改东西还 push！你可以参考下 #472 里我的回复，简单说就是：无论在哪台机器上，开始干活前先 git pull 获取服务器最新版本，然后干活，然后 commit 和 push 成果到服务器上。就可以了。
