### ISSUE TITLE
需要切换 python 版本吗

### ISSUE THREAD

**Issue by wangbing007** [neolee/pilot#477]
输入python -m pip install --upgrade pip
显示 DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Requirement already up-to-date: pip in /Library/Python/2.7/site-packages/pip-19.3.1-py2.7.egg (19.3.1)
但我输入python3 -V时显示的是3.7.4

**Comment by neolee** [comment]
你是 macOS 吧？有些环境需要使用 python3 和 pip3：
```shell
python3 -m pip install --upgrade pip
pip3 install jupyterlab
```

**Comment by wangbing007** [comment]
嗯10.15.1的
嘿嘿终于弄好了
