### ISSUE TITLE
怎么理解【初始化】这个词？

### ISSUE THREAD

**Issue by xiaoerhai** [neolee/pilot#479]
问题背景（摘自 作业参考答案中的内容）：
1. 我们在新的 __init__() 方法中增加了一个参数来 runtype，并指定其缺省值为 'once'，这意味着以前所写的只运行一次的 bot 们在实例化时的代码不需要修改
2. 但这些子类的 __init__() 方法需要修改，对齐父类的定义，并调用父类的 __init__() 方法来初始化 self.runtype。

理解第一句中的【这意味着以前所写的只运行一次的 bot 们在实例化时的代码不需要修改】，它是指以下‘（）’中的内容还是不需要修改，仍然为空：
garfield = Garfield(1)
garfield.add(HelloBot())
garfield.add(GreetingBot())
garfield.add(FavoriteColorBot())
garfield.run()

理解第二句中的前半句没问题，但后半句【并调用父类的 __init__() 方法来初始化 self.runtype】中的【初始化】这个词应该怎么理解？是指父类中的self.runtype=runtype（runtype='once'）吗？

**Comment by neolee** [comment]
类定义里面有 `__init__()`，`__init__()` 里有 `self.xxx = xx` 这样的语句，作用是定义实例变量（属性）并给它赋一个“初始值”，所谓初始值，就是对象刚一建立，里面属性具有的值。初始化就是指这个定义属性并且赋值的过程。

**Comment by xiaoerhai** [comment]
明白了，谢谢李骏老师。我再看看对应章节，感觉其中有一个知识点需要补一下，就是关于__init__()后面这个括号里有时有等号有时没有等号这个点。

**Comment by neolee** [comment]
函数定义的括号里带等号的参数表示它有“缺省值”，这个算超前的知识，以后会专门讲。
