### ISSUE TITLE
【调用了 super() 函数来获得父类对象】中的【父类对象】是指【runtype】吗？

### ISSUE THREAD

**Issue by xiaoerhai** [neolee/pilot#480]
我删除【super().__init__(runtype)】后运行后的error：
AttributeError: 'HelloBot' object has no attribute 'runtype'

根据以上的error，runtype不应该是类的属性吗？

**Comment by neolee** [comment]
`runtype` 是 `Bot` 类里定义的实例属性，一般来说，子类 `__init()__` 中都需要调用父类的 `__init__()`，确保父类中的各种属性都得到恰当的初始化，这个就是 `super().__init__()` 的作用。

如果不做这个调用，子类里就没有对 `runtype` 进行初始化，自然也就出问题了。

**Comment by xiaoerhai** [comment]
1.  父类的方法，子类不是不仅可以继承还支持覆盖吗？这里我一开始认为就是子类继承父类的方法。
2.  我证实了我的想法：把【super().__init__(runtype)】替换成成【self.runtype = runtype】，代码也是能正常运行的。

**Comment by neolee** [comment]
可以覆盖，但是如果是一样的操作，引用父类里的实现不是更好吗？以后要改也只用改父类，不需要每个子类都改。

覆盖一定是子类有不同于父类的个性化需求。

**Comment by xiaoerhai** [comment]
嗯嗯，理解覆盖的作用。

回到第一点，我一开始认为子类会继承父类的方法，也就不需要【super().__init__(runtype)】这段代码了。但听您解释后，我是不是可以这样理解：
__init__() 这个方法，如果里面有缺省值则子类需要用到super().__init__()；如果没有缺省值，则不需要。
实例：
有缺省值：
def __init__(self, runtype='once'):
        self.runtype = runtype
        self.q = ''
        self.a = ''

无缺省值：
def __init__(self):
        self.q = ''
        self.a = ''

**Comment by neolee** [comment]
如果你在子类不覆盖写新的 `__init__()` 的话，确实子类就会执行父类的那个版本，但是你在子类写了个新的 `__init__()` 方法，Python 就不会自动调用父类的这个方法了（这是对的，因为有的时候你就是希望完全改写父类的行为），如果你想复用父类那个版本的 `__init__()` 的话，就要自己调用 `super().__init__()` 才行。

另外，你可以学习下支线课程四介绍的 Markdown，就知道怎么贴代码了。

**Comment by xiaoerhai** [comment]
绝大部分理解了，但还有以下几点疑问：

1.  正如标题所述：【调用了 super() 函数来获得父类对象】，这里的【父类对象】是一种前值引用还是应该改成【父类属性】；

2.  正如您上面的回答中所述：【但是你在子类写了个新的 __init__() 方法】，这里我一直认为是子类覆盖父类的方法，并非写了一个新的方法；

3.  正如我上面的回答中所述：【init() 这个方法，如果里面有缺省值则子类需要用到super().init()；如果没有缺省值，则不需要。】，这里我应该没有搞清楚self.q/self.a这两个实例变量和self.runtype这个实例变量的区别。

**Comment by Jared-Gong** [comment]
我的理解是super()函数是为子类方法中获得父类的方法。子类的继承应该是继承没有重写过的父类的方法，一旦你开始重写父类中的方法（python默认你覆盖了父类的方法），继承失效，这时我们就需要通过super()函数来“继承”父类方法。
我也不知道我的理解是否对，期待老师的回答。

**Comment by neolee** [comment]
@xiaoerhai 

1. super() 返回的是一个类似 self 的对象，只不过里面的东西都是父类版本的。

2. 这个就只是语言理解问题了，父类里有个 `__init__`，子类里你也定义了个同名方法，因为同名，就覆盖了父类实现，理解这个就好。

3. 是否需要调用父类版本的方法实现，取决于你是不是需要执行父类实现里的代码，不一定是属性赋值（虽然眼下的例子里是）。我也不知道你说的这几个属性有什么区别。

我觉得你脑子里有些思维定式，再仔细看看我和其他同学的解释，尝试重新理解下继承、属性和初始化的概念。

**Comment by xiaoerhai** [comment]
> @xiaoerhai
> 
> 1. super() 返回的是一个类似 self 的对象，只不过里面的东西都是父类版本的。
> 2. 这个就只是语言理解问题了，父类里有个 `__init__`，子类里你也定义了个同名方法，因为同名，就覆盖了父类实现，理解这个就好。
> 3. 是否需要调用父类版本的方法实现，取决于你是不是需要执行父类实现里的代码，不一定是属性赋值（虽然眼下的例子里是）。我也不知道你说的这几个属性有什么区别。
> 
> 我觉得你脑子里有些思维定式，再仔细看看我和其他同学的解释，尝试重新理解下继承、属性和初始化的概念。

好，谢谢老师指点。
