### ISSUE TITLE
运行 jupyter lab 为什么谷歌浏览器打不开而360浏览器可以打开

### ISSUE THREAD

**Issue by zhenrany** [neolee/pilot#481]
运行jupyter lab 为什么谷歌浏览器打不开学生用书，而360浏览器可以打开，需要怎么设置？

**Comment by neolee** [comment]
1. 如果你的 Chrome 是原版比较新的版本，不会有这个问题。
2. Jupyter Lab 会用系统缺省浏览器打开链接，你可以在 Windows 设定里修改这个设置。

**Comment by zhenrany** [comment]
谢谢老师，谷歌浏览器升级以后，就可以了！
