### ISSUE TITLE
支线课程 git commit 时出现问题

### ISSUE THREAD

**Issue by jiushijiushi** [neolee/pilot#483]
我先看教程，做好配置：
![image](https://user-images.githubusercontent.com/57130322/68669134-c78dc380-0584-11ea-9750-6a4bb9d77656.png)

然后一路到建好文件夹，弄好文件，准备git commit的时候，出现了这个问题：
![image](https://user-images.githubusercontent.com/57130322/68669248-09b70500-0585-11ea-899d-3e15cd7357ec.png)
之后，我重装了VScode，然后scoop checkup，然后也是同样的问题，不知该如何解决。
可能是VScode没删干净？我已经按照网上教程，卸载VScode后，又删掉了
vscode文件夹和Roaming中的Code文件。

**Comment by neolee** [comment]
和 #415 一样的问题，目前还不知道到底是什么原因。

**Comment by neolee** [comment]
你执行下面命令的返回是什么：

 ```powershell
Get-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled'
```

如果是 `0`，那么需要执行：

```powershell
Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1
```

**Comment by jiushijiushi** [comment]
![image](https://user-images.githubusercontent.com/57130322/68860949-7c5ee680-0725-11ea-8804-d84dc209f872.png)
返回结果是1.

然后我的解决方案是issue里面的一个。既然不能够打开Vscode，我就直接用
git commit -m"Add notes to README.md"
做提交说明了。
最后也能够提交得上去，能用就行
