### ISSUE TITLE
下面第2个 n 为何不等于0，以及 if n 怎么理解

### ISSUE THREAD

**Issue by 18p2p** [neolee/pilot#484]
![11111](https://user-images.githubusercontent.com/48624321/68677222-aafa8700-0596-11ea-8c48-334980015434.png)
n!=0 #N不等于0
if n: #怎么理解？

**Comment by neolee** [comment]
“万物皆为布尔值”这一节就是解释这个问题呀。n 来自前面的 `randrange(1, 100)` 调用，自然不是 0。

**Comment by michaelmakun** [comment]
if  n   注意冒号是定义的标志，if,while,def,class后面都有冒号。

if  n的意思是如果n是正确的，就执行下面的代码，n等于0就不正确，就不执行，n正确用bool表示就是True,n不正确用bool表示就是False。

所以if  n就等价于if  n !=0

**Comment by 18p2p** [comment]
对于老师的说明理解了，是因为文章的开始已经定义为randrange(1,100)随机整数。

对于楼上的解释（if n:0）应该是不对吧？
**if n的意思是如果n是正确的，就执行下面的代码，n等于0就不正确，就不执行，n正确用bool表示就是True,n不正确用bool表示就是False。

所以if n就等价于if n !=0**

**Comment by neolee** [comment]
@18p2p **在确定 n 是一个 int 的前提下**，`if n:` 等价于 `if bool(n):` 等价于 `if n != 0:`。

**Comment by 18p2p** [comment]
谢谢老师，谢谢楼上TX！
