### ISSUE TITLE
scoop update failed，但是checkup没有问题，git/python也能安装

### ISSUE THREAD

**Issue by bing90740** [neolee/pilot#488]
现状：scoop update failed，但是checkup没有问题，git/python也能安装和运行
问题：1.scoop已经重装过一次了，这种情况原因是什么？
2.这种情况下我可以进行后续作业吗？
PS C:\Users\tp\Code> scoop update
Updating Scoop...
error: RPC failed; curl 56 OpenSSL SSL_read: No error
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
Scoop update failed.
PS C:\Users\tp\Code> scoop [checakup](url)
scoop: 'checakup' isn't a scoop command. See 'scoop help'.
PS C:\Users\tp\Code> scoop list
Installed apps:

  7zip [19.00](url)
  busybox 3244-g48128b9aa
  dark 3.11.2
  git 2.24.0.windows.2
  innounp 0.49
  nodejs 13.1.0
  openssh 7.6p1
  python37 3.7.4 C:\Users\tp\scoop\workspace\python37.json][[](url)
<img width="771" alt="scoop update" src="https://user-images.githubusercontent.com/56208944/68740685-936adf00-0626-11ea-95ba-9429766ebc16.PNG">

**Comment by neolee** [comment]
你这 `scoop checkup` 叫没有问题啊？你仔细看看它说啥来着。

`scoop update` 失败看上去是网络问题。
