### ISSUE TITLE
scoop 安装报错

### ISSUE THREAD

**Issue by jundaidai** [neolee/pilot#489]
![scoop安装报错](https://user-images.githubusercontent.com/41604425/68747432-7e497c80-0635-11ea-9cbb-0c7bf40f77bf.png)

报错内容具体如下：
iex : 使用“2”个参数调用“DownloadFile”时发生异常:“在 WebClient 请求期间发生
异常。”
所在位置 行:1 字符: 26
+ iwr -useb get.scoop.sh | iex
+                          ~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-Expression], MethodInv
   ocationException
    + FullyQualifiedErrorId : WebException,Microsoft.PowerShell.Commands.Invok
   eExpressionCommand

**Comment by neolee** [comment]
网络问题。
