### ISSUE TITLE
Windows 7 下 scoop install git 失败 `无法连接到远程服务器`

### ISSUE THREAD

**Issue by Fanfan1031** [neolee/pilot#49]
PS C:\Users\Administrator.PC-20120727WEXY> scoop install git
Scoop uses Git to update itself. Run 'scoop install git' and try again.
Installing 'git' (2.23.0.windows.1) [64bit]
无法连接到远程服务器
URL https://github.com/git-for-windows/git/releases/download/v2.23.0.windows.1/PortableGit-2.23.0-64-bit.7z.exe#/dl.7z is not valid
PS C:\Users\Administrator.PC-20120727WEXY> scoop uninstall git
Uninstalling 'git' ().
'git' was uninstalled.
PS C:\Users\Administrator.PC-20120727WEXY> scoop install git
Scoop uses Git to update itself. Run 'scoop install git' and try again.
Installing 'git' (2.23.0.windows.1) [64bit]
操作超时
URL https://github.com/git-for-windows/git/releases/download/v2.23.0.windows.1/PortableGit-2.23.0-64-bit.7z.exe#/dl.7z is not valid``

**Comment by neolee** [comment]
网络问题，下载 git 安装包失败了，尝试换个网络或者代理试试，或者等一会儿重试。
