### ISSUE TITLE
我在学习用书中输入跟教材一样的代码，但是运行结果不一样

### ISSUE THREAD

**Issue by The993** [neolee/pilot#492]
file:///C:/Users/24978/Documents/Tencent%20Files/2497822197/FileRecv/MobileFile/IMG_20191113_205540.jpg

**Comment by neolee** [comment]
贴图失败，Wiki 里有说明如何贴图，支线课程四里也有。

**Comment by The993** [comment]
为什么会出现错误





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Neo Lee"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月18日(星期一) 下午3:35
收件人:&nbsp;"neolee/pilot"<pilot@noreply.github.com&gt;;
抄送:&nbsp;"一至如何"<2497822197@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [neolee/pilot] 我在学习用书中输入跟教材一样的代码，但是运行结果不一样 (#492)




Closed #492.

**Comment by The993** [comment]
老师你好，打开github的网站是需要外网的服务器吗？我按照编程课里的网址上网想打开，但网页显示找不到该网页
