### ISSUE TITLE
问题如果是closed就看不到回答了么？

### ISSUE THREAD

**Issue by 542809** [neolee/pilot#494]
遇到安装问题，看到有同样问题的提问，但是显示closed,看不到回答，是问题关闭后就不显示答案了么？还是可能问题就没有回答

**Comment by neolee** [comment]
你好像重复提了俩一样的问题。关闭只是个状态，不影响任何其他，答案当然可以看，没有就是没回答。网络问题大同小异，很多重复，并不会一一回答。

**Comment by neolee** [comment]
Dup of #493
