### ISSUE TITLE
对浮点数的取余操作在什么情况下是精确结果

### ISSUE THREAD

**Issue by imSeaton** [neolee/pilot#495]
![image](https://user-images.githubusercontent.com/56856685/68769698-ba91d280-065f-11ea-96f4-6d508c51f91d.png)

老师好，我发现在算术运算 a % b 中， 如果 b < 0.5 * a ，那么计算结果不是精确值（偶尔有精确值），但是如果 b >= 0.5 * a，那么计算结果都是精确值（我还没有发现反例）。
请问，什么情况下，浮点数计算的结果是精确值？并且在已知浮点数计算结果是精确值的情况下，是否仍然推荐使用浮点数的范围比较法代替相等判断？

**Comment by neolee** [comment]
好发现，好问题。

你发现的规律是对的，但并不是一个“显式行为”，也就是说并不是稳定可靠的规律，它与具体实现有关，未来完全有可能改变，所以千万不要依赖它来实现你的算法，还是要假定所有浮点数计算都是有误差的。

另外，我个人的观点是，整除这个运算还是应该局限于整数间，虽然 Python 支持浮点数的整除运算，但这个特性带来的好处远不如麻烦多，能不用就不用。
