### ISSUE TITLE
if else语句在代码框如何输入？

### ISSUE THREAD

**Issue by acexuan** [neolee/pilot#497]
![image](https://user-images.githubusercontent.com/50607017/68773993-6854af80-0667-11ea-9a9e-e03bd105fde1.png)
下图，python代码框里像教材里一行行输入，或是一整行一起输入，都显示错误，是什么原因？
![image](https://user-images.githubusercontent.com/50607017/68774121-94703080-0667-11ea-9280-1f71a041e903.png)

**Comment by sbiwgu** [comment]
print(n,'是奇数‘）是下面一行’

**Comment by sbiwgu** [comment]
而且要缩进

**Comment by acexuan** [comment]
> 而且要缩进

现在可以了，是因为没有缩进的问题，谢谢

**Comment by neolee** [comment]
分行输入不会有问题，但要注意前面同学提示的缩进问题。

另外注意输入时引号等字符一定要用英文半角的，不能用中文标点。
