### ISSUE TITLE
git commit 出错！

### ISSUE THREAD

**Issue by 18p2p** [neolee/pilot#498]
![`HML5) 9(N7BMF3PL9R%`HT](https://user-images.githubusercontent.com/48624321/68775650-ce423680-0669-11ea-9597-2d8ff3321ae6.png)

**Comment by 18p2p** [comment]
老师能否在支线课程里用到的git 命令再贴一下，视频里的命令字太小，感觉可能看错！

**Comment by neolee** [comment]
你做的基本都对，命令也没错，唯一问题出在 add origon 那一步，给出的服务器 repo 地址有问题，你输入的是 git-ssh 地址，支持这个协议在 Windows 下颇麻烦，所以你要使用 https 协议。

**Comment by 18p2p** [comment]
![PQ`2HS0~QUS{YL_)3S_~Q86](https://user-images.githubusercontent.com/48624321/68954911-e5b32800-07ff-11ea-8ac3-f89cba0a6d60.png)
老师应该地址转换正确了吧，可是在 *git commit -a -m "init commit"* 出错了！

**Comment by 18p2p** [comment]
![( J}JI({C1VTBYZD9WM4HGK](https://user-images.githubusercontent.com/48624321/68955799-c1584b00-0801-11ea-8b64-697576ea34e1.png)
*git remote add origin*
显示已存在

**Comment by 18p2p** [comment]
git push 时要求选择证书？

**Comment by neolee** [comment]
前一个截图显示你好像没有增加或者修改什么文件，没有可以 commit 的呀。

后面这个你就选一个好了，我没碰到但有人碰到过，好像第二第三个都可以。

**Comment by 18p2p** [comment]
`git remote add origin https://github.com/18p2p/18p2p.github.io.git`
老师执行这一步的时候就显示远程origin 已经存在了，是否是第一次提问时，远程HSS地址造成的（最前面一张截图）

**Comment by 18p2p** [comment]
现在是否先把origin远程仓库删除？

**Comment by neolee** [comment]
不需要，目前 origin 是对的。

**Comment by 18p2p** [comment]
老师OK了，我选第2项manage 输入账号密码就OK了！
