### ISSUE TITLE
macOS 安装Jupyter Lab 出错

### ISSUE THREAD

**Issue by kenkun-li** [neolee/pilot#5]
老师好！
在终端输入命令：pip install jupyterlab
提示：command not found

前面的步骤已经顺利做完了。
<img width="571" alt="屏幕快照 2019-10-23 上午12 11 27" src="https://user-images.githubusercontent.com/53461353/67300907-af002f80-f529-11e9-8487-0aaf36161a10.png">

**Comment by yayuehuizi** [comment]
我也碰到同样的问题

**Comment by yayuehuizi** [comment]
我后面用pip3 install jupyterlab命令出现了下载的进程，但是最后都是因为网速慢超时没有成功，不知道还有没有其他方法

**Comment by zhang-zedong** [comment]
试试在命令行中先输入`brew install pip3`，来先通过`Homebrew`安装`pip3`

**Comment by yayuehuizi** [comment]
我成功了，还是用的pip3 install jupyterlab，可能前面网速快，试了几次成功了，不过我是在code目录下装的

**Comment by zhang-zedong** [comment]
`pip3 install jupyterlab`，可能是`pip3`和`pip`在有的机器上被区分开了，楼上这样应该没问题。

**Comment by neolee** [comment]
使用 pip3 应该可以。晚点我会更新指引文档，感谢指出。
