### ISSUE TITLE
“$”符号不识别

### ISSUE THREAD

**Issue by hermionepei1029** [neolee/pilot#501]
![image](https://user-images.githubusercontent.com/55781929/68781977-8de7b600-0673-11ea-91fa-8c840e78546e.png)
如图所示

**Comment by neolee** [comment]
正确的命令不包括前面这个 $ 呀，为啥要输入这个？

**Comment by hermionepei1029** [comment]
因为在B站看您的支线课程的视频里面打了这个，所以以为是必要的，谢谢老师的及时回答！

**Comment by neolee** [comment]
操作以配置指南里为准，视频里那个是我环境里配置的提示符而已 😀
