### ISSUE TITLE
‘这种变量是整个类共有的，所有该类的对象实例共享’→‘这种变量是整个类共有的，所有该类的实例对象共享’

### ISSUE THREAD

**Issue by xiaoerhai** [neolee/pilot#503]
李骏老师，以上【对象实例】是否改成【实例对象】更好理解，和下文对应。

具体定位：【理解对象与类：Python 篇】  中的   【类定义与对象创建】  对【类变量】的定义。

**Comment by neolee** [comment]
这两个说法都可以，而且没有区别。单从一致性角度我回头会坐下检查，在这个课程中统一说法。多谢指出～
