### ISSUE TITLE
Terminal 里运行brew update时提示失败 RPCfailed

### ISSUE THREAD

**Issue by zhoujinyunzhouzhou** [neolee/pilot#505]
Terminal 里运行按照 步骤 到了 运行 brew update时提示失败  RPCfailed，在此之前我的MAC电脑里有anaconda-navigator的环境，已经安装了visual studio code 软件，并且可以写程序的。我打开Xcode界面在 VSCode 中按 ⌘⇧+P 打开命令窗口，输入 install，从弹出的命令中选择 Shell Command: Install 'code' command in PATH然后新建了文件夹并保存，后来回到 Terminal 窗口，在命令行界面操作：却提示ls: ↩︎: No such file or directory。不明白怎么回事儿，是我的anaconda-navigator的环境和Homebrew环境相冲突嘛？还是只能用Homebrew的安装包呢？
![14_55_11__11_14_2019](https://user-images.githubusercontent.com/49757857/68836187-bcf23c00-06f4-11ea-8b30-a7b77a38b557.jpg)
![15_14_02__11_14_2019](https://user-images.githubusercontent.com/49757857/68836188-bd8ad280-06f4-11ea-8cf8-1ceb52bb4af5.jpg)
![15_27_43__11_14_2019](https://user-imag@neolee s.githubusercontent.com/49757857/68836189-be236900-06f4-11ea-8eb3-923e880f55e6.jpg)
@

**Comment by zhoujinyunzhouzhou** [comment]
![Uploading 15_27_43__11_14_2019.jpg…]()

**Comment by neolee** [comment]
Duplicate of #506
