### ISSUE TITLE
Scoop 无法安装

### ISSUE THREAD

**Issue by lyq760208** [neolee/pilot#507]
李老师：
![image](https://user-images.githubusercontent.com/52565659/68839535-dd71c480-06fb-11ea-85dc-d067ecd6c314.png)
不明白为什么装不了？谢谢！命令是从网上直接复制过来的！

**Comment by sxuya** [comment]
同样现象，不知到什么情况呀，提示说「可以运行 scoop update」，可是运行就报错。

**Comment by sxuya** [comment]
兄弟，我按照下面的「重装 scoop」解决问题了：
https://github.com/neolee/pilot/wiki

**Comment by neolee** [comment]
@lyq760208 截图里看，你的 PowerShell 里没有 iwr 这个命令，说明你的 PowerShell 版本过低，请按照安装配置指南一步步来，一开始就要确认 PS 版本 >= 5 才行。
