### ISSUE TITLE
visual studio code 如何运行文件？

### ISSUE THREAD

**Issue by hermionepei1029** [neolee/pilot#508]
![image](https://user-images.githubusercontent.com/55781929/68849875-d9e73900-070d-11ea-9d3a-e09f24bea2d2.png)
如图，没有找到类似pycharm的工作台

**Comment by neolee** [comment]
可以在命令行界面执行，或者在 VSCode 的 Terminal 菜单下打开一个内置的命令行界面。

以及，你这文件存成 .txt 文件也不对，应该是 .py。

**Comment by hermionepei1029** [comment]
> 可以在命令行界面执行，或者在 VSCode 的 Terminal 菜单下打开一个内置的命令行界面。
> 
> 以及，你这文件存成 .txt 文件也不对，应该是 .py。
> 
> 最后，你的用语体现似乎是个 IDE 中毒症患者，我建议你改，从课程的配置指南开始一点点学起来。

老师，请问IDE中毒症是什么意思？

**Comment by neolee** [comment]
就是对某个 IDE 工具（譬如 PyCharm）比较依赖，如果从头开始了解命令行界面、Python 解释器，就可以很快学会各种新的工具。

**Comment by hermionepei1029** [comment]
> 就是对某个 IDE 工具（譬如 PyCharm）比较依赖，如果从头开始了解命令行界面、Python 解释器，就可以很快学会各种新的工具。

好的，明白了。谢谢老师指点~
