### ISSUE TITLE
Jupyter Lab 运行后出现密码页如何处理

### ISSUE THREAD

**Issue by robertswg001** [neolee/pilot#509]
![jupyter issure](https://user-images.githubusercontent.com/56988943/68877190-a1ad1e00-0740-11ea-8aff-d8d6d4518e43.png)

**Comment by neolee** [comment]
这个页面是如何出现的能说清楚吗？自动打开的还是你输入地址打开的？如果后者输入的地址是什么？

**Comment by robertswg001** [comment]
是运行Jupyter Lab后自己打开的

**Comment by neolee** [comment]
网址你应该拷贝运行 `jupyter lab` 的命令行界面里 `http://localhost:8888/lab` 打头的**一整行**。
