### ISSUE TITLE
安装 jupyterlab 出现 `无法将 'pip' 识别为 cmdlet、函数...`

### ISSUE THREAD

**Issue by azheng526** [neolee/pilot#51]
![image](https://user-images.githubusercontent.com/50059311/67460114-cc89e200-f66c-11e9-988c-05cbe81f85d2.png)

**Comment by neolee** [comment]
试试这个：

```powershell
python -m pip install jupyter
```

如果成功就：

```powershell
cd pilot-student
python -m jupyter lab
```

**Comment by azheng526** [comment]
![image](https://user-images.githubusercontent.com/50059311/67460806-7d44b100-f66e-11e9-867c-cf4c6bd47ed0.png)
这样好像OK了，李老师

**Comment by neolee** [comment]
啊，前面我输错了一点，应该是：

```powershell
python -m pip install jupyterlab
```

然后：

```powershell
python -m jupyter lab
```

**Comment by azheng526** [comment]
![image](https://user-images.githubusercontent.com/50059311/67478505-cb69ac80-f68e-11e9-9402-eab1d772443d.png)
程序在浏览器打开了https://github.com/neolee/pilot/issues/51

**Comment by azheng526** [comment]
http://localhost:8888/lab应该是已经把您的git教学相关内容下载到我的主机了。

**Comment by neolee** [comment]
这样应该就是好了，以后你就用 `python -m jupyter lab` 来运行 Jupyter Lab 就好了。

**Comment by azheng526** [comment]
好的，谢谢老师！
