### ISSUE TITLE
Scoop 安装失败，但是无法清理掉之前的安装程序

### ISSUE THREAD

**Issue by hermionepei1029** [neolee/pilot#510]
![image](https://user-images.githubusercontent.com/55781929/68883799-b1cafa80-074c-11ea-88ea-9cbf710fa57b.png)
Wiki上边的两种方式都试过了，均失败

**Comment by neolee** [comment]
截图上看不出你试了什么和如何失败的，不好判断。

第一句失败是因为权限不足，很多同样问题的 issue，查一下就能找到，解决办法是换一个管理员权限的命令行界面 PowerShell (Admin) 就可以了。

其他的还是需要重装 Scoop，Wiki 里有指引。
