### ISSUE TITLE
笑来老师的《区块连小白书》目录是如何做的？

### ISSUE THREAD

**Issue by qihongsong** [neolee/pilot#511]
笑来老师《区块连小白书》用打开之后，左侧会有目录，这个目录是怎么做的呢？谢谢并期待老师的耐心解答

**Comment by neolee** [comment]
如果你指这个页面的话：

https://blockchainlittlebook.com/

应该是用 GitBook 制作的：

https://www.gitbook.com/

**Comment by qihongsong** [comment]
好的，太感谢了，谢谢老师



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Neo Lee <notifications@github.com&gt;
发送时间: 2019年11月15日 12:08
收件人: neolee/pilot <pilot@noreply.github.com&gt;
抄送: qihongsong <474858954@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[neolee/pilot] 笑来老师的《区块连小白书》目录是如何做的？ (#511)




如果你指这个页面的话：
 
https://blockchainlittlebook.com/
 
应该是用 GitBook 制作的：
 
https://www.gitbook.com/
