### ISSUE TITLE
在运行 scoop update 时出现以下错误

### ISSUE THREAD

**Issue by zjutimes** [neolee/pilot#512]
PS C:\Users\95172> scoop update 
& : 无法将“C:\Users\95172\scoop\shims\..\apps\scoop\curren
t\bin\scoop.ps1” 项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名
称的拼写，如果包括 路径，请确保路径正确，然后再试一次。 所在位置 C:\Users\9517
2\scoop\shims\scoop.ps1:3 字符: 71 + ... on.expectingInput) { $input | & $path
  @args } else { & $path  @args  . .. +
                      ~~~~~     + CategoryInfo          : ObjectNotFound: (C:\Users\95172\...t\bin\scoop    .ps1:String) [], CommandNotFoundException     + FullyQualifiedErrorId : CommandNotFoundException

**Comment by neolee** [comment]
Scoop 没装好，参照 Wiki 里的指引重装 Scoop。

**Comment by zjutimes** [comment]
已经解决，多谢
