### ISSUE TITLE
定义函数用这样的代码风格好不好？

### ISSUE THREAD

**Issue by hermes0911** [neolee/pilot#513]
看网上一些代码，在定义函数的时候代码风格大概如下：
```
def foo(name: str, age: int) -> None:
    pass
```
之前不明白是什么意思，后来搜了下，大概就是作者把参数的数据类型和函数最后返回的数据类型标示了出来，这样写有没有必要，会不会显得不够简洁？

**Comment by neolee** [comment]
你说的这个叫 *type hints*，是 [PEP 484](https://www.python.org/dev/peps/pep-0484/) 提出的语法，Python 3.5 正式转正。到目前为止应用并不算很多，大部分 Python 开发者认为这个特性的性价比不高。我个人认为这里面有习惯原因，也和团队有关，所以这是个比较复杂的软件工程问题（偏管理）。

我认为在学习 Python 时不需要用这样的语法，倒是应该养成习惯：在定义比较复杂的函数时用一段注释写清楚函数的输入是什么以及什么类型，返回值是什么以及什么类型。所谓“复杂的函数”，指的是光看函数及其参数名字猜不出来是干啥的那些。
