### ISSUE TITLE
依葫芦画瓢完成类定义与对象创建&一些思考

### ISSUE THREAD

**Issue by Amanda-6789** [neolee/pilot#514]
<img width="658" alt="屏幕快照 2019-11-15 下午1 32 33" src="https://user-images.githubusercontent.com/53425091/68919479-3d747380-07ad-11ea-9da3-b1e8fab8941e.png">

上述是依葫芦画瓢的几段代码。

李老师，课程中关于父类、子类、泛化、继承、多态、覆盖的概念我感觉比较复杂，有些思考和疑惑请老师点评。比如如果定义了一个类（*class*）“灯”，再泛化出一些特有的共性，成为公共的父类；同时“灯”的子类继承了“灯”的属性。那就是说，任何抽象的一类都可以泛化出父类，也会有子类继承。所以复杂的程序就像家谱，可以划小责任单元——“责任分离，分而治之”。

**Comment by neolee** [comment]
关于这类“抽象思维”，绝不是几天就能想通透的，需要若干年的思维练习。目前能做的，是养成一些好的“思维习惯”。下面是一些例子：

* 用一段代码完成一个任务之后，想想这个解决方案是不是有普遍意义？是不是可以写成一个函数以便复用？如何设计这个函数的输入和输出，使得它用起来最顺手？

比如下面的代码（来自教材里的例子），是不是可以变成一个通用的函数？
```python
while True:
    try:
        x = int(input('Please enter a number: '))
        break
    except ValueError:
        print('Not a valid number. Try again...')
```

* 随便拿一个概念来，试着举出比它更一般的例子，以及比它更具体的例子。

比如“苹果”，比它更一般的概念是什么？“水果”？如果你去查资料，会发现苹果在科学分类上属蔷薇科苹果属，山楂与它同属，桃与它同科，所以在植物分类上比苹果更一般的概念有很多层级；从不同的分类维度来考虑，比它更一般的概念还可以是“球状物”，球状物就多了，毛线球、地球都是；或者从“味道是甜的”这个特征出发，可以有更一般的概念“甜的食物”，等等。这些更一般的概念都可以是泛化出来的“父类”，这个思考过程可以训练你从不同维度看一个东西，找到它的“特征”的能力。

从一个概念出发，泛化是提炼它的抽象特征的过程，而派生是利用它的抽象特征的过程。

**Comment by Amanda-6789** [comment]
比“苹果”更一般的概念会分出很多层级，也就是某个概念，有可能分到不同的类中。

老师所说的要锻炼思考“比这个概念更一般的例子”，就是要不断练习**抽象的思维能力**。我理解就是将泛化的父类包含更多的抽象概念，尽量全面，尽量减少Exception。

两天前提问的时候，我只考虑了泛化会导致层级越来越多，父类越来越多。并没有考虑尽量抽象概念。

谢谢老师，持续练习抽象思维力。

**Comment by neolee** [comment]
明天的课上还会讲这个话题 😃
