### ISSUE TITLE
同一段代码在 jupyter 可以运行但使用终端运行就会报错

### ISSUE THREAD

**Issue by zyh364267040** [neolee/pilot#515]
Mac上面同一段代码
同一段代码, 在jupyter上可以运行, 但是把这段代码粘贴到vscode上面, 然后使用终端运行就会报错, 请问这是什么问题,   报的错可能是使用非法字符, 但是我的每一个字符都是使用了英文下的, 还有我从jupyter上复制粘贴还是不行, 还会报错
![WeChatc0b181052f555775563698fae534b148](https://user-images.githubusercontent.com/44403599/68950005-3e7dc300-07f6-11ea-993d-ce2970ccaeb0.png)

**Comment by neolee** [comment]
你在命令行界面执行 `python -V` 看看 Python 版本，很可能是 2.7，那么你就应该用 `python3` 来运行你的 `hello.py`。

**Comment by zyh364267040** [comment]
谢谢老师,我刚才看了一下,确实是2.7,好像是mac上自带的,已经通过百度修改启动3.7的了
