### ISSUE TITLE
安装和运行 Jupyter Lab 出错

### ISSUE THREAD

**Issue by 542809** [neolee/pilot#516]
<img width="571" alt="屏幕快照 2019-11-15 22 29 36" src="https://user-images.githubusercontent.com/57673231/68950723-b4365e80-07f7-11ea-9314-cf151c382cee.png">

**Comment by neolee** [comment]
下面两行命令要一行一行的执行，不要一起贴上去……

```shell
python3 -m pip install -U pip
pip3 install jupyterlab
```

**Comment by 542809** [comment]
<img width="574" alt="屏幕快照 2019-11-16 12 41 15" src="https://user-images.githubusercontent.com/57673231/68988227-d3bc9e00-086e-11ea-9e99-950cce7191b4.png">
<img width="573" alt="屏幕快照 2019-11-16 12 43 45" src="https://user-images.githubusercontent.com/57673231/68988228-d4553480-086e-11ea-8997-ec27fbc18f8b.png">

**Comment by neolee** [comment]
网络问题，重试下，或者换换网络或者挂代理。

**Comment by 542809** [comment]
安装好了，谢谢老师
