### ISSUE TITLE
VSCode 不能运行

### ISSUE THREAD

**Issue by hermionepei1029** [neolee/pilot#518]

**Comment by hermionepei1029** [comment]
同样的代码放在Jupyter上就可以运行，但是放在VSC中就没有反应。
问题如图，谢谢李老师~
![image](https://user-images.githubusercontent.com/55781929/68990628-66216980-0890-11ea-84d9-78ec53ac9a1e.png)

**Comment by neolee** [comment]
这运行没问题，你运行的代码只不过是返回一个 True 或者 False，又没有 `print()` 来输出啥，没有显示结果很对。

**Comment by hermionepei1029** [comment]
谢谢老师，发现再VSCode里把想输出得东西前面加上print函数就可以了~
