### ISSUE TITLE
如何升级 git

### ISSUE THREAD

**Issue by xiaoerhai** [neolee/pilot#519]
谷歌后出现如下error：

PS C:\Users\erhai> git update-git-for-windows
Git for Windows 2.23.0.windows.1 (64bit)
Update 2.24.0.windows.2 is available
Download and install Git for Windows 2.24.0(2) [N/y]? y
-=O=-#    #    #     #
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github-production-release-asset-2e65be.s3.amazonaws.com:443
PS C:\Users\erhai>

**Comment by neolee** [comment]
如果按照配置指南做，应该是 `scoop update git`。

你碰到的问题是网络问题，下载安装包出错。

**Comment by xiaoerhai** [comment]
运行`scoop update git`时，提示：`基础连接已经关闭: 发送时发生错误。`它是指最源头的安装包不允许访问下载了吗？
```python
Scoop was updated successfully!
git: 2.23.0.windows.1 -> 2.24.0.windows.2
Updating one outdated app:
Updating 'git' (2.23.0.windows.1 -> 2.24.0.windows.2)
Downloading new version
基础连接已经关闭: 发送时发生错误。
所在位置 C:\Users\erhai\scoop\apps\scoop\current\lib\install.ps1:130 字符: 9
+         throw $e
+         ~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], WebException
    + FullyQualifiedErrorId : 基础连接已经关闭: 发送时发生错误。
```

**Comment by neolee** [comment]
没啥，就是网络不行。
