### ISSUE TITLE
type 的类型为什么不是 builtin_function_or_method 而是 type

### ISSUE THREAD

**Issue by Yi-chenglong** [neolee/pilot#520]
我们使用type的时候是把他当作一个函数的，比如type(3)的输出是int，然后我就尝试了一下type(print)，返回的是builtin_function_or_method，这个好理解，因为print是内建的函数，但是当我尝试type(type)的时候，我认为应该也返回的builtin_function_or_method，但是结果返回是type，这个就不理解了，谁能解答一下？

**Comment by neolee** [comment]
type 在 Python 3 中是个极其特殊的东西，称为“metaclass”，所以比较特别……
