### ISSUE TITLE
如何使用 VSCode 的一些基本功能？

### ISSUE THREAD

**Issue by xiaoerhai** [neolee/pilot#521]
看完老师讲的支线课程，发现还是不能用vscode来运行代码。然后突然发现自己对vscode这个软件也很陌生。

**Comment by hermionepei1029** [comment]
有同样的困扰

**Comment by neolee** [comment]
这种工具的使用，其实最好的办法是自己探索和尝试，有收获了就记录下来，过一段时间整理笔记就是一篇不错的文章。
