### ISSUE TITLE
安装 git 失败

### ISSUE THREAD

**Issue by xiaozhiqiang2020** [neolee/pilot#522]
提示操作超时，然后给出一个URL
![image](https://user-images.githubusercontent.com/57823772/69001270-78de8180-0916-11ea-8937-e5758ff06fec.png)

**Comment by hezongjun** [comment]
同问

**Comment by hezongjun** [comment]
PS C:\Users\HP> scoop install git
Scoop uses Git to update itself. Run 'scoop install git' and try again.
Installing 'git' (2.24.0.windows.2) [64bit]
PortableGit-2.24.0.2-64-bit.7z.exe (41.8 MB) [>                                                                                                                ]   0%
操作已超时。
URL https://github.com/git-for-windows/git/releases/download/v2.24.0.windows.2/PortableGit-2.24.0.2-64-bit.7z.exe#/dl.7z is not valid

**Comment by michaelmakun** [comment]
我也碰到这个情况了，感觉不是网络的问题，初步怀疑是电脑的问题，我那台电脑也是HP，但是时间比较长了，准备配置一下试试，结果就卡在这一步了，我敢肯定不是家里的网络问题。

一模一样的错误，搜了好多地方，没找到合适的解决方案，有没有哪位朋友解决过了，给个提示参考一下

**Comment by neolee** [comment]
@michaelmakun 为什么你可以确定不是网络问题呢？

**Comment by Traveler-in-future** [comment]
同样的情况 是需要换个时间再试试么
