### ISSUE TITLE
VSCode 中修改文件后输入 git status 后显示无提交

### ISSUE THREAD

**Issue by wangbing007** [neolee/pilot#523]
打开vscode后创建了today.py:
from datetime import datetime
print(datetime.now().strftime('今天是%Y年%m月%d日'))
也修改了README.md里的一些 
可回到命令行输入git status还是显示无提交

**Comment by neolee** [comment]
有截图吗？

**Comment by wangbing007** [comment]
<img width="739" alt="截屏2019-11-17下午1 04 21" src="https://user-images.githubusercontent.com/57426218/69003347-e4d2e100-093a-11ea-93ca-3cb98aa0086d.png">

**Comment by neolee** [comment]
首先，有俩问题：1. 你代码的第二行完全写错了哈；2. 如果要学习 git 操作，建议你另开一个目录并创建 git 仓库，，不要开在学习用书的 repo 里面，毕竟这是学习用的，保持其干净、目的纯粹较好。

这些问题先放一边，回到你的问题“输入 git status 还是显示无提交”，所以你需要把你执行 `git status` 的情况截屏出来，才对问题的表述有帮助，是吧？

不过大概能猜出来，可能是你没有执行 `git add hello.py` 这样的命令，所以新建的文件未加入 git 版本管理，又或者你没有正确理解 `git status` 返回的信息。

90% 的情况下，把问题表述清楚，自己就能找到答案。
