### ISSUE TITLE
第9章学习用书执行问题点

### ISSUE THREAD

**Issue by robertswg001** [neolee/pilot#525]
![程序运行问题点](https://user-images.githubusercontent.com/56988943/69005733-3726f880-0961-11ea-9fb1-e62dc5a231cc.png)

![9-structure 问题点](https://user-images.githubusercontent.com/56988943/69005746-59b91180-0961-11ea-8173-9b2486556b87.png)
这两处程序与教材一致，执行结果不一样，尤其是第二点出错，找不到问题原因，求指导

**Comment by neolee** [comment]
第一个问题，我猜你可能在定义 Dog 类和创建 a、b 对象实例之后没有运行 `Dog.kind=...` 这行代码，或者之前运行过，但后面重新运行了定义 Dog 和 a、b 实例的代码。

第二个问题，实例化时说不应该有参数，这就是说你的 `Animal` 类里的 `__init__()` 方法除了 `self` 以外没有其他参数，你可以检查下你的类定义是没写对，还是修改后没执行。

**Comment by robertswg001** [comment]
将教材用书程序拷贝过来后就ok了, 没找到原因，^_^

**Comment by neolee** [comment]
那你可能就少学了很多东西，太遗憾了。

**Comment by robertswg001** [comment]
到时再自己输入一遍，找下原因

**Comment by robertswg001** [comment]
![9 structure reason](https://user-images.githubusercontent.com/56988943/69026250-35167580-0a05-11ea-9fee-c7659b6c906e.png)

找到原因了。

**Comment by neolee** [comment]
Nice!
