### ISSUE TITLE
类变量和对象方法等为什么可以直接执行并得到结果？而普通变量的输出需要使用 print 函数

### ISSUE THREAD

**Issue by spring-ap** [neolee/pilot#527]
![image](https://user-images.githubusercontent.com/57279823/69006916-50d03c00-0971-11ea-8e53-b95e563dd3a3.png)
如图中代码段8，9，10.直接编写类或对象的属性执行后就能得到结果，但是如果将类变量赋值给一个变量`b=c.name`就必须使用printf函数输出。

**Comment by neolee** [comment]
严格来说，所有你希望输出到命令行界面的，都应该用 `print()` 来输出。

在 Python 解释器和 Jupyter 里如果你某一行只写了一个变量（无论它是一般的变量还是对象的属性），会得到这个变量的值，但这不是你的程序输出的，而是解释器（为了你的方便）显示给你看的。你可以建立一个空的 `.py` 文件，然后在里面写下面这样的代码：

```python
a = 42
a
```

然后用 `python xxx.py` 来运行它，你会发现什么输出都没有，因为这种方式运行你的程序和在解释器环境不一样，解释器不会额外打印一个变量的值给你看。

所以，总结下来就是，你想要显示出来的东西，要用 `print()` 或者类似的方法来输出。
