### ISSUE TITLE
两个对象的方法分别调用后，仅输出一个结果。

### ISSUE THREAD

**Issue by spring-ap** [neolee/pilot#528]
![image](https://user-images.githubusercontent.com/57279823/69006988-8fb2c180-0972-11ea-8e14-130c2260e59a.png)
上图我取消了每个子类的方法重命名的语句`bark=voice`和`mew=voice`而后，在for循环后添加了两个对象的voice方法调用`d.voice`和`c.voice`，但是输出结果总是一个，并且为后一个。
然后我又试图将那两个语句添加上，for循环后`d.bark`和`c.mew`，执行结果仍然为一个“meow-meow“

**Comment by neolee** [comment]
请参考这个问题 #527
