### ISSUE TITLE
Jupyter 学习用书不显示要输入的代码

### ISSUE THREAD

**Issue by kanglei1985** [neolee/pilot#529]
![image](https://user-images.githubusercontent.com/53995486/69007451-d86d7900-0978-11ea-9826-061cd845e601.png)

**Comment by michaelmakun** [comment]
对， 就是这样，需要配合教学用书一起使用

**Comment by neolee** [comment]
@michaelmakun 所以需要你照着教材在空格里输入代码，你有仔细看过指南吗？

**Comment by kanglei1985** [comment]
> 对， 就是这样，需要配合教学用书一起使用

明白了，谢谢
