### ISSUE TITLE
while 循环的结果 n 的值为什么每次都不一样呢？

### ISSUE THREAD

**Issue by weiwei886** [neolee/pilot#530]
from random import randrange

while True:
    n = randrange(-2, 5)
    if n < 0:
        break
    elif n % 2 == 0:
        print(n, 'is even')
    else:
        print(n, 'is odd')

**Comment by weiwei886** [comment]
3 is odd
0 is even
1 is odd
2 is even
1 is odd
2 is even
3 is odd有时候是好几个，有时候就一个

**Comment by neolee** [comment]
你理解 `randrange()` 这个函数是干啥的么？

**Comment by xiaoerhai** [comment]
> 你理解 `randrange()` 这个函数是干啥的么？

每次执行的时候在给定的范围里取一个随机数。

**Comment by weiwei886** [comment]
如果前面5个随机数都是大于零的，那么显示5个数基数或偶数，然后继续循环，如果小于零，循环结束。这么理解对吧

**Comment by neolee** [comment]
@weiwei886 `randrange(a, b)` 是在 a 到 b-1 的整数里随机选一个返回，所以那段代码的意思是：随机从 { -2, -1, 0, 1, 2, 3, 4 } 中返回一个数，如果这个数大于等于零，那么打印一句话，说明它是奇数或者偶数，如果这个数小于零就终止循环。

所以并不是一定有五个数，可能第一次就来了个 -1 或者 -2，就直接结束了。其实你多跑几次就能大致明白了。

**Comment by weiwei886** [comment]
明白了，谢谢老师，刚开始读程序不够仔细，然后语言表达也不够清晰，老师辛苦啦。
