### ISSUE TITLE
给父类的 method 取一个别名有什么用处呢

### ISSUE THREAD

**Issue by xiaowei0189** [neolee/pilot#532]
class Cat(Animal):
    
    kind = 'felidae'
    
    def voice(self):
        return 'meow-meow'
    
    mew = voice

**Comment by neolee** [comment]
没啥特别的用处，说明子类定义自己的新方法的一个例子。

要说的话，也有用，叫做“增加可读性”，毕竟 `cat.meow()` 比 `cat.voice()` 看着更有意义，是吧？

另外可以参见 #526
