### ISSUE TITLE
安装无法继续 系统是 Win7 有装过 Python

### ISSUE THREAD

**Issue by lyq760208** [neolee/pilot#533]
![image](https://user-images.githubusercontent.com/52565659/69032885-8da33e00-0a18-11ea-8882-d58167e4b2cd.png)
PS C:\Users\Administrator> $PSVersionTable.PSVersion.Major
2
PS C:\Users\Administrator>
返回值是2，李老师说要 >5  才能继续。求助各位。

**Comment by neolee** [comment]
配置指南里有说，不到5的话需要安装两个包。

不过还是建议你升级到 Windows 10，会少很多麻烦。你现在的环境又是 Win 7，又有以前残留的 Python，可以预见会有不少麻烦。
