### ISSUE TITLE
李骏老师编程课第一节编程环境配置 macOS 篇 完成

### ISSUE THREAD

**Issue by zhoujinyunzhouzhou** [neolee/pilot#534]
经历了连续一周，各种配置环境失败，老师回答过一次提问，说是网络问题，我下载Homebrew
输入：/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" ↩︎
这个命令将下载并执行 Homebrew 的安装脚本，自动安装 Homebrew 到 /usr/local/ 目录下；注意提示 Password: 的时候输入你的登录密码并回车。 这一步总是失败。。。。检查了网络没有问题，我尝试吧自己mac更新了系统，终于在今晚 `配置好了环境，第一章节的步骤全部完成。开心。不放弃慢慢摸索真的就好了，接下来第二章```
![李骏老师编程课    @neolee 第一节完成](https://user-images.githubusercontent.com/49757857/69055781-8fd1c080-0a49-11ea-88a4-0fddab6b55da.jpg)

**Comment by neolee** [comment]
恭喜！后面其实比这个简单，keep going!

**Comment by rightyes** [comment]
请问这个登录密码是输入icould 密码吗？我也老是出错
