### ISSUE TITLE
Fork 和 Branch 的区别是什么?

### ISSUE THREAD

**Issue by xiaoerhai** [neolee/pilot#536]
完整地看了2遍视频和实操了视频里提到的命令，对Fork 和Branch 的理解如下:
Fork：
就是复制整个repository，且在副本可以随意改动的同时支持pull request。

Branch：
跟踪repository里的某个文件的所有版本状态，且支持版本与版本之间的合并。

以上不确定自己描述的对不对。等待老师的解答。

**Comment by xiaoerhai** [comment]
理解，然后它们都支持合并，是吧？

**Comment by neolee** [comment]
Branch 之间可以合并（merge），fork 的 repo 之间不能直接 merge，要通过 pull request 来做。

**Comment by xiaoerhai** [comment]
清楚了，谢谢老师。
