### ISSUE TITLE
更改文件名后为什么不能push到github上？

### ISSUE THREAD

**Issue by xiaoerhai** [neolee/pilot#537]
为了测试自己是否能把本地修改过的文件push到GitHub上，我做了如下2次尝试：

第一次：只更改文件名，将【b-final.ipynb】更改成【B-final.ipynb】，但push失败，GitHub上未同步。
（背景：由于由于 GitHub 的某些 bug，无法打开链接，显示`Sorry, something went wrong. Reload?`，想只改文件名来测试）

第二次：只更改vor这个文件里的内容，push成功，GitHub上已同步。

以上，期待老师的解答。感谢！

**Comment by neolee** [comment]
如果改了名字，用 `git add` 和 `git commit` 的话，是会产生新的版本，也可以 push 到 origin 的。

你的例子里之所以没有变化（你可以多用 `git status` 来看变化），是因为缺省配置下 git 对文件名是不区分大小写的，所以你的修改对 git 来说无意义。可以通过修改 git 的 `core.ignorecase` 配置来强制让 git 区分文件名大小写，不过一般来说不需要这样。

**Comment by xiaoerhai** [comment]
理解，难怪当时git status 的结果没有发生变化。感谢老师的解答~
