### ISSUE TITLE
获取学习用书的第二步中，输入cd pilot-student 时碰见这个问题

### ISSUE THREAD

**Issue by 111xiaochao111** [neolee/pilot#538]
PS C:\Users\A> cd Code
PS C:\Users\A\Code> git clone https://github.com/111xiaochao111/pilot.git
Cloning into 'pilot'...
remote: Enumerating objects: 36, done.
remote: Counting objects: 100% (36/36), done.
remote: Compressing objects: 100% (26/26), done.
remote: Total 209 (delta 15), reused 24 (delta 10), pack-reused 173R
Receiving objects: 100% (209/209), 4.91 MiB | 12.00 KiB/s, done.
Resolving deltas: 100% (107/107), done.
PS C:\Users\A\Code> cd pilot-student
cd : 找不到路径“C:\Users\A\Code\pilot-student”，因为该路径不存在。
所在位置 行:1 字符: 1
+ cd pilot-student
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\A\Code\pilot-student:S
   tring) [Set-Location], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.SetLo
   cationCommand

**Comment by neolee** [comment]
你 fork 和 clone 的是我们的教材，所以他的缺省目录名是 `pilot`；

你需要 fork 和 clone 的是学习用书： https://github.com/neolee/pilot-student
它的缺省目录名才是 `pilot-student`。

`cd pilot-student` 的意思是进入名为 `pilot-student` 的子目录，如果这个目录都不存在，自然没法进入。你可以用 `ls` 命令来查看当前工作目录下有哪些子目录和文件。

Wiki 里面的支线课程第一讲可能值得一看。
