### ISSUE TITLE
支线课程 git 第二节

### ISSUE THREAD

**Issue by ray-zheng** [neolee/pilot#539]
![image](https://user-images.githubusercontent.com/48572098/69148650-b823f280-0b0f-11ea-8aa4-1c5ee49b528f.png)
输入了git commit 后没有自动开启visual studio code，请问是什么原因，谢谢

**Comment by neolee** [comment]
你没有按照教程讲的做 git 基础配置（`core.editor` 配置），所以 git 缺省打开了这个界面，这是一个命令行编辑器叫 Vim，这个恐怕不适合你，你先按 ESC 键，然后输入 `:q!` 退出。然后就可以去补前面的 git 配置工作了。

**Comment by ray-zheng** [comment]
![image](https://user-images.githubusercontent.com/48572098/69150450-a6444e80-0b13-11ea-939c-c4e719365eec.png)
我已经配置了，而且我用了 git config --list 查过

**Comment by ray-zheng** [comment]
啊，不好意思，好像输入错了，是editor
