### ISSUE TITLE
scoop update failed怎么解决呀

### ISSUE THREAD

**Issue by Ppluckyone** [neolee/pilot#541]
PS C:\Users\DELL>  scoop update
Updating Scoop...
fatal: the remote end hung up unexpectedly
error: RPC failed; curl 56 OpenSSL SSL_read: Connection was reset
fatal: early EOF
fatal: index-pack failed
Scoop update failed.

**Comment by Ppluckyone** [comment]
刚刚试了下，应该是网络的原因，终于配置完成了，要抓紧时间跟上老师进度了，哈哈

**Comment by neolee** [comment]
Nice! Keep going!
