### ISSUE TITLE
关于基类（父类）、衍生类（子类）的属性与方法实现规则的逻辑与原理设置的疑问

### ISSUE THREAD

**Issue by ZhaiGuangkai** [neolee/pilot#542]
前提：在知道这是一种规则的情况下，可以正常使用，但是出于一种知其然不知其所以然的状态，所以来请教，希望能解惑。
正文(在类的定义中）：
  一.方法   使用类似  run(self,data)  中 self 指代所定义的类，data 指代交给类处理的数据。关于self知道了是PY语言设计时候就这么定义的，那么我们重新设计一门语言的时候觉得这样不好，那么就可以在编写去掉self，让编译器or语言基础判断中自带这个功能就可以了？
  二.属性   kind=‘’  这个类似标签吗？这种属性的定义应该有很多个吧？方法是一个动态的过程，那么属性就是一种静态的。
          1.假定基类animal的 kind =‘哺乳动物’  衍生类cat的 kind=‘猫科’、dog的kind=‘犬科’。当调用衍生类cat.kind=‘猫科’，那么在我需要判断或者告知程序外的人cat是否是哺乳动物的时候cat.kind输出是‘哺乳动物’怎么做呢？（突然想起也许有的东西可以去敲一敲试试，不过还是先提出来放在这）。
          2.int是数字5的类型，那么数据的类型之间也是有包含关系的，也可以说是基类和衍生类的之间的关系了？那么数据类型与包含的数据之间为什么不可以是基类和衍生类的关系呢？另外数据定义之初的理念、规则。。。是什么样的呢？

  以上。粗鄙之处请勿见怪。感谢

**Comment by neolee** [comment]
第一个问题，关于对象方法的定义。

当我们使用一个对象 obj 的属性或方法时，通常会使用类似这样的语法：

```python
print(obj.name)
obj.do_something(a, b)
```

也就是对象 `obj` 在前，跟一个点 `.`，后面是属性或者方法的名字。这个语法基本是所有具有面向对象特征的编程语言都一致的（有些语言会用 `->` 代替 `.`）。

问题是，当我们定义这个对象的类的时候还没有创建具体对象，在方法定义体里想引用对象的属性或者方法怎么办呢？

这是一个所有面向对象语言都会面临的问题，解决方案也基本一样，那就是允许我们在定义方法时使用一个特殊的对象，来指代未来创建出来的对象。这个对象有的语言里叫 `self`（Python、Objective-C 等），有的语言里叫 `this`（C++、Java 等），而差别在于这个 `self` 或者 `this` 从哪儿来。

Python 强制这个 `self` 作为方法的第一个输入参数，这样 `self` 的来历就很简单了——作为参数传进来的，在方法定义里就可以当个普通的变量用了。但代价是方法的定义和调用格式不一样了——调用时并不用直接传递这个参数，而是通过 `obj.do_something(a, b)` 这种方式间接提供 `obj` 对象给 `do_something` 方法，所以其实有点像是 `do_something(obj, a, b)` 的意思，但又不能这么写。

其他主流语言都不是这样做的，C++、Java、Objective-C 里的对象方法不需要带有 `self` 这样的参数，方法定义和调用的格式是一样的，但在方法定义体中可以直接使用 `self` 或 `this` 对象。例如 C++ 的例子是这样的：

```cpp
class Box {
   private:
      double length;
      double breadth;
      double height;
   public:
      Box(double l = 2.0, double b = 2.0, double h = 2.0) {
         this->length = l;
         this->breadth = b;
         this->height = h;
      }
      double volume() {
         return length * breadth * height;
      }
      int compare(Box box) {
         return this->volume() > box.volume();
      }
};
```

这个做法的好处是方法调用和定义的格式保持一致，但如果问“这个 this 是哪儿来的”，就没法回答了，只能说，这是个 *magic*，编程语言让你可以在类定义里使用这个魔法。

凡事有得必有失，就看你更在乎哪个了。我个人不太喜欢 Python 的这个选择，因为后一种做法我认为更容易解释也更容易被理解，你觉得呢？

另外还有关于 `super` 的问题。如果我们定义对象的方法时想使用父类定义的某个方法，就需要一个指向父类对象的变量，这在 Python 里需要调用一个特殊函数 `super()` 来取得，`super()` 和 `self` 类似，只不过一个里面包含的是父类版本的实现，一个是自己版本的实现，但一个是函数调用，一个是输入参数，这看上去就不一致了。

在 C++、Java 等语言里没有这种不一致的问题，它们反正有一个魔法的 `this` 或者 `self` 了，那么再加一个魔法 `super` 也没啥感觉，所以…

**Comment by neolee** [comment]
第二个问题，关于对象属性和类属性。

对象的属性就是对象的一些特征值，比如机器人的高度、重量、颜色、型号等，这些特征值里，有些是各个对象实例独自拥有的特征，可以各式各样，这些就是“实例变量”；但有些是同一个类的对象实例共享的，这些就是“类变量”。一般来说，类变量就应该用类名加 `.` 加变量名来读写，而实例变量则用对象实例名加 `.` 加变量名来读写。所以可以认为类变量是类的属性，而实例变量是对象的属性。

在大多数情况下，类变量用的并不多，绝大部分情况下应用到的都是对象变量。

在我们那个例子里，`Cat` 类的 `kind` 属性，`Cat.kind` 的值就是 ‘猫科’，如果你想判断 `Cat` 是不是哺乳动物，就需要判断 `Cat` 的祖先（父类或者父类的父类或者父类的父类的父类...）里有没有 `kind` 属性值为 ‘哺乳动物’ 的类。当然了，如果你真要做这个事情，有更好的解决方案，不必依赖与 `king` 这个类属性，可以设计别的机制来解决。

**Comment by neolee** [comment]
第三个问题，关于 Python 的基础类型之间的关系，`int` `float` `str` `bool` 都是 Python 内置定义的 `class`，他们之间大多没啥关系，彼此独立，但有些有关系，比如之前提过 `bool` 是 `int` 的子类。

你问的“数据类型与包含的数据之间为什么不可以是基类和衍生类的关”，就属于概念完全混乱了。5 的类型是 `int`，`int` 是类，`5` 是一个对象，怎么可能是基类和派生类的关系？

“数据定义之初的理念、规则是什么样的” 这个问题不太能理解。

**Comment by ZhaiGuangkai** [comment]
> 
> 
> 第一个问题，关于对象方法的定义。
> 
> 当我们使用一个对象 obj 的属性或方法时，通常会使用类似这样的语法：
> 
> ```python
> print(obj.name)
> obj.do_something(a, b)
> ```
> 
> 也就是对象 `obj` 在前，跟一个点 `.`，后面是属性或者方法的名字。这个语法基本是所有具有面向对象特征的编程语言都一致的（有些语言会用 `->` 代替 `.`）。
> 
> 问题是，当我们定义这个对象的类的时候还没有创建具体对象，在方法定义体里想引用对象的属性或者方法怎么办呢？
> 
> 这是一个所有面向对象语言都会面临的问题，解决方案也基本一样，那就是允许我们在定义方法时使用一个特殊的对象，来指代未来创建出来的对象。这个对象有的语言里叫 `self`（Python、Objective-C 等），有的语言里叫 `this`（C++、Java 等），而差别在于这个 `self` 或者 `this` 从哪儿来。
> 
> Python 强制这个 `self` 作为方法的第一个输入参数，这样 `self` 的来历就很简单了——作为参数传进来的，在方法定义里就可以当个普通的变量用了。但代价是方法的定义和调用格式不一样了——调用时并不用直接传递这个参数，而是通过 `obj.do_something(a, b)` 这种方式间接提供 `obj` 对象给 `do_something` 方法，所以其实有点像是 `do_something(obj, a, b)` 的意思，但又不能这么写。
> 
> 其他主流语言都不是这样做的，C++、Java、Objective-C 里的对象方法不需要带有 `self` 这样的参数，方法定义和调用的格式是一样的，但在方法定义体中可以直接使用 `self` 或 `this` 对象。例如 C++ 的例子是这样的：
> 
> ```c++
> class Box {
>    private:
>       double length;
>       double breadth;
>       double height;
>    public:
>       Box(double l = 2.0, double b = 2.0, double h = 2.0) {
>          this->length = l;
>          this->breadth = b;
>          this->height = h;
>       }
>       double volume() {
>          return length * breadth * height;
>       }
>       int compare(Box box) {
>          return this->volume() > box.volume();
>       }
> };
> ```
> 
> 这个做法的好处是方法调用和定义的格式保持一致，但如果问“这个 this 是哪儿来的”，就没法回答了，只能说，这是个 _magic_，编程语言让你可以在类定义里使用这个魔法。
> 
> 凡事有得必有失，就看你更在乎哪个了。我个人不太喜欢 Python 的这个选择，因为后一种做法我认为更容易解释也更容易被理解，你觉得呢？
> 
> 另外还有关于 `super` 的问题。如果我们定义对象的方法时想使用父类定义的某个方法，就需要一个指向父类对象的变量，这在 Python 里需要调用一个特殊函数 `super()` 来取得，`super()` 和 `self` 类似，只不过一个里面包含的是父类版本的实现，一个是自己版本的实现，但一个是函数调用，一个是输入参数，这看上去就不一致了。
> 
> 在 C++、Java 等语言里没有这种不一致的问题，它们反正有一个魔法的 `this` 或者 `self` 了，那么再加一个魔法 `super` 也没啥感觉，所以…

**Comment by ZhaiGuangkai** [comment]
第一个问题：这个来源于程序语言的创始人，就像上帝创造世界，被创造出来的这个世界的运行逻辑，必然遵循这个上帝的大脑逻辑。即使这个上帝是一个团体，如果这个团体的智慧不足够代表全体的智慧，必然这里运行逻辑不能得到全体的赞赏。
第二个问题：从具体到抽象，再从抽象到具体。工具始终是为了解决实际问题，为了解决方法的普适性，那么必然要允许对象变量的赋值。
第三个问题：之前概念混乱和表达错误。我也许是想知道的是为什么这么分类和每个类型的底层实现逻辑和方法。这样我就可以先去Google一下了。

以上是看过几遍后的理解。不知道是否正确。

人类向来能够给自己创造工具，工具如果不顺手那就再创造一个新的工具，也是社会发展的方向吧。
