### ISSUE TITLE
第十章 字符与字符串中有一段程序执行结果和教材上不一样

### ISSUE THREAD

**Issue by qingyix** [neolee/pilot#543]
看截图，程序检查了没看出问题。
<img width="398" alt="字符与字符串章节问题" src="https://user-images.githubusercontent.com/48583363/69212279-d0d9ea00-0b9b-11ea-82f6-c3c2e844b3a3.PNG">

**Comment by Jared-Gong** [comment]
要被取代的是字母“l”不是1，你输错啦
