### ISSUE TITLE
运行 type(42) 出错

### ISSUE THREAD

**Issue by yuzanzan** [neolee/pilot#545]
<img width="485" alt="image" src="https://user-images.githubusercontent.com/54825122/69219119-1ce15a80-0bad-11ea-9f70-20e4fa01b1f4.png">
环境配置均已成功，但运行type(42)出错是什么原因？

**Comment by Jared-Gong** [comment]
要在命令行中输入` python` 进入到 python语句行 再试试
另外你也结合老师的教学用书学习的话 建议安装[Visual Studio Code](https://github.com/neolee/pilot/blob/master/x1-setup.md) 然后在这上面运行代码

**Comment by neolee** [comment]
教材里、之前的主课和支线课程视频里都有介绍如何运行 Python 代码。可以先完整学习下。

**Comment by yuzanzan** [comment]
> 要在命令行中输入 python 进入到 python语句行 再试试
> 另外你也结合老师的教学用书学习的话 建议安装Visual Studio Code 然后在这上面运行代码

谢谢！
