### ISSUE TITLE
安装 Con Emu 用一段时间会不见

### ISSUE THREAD

**Issue by guansheji** [neolee/pilot#546]
在windows10系统里安装Con Emu，用一段时间会不见，要从新安装，好烦

**Comment by neolee** [comment]
安全软件干的？

**Comment by guansheji** [comment]
我装了360。我回想了下在有时候电脑开机后，会弹出有红色的字，写上有应用试图修改······程序（具体写的什么程序我忘了），是否阻拦？然后我按是，好像就没了。如果是安全软件干的，应该怎么解？直接把它给删啦？

**Comment by neolee** [comment]
我自己不太使用这类安全软件，所以不能具体确认，但一般来说：
1. 安全软件提示的时候你要看清楚提示的是什么，如果是和你有用的软件（譬如 ConEmu），你别让他阻拦啊，一阻拦那个软件就被隔离（对你来说就是删掉）了。
2. 安全软件里通常有白名单，你可以试试找到这个设置，如果找到，把 ConEmu 加进去，以后就不会提示了。
