### ISSUE TITLE
试了好多遍不行，求老师帮助

### ISSUE THREAD

**Issue by lxj376169569** [neolee/pilot#547]
PS C:\Users\Administrator> Get-ExecutionPolicy
RemoteSigned
PS C:\Users\Administrator> iwr -useb get.scoop.sh | iex
Initializing...
Downloading scoop...
Extracting...
Creating shim...
Downloading main bucket...
Extracting...
Adding ~\scoop\shims to your path.
iex : 使用“3”个参数调用“SetEnvironmentVariable”时发生异常:“尝试执行未经授
权的操作。”
所在位置 行:1 字符: 26
+ iwr -useb get.scoop.sh | iex
+                          ~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-Expression], MethodInv
   ocationException
    + FullyQualifiedErrorId : UnauthorizedAccessException,Microsoft.PowerShell
   .Commands.InvokeExpressionCommand

**Comment by neolee** [comment]
尝试用管理员权限的命令行界面 {{ PowerShell (Admin) }}。
