### ISSUE TITLE
Jupyter 运行之后没结果，左边只出现 In[*]

### ISSUE THREAD

**Issue by wenlongduan19** [neolee/pilot#549]
李老师，请问这个是为什么？刚开始是正常的，只是多操作几次就会这样！
![TIM截图20191120234559](https://user-images.githubusercontent.com/48726066/69255137-407ac400-0bf2-11ea-9629-1bc4797dfdf9.jpg)

我在issues没看到其他同学遇到这个情况，在按照网上搜索的方式试过，但运行一次后又变成上述那种情况：
![TIM截图20191120235113](https://user-images.githubusercontent.com/48726066/69254191-ceee4600-0bf0-11ea-9085-841a10398a70.jpg)

**Comment by xiaoerhai** [comment]
支线课程第三讲里有答案。

**Comment by neolee** [comment]
这个现象是没执行完（该 cell 正在执行）。你出现问题的两个 cell 里面都有 `input()`，应该要出现让你输入的输入框才对。
