### ISSUE TITLE
运行 code. 命令时出现报错

### ISSUE THREAD

**Issue by dongjin936** [neolee/pilot#55]
![屏幕截图(1)](https://user-images.githubusercontent.com/56923938/67463194-8be19700-f673-11e9-9b2c-503d376371cb.png)

**Comment by neolee** [comment]
命令应该是 `code .`，`code` 和 `.` 之间有个空格。

`code <文件或者目录>` 的作用是用 Visual Studio Code 打开指定的文件或者目录，而 `.` 是个特殊的目录，就是你当前的工作目录。

参见 issue #39 。

**Comment by ellenxh18** [comment]
运行任何code命令都遇到红字错误 无法将 code识别为 cmdlet、函数、脚本文件...

**Comment by neolee** [comment]
你是否已经下载安装了最新的 Visual Studio Code？

**Comment by dongjin936** [comment]
![屏幕截图(4)](https://user-images.githubusercontent.com/56923938/67483091-99107d00-f697-11e9-806b-b7132afaa1f6.png)

**Comment by dongjin936** [comment]
刚刚又试了一次，带空格，仍然如此。

**Comment by dongjin936** [comment]
哇！！解决了！又是重启，之后再从进入Code目录那一步开始往下走。解决！谢谢李老师。

**Comment by dongjin936** [comment]
![屏幕截图(5)](https://user-images.githubusercontent.com/56923938/67484019-bba39580-f699-11e9-9a3d-bb198f0ecbc4.png)

**Comment by neolee** [comment]
Nice! 

p.s. 你的程序里，world 之后漏了一个（英文半角）单引号所以运行出错……

**Comment by dongjin936** [comment]
> Nice!
> 
> p.s. 你的程序里，world 之后漏了一个（英文半角）单引号所以运行出错……

谢谢李老师！

**Comment by dongjin936** [comment]
![屏幕截图(7)](https://user-images.githubusercontent.com/56923938/67491841-13e19400-f6a8-11e9-9aec-6a7490c11a33.png)

**Comment by dongjin936** [comment]
![屏幕截图(8)](https://user-images.githubusercontent.com/56923938/67492527-23151180-f6a9-11e9-8e6e-f5833a58fc3c.png)

咋几步一错。啊啊

**Comment by dongjin936** [comment]
cd pilot-student 出现错误。

**Comment by neolee** [comment]
你 clone 错了，你 clone 了教材所在的 pilot 仓库，应该 clone 学习用书 pilot-student。

所以你本地现在有了 pilot 这个目录但没有 pilot-student 这个目录，自然 cd 不进去啦。

**Comment by dongjin936** [comment]
![屏幕截图(9)](https://user-images.githubusercontent.com/56923938/67494049-31fcc380-f6ab-11e9-8740-1f1d0de3e72a.png)

**Comment by dongjin936** [comment]
手把手，惭愧，谢谢。

**Comment by dongjin936** [comment]
安装和运行 Jupyter Lab，就是直接在上面的pilot-student 目录下进行吗？

**Comment by dongjin936** [comment]
![屏幕截图(12)](https://user-images.githubusercontent.com/56923938/67495129-037fe800-f6ad-11e9-836b-fbf8e3bd9441.png)

安装刷屏中了
