### ISSUE TITLE
Windows PowerShell 与环境变量

### ISSUE THREAD

**Issue by blueeyezhy** [neolee/pilot#550]
李老师您好：
我在学习Python过程中，接触过Anaconda prompt，Anaconda PowerShell prompt，npm，windows cmd，以及Windows PowerShall这几种”黑屏“终端，最后虽然通过搜索和实验设置环境变量，都集中在Windows PowerShall这个终端上了。但是对他们之间的关系，作用，安装过程的配置，应用范围还是不是很了解。老师能不能做一个关于 PowerShall 的支线课程，普及一下？

**Comment by neolee** [comment]
在 Windows Shell 方面，你的实践经验比我丰富啊，你可以把你的尝试过的、以及得到的收获总结一下发出来？

严格来说，有两类程序，一类是“命令行界面（*shell*）”，一类是“终端模拟器（*terminal emulator*）”，*shell* 负责处理我们输入的命令并给出结果，而终端模拟器负责具体的用户输入和输出处理，以及管理多个命令行交互会话（*session*）。

Windows 下的命令行界面，其实主要的就三个：最古老的 cmd、目前官方主推的 PowerShell 和从 Linux 移植的 Bash，这三个不同的 *shell* 有不同的配置系统、支持不一样的命令和脚本（有部分命令是一样的）。对于学习编程的新人来说，如果可预见的未来不打算转向 Mac 或者 Linux 的话，PowerShell 是绝对的不二之选。

至于“终端模拟器”，其实是运行特定 *shell* 的那个程序，比如 ConEmu，还有 Microsoft 自己在开发的 Windows Terminal（目前是 Preview 版），还有 cmd 和 PowerShell 都自己带一个终端模拟器。

**Comment by blueeyezhy** [comment]
谢谢老师，等我把手头的习题做完就做个 PowerShell 的总结。

**Comment by blueeyezhy** [comment]
https://press.one/files/322f2647c0bb7f85f214c109a35bd3ce744b6710083e64e1b38e19de107076e5

李老师，对于powershell，我做了一下总结。对现在的我够用了，也希望可以帮助其他同学少走弯路。

**Comment by neolee** [comment]
赞，我可以把链接放到 Wiki 里吧？

**Comment by blueeyezhy** [comment]
当然可以



-------- 原始邮件 --------
发件人： Neo Lee <notifications@github.com>
日期： 2019年11月22日周五 13:16
收件人： neolee/pilot <pilot@noreply.github.com>
抄送： Harry Zhang <blueeye_zhy@outlook.com>, State change <state_change@noreply.github.com>
主 题： Re: [neolee/pilot] Windows PowerShell 与环境变量 (#550)

赞，我可以把链接放到 Wiki 里吧？

―

**Comment by blueeyezhy** [comment]
李俊老师：
我写了自己的第三篇学习总结，编写我的第一个desktop程序并上传到个人主页上了。
您的课程对我帮助很大，特别是支线课程，是我能够多方位的推进自己的学习。
谢谢

https://press.one/files/b144e92ec716bf268ca4eb1124a78a11d12fa19f8b2f627e452843c37366d472
https://blueeyezhy.github.io/

Harry, a life-long learner.

________________________________
发件人: Neo Lee <notifications@github.com>
发送时间: Friday, November 22, 2019 1:16:45 PM
收件人: neolee/pilot <pilot@noreply.github.com>
抄送: Harry Zhang <blueeye_zhy@outlook.com>; State change <state_change@noreply.github.com>
主题: Re: [neolee/pilot] Windows PowerShell 与环境变量 (#550)


赞，我可以把链接放到 Wiki 里吧？

―

**Comment by neolee** [comment]
哈，自己学了 PyQt 啊，挺好的，开始学习时玩玩 GUI 程序挺好的！

**Comment by blueeyezhy** [comment]
我以前都没有建主页，也没有接触过md。是您的支线课程开启了我的视野。由衷的感谢。

发自我的华为手机


-------- 原始邮件 --------
发件人： Neo Lee <notifications@github.com>
日期： 2019年11月30日周六 20:13
收件人： neolee/pilot <pilot@noreply.github.com>
抄送： Harry Zhang <blueeye_zhy@outlook.com>, State change <state_change@noreply.github.com>
主 题： Re: [neolee/pilot] Windows PowerShell 与环境变量 (#550)

哈，自己学了 PyQt 啊，挺好的，开始学习时玩玩 GUI 程序挺好的！

―

**Comment by blueeyezhy** [comment]
李老师您好：
我用python将以前学习的密码学知识实践为python代码，下面是我第一次实现这么复杂的逻辑算法的总结。
对于代码的实现我觉得我已经做到极限了，您能帮我看一下在代码，结构和算法方面还有那些地方是我需要加强训练的？

https://press.one/files/47660cce5e8fcd99f98ca20810a1f19a6bc3c6544a690630c344ee7af3ddbcf3

Harry, a life-long learner.

发件人: Neo Lee<mailto:notifications@github.com>
发送时间: 2019年11月30日 20:13
收件人: neolee/pilot<mailto:pilot@noreply.github.com>
抄送: Harry Zhang<mailto:blueeye_zhy@outlook.com>; State change<mailto:state_change@noreply.github.com>
主题: Re: [neolee/pilot] Windows PowerShell 与环境变量 (#550)


哈，自己学了 PyQt 啊，挺好的，开始学习时玩玩 GUI 程序挺好的！

―

**Comment by neolee** [comment]
我回头研究下哈，这一块我自己没做过呢 😀
