### ISSUE TITLE
关于 Python 的语法问题

### ISSUE THREAD

**Issue by onthebus98** [neolee/pilot#551]
请教老师，一直以来有一个困惑，就是python的语法规律怎样去系统地掌握？比如这个if "great" in feeling.lower( ):    里面的.lower 为什么不是写在good 后面, 以及这个feeling 是随意的吗？还是有python的语法规律在里面？等等。

print("How are you today?")
feeling = input()
if "great" in feeling.lower():
    print ("I am feeling great, too!")

**Comment by neolee** [comment]
`if "great" in feeling.lower():` 这句话应该这么去理解：

1. 这是一个 `if` 语句，关键字 `if` 后面是一个“逻辑表达式”，也就是一个表达式，这个表达式求值结果是一个布尔值；
2. 这个逻辑表达式 `"great" in feeling.lower()` 的核心是逻辑运算符 `in`，而 `a in b` 的求值结果，当且仅当 `b` 中包含 `a` 时为 `True`，其他时候为 `False`；
3. 在这个例子里，`a` 是字符串 `"great"`，而 `b` 是字符串类型的变量 `feelings`，由于 `feelings` 是用户输入的，有可能包含大小写字母，为了比较更严谨，将其全部转换为小写，再来判断里面是否包含 `great` 这个词。

你仔细体会这个例子，其实理解程序（及其语法）和我们做中文、英文（以及其他外文）的阅读理解是差不多的。首先你需要了解这个编程语言的基本结构（也就是我们在“程序基本结构”那五章里讲的东西），然后面对组合起来的稍微复杂的程序，你要将它解构为那些你已经学会的基本结构，然后识别它的真正意义。这个是要多练的，多看、多写。

**Comment by xiaoerhai** [comment]
老师，`feeling.lower()`里面的`self.name`   里面的 `.` 是同一个意思吗？

**Comment by neolee** [comment]
@xiaoerhai 是的，都是对象语法，`.` 的前面是对象，后面是对象的方法或者属性。
