### ISSUE TITLE
主类中使用到了 Bot 类中的 wait，在编写程序模块是不是要将主类写在 Bot 类之后？

### ISSUE THREAD

**Issue by spring-ap** [neolee/pilot#552]
![image](https://user-images.githubusercontent.com/57279823/69301761-4d2f0480-0c52-11ea-8377-f21afa01956d.png)
有关程序模块的编写结构顺序，是不是一定要将主类写在所有类的最后？
主类中使用到了bot类中的类变量wait，在编写程序模块是不是要将主类写在bot类之后？

**Comment by neolee** [comment]
Python 解释器执行一个源代码文件时，是一行一行按顺序读取并运行的，所以在用到 Bot 类之前，需要有 Bot 类的定义。所以你说的对，Garfield 类的定义用到了 Bot 类，所以要写在 Bot 类后面。
