### ISSUE TITLE
Python 中的函数的参数变量问题

### ISSUE THREAD

**Issue by spring-ap** [neolee/pilot#553]
看过最后一节b-final所想到的：
1、python函数的参数变量是不是不需要提前预定义？
2、如果子类和父类的函数或方法中的参数是不是仅在本类中有效？
3、如果在一个类中，有不同的多个函数，如果其中有两个函数的参数变量相同时，指代的是不是一个参数变量？

**Comment by neolee** [comment]
问题1：用 `def` 定义一个函数是，后面 `()` 里的就是参数的定义，不需要额外再定义这些参数（变量）。

问题2和3：函数的参数变量，在且仅在**这个**函数的定义体内有效，在**这个**函数的定义体以外都是无效的；如果俩函数碰巧有同名的参数变量，也是完全不同的两个东西。这个概念叫做变量的“作用域”，以后我们会专门讲的。
