### ISSUE TITLE
执行结果为“IPython.utils.text.SList”代表什么？

### ISSUE THREAD

**Issue by Maxuanrui** [neolee/pilot#554]
![image](https://user-images.githubusercontent.com/53324687/69316284-7449fe00-0c73-11ea-85eb-d8e0d88dbb3f.png)
我发现大部分符号是不能“被赋值”的，我想是因为不存在比如+这样的数据，但是我发现()、[]、{}这样符号是可以的，应该是分别指空的元组、列表、词典（搜索得知）。但是，！又为什么可以“被赋值”呢，而且我想知道它的类型，又会报错，或者返回“IPython.utils.text.SList”。

**Comment by neolee** [comment]
在 Jupyter 的 Python 环境（称为 IPython）下，`!` 是个特殊字符，用这个字符开头的代码会被作为命令行命令执行（是的，你可以用这个办法来在 Jupyter Lab 里列目录、安装软件包等）。在一般的 Python 环境下这个不是个合法的“值”。

具体原理可以参考这里：
https://gist.github.com/parente/b6ee0efe141822dfa18b6feeda0a45e5
