### ISSUE TITLE
本电脑第二次装 jupyter lap 中断报错

### ISSUE THREAD

**Issue by guansheji** [neolee/pilot#556]
![1212](https://user-images.githubusercontent.com/55250000/69334475-bf750880-0c95-11ea-9ac1-263f6afb1a87.png)

**Comment by neolee** [comment]
你这个命令显然是敲错了吧，怎么会有 `lap` 这种东西？你应该安装的包叫 `jupyterlab`……

话说你这是第二次，第一次咋装的？

**Comment by guansheji** [comment]
![333](https://user-images.githubusercontent.com/55250000/69341098-dde20080-0ca3-11ea-946d-ceae624a903b.png)
是找不到合适的版本。我到无眼看我自己了，敲了几次次jupyterlap,出现报错，我以为是我自己敲错了，然后我就试了一下jupyter lap ,,觉果就~~·

**Comment by neolee** [comment]
你还是敲错了，是 **jupyterlab**，再仔细看看……莫非你是退役星际选手……

**Comment by guansheji** [comment]
哈哈·······不配置这次环境还不知道自己原来这么傻逼，昨晚上还被这个lap,搞到差点一夜没睡。谢谢李老师，碰上我这傻逼都还敢提问的，真是为难你了。
配置这环境太难了，先是网络问题，搞掂了网络问题，第一次好不容易安装好后第二天，vpn又崩了，过了好几天再次搞好网络,发现之前装好的给本地的安全软件给杀掉了，又从装。要不是遇到李老师这样有耐心解答问题的，早缩回去了。谢谢，真的非常感谢李老师的耐心解答。

**Comment by neolee** [comment]
环境确实是个大挑战，我也在想有什么办法可以稍微简化一点。加油，keep going!

**Comment by guansheji** [comment]
嗯，一定，谢谢老师
