### ISSUE TITLE
Garfield 实例运行错误

### ISSUE THREAD

**Issue by wenwen-shan** [neolee/pilot#557]
![图片](https://user-images.githubusercontent.com/57054269/69348355-015f7800-0cb1-11ea-9e0c-9c945bf2097d.png)
![图片](https://user-images.githubusercontent.com/57054269/69348384-10462a80-0cb1-11ea-806d-96eab913b729.png)
![图片](https://user-images.githubusercontent.com/57054269/69348399-15a37500-0cb1-11ea-9ea5-abd3152af26c.png)
![图片](https://user-images.githubusercontent.com/57054269/69348411-1a682900-0cb1-11ea-9a96-de6fd60fbf59.png)
查找了很久，没有找到错误原因。

**Comment by neolee** [comment]
错误信息是 `HelloBot` 类的对象实例没有 `run` 这个方法，而 `HelloBot` 的 `run` 方法是从基类 `Bot` 继承来的，你的 `Bot` 类定义长啥样，发来看看。

**Comment by wenwen-shan** [comment]
![图片](https://user-images.githubusercontent.com/57054269/69352014-21923580-0cb7-11ea-9308-bd8f7fd81a9c.png)

**Comment by xiaoerhai** [comment]
`def __run(self)`改为`def run(self)`试试

**Comment by wenwen-shan** [comment]
还是显示无变化

**Comment by xiaoerhai** [comment]
确保前面的代码都按了 `ctrl` +`enter`  后在左边的[ ]显示数字执行了吗？我之前按了一次后也会出现仍然报错的情况，当全部重新执行一次就正常了。

**Comment by wenwen-shan** [comment]
将run前面的下划线去掉后，程序运行显示正常，但是在对话输入时，最后一个FavoriteBot出现了相同的问题，
![图片](https://user-images.githubusercontent.com/57054269/69394503-28e92b80-0d17-11ea-8e34-2a53a9b899ca.png)

**Comment by neolee** [comment]
@wenwen-shan 
要么你的 `FavoriteColorBot` 没有正确继承自 `Bot`，要么你没有重新运行定义它的代码。

关于课程练习的课程讲解已经发布了，可以先去看看。

**Comment by wenwen-shan** [comment]
已解决，是没有重新运行这个代码，主要原因是对于子类和父类理解的不够深刻，思路不清。谢谢老师和同学的帮助！
