### ISSUE TITLE
为什么 while 会陷入无限循环？

### ISSUE THREAD

**Issue by lidewen-yue** [neolee/pilot#559]
![image](https://user-images.githubusercontent.com/56989072/69426397-27941f00-0d68-11ea-959c-6e8a2c6c47fc.png)
我的思考逻辑如下：输入9-然后执行name>8-然后返回small-最后返回game over，但是为什么会陷入无限循环呢？为什么返回的不是一个small呢？而是无限个？
![4491574426622_ pic_hd](https://user-images.githubusercontent.com/56989072/69428033-421bc780-0d6b-11ea-81d5-a244fa698f40.jpg)

然后我在每个if条件句后面加个break才能打断，

**Comment by neolee** [comment]
你需要重新学习和理解 `while` 结构。

其实，假定你输入的是 `9`，那么你前面一个版本等价于：
```python
number = 9

while True:
    print('small')

print('game over')
```

而后一个版本等价于：
```python
number = 9

while True:
    print('small')
    break
    print('game over')
```

后一个版本因为先 break 了，最后打印 "game over" 的也不会执行。

所以，你其实想要的是啥效果？

**Comment by xiaoerhai** [comment]
你讲的是不是以下这段代码的逻辑，你可以试着运行下：
```python
while True:
    name = int(input('Please enter a number'))
    if name == 8:
        print('nice')
    elif name < 8:
        print('big')
    elif name>8:
        print('small')
        break
print('game over')
```
这就是`break`的作用，在你上面的代码中，如果没有它，那么会进入`while True`的的死循环，因为`name=9` 就代表`True`，它的值一直是真。
