### ISSUE TITLE
Jupyter 运行程序报错 name ' ' is not defined

### ISSUE THREAD

**Issue by kanglei1985** [neolee/pilot#561]
![image](https://user-images.githubusercontent.com/53995486/69473727-8e5e1a80-0df2-11ea-8c33-3f3ccc7f6bc4.png)

**Comment by neolee** [comment]
你截图里最上面那个代码的 cell 要运行一下，不然这些变量都没定义/初始化，后面就不能用了。

**Comment by kanglei1985** [comment]
谢谢
