### ISSUE TITLE
代码在 VSCode 里面运行后 结果中出现乱码？

### ISSUE THREAD

**Issue by Jared-Gong** [neolee/pilot#562]

**Comment by Jared-Gong** [comment]
![1574495183(1)](https://user-images.githubusercontent.com/56901849/69475488-ba849600-0e08-11ea-91d3-d38895a0c950.png)
还有需要上颜色的代码段，结果中也没有体现。
但我在powershell中运行 `python. \Scarlett.py` 都是完全正常的，是不是我的VSCode版本问题？

**Comment by xiaoerhai** [comment]
![vscode](https://user-images.githubusercontent.com/48662601/69476641-44d3f680-0e17-11ea-88cf-7c2fcd92fbba.png)
请教下，你是怎么在VScode上执行代码的？我按了`Terminal`里的`New Terminal`后没有出现光标提示我输入（如上图）。

**Comment by Jared-Gong** [comment]
这个不太清楚呀，要不你重启下VSCode，或者用powershell重启VSCode。正常的话是，我这种吧（如下图）
![1574502163(1)](https://user-images.githubusercontent.com/56901849/69476730-b19bc080-0e18-11ea-8ee7-1037fb582b6e.png)

**Comment by neolee** [comment]
Duplicate of #555
