### ISSUE TITLE
自定义函数，return 结果的疑问

### ISSUE THREAD

**Issue by kanglei1985** [neolee/pilot#563]
![image](https://user-images.githubusercontent.com/53995486/69475877-a2634580-0e0d-11ea-8af8-241619cb49bb.png)

老师，我自定义了一个函数，我理解结果应该是True才对. 麻烦帮忙看看。

**Comment by xiaoerhai** [comment]
执行代码`sqrt(4)`,应该返回的结果为`2.0`,再执行代码`type(2.0)`,应该返回的结果为`float`而不是`int`。所以，结果为`False`是正常的。

**Comment by neolee** [comment]
@xiaoerhai 说的很对！

**Comment by kanglei1985** [comment]
> 执行代码`sqrt(4)`,应该返回的结果为`2.0`,再执行代码`type(2.0)`,应该返回的结果为`float`而不是`int`。所以，结果为`False`是正常的。

谢谢解答。那请问怎么做结果能输出True 呢？

**Comment by neolee** [comment]
> > 执行代码`sqrt(4)`,应该返回的结果为`2.0`,再执行代码`type(2.0)`,应该返回的结果为`float`而不是`int`。所以，结果为`False`是正常的。
> 
> 谢谢解答。那请问怎么做结果能输出True 呢？

比如把你的 `isinstance()` 的第二个参数改成 `float`，你可以自己思考一下，还有不少别的办法。
