### ISSUE TITLE
本章代码突然不能运行，其他章节正常

### ISSUE THREAD

**Issue by wenwen-shan** [neolee/pilot#564]
在输入代码过程，有过剪切，复制的操作，不知道什么原因，这个章节代码不能运行，原来运行过的代码重新运行，也无法显示；打开其他章节，代码能够正常运行输出；如下图，中间代码显示星号

![图片](https://user-images.githubusercontent.com/57054269/69476157-3551af00-0e11-11ea-9dca-879c99b06fb7.png)

**Comment by neolee** [comment]
1. 试试重启这个 notebook 的 kernel；
2. 如果还有问题，从显示 [*] 的 cell 出发仔细找找代码里有没有无限循环之类的问题。

**Comment by wenwen-shan** [comment]
还以为是自己误动了哪个点造成的错误，已通过重启解决。
