### ISSUE TITLE
自己练习的时候提示类中没有指定属性“XX”

### ISSUE THREAD

**Issue by zhangSen1987** [neolee/pilot#567]
![错误](https://user-images.githubusercontent.com/53714512/69476654-8795ce80-0e17-11ea-8fe8-56cd03183a26.png)
李老师帮我看看 谢谢！

**Comment by xiaoerhai** [comment]
1. 没有父子关系，类命名不是一定要`()`这个括号的（我试了下有它好像也不影响）；
2. 之前我也老是忘记不同代码块的缩进情况。这个例子，你在创建实例对象的时候记得不需要缩进。如下代码，重点看最后4列，它们都不需要缩进的。我运行后的结果是：
```
2019 Benz C63Amg
This car has 12 milse on it.
```
```python
class Car:
    def __init__(self,make,model,year):
        self.make = make
        self.model = model
        self. year = year
        self.odometer_reading = 0
        
    def get_descriptive_name(self):
        long_name = f'{self.year} {self.make} {self.model}'
        print(long_name.title())
        
    def read_odometer(self):
        print(f'This car has {self.odometer_reading} milse on it.')
        
    def update_odometer(self,mileage):
        self.odometer_reading = mileage
        
your_car = Car('benz','c63amg',2019)
your_car.get_descriptive_name()
your_car.update_odometer(12)
your_car.read_odometer()
```
（I like your car.）

**Comment by zhangSen1987** [comment]
> 1. 没有父子关系，类命名不是一定要`()`这个括号的（我试了下有它好像也不影响）；
> 2. 之前我也老是忘记不同代码块的缩进情况。这个例子，你在创建实例对象的时候记得不需要缩进。如下代码，重点看最后4列，它们都不需要缩进的。我运行后的结果是：
> 
> ```
> 2019 Benz C63Amg
> This car has 12 milse on it.
> ```
> 
> ```python
> class Car:
>     def __init__(self,make,model,year):
>         self.make = make
>         self.model = model
>         self. year = year
>         self.odometer_reading = 0
>         
>     def get_descriptive_name(self):
>         long_name = f'{self.year} {self.make} {self.model}'
>         print(long_name.title())
>         
>     def read_odometer(self):
>         print(f'This car has {self.odometer_reading} milse on it.')
>         
>     def update_odometer(self,mileage):
>         self.odometer_reading = mileage
>         
> your_car = Car('benz','c63amg',2019)
> your_car.get_descriptive_name()
> your_car.update_odometer(12)
> your_car.read_odometer()
> ```
> 
> （I like your car.）

谢谢，我把缩进去掉就好了。但是之前我也有缩进，可以正常运行，这怎么解释，谢谢
![示范](https://user-images.githubusercontent.com/53714512/69477490-dea0a100-0e21-11ea-947e-868a11229c45.png)

**Comment by xiaoerhai** [comment]
李老师，楼主截图的代码，error为什么不是```NameError: name 'Car' is not defined```?（这个是我在jupyter lab上输入楼主的代码时报的错）对比了好一会还是找不到问题在哪里，我个人能理解我那个报错，因为缩进和def一致的话应该默认Car这个类还没被定义。

**Comment by zhangSen1987** [comment]
> 李老师，楼主截图的代码，error为什么不是`NameError: name 'Car' is not defined`?（这个是我在jupyter lab上输入楼主的代码时报的错）对比了好一会还是找不到问题在哪里，我个人能理解我那个报错，因为缩进和def一致的话应该默认Car这个类还没被定义。

我那个提示是属性错误，并不是Car类没有被定义，提示的是update_odometer这个属性没有被定义，问题解决了，反而更疑惑了，哈哈....李老师快来帮我们看看。

**Comment by xiaoerhai** [comment]
@zhangSen1987 
我也发现这个问题了。我猜是这样的（也是执行后得出来的结论）：
如果你第一次运行有缩进的那段代码，则会报错；
但如果你先运行没有缩进时的代码（这时Car已经被确认定义了，且没按`restart`这个按钮），然后再运行有缩进的代码时就不会报错了。不清楚你遇到的是不是和我一样的情况。

**Comment by neolee** [comment]
1. 对类进行实例化，必须在类的定义已经完成，如果你在类定义里面试图实例化这个类，会出现类似 `NameError: name 'Car' is not defined` 的错误。这种操作是绝对要避免的。

2. @zhangSen1987 你前面出的错误，以及后面执行又好像没错，是因为你在执行这些代码之前执行过定义 `Car` 这个类的代码。第一个错误，我猜你之前运行过一个版本的 `class Car:...` 代码，里面没有 `update_odometer` 方法的定义，所以报了那么一个错误；而第二次，你可能之前已经运行过正确的 `class Car:...` 代码，有个正确的 Car 类定义在解释器里了，所以执行也不会报错——但后面这个代码是有问题的，因为在类定义里你执行了类的实例化代码，这些代码用的还是老的 Car 类定义，这个结构是乱的，后患无穷。

Jupyter Lab 有个潜在的陷阱，因为你可以任意选择执行哪些 cell，以及执行的顺序，所以解释器里的程序运行状态，和你看到纸面上的程序并不一定一致，有时候就会产生让人费解的结果。这时候尝试重启 notebook 的 kernel，然后从第一个 cell 开始一个个执行，那才是程序应有的状态。

**Comment by xiaoerhai** [comment]
>但后面这个代码是有问题的，因为在类定义里你执行了类的实例化代码，这些代码用的还是老的 Car 类定义，这个结构是乱的，后患无穷。

get 到了。感谢李骏老师解答！
