### ISSUE TITLE
练习学习用书中的 if else ，遇到一个问题

### ISSUE THREAD

**Issue by kanglei1985** [neolee/pilot#568]
![image](https://user-images.githubusercontent.com/53995486/69476960-5f0fd380-0e1b-11ea-936d-4effaaaebcd7.png)

老师，我练习这个教学案例，其他都OK。但是输入False时, 返回的却是int。

**Comment by neolee** [comment]
参见 #466 。

因为上面那个 issue 里谈到的原因，上面这个 `type_0` 的实现可以优化一下，就是把 `bool` 的判断放到 `int` 之前，就会更好一下。你可以想想为什么。

**Comment by kanglei1985** [comment]
> 参见 #466 。
> 
> 因为上面那个 issue 里谈到的原因，上面这个 `type_0` 的实现可以优化一下，就是把 `bool` 的判断放到 `int` 之前，就会更好一下。你可以想想为什么。

我猜测是不是因为True=1 False=0 ？

**Comment by neolee** [comment]
我猜主要是为了和 C 语言兼容，C 语言里用 0 表示假，任何其他数都是真。而 Python 底层是非常依赖 C 的。
