### ISSUE TITLE
建了个 github.io 的网站不能访问是什么原因?

### ISSUE THREAD

**Issue by iceberg-yuan** [neolee/pilot#569]
![iceberg-yuan github io](https://user-images.githubusercontent.com/57003256/69477819-e5c9ae00-0e25-11ea-9a3a-5f06c206617a.PNG)

提示不安全

**Comment by neolee** [comment]
提示不是安全问题，是说页面不存在，应该是你的 repo 没有做对吧（里面有没有 README.md 文件？）

有的时候是需要稍微等一下再试。

**Comment by iceberg-yuan** [comment]
谢谢李老师，ok了

**Comment by iceberg-yuan** [comment]
![捕获](https://user-images.githubusercontent.com/57003256/69478250-69d26480-0e2b-11ea-8a8e-d673a0f6ee46.PNG)

李老师，我在网站上加了两个文件，为什么在登录网站后不显示新加的文件呢？谢谢

**Comment by neolee** [comment]
那个网站会渲染 `README.md` 文件内容，仅此而已。你要是加了别的文件，就要在 `README.md` 里放链接把它们展现出来。

**Comment by iceberg-yuan** [comment]
明白了，thanks

**Comment by iceberg-yuan** [comment]
![捕获](https://user-images.githubusercontent.com/57003256/69479739-d2c1d880-0e3b-11ea-88b6-c048dd01f409.PNG)
![捕获1](https://user-images.githubusercontent.com/57003256/69479741-d2c1d880-0e3b-11ea-8315-32b87d6d06f7.PNG)
李老师，我在readme.md里写的东西，从网站上看，为什么Blockchain是缩进的呢？他应该与Python和English一样，都是左对齐的啊

**Comment by neolee** [comment]
不知道，我这里显示正常：

<img width="779" alt="Screen Shot 2019-11-23 at 10 06 11 PM" src="https://user-images.githubusercontent.com/24796/69479896-824b7a80-0e3d-11ea-9d3b-7b2abea1de62.png">
