### ISSUE TITLE
学习 3-structure-2.ipynb 里关于 abs() 调用问题

### ISSUE THREAD

**Issue by tiamming666** [neolee/pilot#57]
![1571904978(1)](https://user-images.githubusercontent.com/48582921/67467005-9ce1d680-f67a-11e9-8a7e-7cf8c7692dd2.jpg)

**Comment by neolee** [comment]
在 3-structure-2 中未发现你截图中的代码，看上去你前面定义了一个 `abs` 覆盖掉了系统自带的 `abs()` 函数。

**Comment by tiamming666** [comment]
我确定没有定义 `abs` ，试了在别的章节都可以用这个函数，只有在 3-structure-2 中用 abs() 会报错。

**Comment by tiamming666** [comment]
[3-structure-2.zip](https://github.com/neolee/pilot/files/3766737/3-structure-2.zip)

**Comment by neolee** [comment]
在我这里运行没有问题呀：

<img width="1387" alt="screen" src="https://user-images.githubusercontent.com/24796/67473462-4af27e00-f685-11e9-83ac-80da876f764a.png">

**Comment by tiamming666** [comment]
老师，问题解决了。今天打开文件重新输入之后就正常了。
