### ISSUE TITLE
小白太难了！！！！scoop安装的网络问题

### ISSUE THREAD

**Issue by AidenDong** [neolee/pilot#570]
![image](https://user-images.githubusercontent.com/48676560/69481014-1c182500-0e48-11ea-83ce-fd762a96683c.png)

我浏览了李俊老师的回答——最简单粗暴的解决方法是重装系统和换网络或开代理。

![image](https://user-images.githubusercontent.com/48676560/69481087-e293e980-0e48-11ea-86e5-c494d2a31495.png)

上图是浏览https://get.scoop.sh/ 根据要求下载了证书也还是一样的错误，用Vultr搭建vpn也失败了因为Xshell也需要浏览到一个我这无法访问的地址。

我是小白一枚，看了一些博客、论坛，瞎弄吧也没有解决问题 。内心很受挫，就同abandon于英语字典，我翻到了学习编程的abandon。求助!

**Comment by AidenDong** [comment]
解决了 powershell如上问题：
add-type @"
    using System.Net;
    using System.Security.Cryptography.X509Certificates;
    public class TrustAllCertsPolicy : ICertificatePolicy {
        public bool CheckValidationResult(
            ServicePoint srvPoint, X509Certificate certificate,
            WebRequest request, int certificateProblem) {
            return true;
        }
    }
"@
[System.Net.ServicePointManager]::CertificatePolicy = New-Object TrustAllCertsPolicy

$result = Invoke-WebRequest -Uri "https://IpAddress/resource"

**Comment by neolee** [comment]
没看懂，这个是怎么操作的，解决了什么问题呀？

你的 Windows 是 Windows 7 吗？

**Comment by AidenDong** [comment]
后来在接下来几步中又出问题了，所以并不能解决问题。我刚刚重置了系统SCOOP安装都很顺畅，很巴适！一开始就该这么做（原来就是不想重新安装PS AI...看来还是简单粗暴适合我 哈哈哈）。Widows 10
