### ISSUE TITLE
Mac 系统安装 JupyterLab 成功但是运行时候报错

### ISSUE THREAD

**Issue by leeyeep** [neolee/pilot#571]
[E 01:48:25.878 LabApp] JupyterLab application assets not found in "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/share/jupyter/lab"
[E 01:48:25.879 LabApp] Please run `jupyter lab build` or use a different app directory

安装的时候用pip安装回报错，然后我根据老师提示改成pip3后成功，然后运行时候就报了上述错误了

**Comment by neolee** [comment]
你这个看上去不是 Homebrew 安装的版本，是别的 Python 环境，不过理论上也是可以的才对。

你试试运行 `jupyter lab build` 看看？

**Comment by leeyeep** [comment]
运行后提示这个

[LabBuildApp] JupyterLab 1.2.3
[LabBuildApp] Building in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/share/jupyter/lab
[LabBuildApp] Building jupyterlab assets (build:prod:minimize)
An error occured.
PermissionError: [Errno 13] Permission denied: '/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/share/jupyter'
See the log file for details:  /var/folders/xd/hvqh8wfj6sj788l_2mwlmmch0000gn/T/jupyterlab-debug-2v8804q1.log

**Comment by leeyeep** [comment]
下面是日志里的内容
[LabBuildApp] Building in /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/share/jupyter/lab
[LabBuildApp] Yarn configuration loaded.
[LabBuildApp] Node v13.1.0

[LabBuildApp] Building jupyterlab assets (build:prod:minimize)
[LabBuildApp] Traceback (most recent call last):

[LabBuildApp]   File "/Library/Python/3.7/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

[LabBuildApp]   File "/Library/Python/3.7/site-packages/jupyterlab/labapp.py", line 98, in start
    command=command, app_options=app_options)

[LabBuildApp]   File "/Library/Python/3.7/site-packages/jupyterlab/commands.py", line 459, in build
    command=command, clean_staging=clean_staging)

[LabBuildApp]   File "/Library/Python/3.7/site-packages/jupyterlab/commands.py", line 650, in build
    clean=clean_staging

[LabBuildApp]   File "/Library/Python/3.7/site-packages/jupyterlab/commands.py", line 1084, in _populate_staging
    self._ensure_app_dirs()

[LabBuildApp]   File "/Library/Python/3.7/site-packages/jupyterlab/commands.py", line 1395, in _ensure_app_dirs
    os.makedirs(path)

[LabBuildApp]   File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)

[LabBuildApp]   File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/os.py", line 211, in makedirs
    makedirs(head, exist_ok=exist_ok)

[LabBuildApp]   File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/os.py", line 221, in makedirs
    mkdir(name, mode)

[LabBuildApp] PermissionError: [Errno 13] Permission denied: '/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/share/jupyter'

[LabBuildApp] Exiting application: JupyterLab

**Comment by neolee** [comment]
果然还是环境的问题，你的 Python 环境不是按照环境配置指南安装的，而 Python 环境所在的路径没有写权限，所以 Jupyter 配置失败了。

有挺多办法解决这个问题，不过大多需要对环境比较熟悉。我建议你把 `/Library/Developer/CommandLineTools` 这个目录整个移动到一个备份目录下（相当于将其移除了），然后按照配置指南，用 Homebrew 重新确认 Python 的安装，然后再重新安装 JupyterLab。

**Comment by leeyeep** [comment]
没有删除又重新装把python 升级了下就又好了，貌似是跟mac系统里的2.7的那个版本冲突了还是怎么回事，不过现在好了
