### ISSUE TITLE
李老师，我运行python -v 查看版本的时候，为什么出现这么多东西？以前都是显示版本的，难以理解。

### ISSUE THREAD

**Issue by zhipingyang120** [neolee/pilot#573]
PS C:\Users\90522> python -v
import _frozen_importlib # frozen
import _imp # builtin
import '_thread' # <class '_frozen_importlib.BuiltinImporter'>
import '_warnings' # <class '_frozen_importlib.BuiltinImporter'>
import '_weakref' # <class '_frozen_importlib.BuiltinImporter'>
# installing zipimport hook
import 'zipimport' # <class '_frozen_importlib.BuiltinImporter'>
# installed zipimport hook
import '_frozen_importlib_external' # <class '_frozen_importlib.FrozenImporter'>
import '_io' # <class '_frozen_importlib.BuiltinImporter'>
import 'marshal' # <class '_frozen_importlib.BuiltinImporter'>
import 'nt' # <class '_frozen_importlib.BuiltinImporter'>
import _thread # previously loaded ('_thread')
import '_thread' # <class '_frozen_importlib.BuiltinImporter'>
import _weakref # previously loaded ('_weakref')
import '_weakref' # <class '_frozen_importlib.BuiltinImporter'>
import 'winreg' # <class '_frozen_importlib.BuiltinImporter'>
# C:\Users\90522\scoop\apps\python37\current\lib\encodings\__pycache__\__init__.cpython-37.pyc matches C:\Users\90522\scoop\apps\python37\current\lib\encodings\__init__.py
# code object from 'C:\\Users\\90522\\scoop\\apps\\python37\\current\\lib\\encodings\\__pycache__\\__init__.cpython-37.pyc'
# C:\Users\90522\scoop\apps\python37\current\lib\__pycache__\codecs.cpython-37.pyc matches C:\Users\90522\scoop\apps\python37\current\lib\codecs.py
# code object from 'C:\\Users\\90522\\scoop\\apps\\python37\\current\\lib\\__pycache__\\codecs.cpython-37.pyc'
import '_codecs' # <class '_frozen_importlib.BuiltinImporter'>
import 'codecs' # <_frozen_importlib_external.SourceFileLoader object at 0x0000016E0F284508>
# C:\Users\90522\scoop\apps\python37\current\lib\encodings\__pycache__\aliases.cpython-37.pyc matches C:\Users\90522\scoop\apps\python37\current\lib\encodings\aliases.py
# code object from 'C:\\Users\\90522\\scoop\\apps\\python37\\current\\lib\\encodings\\__pycache__\\aliases.cpython-37.pyc'
import 'encodings.aliases' # <_frozen_importlib_external.SourceFileLoader object at 0x0000016E10B28208>
import 'encodings' # <_frozen_importlib_external.SourceFileLoader object at 0x0000016E0F281448>
# C:\Users\90522\scoop\apps\python37\current\lib\encodings\__pycache__\utf_8.cpython-37.pyc matches C:\Users\90522\scoop\apps\python37\current\lib\encodings\utf_8.py
# code object from 'C:\\Users\\90522\\scoop\\apps\\python37\\current\\lib\\encodings\\__pycache__\\utf_8.cpython-37.pyc'
import 'encodings.utf_8' # <_frozen_importlib_external.SourceFileLoader object at 0x0000016E10B345C8>
import '_signal' # <class '_frozen_importlib.BuiltinImporter'>
# C:\Users\90522\scoop\apps\python37\current\lib\encodings\__pycache__\latin_1.cpython-37.pyc matches C:\Users\90522\scoop\apps\python37\current\lib\encodings\latin_1.py
# code object from 'C:\\Users\\90522\\scoop\\apps\\python37\\current\\lib\\encodings\\__pycache__\\latin_1.cpython-37.pyc'
import 'encodings.latin_1' # <_frozen_importlib_external.SourceFileLoader object at 0x0000016E10B34E48>
# C:\Users\90522\scoop\apps\python37\current\lib\__pycache__\io.cpython-37.pyc matches C:\Users\90522\scoop\apps\python37\current\lib\io.py
# code object from 'C:\\Users\\90522\\scoop\\apps\\python37\\current\\lib\\__pycache__\\io.cpython-37.pyc'
# C:\Users\90522\scoop\apps\python37\current\lib\__pycache__\abc.cpython-37.pyc matches C:\Users\90522\scoop\apps\python37\current\lib\abc.py
# code object from 'C:\\Users\\90522\\scoop\\apps\\python37\\current\\lib\\__pycache__\\abc.cpython-37.pyc'
import '_abc' # <class '_frozen_importlib.BuiltinImporter'>
import 'abc' # <_frozen_importlib_external.SourceFileLoader object at 0x0000016E10B37A08>
import 'io' # <_frozen_importlib_external.SourceFileLoader object at 0x0000016E10B371C8>
# C:\Users\90522\scoop\apps\python37\current\lib\__pycache__\site.cpython-37.pyc matches C:\Users\90522\scoop\apps\python37\current\lib\site.py
# code object from 'C:\\Users\\90522\\scoop\\apps\\python37\\current\\lib\\__pycache__\\site.cpython-37.pyc'
# C:\Users\90522\scoop\apps\python37\current\lib\__pycache__\os.cpython-37.pyc matches C:\Users\90522\scoop\apps\python37\current\lib\os.py
# code object from 'C:\\Users\\90522\\scoop\\apps\\python37\\current\\lib\\__pycache__\\os.cpython-37.pyc'
# C:\Users\90522\scoop\apps\python37\current\lib\__pycache__\stat.cpython-37.pyc matches C:\Users\90522\scoop\apps\python37\current\lib\stat.py
# code object from 'C:\\Users\\90522\\scoop\\apps\\python37\\current\\lib\\__pycache__\\stat.cpython-37.pyc'
import '_stat' # <class '_frozen_importlib.BuiltinImporter'>
import 'stat' # <_frozen_importlib_external.SourceFileLoader object at 0x0000016E10B57D88>
# C:\Users\90522\scoop\apps\python37\current\lib\__pycache__\ntpath.cpython-37.pyc matches C:\Users\90522\scoop\apps\python37\current\lib\ntpath.py
# code object from 'C:\\Users\\90522\\scoop\\apps\\python37\\current\\lib\\__pycache__\\ntpath.cpython-37.pyc'
# C:\Users\90522\scoop\apps\python37\current\lib\__pycache__\genericpath.cpython-37.pyc matches C:\Users\90522\scoop\apps\python37\current\lib\genericpath.py
# code object from 'C:\\Users\\90522\\scoop\\apps\\python37\\current\\lib\\__pycache__\\genericpath.cpython-37.pyc'
import 'genericpath' # <_frozen_importlib_external.SourceFileLoader object at 0x0000016E10B62D88>
import 'ntpath' # <_frozen_importlib_external.SourceFileLoader object at 0x0000016E10B59848>
# C:\Users\90522\scoop\apps\python37\current\lib\__pycache__\_collections_abc.cpython-37.pyc matches C:\Users\90522\scoop\apps\python37\current\lib\_collections_abc.py
# code object from 'C:\\Users\\90522\\scoop\\apps\\python37\\current\\lib\\__pycache__\\_collections_abc.cpython-37.pyc'
import '_collections_abc' # <_frozen_importlib_external.SourceFileLoader object at 0x0000016E10B65948>
import 'os' # <_frozen_importlib_external.SourceFileLoader object at 0x0000016E10B47D88>
# C:\Users\90522\scoop\apps\python37\current\lib\__pycache__\_sitebuiltins.cpython-37.pyc matches C:\Users\90522\scoop\apps\python37\current\lib\_sitebuiltins.py
# code object from 'C:\\Users\\90522\\scoop\\apps\\python37\\current\\lib\\__pycache__\\_sitebuiltins.cpython-37.pyc'
import '_sitebuiltins' # <_frozen_importlib_external.SourceFileLoader object at 0x0000016E10B4A348>
# C:\Users\90522\scoop\apps\python37\current\lib\__pycache__\_bootlocale.cpython-37.pyc matches C:\Users\90522\scoop\apps\python37\current\lib\_bootlocale.py
# code object from 'C:\\Users\\90522\\scoop\\apps\\python37\\current\\lib\\__pycache__\\_bootlocale.cpython-37.pyc'
import '_locale' # <class '_frozen_importlib.BuiltinImporter'>
import '_bootlocale' # <_frozen_importlib_external.SourceFileLoader object at 0x0000016E10B4A9C8>
# C:\Users\90522\scoop\apps\python37\current\lib\encodings\__pycache__\gbk.cpython-37.pyc matches C:\Users\90522\scoop\apps\python37\current\lib\encodings\gbk.py
# code object from 'C:\\Users\\90522\\scoop\\apps\\python37\\current\\lib\\encodings\\__pycache__\\gbk.cpython-37.pyc'
import '_codecs_cn' # <class '_frozen_importlib.BuiltinImporter'>
import '_multibytecodec' # <class '_frozen_importlib.BuiltinImporter'>
import 'encodings.gbk' # <_frozen_importlib_external.SourceFileLoader object at 0x0000016E10B53A88>
import 'site' # <_frozen_importlib_external.SourceFileLoader object at 0x0000016E10B43288>
Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
import 'atexit' # <class '_frozen_importlib.BuiltinImporter'>
>>> # #

**Comment by xiaoerhai** [comment]
是大写V，不是小写v。
含义：
V：version
v：verbose

**Comment by zhipingyang120** [comment]
哈哈，还真是！



---原始邮件---
发件人: "卢张凯"<notifications@github.com&gt;
发送时间: 2019年11月24日(星期日) 中午11:00
收件人: "neolee/pilot"<pilot@noreply.github.com&gt;;
抄送: "zhipingyang120"<905227121@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [neolee/pilot] 李老师，我运行python -v 查看版本的时候，为什么出现这么多东西？以前都是显示版本的，难以理解。 (#573)



是大写V，不是小写v。
 含义：
 V：version
 v：verbose
