### ISSUE TITLE
关于【没有 return 语句的函数】

### ISSUE THREAD

**Issue by xiaoerhai** [neolee/pilot#574]
```
def do_something():
    print('This is a hello message from do_something().')

if not do_something():                # 由于该函数名称的缘故，这一句代码的可读性很差……
    print("The return value of 'do_something()' is None.")
```
以上代码的输出是：
```
This is a hello message from do_something().
The return value of 'do_something()' is None.
```
而不是：
`The return value of 'do_something()' is None.`

我当时认为只会输出判断语句的那个print()内容，因为函数do_something()没有被调用。

（以上例子来源于笑来老师的the-craft-of-selfteaching）

**Comment by Jared-Gong** [comment]
能说下那一页吗？

**Comment by neolee** [comment]
为啥你会觉得“函数 do_something() 没有被调用”呢？

`if not do_something():` 这一句应该这么看：
1. 这是一个 `if` 语句，`if` 之后是一个逻辑判断表达式；
2. 对该逻辑判断表达式求值，即计算 `not do_something()` 的值；
3. 首先执行 `do_something()`，打印出第一句话，因为没有显式 `return`，其实是返回了一个 `None`；
4. 计算逻辑表达式 `not None`，结果为 `True`。

然后执行 `if` 下面的分支，打印出第二句话。

**Comment by xiaoerhai** [comment]
谢谢老师，我理解了，个人觉得第3步尤为重要。

**Comment by xiaoerhai** [comment]
> 能说下那一页吗？

Part.2.D.1-args（关于参数（上））

**Comment by neolee** [comment]
@xiaoerhai `if` 后面的表达式必须求值才能完成 `if` 语句，而表达式里有个函数调用，那么必须完成这个调用才能知道函数的返回值。理解这个逻辑是关键。

**Comment by xiaoerhai** [comment]
明白了，谢谢解答。
