### ISSUE TITLE
为什么显示：AttributeError: 'super' object has no attribute '_init__'

### ISSUE THREAD

**Issue by zilin19** [neolee/pilot#576]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-19-b30970144227> in <module>
      1 garfield = Garfield(1)
----> 2 garfield.add(HelloBot())
      3 garfield.add(GreetingBot())
      4 garfield.add(FavoriteColorBot())
      5 garfield.add(CalcBot('looped'))

<ipython-input-14-a55562d4d67d> in __init__(self, runtype)
      1 class HelloBot(Bot):
      2     def __init__(self, runtype='once'):
----> 3         super()._init__(runtype)
      4         self.q = "Hi, What is your name?"
      5 

AttributeError: 'super' object has no attribute '_init__'

**Comment by Jared-Gong** [comment]
最好把代码段也贴出来，才能帮忙分析呀
另外代码行最好用代码的形式写 可以学习老师的支线课程[Markdown](https://www.bilibili.com/video/av75225128?p=2)这样其他同学也可以帮忙回答

**Comment by zilin19** [comment]
在jupyter lab 中做完联系（描红）后显示下面结果：
![QQ截图20191124124217](https://user-images.githubusercontent.com/51396634/69490740-82438d00-0ec6-11ea-9a66-85e156f4ce41.png)
前面输入的代码：
![QQ截图20191124143207](https://user-images.githubusercontent.com/51396634/69490791-4fe65f80-0ec7-11ea-9ecd-af74c53bf9db.png)


请指教

**Comment by Jared-Gong** [comment]
```super().__init__()```中```__init__```是两行下滑线

**Comment by zilin19** [comment]
还是不行啊 
![QQ截图20191124144834](https://user-images.githubusercontent.com/51396634/69490989-03e8ea00-0eca-11ea-9bcd-d098303cbc7e.png)

拼写和缩进也没有问题啊 
![QQ截图20191124145014](https://user-images.githubusercontent.com/51396634/69490996-12370600-0eca-11ea-8130-e3107cc637f4.png)

**Comment by Jared-Gong** [comment]
重启kernel，然后按顺序运行一遍试试。

**Comment by neolee** [comment]
一直没看到你的 Bot 类代码，你能把完整代码贴出来吗？

**Comment by zilin19** [comment]
![QQ截图20191124151416](https://user-images.githubusercontent.com/51396634/69491250-7b6c4880-0ecd-11ea-9886-cc8c8a176be7.png)
按顺序又运行了一遍，显示为：
![QQ截图20191124151603](https://user-images.githubusercontent.com/51396634/69491254-92ab3600-0ecd-11ea-941c-11db1f0f9edd.png)

**Comment by Jared-Gong** [comment]
你再把你和老师写的代码对对。你把```CalcBot()```下面那个```run()```去掉，因为你```Bot()```下面已经有了

**Comment by Jared-Gong** [comment]
你把老师的建议的两种方法混在一起使用了，要重新整理下思路。

**Comment by zilin19** [comment]
get 了，多谢
