### ISSUE TITLE
类中变量的引用 Bot.wait 和 self.wait 都能正常使用

### ISSUE THREAD

**Issue by getjake** [neolee/pilot#579]
```python
class Bot:
    
    wait = 1

    def __init__(self):
        self.q = ''
        self.a = ''
        
    def _think(self, s):
        return s # 先搞个缺省实现，
        
    def _say(self, s):
        time.sleep(self.wait) # 这里无论下写self.wait 还是 Bot.wait 都能正常使用 
        print(s)

    def run(self):
        self._say(self.q)
        self.a = input()    
        self._say(self._think(self.a)) # self.think 成为一个函数, self.think的输出，就是第三句话, 引用类内部的函数，需要在函数名前面加 'self.'
```
请问哪种写法更好呢？

----
在 Stackoverflow [这里](https://stackoverflow.com/questions/707380/in-python-how-can-i-access-static-class-variables-within-class-methods)
找到答案： 如果是用 `self.wait`是创建实例变量， `Bot.wait` 则是创建静态变量。

两者具体区别也不太懂

**Comment by Jared-Gong** [comment]
```wait```是类变量，可以通过实例和类进行访问，实现的功能是一样的。程序简单的话，比较好区分，程序一旦复杂就分不清到底是类变量还是实例变量了，特别是实例变量中有```wait```的时候。这是我的理解，期待老师的回答。

**Comment by xiaoerhai** [comment]
建议这时可以补一下笑来老师书里的`  Scoop（变量的作用域）`,在 `Part.3.B.2.classes-2.ipynb` 这一章节。

**Comment by Jared-Gong** [comment]
嗯嗯  学到了，老师讲的很细。[Scope（变量的作用域）](https://github.com/selfteaching/the-craft-of-selfteaching/blob/master/Part.3.B.2.classes-2.ipynb)

**Comment by neolee** [comment]
`wait` 是类变量，所以应该用 `Bot.wait` 来读写它。

如果你用 `self.wait` 本质上是创建了一个叫 `wait` 的实例变量，覆盖掉了同名的类变量（在这个类里面就没有类变量 `wait` 了） 。这无疑是一种混乱的情况，不推荐。所以要么它是类变量，要么是实例变量，不要混杂。

Python 对这种情况不加提示的覆盖处理，我觉得其实对学习者是不友好的。
