### ISSUE TITLE
Homebrew 下载的速度只有 18k

### ISSUE THREAD

**Issue by bianka727** [neolee/pilot#58]
下载的速度只有18k

**Comment by bianka727** [comment]
homebrew

**Comment by bianka727** [comment]
我前段时间好像安装过anaconda 从清华镜像 请问老师我是不是已经安装了python了？

**Comment by neolee** [comment]
有些网络下 Homebrew 确实比较慢，可以上网搜搜国内镜像，比如这个：

https://www.jianshu.com/p/6523d3eee50d

另外其他同学有类似的 issue #2 可以参考。

**Comment by bianka727** [comment]
我要如何结束当前的进程呢？直接关闭？现在28%
