### ISSUE TITLE
在定义 Dog 类时 kind = '' 的作用是什么呢？

### ISSUE THREAD

**Issue by lidewen-yue** [neolee/pilot#580]
class Dog:

    kind = ''  **#这段代码的作用时什么呢？在下文中也没有提及，删了也并不影响运行。**

    def __init__(self, name):
        self.name = name
        
    def bark(self):
        return 'woof-woof'

a = Dog('Fido')
b = Dog('Buddy')

**Comment by Jared-Gong** [comment]
```kind```是类变量，可以通过类来传参。```name```是实例变量，通过实例传参。简单的说，类变量统一了全部的类别，不管你是鸡是狗是猫都是动物，但实例变量是把这三种动物区分开来，输入的可以不一样。

**Comment by lidewen-yue** [comment]
但是为什么kind = ' '里面却是空的呢？放一个空的东西又有什么意义呢？

**Comment by Jared-Gong** [comment]
老师举的一个例子，让我们更好的了解类变量和实例变量的区别和如何实现传参的吧。可以为空，只是后面通过```class```访问```kind```并传参，老师的例子是后面传了一个```canidae```,你可以把```canidae```放到```kind```里面```kind = 'canidae' ```试试效果是不是一样。

**Comment by neolee** [comment]
父类里定义了这个类变量，算是一种“接口（*interface*）”，所有子类也就有了这个接口，而子类里就需要给它一个合适的值（表明特定子类对应的动物的生物学分类）。

**Comment by lidewen-yue** [comment]
昨天看了老师做的支线教程后就明白了，谢谢。
