### ISSUE TITLE
定义对话机器人是，提问为什么是乱码？

### ISSUE THREAD

**Issue by lidewen-yue** [neolee/pilot#584]
![image](https://user-images.githubusercontent.com/56989072/69595825-94930780-103b-11ea-8003-ebe056c8d7b6.png)
为什么在乱码里老是会有Dog的信息呢？之前的编码我全都删了啊，这个也是第一条，我也重新执行过了，而且这个的提问为什么不是hi，what is
your name？

**Comment by neolee** [comment]
因为你 `Bot` 类里的 `run()` 方法里，第一句 `print()` 里面的参数写错了，你仔细看看……
