### ISSUE TITLE
Markdown 演练问题点

### ISSUE THREAD

**Issue by robertswg001** [neolee/pilot#585]
![markdown issue](https://user-images.githubusercontent.com/56988943/69603694-5f47e300-1056-11ea-8da8-c180ab21535f.png)

按照支线4课程演练时，在使用Git命令时出现如图三个问题，请老师指点。

**Comment by neolee** [comment]
第一个没啥问题吧。

第二个，你用 `git status` 就行了，我用的那个就是这个的简写，需要自己配置，你可以搜索下 “git command alias” 就知道怎么配置了。

第三个，你没有做 git 的初始化配置，先学习下讲 git 的 支线课程就会了。
