### ISSUE TITLE
安装 git 失败

### ISSUE THREAD

**Issue by leecoon** [neolee/pilot#586]
李老师，我无法用scoop 安装 git，反复试过都不行，也找不出问题，请看 
PS C:\Users\Leon_Liang> scoop list
Installed apps:

  7zip 19.00
  git  *failed*

PS C:\Users\Leon_Liang> scoop uninstall git
Uninstalling 'git' ().
'git' was uninstalled.
PS C:\Users\Leon_Liang> scoop install git
Updating Scoop...
Updating 'main' bucket...
Checking repo... ok
The main bucket was added successfully.
Scoop was updated successfully!
Installing 'git' (2.24.0.windows.2) [64bit]
无法连接到远程服务器
URL https://github.com/git-for-windows/git/releases/download/v2.24.0.windows.2/PortableGit-2.24.0.2-64-bit.7z.exe#/dl.7z is not valid

**Comment by neolee** [comment]
网络问题，换网络或者挂代理试试。

**Comment by leecoon** [comment]
还真是，我换了手机wifi就可以了，感谢李老师。大家有同样问题的也请注意下，中国移动的网络不行，要用别的。

**Comment by neolee** [comment]
其实这个完全看自己的网络环境，也有别的同学移动不行，换电信就好……
