### ISSUE TITLE
'git' 不是内部或外部指令

### ISSUE THREAD

**Issue by hanshu231** [neolee/pilot#588]
![QQ截图20191126164450](https://user-images.githubusercontent.com/56158763/69613194-1d299c00-106c-11ea-8954-7a48b1140627.png)

**Comment by neolee** [comment]
你有按照配置指南一步步成功完成环境安装配置吗？

即使已经做好了环境准备，也要用 PowerShell，你截图里用的是 cmd 界面，是没法使用用 Scoop 安装的软件包（比如 `git`）的。
