### ISSUE TITLE
 下载和安装 homebrew 时提示失败

### ISSUE THREAD

**Issue by dongruixue** [neolee/pilot#589]
=> This script will install:
/usr/local/bin/brew
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew
/usr/local/Homebrew

Press RETURN to continue or any other key to abort
==> Downloading and installing Homebrew...
remote: Enumerating objects: 35, done.
remote: Counting objects: 100% (35/35), done.
remote: Compressing objects: 100% (31/31), done.
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
Failed during: git fetch origin master:refs/remotes/origin/master --tags --force
(base) dongruixuedeiMac:~ dongruixue$ brew update
-bash: brew: command not found
(base) dongruixuedeiMac:~ dongruixue$ 
(base) dongruixuedeiMac:~ dongruixue$ 
(base) dongruixuedeiMac:~ dongruixue$ 
(base) dongruixuedeiMac:~ dongruixue$ 
(base) dongruixuedeiMac:~ dongruixue$ 
(base) dongruixuedeiMac:~ dongruixue$ 
(base) dongruixuedeiMac:~ dongruixue$ 
(base) dongruixuedeiMac:~ dongruixue$ 
(base) dongruixuedeiMac:~ dongruixue$ 
(base) dongruixuedeiMac:~ dongruixue$ 
(base) dongruixuedeiMac:~ dongruixue$ /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" 

==> This script will install:
/usr/local/bin/brew
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew
/usr/local/Homebrew

Press RETURN to continue or any other key to abort
==> Downloading and installing Homebrew...
remote: Enumerating objects: 35, done.
remote: Counting objects: 100% (35/35), done.
remote: Compressing objects: 100% (31/31), done.
Receiving objects:   1% (2512/129137), 1.50 MiB | 3.00 KiB/s       
这里要过非常久之后又会报错，不明白是哪里出了问题

**Comment by dongruixue** [comment]
看了前面的人的issue，不确定是不是和 issue2同样问题，其他的同学都没有同样的问题吗？

**Comment by dongruixue** [comment]
Last login: Tue Nov 26 22:46:38 on ttys001
(base) dongruixuedeiMac:~ dongruixue$ 
(base) dongruixuedeiMac:~ dongruixue$ ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
==> This script will install:
/usr/local/bin/brew
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew
/usr/local/Homebrew

Press RETURN to continue or any other key to abort
==> Downloading and installing Homebrew...
error: RPC failed; curl 52 Empty reply from server
fatal: the remote end hung up unexpectedly
Failed during: git fetch origin master:refs/remotes/origin/master --tags --force
(base) dongruixuedeiMac:~ dongruixue$ 
又试了一次，还是不行

**Comment by neolee** [comment]
网络问题。

**Comment by dongruixue** [comment]
那应该如何处理？网络下载其他都好的啊。

**Comment by neolee** [comment]
网络遍布全世界，访问某些服务很快不代表访问 Homebrew 所需要的服务就没问题，这个我上课解释过。

办法就是换网络或者挂代理试试。有很多同类的 issue。

**Comment by dongruixue** [comment]
下载好了  换个时间点 换个网络
