### ISSUE TITLE
安装 git 失败提示“操作已超时”

### ISSUE THREAD

**Issue by maxuanr** [neolee/pilot#59]
安装git速度很慢，并无法成功安装：提示“操作已超时”。
![1571907087(1)](https://user-images.githubusercontent.com/53324687/67469296-9190aa00-f67e-11e9-8e9f-bd41f8e9c44d.jpg)

**Comment by neolee** [comment]
网络问题，换其他网络尝试，或者试试代理，或者换个时间重试。
