### ISSUE TITLE
在 Visual Studio Code 运行 py 文件报错：无法将“conda”项识别为 cmdlet、函数、脚本文件或可运行程序的名称

### ISSUE THREAD

**Issue by jianlonglaoda** [neolee/pilot#590]
![1574824557(1)](https://user-images.githubusercontent.com/48595445/69691081-ccb44c00-1108-11ea-801a-8ec5a838d9b6.png)
### 老师你好，遇到一个问题好几天都解决不了，麻烦指点一下
1.在网上查找原因，是没有添加环境变量到系统中，在添加环境变量时，找不到`Library\bin`文件
2. 查找了Issues没找到相同的问题

**Comment by neolee** [comment]
我的环境配置指南不是用 Anaconda，我也不推荐新人使用这个东西，我不太清楚为什么你会碰到这个问题，关于你之前做了哪些操作，有更多信息吗？

**Comment by jianlonglaoda** [comment]
![1574841059(1)](https://user-images.githubusercontent.com/48595445/69704129-d43a1c00-112d-11ea-8374-c5e5ffa46b83.png)
当时报了自学训练营，然后跟着步骤下载了，记得在这里面点了。

**Comment by neolee** [comment]
对于新手来说，一个系统里有 Anaconda 再装别的 Python 一般都是一片混乱，所以我建议你干净的卸载和删除 Anaconda，然后再按照我们的环境配置指南一步步做好。

**Comment by jianlonglaoda** [comment]
弄了一下午，刚解决好，谢谢老师
