### ISSUE TITLE
域名绑定 github 报错的问题

### ISSUE THREAD

**Issue by qihongsong** [neolee/pilot#592]
老师好
我按照笑来老师区块连小白书里的方法购买了域名：www.jinjiafan.com
然后再github里创建了一个仓库，还有写了两篇文章
按照笑来老师的设置方法把域名填进了Custom domain里
然后ping了我的用户名qihongsong.github.io得到ip为185.199.109.153
把这个地址加到了域名解析的DNS里
但是我进入域名的时候报错了，一下是报错信息，请老师帮我看看，我弄了一天了，还是没搞懂：
404

File not found

The site configured at this address does not contain the requested file.

If this is your site, make sure that the filename case matches the URL.
For root URLs (like http://example.com/) you must provide an index.html file.

Read the full documentation for more information about using GitHub Pages. 

谢谢老师

**Comment by neolee** [comment]
我访问你的 qihongsong.github.io 这个地址就是 404，那你绑自定义域名肯定也不会成功啦。

你要先保证 qihongsong.github.io 可以正确访问，然后再做域名转发的配置，才能让另一个域名工作起来。

**Comment by neolee** [comment]
然后我去看了看你的 GitHub profile，你并没有建立名字叫 `qihongsong.github.io` 的 repo，那你的 qihongsong.github.io 网站自然也不存在呀。你看过我的支线课程 4 吗？

**Comment by qihongsong** [comment]
老师我看过您的直线课程4讲markdown的那节


现在我创建了一个仓库名字叫jin-jiafan.github.io
然后这个仓库的ip添加在阿里云的解析上了，可还是报错，请问老师这个要怎么处理。感谢🙏





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Neo Lee <notifications@github.com&gt;
发送时间: 2019年11月27日 19:15
收件人: neolee/pilot <pilot@noreply.github.com&gt;
抄送: qihongsong <474858954@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[neolee/pilot] 域名绑定github报错的问题 (#592)




然后我去看了看你的 GitHub profile，你并没有建立名字叫 qihongsong.github.io 的 repo，那你的 qihongsong.github.io 网站自然也不存在呀。你看过我的支线课程 4 吗？

**Comment by neolee** [comment]
你现在访问 https://qihongsong.github.io/ 还是 404 啊，这里你有好几个问题：

1. 你建立的用于 GitHub Pages 的 repo 名字，必须是 `qihongsong.github.io`，一个字儿也不能错，也就是你的 GitHub 用户名，加上 `.github.io`，你现在用的并不是这个名字。

2. 在这个 repo 下必须有一个叫做 `README.md` 或者 `README.markdown` 的文件，这个文件会成为站点的主页，你现在的 repo 下并没有这样的文件。

这两点我的课程里都有说的，你没认真看。按照上面的两条修改，你应该可以让 https://qihongsong.github.io/ 这个站点可以访问，在此之前不用去动你的 DNS 设置，DNS 设置每次都需要时间来生效的。

在前面这步完成无误之后，再去你的 DNS 供应商那里设置你的 www.jinjiafan.com 域名的 A 记录和 CNAME 记录，应该就可以了（我大致看了你现在 repo 里的 CNAME 文件，应该没啥问题）。

做事要有有条理有定力，不然反而浪费更多时间。
