### ISSUE TITLE
逻辑判断与分支：程序上的问题

### ISSUE THREAD

**Issue by PATIEN** [neolee/pilot#593]
<img width="611" alt="捕获" src="https://user-images.githubusercontent.com/53363523/69722320-c4343380-1151-11ea-80ce-11d63de9f551.PNG">
李骏老师，你好，这是我在练习时发现的一个非常隐秘的问题
def type_1(n):
    if isinstance(n, int):
        return 'int'
    elif isinstance(n, bool):
        return 'bool'
    else:
        return "unknow"

type_1(False)
‘int’  #结果竟然是int，而不是‘bool’
于是，我又将程序改为如下：

**Comment by PATIEN** [comment]
def type_1(n):
    if isinstance(n, float):
        return 'float'
    elif isinstance(n, bool):
        return 'bool'
    else:
        return "unknow"

type_1(False)
'bool'   #结果变成了‘bool’

然后继续将float替换成str 
type_1(False)
'bool'   #结果为‘bool’

再继续将int和bool的顺序调换过来，结果也不会出错。
def type_1(n):
    if isinstance(n, bool):
        return 'bool'
    elif isinstance(n, int):
        return 'int'
    else:
        return "unknow"
type_1(False)
'bool'   #结果为‘bool’

这种情况该如何去理解呢？int 和 bool难道还有先后顺序？

**Comment by neolee** [comment]
请参考 #568 和 #466
