### ISSUE TITLE
请教大家：这里的 %s 是什么用法

### ISSUE THREAD

**Issue by onthebus98** [neolee/pilot#594]
![屏幕快照 2019-11-27 下午10 46 42的副本](https://user-images.githubusercontent.com/53966721/69733262-0d8f7d80-1168-11ea-8dc0-967f06721328.png)

**Comment by neolee** [comment]
这是有 f-string 之前拼字符串的方法，等价于下面的这句：

```python
print(f'My name is {name} and I come from {city}')
```

**Comment by onthebus98** [comment]
难怪从python3.7 的手册里也没有找到解释.
