### ISSUE TITLE
安装 git 时失败，非网络原因

### ISSUE THREAD

**Issue by BruceWu51** [neolee/pilot#595]
PS E:\> scoop install git
Installing 'git' (2.24.0.windows.2) [64bit]
PortableGit-2.24.0.2-64-bit.7z.exe (41.8 MB) [=================================================================================================================] 100%
Checking hash of PortableGit-2.24.0.2-64-bit.7z.exe ... ok.
Extracting dl.7z ... Expand-7zipArchive : 无法对参数“FilePath”执行参数验证。参数为 Null 或空。请提供一个不为 Null 或空的参数，然后重试该命令。
所在位置 C:\Users\热爱学习的小吴\scoop\apps\scoop\current\lib\install.ps1:563 字符: 13
+             & $extract_fn -Path "$dir\$fname" -DestinationPath "$dir\ ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Expand-7zipArchive]，ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Expand-7zipArchive

**Comment by neolee** [comment]
执行 `scoop checkup` 按照建议执行。

中间如果碰到权限错误，尝试打开一个 Admin 权限的 PowerShell 来执行。
