### ISSUE TITLE
第十一章课程练习中的执行问题

### ISSUE THREAD

**Issue by qingyix** [neolee/pilot#596]
![1](https://user-images.githubusercontent.com/48583363/69789708-087c0e00-11fc-11ea-8b2c-84019014d316.JPG)
初学小白，仔细检查前面的代码，没发现问题，请帮忙看看提示错误，谢谢！

**Comment by neolee** [comment]
从出错信息看，你的 `Garfield` 类的类定义里应该有问题，可能 `__init__()` 方法没写对（比如，这个方法的名字前后都是两个下划线，不是一个哦）。

你可以吧 `Garfield` 类的定义贴出来看看。

**Comment by qingyix** [comment]
class Garfield:
    def __int__(self,wait=1):
        Bot.wait = wait
        self.bots = []
    def add(self,bot):
        self.bots.append(bot)
    def _prompt(self,s):
        print(s)
        print()
    def run(self):
        self._prompt("This is Garfield dialog system. Let's talk.")
        for bot in self.bots:
            bot.run()

**Comment by qingyix** [comment]
![1](https://user-images.githubusercontent.com/48583363/69811182-80602d80-1228-11ea-87bf-6406e8c8203f.JPG)
您看看

**Comment by qingyix** [comment]
我检查没看出问题

**Comment by neolee** [comment]
那个方法叫 `__init__()`，你再仔细看看你的叫啥……

**Comment by qingyix** [comment]
谢谢老师 我检查前面也不多 疏忽了 估计看多了。

**Comment by qingyix** [comment]
我检查前面都不对，估计看花了，谢谢老师，很不好意思。
