### ISSUE TITLE
为什么返回值与预期结果不同？

### ISSUE THREAD

**Issue by Maxuanrui** [neolee/pilot#597]
![image](https://user-images.githubusercontent.com/53324687/69789647-eda99980-11fb-11ea-9c36-eb6899fb1c09.png)
我定义了type_0(x)这个函数;
当我的输入x为bool，则返回(x,"是布尔值");
但是type_(True)并不返回预期结果；
反复检查后还是不明白这是为什么

**Comment by neolee** [comment]
请参考 #568 和 #466
