### ISSUE TITLE
进阶篇 - 同步学习用书 - Git Bash 找不到 .git 文件

### ISSUE THREAD

**Issue by reganhsl** [neolee/pilot#599]
按官方文件显示，是有两行git结尾的文件，要怎么安装？
官方结果如下：<img width="482" alt="图片2" src="https://user-images.githubusercontent.com/48468031/69803316-d330e980-1216-11ea-9254-9ced810a3df7.png">

我的结果如下：<img width="466" alt="图片1" src="https://user-images.githubusercontent.com/48468031/69803131-2fdfd480-1216-11ea-8ac9-0e768c0eb5eb.png">

**Comment by neolee** [comment]
你要在你 fork & clone 到本地的学习用书目录下执行这个才行。

另外，如果按照我们的指南配置好环境，并不需要用 Git Bash，在 PowerShell 下装好 git 即可。。
