### ISSUE TITLE
建议说明文档里要有一个安装成功后的载图

### ISSUE THREAD

**Issue by tsao86** [neolee/pilot#6]
很感谢老师提供这样的一个学习平台。
但有一个建议，在学习的文档里如果可以加上安装成功后的一个载图，
那新人就知道在自己当前的环境下到底是安装成功了还是不成功，有一些问题在终端下面显示出来的英文和代码真心不知道是什么！希望可以改进，定会帮到不少新手。

**Comment by neolee** [comment]
之前有过这样的考虑，但计算机环境千差万别，我自己的系统又已经使用很久，和新人肯定有不同，比较担心发出来反而误导大家。

你的环境配置如果成功，过程中如有截图可以分享出来，可能会很有用。
