### ISSUE TITLE
合并第一次下载的 pilot-student 和第二次下载的 pilot-student 方法有吗

### ISSUE THREAD

**Issue by Pony-2019** [neolee/pilot#600]
学习第一阶段下载一次pilot-student，现在准备学习第二阶段就第二次下载了pilot-student，这两次下载的内容有方法合并到一起吗？：）

**Comment by neolee** [comment]
按照我们在 [文档](https://github.com/neolee/pilot/blob/master/README-S2.md) 里面讲的，合并的办法就是按照 [GitHub 官方指南](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork) 来完成你之前那个 repo 和新版学习用书之间的同步。

但这个不是必须的，你完全可以保留两个本地版本分别使用。
