### ISSUE TITLE
Bot.py 代码在 VS Code 中运行和 jupyter lab 中运行结果不一样

### ISSUE THREAD

**Issue by chenmite** [neolee/pilot#601]
![image](https://user-images.githubusercontent.com/25859760/69814189-9f61be00-122e-11ea-9a41-ac29f1dcefba.png)
上图在jupyter lab 中可以运行到第四个实例，即可以运行到运算。
但在VScode中运行到第三个实例就结束了。

**Comment by neolee** [comment]
可以把 VSCode 中运行的代码完整贴出来吗？

**Comment by chenmite** [comment]
from time import sleep
from termcolor import colored
import random
from simpleeval import simple_eval


class Bot:
    
    wait = 1
    
    def __init__(self):
        self.q = ''
        self.a = ''
    
    def _think(self, s):
        return s
    
    def _format(self, s):
        return colored(s,'blue')
    
    def run(self):
        sleep(Bot.wait)
        print(self._format(self.q))
        self.a = input()
        sleep(Bot.wait)
        print(self._format(self._think(self.a)))

    
class HelloBot(Bot):
    def __init__(self):
        self.q = 'Hi, what is your name'
        
    def _think(self,s):
        return f'Hello {s}'


class GreetingBot(Bot):
    def __init__(self):
        self.q = "How are your today?"
        
    def _think(self, s):
        if 'good' in s.lower() or 'fine' in s.lower():
            return "I am feeling good too"
        else:
            return "Sorry to hear that"


class FavoriteColorBot(Bot):
    def __init__(self):
        self.q = "What is your favorite color?"
        
    def _think(self, s):
        colors = ['red', 'orange', 'yellow', 'green', 'blue', 'indigo', 'purple']
        return f"You like {s.lower()}? My favorite color is {random.choice(colors)}"


class CalcBot(Bot):
    def __init__(self):
        self.q = "Through recent upgrade I can do calculation now. Input some arithmetic expression to try:"

    def _think(self, s):
        result = simple_eval(s)
        return f"Done. Result = {result}"


a = HelloBot()     
b = GreetingBot()
c = FavoriteColorBot()
f = CalcBot()

a.run()
b.run()
c.run()
f.run()

**Comment by neolee** [comment]
我把你的代码 copy 下来然后存成文件，运行无问题：

<img width="665" alt="Bot Run" src="https://user-images.githubusercontent.com/24796/69816832-2c5b4600-1234-11ea-8f26-755f614a82d8.png">

**Comment by chenmite** [comment]
问题已解决，我在VS中忘了保存，一直运行的是之前编辑的代码
