### ISSUE TITLE
第十一课练习部分最后四则远算结果不对

### ISSUE THREAD

**Issue by qingyix** [neolee/pilot#602]
![1](https://user-images.githubusercontent.com/48583363/69815603-a4743c80-1231-11ea-9ffa-91c96c8561cd.JPG)
前面程序也检查了，没发现问题。
![2](https://user-images.githubusercontent.com/48583363/69815680-ccfc3680-1231-11ea-845d-45949a0958bd.JPG)

**Comment by neolee** [comment]
`CalcBot` 的 `_think()` 方法最后一句里 `{reslut}` 这个变量拼写错了。

其实出错信息最后一句已经说的很清楚了：name `reslut` is not defined

**Comment by qingyix** [comment]
已解决
