### ISSUE TITLE
为何我的 outline 部分没有老师视频的树形结构？不知如何设置？

### ISSUE THREAD

**Issue by 18p2p** [neolee/pilot#604]
![1](https://user-images.githubusercontent.com/48624321/69843438-74b14d00-12a2-11ea-90da-e2fb7efa99ea.png)
![2](https://user-images.githubusercontent.com/48624321/69843444-79760100-12a2-11ea-96e2-c00889dee366.png)

**Comment by neolee** [comment]
按理说只要你装了 Visual Studio Code 的 Python 插件，就应该有。
