### ISSUE TITLE
配置 scoop 出现如下问题？

### ISSUE THREAD

**Issue by zhaoliang918** [neolee/pilot#606]
PS C:\Users\a> scoop checkup
WARN  LongPaths support is not enabled.
You can enable it with running:
    Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1
ERROR 'dark' is not installed! It's required for unpacking installers created with the WiX Toolset. Please run 'scoop install dark' or 'scoop install wixtoolset'.
WARN  Found 2 potential problems.
PS C:\Users\a> scoop install dark

**Comment by neolee** [comment]
Wiki 和 Issues 里都有不少类似问题。

基本上你照它说的做就好。
