### ISSUE TITLE
配置 scoop 如下然后不知道如何操作了

### ISSUE THREAD

**Issue by zhaoliang918** [neolee/pilot#607]
PS C:\Users\a> scoop uninstall git
Uninstalling 'git' ().
'git' was uninstalled.
PS C:\Users\a> scoop list
Installed apps:

  7zip 19.00
  dark  *failed*
  innounp 0.49

**Comment by neolee** [comment]
在使用 Scoop 安装 Python 之前，你需要：
1. `scoop checkup` 检查出来的问题都要解决掉；
2. `scoop list` 里标记为 `failed` 的项要重新安装（先 `scoop uninstall xxx` 再 `scoop install xxx`）直至成功；
3. 确保 git 安装成功，可以用 Scoop 也可以用别的办法安装，用 `git --version` 可以确认是不是装好了，以及安装版本为何。

以上都 OK 了，就可以按照指南的说明继续安装 Python 了。

**Comment by neolee** [comment]
另外，同一个问题不需要开多个 issue。

**Comment by zhaoliang918** [comment]
PS C:\Users\a> scoop install dark
Scoop uses Git to update itself. Run 'scoop install git' and try again.
ERROR It looks like a previous installation of dark failed.
Run 'scoop uninstall dark' before retrying the install.
WARN  'dark' () is already installed.
Use 'scoop update dark' to install a new version.
PS C:\Users\a> scoop install git
Scoop uses Git to update itself. Run 'scoop install git' and try again.
Installing 'git' (2.24.0.windows.2) [64bit]
PortableGit-2.24.0.2-64-bit.7z.exe (41.8 MB) [>                                  ]   1%
无法从传输连接中读取数据: 远程主机强迫关闭了一个现有的连接。。
URL https://github.com/git-for-windows/git/releases/download/v2.24.0.windows.2/PortableGit-2.24.0.2-64-bit.7z.exe#/dl.7z is not valid

**Comment by zhaoliang918** [comment]
老师是这样操作吗?小白学习甚是不懂    
PS C:\Users\a> scoop checkup
WARN  LongPaths support is not enabled.
You can enable it with running:
    Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1
ERROR 'dark' is not installed! It's required for unpacking installers created with the WiX Toolset. Please run 'scoop install dark' or 'scoop install wixtoolset'.
WARN  Found 2 potential problems.
PS C:\Users\a>   Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem'

位于命令管道位置 1 的 cmdlet Set-ItemProperty
请为以下参数提供值:
Name: -Name 'LongPathsEnabled' -Value 1
Value:

**Comment by neolee** [comment]
你装 git 失败了，后面很多操作都会有问题，所以要先确保 git 装好可以工作。

失败原因是网络不好，可以换个网络或者挂代理试试。类似问题已经有很多，可以在 issues 里搜索下。
