### ISSUE TITLE
如何实现工作任务的自动化汇总

### ISSUE THREAD

**Issue by iceberg-yuan** [neolee/pilot#608]
一、想在工作中用python实现工作任务的自动化汇总，跟李老师费用汇总的例子差不多，实际场景是这样的：

办公室有8个人，周五每个人填写本周工作完成情况和下周工作计划，工作分重点工作、常规工作、临时工作（模板见附图）。由专人汇总，下周一8点半前部门开会用。因为各种原因，汇总工作很繁琐，且易出现漏缺等情况。考虑实现自动化汇总，下列步骤是否可行：
1.	通过办公内网，搭建一个文件服务器，ftp服务器。
2.	每个人按模板填写，填写完后上传到服务器。
3.	服务器从周六的0点开始自动汇总，设定每1个小时汇总一次，生成一个汇总文件。因为可能有补充修改，所以每次汇总，发现文件有更新，要把原来汇总的进行覆盖更新。
4.	周一的8点之前停止汇总。

二、涉及到知识点
1.内网搭建ftp服务器
2.按照汇总时间生成一个” yyyymmdd.xls”汇总文件。
3.遍历每个人的xls文件，将工作记录插入汇总文件。
4.判断文件是否被更新，如有更新，先删除汇总文件中的原有记录，插入新记录。
5.其他没想到的知识点。

![微信图片_20191129105446](https://user-images.githubusercontent.com/57003256/69848053-dcbc5f00-12b3-11ea-93c8-1884e47973bb.jpg)

**Comment by iceberg-yuan** [comment]
请问李老师项目是否可行？

**Comment by neolee** [comment]
基本是可行的，用到的知识点和我介绍那个案例大抵差不多。

不过有个建议：去掉反复汇总和更新的这个需求。这并不是很必要的一个特性，而且会带来很多实现上的麻烦。

实际上你只要设定一个交报告的 deadline（比如周日晚 10 点），然后在此之后执行汇总程序，这样你还有时间 review 一下汇总的报告，第二天一早开会正好。以我多年做管理的经验，这比允许随意上传然后再反复改要好得多。

**Comment by iceberg-yuan** [comment]
ok，那开始尝试学习动手了

**Comment by Pony-2019** [comment]
：0
我也有类似的需求，可以交流一下。 @iceberg-yuan
