### ISSUE TITLE
Mac 环境配置安装 brew 老是卡住安装不了

### ISSUE THREAD

**Issue by zsqiang001** [neolee/pilot#61]
![WechatIMG372](https://user-images.githubusercontent.com/37511474/67474705-7d04df80-f687-11e9-8676-e6d125f16688.jpeg)

**Comment by neolee** [comment]
这是网络的问题，换个网络或者挂代理，或者用国内的镜像，例如这里描述的办法：

https://www.jianshu.com/p/6523d3eee50d

**Comment by bianka727** [comment]
换个网试试，我折腾一下午了

**Comment by zsqiang001** [comment]
> 换个网试试，我折腾一下午了
按李老师的指导安装好了，VScode安装好新建文件的时候不能保存，就是保存不了hello.py,你遇到了吗
