### ISSUE TITLE
安装 JuputerLab 插件报错，请教是什么问题？如何解决？

### ISSUE THREAD

**Issue by yiguo-hu** [neolee/pilot#610]
![捕获](https://user-images.githubusercontent.com/51398930/69855525-ab995a00-12c6-11ea-9646-23e90eab989b.JPG)
![捕获02](https://user-images.githubusercontent.com/51398930/69855555-b48a2b80-12c6-11ea-89eb-042f3b80c5c0.JPG)
![捕获03](https://user-images.githubusercontent.com/51398930/69855566-b81db280-12c6-11ea-9824-018a485c1ded.JPG)

**Comment by neolee** [comment]
出错信息不是很完整，不太好判断，有几个点：

1. 所以你现在 Jupyter Lab 能用么？ ToC 插件正常么？
2. 看截屏里你的 Jupyter Lab 是 Anaconda 环境的，我们的配置指南不使用 Anaconda，而且我也不推荐新手用 Anaconda，里面坑很多。
