### ISSUE TITLE
类定义与对象创建操作输入问题

### ISSUE THREAD

**Issue by Yolandasoar** [neolee/pilot#612]
![image](https://user-images.githubusercontent.com/57901787/69862022-890e3d80-12d4-11ea-8a71-4606840238cd.png)

老师，已经检查过很多很多次了，还是说有type error，我迷茫了，还请帮忙解答一下，谢谢！

**Comment by neolee** [comment]
截屏失败了……你把图片拖进输入框，要等那个 Uploading 提示变成 img 标签。

**Comment by neolee** [comment]
那个方法叫 `__init__()`，前后都是两个下划线，我在讲课的时候说过 😀

**Comment by Yolandasoar** [comment]
> 那个方法叫 `__init__()`，前后都是两个下划线，我在讲课的时候说过 😀

图片贴好了，下划线显示没有问题，9和11，12行哪里出了问题吗？

**Comment by Yolandasoar** [comment]
> 那个方法叫 `__init__()`，前后都是两个下划线，我在讲课的时候说过 😀

老师我知道了，我打得是单下划线，仔细看文字里面也有注释，我太大意了
