### ISSUE TITLE
机器人视频讲解中用Visual code保存python源代码中有个命令看不清，是workon jupyter 吗？ 蒙了好几遍都不对

### ISSUE THREAD

**Issue by Lilidandan321** [neolee/pilot#613]
![image](https://user-images.githubusercontent.com/53359222/69868526-e9a57680-12e4-11ea-8502-58bfd0edf62b.png)
![image](https://user-images.githubusercontent.com/53359222/69868534-ee6a2a80-12e4-11ea-88a2-4515c8c8c421.png)

**Comment by neolee** [comment]
那个是我用了虚拟环境才需要执行，你不用管的，直接上就行了 😀

**Comment by Lilidandan321** [comment]
好啦，谢谢老师。
