### ISSUE TITLE
Mac 运行 python -m pip install --upgrade pip 出错

### ISSUE THREAD

**Issue by powerzhengh** [neolee/pilot#614]
![001](https://user-images.githubusercontent.com/58015512/69871901-f929bd00-12ee-11ea-85c0-1d12d194c56b.png)

**Comment by neolee** [comment]
如果 `python -V` 返回是 2.7.x 的话，说明 `python` 是指向老版本的，可以改用 `python3` 这个命令。

所以你可以试试 `python3 -m pip install -U pip`。

不过你现在的 Python 是 3.8.0，这个版本我没试过，风险自担……
