### ISSUE TITLE
第十一课作业最后一个编程执行错误

### ISSUE THREAD

**Issue by qingyix** [neolee/pilot#616]
![3](https://user-images.githubusercontent.com/48583363/69874262-7c4e1180-12f5-11ea-85eb-150ab5c1024b.JPG)
前面代码检查，没发现问题。还有，上面练习部分之前可以执行，重新打开后也出现此问题，重新看一遍再次执行又没问题。现在就剩最后一步出现问题，觉得奇怪？

**Comment by neolee** [comment]
出错信息最后部分已经显示出问题了，第 16 行最后应该是 `self.a`，不是 `self, a`。
