### ISSUE TITLE
git 配置不了user.name/email

### ISSUE THREAD

**Issue by chenmite** [neolee/pilot#617]
![image](https://user-images.githubusercontent.com/25859760/69875387-f2ec0e80-12f7-11ea-9a8b-cef60e3faeee.png)

**Comment by chenmite** [comment]
![image](https://user-images.githubusercontent.com/25859760/69875447-22028000-12f8-11ea-9df6-836f93cd8e0b.png)

**Comment by chenmite** [comment]
![image](https://user-images.githubusercontent.com/25859760/69875485-39da0400-12f8-11ea-9e23-6c8c7a367ba1.png)

**Comment by neolee** [comment]
命令漏了空格。
