### ISSUE TITLE
学习用书可编辑程序执行部分出错

### ISSUE THREAD

**Issue by qingyix** [neolee/pilot#618]
不是可执行代码 执行后错误。可能我操作谋按键。
![5](https://user-images.githubusercontent.com/48583363/69875599-858cad80-12f8-11ea-99d0-5650a04606e1.JPG)
![4](https://user-images.githubusercontent.com/48583363/69875619-8e7d7f00-12f8-11ea-9b06-c7e6b3b2da74.JPG)

**Comment by qingyix** [comment]
不知怎么恢复原状态

**Comment by neolee** [comment]
选中出问题那个格子，在上面工具栏的那个下拉列表里选 “Code”。
