### ISSUE TITLE
Garfield 写的跟老师一样，检查好几遍没发现问题，运行出错

### ISSUE THREAD

**Issue by Lilidandan321** [neolee/pilot#620]
![image](https://user-images.githubusercontent.com/53359222/69894666-b4893a80-135d-11ea-918c-98819ab158e8.png)
![image](https://user-images.githubusercontent.com/53359222/69894668-b8b55800-135d-11ea-9bb4-3f11ea3be9f0.png)

**Comment by neolee** [comment]
你 Garfield 类里定义的那个方法应该叫 `add`，而你多了个下划线。

另外两个问题，一个是你的类的命名很杂乱，一会儿首字母大写一会儿全小写，一会儿有 Bot 结尾一会儿没有，一定要养成追求一致性的好习惯；另一个是你初始化 garfield 对象那一段，某个 add 调用的参数写的不对，写代码一定要养成自查习惯，写完多看几遍。

**Comment by Lilidandan321** [comment]
好的，好了，谢谢老师
