### ISSUE TITLE
复制教材中的代码报错

### ISSUE THREAD

**Issue by xiaoerhai** [neolee/pilot#627]
执行以下代码：

```Python
print("压缩版日期：", t.strftime("%Y-%-m-%-d"))
```
出现以下error：
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-40-f2616ef11027> in <module>
      4 print("日：", t.strftime("%d"))
      5 print("完整日期：", t.strftime("%Y-%m-%d"))
----> 6 print("压缩版日期：", t.strftime("%Y-%-m-%-d"))

ValueError: Invalid format string
```

**Comment by neolee** [comment]
看代码没有问题，你的 Python 版本是？

**Comment by xiaoerhai** [comment]
python 3.7.5

**Comment by iceberg-yuan** [comment]
我的这句print(t.strftime("%Y年%m月%d日 %H时%M分"))提示错误：
---------------------------------------------------------------------------
UnicodeEncodeError                        Traceback (most recent call last)
<ipython-input-71-6fcde9ab0465> in <module>
----> 1 print("完整日期：", t.strftime("%Y年-%m-%d"))

UnicodeEncodeError: 'locale' codec can't encode character '\u5e74' in position 2: encoding error

**Comment by iceberg-yuan** [comment]
是不是这种自由组合的格式不支持？

**Comment by neolee** [comment]
@iceberg-yuan 我试了试你的代码，没啥问题：

<img width="516" alt="datetime" src="https://user-images.githubusercontent.com/24796/69912964-3c5d6a80-146c-11ea-86ba-f9ccf8ea69f1.png">

你这个 `UnicodeEnodeError` 比较奇怪，我已经很久没见过这个错误了，感觉是你系统的字符编码设置有点问题，你的操作系统和浏览器是什么版本？

**Comment by neolee** [comment]
@xiaoerhai @iceberg-yuan 我 Google 了一下，下面这个页面可能对你们有帮助：

https://segmentfault.com/q/1010000003070325

**Comment by neolee** [comment]
我在 Python 解释器里执行下面命令，我这样的 locale 设置是不会有问题的，你们也可以试试，你们的机器上这个 locale 很可能不一样。

<img width="214" alt="locale" src="https://user-images.githubusercontent.com/24796/69913018-606d7b80-146d-11ea-8b6a-25b8b74ae7b8.png">

**Comment by iceberg-yuan** [comment]
李老师，根据google上的解决方案，就没问题了。

**Comment by iceberg-yuan** [comment]
![捕获](https://user-images.githubusercontent.com/57003256/69926969-69079580-14f1-11ea-9316-9b7c6541efeb.PNG)

**Comment by neolee** [comment]
@iceberg-yuan  所以很奇怪啊，都什么年代了，操作系统还在用 936 这么古老的 code page…我对 Windows 也不够熟悉，不知道怎么改这个，有空去研究下。

**Comment by ZhaiGuangkai** [comment]
![微信图片_20191202170347](https://user-images.githubusercontent.com/54047618/69946020-bd2c6d00-1525-11ea-8d81-0c74cab84fa0.png)
![微信图片_20191202171103](https://user-images.githubusercontent.com/54047618/69946561-cff37180-1526-11ea-9afa-50970439173d.png)
![微信图片_20191202171107](https://user-images.githubusercontent.com/54047618/69946566-d1249e80-1526-11ea-8d0b-b5a9258fc650.png)
这是我运行的结果

**Comment by neolee** [comment]
@xiaoerhai @ZhaiGuangkai 似乎有些 Windows 的版本不支持我写的月日“压缩”格式符 `%-m` 和 `%-d`，Windows 支持的一些格式符在下面链接里有：

https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/strftime-wcsftime-strftime-l-wcsftime-l

所以 Windows 下压缩格式年月就只好先别用了。我会更新下教材，说明这一点。
