### ISSUE TITLE
与教材中 code 的执行结果不一样

### ISSUE THREAD

**Issue by xiaoerhai** [neolee/pilot#628]
执行以下code：
```python
t = datetime.now().astimezone()
print(t.tzinfo)
```
学习用书中的结果：
```python
?D1¨²¡À¨º¡Á?¨º¡À??
```
教材中显示的结果：
```python
CST
```

**Comment by neolee** [comment]
看代码无问题，你的运行环境是？Python 版本是？

**Comment by xiaoerhai** [comment]
我的运行环境：Windows 10 操作系统  PowerShell 环境
我的Python版本：3.7.5

**Comment by neolee** [comment]
你在哪里执行出现乱码？可以来个截图不？

**Comment by xiaoerhai** [comment]
就是在jupyter lab 上打开学习用书并运行以上代码的时候。没法截图。拖图或者上传每次都提示：
```Something went really wrong, and we can't process that file. try again.```

**Comment by neolee** [comment]
没法截图可是个大问题，试试怎么能解决它吧。

现在你碰到的这种问题，不截图基本说不清，你没法完整的表述现场是啥样子。

**Comment by xiaoerhai** [comment]
![Uploading 20DACBE4-2EA7-432A-BFCD-15A10C7C8213.png…]()

**Comment by xiaoerhai** [comment]
![E562DCD8-4E70-494B-A009-197751185BA4](https://user-images.githubusercontent.com/48662601/69916421-c968e980-1495-11ea-8e39-aeb525f85a25.png)

**Comment by ZhaiGuangkai** [comment]
![微信图片_20191202171700](https://user-images.githubusercontent.com/54047618/69946947-940cdc00-1527-11ea-822a-cc939d1b9e37.png)

**Comment by neolee** [comment]
看 @ZhaiGuangkai 的截图，似乎 @xiaoerhai 的浏览器的语言设置显示中文出了问题……

**Comment by xiaoerhai** [comment]
![3E7FE67C-33A1-4391-B192-14FC2EA93AF0](https://user-images.githubusercontent.com/48662601/70021624-45654d80-15cc-11ea-9b13-380da366a669.png)

**Comment by neolee** [comment]
@xiaoerhai 你的系统没配置好缺省字符编码，所以某些程序里显示中文有问题，这是经典的 Windows 问题了，去搜搜就有答案了。

**Comment by xiaoerhai** [comment]
好，谢谢李骏老师解答。
