### ISSUE TITLE
老师帮我看看，同步用书2哪里出问题了

### ISSUE THREAD

**Issue by 18p2p** [neolee/pilot#631]
![S EQUZ5EGPUQQBW @$Q03G5](https://user-images.githubusercontent.com/48624321/69899861-3c476700-13a7-11ea-9ebf-b922a856252b.png)

**Comment by 18p2p** [comment]
![94_%}%KABAYMJI`%I`J4 1M](https://user-images.githubusercontent.com/48624321/69899918-d9a29b00-13a7-11ea-847b-5059d2b4c5e3.png)

**Comment by neolee** [comment]
你的本地和 origin repo 都是 "pilot-student"，而加入的 upstream 是 "pilot"，这是两个各自独立的 repo，自然无法 merge。

注意看 `git remote -v` 的返回信息就能发现问题。

**Comment by 18p2p** [comment]
我也发现这个问题了

**Comment by 18p2p** [comment]
我把老师的教科书FORK过去了，现在应该把学习用书FORK到我的GIT网站上去，可是老是不成功

**Comment by 18p2p** [comment]
![TEMBFU3 8KN$4521V_APN4B](https://user-images.githubusercontent.com/48624321/69900070-46b73000-13aa-11ea-9ed5-4e984b0f7df1.png)
是不是要把GIT网上自己账号原来的用书删了才能FORK？

**Comment by neolee** [comment]
不需要删了重来啊，主要是你的 `git remote add ...` 那一句加错了呀。

先 `git remote rm upstream`，然后把正确的 pilot-student 地址加进去 `git remote add https://github.com/neolee/pilot-student.git`，然后继续按照官方指南做。

不过这个过程却是有些麻烦，要是不纠结，直接把本地的 pilot-student 找个地方备份好，然后删了自己账号下的 pilot-student，重新 fork & clone 也是完全可以的。

**Comment by Winsi0n** [comment]
已经成功同步了学生用户书，借这个issue问问老师：

第一次merge的时候提示我没有什么可以merge，然后我 git statues 了一下看到有几个之前的修改没有commit，然后我就把这几个文件commit并push了，然后再merge就可以。

请问老师第一次merge失败是因为没有commit吗？还是有其他原因

**Comment by neolee** [comment]
merge 是两个 branch 之间的操作，而 branch 就是一串 commit 的线索。

如果你本地的修改没有 commit，那么 git 会认为没有可以 merge 的 commit。

你第一次 merge 可能是这种情况。

**Comment by 18p2p** [comment]
![QFPISL@O1~U5R}~8VBB4J1S](https://user-images.githubusercontent.com/48624321/69901095-0363be00-13b8-11ea-8655-9bbae402e11a.png)
不知是chechout 出问题？还是git merge upstream/master 出问题？

**Comment by neolee** [comment]
还是你本地有未提交的更改，merge 之前需要把你本地的所有修改都 commit 掉才行。

**Comment by 18p2p** [comment]
老师直接用 git commit 吗？另外想问一下老师视频课里命令行不清晰（只有480P），是否成为付费用户能看到清晰视频？

**Comment by neolee** [comment]
你只要有 B 站账号，登录就可以看高清的吧。

**Comment by zhipingyang120** [comment]
是的，只要在B站上注册一下，就可以看高清视频。

**Comment by 18p2p** [comment]
我真够傻的，一直看480P的版本，估计还有不少TX像我这样,只要注册就能看1080P了

**Comment by 18p2p** [comment]
老师问题解决了，谢谢！

**Comment by neolee** [comment]
Nice! Keep going...
