### ISSUE TITLE
jupyterlab 运行错误

### ISSUE THREAD

**Issue by xiaoliuzi1124** [neolee/pilot#632]
老师之前可以运行，现在不知道为什么出现这个问题

![微信图片_20191130201749](https://user-images.githubusercontent.com/57397833/69900460-83852600-13ae-11ea-90e9-cd56dab75d25.png)

**Comment by Winsi0n** [comment]
正确的写法：jupyter lab
您缺了个空格

**Comment by Winsi0n** [comment]
事实上您应该看看给您报错的红字，上面有提到“检查名称的拼写”

**Comment by xiaoliuzi1124** [comment]
> 实际上您应该看看给您报错的红字，上面有提到“检查名称的拼写”

空格打出来也是同样的问题

**Comment by neolee** [comment]
@xiaoliuzi1124 首先你要理解命令的含义，`jupyterlab` 失败因为并不存在这样的可执行的程序或者命令，应该执行的是 `jupyter lab`，后面这个的含义是：执行 `jupyter` 这个程序，并用 `lab` 作为参数。

后面你如果执行 `jupyter lab` 也失败了，和前一个问题的本质是完全不同的，命令对了，但是无法执行，报的错是什么？如果也是说无法识别 `jupyter`，那就是你的 JupyterLab 没有装好。

**Comment by xiaoliuzi1124** [comment]
> @xiaoliuzi1124 首先你要理解命令的含义，jupyterlab 失败因为并不存在这样的可执行的程序或者命令，应该执行的是 jupyter lab，后面这个的含义是：执行 jupyter 这个程序，并用 lab 作为参数。
> 后面你如果执行 jupyter lab 也失败了，和前一个问题的本质是完全不同的，命令对了，但是无法执行，报的错是什么？如果也是说无法识别 jupyter，那就是你的 JupyterLab 没有装好。

是的，我重新配置了环境可以了，之前有一些文件被我不小心删掉了。谢谢老师！
