### ISSUE TITLE
无法将 scoop.sp1 项识别为 cmdlet、函数、脚本文件或可运行程序的名称

### ISSUE THREAD

**Issue by LONGMONG** [neolee/pilot#633]
在执行scoop update时出现报错。
& : 无法将“C:\Users\shenx\scoop\shims\..\apps\scoop\current\bin\scoop.ps1”项识别为 cmdlet、函数
、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 C:\Users\shenx\scoop\shims\scoop.ps1:3 字符: 71
+ ... on.expectingInput) { $input | & $path  @args } else { & $path  @args  ...
+                                                             ~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\shenx\...t\bin\scoop.ps1:String) [], Com
   mandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by LONGMONG** [comment]
尝试几次，解决方法都不成功。
1.检查scoop.ps1的路径，没有错误。
2.删除scoop文件夹，再全部重新安装。
3.把powershell设置为管理员。

**Comment by neolee** [comment]
Scoop 没装好，按照 Wiki 里“重装 Scoop”一节重新安装。

**Comment by neolee** [comment]
另外你的 PowerShell 版本是 >= 5 的对吧？

**Comment by LONGMONG** [comment]
![image](https://user-images.githubusercontent.com/51018702/69911029-36f22700-1450-11ea-9cb4-eab950056c33.png)
★确认$PSVersionTable.PSVersion.Major的返回值为5.
★用scoop一直安装到git完成，每一步都用checkup检查，都没问题。但只是执行update就出现报错。

**Comment by LONGMONG** [comment]
再后来，使用其他的scoop命令就一直会报错。
我的电脑系统是win10家庭版，会不会有影响。
![image](https://user-images.githubusercontent.com/51018702/69911168-820d3980-1452-11ea-988d-ecd0271fc106.png)

**Comment by neolee** [comment]
看上去在前面一个截图出错的时候 Scoop 的安装目录出现了一些问题，后面就不 work 了。

建议先按照 Wiki 里的说明删掉 Scoop： 
```powershell
cd
del .\scoop -Force
```

然后打开一个 PowerShell (Admin) 命令行窗口（管理员权限），重新安装一次 Scoop。

**Comment by LONGMONG** [comment]
系统也重新恢复出厂设置了。用管理员权限重新全部安装一遍，仍然报错。但第一次update时用些变化，会failed报错。接下来的报错就又与以前一样了。
![image](https://user-images.githubusercontent.com/51018702/69931540-a58fbd00-1502-11ea-8c4a-56872851429f.png)

**Comment by neolee** [comment]
截图里第一次执行 `scoop update` 是典型的网络错误，按理换网络或者挂代理重试就可以。

后面的错误就比较少见了，目前还不知道为啥。

**Comment by LONGMONG** [comment]
问题已解决。环境配置已完成。
1. 杀毒软件干扰。卸载macfee(电脑厂家自带），关闭windows defender。
2. 环境变量未生效。在安装scoop、python、vs code时，会在环境变量中添加path,每一步安装完成后建议重启系统，让path生效。
<img width="587" alt="50fc82c9ea65eca046eee36864fb52e" src="https://user-images.githubusercontent.com/51018702/69946714-252f8300-1527-11ea-843f-5d4f5cc92973.png">
<img width="429" alt="1575277539" src="https://user-images.githubusercontent.com/51018702/69946727-2d87be00-1527-11ea-8fce-24b2131220c9.png">

**Comment by neolee** [comment]
Nice! Keep going!

**Comment by 553195418** [comment]
useful
