### ISSUE TITLE
 报错：'str' object is not callable

### ISSUE THREAD

**Issue by zilin19** [neolee/pilot#636]
***总显示不可调用，如下：
请老师指教***
![Annotation 2019-12-01 114454](https://user-images.githubusercontent.com/51396634/69909096-714bcc00-1430-11ea-9f49-f08f8aec6c80.png)

**Comment by neolee** [comment]
感觉是你前面用 `input` 做过变量名，仔细检查你前面有否执行过 `input = '...'` 这样的代码。
