### ISSUE TITLE
重新 clone 无法包含第二部分课程

### ISSUE THREAD

**Issue by Yolandasoar** [neolee/pilot#637]
老师，我把原来的fork删了之后，重新clone包含第二部分课程的全部内容，clone过来的还是只有第一部分的课程，是什么原因呢？

**Comment by Jared-Gong** [comment]
你要去```repo```里删除```fork```的学习内容呢，在```setting```下面有个```Delete this repository```然后再```fork&clone```

**Comment by neolee** [comment]
把你 clone 的地址发来看看。

**Comment by Yolandasoar** [comment]
> 老师，我把原来的fork删了之后，重新clone包含第二部分课程的全部内容，clone过来的还是只有第一部分的课程，是什么原因呢？


> 把你 clone 的地址发来看看。

https://github.com/Yolandasoar/pilot  老师这是我的地址

**Comment by Yolandasoar** [comment]
> 你要去`repo`里删除`fork`的学习内容呢，在`setting`下面有个`Delete this repository`然后再`fork&clone`

同学，我就是已经删除了还是不行所以才苦恼。。。

**Comment by iceberg-yuan** [comment]
你可以把原来的code目录下的pilot-student里的内容删除，再fork就好了。

**Comment by Yolandasoar** [comment]
> 把你 clone 的地址发来看看。

老师我看完课后练习视频再回去操作就好了，已经解决了。。。难道删除repo也有滞后反应 😅
