### ISSUE TITLE
老师支线课程初步设计和责任分离中的错误？

### ISSUE THREAD

**Issue by lidewen-yue** [neolee/pilot#638]
<img width="1104" alt="image" src="https://user-images.githubusercontent.com/56989072/69911469-df0aee80-1456-11ea-84a4-4c8a67006145.png">
在红框中的这段代码中feeling并没有被赋值啊，即使是父类中也没有，那为什么这段代码还是可以运行呢？

下面我也写了同样的代码却运行不了，说feeling没有赋值，问题出在哪里呢？
![image](https://user-images.githubusercontent.com/56989072/69911519-999af100-1457-11ea-9a3a-81aac94bc950.png)
![image](https://user-images.githubusercontent.com/56989072/69911521-9dc70e80-1457-11ea-8073-81ed4c7570b3.png)

**Comment by neolee** [comment]
哈哈哈，所以你继续看下去啊，我也出错了，然后改了……

**Comment by lidewen-yue** [comment]
其实我是想问为什么在之前的代码确可以运行呢？我还反复看了很多次，在前面feeling也没有赋值啊。

**Comment by lidewen-yue** [comment]
我是一边看视频一边自己打的，我自己打的时候是if 'good' in s:的，然后看到老师写的feeling的时候还想着运行会出错呢，但是居然也可以运行，然后我也改成feeling确不行，我其实是想问一下之前的代码feeling没有赋值，可是为什么还是可以运行呢？

**Comment by neolee** [comment]
我是从 notebook 里直接 copy & paste 过来的，上下文不一样，所以有几个变量名错了，一般正常自己一点点写是不会有这种问题的。所以也算实际演示了下 copy & paste 没有自己写好 😀

**Comment by lidewen-yue** [comment]
明白了，谢谢老师。
