### ISSUE TITLE
运行时提示 TypeError: 'fib' object is not iterable

### ISSUE THREAD

**Issue by iceberg-yuan** [neolee/pilot#639]
from itertools import islice
f = fib()
for n in islice(f, 0, 10):
    print(n)

运行时出错，错误提示：
TypeError                                 Traceback (most recent call last)
<ipython-input-24-415df7d883c6> in <module>
      1 from itertools import islice
      2 f = fib()
----> 3 for n in islice(f, 0, 10):
      4     print(n)

TypeError: 'fib' object is not iterable

**Comment by iceberg-yuan** [comment]
查阅itertools的官方文档里确实没有fib

**Comment by iceberg-yuan** [comment]
不过这么一改就好了：
def fib():
    prev, curr = 0, 1
    while True:
        # 这个 yield 是一切魔法的核心，下面解释
        yield curr
        prev, curr = curr, prev + curr

from itertools import islice

f = fib()
for n in islice(f, 0, 10):
    print(n)

**Comment by iceberg-yuan** [comment]
这样就对了。
```python
def fib():
    prev, curr = 0, 1
    while True:
        # 这个 yield 是一切魔法的核心，下面解释
        yield curr
        prev, curr = curr, prev + curr

from itertools import islice

f = fib()
for n in islice(f, 0, 10):
    print(n)
```

**Comment by neolee** [comment]
> 查阅itertools的官方文档里确实没有fib

你碰到的那个错误说 `fib` 不是 iterable，所以不能放在 `islice` 的第一个参数位，应该是你没有正确的定义 `fib()` 函数。这和 itertools 里有没有 fib 有啥关系？

然后我也没搞懂，你下面说的“一改就对了”，你改了什么？你最后对了的版本和下面摘引的教材里的代码有啥区别么？

```python
def fib():
    prev, curr = 0, 1
    while True:
        # 这个 yield 是一切魔法的核心，下面解释
        yield curr
        prev, curr = curr, prev + curr

f = fib()
list(islice(f, 0, 10))
```

**Comment by iceberg-yuan** [comment]
李老师，是这样的。我原来是按照学习用书顺序执行的，提示出错。
1.第1步执行的是下面这段代码块：
```python
class fib:
    def __init__(self):
        self.prev = 0
        self.curr = 1

    def __iter__(self):
        return self

    def __next__(self):
        self.prev, self.curr = self.curr, self.prev + self.curr
        return self.prev
```
2.第2步执行的是下面这段代码块：
```python
from itertools import islice

f = fib()
for n in islice(f, 0, 10):
    print(n)
```
3.然后出现了这个错误提示：'fib' object is not iterable。我以为是和islice有什么关系，就去查阅了itertools官方文档。是我理解错了。
4.我把教材下面的这段，放到第2步的代码块里，作为一个代码块执行没出错。就是下面这个代码块：
```python
def fib():
    prev, curr = 0, 1
    while True:
        # 这个 yield 是一切魔法的核心，下面解释
        yield curr
        prev, curr = curr, prev + curr

from itertools import islice

f = fib()
for n in islice(f, 0, 10):
    print(n)
```
5.看了您的解释后，我又到学习用书里按照原来的顺序（即上面的第1步和第2步）执行了一边，结果就不出错了。确实不知道一开始执行的时候怎么了。

**Comment by neolee** [comment]
你列出的信息很清晰。第2步是依赖于第1步的，你之前第2步出错一定是第1步有些问题（没执行，执行的代码有问题，或者执行后又执行了别的代码从而重定义了 `fib`之类的）。

在原教材中对 Fibonacci 有两个不同的实现：第一个是你的第1步里的 `class fib`，这是一个 *iterator* 类；第二个是你的第4步里的 `def fib()`，这是一个函数，是一个 *generator*。这俩虽然都叫 `fib` 但一个是个类，一个是个函数，不过这两种情况下都可以用下面的代码来使用：
```python
f = fib()
print(list(islice(f, 0, 10)))
```

在两个实现里，`f = fib()` 这一句的含义是不一样：
1. 当 `fib` 是个类的时候，这句是创建了 `fib` 类的一个对象实例然后赋值给 `f`；
2. 当 `fib` 是个函数时，这句是调用 `fib()` 函数，该函数返回了一个 *iterable* 对象赋值给 `f`。
无论哪种情况，`f` 都得到了一个  *iterable* 对象。
