### ISSUE TITLE
安装 Scoop 前设置权限遇到的问题

### ISSUE THREAD

**Issue by Zoeqiaqia** [neolee/pilot#64]
PS C:\Users\Administrator> Get-ExecutionPolicy
Restricted
PS C:\Users\Administrator> Set-ExecutionPolicy RemoteSigned-scope CurrentUser
Set-ExecutionPolicy : 找不到接受实际参数“RemoteSigned-scope”的位置形式参数。
所在位置 行:1 字符: 1
+ Set-ExecutionPolicy RemoteSigned-scope CurrentUser
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-ExecutionPolicy]，ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.SetExecutionPolicyCommand

PS C:\Users\Administrator>

**Comment by neolee** [comment]
那行命令应该是 `Set-ExecutionPolicy RemoteSigned -scope CurrentUser`

在 `-scope` 之前有个空格。

**Comment by Zoeqiaqia** [comment]
麻烦帮我看下，谢谢






发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Neo Lee <notifications@github.com&gt;
发送时间: 2019年10月25日 12:05
收件人: neolee/pilot <pilot@noreply.github.com&gt;
抄送: Zoeqiaqia <283039625@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[neolee/pilot] 安装 Scoop 前设置权限遇到的问题 (#64)




Closed #64.

**Comment by neolee** [comment]
建议你访问这个网页来提问： https://github.com/neolee/pilot/issues/64

现在完全不知道你在说什么。

**Comment by Zoeqiaqia** [comment]
我发了图片，你能收到吗





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Neo Lee <notifications@github.com&gt;
发送时间: 2019年10月25日 16:17
收件人: neolee/pilot <pilot@noreply.github.com&gt;
抄送: Zoeqiaqia <283039625@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[neolee/pilot] 安装 Scoop 前设置权限遇到的问题 (#64)




建议你访问这个网页来提问： #64
 
现在完全不知道你在说什么。
