### ISSUE TITLE
Python 中 return 和 print 有什么区别？

### ISSUE THREAD

**Issue by lidewen-yue** [neolee/pilot#640]
什么情况下该用return？
什么情况下该用print?

**Comment by iceberg-yuan** [comment]
return 专门用于函数的返回
print用于屏幕输出

**Comment by neolee** [comment]
@lidewen-yue 请参考 #451

**Comment by RayOng666** [comment]
试卷做完了，答案只有你自己知道，这是return.
做完了，然后还在课上大喊：选B!选B！，然后所有人都知道了，这是print
我理解差不多这个效果区别吧 ^^

**Comment by neolee** [comment]
@RayOng666 这个说法挺有意思的。更技术地说，`return` 是函数和它的调用方之间的单向交互，而 `print()` 这个函数则是在命令行界面输出一些信息，所以类似于：return 是做完卷子交回给老师，而 print() 是额外地把内容又去某个大黑板写了一遍。
