### ISSUE TITLE
打印出的结果为什么多了一个 None？

### ISSUE THREAD

**Issue by lidewen-yue** [neolee/pilot#641]
![image](https://user-images.githubusercontent.com/56989072/69913649-8b5bcd80-1475-11ea-91b9-f84bbe8fb487.png)

<img width="1140" alt="image" src="https://user-images.githubusercontent.com/56989072/69913662-a595ab80-1475-11ea-9d51-36d562809353.png">
第二个图片里的none是怎么出现的呢？

**Comment by neolee** [comment]
传图失败。

**Comment by neolee** [comment]
你的 `greeting` 类的 `think()` 方法里，没有如父类接口定义那样返回一个字符串，而是直接调用 `print()` 来打印出一个字符串，这样 `greeting` 类对象的 `think()` 方法就没有返回值，相当于返回了一个 `None`；再看 `run()` 方法的最后一句：

```python
self.say(self.think(self.a))
```
对 `greeting` 类的对象 `g` 来说，这个 `self.think()` 返回是个 `None`，这一句就变成了 `self.say(None)`，看 `say()` 方法定义就知道，这就会导致 `print()` 一个 `None` 出来。

**Comment by neolee** [comment]
顺便说一句，这个问题是“父类子类统一接口重要性”的一个绝佳例子。

父类定义的一些重要的=方法，其输入输出是严格一致的，比如 `_think(self, s)` 这个方法，输入的 `s` 是用户输入的内容，而返回值是 bot 的回答内容，输入输出都是字符串。这个接口在任何子类里都不可以改变，否则会直接导致调用了这个方法的地方出问题，比如 `run()` 里面。

**Comment by lidewen-yue** [comment]
明白了，只要把def think(self,s):后的print修改为return就好了，自己对于代码中的逻辑认识也更深刻了。
我这里看完视频后自己凭逻辑写出来的，有很多东西就加上了自己的理解，运行中也发现了很多意想不到的问题和错误，看完老师的讲解再去看回视频后，自己的体会有深刻了许多，视频前前后后看了5遍了，现在才感觉把老师讲的内容‘吸收消化’了。
