### ISSUE TITLE
Mac 系统 pip3 install jupyterlab 安装报错

### ISSUE THREAD

**Issue by Darry2019** [neolee/pilot#643]
李老师，安装pip3 install jupyter lab 显示报错
根据您的指导重新输入显示如下：
promote:~ DR$ python -V
Python 2.7.16
promote:~ DR$ pip -V
-bash: pip: command not found

我记得执行python3 -v命令是显示的python是3.7.5版本的，还请帮忙解答一下，谢谢！

**Comment by neolee** [comment]
指南里说了，Mac 里有时候 `python` 这个命令会指向老的 Python 2，这种情况下你需要使用 `python3` 和 `pip3` 命令。

```shell
python3 -m pip install -U pip
pip3 install jupyterlab
```

注意，以后你要执行 Python 解释器也需要使用 `python3` 命令。

**Comment by Darry2019** [comment]
> 指南里说了，Mac 里有时候 `python` 这个命令会指向老的 Python 2，这种情况下你需要使用 `python3` 和 `pip3` 命令。
> 
> ```shell
> python3 -m pip install -U pip
> pip3 install jupyterlab
> ```
> 
> 注意，以后你要执行 Python 解释器也需要使用 `python3` 命令。

好的老师，更改后重新运行了一次依旧显示read time out ，无法进行安装。  
我今天采用的vpn代理/宽带/手机热点 等三种方式尝试进行安装都显示read time out 。 想请教一下老师还有其他什么好的办法吗？

**Comment by neolee** [comment]
网络代理应该有用，但是对命令行需要专门配置一下，你可以咨询你的服务商。
