### ISSUE TITLE
学生用书无法运行部分代码（代码行旁边出现星号）

### ISSUE THREAD

**Issue by xiaoswain** [neolee/pilot#644]
近期打开jupyter lab 使用学生用书联系，输入代码后，无法运行。
代码旁出现星号。
准确说，打开学习用书，只有第一段能一次运行，之后都是出现旁边星号
![捕获1](https://user-images.githubusercontent.com/57038028/69921235-1c10c880-14cb-11ea-818a-8ade9999706f.JPG)

而部分简单代码能运行。

**Comment by Jared-Gong** [comment]
重启一个```kernel```试试

**Comment by neolee** [comment]
出现星号说明 kernel 还在运行代码，没有给出结果，偶尔会出这种问题的话，像上面同学说的重启 kernel 就好了，要是频繁出现，可能是 Python 或者 Jupyter Lab 系统有些问题。

另外你的截图里目前正选中的哪一个 cell，应该是 Markdown cell 才对，怎么变成 Code cell 了，那个运行肯定是会出错的。

**Comment by xiaoswain** [comment]
老师，我尝试了重启kernel，问题没有根本解决，python系统经常显示忙。
我是应该重装一遍系统？
我在考虑是否需要买一个新电脑，我这个电脑2013年左右买的，是不是硬件老旧了？
以下是我的配置情况，谢谢！
![2](https://user-images.githubusercontent.com/57038028/70094959-8f970f00-165e-11ea-9ff4-f31c13498da7.jpg)

**Comment by neolee** [comment]
如果反复出现该问题，那就是系统或者 Python 环境有些问题，重装可能是个办法。
