### ISSUE TITLE
scoop list 中 git 的版本和 git --version 中显示不一样

### ISSUE THREAD

**Issue by wulemon78** [neolee/pilot#645]
scoop list下“git 2.23.0.windows.1”
 git --version 下“git version 2.15.1.windows.2”
这两个为什么不一样
我在练习git是用restore命令报错，是不是和版本有关

**Comment by neolee** [comment]
说明你的系统里有不止一个 git，而版本老的那个在系统 PATH 里更靠前。

第二个问题的答案是：对的，git restore 是 2.23 之后才加入的命令，其实你用早一点的版本也没问题，有另外一些命令，作用完全一样，注意看 `git status` 返回的信息。

**Comment by wulemon78** [comment]
如何改写系统PATH,或者统一我系统里的git

**Comment by neolee** [comment]
Wiki 里有 blueeyezhy 同学整理的一些经验可以参考，搜索引擎也是好东西。
