### ISSUE TITLE
Win 10 MySQL 运行错误

### ISSUE THREAD

**Issue by RayOng666** [neolee/pilot#646]
按照x5-mysql-setup说明中安装mysql后，后台和服务已经启动mysql服务。
但是继续执行mysql -uroot 命令时，提示2003错误，无法连接数据库。
百度和谷歌搜索结果里，没有发现解决教程。
还请李老师帮忙看一下
错误和电脑细节如下
系统服务里一直显示的是‘启动‘而不是‘正在运行’状态

![1](https://user-images.githubusercontent.com/57169377/69925321-78cfab80-14ea-11ea-939e-66c1e7137655.png)

![2](https://user-images.githubusercontent.com/57169377/69925323-7a00d880-14ea-11ea-8f19-55dc35afbe2e.png)

![3](https://user-images.githubusercontent.com/57169377/69925324-7a996f00-14ea-11ea-8822-92d134a853ae.png)

**Comment by RayOng666** [comment]
好像解决了，
我在my.ini第一行加了 mysql -uroot
再net start mysql就提示启动成功

**Comment by neolee** [comment]
你可以把你的 my.ini 内容贴出来看看吗？

**Comment by RayOng666** [comment]
教程有一句是可以自己创建，我就把原内容删除了（好像有两行设置）
只复制保留了教程显示的代码部分。
现在就是第一行加了[mysql]，已经正常启动，并实现后面fifa19的导入。

![1](https://user-images.githubusercontent.com/57169377/69933723-ad535f80-150a-11ea-9c40-7c56a95a5ca2.png)

三台电脑安装过程中同时遇到几个小问题，搜索后解决。
1.就是要用管理员权限运行power shell，我就安装服务失败，其实是权限不够.
2. my.ini 要改成ansi编码格式
3.Win+R无法启动services，如果是纯小白，可能不知道方法，直接去控制面板->管理工具->服务，手动管理

**Comment by neolee** [comment]
几个问题：
1. 按理说 `my.ini` 里大部分内容都不是必须的，不知道为啥缺了个空的 [mysql] section 差别这么大…
2. 这几个服务的安装都是要 Admin 权限的命令行的，指南里有说，大概不够醒目，我加个强调。
3. `my.ini` 的编码格式这个也加个强调。
4. 找不到  Services 独立的 app，应该是比较老的 Windows，也加个说明好了。

多谢你的反馈。

**Comment by RayOng666** [comment]
关于services，本地三台不同win10，安装mysql后同样的错误提示, services前几周正常使用过，我不确定什么原因引起的错误。
不过可以用services.msc 和 控制面板手动两个方法启动。

**Comment by bing90740** [comment]
参考@fengxh2015的方式成功了，谢谢
