### ISSUE TITLE
iwr : 基础连接已经关闭: 发送时发生错误。

### ISSUE THREAD

**Issue by RearDrive** [neolee/pilot#648]
由于平常工作忙，近期年底换机频繁，已经安装过两三回环境了，但是这次在笔记本电脑上安装，遇到了这个问题，看了以前issues也没有。

输入 Get-ExecutionPolicy ↩︎ ， 系统返回 RemoteSigned 这个是OK的， 但是进行下一步 
iwr -useb get.scoop.sh | iex  就不行了。 我都已经挂上了sockscap，虽然在公司里按理是可以通畅链接的。
附件截图了。

<img width="480" alt="微信截图_20191202112817" src="https://user-images.githubusercontent.com/25167605/69928553-fd282b80-14f6-11ea-955c-0f954f7a3b18.png">

**Comment by RearDrive** [comment]
刚又重试一下又可以安装了，原因未知。

**Comment by neolee** [comment]
就是网络的问题。注意很多代理都需要额外配置才能在命令行使用，你可以咨询下你的服务商。
