### ISSUE TITLE
关于 type() 使用的问题

### ISSUE THREAD

**Issue by ZhaiGuangkai** [neolee/pilot#649]
```python
print(type('a'))
print(type(True))
type(False)
type('fdsafsfg')
```

同时运行以上的代码输出以下结果：
```
        <class 'str'>
        <class 'bool'>
[23]    str
```

1. 是不是在使用的过程中 type() 只能输出一次结果？即最后一次运行的结果。
2. 使用 print() 后的输出结果为什么会自动多出 <class '  '>
3. 如果不使用 type() 且 type() 不在最后运行，jupyter lab中运行后输出的结果前就不会有"[ 23]"这个中括号加数字，这个是什么原因呢？
4. type() 和类有什么联系呢？为什么会出现class这个词。

**Comment by ZhaiGuangkai** [comment]
type（）是类中的属性吗？

**Comment by neolee** [comment]
1. 请参考 #310 和 #527 

2. `type()` 返回的是一个 *Type object*，也就是表示一个“对象类型”的对象，这个对象直接用 `print()` 打印的话结果就是 `<class '...'>` 这样的格式，这是 Python 语言的实现。
Jupyter Notebook 中直接输入这个对象的话，会显示这个对象的值，这时候 Jupyter 的实现是只输出类类型的名字（上面结果中引号内的部分）。下面两个截图可以说明，Python 解释器和 Jupyter 的处理差别。

<img width="503" alt="Python Imterpretor" src="https://user-images.githubusercontent.com/24796/69945343-5490c080-1524-11ea-9362-eefa6bc59b83.png">

<img width="461" alt="Jupyter Notebook" src="https://user-images.githubusercontent.com/24796/69945355-578bb100-1524-11ea-8bf1-68f354c6b70f.png">

3. Jupyter Notebook 中凡是用 `print()` `input()` 等函数来与标准 I/O 交互的显示，都不会标记标号；而单独写一个表达式，显示其结果的话，在前面会表上与代码对应的标号，这种情况下，一个 cell 中只有最后一个表达式的结果会显示。

4. Python 里几乎所有东西都是对象，`type()` 会返回输入对象背后的 *class* 对应的一个 *type object*。参见第 2 点。

**Comment by ZhaiGuangkai** [comment]
> 
> 
>     1. 请参考 #310 和 #527
> 
>     2. `type()` 返回的是一个 _Type object_，也就是表示一个“对象类型”的对象，这个对象直接用 `print()` 打印的话结果就是 `<class '...'>` 这样的格式，这是 Python 语言的实现。
>        Jupyter Notebook 中直接输入这个对象的话，会显示这个对象的值，这时候 Jupyter 的实现是只输出类类型的名字（上面结果中引号内的部分）。下面两个截图可以说明，Python 解释器和 Jupyter 的处理差别。
> 
> 
> <img alt="Python Imterpretor" width="503" src="https://user-images.githubusercontent.com/24796/69945343-5490c080-1524-11ea-9362-eefa6bc59b83.png">
> 
> <img alt="Jupyter Notebook" width="461" src="https://user-images.githubusercontent.com/24796/69945355-578bb100-1524-11ea-8bf1-68f354c6b70f.png">
> 
>     1. Jupyter Notebook 中凡是用 `print()` `input()` 等函数来与标准 I/O 交互的显示，都不会标记标号；而单独写一个表达式，显示其结果的话，在前面会表上与代码对应的标号，这种情况下，一个 cell 中只有最后一个表达式的结果会显示。
> 
>     2. Python 里几乎所有东西都是对象，`type()` 会返回输入对象背后的 _class_ 对应的一个 _type object_。参见第 2 点。

收到，明白了
