### ISSUE TITLE
更新学习用书出现了问题

### ISSUE THREAD

**Issue by hailinsu** [neolee/pilot#650]
第一步的Git Bash在哪里,不知道位置在哪里
![image](https://user-images.githubusercontent.com/48571418/69939436-cfed7480-151a-11ea-8a83-629f1919765b.png)

**Comment by neolee** [comment]
打开你的命令行界面就可以了。

**Comment by zhipingyang120** [comment]
建议你看一下问题#651，里面有详细的解答。
https://github.com/neolee/pilot/issues/651

**Comment by hailinsu** [comment]
运行时除了问题
![$Q %G0W QZEKAZ2{T3G ~6L](https://user-images.githubusercontent.com/48571418/69944985-8fdebf80-1523-11ea-95ff-97b1a52f5a8b.png)

**Comment by neolee** [comment]
@hailinsu 你只需要运行 `git ...` 这样的命令，前面的一串目录路径是 PS 提示符的一部分，@zhipingyang120 同学写的时候把提示符也完整的包含在里面了，应该不难理解。

**Comment by hailinsu** [comment]
已经更新好了  不难理解

**Comment by hailinsu** [comment]
这样算是跟新成功了吗
![AMAPQJ U@5}_~T9T8 ((M5C](https://user-images.githubusercontent.com/48571418/69948464-a50b1c80-152a-11ea-84bd-18462550bbc5.png)
为什么我的学习用书没有更新呢
![OPTZKJS_$2Q8M1J6IOY3YIS](https://user-images.githubusercontent.com/48571418/69948550-d4218e00-152a-11ea-99c5-6ff29d61c0b0.png)
我的主页也没有跟新
![C)F`@QSDQ7GVY98OZ}SDZ(X](https://user-images.githubusercontent.com/48571418/69948708-134fdf00-152b-11ea-9306-a112f81e748d.png)

**Comment by neolee** [comment]
@hailinsu 没有，你 merge 没完成，因为你本地有修改未 commit，先 commit 本地所有的修改，然后在做一次 git merge。你看看你的执行 `git merge` 下面的出错信息就知道了呀。

**Comment by hailinsu** [comment]
如何commit本地所有的修改，是在这里吗 
![}NLLMQBWR50M ___$ XBBD9](https://user-images.githubusercontent.com/48571418/69956333-a47a8200-153a-11ea-99e6-e4ad9ced3593.png)
之后的 git merge是在我的学习目录下运行吗

**Comment by hailinsu** [comment]
如何commit本地所有的修改，是在这里吗
}NLLMQBWR50M ___$ XBBD9
之后的 git merge是在我的学习目录下运行吗

**Comment by neolee** [comment]
@hailinsu 先去看看所有的支线课程，尤其是第一和第二讲。

**Comment by hailinsu** [comment]
我观看了支线课程，发现先commit后merge这属于支线课程第二讲里第三部分的基本操作的两类中
第一个是你有了一些东西，你想放到github上去，第二个是仓库中有好动，你想把它拿回来。我这次的commit,之后merge是属于第二种吗？在ConEmu里提交commit吗？

**Comment by neolee** [comment]
你先搞清楚 git 版管理本的基本概念以及 status、commit 等基本操作。

而 merge 是分支之间进行的，分支的概念课程里也有，但如果你前面还没深入搞明白，理解分支就更难一些。

一步步来吧，如果感觉比较难，不妨跳过去，重新 fork & clone 新版学习用书，先继续学编程课程。

**Comment by hailinsu** [comment]
还是先学习编程课程吧，有时间再学习这个。

**Comment by hailinsu** [comment]
谢谢老师，我已经更新了学习用书，虽然是重新fork & clone 新版学习用书。我也会帮助其他人解答这个问题
