### ISSUE TITLE
Can't shim 'python.exe': File doesn't exist

### ISSUE THREAD

**Issue by NathanJJr** [neolee/pilot#652]
因为用不了PIP所以我检查了一边python的环境安装，重装的时候遇到了这种情况
![图片](https://user-images.githubusercontent.com/52474460/69952291-db986580-1531-11ea-9baf-c85bd555c6bb.png)

**Comment by neolee** [comment]
先运行 `scoop checkup`，按照提示操作，然后在尝试重新安装 Python：

```powershell
scoop uninstall python37
scoop install python37@3.7.4
```

**Comment by NathanJJr** [comment]
> 
> 
> 先运行 `scoop checkup`，按照提示操作，然后在尝试重新安装 Python：
> 
> ```powershell
> scoop uninstall python37
> scoop install python37@3.7.4
> ```

可以手动安装innounp 吗，在控制台安装不知道怎么翻墙，安装失败，innounp安装文件已经在浏览器下载好了，安装了用不了，怎样安装到控制台的路径？
![图片](https://user-images.githubusercontent.com/52474460/70016639-d54ecb80-15bb-11ea-95e3-36a1328ae24d.png)

**Comment by NathanJJr** [comment]
> 
> 
> > 先运行 `scoop checkup`，按照提示操作，然后在尝试重新安装 Python：
> > ```powershell
> > scoop uninstall python37
> > scoop install python37@3.7.4
> > ```
> 
> 可以手动安装innounp 吗，在控制台安装不知道怎么翻墙，安装失败，innounp安装文件已经在浏览器下载好了，安装了用不了，怎样安装到控制台的路径？
> ![图片](https://user-images.githubusercontent.com/52474460/70016639-d54ecb80-15bb-11ea-95e3-36a1328ae24d.png)

![图片](https://user-images.githubusercontent.com/52474460/70016822-53ab6d80-15bc-11ea-901d-39a4b5c29c4c.png)

**Comment by neolee** [comment]
命令行下代理不知道怎么配置？那就搞清楚它，这种问题比其他问题简单多了吧。

**Comment by NathanJJr** [comment]
![图片](https://user-images.githubusercontent.com/52474460/70031703-ce897e00-15e6-11ea-8f5f-bb06a826a913.png)
checkup的问题全部解决了，现在还是一样的问题，我尝试过去吧路径修改到安装python的路径但是又用不了scoop

**Comment by neolee** [comment]
试试删掉 Python 重装。

首先在 Windows 删除应用界面里找有没有 Python 相关的，都删除。然后：

```powershell
scoop uninstall python37
scoop install python37@3.7.4
```

**Comment by NathanJJr** [comment]
删完所有应用，问题解决了！
