### ISSUE TITLE
配置学习用书的问题

### ISSUE THREAD

**Issue by whxzhou** [neolee/pilot#653]
![image](https://user-images.githubusercontent.com/48576143/69952828-f6b7a500-1532-11ea-84b2-35910815f463.jpg)
我删了之前的学习用书重新fork了现在的，但是目录显示是空的？我不知道是漏了哪个环节了？谢谢

**Comment by neolee** [comment]
你的 pilot-student 目录没删，所以 `git clone` 那一句就没成功啊，你看看命令返回的信息就知道了呀。

**Comment by whxzhou** [comment]
我不知道该怎么操作

**Comment by neolee** [comment]
先去看看所有的支线课程，尤其是第一和第二讲。

**Comment by whxzhou** [comment]
可以了。
