### ISSUE TITLE
支线课程 git 案例建立文档和视频不符

### ISSUE THREAD

**Issue by dongruixue** [neolee/pilot#656]
Last login: Tue Dec  3 05:48:15 on ttys000
(base) dongruixuedeiMac:~ dongruixue$ cd .Code
-bash: cd: .Code: No such file or directory
(base) dongruixuedeiMac:~ dongruixue$ mkdir code
mkdir: code: File exists
(base) dongruixuedeiMac:~ dongruixue$ cd .code
-bash: cd: .code: No such file or directory
(base) dongruixuedeiMac:~ dongruixue$ cd .\code\
> mkdir learn-git
-bash: cd: .codemkdir: No such file or directory
(base) dongruixuedeiMac:~ dongruixue$ git config --list
credential.helper=osxkeychain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
user.name=dongruixue
user.email=526765414@qq.com
core.editor=code -w
(base) dongruixuedeiMac:~ dongruixue$ code .\.gitconfig
(base) dongruixuedeiMac:~ dongruixue$

**Comment by neolee** [comment]
你需要先补一补命令行的基本知识，仔细看一下支线课程第一讲吧。
