### ISSUE TITLE
 Control+C 组合键停止 Jupyter Lab 服务

### ISSUE THREAD

**Issue by dongruixue** [neolee/pilot#657]
[I 06:28:22.304 LabApp] Saving file at /2-structure-1.ipynb

tpye(42)

[I 06:30:22.336 LabApp] Saving file at /2-structure-1.ipynb
[I 06:36:35.749 LabApp] Adapting to protocol v5.1 for kernel 82e50a79-0dc9-40b1-adae-47abdc974b8d
[I 06:38:35.580 LabApp] Saving file at /2-structure-1.ipynb
[I 06:42:35.613 LabApp] Saving file at /2-structure-1.ipynb
[I 06:44:35.646 LabApp] Saving file at /2-structure-1.ipynb
[I 06:46:35.678 LabApp] Saving file at /2-structure-1.ipynb
[I 06:48:35.713 LabApp] Saving file at /2-structure-1.ipynb
[I 06:50:35.749 LabApp] Saving file at /2-structure-1.ipynb
[I 06:52:35.784 LabApp] Saving file at /2-structure-1.ipynb
[I 06:54:35.817 LabApp] Saving file at /2-structure-1.ipynb
[W 06:54:51.762 LabApp] Notebook 3-structure-2.ipynb is not trusted
[I 06:54:53.640 LabApp] Kernel started: afd93380-dc88-44a6-af20-7359c9567a74
[I 06:54:54.762 LabApp] Adapting to protocol v5.1 for kernel afd93380-dc88-44a6-af20-7359c9567a74
git commit
git push
[I 06:56:52.715 LabApp] Saving file at /3-structure-2.ipynb
^C[I 06:58:03.537 LabApp] 中断
启动notebooks 在本地路径: /Users/dongruixue/pilot-student
3 活跃的服务
本程序运行在: http://localhost:8888/?token=8acecb08574a504853fe245ec043fedc936bf5d002872bae
关闭服务 (y/[n])5s 未响应 重启操作...
^C[I 06:58:16.167 LabApp] 中断
启动notebooks 在本地路径: /Users/dongruixue/pilot-student
3 活跃的服务
本程序运行在: http://localhost:8888/?token=8acecb08574a504853fe245ec043fedc936bf5d002872bae
关闭服务 (y/[n])5s 未响应 重启操作...

**Comment by neolee** [comment]
所以你的问题是啥？你粘贴的这些文本是什么，自己仔细看过吗？
