### ISSUE TITLE
编程环境配置问题  scoop checkup 后 LongPaths support is not enabled.

### ISSUE THREAD

**Issue by annie0629** [neolee/pilot#658]
PS C:\Users\admin> scoop checkup
WARN  LongPaths support is not enabled.
You can enable it with running:
    Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1
WARN  Found 1 potential problem.

PS C:\Users\admin> Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1
Set-ItemProperty : 不允许所请求的注册表访问权。
所在位置 行:1 字符: 1
+ Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem'  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (HKEY_LOCAL_MACH...trol\FileSystem:String)
    [Set-ItemProperty], SecurityException
    + FullyQualifiedErrorId : System.Security.SecurityException,Microsoft.PowerShell.Comma
   nds.SetItemPropertyCommand

PS C:\Users\admin> scoop bucket and versions
scoop bucket: cmd 'and' not supported
Usage: scoop bucket add|list|known|rm [<args>]

PS C:\Users\admin> scoop checkup
WARN  LongPaths support is not enabled.
You can enable it with running:
    Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1
WARN  Found 1 potential problem.

PS C:\Users\admin> scoop install python37@3.7.4
WARN  Given version (3.7.4) does not match manifest ()
WARN  Attempting to generate manifest for 'python37' (3.7.4)
'python37' does not have autoupdate capability
couldn't find manifest for 'python37@3.7.4'

PS C:\Users\admin> scoop list
Installed apps:
  7zip 19.00
  git 2.24.0.windows.2
  innounp 0.49
  wixtoolset 3.11.2

PS C:\Users\admin>

**Comment by neolee** [comment]
两个问题。

第一，`scoop bucket add ...` 这个命令你输错了，仔细看命令给出的提示。我记得我第一次课就反复强调了，和计算机交互就像和好朋友聊天，要搞懂自己和对方说的每一句话，这个做不到的话就很难了。

第二，关于 LongPath 的那句执行失败是因为权限问题，你需要开一个管理员权限的命令行界面（ PowerShell (Admin) ）来执行就可以了。

**Comment by annie0629** [comment]
谢谢老师！
第一个，输错了命令（把add写成了and)，已经解决了。  以后会更小心，争取不再犯这种错误。

第二个问题， 打开ConEmu，在右上角绿色加号旁点向下的小三角标，出现列表，选了{shells::PowerShell(Admin)},再去执行命令，还是找不到路径。复制如下： 
=======复制开始===================================================
Windows PowerShell
版权所有 (C) Microsoft Corporation。保留所有权利。

尝试新的跨平台 PowerShell https://aka.ms/pscore6

PS C:\Users\admin> scoop checkup
WARN  LongPaths support is not enabled.
You can enable it with running:
    Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1
WARN  Found 1 potential problem.
PS C:\Users\admin> Set-ItemProperty 'HKLM:\STSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1
Set-ItemProperty : 找不到路径“HKLM:\STSTEM\CurrentControlSet\Control\FileSystem”，因为该
路径不存在。
所在位置 行:1 字符: 1
+ Set-ItemProperty 'HKLM:\STSTEM\CurrentControlSet\Control\FileSystem'  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (HKLM:\STSTEM\Cu...trol\FileSystem:String) [
   Set-ItemProperty], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.SetItemPropertyCo
   mmand

PS C:\Users\admin>
======复制结束====================================================

**Comment by annie0629** [comment]
李老师，我好像刚才把这个问题解决了，我右击ConEmu,在属性-安全里面设置了权限。
=====================================================
PS C:\Users\admin> scoop checkup
WARN  LongPaths support is not enabled.
You can enable it with running:
    Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1
WARN  Found 1 potential problem.
PS C:\Users\admin> Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1
PS C:\Users\admin> scoop checkup
No problems identified!
==============================================================

**Comment by annie0629** [comment]
李老师，我好像刚才把这个问题解决了，我右击ConEmu,在属性-安全里面设置了权限。
=========================================================
PS C:\Users\admin> scoop checkup
WARN  LongPaths support is not enabled.
You can enable it with running:
    Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1
WARN  Found 1 potential problem.
PS C:\Users\admin> Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1
PS C:\Users\admin> scoop checkup
No problems identified!
========================================================

**Comment by annie0629** [comment]
李老师，我好像刚才把这个问题解决了，我右击ConEmu,在属性-安全里面设置了权限。

**Comment by annie0629** [comment]
执行scoop update的结果：

error: RPC failed; curl 56 OpenSSL SSL_read: No error
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

**Comment by annie0629** [comment]
确认已解决了问题，谢谢李老师！ : )

PS C:\Users\admin> scoop update
Updating Scoop...
Updating 'main' bucket...
Checking repo... ok
The main bucket was added successfully.
Updating 'versions' bucket...
Scoop was updated successfully!
PS C:\Users\admin>

**Comment by yxl-study** [comment]
您好，我也碰到了同样的问题，在您设置权限的那个地方，并不是很明白，来向您取取经，谢谢

**Comment by jinbin697** [comment]
您好，怎么联系，我也遇到同样问题，目前还没解决，请教。
我密信：金斌
