### ISSUE TITLE
MySQL 环境准备

### ISSUE THREAD

**Issue by xiaoerhai** [neolee/pilot#659]
1.  我现在通过官网，下载好了32位的服务程序（电脑是win10 64位的，装的时候还是找有管理员权限的同事帮忙装的）；
2.  看到【MySQL 配置指南】下面，发现可以通过命令行编译器运行代码```scoop install mysql57```来安装64位的。
疑问：
1.  现在是否可以卸载32位的？
2.  通过命令行编译器下载64的是否还需要管理员权限？

**Comment by neolee** [comment]
你说呢？

**Comment by xiaoerhai** [comment]
![4464ADC2-5B14-4ED5-B8E6-31CD07129B56](https://user-images.githubusercontent.com/48662601/70022020-ac373680-15cd-11ea-9b8b-d04c05f203f6.png)

**Comment by xiaoerhai** [comment]
主要还是我不敢乱操作。
现在我都不清楚32位的服务程序在哪，如何卸载。
通过命令行编译器下载64位，出现了上面的问题，我猜是公司网络的问题。

**Comment by neolee** [comment]
之前装的一定要删掉，两个版本有冲突的机会很高。

你用 Scoop 下载安装失败是网络问题。

**Comment by xiaoerhai** [comment]
好的，感谢李骏老师解答。

**Comment by xiaoerhai** [comment]
![Uploading 9A3F89F6-AB37-4A38-A20D-7B1C371060C2.png…]()
李骏老师，今天终于用公司的网把安装包下载好了。但碰到了一个相关权限的问题，从而导致不能安装。IT同事也帮我尝试安装了好久，但也没得到解决。他告诉我的原因是：我自己必须要有相关管理人员的权限，否则安装不了。它和jupyter lab有啥区别呀？当时我安装jupyter lab是没有权限相关的提示的。

**Comment by neolee** [comment]
看不到截图。

**Comment by xiaoerhai** [comment]
已经在it的帮助下装好了（装好后重启就OK了），但在设置密码的时候出现了以下截图的问题（与指南讲的不一致）：
![E6EFBE21-4C07-41E0-B888-21213262B08F](https://user-images.githubusercontent.com/48662601/70226288-8bb4db00-178b-11ea-8614-e6e76120a52b.png)太南了，这次截图估计也是加载不出来。电脑传不了，我用手机传图前几次是可以的。这两次又不可以了……

**Comment by neolee** [comment]
在 mysql 交互界面里每个命令最后需要又一个分号 `;`。

**Comment by xiaoerhai** [comment]
感谢李骏老师，还是自己粗心大意了，没有一字不漏的去解读以下这句话：
>在 mysql> 提示符之后可以输入任何 MySQL 支持的 SQL 语句（用半角分号 ; 结尾）。

**Comment by iceberg-yuan** [comment]
![mysql](https://user-images.githubusercontent.com/57003256/70391931-3ee43500-1a15-11ea-93e6-7b8993a52f48.PNG)
mysql 已经启动了
![cmd](https://user-images.githubusercontent.com/57003256/70391943-5cb19a00-1a15-11ea-8ae4-f486dbddf13a.PNG)
但是命令行下输入mysql -uroot提示错误

**Comment by neolee** [comment]
看看 #646 有没有帮助。
