### ISSUE TITLE
如果只写 git commit 会报错，如果加上 git commit -m "init commit" 就会正常

### ISSUE THREAD

**Issue by michaelmakun** [neolee/pilot#66]
老师您看看，教程上是不是改一下。
![7](https://user-images.githubusercontent.com/19246142/67488530-8e0f1a00-f6a2-11e9-8df6-e60effde14ae.jpg)

**Comment by neolee** [comment]
`git commit` 会打开设置的编辑器来编辑提交说明信息，在编辑器中写提交信息然后保存退出，`git commit` 就会继续完成。

而 `git commit -m "......"` 用 `-m` 把提交信息直接写在后面，就直接 commit 了。所以本质都一样。

至于你为什么会第一个不行，可以参考下 issue #13 ，看是不是这个问题。
