### ISSUE TITLE
add() missing 1 required positional argument: 'bots' 是什么错误？

### ISSUE THREAD

**Issue by lidewen-yue** [neolee/pilot#660]
![image](https://user-images.githubusercontent.com/56989072/70021361-6ed1a980-15cb-11ea-8a6f-fa48c3862edd.png)
![image](https://user-images.githubusercontent.com/56989072/70021369-74c78a80-15cb-11ea-97b5-b287d346ea4b.png)
这个错误的具体原因是什么？

**Comment by neolee** [comment]
你先问问自己，你这里的 `garfield` 是什么，是个类还是个对象？

**Comment by lidewen-yue** [comment]
![image](https://user-images.githubusercontent.com/56989072/70021717-a0974000-15cc-11ea-8b49-f0f5c31427ef.png)
这是最终章In[9]中的代码

**Comment by neolee** [comment]
你看你自己的代码，然后想想我问的问题，你的代码和教材里的明显不一样啊。

**Comment by lidewen-yue** [comment]
我想试下不定义def prompt(self ,s):直接在run()里面用print来运行，这样应该也不影响程序的逻辑运行

**Comment by lidewen-yue** [comment]
![image](https://user-images.githubusercontent.com/56989072/70022414-24522c00-15cf-11ea-9e56-70b8c42e6acd.png)
![image](https://user-images.githubusercontent.com/56989072/70022425-29af7680-15cf-11ea-98a1-88e5b5388752.png)
![image](https://user-images.githubusercontent.com/56989072/70022432-2e742a80-15cf-11ea-9ff8-8675fe1b1f82.png)
![image](https://user-images.githubusercontent.com/56989072/70022447-346a0b80-15cf-11ea-8bac-458e261f4b7b.png)

**Comment by neolee** [comment]
你的代码里有两个严重的问题。

1. 大小写很随意，我们一般都会用大写开头的词作为类的名字，而类进行实例化出来的对象则用小写的名字，你既没有学习 PEP8 的规范，也没有模仿我们所有例子里的风格，而是都用小写。这直接导致了下一个问题。

2. 你的 `garfield` 是一个类，没有进行实例化，直接调用 `garfield.add()` 方法，这是不对的，`add()` 是一个对象的方法，必须在实例化之后调用。你把你的 `garfield.add()` 那几行和教材中的代码对比，就会看到你缺了实例化的一步。

专注，严谨。

**Comment by lidewen-yue** [comment]
老师好，我会认真检讨我在写程序时的不规范行为，以后绝不再犯，做一个专注、严谨的程序员，但是老师说的第二点我反复和老师写的代码进行了对比，奇怪的是我没有发现差异，我即使将代码改成和老师一模一样可是执行还是出错，


![image](https://user-images.githubusercontent.com/56989072/70046582-4cf31980-1601-11ea-8c39-889c11475b56.png)

![image](https://user-images.githubusercontent.com/56989072/70046599-53819100-1601-11ea-8c79-97f2ad4cfb2f.png)
ps：执行出错的那个是我写的，另外一个是课程的截图

**Comment by neolee** [comment]
你出错的代码是哪一行？对应的教材中的代码在哪里？找到了对应代码再比较一下。

下面是教材中对应你出错代码的部分：
![screen](https://user-images.githubusercontent.com/24796/70047973-271b4400-1604-11ea-8484-238e4f0b816f.jpg)

**Comment by neolee** [comment]
以及，我说你的错误在于没有创建类的对象实例，这句话理解了吗？

**Comment by lidewen-yue** [comment]
我知道错了，都是我自己做事马虎，总是想偷懒少写点，闹了一个笑话。

**Comment by neolee** [comment]
这个不是偷懒的问题哈，你要确认理解好类和对象的关系，以及前面说的大小写习惯问题。
