### ISSUE TITLE
使用git log命令时出现这个问题，请指教

### ISSUE THREAD

**Issue by liufubo9** [neolee/pilot#661]
![使用git log出现这种情况](https://user-images.githubusercontent.com/57818851/70025030-cb869180-15d6-11ea-8916-0cd475ef626d.png)

**Comment by liufubo9** [comment]
最后没有回到PS C:\Users\liufu\Code\learn-git>：

**Comment by neolee** [comment]
按 `q` 键可以退出回到命令行界面。
