### ISSUE TITLE
安装scoop脚本失败 显示无法连接到远程服务器 请问如何解决？

### ISSUE THREAD

**Issue by WOODSBANGZHU** [neolee/pilot#662]
(base) PS>Set-ExecutionPolicy RemoteSigned -scope CurrentUser
(base) PS>iwr -useb get.scoop.sh | iex
iwr : 无法连接到远程服务器
所在位置 行:1 字符: 1
+ iwr -useb get.scoop.sh | iex
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:Htt
   pWebRequest) [Invoke-WebRequest]，WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShe
   ll.Commands.InvokeWebRequestCommand

**Comment by neolee** [comment]
网络问题，已有很多很多类似 issue 了。
