### ISSUE TITLE
Instant Markdown 页面打不开

### ISSUE THREAD

**Issue by here9527** [neolee/pilot#664]
安装完 Instant Markdown，命令行打开 Instant Markdown: Open Broweser 浏览器页面打不开，是网络问题吗？重启过 Visual Studio Code，网络也换了几个，试了好多次都是这样：

![屏幕快照 2019-12-03 下午2 26 00](https://user-images.githubusercontent.com/57101368/70025745-e22de800-15d8-11ea-9e0b-672d50febe39.png)

![屏幕快照 2019-12-03 下午2 15 49](https://user-images.githubusercontent.com/57101368/70025651-9a0ec580-15d8-11ea-89e9-9b87fc33e671.png)

**Comment by neolee** [comment]
看截图，这不是已经打开了吗？里面空着，是因为你的 Markdown 文件里也没写东西呀，写点东西应该就能看到了吧、

**Comment by here9527** [comment]
有写东西还是这样，感觉是打开的网址不对，打开的是localhost  看李老师的视频里面显示的是instant markdown

**Comment by neolee** [comment]
地址就是 `http://localhost:8090/` 这个是没错的，页面标题确实应该是 “Instant Markdown”，你截图那个标题不对。你试试在浏览器刷新下那个页面试试？

**Comment by here9527** [comment]
都试过了，我一直以为是网络问题
![屏幕快照 2019-12-03 下午6 22 59](https://user-images.githubusercontent.com/57101368/70045614-5e3b2680-15ff-11ea-9f78-b8bb00b798ef.png)

**Comment by here9527** [comment]
试过了，我一直以为是网络问题

![屏幕快照 2019-12-03 下午6 22 59](https://user-images.githubusercontent.com/57101368/70045702-7dd24f00-15ff-11ea-8aae-9aaf034b5189.png)

**Comment by neolee** [comment]
这比较奇怪，暂时没找到类似案例。

**Comment by neolee** [comment]
临时解决方案是这样：不适用 Instant Markdown 插件，而是直接用 VSCode 自带的预览功能：

1. 在 VSCode 左边的文件列表里点击你的 Markdown 文件，选择 Open Preview，这会打开预览窗口；
2. 拖动预览窗口的 tab 到 VSCode 窗口的右侧，这样可以把你的 Markdown 源文件和预览窗口并排显示。

具体可以参考 VSCode 的官方指南：

https://code.visualstudio.com/docs/languages/markdown
