### ISSUE TITLE
VSCode 下 from bot import * 出错

### ISSUE THREAD

**Issue by bing90740** [neolee/pilot#665]
from bot import * 代码无法正常运行 from报错
from bot import *

class Garfield:
    
    def __init__(self):
        self.bots = []
        
    def _add(self, bot):
        self.bots.append(bot)
        
    def run(self):
        print("This is a dialog syetem. Let's talk now.")
        print()        
        for bot in self.bots:
            bot.run()

if __name__ == '__main__':
    garfield = Garfield()
    garfield._add(HelloBot())
    garfield._add(GreetingBot())
    garfield._add(FavcolorBot())
    garfield.run()
![from bot import](https://user-images.githubusercontent.com/56208944/70030447-39858580-15e4-11ea-900f-dc4bc6610fa0.JPG)

**Comment by neolee** [comment]
你看到的不是错误，而是 *pylint* 这个工具给出的一些警告性的提示（告诉你 `bot` 模块里有些 `import` 没用上），实际上经常不准确，也可以无视。事实上有些提示我都是关掉的（我使用 *pylint* 的一个最小检查集）。
