### ISSUE TITLE
S1 本地和 GitHub 上的学习用书已经删，为何同步新的学习用书还是失败

### ISSUE THREAD

**Issue by Erika00** [neolee/pilot#667]
李老师 我的问题出在哪里？
![@ RL$P0ULCO`~P %}AE_BD4](https://user-images.githubusercontent.com/52418630/70056025-b715b980-1615-11ea-8eb8-d5fae6befee0.png)
![W4UT3)S9 76HO8B`LMC75B1](https://user-images.githubusercontent.com/52418630/70056036-bed55e00-1615-11ea-9cfb-04e24377e7c9.png)

**Comment by Erika00** [comment]
![@ RL$P0ULCO`~P %}AE_BD4](https://user-images.githubusercontent.com/52418630/70056225-0956da80-1616-11ea-9ba6-81dd083860bf.png)

**Comment by neolee** [comment]
首先你有个加错了的 remote，建议先删掉（注意，要在你的 pilot-student 本地目录里执行）：
```shell
git remote rm upsteam
```

第二个问题，你 `git fetch upstream` 这一步失败了，网络中断，这个要重新试，知道成功。我们一开始就讲学编程首先要和计算机混熟、成为密友，所以你要搞清楚你自己对它说的每句话，也要理解它回应你的每句话，不然很浪费时间。

第三个问题，你 `git checkout master` 这句，git 告诉你你已经在 `master`  分支下了，所以没问题，但是下面有一串文件，前面都有个 D 字母，你是不是吧这个目录的文件都删了？这也是个大问题，你并不需要删掉它们。

**Comment by Erika00** [comment]
好的，谢谢老师
我再来试一遍

**Comment by Erika00** [comment]
![QCJO9H5B903K8BU2Y%)5MM3](https://user-images.githubusercontent.com/52418630/70107228-d85fbf80-1680-11ea-899d-2d316399dad7.png)
李老师 能在jupyter lab 打开同步学习用书就算同步成功了？

**Comment by neolee** [comment]
看上去是好了 😀
