### ISSUE TITLE
Jupyter Lab 代码段前面 出现“*”导致无法运行代码如何解决

### ISSUE THREAD

**Issue by zhangfei002** [neolee/pilot#669]
![image](https://user-images.githubusercontent.com/49616309/70058080-3bb60700-1619-11ea-9573-d63759872ba2.png)
不知道是不是操作有误，出现这个“*”就无法运行了，想知道是什么原因导致的，如何恢复？

**Comment by neolee** [comment]
那不是“出现*导致无法运行”，而是“运行中未完所以显示*”。

参见 #644
