### ISSUE TITLE
Mac 环境安装 Homebrew 后打不开

### ISSUE THREAD

**Issue by vhanmeng** [neolee/pilot#67]
![image](https://user-images.githubusercontent.com/51287605/67488883-260d0380-f6a3-11e9-993d-3e5373bcddff.png)

**Comment by neolee** [comment]
安装 Homebrew 的命令是：

```shell
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
```

当提示 `Press RETURN to continue or any other key to abort` 时一定要按回车键，就会继续安装，任何其他键就退出了（看上去这是你的情况）。

**Comment by vhanmeng** [comment]
确实是我没按回车键的问题。
按回车键后 需要输入管理密码，在下载Homebrew的地方卡住了，一直过不去，网络速度只有4kb，今天我买了一个vpn服务，重新操作了一次，非常顺利。
只是我安装的python的版本不对，版本是python 3.7.3
李老师，这个影响学习吗？    我准备自己现在去goole一下升级办法。

Last login: Fri Oct 25 08:22:18 on ttys000
(base) hanmengdeMacBook-Pro:~ hanmeng$ python3 -V
**Python 3.7.3**
(base) hanmengdeMacBook-Pro:~ hanmeng$ brew list
gdbm		git		pcre2		readline	xz
gettext		openssl@1.1	python		sqlite
(base) hanmengdeMacBook-Pro:~ hanmeng$ code
(base) hanmengdeMacBook-Pro:~ hanmeng$ python3 hello.py
python3: can't open file 'hello.py': [Errno 2] No such file or directory
(base) hanmengdeMacBook-Pro:~ hanmeng$ cd Code
(base) hanmengdeMacBook-Pro:Code hanmeng$ code .
(base) hanmengdeMacBook-Pro:Code hanmeng$ ls
hello.py
(base) hanmengdeMacBook-Pro:Code hanmeng$ pthon3 hello.py
-bash: pthon3: command not found
(base) hanmengdeMacBook-Pro:Code hanmeng$ python hello.py
hello world
(base) hanmengdeMacBook-Pro:Code hanmeng$

**Comment by neolee** [comment]
Python 3.7.3 是可以用于学习的。不过我的担心是，你用 Homebrew 安装的应该是 3.7.4，为什么会是 3.7.3 呢，这里面一定有点问题。请你运行下面几个命令，告诉我结果：

```shell
which python
which python3
which pip
which pip3

python -V
python3 -V
pip -V
pip3 -V

pip list
pip3 list
```

**Comment by vhanmeng** [comment]
应该是我在看笑来老师的《自学是门手艺》时通过方式装的。
运行结果如下：
Last login: Fri Oct 25 10:00:27 on console
(base) hanmengdeMacBook-Pro:~ hanmeng$ which python
/anaconda3/bin/python
(base) hanmengdeMacBook-Pro:~ hanmeng$ which python3
/anaconda3/bin/python3
(base) hanmengdeMacBook-Pro:~ hanmeng$ which pip
/anaconda3/bin/pip
(base) hanmengdeMacBook-Pro:~ hanmeng$ which pip3
/usr/local/bin/pip3
(base) hanmengdeMacBook-Pro:~ hanmeng$ python -V
Python 3.7.3
(base) hanmengdeMacBook-Pro:~ hanmeng$ python -V
Python 3.7.3
(base) hanmengdeMacBook-Pro:~ hanmeng$ python3 -V
Python 3.7.3
(base) hanmengdeMacBook-Pro:~ hanmeng$ pip -V
pip 19.0.3 from /anaconda3/lib/python3.7/site-packages/pip (python 3.7)
(base) hanmengdeMacBook-Pro:~ hanmeng$ pip3 -V
pip 19.2.3 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)
(base) hanmengdeMacBook-Pro:~ hanmeng$ pip list
Package                            Version 
---------------------------------- --------
alabaster                          0.7.12  
anaconda-client                    1.7.2   
anaconda-navigator                 1.9.7   
anaconda-project                   0.8.2   
appnope                            0.1.0   
appscript                          1.0.1   
asn1crypto                         0.24.0  
astroid                            2.2.5   
astropy                            3.1.2   
atomicwrites                       1.3.0   
attrs                              19.1.0  
Babel                              2.6.0   
backcall                           0.1.0   
backports.os                       0.1.1   
backports.shutil-get-terminal-size 1.0.0   
beautifulsoup4                     4.7.1   
bitarray                           0.8.3   
bkcharts                           0.2     
bleach                             3.1.0   
bokeh                              1.0.4   
boto                               2.49.0  
Bottleneck                         1.2.1   
certifi                            2019.3.9
cffi                               1.12.2  
chardet                            3.0.4   
Click                              7.0     
cloudpickle                        0.8.0   
clyent                             1.2.2   
colorama                           0.4.1   
conda                              4.6.14  
conda-build                        3.17.8  
conda-verify                       3.1.1   
contextlib2                        0.5.5   
cryptography                       2.6.1   
cycler                             0.10.0  
Cython                             0.29.6  
cytoolz                            0.9.0.1 
dask                               1.1.4   
decorator                          4.4.0   
defusedxml                         0.5.0   
distributed                        1.26.0  
docutils                           0.14    
entrypoints                        0.3     
et-xmlfile                         1.0.1   
fastcache                          1.0.2   
filelock                           3.0.10  
Flask                              1.0.2   
future                             0.17.1  
gevent                             1.4.0   
glob2                              0.6     
gmpy2                              2.0.8   
greenlet                           0.4.15  
h5py                               2.9.0   
heapdict                           1.0.0   
html5lib                           1.0.1   
idna                               2.8     
imageio                            2.5.0   
imagesize                          1.1.0   
importlib-metadata                 0.0.0   
ipykernel                          5.1.0   
ipython                            7.4.0   
ipython-genutils                   0.2.0   
ipywidgets                         7.4.2   
isort                              4.3.16  
itsdangerous                       1.1.0   
jdcal                              1.4     
jedi                               0.13.3  
Jinja2                             2.10    
jsonschema                         3.0.1   
jupyter                            1.0.0   
jupyter-client                     5.2.4   
jupyter-console                    6.0.0   
jupyter-core                       4.4.0   
jupyterlab                         0.35.4  
jupyterlab-server                  0.2.0   
keyring                            18.0.0  
kiwisolver                         1.0.1   
lazy-object-proxy                  1.3.1   
libarchive-c                       2.8     
lief                               0.9.0   
llvmlite                           0.28.0  
locket                             0.2.0   
lxml                               4.3.2   
MarkupSafe                         1.1.1   
matplotlib                         3.0.3   
mccabe                             0.6.1   
mistune                            0.8.4   
mkl-fft                            1.0.10  
mkl-random                         1.0.2   
more-itertools                     6.0.0   
mpmath                             1.1.0   
msgpack                            0.6.1   
multipledispatch                   0.6.0   
navigator-updater                  0.2.1   
nbconvert                          5.4.1   
nbformat                           4.4.0   
networkx                           2.2     
nltk                               3.4     
nose                               1.3.7   
notebook                           5.7.8   
numba                              0.43.1  
numexpr                            2.6.9   
numpy                              1.16.2  
numpydoc                           0.8.0   
olefile                            0.46    
openpyxl                           2.6.1   
packaging                          19.0    
pandas                             0.24.2  
pandocfilters                      1.4.2   
parso                              0.3.4   
partd                              0.3.10  
path.py                            11.5.0  
pathlib2                           2.3.3   
patsy                              0.5.1   
pep8                               1.7.1   
pexpect                            4.6.0   
pickleshare                        0.7.5   
Pillow                             5.4.1   
pip                                19.0.3  
pkginfo                            1.5.0.1 
pluggy                             0.9.0   
ply                                3.11    
prometheus-client                  0.6.0   
prompt-toolkit                     2.0.9   
psutil                             5.6.1   
ptyprocess                         0.6.0   
py                                 1.8.0   
pycodestyle                        2.5.0   
pycosat                            0.6.3   
pycparser                          2.19    
pycrypto                           2.6.1   
pycurl                             7.43.0.2
pyflakes                           2.1.1   
Pygments                           2.3.1   
pylint                             2.3.1   
pyodbc                             4.0.26  
pyOpenSSL                          19.0.0  
pyparsing                          2.3.1   
pyrsistent                         0.14.11 
PySocks                            1.6.8   
pytest                             4.3.1   
pytest-arraydiff                   0.3     
pytest-astropy                     0.5.0   
pytest-doctestplus                 0.3.0   
pytest-openfiles                   0.3.2   
pytest-remotedata                  0.3.1   
python-dateutil                    2.8.0   
pytz                               2018.9  
PyWavelets                         1.0.2   
PyYAML                             5.1     
pyzmq                              18.0.0  
QtAwesome                          0.5.7   
qtconsole                          4.4.3   
QtPy                               1.7.0   
requests                           2.21.0  
rope                               0.12.0  
ruamel-yaml                        0.15.46 
scikit-image                       0.14.2  
scikit-learn                       0.20.3  
scipy                              1.2.1   
seaborn                            0.9.0   
Send2Trash                         1.5.0   
setuptools                         40.8.0  
simplegeneric                      0.8.1   
singledispatch                     3.4.0.3 
six                                1.12.0  
snowballstemmer                    1.2.1   
sortedcollections                  1.1.2   
sortedcontainers                   2.1.0   
soupsieve                          1.8     
Sphinx                             1.8.5   
sphinxcontrib-websupport           1.1.0   
spyder                             3.3.3   
spyder-kernels                     0.4.2   
SQLAlchemy                         1.3.1   
statsmodels                        0.9.0   
sympy                              1.3     
tables                             3.5.1   
tblib                              1.3.2   
terminado                          0.8.1   
testpath                           0.4.2   
toolz                              0.9.0   
tornado                            6.0.2   
tqdm                               4.31.1  
traitlets                          4.3.2   
unicodecsv                         0.14.1  
urllib3                            1.24.1  
wcwidth                            0.1.7   
webencodings                       0.5.1   
Werkzeug                           0.14.1  
wheel                              0.33.1  
widgetsnbextension                 3.4.2   
wrapt                              1.11.1  
wurlitzer                          1.0.2   
xlrd                               1.2.0   
XlsxWriter                         1.1.5   
xlwings                            0.15.4  
xlwt                               1.3.0   
zict                               0.1.4   
zipp                               0.3.3   
(base) hanmengdeMacBook-Pro:~ hanmeng$ pip3 list
Package    Version
---------- -------
pip        19.2.3 
setuptools 41.4.0 
wheel      0.33.6 
(base) hanmengdeMacBook-Pro:~ hanmeng$

**Comment by neolee** [comment]
你用的是 Anaconda 的安装包，这个包东西比较多，很多我们用不到，而且多了一层管理，所以我没有选择这个方案。但是这个方案对于学习我们的课程是完全没问题的。

你可以直接尝试 `pip install jupyterlab`，如果没有问题，就可以按照学习用书的指南的说明继续准备学习用书了。

**Comment by neolee** [comment]
你用的是 Anaconda 的安装包，这个包东西比较多，很多我们用不到，而且多了一层管理，所以我没有选择这个方案。但是这个方案对于学习我们的课程是完全没问题的。

现在的问题是你用 Anaconda 安装的一套 3.7.3 在 /anaconda3 目录下，用 Homebrew 安装的一套 3.7.4 在 /usr/local 下面。

当系统存在多个同名的程序时，Unix 系统是根据不同目录在 PATH 环境变量里的先后次序决定哪个优先的，从上面你贴的内容看，/anaconda3/bin 是排在 /usr/local/bin 的前面，更加优先的，所以你现在运行 python 和 python3 都跑的是 Anaconda 那一套。

另外，/anaconda3/bin 下面应该没有 pip3 这个文件，所以你如果执行 pip3 会用 /usr/local/bin 下面的 pip3（Homebrew 安装的）。这是个隐患，不过问题也不大。

现在你有几个选择：
1. 继续使用 Anaconda 那一套，对于我们学习完全 OK，你只要记住永远只用 python 和 pip 这俩，不要用 python3 和 pip3 就可以了。你可以直接尝试 `pip install jupyterlab` 并继续准备学习用书等。
2. 在你的命令行配置中（~/.bash_profile 或者 ~/.profile 之类），找到 PATH 环境变量，把 /anaconda3/bin 去掉，这样从现在开始你的 Anaconda 并不会被启用（以后要用把它加回 PATH 就行了），你运行的 python pip 等都是 Homebrew 的（3.7.4）。

这俩方案都可以。
