### ISSUE TITLE
使用 Ctrl Enter 执行代码并没有出现结果，无法判断自己的代码对不对

### ISSUE THREAD

**Issue by hailinsu** [neolee/pilot#672]
这个例子中的False，
![8P{SPFZQ2T{Q Z6739`N`H3](https://user-images.githubusercontent.com/48571418/70093375-34175200-165b-11ea-8fe7-6bcb623aeb36.png)

**Comment by neolee** [comment]
左边的星号表示 kernel 正在执行这个代码，还没给出结果，可这是非常简单的代码，不应该这么久。所以这里是有些问题发生了，你可以点击 notebook 上方的“Restart kernel”的按钮，再重新尝试。

参考 #644

**Comment by hailinsu** [comment]
解决了
