### ISSUE TITLE
关于 arbitrary argument with default 的使用

### ISSUE THREAD

**Issue by johnxie1225** [neolee/pilot#673]
请问老师，是否可以举个例子说明一下，arbitrary argument with default是怎么使用的？在网上搜索不到相关的范例。

**Comment by neolee** [comment]
你是指 arbitrary argument 本身带 default value 的情况吗？这种并不多见，也很少用到，一般的建议是一个函数里最多一个 arbitrary argument，而且不要带缺省值。

硬要用的话，大致是这样的：

```python
def test(a, b, c = '', *lst):
    print(f'c: {c}')
    print(f'length of lst: {len(lst)}')
    pass

test(1, 2)
test(1, 2, 3, 4, 5)
```

**Comment by johnxie1225** [comment]
明白了 谢谢老师



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Neo Lee <notifications@github.com&gt;
发送时间: 2019年12月4日 15:37
收件人: neolee/pilot <pilot@noreply.github.com&gt;
抄送: johnxie1225 <1281991939@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[neolee/pilot] 关于 arbitrary argument with default 的使用 (#673)




你是指 arbitrary argument 本身带 default value 的情况吗？这种并不多见，也很少用到，一般的建议是一个函数里最多一个 arbitrary argument，而且不要带缺省值。
 
硬要用的话，大致是这样的：
 def test(a, b, c = '', *lst):     print(f'c: {c}')     print(f'length of lst: {len(lst)}')     pass test(1, 2) test(1, 2, 3, 4, 5)
