### ISSUE TITLE
关于 Functional Programming 的一些问题

### ISSUE THREAD

**Issue by bodhi-ma** [neolee/pilot#675]
刚才看了老师之前翻译的一篇文章“Why SICP Matters”，里面提到“学习编程重要的是学习思想，而不是某一特定编程语言的语法”，以及里面有个例子说“Google 的 MapReduce 的实现是深深根植函数式编程的思想”。想问老师有没有关于函数式编程书籍推荐，或者是体现文中所说编程思想类的书籍推荐？

**Comment by neolee** [comment]
本课程 S2 的第五和第十三章就是很好的入门读物。可以从这里开始。

**Comment by bodhi-ma** [comment]
> 本课程 S2 的第五和第十三章就是很好的入门读物。可以从这里开始。

好的
