### ISSUE TITLE
如何将 VSCode 应用程序拖到 Applications 目录下

### ISSUE THREAD

**Issue by mage168** [neolee/pilot#677]
我搜索了mac上所有文件夹Applications，将vscode拖过去后，在 Spotlight，输入 code ，显示：command not found；
Applications 目录是哪一个，能不能仔细讲下步骤

**Comment by neolee** [comment]
你是第一次在 Mac 下安装 app 吧，看下图：

<img width="744" alt="Applications" src="https://user-images.githubusercontent.com/24796/70144794-a6c71280-16d9-11ea-874e-25dd6a6e23b2.png">

**Comment by mage168** [comment]
我已经这么操作了，但是输入 code时还是显示command not found，这是啥情况呀

**Comment by neolee** [comment]
你在哪里输入？

**Comment by mage168** [comment]
感谢老师，编程环境准备好了
