### ISSUE TITLE
用Scoop安装Mysql时出现问题

### ISSUE THREAD

**Issue by AustinJiangg** [neolee/pilot#678]
![image](https://user-images.githubusercontent.com/48593934/70140962-e4736d80-16d0-11ea-8ef8-f6fc0dc74106.png)
完全按照教材配置的编程环境。在管理员模式下运行scoop install mysq157后提示Couldn't find manifest for 'mysq157'.  Google该提示，无果。

**Comment by AustinJiangg** [comment]
我看错了，是mysql57, 不是mysq157

**Comment by Sincere-io** [comment]
我也犯了同样的错误
