### ISSUE TITLE
brew install git python 出错

### ISSUE THREAD

**Issue by bianka727** [neolee/pilot#68]
Error: An exception occurred within a child process:
  DownloadError: Failed to download resource "python--pip"
Download failed: https://files.pythonhosted.org/packages/00/9e/4c83a0950d8bdec0b4ca72afd2f9cea92d08eb7c1a768363f2ea458d08b4/pip-19.2.3.tar.gz

**Comment by bianka727** [comment]
一般都是进度条走不完 停很久 然后报错

**Comment by neolee** [comment]
这个是网络问题，多试几次，或者挂代理试试。

**Comment by neolee** [comment]
@bianka727 类似这种吧
