### ISSUE TITLE
字符串数据这一章的小问题

### ISSUE THREAD

**Issue by Winsi0n** [neolee/pilot#680]
在调用print(t.tzinfo)时，输出是乱码 （如下）

?D1¨²¡À¨º¡Á?¨º¡À??

第一反应是是缺文字库，但是看了下课本的输出结果是“CST”。猜想是不是这里“CST” 不只是我们平常用到的“CST”，请教老师这里是怎么了呢？

**Comment by neolee** [comment]
如果系统设置的区域是中文，这里会显示“中国标准时间”，你这个是显示中文有问题，结果出来乱码了。

**Comment by Winsi0n** [comment]
原来如此，谢谢老师

**Comment by Winsi0n** [comment]
老师同一章中

print(t.strftime("%Y年%m月%d日 %H时%M分"))

会有 UnicodeEncodeError 错误：

---------------------------------------------------------------------------
UnicodeEncodeError                        Traceback (most recent call last)
<ipython-input-44-09fbcc1e91f1> in <module>
----> 1 print(t.strftime("%Y年%m月%d日 %H时%M分"))

UnicodeEncodeError: 'locale' codec can't encode character '\u5e74' in position 2: encoding error

需要怎么解决呢？

**Comment by neolee** [comment]
参考 #627

**Comment by Winsi0n** [comment]
看来segmentfault是个好东西，谢谢老师
