### ISSUE TITLE
termcolor 在 ConEmu 成功上色而 VS Code 中不成功

### ISSUE THREAD

**Issue by 18p2p** [neolee/pilot#681]
![}E`85MS5$JBJ232YFVG~` Q](https://user-images.githubusercontent.com/48624321/70145645-8ef08e00-16db-11ea-851e-452893d964a0.png)
![_387LBAQ}PTZE R)}`(965T](https://user-images.githubusercontent.com/48624321/70145653-92841500-16db-11ea-858c-b4ab3eab119c.png)

**Comment by 18p2p** [comment]
老师把我的问题改的很专业，不知为何两者不一致？

**Comment by neolee** [comment]
通常是因为 VS Code 里的命令行环境有问题，你可以检查下 Terminal 配置，一般来说需要设置使用 External terminal，然后选择和你 ConEmu 里使用的一样的 PowerShell 程序。
