### ISSUE TITLE
安装软件包管理工具 Scoop时，提示“基础连接已经关闭: 发送时发生错误”

### ISSUE THREAD

**Issue by nangongxiaoxiong** [neolee/pilot#684]
安装软件包管理工具 Scoop时，提示“基础连接已经关闭: 发送时发生错误”
iwr : 基础连接已经关闭: 发送时发生错误。
所在位置 行:1 字符: 1
+ iwr -useb get.scoop.sh | iex
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest]，WebExceptio
    n
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestComma

**Comment by yehangchuan11** [comment]
后面这个问题怎么解决的？我也遇到了。
