### ISSUE TITLE
缩进错误处理 expected an indented block

### ISSUE THREAD

**Issue by zhangfei002** [neolee/pilot#687]
![image](https://user-images.githubusercontent.com/49616309/70150884-b9dfdf80-16e5-11ea-9db9-e929efe57a10.png)
![image](https://user-images.githubusercontent.com/49616309/70150953-d714ae00-16e5-11ea-86c2-6db2b21355a0.png)
按照课件输入代码，运行时提示缩进错误，但是缩进处理以后依然错误

**Comment by neolee** [comment]
你的 `def __init__(self, n):` 那一句是定义函数，下面要接缩进的函数定义。

你前面第一阶段函数的章节咋学的？
