### ISSUE TITLE
Markdown 演练时预览没有变化

### ISSUE THREAD

**Issue by banshibao** [neolee/pilot#688]
![md1](https://user-images.githubusercontent.com/24274761/70161412-fc5de800-16f6-11ea-8c40-1c7f06ce76df.JPG)
![md2](https://user-images.githubusercontent.com/24274761/70161416-fcf67e80-16f6-11ea-92bd-8322f1056834.JPG)
![md](https://user-images.githubusercontent.com/24274761/70161417-fd8f1500-16f6-11ea-8151-1aaa5d4c8799.JPG)
markdowm演练时，在写了：
#标题
##标题
在http://localhost:8090/显示：#Titil ##小标题 ###小小标题，没有变化，而且都不换行。

**Comment by neolee** [comment]
你的那几行之间要有空行。
