### ISSUE TITLE
为什么父类和子类都有定义 self.q 这个函数但是运行不了呢

### ISSUE THREAD

**Issue by tinalll12** [neolee/pilot#691]
![mmexport1575476089949](https://user-images.githubusercontent.com/57087700/70196868-fbec3e00-1744-11ea-8f30-9c36a86db2e4.jpg)
![mmexport1575476092711](https://user-images.githubusercontent.com/57087700/70196896-14f4ef00-1745-11ea-8213-ba30dcfab475.jpg)

**Comment by neolee** [comment]
那个方法叫 `__init__`，前后各两个下划线，不是一个，我讲课时多次强调过的。

另外，你改写了 `_think`，这是很好的尝试，我也能猜到你想达成的目标，但目前你用的方法是不行的，再想想。

**Comment by tinalll12** [comment]
![mmexport1575523442983](https://user-images.githubusercontent.com/57087700/70206534-d66e2d00-1762-11ea-8b5a-2fcfd0b616ef.jpg)
谢谢Mr.Neo,头个问题已解决，后面的也自己摸索出来了，编程真好玩。
