### ISSUE TITLE
git 提交时出现的问题

### ISSUE THREAD

**Issue by wenwen-shan** [neolee/pilot#692]
1、P2-1章节进行了修改，打算commit提交，但是查询状态时，感觉有些问题，P2-1显示modified已修改，不知道为什么其他的前缀显示deleted，该怎么调整，还是继续采用git commit -a -m的方式提交么？
2、在进行第二部分的clone时，由于误操作，是文件夹多了pilot/assets/文件，可以用什么命令删除呢？

![图片](https://user-images.githubusercontent.com/57054269/70197897-399e9600-1748-11ea-9332-1e9d0a1b8d75.png)
![图片](https://user-images.githubusercontent.com/57054269/70197892-35727880-1748-11ea-8f30-e94e8d470dc1.png)

**Comment by neolee** [comment]
不知道你做了啥，现在是这些问题都不见了。你在此目录下执行 `ls` 看看？

**Comment by wenwen-shan** [comment]
![图片](https://user-images.githubusercontent.com/57054269/70199779-8d5fae00-174d-11ea-9969-683da4173685.png)
目录下还在。

**Comment by wenwen-shan** [comment]
![图片](https://user-images.githubusercontent.com/57054269/70199825-b08a5d80-174d-11ea-9531-da2ff3066b8c.png)
老师，发的图片能看到么？

**Comment by neolee** [comment]
噢，我知道了，你之前把 pilot 整个目录放进你目前这个目录，然后又删掉了。那没问题，你可以 `git add .` 然后 commit 了。

**Comment by wenwen-shan** [comment]
好的，谢谢老师
