### ISSUE TITLE
Jupyter Lab 如何预览 md 文件

### ISSUE THREAD

**Issue by RayOng666** [neolee/pilot#694]
李老师，课程文件里部分是md文件，
这些文件在用jupyter lab打开时只显示全部代码的形式，和网页端不同。
VS code安装插件可以编辑和预览
那为了方便课程的学习，可以在jupyter lab里直接实现md文件的预览吗？
谢谢！

试过网页端安装notedown插件的教程，但是jupyterlab里只有图标的改变，并没有预览效果。

**Comment by neolee** [comment]
你不需要在 Jupyter Lab 里看教材呀，直接 GitHub 里打开就可以。

如果一定要在 Jupyter Lab 里看 Markdown 预览，打开 Markdown 文件，右键在打开的编辑窗里面点击，选打开预览就行了。

**Comment by RayOng666** [comment]
感谢！
原来要在内容部分右键，早之前在文件名和标题上右键找了好多遍。
github不同网络状态连接差别很大，年纪大了，注意力有限，就更偏好简单粗暴直接不分心的，所以本地最适合我这种笨人。
^^
