### ISSUE TITLE
str.index(string) and str.rindex(string) return the same value

### ISSUE THREAD

**Issue by sjtu-st** [neolee/pilot#695]
In the jupyter lab，str.index(string) and str.rindex(string) return the same value. As shown in the following:
![image](https://user-images.githubusercontent.com/51409636/70205868-8aba8400-1760-11ea-84f2-78af614d96be.png)

**Comment by neolee** [comment]
这个结果很正确呀，你的字符串里只有一个 “missed” 子串，从左开始找和从右开始找，结果都是找到同一个子串，那么返回的 index 自然也一样。

**Comment by sjtu-st** [comment]
I got it.
Sorry, I misunderstand the rindex() method.
