### ISSUE TITLE
except ZeroDivisionError as err, 这句话怎么理解

### ISSUE THREAD

**Issue by bigbigblock** [neolee/pilot#697]
```python
def this_fails():
    x = 1/0

try:
    this_fails()
except ZeroDivisionError as err:
    print('Handling run-time error:', err)
    print(type(err))
```

结果
```
Handling run-time error: division by zero
<class 'ZeroDivisionError'>
```

division by zero 是 ZeroDivisionError 的什么属性还是？

**Comment by neolee** [comment]
```python
try:
    
except ZeroDivisionError as err:

```
上面这个结构的意思是：在 `try` 后面的代码块里如果出现了 `ZeroDivisionError` 类型的运行时异常，就运行 `except` 后面的代码块；同时出现的运行时异常相关信息被封装到 `err` 这个变量中，可以在 `except` 后面的代码块里使用。

`division by zero` 就是 `err` 里携带的信息。

p.s. 我修改了你的问题，加入了一些标签，使得代码显示更清楚，最好学会这些方法。

**Comment by ClaudeH1024** [comment]
这段代码想要表达的意思我大概明白了，但是例子最前面的那个
`def this_fails():
    x = 1/0`
是什么意思？ `def` 后面定义的些东西是个函数吗？因为没看到输入参数和return，我有点懵。
