### ISSUE TITLE
S2 克隆后 git push 出现了错误

### ISSUE THREAD

**Issue by kagamiqyah** [neolee/pilot#698]
git commit成功了，但是到了git push时，总是出现这类错误，我去搜索了没有得到答案。卡壳了24小时了，我想还是发上来，看看谁能解答一下。https://tva1.sinaimg.cn/large/006tNbRwly1g9lvfno00gj30uu0gqwi4.jpg

**Comment by neolee** [comment]
基本要点是：在 push 之前要先 fetch 服务器上的最新版本回来，如果两端有不一样的修改，在本地合并和解决冲突，都解决之后再 push。如果还有 fork 的情况，这个过程就会更加复杂。

所以我一直说这个不是硬性要求，从你的问题看，目前来看是有点难度的。另外你截图里运行的命令是哪里来的？我比较建议你参考 zhipingyang120 同学的指南： #651 

或者干脆就重新 fork 和 clone 一份最新的学习用书好了，目前不值得为这个花太多时间。

**Comment by kagamiqyah** [comment]
好的，收到，谢谢你，我再试试

**Comment by kagamiqyah** [comment]
已经完全弄好了，就是按照zhipingyang120的步骤，我之前一看是windows系统就没仔细看，其实mac也是一样按照指导，就弄好了，感谢～
