### ISSUE TITLE
引用模块很神奇，那怎样寻找合适的模块呢？

### ISSUE THREAD

**Issue by nimi369** [neolee/pilot#699]
直接引用前人写好的模块真的感觉好神奇。但是确实感觉很难，怎么找呢？如何比较哪个更合适呢?希望能面向小白讲一个入门的课程。

**Comment by neolee** [comment]
不太理解你的问题，你是指面对具体问题用什么第三方模块好吗？一般就是上网搜，然后看别人用的经验评价，然后自己都试试。
