### ISSUE TITLE
安装 scoop update 提示运行 scoop install git 运行后显示操作超时

### ISSUE THREAD

**Issue by annie0629** [neolee/pilot#7]
配置指南中：安装好Scoop后安装三个软件包，运行其中的
scoop update
系统显示：Scoop uses Git to update itself. Run 'scoop install git' and try again.
于是运行scoop install git，系统自己安装了半个多小时。
最后显示操作超时。

请问该如何处理？

**Comment by neolee** [comment]
这是网络问题，可以等一会儿再试。

既然可以安装成功 scoop（确认没有报错），说明可以访问其服务；后面安装 git 又有问题，说明网络不太稳定（我国网络现状如此，没办法）。
