### ISSUE TITLE
到这一步进行不下去了，请教什么原因

### ISSUE THREAD

**Issue by zhangshu-xiong** [neolee/pilot#70]
<img width="483" alt="批注 2019-10-24 213839" src="https://user-images.githubusercontent.com/53045404/67491682-df6dd800-f6a7-11e9-82d8-210e6856b72f.png">

**Comment by neolee** [comment]
正确的命令是：

```powershell
Set-ExecutionPolicy RemoteSigned -scope CurrentUser
```

仔细对照，你有一个地方没拼对。
