### ISSUE TITLE
在复习第一阶段 Python 篇时出现了一些问题

### ISSUE THREAD

**Issue by hailinsu** [neolee/pilot#701]
根据教材上写的，发现出错了
![F3 D}S)C)` UM79K5`FPZI](https://user-images.githubusercontent.com/48571418/70225081-51e2d500-1789-11ea-912b-cec273080406.png)
还有一个问题就是，在看完第一阶段总结之后发现我上一阶段没有学好，于是花时间先看完概念篇，python篇，做任务，然后看视频之后再重新思考如何做作业，再接着学习第二阶段没有问题吧。

**Comment by Yolandasoar** [comment]
大概率是上面的代码有错误，要往前去一个个排查一下。
