### ISSUE TITLE
git commit后没有打开编辑器 出现下面这个界面

### ISSUE THREAD

**Issue by here9527** [neolee/pilot#704]
![屏幕快照 2019-12-05 下午9 22 26](https://user-images.githubusercontent.com/57101368/70239320-0e4a9400-17a6-11ea-85cb-12c9c2e48010.png)

**Comment by here9527** [comment]
![屏幕快照 2019-12-05 下午9 30 08](https://user-images.githubusercontent.com/57101368/70239554-76997580-17a6-11ea-9532-32e8b6e64e1d.png)

**Comment by here9527** [comment]
![屏幕快照 2019-12-05 下午9 43 40](https://user-images.githubusercontent.com/57101368/70240552-608cb480-17a8-11ea-8141-1f22b5737825.png)
我不太理解意思，就输入r 后出现最上面那个图

**Comment by neolee** [comment]
你配置有误，不是 `code.editor` 而是 `core.editor`。

**Comment by here9527** [comment]
嗯嗯 对对对，后来发现了
