### ISSUE TITLE
请问李老师，讲课的图片，黑底代码并带着序号是怎么制作的？

### ISSUE THREAD

**Issue by wanxb** [neolee/pilot#706]
[课件图片](https://user-images.githubusercontent.com/20410636/70288651-36b9a900-180d-11ea-8ac3-1d233618a7a4.jpg)

**Comment by neolee** [comment]
用 Mac 下的 Keynote 做的，理论上 PowerPoint 也应该可以。几个要点：

1. 从 VS Code 里 copy 代码，是带有颜色和字体属性的带格式文本，可以直接粘贴到 Keynote 里的，然后修改一下字体，适合展示即可；
2. 通常需要设置一下 Keynote 幻灯片的底色，用取色工具取一下 VS Code 的编辑窗口底色；
3. 其他就是在 Keynote 里划线、加文字等等，哪些数字标号是 Unicode 字符，在 Mac 下可以方便的选择和加入。

**Comment by wanxb** [comment]
好的，感谢李老师

**Comment by spring-ap** [comment]
我曾经深度学习过keynote制作动画，原来keynote还可以用在这里！学习了！我还以为使用截图软件编辑的呢。
