### ISSUE TITLE
老师，提示网址无效，这个该怎么解决？

### ISSUE THREAD

**Issue by wangkai-china1993** [neolee/pilot#707]
Scoop uses Git to update itself. Run 'scoop install git' and try again.         
Installing 'git' (2.23.0.windows.1) [64bit]                                     
The remote name could not be resolved: 'github-production-release-asset-2e65be.s
3.amazonaws.com'                                                                
URL https://github.com/git-for-windows/git/releases/download/v2.23.0.windows.1/P
ortableGit-2.23.0-64-bit.7z.exe#/dl.7z is not valid

**Comment by neolee** [comment]
网络问题。

**Comment by wangkai-china1993** [comment]
需要翻墙吗？老师，我不懂
