### ISSUE TITLE
两个问题：安装 toc 插件失败与 instantmarkdown.openbrowser 无法发现

### ISSUE THREAD

**Issue by dongjin936** [neolee/pilot#708]
李老师，昨天和今天集中跟着视频练习过程，其它环节都顺利。就出现这两个问题。如下图，谢谢李老师。

**Comment by dongjin936** [comment]
![Uploading 屏幕截图(5).png…]()

**Comment by dongjin936** [comment]
![截图20191206110500](https://user-images.githubusercontent.com/56923938/70292686-cc5b3580-1819-11ea-83e9-f596b1f226c4.png)

**Comment by dongjin936** [comment]
![屏幕截图(5)](https://user-images.githubusercontent.com/56923938/70292703-d67d3400-1819-11ea-932e-dfe1db942fb8.png)

**Comment by neolee** [comment]
第一个问题，返回的信息讲的很清楚，你需要先安装 nodejs，方法是：`scoop install nodejs`。

第二个问题，系统也说得很清楚，左侧列表 Instant Markdown 一项写着 “Reload Required”，你需要点一下这个按钮。

别怕，努力深入理解计算机对你说了啥……

**Comment by dongjin936** [comment]
谢谢李老师！第二个问题按照您的提示解决。第一个安好nodejs之后，接着安装toc，出现一个斜线一直摆动，PS程序就停在这里了。

**Comment by dongjin936** [comment]
![截图20191206110500](https://user-images.githubusercontent.com/56923938/70301393-346b4500-1835-11ea-88d5-8e6b559ad55b.png)

**Comment by dongjin936** [comment]
![屏幕截图(6)](https://user-images.githubusercontent.com/56923938/70301413-464ce800-1835-11ea-95fb-94732b17092b.png)

**Comment by dongjin936** [comment]
结果又一个ERROR出现

**Comment by dongjin936** [comment]
![屏幕截图(7)](https://user-images.githubusercontent.com/56923938/70301509-7bf1d100-1835-11ea-840e-0d398fbc0c16.png)

**Comment by dongjin936** [comment]
是不是再根据提示，安装那个npm？？

**Comment by neolee** [comment]
不是，安装好 nodejs 自然就有 npm。这里是说某个 dependency 安装失败，你可以打开它说的那个 log 文件看看是啥错误。这里有时候会碰到很麻烦的问题，涉及到 Windows 的一些系统文件的。

**Comment by dongjin936** [comment]
![屏幕截图(8)](https://user-images.githubusercontent.com/56923938/70384422-1dedf680-19b9-11ea-8c74-ab9aee7cc994.png)
李老师，按照路径找到这个文件，打开是这样的，看不懂呢。

**Comment by dongjin936** [comment]
只看到npm dependencies安装失败.

**Comment by neolee** [comment]
里面有说，下载安装 typescript 失败，原因是网络问题。

**Comment by dongjin936** [comment]
谢谢李老师！那我先解决这个问题。
