### ISSUE TITLE
无法安装 homebrew

### ISSUE THREAD

**Issue by jonasumtaoo** [neolee/pilot#71]
下载速度只有几k，用了vpn全局模式，仍然只有几k。下载了大约二十分钟后报错。内容如下：

error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
Failed during: git fetch origin master:refs/remotes/origin/master --tags --force

请问怎样解决？

**Comment by jonasumtaoo** [comment]
不是啊，是百兆的宽带，看视频很流畅。

**Comment by neolee** [comment]
看视频流畅（很可能提供视频的服务在国内），但是访问 Homebrew 的服务慢（Homebrew 的服务在国外），这很正常，因为互联网遍布全世界，有的服务你访问很快，有的很慢，都属于网络问题。

目前你可以多试几次，我国的网络有时候是时灵时不灵的；或者换别的网络试试，或者使用代理。

**Comment by jonasumtaoo** [comment]
李老师好，下面是我的尝试，还是没解决。

描述：
1. 因为国外服务器网速太慢，试了几个vpn都无法提速。
2.于是网上教程，可以换成国内中国科技大学的安装源。下载install文件，并修改安装源。
3.但在安装过程到下面这一步的时候，报错。重试了，每次到7.8%就报错了。

==> Downloading https://homebrew.bintray.com/bottles-portable-ruby/portable-ruby--2.6.3.mavericks.bottle.tar.gz
#####                                                                      7.8%
curl: (56) LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54
Error: Checksum mismatch.
Expected: ab81211a2052ccaa6d050741c433b728d0641523d8742eef23a5b450811e5104
  Actual: c2c34cd94b68f9fa226d880b66a4a806d44d9b649966cfc36adb8e6bcdd6ba29
 Archive: /Users/taojuncai/Library/Caches/Homebrew/portable-ruby--2.6.3.mavericks.bottle.tar.gz
To retry an incomplete download, remove the file above.
Error: Failed to install vendor Ruby.
Failed during: /usr/local/bin/brew update --force

网上找了很久，都没有这个错误的解决方案。请问老师是什么原因？怎样解决？

**Comment by neolee** [comment]
这个还是网络问题，下载失败了。

**Comment by jonasumtaoo** [comment]
晕死，我单独下这个文件非常快的。但一用terminal下载就是不行。
