### ISSUE TITLE
Scoop 显示已安装但无法运行

### ISSUE THREAD

**Issue by xiaot3** [neolee/pilot#710]
PS C:\Users\adminA> iwr -useb get.scoop.sh | iex
Initializing...
Scoop is already installed. Run 'scoop update' to get the latest version.
PS C:\Users\adminA> scoop update
scoop : 无法将“scoop”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检
查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ scoop update
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (scoop:String) [], ParentContain
   sErrorRecordException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by neolee** [comment]
已经有无数同样的 issue 了，Scoop 没装好，需要重装，参考 Wiki 里“重装 Scoop”一节。
