### ISSUE TITLE
S2 学习用书 code 已经有内容不需要自己填写了

### ISSUE THREAD

**Issue by imagelan** [neolee/pilot#711]
老师，
不知道为什么我的S2 的用书重新clone后，所以的code都是写好的。不需要自己填写。

![image](https://user-images.githubusercontent.com/48951128/70297396-7a7fc480-17b3-11ea-828b-e16867084de0.png)

**Comment by neolee** [comment]
那肯定是你 clone 错了，直接吧教材拿回去了吧？
