### ISSUE TITLE
p1-b 中命令行运行 pip install termcolor 没有反应

### ISSUE THREAD

**Issue by maomaomizi** [neolee/pilot#712]
![屏幕快照 2019-12-06 下午1 44 04](https://user-images.githubusercontent.com/57162859/70299002-93798b80-182e-11ea-91e3-9ac85e336080.png)
![屏幕快照 2019-12-06 下午1 44 17](https://user-images.githubusercontent.com/57162859/70299003-93798b80-182e-11ea-8e92-400aa6013844.png)

**Comment by neolee** [comment]
命令行一直在告诉你，不存在 pip 这个命令，所以那些包都没装成功，那运行 Python 程序自然就不会对了。

所以为啥你的系统里没有 pip 这个命令呢？你的 Python 怎么装的？运行下面的命令看看：

```shell
which python
which python3
which pip
which pip3
```

**Comment by maomaomizi** [comment]
![屏幕快照 2019-12-06 下午5 50 31](https://user-images.githubusercontent.com/57162859/70313643-faa83780-1850-11ea-88ea-247e82c5b405.png)
多谢老师指点，我又回到了环境配置那篇文章看了一下，想起来了当时装pip install jupyterlab 显示找不到目标 所以装的是pip3 install jupyterlab  所有我把final中的代码 pip换成了pip3 现在装成功了。
