### ISSUE TITLE
 p2-b-fsm 中示例代码好像有个小 bug

### ISSUE THREAD

**Issue by hermes0911** [neolee/pilot#713]
![QQ截图20191206144553](https://user-images.githubusercontent.com/28388579/70302121-346c4480-1837-11ea-9e92-921a5ef5e3ae.png)
这一段代码如果 `trigger='return'`, 在后面测试运行 `order1.return()` 的时候会报错 SyntaxError: invalid syntax，好像是占用到了关键字了吧。

**Comment by neolee** [comment]
是的，正好我没有跑这个 state 的测试代码，没发现这个问题。你的观察很细致，多谢指出！

**Comment by neolee** [comment]
已经修复。
