### ISSUE TITLE
regex101 里的结果和学习用书的结果不一致

### ISSUE THREAD

**Issue by xiaoerhai** [neolee/pilot#715]
![6F7B0D2E-F962-4DD3-880D-625FC1DD1D07](https://user-images.githubusercontent.com/48662601/70318609-668f9d80-185b-11ea-9aff-41448f0109fd.png)
一开始是一样的，但我多试了几次就不一样了，怎么也回不到刚开始的时候了……fox 和 dog 这俩就没有在识别结果里了。

**Comment by neolee** [comment]
这个应该去问 regex101 啊。
