### ISSUE TITLE
为什么在 Jupyter Lab 运行很好但是 VScode 运行时 import 是 invalid syntax

### ISSUE THREAD

**Issue by tinalll12** [neolee/pilot#716]
![mmexport1575630899393](https://user-images.githubusercontent.com/57087700/70319352-0c8fd780-185d-11ea-81a0-16fee1688e47.jpg)
如图，自己尝试解决快一个半小时，包括保存在根目录下面运行VScode，查了百度，实在找不出原因。求解答，谢谢。。。

**Comment by neolee** [comment]
这个截图里显示出来的问题还真不少：文件名没有 .py 后缀（不是一定要有，但是没有可能带来难以预期的怪事），源代码乱放，环境不是按照课程指南配置的……编程是一个相当精细的工作，每一个细节都可能带来隐患，你们目前学的东西还很简单，就已经乱成这样，以后咋办啊？

至于为啥运行出错，要看完整的代码，可能的话把你的源代码文件作为附件发上来给我试试吧。

**Comment by tinalll12** [comment]
/Users/luotian/Desktop/屏幕快照 2019-12-06 下午11.02.07.png


关于学习环境，我又从头看了一遍课程，发现自己漏了好多，谢谢老师指出来，我做了些改进，不过，这次没说import 是invalid syntax,   说的是”是 invalid syntax。

import random

class Bot:
    
    def __init__(self):
        self.q = ""
        
    def think(self, s):
        return s
    
    def run(self):
        print(self.q)
        self.a = input()
        print(self.think(self.a))

class GreetingBot(Bot):
    
    def __init__(self):
        self.q = "How are you feeling today?"
        
    def think(self, s):
        feeling = ["good","fantastic","amazing","great"]
        if random.choice(feeling) in self.a.lower():
            return"I'm fine,too."
        else:
            return"Sorry to hear that."
        
class favcolorBot(Bot):
    
    def __init__(self):
        self.q = "what's your favorite color?"
        
    def think(self, s):
        favcolor = ["red","orange","yellow","green","blue","indigo","purple"]
        return f"You like {s}? That's a great color.My favorate colour is {random.choice(favcolor)}."
            
class richBot(Bot):    
    def __init__(self):
        self.q = "Will I be very rich, and how much can I earn for a month in the next month?"
        
    def think(self, s):
        money = ["30000","40000","25000","36000"]
        return f"{s},and you can make {random.choice(money)} every month next year."



g = GreetingBot()
f= favcolorBot()
r = richBot()

g.run()  
f.run()
r.run()

**Comment by tinalll12** [comment]
关于学习环境，我又从头看了一遍课程，发现自己漏了好多，谢谢老师指出来，我做了些改进，不过，这次没说import 是invalid syntax, 说的是”是 invalid syntax，代码如下：


import random

class Bot:
    
    def __init__(self):
        self.q = ""
        
    def think(self, s):
        return s
    
    def run(self):
        print(self.q)
        self.a = input()
        print(self.think(self.a))

class GreetingBot(Bot):
    
    def __init__(self):
        self.q = "How are you feeling today?"
        
    def think(self, s):
        feeling = ["good","fantastic","amazing","great"]
        if random.choice(feeling) in self.a.lower():
            return"I'm fine,too."
        else:
            return"Sorry to hear that."
        
class favcolorBot(Bot):
    
    def __init__(self):
        self.q = "what's your favorite color?"
        
    def think(self, s):
        favcolor = ["red","orange","yellow","green","blue","indigo","purple"]
        return f"You like {s}? That's a great color.My favorate colour is {random.choice(favcolor)}."
            
class richBot(Bot):    
    def __init__(self):
        self.q = "Will I be very rich, and how much can I earn for a month in the next month?"
        
    def think(self, s):
        money = ["30000","40000","25000","36000"]
        return f"{s},and you can make {random.choice(money)} every month next year."



g = GreetingBot()
f= favcolorBot()
r = richBot()

g.run()  
f.run()
r.run()

**Comment by tinalll12** [comment]
![mmexport1575645237377](https://user-images.githubusercontent.com/57087700/70368970-00535b00-18ed-11ea-8a51-3e8529ac247a.jpg)

**Comment by neolee** [comment]
我试了试你的代码，好像没啥问题，我猜你应该在 VSCode 的 Terminal 里运行的是 `python3 bot.py`，因为有些 Mac 环境里 `python` 指向的是老的 Python 2。

另外，你的后两个 Bot 类命名还是不对，应该是 `FavColorBot` 和 `RichBot`，类名每个词首字母都大写。

最后，我改了下你前一个回复，加上了代码块标签，这样显示代码比较容易看，你以后注意照这个写。

**Comment by tinalll12** [comment]
啊，果然。。。我用Python3运行，就是正确的了。超感谢。。。。
