### ISSUE TITLE
iex : 使用“1”个参数调用“DownloadString”时发生异常:“操作超时”

### ISSUE THREAD

**Issue by Liujiale02** [neolee/pilot#72]
老师这应该怎么解决?

iex : 使用“1”个参数调用“DownloadString”时发生异常:“操作超时”
所在位置 行:1 字符: 26
+ iwr -useb get.scoop.sh | iex
+                          ~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-Expression], MethodInv
   ocationException
    + FullyQualifiedErrorId : WebException,Microsoft.PowerShell.Commands.Invok
   eExpressionCommand

**Comment by neolee** [comment]
应该是网络问题，稍后重试几次；或者换网络、挂代理试试。
