### ISSUE TITLE
为什么我 import 的 termcolor 模块不能正常工作？

### ISSUE THREAD

**Issue by wennianxing** [neolee/pilot#722]
以下是加了termcolor模块后的HelloBot的运行结果

PS C:\Users\Administrator\Code> python bot1
This is LittleSheep dialog system. Let's talk.

?[34mHi, what is your name??[0m
wen
?[34mHello wen?[0m
Through recent upgrade I can do calculation now. Input some arithmetic expression to try:

**Comment by wennianxing** [comment]
把'blue'换成'red'之后结果代码中的34变31了，可否认为是py文件的运行环境不支持显示颜色？
可是我就是在vs里运行的呢



PS C:\Users\Administrator\Code> python bot1
This is LittleSheep dialog system. Let's talk.

?[31mHi, what is your name??[0m
wen
?[31mHello wen?[0m

**Comment by wennianxing** [comment]
哦 还真的是vs的terminal中运行不支持显示颜色 呵呵

**Comment by neolee** [comment]
需要对 VSCode 里的 Terminal 做些配置，使用外部 Terminal，然后选系统里装的 PowerShell，一般就可以了。
