### ISSUE TITLE
“database = 'fifa19'”→“database = 'demo”

### ISSUE THREAD

**Issue by xiaoerhai** [neolee/pilot#727]
具体定位：
# 数据和数据库

### MYSQL 数据库

#我一开始按着学习用书运行时报错了，提示`1044 (42000): Access denied for user 'learn'@'localhost' to database 'fifa19'` 。于是返回去对照了指南，发现指南里创建的数据库叫`demo`，并不是`fifa19`。于是我把`fifa19`改为'demo'，运行后就没有报错了。以上问题，不知道我反馈的对不对。

**Comment by neolee** [comment]
这里是有点迷惑人，我改写了一下。多谢指出~
