### ISSUE TITLE
strftime 运行出错

### ISSUE THREAD

**Issue by RayOng666** [neolee/pilot#728]
李老师，两个strftime函数代码在本地运行出现错误
眼看花了也没发现错误在哪，粘帖你的代码也是一样
请帮忙看下问题在哪里，谢谢！
![111](https://user-images.githubusercontent.com/57169377/70371658-df9cfc80-1910-11ea-8a9b-4d07adc5aea1.png)

**Comment by neolee** [comment]
请参考 #627 

教材已经添加了相关说明，如果你是 clone 回本地看的，请 `git pull` 更新本地的教材。

**Comment by RayOng666** [comment]
按那个谷歌教程在VS code里鼓捣一顿，虽然头几行设置编码区域的代码，逐行执行结果和ZhaiGuangkai的截屏相同，但是输教程代码还是不正常。
另外 我的头一个错误代码是value error，中文换成英文换成 `print('date',t.strftime("%Y-%-m-%-d"))` 也还是value error. 按说时间值应该是对的。

**Comment by neolee** [comment]
你最后的回复我实在看不懂，你不妨自己多读几次，看看想表达什么意思。

气质这里主要就两个问题：1. Windows 不支持 `%-m` 和 `%-d` 这样的格式符，Windows 支持的格式符在我 #627 的回复里有。 2. 需要修改环境 locale 设置，令之支持 Unicode，否则带中文的格式串会出错。

**Comment by RayOng666** [comment]
哈哈，谢谢老师
小白就是这样，提问题往往会有难以准确到位的情况。
大体的原因和思路已经明白了，由于环境细节和个人能力不同，问题情况和解决方法可能不同。毕竟解决问题先要解决拓展知识依赖的情况，很多这种问题在长期的学习和应用过程中会自然理解和解决。我暂时还是挂起这个事情，集中注意力把课程主线了解清楚，积累操作经验。
