### ISSUE TITLE
无法将“iwr”项识别为 cmdlet、函数、脚本文件或可运行程序的名称

### ISSUE THREAD

**Issue by jin20191013** [neolee/pilot#73]
PS C:\Users\hp> iwr -useb get.scoop.sh | iex
无法将“iwr”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼
写，如果包括路径，请确保路径正确，然后重试。
所在位置 行:1 字符: 4
+ iwr <<<<  -useb get.scoop.sh | iex
    + CategoryInfo          : ObjectNotFound: (iwr:String) [], CommandNotFound
   Exception
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by neolee** [comment]
似乎 PowerShell 版本不够，你执行 `$PSVersionTable.PSVersion.Major` 返回是什么？

**Comment by jin20191013** [comment]
返回是 2，谢谢李老师。

**Comment by neolee** [comment]
指南中明确写了这个版本号要大于等于5，否则需要安装一些支持软件，请你严格按照 [配置指南](https://github.com/neolee/pilot/blob/master/x1-setup.md) 操作吧。

**Comment by jin20191013** [comment]
收到，后续会严格执行，谢谢老师。
