### ISSUE TITLE
关于参数的疑问？

### ISSUE THREAD

**Issue by Pony-2019** [neolee/pilot#732]
实验了几个什么可以做参数，发现“值”可以做参数，甚至函数和类都可以做参数，变量不可以做参数， 猜测一下定义过的函数和类是不是也应该有“值“？
![QQ截图20191207200913](https://user-images.githubusercontent.com/48638166/70374536-5d233580-192e-11ea-8851-856b96bb284b.png)

**Comment by neolee** [comment]
变量或者表达式都可以作为参数传给函数，传参时先计算变量或表达式的值，然后把值传进去。

你这个例子里最后出错，是因为变量 f 还未定义，也无法求值，调用函数会失败。

**Comment by Pony-2019** [comment]
谢谢老师
