### ISSUE TITLE
关于变量的 scope 的问题？

### ISSUE THREAD

**Issue by Pony-2019** [neolee/pilot#733]
老师：可不可以把变量的作用范围理解为：变量只在每一个“ ： ”定义的表达式范围起作用。也不知道表达的对不对：）
另请帮忙解释一下下图中运行结果为啥有个“None”
![scope](https://user-images.githubusercontent.com/48638166/70375090-ca39c980-1934-11ea-95d7-ca8f59470965.png)

**Comment by Pony-2019** [comment]
是Hi():这个函数的返回值是“None”吗？

**Comment by neolee** [comment]
是的。
