### ISSUE TITLE
运行结果一样，是不是说两者是等价的？

### ISSUE THREAD

**Issue by Pony-2019** [neolee/pilot#734]
![leap_years2](https://user-images.githubusercontent.com/48638166/70375513-84333480-1939-11ea-8339-a38a9cf53d8d.png)
![leap_years1](https://user-images.githubusercontent.com/48638166/70375514-885f5200-1939-11ea-91ce-74d7a6c386e2.png)
第二个图我是误打误撞的运行处理相同的结果，但是不理解为什么会是这样。麻烦老师解答 ：）

**Comment by neolee** [comment]
碰巧而已，你这个版本是有可能造成死循环的，不信你试试 `leap_years(2050, 2110)`……

**Comment by Pony-2019** [comment]
谢谢。
