### ISSUE TITLE
while 循环出错

### ISSUE THREAD

**Issue by nangongxiaoxiong** [neolee/pilot#737]
count = 0
while count < 5:
    print(count)
    count += 1
    
print('Loop ends.')
李老师，你好，这串代码输入python提示错误，如下图
![TIM图片20191208100331](https://user-images.githubusercontent.com/57780075/70383040-05bead00-19a2-11ea-8c26-0366de675000.png)

**Comment by neolee** [comment]
在 Jupyter Lab 中运行，或者存成文件用 python xx.py 来执行。

建议先学习支线课程一和二。
