### ISSUE TITLE
下载的是“ConEmu Preview, Installer (32-bit, 64-bit)”可以正常学习吗

### ISSUE THREAD

**Issue by johnxie1225** [neolee/pilot#74]
进入 ConEmu 首页，点击 Download 按钮，选择下载 “ConEmu Alpha, Installer (32-bit, 64-bit)” 这个安装器版本；
下载的是“ConEmu Preview, Installer (32-bit, 64-bit)”是否可以？
![image](https://user-images.githubusercontent.com/56942215/67528450-1534b000-f6ec-11e9-87c2-363eb6a73858.png)

**Comment by neolee** [comment]
请问为什么不按照指南做呢？

**Comment by johnxie1225** [comment]
感谢老师的答复。我早上在链接过去的下载页面就只发现以上三个下载项（见截图）。我应该把问题描述清楚的，抱歉。

**Comment by neolee** [comment]
配置之类的指南的意义，在于简化教学过程，理论上讲，很可能有很多办法都能达成目标，但是严格按照指南操作，出现问题的时候就比较容易解决（因为指南的内容是我严格测试过的，我知道每一个步骤的影响和后果是什么），如果偏离指南，也可能没问题，但是出现问题就只能靠你自己去解决。

所以你有两个选择：1. 继续，可能没问题也可能有问题，有问题需要你自己研究和解决；2. 重新开始，严格按照指南一步步操作，出现问题更容易得到别人的帮助。

**Comment by Merezhu** [comment]
进入 ConEmu 首页，点击 Download 按钮，选择下载 “ConEmu Alpha, Installer (32-bit, 64-bit)” 这个安装器版本；

老师，点击指南链接进入ConEmu主页并点击Download之后，只有Preview版本，整个Site没有找到Alpha版本的下载链接。 请问怎么操作呢? 

![1](https://user-images.githubusercontent.com/36255603/67769055-b88c1900-fa8e-11e9-9a83-ea4ad76d7392.png)

**Comment by johnxie1225** [comment]
目前可以正常使用


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: merezhu <notifications@github.com&gt;
发送时间: 2019年10月29日 20:57
收件人: neolee/pilot <pilot@noreply.github.com&gt;
抄送: johnxie1225 <1281991939@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[neolee/pilot] 下载的是“ConEmu Preview, Installer (32-bit, 64-bit)”可以正常学习吗 (#74)




进入 ConEmu 首页，点击 Download 按钮，选择下载 “ConEmu Alpha, Installer (32-bit, 64-bit)” 这个安装器版本；
 
老师，点击指南链接进入ConEmu主页并点击Download之后，只有Preview版本，整个Site没有找到Alpha版本的下载链接。 请问怎么操作呢?
