### ISSUE TITLE
Redis 环境准备的最后一步无法执行

### ISSUE THREAD

**Issue by xiaoerhai** [neolee/pilot#740]
![5705B61A-7CC8-4FEF-BD4E-706F56AE0AEC](https://user-images.githubusercontent.com/48662601/70383406-7799f500-19a8-11ea-8559-1d72377b3894.png)
在 Service 管理程序里，右键选择启动时如上图显示无法启动。

**Comment by neolee** [comment]
错误5 一般是权限问题。你直接运行 redis-server.exe 有什么问题么？

**Comment by xiaoerhai** [comment]
![8941EAC9-F3AF-4FAE-953D-92557B327EEA](https://user-images.githubusercontent.com/48662601/70406873-1abc3e80-1a7d-11ea-9374-eb8cfa3f35f4.png)
 
如上图，输入后没法进行人为操作了，光标一直在行首跳动。用的也是管理员的账号。

**Comment by neolee** [comment]
这样没问题，你另开一个命令行，应该就可以 redis-cli 连上去试了。

暂时可以先这么用着。Windows Service 那个不知道是啥情况。

**Comment by Winsi0n** [comment]
我反馈下老师，我也遇到同样的问题。按老师说的也可以连上，但是就是也是一直错误5
>-<

**Comment by neolee** [comment]
@Winsi0n 由于日志缺乏和系统的过于复杂，Windows 系统处理这类系统问题一直都很费事，我可能在自己机器上还能折腾下，远程诊断就太难了，所以，能有个 workaround 就先用吧……

**Comment by Winsi0n** [comment]
嗯嗯，我就是反馈下下，谢谢老师

**Comment by JoshChunge** [comment]
我也遇到Windows 无法启动 Redis 问题。我在服务列表对比了一下 Mysql, 发现 Mysql 属性中-登录选项为 “本地系统”，而 Redis 的登录选项为 “网络服务”。
于是，我把 Redis 属性中-登录选项也改成了 “本地系统”。最后，启动成功了 :)
