### ISSUE TITLE
Warning: Homebrew's sbin was not found in your PATH

### ISSUE THREAD

**Issue by ZhangKaiHua-CW** [neolee/pilot#741]
李骏老师您好，我刚刚开始学习编程，不知道您还能不能查看到我的问题，如果看到希望起到您的解答。
我的问题是这一串代码，您看一下：
Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so:
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.bash_profile

**Comment by neolee** [comment]
你这是干啥的时候碰到额？问题的上下文是啥？

**Comment by ZhangKaiHua-CW** [comment]
brew doctor后出现的

rosemac:~ xianrou$ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so:
  echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.bash_profile
rosemac:~ xianrou$ 
rosemac:~ xianrou$

**Comment by neolee** [comment]
这个提示不影响现阶段使用，可以继续。

**Comment by ZhangKaiHua-CW** [comment]
👌谢谢李老师，今后在遇到麻烦也能很好的解决是吗？
