### ISSUE TITLE
在学习用书中输入代码，不会自动显示结果

### ISSUE THREAD

**Issue by h140** [neolee/pilot#742]
![屏幕截图(1)](https://user-images.githubusercontent.com/54472184/70385515-4a117380-19c9-11ea-804c-d32e0dc4de9b.png)

**Comment by neolee** [comment]
前面的 # 表示后面的是“注释”，你要把 # 去掉才行。

**Comment by h140** [comment]
#去掉了，
![屏幕截图(5)](https://user-images.githubusercontent.com/54472184/70386054-4680eb00-19cf-11ea-93eb-a8e24fc353e5.png)
平时描写都是去掉的，按回车键后还是没有运行结果，

**Comment by chenmite** [comment]
从开始挨个运行一遍

**Comment by neolee** [comment]
按 Control+Enter 或者 Alt+Enter，没反应？？
