### ISSUE TITLE
VSCode 环境如何实现 list 数据换行显示

### ISSUE THREAD

**Issue by spring-ap** [neolee/pilot#743]
![image](https://user-images.githubusercontent.com/57279823/70385821-cdcc5f80-19cb-11ea-9d8f-e8a9b438f55b.png)
我没有在jupyterlab中编写和运行python代码，而是采用vscode直接编码方式。当运行截图中的代码段时，我得到的结果与jupyterlab结果有差异：list内的每个元素连续打印，没有换行。我使用for循环时，虽然可以换行，但是每个元素的显示还是不完全一致，我想实现和jupyterlab一样的显示方式应该怎么做呢？下图为课本中的jupyterlab的显示截图。
![image](https://user-images.githubusercontent.com/57279823/70386550-84ccd900-19d4-11ea-83f2-ba43500168cc.png)

**Comment by neolee** [comment]
这是 Python 解释器和 Jupyter 前端展现的差异，没法简单地统一。如果你真想做，你可以自己写一个函数，比如叫 `pplist(lst)`（意思是"pretty printed list"），然后用这个函数来实现一个类似 Jupyter 那样的显示——这是个不错的练习呢。

**Comment by spring-ap** [comment]
```python
def pplist(list):
    i=0
    y=len(list)
    for line in list:
        if i==0:
            print("["+"\'"+line+"\'"+",")
        elif i<y-1:
            print("\'"+line+"\'"+",")
        else:
            print("\'"+line+"\'"+"]")
        i+=1
    return None
pplist(keyword.kwlist)
```
我编写了上面的代码实现了该功能，不过这段代码是不是不够精简呢？

**Comment by spring-ap** [comment]
> 这是 Python 解释器和 Jupyter 前端展现的差异，没法简单地统一。如果你真想做，你可以自己写一个函数，比如叫 `pplist(lst)`（意思是"pretty printed list"），然后用这个函数来实现一个类似 Jupyter 那样的显示——这是个不错的练习呢。

**Comment by neolee** [comment]
嗯嗯，不错的，下面是我的版本：

pplist.py
```python
def pplist(lst):
    for index, item in enumerate(lst):
        if index == 0:
            print(f"['{item}',")
        elif index + 1 == len(lst):
            print(f"'{item}']")
        else:
            print(f"'{item}',")

if __name__ == '__main__':
    import keyword
    pplist(keyword.kwlist)
    pplist(['apple', 'orange', 'banana'])
```

**Comment by spring-ap** [comment]
谢谢，老师给出的样例我学到了新的函数enumerate。

**Comment by neolee** [comment]
S2 课程第八和第九章介绍 Python 的主要数据容器时会讲这个 😀
