### ISSUE TITLE
p2-1-function-def.ipynb小节的英文单词释义问题。

### ISSUE THREAD

**Issue by spring-ap** [neolee/pilot#746]
![image](https://user-images.githubusercontent.com/57279823/70390063-55cd5c00-1a02-11ea-9608-4c2dd51bf9d4.png)
上图中标注的英文单词idiotic，我在网上查询的意思好像没有“地道的”意思？
![image](https://user-images.githubusercontent.com/57279823/70390059-45b57c80-1a02-11ea-9712-9a86de084e56.png)

**Comment by neolee** [comment]
噗，我写错了，应该是 *idiomatic*。已经修正，多谢指出~
