### ISSUE TITLE
变长参数带缺省值的定义方法

### ISSUE THREAD

**Issue by spring-ap** [neolee/pilot#747]
![image](https://user-images.githubusercontent.com/57279823/70390293-c5444b00-1a04-11ea-88bd-0ffef4ccbc7b.png)
上图中的例子是不是变长参数及带缺省值的变长参数的组合应用？

**Comment by neolee** [comment]
不是，这两个，一个是变长参数，一个是带变量名（*keyword*）的变长参数，也就是说，`name` 是个 tuple，而 address 是个 dict。

**Comment by spring-ap** [comment]
老师，那带缺省值的变长参数应该如何定义呢？

> 不是，这两个，一个是变长参数，一个是带变量名（_keyword_）的变长参数，也就是说，`name` 是个 tuple，而 address 是个 dict。

老师，那带缺省值的变长参数应该如何定义呢？

**Comment by neolee** [comment]
变长参数天生就带缺省值（空的 `()`），你在变长参数的位置啥也不输入，它就等于空的一个 tuple。
