### ISSUE TITLE
赋值出现错误后却能够显示 type

### ISSUE THREAD

**Issue by PanChuang2019** [neolee/pilot#748]
![微信截图_20191208222211](https://user-images.githubusercontent.com/48653618/70390802-6d5c1300-1a09-11ea-8c68-2e6360c5140c.png)

请问老师，为什么我的赋值已经被提示有问题，但是依然可以显示出type的类型。

**Comment by neolee** [comment]
因为在出错之前有过给 c 的成功赋值吧。

**Comment by PanChuang2019** [comment]
是的，出错之前我是给false加了引号的，对应的就应该是字符串str。后面我想试试，如果没有加引号会是怎样的结果，我就顽皮的将引号去掉了，系统就对于赋值内容报错了，但是我下面试着用type去运行，还是原来的str。老师，这是不是类似于缓存的原理，要刷新处理。

**Comment by neolee** [comment]
这不是缓存，可以这么理解：一个 notebook 背后是一个 kernel，也就是一个 Python 解释器，从你打开 notebook 开始这个解释就就开始运行，你在这个 notebook 里运行的所有代码都会一条一条的送到这个解释器其运行，解释器里有你定义过的所有变量、函数、类等等，也会记录他们的状态。

如果你希望清除这个 notebook 的历史，可以在 Jupyter Lab 里选择 Restart the kernel。
