### ISSUE TITLE
为什么我的命令提示符没有美元符号？

### ISSUE THREAD

**Issue by hermanxie** [neolee/pilot#749]
![001](https://user-images.githubusercontent.com/48776732/70397294-07dd4600-1a4c-11ea-8bcb-8bd081c39183.png)

**Comment by michaelmakun** [comment]
因为你是windows系统，所以没有

**Comment by neolee** [comment]
缺省的 PowerShell 提示符就是你那样，没有 $ 的，不过这个可以自行配置，我的环境下有，因为我配置过。

要是有兴趣我可以 share 我的配置文件。
