### ISSUE TITLE
Git 与 GitHub 入门执行 touch README.md 时出错

### ISSUE THREAD

**Issue by jianqingchen** [neolee/pilot#75]
![image](https://user-images.githubusercontent.com/24488183/67534802-6d76ac80-f702-11e9-9679-dba0406b29e7.png)
[https://github.com/neolee/pilot/blob/master/x3-git-github.ipynb](url)

**Comment by neolee** [comment]
两个方法，第一，用 PowerShell 自己的命令：

```powershell
New-Item -ItemType file README.md
```

第二个方法，用 Scoop 安装软件包 `busybox`，这个包里包含了 `touch` 这个命令：

```powershell
scoop install busybox
```

然后就可以执行 `touch README.md` 了。
