### ISSUE TITLE
代码显示获取学习用书失败了吗？

### ISSUE THREAD

**Issue by ZhangKaiHua-CW** [neolee/pilot#750]
李骏老师您好，以下是我获取学习用书过程中出现的代码？请问要不要紧？怎么操作？

rosemac:Code xianrou$ git clone https://github.com/ZhangKaiHua-CW/pilot-student.git
正克隆到 'pilot-student'...
remote: Enumerating objects: 90, done.
error: RPC 失败。curl 18 transfer closed with outstanding read data remaining
fatal: 远端意外挂断了
fatal: early EOF
fatal: unpack-objects 失败
rosemac:Code xianrou$

**Comment by ZhangKaiHua-CW** [comment]
需不需要再重新操作一次？

**Comment by michaelmakun** [comment]
需要重新操作一次，这样子看起来是网络不好造成的
