### ISSUE TITLE
按步骤在创不出 python Hello.py

### ISSUE THREAD

**Issue by wangkai-china1993** [neolee/pilot#751]
python37 3.7.4 [C:\Users\Administrator\scoop\workspace\python37.json]

**Comment by wangkai-china1993** [comment]
PS C:\Users\Administrator\Code> ls


    Directory: C:\Users\Administrator\Code


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        2019/12/8     10:51                test
-a----        2019/12/9      9:04             20 .test

**Comment by michaelmakun** [comment]
如果是在Code文件夹下，可以试试
touch hello.py 
code hello.py

这两行命令。

打开后，在里面写点东西，比如 print("hello world")
然后，保存

然后在命令行 输入  python hello.py 

顺利的话，可以看到结果

**Comment by wangkai-china1993** [comment]
PS C:\Users\Administrator\Code> scoop list                              
Installed apps:                                                         
                                                                        
  7zip 19.00                                                            
  busybox 3244-g48128b9aa                                               
  curl 7.66.0_2                                                         
  dark 3.11.2                                                           
  git 2.23.0.windows.1                                                  
  innounp 0.49                                                          
  lessmsi 1.6.91                                                        
  python37 3.7.4 [C:\Users\Administrator\scoop\workspace\python37.json] 
请教老师，配置环境算是完成了吗？python37 3.7.4后面的文件位置为什么会出现？

**Comment by neolee** [comment]
建议先学习支线课程第一讲，这个仓库的 Wiki 里有链接。

**Comment by wangkai-china1993** [comment]
好的，谢老师啦。

> 如果是在代码文件夹下，可以尝试
> 触摸hello.py
> 代码hello.py
> 
> 两项行命令。
> 
> ：后，在里面写点东西，例如print（“ hello world”）
> 然后，保存
> 
> 然后在命令行输入python hello.py
> 
> 顺利的话，可以看到结果

**Comment by wangkai-china1993** [comment]
好的，谢老师，谢谢michaelmakun同学。
