### ISSUE TITLE
安装和运行 Jupyter Lab 是在 code 目录下还是在 pilot-student 目录下进行？

### ISSUE THREAD

**Issue by ZhangKaiHua-CW** [neolee/pilot#752]
李骏老师您好，

我刚刚完成获取你的学习用书的最后一个命令“输入 cd pilot-student ↩︎ 进入克隆好的目录中”，接下来的操作是“安装和运行 Jupyter Lab”，这是不是默认接下来的操作是在pilot-student目录下面，而且不是在code下面？

以下是代码：
rosemac:Code xianrou$ cd pilot-student
rosemac:pilot-student xianrou$

**Comment by neolee** [comment]
安装 Jupyter Lab 在哪里运行都可以，装好后执行 `jupyter lab` 需要在你的学习用书目录（pilot-student）下。
