### ISSUE TITLE
p1-3-structure-2,函数公式isinstance

### ISSUE THREAD

**Issue by unseengoal886** [neolee/pilot#754]
isinstance(True,int) #true
isinstance(True,bool) #ture

为什么整数判定 True 也是正确的？

**Comment by neolee** [comment]
参考 #466 

另外，这个例子我上课也讲过，没有听吗？

**Comment by unseengoal886** [comment]
> 参考 #466
> 
> 另外，这个例子我上课也讲过，没有听吗？

刚听完第一堂课，还在补课中。
