### ISSUE TITLE
MySQL 安装好但服务启动不起来

### ISSUE THREAD

**Issue by wanxb** [neolee/pilot#755]
![mysql](https://user-images.githubusercontent.com/57003256/70391931-3ee43500-1a15-11ea-93e6-7b8993a52f48.PNG)
mysql 已经启动了
![cmd](https://user-images.githubusercontent.com/57003256/70391943-5cb19a00-1a15-11ea-8ae4-f486dbddf13a.PNG)
但是命令行下输入mysql -uroot提示错误

_Originally posted by @iceberg-yuan in https://github.com/neolee/pilot/issues/659#issuecomment-562962226_

**Comment by wanxb** [comment]
出现这种情况，自己google没能解决，请李老师或哪位知道的同学帮忙解决下，谢谢

**Comment by neolee** [comment]
看看 #646 有没有帮助。

**Comment by iceberg-yuan** [comment]
ini文件里增加[mysql]后，错误提示变成了：
ERROR 2003 (HY000): Can't connect to MySQL server on 'localhost' (10061)

**Comment by iceberg-yuan** [comment]
又做了几项工作，不知怎么就好了：
1.其实一开始“服务”里面，mysql是有问题的，“启动”，“暂停”，“停止”等按钮是灰色的。改为“禁用”，重启电脑，再启动，几个按钮就变成可用的了。
2.把ini文件，另存，选择ansi类型。
3.再运行mysql -uroot就没问题了。

**Comment by wanxb** [comment]
谢谢，我试一下

**Comment by fengxh2015** [comment]
我也遇到类似问题，试一下：
1. 把my.ini文件增加一行（[mysql]）
2. my.ini编码类型ansi。
3. mysqld --install
4. 如果“服务”-"MySQL" -"启动/暂停/停止”等按钮是灰色的，说明服务有问题。右键->启动类型->改为“禁用”，重启。
5. 重启服务，正常“暂停/停止”不是灰色。
6. mysql -uroot
