### ISSUE TITLE
关闭 Terminal 终端窗口后如何查看之前的操作代码

### ISSUE THREAD

**Issue by ZhangKaiHua-CW** [neolee/pilot#756]
关闭 Terminal 终端窗口后再打开，之前的所有代码都不见了，完全是一个新的界面，请问在这种情况下想要查看之前的操作代码怎么办？

**Comment by neolee** [comment]
请参考我在 #758 里的回复，先优化你的问题，不然没法提供有用的帮助。

另外，善用问题描述，不要把所有问题都写在标题里，详细描述写在问题描述中。

我已经按照我自己的猜测帮你修改了一下问题，如果我的猜测没错的话，你可以用箭头键中的上和下来遍历命令历史。
