### ISSUE TITLE
Tab 键为什么不能补全我想要打的代码？

### ISSUE THREAD

**Issue by ZhangKaiHua-CW** [neolee/pilot#758]
我用的是Mac系统，看了老师的教程里Tab键有补全代码的快捷功能，可是我实践的时候只听到电脑发出“铛”的声音，请问这是什么原因？

**Comment by neolee** [comment]
我看到你一口气发了好几个问题，但是有类似的毛病，就是没头没尾，没上下文，没有相关场景的信息。这种情况下就没法提供什么帮助了。

比如这个问题，你看了哪个教程？在什么程序什么界面可以用 Tab 键补全代码？而你是怎么操作的，在哪里按 Tab 键只有音效？这些如果不说清楚，怎么知道是什么原因呢？

**Comment by ZhangKaiHua-CW** [comment]
我刚刚总结了一下自己在学习第一节课的过程中遇到的这几个悬而未决的问题，因为不是即时记录的问题，没有做好上下文和相关场景的记录，如果今后再遇到同样的问题，一定会留心即时记录优化自己的提问。谢谢老师！
