### ISSUE TITLE
Terminal 下怎样使其默认运行 Homebrew 安装的 python？

### ISSUE THREAD

**Issue by chhyuan** [neolee/pilot#760]
老师，我之前安装过anaconda3，今天卸载了。之前安装python3.7.0b1版本时，把它修改为默认运行版本，今天想用同样的方法让terminal默认运行3.7.4，就不行了。修改配置文件后，显示：-bash: /usr/local/Cellar/python3/3.7.4/bin: No such file or directory

这是python 3.7.0b1的配置文件：
<img width="690" alt="Screen Shot 2019-12-09 at 9 53 41 PM" src="https://user-images.githubusercontent.com/42464384/70441895-2dac2e80-1ad0-11ea-8121-8ff0ff225bd6.png">

这是我试着修改但没有成功的：
<img width="689" alt="Screen Shot 2019-12-09 at 9 57 32 PM" src="https://user-images.githubusercontent.com/42464384/70441968-516f7480-1ad0-11ea-90fe-591de7c396ae.png">

这是运行which python、which python3、python -V、python3 -V、which pip、which pip3、pip -V、pip3 -V、echo $PATH 之后的结果：
<img width="1440" alt="Screen Shot 2019-12-09 at 9 28 38 PM" src="https://user-images.githubusercontent.com/42464384/70442186-c5118180-1ad0-11ea-9e26-1d4e3ce92e5e.png">

按照老师的编程环境配置指南的所有步骤都弄好了，就剩这个python版本问题了，在issue里试着找过答案，还是不知道问题出在哪里，请老师指教。

**Comment by neolee** [comment]
如果你安装配置好了 Homebrew，并且用 Homebrew 安装了 Python 3.7.x 的话，那么你的 .bash_profile 只需要有这么些东西就可以了——实际上大部分情况下连这都不需要，不过保险起见，还是写这个吧：

```shell
export PATH="/usr/local/bin:$PATH"
```

除此以外别的都不需要，你目前就是这个文件写坏掉把环境变量 PATH 搞乱了。

修改好之后，新开一个 Terminal 窗口（或 tab），然后再执行一遍下面这几个：

```shell
which python
which python3
which pip
which pip3
python -V
python3 -V
pip -V
pip3 -V
```

**Comment by chhyuan** [comment]
老师，按照您的方法修改后，现在terminal默认运行python 2.7.16版本。

这是 .bash_profile
<img width="645" alt="Screen Shot 2019-12-10 at 11 59 23 AM" src="https://user-images.githubusercontent.com/42464384/70493994-992fe380-1b44-11ea-8a0b-4df509c9d79d.png">

这是运行
which python
which python3
which pip
which pip3
python -V
python3 -V
pip -V
pip3 -V 的结果：
<img width="665" alt="Screen Shot 2019-12-10 at 11 54 03 AM" src="https://user-images.githubusercontent.com/42464384/70494026-bfee1a00-1b44-11ea-9678-9c6f24a70c32.png">

**Comment by chhyuan** [comment]
老师，按照您的方法改过之后，现在terminal默认运行python 2.7.16

.bash_profile:
<img width="645" alt="Screen Shot 2019-12-10 at 11 59 23 AM" src="https://user-images.githubusercontent.com/42464384/70494203-62a69880-1b45-11ea-8843-1976c4478e09.png">

python、python3、pip、pip3的版本和路径如下：
<img width="665" alt="Screen Shot 2019-12-10 at 11 54 03 AM" src="https://user-images.githubusercontent.com/42464384/70494251-908bdd00-1b45-11ea-9054-cdb3f05157a9.png">

**Comment by neolee** [comment]
这就对啦，从此以后你就用 `python3` 和 `pip3` 就好了，比如安装 Jupyter Lab：

```shell
python3 -m pip install -U pip
pip3 install jupyterlab
```

要运行某个 Python 程序：

```shell
python3 hello.py
```

其实指南里有提到的 😀

**Comment by chhyuan** [comment]
谢谢 老师！怪我自己瞎捣鼓😅
