### ISSUE TITLE
if img in function draw_rect is a local variable, why there is a rect on the image I save?

### ISSUE THREAD

**Issue by erdongchendou** [neolee/pilot#761]
```import cv2

def draw_rect(img):
    cv2.rectangle(img, (50, 50), (200, 200), (0, 0, 255), thickness=3)

img = cv2.imread('/a/b/c/one.jpg')
draw_rect(img)
cv2.imwrite('/a/b/c/two.jpg', img)
```
![two](https://user-images.githubusercontent.com/36499572/70444705-4a973080-1ad5-11ea-8bff-74cf1570c43d.jpg)

**Comment by neolee** [comment]
与本课程无关。

**Comment by erdongchendou** [comment]
```
def increase_one(n):
    n += 1
    return n

n = 1
print(increase_one(n))
print(n)
```
怎么是无关呢，我是在看局部变量的时候，想起来这个例子的。在这个例子里`img = cv2.imread('/a/b/c/one.jpg')`这里的img是全局变量，调用draw_rect()的时候，在函数内部img应该是局部变量，对该局部变量的画框操作应该不影响外部的全局变量img，但是保存全局变量后，图片上却是有矩形框的。也就是对局部变量的操作影响到了全局变量，这是什么原因呢？

**Comment by neolee** [comment]
你的问题源于你对 OpenCV 的理解有问题，和局部变量全局变量有啥关系？
