### ISSUE TITLE
改下素数迭代器运行结果不对

### ISSUE THREAD

**Issue by chenmite** [neolee/pilot#762]
![image](https://user-images.githubusercontent.com/25859760/70491655-d09a9200-1b3c-11ea-8df8-0a8100786a60.png)

**Comment by neolee** [comment]
迭代器里关键的 `__next__()` 方法，其目的是“找到序列中的下一项”，以素数来说，就是“找到下一个素数”，所以这个方法的内容就是找到下一个素数并返回。

所以你的代码中 `return False` 肯定是不需要的，在这基础上重新考虑 `__next__()` 的逻辑再试试。

**Comment by chenmite** [comment]
![image](https://user-images.githubusercontent.com/25859760/70503108-ad340f00-1b5d-11ea-8d6a-b6ffa02c7255.png)

修改一下可以了

**Comment by neolee** [comment]
有进展，不过还是不对，27 并不是素数。

重新分析一下 `__next()__` 基本的实现思路：每一次调用 `__next()__` 返回一个素数，同时 `self.base` 被设定为这个素数+1；然后下一次调用 `__next()__` 时，就从 `self.base` 开始寻找下一个素数。

所以我们我们在 `__next()__` 中要做的事情就是从 `self.base` 开始测试它是不是一个素数，是的话就返回（注意返回前要对 `self.base` +1），不是就 +1 继续。

理解这个基本思路之后再看你的 `__next()__`，里面的思路是有点混乱的，尤其是 `for` 循环，`for` 循环是范围固定的循环，一开始就确定了从 2 循环到 `self.base - 1`，你在循环体里对 `self.base` +1 也不会改变这一点，这是不对的，我们在寻找下一个素数时其实并不知道要试多少个数。

先把大思路理清。

另外有两个小的细节，作为良好的编程习惯，可以立刻就改进：
1. 可以考虑把“判断一个数是不是素数”抽出来做成一个独立的函数，这样可以独立的优化演进这个算法，这是一种有价值的“概念分离”——如果你这么做了，你的思路会更清晰，在一个函数里实现判断一个数是不是素数，另一个函数里测试一个个数字知道找到素数。
2. 这个迭代器的类名，不应该是 `is_prime`，迭代器是用来产生一个序列的，叫 `primes` 或者 `PrimeIterator` 更合适；实际上我感觉你起的这个名字，也一定程度暗示了概念上不清晰的根源。

**Comment by ds-dog** [comment]
![图片](https://user-images.githubusercontent.com/49094749/70902521-fbeb1880-2037-11ea-9b35-4a3a90fa2397.png)
这是我完全没看答案写的……也是结果不正确，一搜发现了这个issue。不知道问题出在哪里，不过看得懂老师说的概念分离，只不过现在还做不到（捂脸）

**Comment by chenmite** [comment]
顺着概念分离，再试试。

**Comment by ds-dog** [comment]
> 
> 
> 顺着概念分离，再试试。

嗯，分离不会出错，但是好奇这个错在哪……
