### ISSUE TITLE
git 为什么老是安装失败！

### ISSUE THREAD

**Issue by lyq760208** [neolee/pilot#763]
各位老师同学们好：
重新安装win10了之后，GIt 一直安装不好！求助
[安装scoop的问题.docx](https://github.com/neolee/pilot/files/3943418/scoop.docx)

**Comment by neolee** [comment]
首先，贴图比贴 Word 文档方便得多，对你和对其他人都是。

其次，这个问题在 Issues 里已经有无数类似问题了，可以先搜索一下。

最后，这个问题的答案是，网络问题，安装 git 失败了。需要 uninstall 然后再重装。
