### ISSUE TITLE
创造子类的时候如需要新的属性，应去修改初始化“__init__”  ,还是用“def”定一个新的变量

### ISSUE THREAD

**Issue by jiangsv** [neolee/pilot#764]
<img width="1042" alt="Screen Shot 2019-12-10 at 3 34 58 PM" src="https://user-images.githubusercontent.com/30655849/70505392-dc994a80-1b62-11ea-82f4-aff289ed965a.png">
我想定义一个`Dog`的子类`husky`，并且希望在`husky`里面加入`habitat`的属性。我只能在每次定义时加上一个`def` 而不能在这个类里面用`__init__`语句么？
或者是说当我们建立了`Cat` 、`Dog`的类以后，要把他们变成Animal 的子类就必须不能让子类的代码里不能有任何的`__init__`语句？
另外一个问题是，我们想让不同的`Dog`有不同的`bark`或者`voice`，只能通过`def`来定义么？
谢谢老师

**Comment by blockchainguangzhou** [comment]
好问题，同问老师

**Comment by neolee** [comment]
这个问题，感觉你没有完全理解面向对象里“覆盖”的概念，所以不太清楚子类可以对父类已有的东西做些啥；另外对对象的“属性”和“方法”理解也有些偏差。建议重新温习下面向对象的基本概念。

从概念上来说，实例属性是一个变量，当一个类定义了一个实例属性之后，这个类的所有对象实例都具有这个变量，但是其值可以各不相同，也就是说属性代表了同类对象之间的个体差异。而 `def` 定义的是一个函数，在类定义里的函数也叫方法；方法是我们可以请对象执行的一个函数，这个函数可以做任何事情，但都与这个对象相关。

从实现的角度，对象的方法也可以做“返回一个属性值”这件事，也就是说，属性可以做的事情，方法也可以做。比如我们的 `Animal` 类有个属性叫做 `self.name`，我们可以不用这个属性，而是定义两个方法，一个叫 `get_name()` 一个叫 `set_name`，分别用于读写对象的 *name*——但这么做并没啥必要，直接用 `self.name` 属性更简单。

但属性有个限制，那就是当子类继承父类的时候，不存在“覆盖（*override*）”父类的属性的选项，必须接受父类定义的属性，你在子类里写 `self.name` 访问的就是父类定义的那个 `self.name`，不会出现两种不同的含义。而方法的优势就是，子类可以 *override* 父类定义的方法，提供完全不同的方法实现——这是我们很多时候选择用方法来实现某个特性的主要理由。

如果理解了上面的基础概念，再来看你的需求，我先尝试归纳一下你的需求，如果不准确请指出：
1. 希望在子类中增加父类里没有的属性；
2. 希望增加 Dog 的子类，子类里 `voice()` `bark()` 方法可以返回不一样的叫声。

第一个需求很简单，在子类里定义你想要的属性就行了，需要的时候可以 override `__init__()` 方法；第二个也很简单，*override* `voice()` 方法即可。

比如像下面这样：

```python
class Animal:

    kind = ''

    def __init__(self, name):
        self.name = name
        
    def voice(self):
        return '...'


class Dog(Animal):
    
    kind = 'canidae'
    
    def voice(self):
        return 'woof-woof'
    
    bark = voice


class Cat(Animal):
    
    kind = 'felidae'
    
    def voice(self):
        return 'meow-meow'
    
    mew = voice


a = Animal('キュゥべえ')
c = Cat('Garfield')
d = Dog('Snoopy')

for animal in [a, c, d]:
    print(animal.name, ':', animal.voice())


class Husky(Dog):
    def __init__(self, name):
        super().__init__(name)
        self.habitat = 'Arctic'

    def voice(self):
        return 'Ohooo'

h = Husky('Snowman')
print(f'{h.name} from {h.habitat}: {animal.voice()}')
```

注意几个点：
1. 类名通称首字母大写，以便和对象及其他变量有显著差异；
2. 子类 override 父类里的方法时，方法的参数和返回值必须保持一致；
3. 子类 override 父类里的方法时，可以用 `super().xxx()` 的方式来获取父类的方法实现，从而复用父类里已经做了的事情。

**Comment by jiangsv** [comment]
谢谢老师的解答，我的概念清晰了很多。
另外我像下面这样初始化`Husky`除了有重复的代码，和您的解决方案上有什么内在的区别么？或者未来会有衍生的问题？


```
class Husky(Dog):
    def __init__(self,name, habitat):
        self.name = name
        self.habitat = habitat

w = Husky('Canadian-Husky', 'Arctic')

x = Husky('Siberian-Husky', 'Siberian')

w.habitat

'Arctic'

w.voice()

'woof-woof'

x.habitat

'Siberian'

x.voice()

'woof-woof'
```

**Comment by neolee** [comment]
可以的，但是重复了 `Animal` 父类里已有的功能，如果某天你想改变 name 的初始化算法，比如想判断下 name 里前后有没有空格，有的话就删掉，那么你就需要在多个地方去修改。所以还是我一直强调的，要避免重复代码，尽量分离概念，各司其职。
