### ISSUE TITLE
关于转义符‘\’的疑问

### ISSUE THREAD

**Issue by ZhaiGuangkai** [neolee/pilot#766]
![微信图片_20191210202743](https://user-images.githubusercontent.com/54047618/70529447-8f7d9e80-1b8b-11ea-97c6-14dc0288e92f.png)
1.为什么我\a 的结果和Python 3转义序列提供的结果不一样？
![微信图片_20191210202905](https://user-images.githubusercontent.com/54047618/70529526-b9cf5c00-1b8b-11ea-8e32-95908e843f1b.png)
2.为什么我的“\\”的结果是  \\  ?
3.为什么“\”不能单独放在字符串末尾？并且在字符串前加上了小写的 r 也不能单独放置在字符串末尾，同时写 \\ 的结果是 \\\\ 呢？

**Comment by neolee** [comment]
1. `'\a'` 已经被转换为特殊字符 `'\x07'`，即 ASCII 表里的 `0x07` 号字符，这个没有问题。
2. 回显的字符串值里面的 `'\\'` 就表示 `\` 这个字符，这个也没有问题。
3. 末尾的 `\'` 会被视为字符串里的一个引号，于是整个字符串就缺少结束的引号，从而语法出错。

另外，你为啥不听课？刚才不是在讲课吗？

**Comment by ZhaiGuangkai** [comment]
觉得之前学的不好，又重新学一遍。看完了就去听课了。😂 在2019年12月10日 21:06，Neo Lee 写道： '\a' 已经被转换为特殊字符 '\x07'，即 ASCII 表里的 0x07 号字符，这个没有问题。 回显的字符串值里面的 '\\' 就表示 \ 这个字符，这个也没有问题。 末尾的 \' 会被视为字符串里的一个引号，于是整个字符串就缺少结束的引号，从而语法出错。 另外，你为啥不听课？刚才不是在讲课吗？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
