### ISSUE TITLE
关于组装字符串：f-string中 { } 嵌套的问题。

### ISSUE THREAD

**Issue by ZhaiGuangkai** [neolee/pilot#767]
在嵌套使用 { } 时候，发现从外往内数大括号的数量，单数的大括号都会把其内的内容做表达式处理，而双数大括号内的则做字符串处理，例如：
1、{ { { { a } } } }   >>>>  { { a } }
2、x = 62
{ { x { x } } } { x }  >>>>  { x 62 } 62
3、{ { { x } { x } } }  >>>>>>  {6262}
4、{  { x } { x } }  >>>>> 提示错误
李骏老师可否帮助解读理解一下

**Comment by neolee** [comment]
f-string 中的 `{表达式}` 会先计算表达式然后替换掉这个 `{}` 及其内部的部分，而 `{{` 和 `}}` 会被理解为普通字符 `{` 和 `}`。以此规则，你的问题都可以自己思考解决。
