### ISSUE TITLE
打印时区时出现中文乱码，而之前与字符串有关的chr()函数则不会是什么情况

### ISSUE THREAD

**Issue by ds-dog** [neolee/pilot#768]
![图片](https://user-images.githubusercontent.com/49094749/70538354-e50e7700-1b9c-11ea-8e61-fd2d862d8982.png)
如上，我也是打印时区时出现乱码，但是在之前的字符串相关的chr()函数时打印的中文不论是如下哪种形式都能正常显示呢？
![图片](https://user-images.githubusercontent.com/49094749/70538518-31f24d80-1b9d-11ea-9c01-c0b8f4c1a8cf.png)

**Comment by ds-dog** [comment]
感觉是不是应该找找tzinfo这个函数好好研究一下，因为其他地方输出中文字符串都很正常……

**Comment by neolee** [comment]
这是 Python 的一个历史悠久的 bug： https://bugs.python.org/issue16322
