### ISSUE TITLE
Python 提供了的 keyword 模块不是内置模块吗

### ISSUE THREAD

**Issue by here9527** [neolee/pilot#769]
老师，有个问题没有想清楚：
在第二阶段的教材第一课，您提到
![屏幕快照 2019-12-11 下午1 09 23](https://user-images.githubusercontent.com/57101368/70593313-89cd9a80-1c17-11ea-90c9-a365f89d2c51.png)
可是在第三课这里系统内置模块list并没有这个模块呀？那这个模块是怎么调用的呢？
![屏幕快照 2019-12-11 下午1 10 37](https://user-images.githubusercontent.com/57101368/70593400-e03ad900-1c17-11ea-866f-8ebe37eb482a.png)
还有this这个模块也是不在内置模块list，我看前面整个教材内容您也没有自己创建this模块并引入呀？那这个是怎么实现的呢？
![屏幕快照 2019-12-11 下午1 10 37](https://user-images.githubusercontent.com/57101368/70593603-a4ecda00-1c18-11ea-8c29-dcb301e48996.png)
描述说是python的彩蛋，那应该是在python内置里，是不是这个模块只是不在sys（系统环境的模块）的list下呀？
![屏幕快照 2019-12-11 下午1 22 46](https://user-images.githubusercontent.com/57101368/70593818-64419080-1c19-11ea-9067-1c3eb5bc9c65.png)

**Comment by neolee** [comment]
好问题。

其实在 Python 的体系里，“built-in” 的概念有宽有紧，这个 `sys.builtin_module_names` 返回的是编译进解释器的模块，换句话说，只要你的解释器跑起来，这些模块就可用，不需要依赖任何其他文件，当然用的时候还是要 import 的。

诸如 keyword 这样的，虽然也是随着 Python 标准安装包安装在你的系统里了，但在你 import 的时候解释器才会从硬盘上加载对应的模块文件。这种通常也算 built-in，但是没有上面那种那么 built-in。

最后是我们用的 termcolor 一类的，就算第三方模块了，因为你必须要 pip install 之后才能用。
