### ISSUE TITLE
Git 与 GitHub 入门 git log 没有出结果

### ISSUE THREAD

**Issue by jianqingchen** [neolee/pilot#77]
![image](https://user-images.githubusercontent.com/24488183/67536523-33110d80-f70a-11e9-9687-5986d7925a35.png)
windos7电脑

![image](https://user-images.githubusercontent.com/24488183/67536487-02c96f00-f70a-11e9-8126-b87b5d7ff226.png)

**Comment by neolee** [comment]
你的 commit 没有成功，所以 `git log` 告诉你还没有任何 commit。

`git commit` 会打开一个编辑器，让你输入提交的说明信息，你输入之后保存关闭编辑器，`git commit` 才会继续执行。你的 commit 没有成功就是因为这里的问题。

另外还有一个可能：之前我的 Git 教程中有个 bug #13 ，已经修正，所以你需要按照 issue #13 里说的设置 git 编辑器。

前天 [教程](https://github.com/neolee/pilot/blob/master/x3-git-github.ipynb) 已经更新，没有这个问题了，按照教程操作即可。
