### ISSUE TITLE
Jupyter Notebook 中 import 模块出错

### ISSUE THREAD

**Issue by bing90740** [neolee/pilot#770]
jupyter中import模块无法运行
模块本身文件在VS.code中可以正常运行
![jupyer 中无法import](https://user-images.githubusercontent.com/56208944/70595601-bdf88980-1c1e-11ea-9335-5e55d832ba65.JPG)

**Comment by neolee** [comment]
你的 notebook 出的错不是 import 出错，而是说 test 模块中没有 say_hi 这个东西，具体原因不清楚，还需要更多信息才行，比如你的目录结构，还有没有其他叫 test 的文件，有没有正确保存 test.py 等等。

**Comment by jiangsv** [comment]
你用的是window的把，看看sys.path.append(.\assets\')
\和/ 的区别
老师用的mac的斜线 所以可能你没有把test.py加进去?
只是猜测

**Comment by neolee** [comment]
嗯，我知道了，因为你的模块名字没取好，Python 自带一个叫 `test` 的模块，所以你这里 import 的是那个模块。你可以这么测试：

```python
import test
test.__path__
```

上面的代码会显示 `test` 模块的源文件所在位置。

反过来说，可能你自己的 test 模块是没有成功引入的，当然最好是别用这种太一般性的名字。

**Comment by bing90740** [comment]
> 你用的是windows的把，看看sys.path.append('.\assets\')
> \和/ 的区别
> 老师用的mac的斜线 所以可能你没有把test.py加进去?
> 只是猜测
你好，我是windows，换了\依旧报错
import sys
sys.path.append('.\assets\')


  File "<ipython-input-30-704223df02a5>", line 2
    sys.path.append('.\assets\')
                                ^
SyntaxError: EOL while scanning string literal

![jupyer 中无法import_3](https://user-images.githubusercontent.com/56208944/70603723-21d87d80-1c32-11ea-968b-4a004be8307a.JPG)

**Comment by bing90740** [comment]
> 你用的是windows的把，看看sys.path.append('.\assets')
> \和/ 的区别
> 老师用的mac的斜线 所以可能你没有把test.py加进去?
> 只是猜测
> 你好，我是windows，换了\依旧报错
> import sys
> sys.path.append('.\assets')
> 
> File "", line 2
> sys.path.append('.\assets')
> ^
> SyntaxError: EOL while scanning string literal



> 嗯，我知道了，因为你的模块名字没取好，Python 自带一个叫 test 的模块，所以你这里 import 的是那个模块。你可以这么测试：
> import test
> test.__path__
> 上面的代码会显示 test 模块的源文件所在位置。
> 反过来说，可能你自己的 test 模块是没有成功引入的，当然最好是别用这种太一般性的名字。

老师好，
测试了test源文件不在这个文件夹
换了一个文件名，myutil在asset目录中，但是找不到源文件位置了
![jupyer 中无法import_1](https://user-images.githubusercontent.com/56208944/70604196-2e110a80-1c33-11ea-98e5-4ce5fdfbb837.JPG)
![jupyer 中无法import_2](https://user-images.githubusercontent.com/56208944/70604229-441ecb00-1c33-11ea-81b0-c3a5530a8407.JPG)

**Comment by jiangsv** [comment]
你可以再运行下`sys.path`看看有没有`'./assets/'`。

**Comment by neolee** [comment]
那就很可能是 @jiangsv 说的问题了，可以试试 `sys.path.append('.\\assets')`

注意目录名因为 Windows 下要使用反斜杠，所以需要用两个反斜杠来转义。

**Comment by bing90740** [comment]
> 那就很可能是 @jiangsv 说的问题了，可以试试 sys.path.append('.\\assets')
> 注意目录名因为 Windows 下要使用反斜杠，所以需要用两个反斜杠来转义。
> p.s. 不过我在 Windows 下用 sys.path.append('./assets') 和 sys.path.append('.\\assets')，效果是一样的，都没问题……
使用反斜杠\\也还是不行，但是sys.path.append('.\\assets')之后sys.path可以查到asset

![jupyer 中无法import_4](https://user-images.githubusercontent.com/56208944/70674613-75de7300-1cc1-11ea-9da9-52cd5373c855.JPG)


![jupyer 中无法import_5](https://user-images.githubusercontent.com/56208944/70674627-842c8f00-1cc1-11ea-8797-373d5a415a70.JPG)


![jupyer 中无法import_6](https://user-images.githubusercontent.com/56208944/70674639-8abb0680-1cc1-11ea-9b9c-26bd60f47f48.JPG)

**Comment by neolee** [comment]
不用看 asset 的 path，你这个可以直接试着用 `myutil.say_hi` 了吧。

**Comment by bing90740** [comment]
李老师，`myutil.say_hi`可以运行，但是，发现运行`myutil.__path__`出错，这个是什么原因？
```
import myutil
myutil.__path__

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-60-4d83131948b8> in <module>
      1 import myutil
----> 2 myutil.__path__

AttributeError: module 'myutil' has no attribute '__path__'

myutil.say_hi('bing','h')

Hi, Bing!
Hi, H!
```
![2](https://user-images.githubusercontent.com/56208944/70682683-9666f700-1cda-11ea-9c25-a01b6fa144a3.JPG)

**Comment by neolee** [comment]
因为你的 myutil 模块就是没有这个属性呀，前面我说的是官方的 test 那个 module 有这个属性（因为那是个目录，而且下面有 __init__.py）。

所以你现在是没问题的（感觉之前除了用 test 做名字不好，其他也没问题）。

**Comment by bing90740** [comment]
好的，谢谢老师
