### ISSUE TITLE
执行“git diff ”命令出来这么复杂的页面了

### ISSUE THREAD

**Issue by hermanxie** [neolee/pilot#771]
![image](https://user-images.githubusercontent.com/48776732/70636171-0a1fea00-1c70-11ea-8636-5b687ad6d042.png)

**Comment by hermanxie** [comment]
还不能退出

**Comment by hermanxie** [comment]
![image](https://user-images.githubusercontent.com/48776732/70636243-24f25e80-1c70-11ea-8682-32170771f593.png)

**Comment by neolee** [comment]
输入 q 应该可以退出。

diff 的格式就这样，看不明白的话，可以考虑用 VSCode 的可视化界面。
