### ISSUE TITLE
git 安装总是失败

### ISSUE THREAD

**Issue by zhaoliang918** [neolee/pilot#772]
网络换了好几家，还是无法解决，不知还有什么办法解决？

```powershell
PS C:\Users\a> scoop list
Installed apps:

  7zip 19.00
  innounp 0.49

PS C:\Users\a> scoop install git
Scoop uses Git to update itself. Run 'scoop install git' and try again.
Installing 'git' (2.24.0.windows.2) [64bit]
未能解析此远程名称: 'github-production-release-asset-2e65be.s3.amazonaws.com'
URL https://github.com/git-for-windows/git/releases/download/v2.24.0.windows.2/PortableGit-2.24.0.2-64-bit.7z.exe#/dl.7z is not valid
PS C:\Users\a> scoop install git
Scoop uses Git to update itself. Run 'scoop install git' and try again.
ERROR It looks like a previous installation of git failed.
Run 'scoop uninstall git' before retrying the install.
WARN  'git' () is already installed.
Use 'scoop update git' to install a new version.
PS C:\Users\a> scoop update git
Scoop uses Git to update itself. Run 'scoop install git' and try again.
PS C:\Users\a>
```

**Comment by zhaoliang918** [comment]
Installed apps:

  7zip 19.00
  git  *failed*
  innounp 0.49

PS C:\Users\a> scoop uninstall git
Uninstalling 'git' ().
'git' was uninstalled.
PS C:\Users\a> scoop install git
Scoop uses Git to update itself. Run 'scoop install git' and try again.
Installing 'git' (2.24.0.windows.2) [64bit]
未能解析此远程名称: 'github-production-release-asset-2e65be.s3.amazonaws.com'
URL https://github.com/git-for-windows/git/releases/download/v2.24.0.windows.2/PortableGit-2.24.0.2-64-bit.7z.exe#/dl.7z is not valid
PS C:\Users\a>

**Comment by neolee** [comment]
大多数代理服务都需要特定配置才能用在命令行环境。

**Comment by michaelmakun** [comment]
换一个好的网络，在一个网络好的时间段下载。

或者先看一下老师下面的配置

用命令scoop checkup

按照提示操作，不行的话换到admin界面。


最后的最后，自己下载一个git，安装。亲测可用
