### ISSUE TITLE
日期转字符串时区乱码/输出年月日出错

### ISSUE THREAD

**Issue by bing90740** [neolee/pilot#774]
1.`print tzinfo`是乱码
2.`print(t.strftime("%Y年%m月%d日 %H时%M分%S秒"))`报错，
    `print(t.strftime("%Y-%m-%d %H:%M:%S"))`正常

**出现这两种情况是因为window环境下关系吗？**
```
from datetime import datetime

t = datetime.now()
t = datetime.now().astimezone()
print(t)
print(t.tzinfo)
```
2019-12-12 13:41:08.508198+08:00
?D1¨²¡À¨º¡Á?¨º¡À??

`print(t.strftime("%Y年%m月%d日 %H时%M分%S秒"))`

---------------------------------------------------------------------------
UnicodeEncodeError                        Traceback (most recent call last)
<ipython-input-74-eb6d1fb40ee3> in <module>
----> 1 print(t.strftime("%Y年%m月%d日 %H时%M分%S秒"))

UnicodeEncodeError: 'locale' codec can't encode character '\u5e74' in position 2: encoding error

`print(t.strftime("%Y-%m-%d %H:%M:%S"))`

2019-12-12 13:41:08

![S2-6日期转字符串](https://user-images.githubusercontent.com/56208944/70686437-50fcf680-1ce7-11ea-9c01-8a36bf2622ca.JPG)

**Comment by neolee** [comment]
周二的课上刚说了这事儿——你不听课的么？

**Comment by bing90740** [comment]
这个课没听，我去听下课，抱歉
