### ISSUE TITLE
p2-3的例子里为什么在 assets 目录下没有 __init__.py 的文件？

### ISSUE THREAD

**Issue by jiangsv** [neolee/pilot#775]
<img width="669" alt="Screen Shot 2019-12-12 at 4 21 42 PM" src="https://user-images.githubusercontent.com/30655849/70695324-6a5c6d80-1cfc-11ea-826c-98019013939b.png">
<img width="220" alt="Screen Shot 2019-12-12 at 4 21 19 PM" src="https://user-images.githubusercontent.com/30655849/70695325-6a5c6d80-1cfc-11ea-952c-44ff12e57bea.png">
老师，在您的p2-3课件和官方文档里都说需要把路径加入`sys.path`,并且需要`__init__.py`。但是我jupyter lab和终端ls命令都看不到，是怎么回事呢？而且官方文档里是每一个子文件夹也是要`__init__.py`的，这是必须的么？

**Comment by neolee** [comment]
实际上 Python  有两种 “package”，一种叫 *regular package*，另一种是 3.3 引入的 *namespace package*，前者必须要 `_init__.py`，而后者不需要，所以我在构建教材的时候为了干净和省事，没有放 `__init__.py`，但对于这个简单的例子，仍然还是无问题的。

具体关于 namespace & packae 说起来有点麻烦，对目前学习也不太重要，如果希望搞清楚可以看官方的文档：

https://docs.python.org/3/reference/import.html#regular-packages

**Comment by jiangsv** [comment]
谢谢老师的解答
