### ISSUE TITLE
两个布尔值其中一个是 True 那么他们 or 运算结果就为 True 不是吗？

### ISSUE THREAD

**Issue by ZhangKaiHua-CW** [neolee/pilot#776]
<img width="251" alt="截屏2019-12-12下午4 31 20" src="https://user-images.githubusercontent.com/58540355/70695714-43526b80-1cfd-11ea-8206-d26828c11451.png">
截图最下面的运算【137】not t or not f，其中not f 不是“True”吗？那两个当中有一个是“True”，那运算结果不就是“True”吗？为什么是“False“？

**Comment by neolee** [comment]
<img width="249" alt="not t or not f" src="https://user-images.githubusercontent.com/24796/70701448-5833fc80-1d07-11ea-9b68-7383f224089b.png">

所以我也不知道你是怎么运行出你那个结果的。
