### ISSUE TITLE
第三方模块安装成功但用 Jupyterlab 或者 VS 测试都显示模块不存在

### ISSUE THREAD

**Issue by JianhaoChen2018** [neolee/pilot#777]
第三方模块termcolor和simpleeval显示安装成功已存在，但用Jupyterlab或者VS测试都显示模块不存在，请问是什么原因呢？是否跟第三方模块的安装目录有关系呢？谢谢
![image](https://user-images.githubusercontent.com/46193647/70699686-7ba97800-1d04-11ea-8932-34c86dc55076.png)
![image](https://user-images.githubusercontent.com/46193647/70699727-8a902a80-1d04-11ea-9097-6f6ec1230561.png)

**Comment by neolee** [comment]
执行这些看看：

```shell
which python
which python3
python -V
python -V
pip -V
pip3 -V
```

**Comment by JianhaoChen2018** [comment]
> 执行这些看看：
> which python
> which python3
> python -V
> python -V
> pip -V
> pip3 -V

![image](https://user-images.githubusercontent.com/46193647/70706003-09d72b80-1d10-11ea-825f-89f0162c3d51.png)
注：我电脑用的 python 是在这个课程之前安装的，版本应该是3.7.3
![image](https://user-images.githubusercontent.com/46193647/70706196-6f2b1c80-1d10-11ea-9500-05126a8fa266.png)

**Comment by neolee** [comment]
看上去你的 pip 和 python 可能不是一套。由于你不是按照课程里的环境配置指南准备的，所以没法提供什么建议。

**Comment by JianhaoChen2018** [comment]
> 看上去你的 pip 和 python 可能不是一套。由于你不是按照课程里的环境配置指南准备的，所以没法提供什么建议。

好的，谢谢李骏老师。我再捣鼓捣鼓，不行就删了按课程配置指南来再装一遍。
