### ISSUE TITLE
命令符修改后再执行没反应：命令行前面方括号显示[*]

### ISSUE THREAD

**Issue by dongjin936** [neolee/pilot#778]
如图：
![QQ浏览器截图20191212152612](https://user-images.githubusercontent.com/56923938/70701910-2707fc00-1d08-11ea-98d9-3f46b1f96206.png)

我遇见两次这个问题，求解。

**Comment by neolee** [comment]
搜索下（比如“星号”）就能找到一堆类似 issue。

请参考 #644
