### ISSUE TITLE
第二章关于理解“赋值”时的疑问：多次赋值

### ISSUE THREAD

**Issue by xbq1022** [neolee/pilot#78]
李老师，在第二章中讲解赋值概念时，程序中有对f进行重复赋值，分别赋值为一个浮点数和一个布尔值。在练习册中，查到f赋值为布尔值。
此处是否为c=3.14？
如果在编程中，出现重复赋值，程序是否只以最下列赋值为准呢？
![image](https://user-images.githubusercontent.com/56924543/67540899-acfcc300-f719-11e9-8866-4f7dfbd1db3e.png)
![image](https://user-images.githubusercontent.com/56924543/67540915-b5ed9480-f719-11e9-8dcc-abd7ecfedd89.png)

**Comment by best-way** [comment]
是以最后赋值的结果为准
![image](https://user-images.githubusercontent.com/49242101/67541257-e1bd4a00-f71a-11e9-8ae5-7b7c21cd2fec.png)

**Comment by neolee** [comment]
你的理解正确，对同一个变量多次赋值，后面的会覆盖前面的，最后一个有效。
