### ISSUE TITLE
更新学习用书出现如下提示(macOS)

### ISSUE THREAD

**Issue by justfiner** [neolee/pilot#780]
在命令行界面出现如下提示:

! [rejected]        master -> master (non-fast-forward)
error: 推送一些引用到 'https://github.com/justfiner/pilot-student.git' 失败
提示：更新被拒绝，因为您当前分支的最新提交落后于其对应的远程分支。
提示：再次推送前，先与远程变更合并（如 'git pull ...'）。详见
提示：'git push --help' 中的 'Note about fast-forwards' 小节。

**Comment by neolee** [comment]
你的远端 repo 比本地的新，所以无法 push。

你肯定操作的顺序有问题。

**Comment by onthebus98** [comment]
你是不是在另外一台电脑上也编辑过学习用书?
