### ISSUE TITLE
用 Unicode 的 code point 打印 emoji 表情时不能正确识别字节数

### ISSUE THREAD

**Issue by jiangsv** [neolee/pilot#781]
<img width="414" alt="Screen Shot 2019-12-12 at 11 57 24 PM" src="https://user-images.githubusercontent.com/30655849/70731619-f1800480-1d41-11ea-9fc5-0c1c26aec360.png">
我在尝试打印多种特殊符号时，发现用unicode的` \u10FFFF `方式不能正确解码（计算器上输入是正常的），查了很多文章还是不能弄懂，感觉应该是字节数判定的问题吧，望老师解答。

**Comment by neolee** [comment]
`\u` 用 Unicode 16 位编码（只有基本多文本平面 BMP 里的字符），`\U` 才是 32 位编码。

**Comment by jiangsv** [comment]
![image](https://user-images.githubusercontent.com/30655849/70779011-950efa80-1dbe-11ea-8dc8-3b7184f9dc83.png)
转换成UTF-32终于实现了，谢谢老师。感觉很有成就感！
