### ISSUE TITLE
这个赋值操作符是什么意思？

### ISSUE THREAD

**Issue by ZhangKaiHua-CW** [neolee/pilot#783]
<img width="317" alt="截屏2019-12-13上午9 38 03" src="https://user-images.githubusercontent.com/58540355/70762779-dedeed00-1d8c-11ea-8848-9b1abf1132b9.png">
以上截图的赋值操作符是我自己好奇心驱使搞出来的，就想看看会出现什么效果，结果出来后看不懂，请指教！

**Comment by neolee** [comment]
`c = +2`

**Comment by ds-dog** [comment]
![图片](https://user-images.githubusercontent.com/49094749/70858951-76d40680-1f46-11ea-97f0-e001d57e32f4.png)
=+的话应该是相当于把后面的数赋值给c吧？

**Comment by neolee** [comment]
@ds-dog 是啊，`=` 后面的都算值，那就是 `+2` 和 `-2` 了。

**Comment by ZhangKaiHua-CW** [comment]
那么是不是意味着 
c =+ 2 
c = +2
c=+2
都是同一个算法，只不过为了统一的格式我们最好写成
c = +2

**Comment by neolee** [comment]
对解释器来说，都是一回事。这个是有解释器的 parser 决定的。

对的，写得清晰是程序员的责任，主要是对我们人类好。
