### ISSUE TITLE
学习用书下载到本地变了味

### ISSUE THREAD

**Issue by doujingling** [neolee/pilot#786]
![image](https://user-images.githubusercontent.com/48606479/70789776-a2cc7c00-1dce-11ea-843d-b75b2775ccea.png)

**Comment by doujingling** [comment]
cd.\Code\ 无法识别；jupyterlab打开选择方式没有conemu选项;

**Comment by neolee** [comment]
前一个命令出错，因为你漏了空格；

后一个命令应该自动打开浏览器，如果没有可以拷贝 `http://localhost...` 那一行地址到浏览器自行打开。

这些都是讲过的。建议先好好学习主课和视频课程，尤其是支线课程的前几课。
