### ISSUE TITLE
clone 学习用书问题

### ISSUE THREAD

**Issue by 123yumingtao** [neolee/pilot#787]
老师，使用PS C:\Users\LENOVO\Code> git clone https://github.com/123yumingtao/pilot-student.git
先是出现RPC failed; curl 56 OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 10054
后来重新运行出现 RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: The remote end hung up unexpectedly
fatal: early EOF
修改PS C:\Users\LENOVO\Code> git config --global http.postBuffer 24288000 然后再克隆

又出现PS C:\Users\LENOVO\Code> git clone https://github.com/123yumingtao/pilot-student.git
Cloning into 'pilot-student'...
remote: Enumerating objects: 90, done.
Unpacking objects:  20% (18/90)
停止半天不动了。
不知道什么原因。

**Comment by neolee** [comment]
网络问题。

**Comment by ygrdkl** [comment]
我也一样的问题
