### ISSUE TITLE
ValueError: time data '2019-7-17 Wed 12:09:13' does not match format '%Y-%m-%d %a %H:%M:%S'

### ISSUE THREAD

**Issue by Vincent-box** [neolee/pilot#788]
![image](https://user-images.githubusercontent.com/56910310/70839896-152e7200-1e4a-11ea-89f0-28cee3acd242.png)
![image](https://user-images.githubusercontent.com/56910310/70839923-3a22e500-1e4a-11ea-8eaa-551abeeb7e71.png)
老師好，我在p2-6遇到了問題，可否幫忙看看，謝謝

**Comment by neolee** [comment]
是不是应该 “2019-07-17” 这样子？

**Comment by Vincent-box** [comment]
還是一樣error
![image](https://user-images.githubusercontent.com/56910310/70844225-12974100-1e79-11ea-983e-61a7137d112b.png)
我的系統是win10
![image](https://user-images.githubusercontent.com/56910310/70844240-4a05ed80-1e79-11ea-896b-b60e58d7a73f.png)

**Comment by qingyix** [comment]
我也出现此问题 win10系统。
![S2 字符串执行错误](https://user-images.githubusercontent.com/48583363/70971403-d7e11300-20db-11ea-8c95-0c54cd574452.JPG)

**Comment by neolee** [comment]
@qingyix 你这个 tzinfo 出乱码是 Python 的一个 bug，在某些版本和配置的 Windows 下会出现，可以参考 #627 ，以及最新的 S2-6 视频课里我也有做解释。

@Vincent-box 的问题是 strptime 无法识别看上去是正确的字符串，这个还没搞清楚为啥。

**Comment by Milkmocha** [comment]
老师，我有一个相关的问题：在命令第二行中有“%a”以获取星期几的信息，但为什么输出里没有"Wed":
Input:
```
s1 = "2019-7-17 Wed 12:09:13"
t1 = datetime.strptime(s1, "%Y-%m-%d %a %H:%M:%S")
print(type(t1), t1)
```
Output:
<class 'datetime.datetime'> 2019-07-17 12:09:13

谢谢啦！

**Comment by neolee** [comment]
@Milkmocha 有问题另开 issue，不要挖已经关闭的老 issue。

你这个问题也有 issue 问过，因为星期不是日期的基本部分，日期的缺省显示里不会显示星期。如果要看星期，需要用 `dt.strftime()` 方法。

**Comment by neolee** [comment]
@Vincent-box 这个老 issue 不知道你后来解决没有，很可能是你的系统的区域设置为中国台湾，所以不认识 Wed 这样的星期，要用中文星期表示。

要确认，你可以用 `d.strftime()` 方法试着打印一个日期的星期出来看看，然后照着这个星期的表示法再去测试 `d.strptime()` 方法。
