### ISSUE TITLE
Scoop 安装报错

### ISSUE THREAD

**Issue by robertswg001** [neolee/pilot#79]
![Scoop install](https://user-images.githubusercontent.com/56988943/67542271-b3da0480-f71e-11e9-8118-38207948c140.png)

**Comment by neolee** [comment]
有同学遇到一样的问题：issue #17 ，issue #52 

这个问题的核心是系统不允许执行某个操作，这个操作是 Scoop 安装所必需的。我目前没有找到解决方案，似乎和特定的 Windows 版本或者当前登录账号的权限有关。

**Comment by robertswg001** [comment]
![scoop install出错1](https://user-images.githubusercontent.com/56988943/67542754-d0773c00-f720-11e9-868e-ec5db2e3797b.png)
重新运行，这个命令也出错了

**Comment by robertswg001** [comment]
不知是否是管理员权限要从电脑设置开启才行

**Comment by neolee** [comment]
你需要是管理员权限的 Windows 账户。

**Comment by robertswg001** [comment]
![scoop install出错2](https://user-images.githubusercontent.com/56988943/67549159-328e6c00-f736-11e9-963a-aba56dde4adc.png)
显示scoop已安装，但不识别？？？

**Comment by neolee** [comment]
Scoop 没装好，需要删了重装，点这个页面上面的 Wiki，按照“重装 Scoop”的说明操作，

**Comment by robertswg001** [comment]
![scoop install出错3](https://user-images.githubusercontent.com/56988943/67554045-28259f80-f741-11e9-98a5-d47d7ce72aae.png)
卸载了重新安装仍出错

**Comment by robertswg001** [comment]
![scoop install出错3](https://user-images.githubusercontent.com/56988943/67554045-28259f80-f741-11e9-98a5-d47d7ce72aae.png)
卸载了重新安装仍出错

**Comment by robertswg001** [comment]
![scoop install出错4](https://user-images.githubusercontent.com/56988943/67554149-5c00c500-f741-11e9-82a1-1c2e1eba1cda.png)
设置c:\Code\scoop,后用划线命令仍出错

**Comment by robertswg001** [comment]
![scoop install出错4](https://user-images.githubusercontent.com/56988943/67554149-5c00c500-f741-11e9-82a1-1c2e1eba1cda.png)
设置c:\Code\scoop,后用划线命令仍出错

**Comment by neolee** [comment]
看我前面一条回复，不用反复发一样的内容。

**Comment by neolee** [comment]
Duplicate of #17
