### ISSUE TITLE
在面向对象 Python 篇输入的代码总是报错

### ISSUE THREAD

**Issue by The993** [neolee/pilot#790]
![4f98c677420a5c2b4c3a9c8b3baf7a9](https://user-images.githubusercontent.com/56963491/70846559-59932f80-1e95-11ea-83c7-8c81ad6eec76.jpg)

**Comment by neolee** [comment]
对象初始化的那个方法叫 `__init__()`，前后都是俩下划线，你写错了，所以解释器认为你没有定义初始化方法。

这个问题课上讲过多次，你没怎么听课吗？

**Comment by The993** [comment]
是没有怎么听课，都是在用学习用书

**Comment by neolee** [comment]
课还是要听的，不然我为啥要专门讲课呢？不就是因为有些估计会有普遍性的问题，专门拿来讲解和强调下嘛。

**Comment by The993** [comment]
好的，老师我会把以前课都听一遍以上的
