### ISSUE TITLE
老师好，这是关于git的问题，不知道该怎么改了

### ISSUE THREAD

**Issue by The993** [neolee/pilot#791]
![图片](https://user-images.githubusercontent.com/56963491/70849681-e7364580-1ebc-11ea-9bf0-973acf198ae0.png)

**Comment by neolee** [comment]
1. 命令返回的提示明确告诉你，有些文件是 untrack 状态，需要先把它们先 git add 进版本库；
2. 还是建议去看 Wiki 里列出的视频课程，里面支线课程第一第二讲是必看的。
