### ISSUE TITLE
对象与类的自练习中定义完方法返回结果不是自己的预期结果

### ISSUE THREAD

**Issue by Erika00** [neolee/pilot#792]
![@%JB}A7CY$%7JHJB~J_6EJJ](https://user-images.githubusercontent.com/52418630/70850519-2e750400-1ec6-11ea-8031-ffea293b0fe4.png)
![ZZ2(G%6 Q$_MJH@MES4X)FC](https://user-images.githubusercontent.com/52418630/70850524-35037b80-1ec6-11ea-9648-6ff2174e17fe.png)
![M}MK)T6NDYR3IBMEW{MBK(R](https://user-images.githubusercontent.com/52418630/70850530-42206a80-1ec6-11ea-999e-d865b7321f09.png)
![{FJ76@K{L%_7 7MSM}EK2DT](https://user-images.githubusercontent.com/52418630/70850535-4cdaff80-1ec6-11ea-9626-ede883eed481.png)
最后一图是想要的预期，老师我的问题是 a.heel()为什么返回z这个“..."，还有最后一起执行实例变量a和b 为什么说是存在无效字符，我找不出来。辛苦老师了

**Comment by ds-dog** [comment]
你倒数第二张图里，最后一句的print那里括号有问题，应该是打成中文括号了，建议检查一下

**Comment by neolee** [comment]
@Erika00 你需要仔细检查两个点：

1. 有些地方的大小写不一致，Python 语言是区分大小写的，`heel` 和 `Heel` 会被视为两个不同的东西。
2. 所有代码里的符号都必须是英文半角，如果错用了中文括号之类的符号，就会出错。

**Comment by Erika00** [comment]
> @Erika00 你需要仔细检查两个点：
> 
> 1. 有些地方的大小写不一致，Python 语言是区分大小写的，`heel` 和 `Heel` 会被视为两个不同的东西。
> 2. 所有代码里的符号都必须是英文半角，如果错用了中文括号之类的符号，就会出错。



> 你倒数第二张图里，最后一句的print那里括号有问题，应该是打成中文括号了，建议检查一下



> 你倒数第二张图里，最后一句的print那里括号有问题，应该是打成中文括号了，建议检查一下

找到问题了，感谢！

**Comment by Erika00** [comment]
> @Erika00 你需要仔细检查两个点：
> 
> 1. 有些地方的大小写不一致，Python 语言是区分大小写的，`heel` 和 `Heel` 会被视为两个不同的东西。
> 2. 所有代码里的符号都必须是英文半角，如果错用了中文括号之类的符号，就会出错。



> @Erika00 你需要仔细检查两个点：
> 
> 1. 有些地方的大小写不一致，Python 语言是区分大小写的，`heel` 和 `Heel` 会被视为两个不同的东西。
> 2. 所有代码里的符号都必须是英文半角，如果错用了中文括号之类的符号，就会出错。



> @Erika00 你需要仔细检查两个点：
> 
> 1. 有些地方的大小写不一致，Python 语言是区分大小写的，`heel` 和 `Heel` 会被视为两个不同的东西。
> 2. 所有代码里的符号都必须是英文半角，如果错用了中文括号之类的符号，就会出错。

![DGW0I4B6$8K` 657_KWGD}I](https://user-images.githubusercontent.com/52418630/71146015-890fb680-225e-11ea-86e5-4f0e40a26955.png)
感谢老师，问题找到！
