### ISSUE TITLE
Mac 系统 Jupyter Lab 里按 Control+Enter 后没有执行并且不能保存文件

### ISSUE THREAD

**Issue by tsao86** [neolee/pilot#793]
我尝试在命令行里关闭再重启jupyter lab ,有时会执行代码，但一会便不能执行，请指教
<img width="685" alt="屏幕快照 2019-12-14 下午11 28 58的副本 3" src="https://user-images.githubusercontent.com/49138260/70851268-f2de3800-1ecd-11ea-82ae-926bd975e449.png">

**Comment by neolee** [comment]
你执行 jupyter lab 的命令行窗口里有什么提示？可能是新版 macOS 的一个毛病，打开文件数目受限。

**Comment by tsao86** [comment]
<img width="590" alt="屏幕快照 2019-12-15 下午9 11 18" src="https://user-images.githubusercontent.com/49138260/70863104-8de31a80-1f7f-11ea-9f3e-03d5390f7522.png">

**Comment by neolee** [comment]
你这个 Jupyter 安装似乎有问题呀，版本不太一致。是按课程里的指南装的么？更新到最新了么？

**Comment by tsao86** [comment]
找到问题了，原来是因为没有安装nodejs,谢谢
