### ISSUE TITLE
调用 fastnumber 这个模块出了问题

### ISSUE THREAD

**Issue by hailinsu** [neolee/pilot#794]
自己输入出错了，于是粘贴复制但还是出错
![TTJ NVJ(@5KJZ21MO}@W5SO](https://user-images.githubusercontent.com/48571418/70856570-221a9680-1f1a-11ea-9f5a-b6790f48fcda.png)

**Comment by neolee** [comment]
你用之前有 `pip install fastnumbers` 安装这个 module 吗？
