### ISSUE TITLE
返回值多了个None

### ISSUE THREAD

**Issue by lilei5200** [neolee/pilot#795]
pets = {'cat': 'cute',   'dog': 'furry'}

def find_pet(name):
    if name in pets:
        print(pets[name])
    else:
        print(f'没找到宠物{name}的信息')

print(find_pet('cat'))
----------------
cute
None

请问老师，这里的返回值，为什么除了cute，还多了个None

**Comment by neolee** [comment]
这个问题上课时候专门讲过，将函数的返回值的时候，去听听第六课的录音。
