### ISSUE TITLE
Visual studio code   不能保存文件

### ISSUE THREAD

**Issue by chenagain** [neolee/pilot#796]
visual studio code 在保存文件的时候，提示错误。如下表示
Failed to save 'Untitled-1': Unable to write file (NoPermissions (FileSystemError): Error: EACCES: permission denied, open '/Untitled-1')

**Comment by chenagain** [comment]
当切换到root后，以下提示：
chendeMBP:~ chenyungen$ su  root
Password:
su: Sorry

**Comment by chenagain** [comment]
The issue solved  already.

**Comment by neolee** [comment]
这个问题并没有解决，你这个解决办法是典型的“饮鸩止渴”。

1. 不应该吧源程序保存在你没有保存权限的地方；
2. 应该尽可能减少使用 root 的机会——我现在一年也没几次会用 root 权限（包括 sudo）。

你现在做法的危险在哪里呢？人为扩大了必要的权限，哪天你在 VSCode 里保存文件，结果不当心覆盖了一个系统文件的时候，就知道了。

所以，正确的思路是，搞清楚你应该在哪里存放你的程序。Wiki 里的支线课程一和二是必须学习的。
