### ISSUE TITLE
关于 datetime 对象的困惑

### ISSUE THREAD

**Issue by spring-ap** [neolee/pilot#798]
```python
from datetime import datetime
t = datetime.now().astimezone()
d = datetime.now()
print(t)
print(t.tzinfo)
print(type(t))
print(type(d))
```
运行后得到如下结果：
```
2019-12-15 21:36:32.929662+08:00
CST
<class 'datetime.datetime'>
<class 'datetime.datetime'>
```
我的问题是：
>1.参考datetime的官方文档，`datetime.now()`是类方法，`datetime.astimezone()`是实例方法。在`t = datetime.now().astimezone()`中，是怎样的调用关系？出现了两次“.”我不太明白。
>2.变量t和d得到的类型都是datetime，为什么呢？
>3.函数的嵌套也是这样使用吗？两次使用“.”?

**Comment by neolee** [comment]
`datetime.now()` 是调用 `datetime` 类的类方法，结果是一个 `datetime` 类的对象实例，然后调用这个对象实例的 `astimezone()` 方法，结果是一个新的 `datetime` 类的对象实例。

这样你的三个问题应该都能想明白了吗？

**Comment by spring-ap** [comment]
老师，你能写一个简单的调用的例子说明一下吗？因为我去看官方的源码还是有点困难。
从你的回答描述表面上可以理解，但是不知道如何应用到代码编写中。在我的认知里，对象作为类的实例后，就会使用类的方法，对象本身又怎样重新定义新的方法呢？
谢谢！

**Comment by neolee** [comment]
```python
t = datetime.now().astimezone()
```

等效的代码是：

```python
t1 = datetime.now() # t1 是个 datetime 类型的对象
t = t1.astimezone() # t 也是个 datetime 类型的对象，其代表的时间与 t1 一样，但增加了时区信息
```

这个能理解吗？

另外，上面说的内容并不需要你去读 Python 源码，所以你的真正困难在哪里？

**Comment by spring-ap** [comment]
可能我的表达不够准确，我是去看python的模块文档用法时，无法区分和使用这些方法应该在编码时如何引用。可能我对于程序中的“对象”概念的理解不够，认为一个类，类中可以包含很多方法，对象实例化后，可以引用类中的方法，但是这个对象的方法是怎样在代码中定义的呢？回头我写个程序吧，可能文字表达还是不清楚。

**Comment by spring-ap** [comment]
我再试图表达一下😄
我理解的"对象"，是从"类"实例化而来，那么上面t1对象只能拥有类datetime的方法。t1如何才能定义自己的方法astimezone,并且该方法还不属于datetime这个类？

**Comment by neolee** [comment]
什么叫 “t1 自己的方法” 呀？`astimezone()` 就是 `datetime` 类定义的方法，所以一切 `datetime` 类的对象实例都拥有这个方法，所以 t1 当然可以调用它。

**Comment by spring-ap** [comment]
https://docs.python.org/3/library/datetime.html#datetime-objects
中描述datetime.now()为class method.
datetime.astimezone()为instance method.如果这两个方法都是属于类datetime的方法，为什么要分开列举呢？

**Comment by neolee** [comment]
因为一个是 class method，一个是 instance method：

* 前者 `datetime` 类对象自己使用（`datetime.now()`），一般类方法都是用来生产对象实例的；
* 后者被`datetime` 类的实例对象使用，比如 `t = datetime.now()` 然后 `t.astimezone()`。

**Comment by spring-ap** [comment]
老师，我们上课时讲的都是class method吧？是不是没有列举过instance method的例子？

**Comment by neolee** [comment]
我们从来没举过 class method 的例子，到目前为止举例的都是 instance method。

**Comment by spring-ap** [comment]
哦，这个问题可以算解决了。结论是，自己仍然不能完全看懂模块手册。
