### ISSUE TITLE
安装 git 总是显示超时

### ISSUE THREAD

**Issue by xiaofeidong2028** [neolee/pilot#80]
![无标题](https://user-images.githubusercontent.com/56985358/67544036-78dbcf00-f726-11e9-89ec-59e3a41a9878.png)

**Comment by neolee** [comment]
网络问题比较麻烦，你可以试试：

1. 换网络；
2. 使用网络代理；
3. 上网搜一下有否其他安装 git 的办法，git 只是工具，只要能用就行；然后看看 scoop 是不是可以正常工作。

**Comment by PATIEN** [comment]
这个我也搞了好久，总是这样，看到李俊老师说换一个网络。我马上想到了用我手机的共享热点连接上电脑，立马就OK了，希望你也试试。
<img width="557" alt="捕获" src="https://user-images.githubusercontent.com/53363523/67614738-a2632c00-f7f4-11e9-971a-0d26d2b82db8.PNG">

**Comment by xiaofeidong2028** [comment]
已经搞定了，谢谢发自我的华为手机-------- 原始邮件 --------主题：Re: [neolee/pilot] 安装 git 总是显示超时 (#80)发件人：PATIEN 收件人：neolee/pilot 抄送：xiaofeidong2028 ,Author 这个我也搞了好久，总是这样，看到李俊老师说换一个网络。我马上想到了用我手机的共享热点连接上电脑，立马就OK了，希望你也试试。

**Comment by 13929103260** [comment]
我试了用手机热点也不行，也试了去Windows下安装，提示说网络代理不行，网络就搞不定了，如果不装是不是就学不了了啊？

**Comment by xiaofeidong2028** [comment]
可以百度下载个git装上就可以了发自我的华为手机-------- 原始邮件 --------主题：Re: [neolee/pilot] 安装 git 总是显示超时 (#80)发件人：13929103260 收件人：neolee/pilot 抄送：xiaofeidong2028 ,Author 我试了用手机热点也不行，也试了去Windows下安装，提示说网络代理不行，网络就搞不定了，如果不装是不是就学不了了啊？
