### ISSUE TITLE
name"n"is not defined

### ISSUE THREAD

**Issue by NathanJJr** [neolee/pilot#801]
![图片](https://user-images.githubusercontent.com/52474460/70864874-d73c6580-1f91-11ea-85ba-073a004b300a.png)
按着教材走的时候发现问题，是因为n必须要在之前赋值好吗

**Comment by xiaoerhai** [comment]
是因为n必须要在之前赋值好吗
------
是的。所有没有被定义过的变量在被调用之前都必须先赋值。我猜，你应该是跳过了教材里的一些code(图中的前面一些代码行还是初始的样子），理论上，如果你按着教材操作（按顺序，不遗漏任何code并执行它们）应该不会报这个错误的。
