### ISSUE TITLE
Regex 输出在 jupyterlab 和 Visual Studio Code 结果不同

### ISSUE THREAD

**Issue by imagelan** [neolee/pilot#803]
老师：
我没有看到有人问这个问题。我试着将下面这段代码在jupyterlab 和Visual Studio Code上运行，结果如下：
jupyter lab- 结果是我们想要的
![image](https://user-images.githubusercontent.com/48951128/70865483-e1c01600-1f23-11ea-9253-2234616195a9.png)

Visual Studio Code- 结果不是我们预期的
![image](https://user-images.githubusercontent.com/48951128/70865513-1d5ae000-1f24-11ea-8614-7549355b2530.png)

我把 pattern 放在https://regex101.com/ 上试着test 一下，出现的结果是 “Your regular expression does not match the subject string.” 不知道怎么回事？

![image](https://user-images.githubusercontent.com/48951128/70865526-53985f80-1f24-11ea-9a44-4780b73caeaf.png)
请老师帮忙解答。

**Comment by neolee** [comment]
你贴在 regex101 的只需要引号里的部分，外面的 `r''` 是不需要的。

在 VSCode 里运行这部分不太清楚，你可以试试：把完整的代码存成一个 .py 文件，然后打开 VSCode 打开一个 PowerShell 的 Terminal，在里面运行 `python xxx.py`。

**Comment by imagelan** [comment]
老师：
我可能对怎么运行Python 还是不太明白。 我将源文件存在如下路径， 文件名是 Regextest.py

![image](https://user-images.githubusercontent.com/48951128/70962307-4f666200-204a-11ea-85ab-36c32b691bcd.png)

在powershell 里报错如下：
![image](https://user-images.githubusercontent.com/48951128/70962388-a79d6400-204a-11ea-8d49-a56e52a05b27.png)

在Visual Studio Code 里报错如下：

![image](https://user-images.githubusercontent.com/48951128/70962427-d287b800-204a-11ea-9b1c-9ae8c53d5e3e.png)

谢谢老师解答。

**Comment by neolee** [comment]
你前面运行 `python Regextest.py` 就是对的做法：`python` 后面是你要运行的文件的路径，如果在当前目录下就直接是文件名，完整的的带后缀的文件名（BTW，文件名最好全小写，符合 Python 的风格习惯）——但你的程序里没有用 `print` 输出，所以你的程序运行完成，没有输出任何东西而已。

后面的尝试就不对了。

**Comment by imagelan** [comment]
老师：
这个问题我又绕回来啦！实在不好意思，麻烦老师解答。 可能我概念不清，不知道为什么Print 输出结果和我的预期不符。会不会是我print的变量输入不对？

![image](https://user-images.githubusercontent.com/48951128/71144917-43fb6e00-21e5-11ea-9c11-8506875ba429.png)

还有一个相似的例子是我从网上搜索的一个iterators 的例子：

我先是定义了一个class，保存成 powtwo001.py。
![image](https://user-images.githubusercontent.com/48951128/71145095-f16e8180-21e5-11ea-921e-7c613481a5e3.png)
另外，新建了一个test_powtow.py 的code 去调用powtwo001.py. 在Visual Studio Code 里面运行的结果如下。 我在想我是不是和上面的例子一样print 的参数不对，所以没有输出结果呢？
![image](https://user-images.githubusercontent.com/48951128/71145236-7eb1d600-21e6-11ea-8ab3-b1f961a72958.png)

**Comment by neolee** [comment]
首先，`str` 是一个 Python 内置函数，你不应该用这个做你的变量名。

然后 `a` 是你定义的一个类的对象实例，你 `print(a)` 就打印出这个对象的缺省信息。

所以你看到的输出都很正常。

那么问题来了：你想实现什么效果？如果你要看迭代器输出的值，那么应该类似这样：

```python
powers = PowTwo(4)
print(powers.__next__())
```

另外，你目前很多基本概念还不清晰，不要一下子搞太复杂，把问题分解，一个个解决；每个问题用简单、集中的几行代码来测试和验证。

比如你要搞清楚正则表达式的疑问，就用简单几行代码验证就好了，不要用对象和类。要学习 iterator 也类似。
