### ISSUE TITLE
hello py文件没有长度，无法打印

### ISSUE THREAD

**Issue by ygrdkl** [neolee/pilot#804]
![hello py文件没有长度](https://user-images.githubusercontent.com/31388214/70870805-e5f73c80-1fd2-11ea-830d-dfe8e2256905.png)

**Comment by xiaoerhai** [comment]
你的`hello.py`是不是本来就是空文件（没有任何内容）。如果是的话打印出来就是空白（也就是你指的“无法打印”吧？）

**Comment by ygrdkl** [comment]
好的，弄好了，就是一个问题，我在VS中，对代码点了Ctrl +S，然后下载了一段代码，就可以打印了。

**Comment by ygrdkl** [comment]
![打印](https://user-images.githubusercontent.com/31388214/70876656-5adb6e00-1ff5-11ea-8653-8245b4483132.png)

**Comment by ygrdkl** [comment]
感谢哈！！
