### ISSUE TITLE
关于enumerate().__next__()的问题

### ISSUE THREAD

**Issue by lilei5200** [neolee/pilot#806]
输入:
animals = ['cat', 'dog', 'monkey']
print(enumerate(animals).__next__())
=======================
输出:
(0, 'cat')

-----------
老师，为什么这里重复代码
print(enumerate(animals).__next__())
总是在原地踏步，总是得到(0, 'cat)
而不是接下来得到（1, 'dog'）?

**Comment by neolee** [comment]
因为每次 `enumerate(animals)` 都会创建一个新的 iterator，从头开始。你应该这么去写：

```python
animals = ['cat', 'dog', 'monkey']
iter = enumerate(animals)

print(iter.__next__()) # 重复执行这一句
```
