### ISSUE TITLE
报错 Unused import time from wildcard import

### ISSUE THREAD

**Issue by leeyeep** [neolee/pilot#807]
代码运行没有问题，但是在VSC里面提示着几个错误，而且无法用vsc的绿色箭头进行执行，但是用命令行的.python 的命令运行没有问题
如图
![image](https://user-images.githubusercontent.com/18671014/70900640-3652b680-2034-11ea-9be9-c1d100d3e181.png)

**Comment by neolee** [comment]
这个不碍事，参考 #665
