### ISSUE TITLE
无法复制pilot-student.git

### ISSUE THREAD

**Issue by ygrdkl** [neolee/pilot#808]
![无法复制pilot-student git](https://user-images.githubusercontent.com/31388214/70901385-a1e95380-2035-11ea-828f-c3bf50259ece.png)

**Comment by ygrdkl** [comment]
试了三次，每次都下载不了，什么情况啊？

**Comment by neolee** [comment]
网络问题，已经有无数这样的 issue 了。

**Comment by ygrdkl** [comment]
终于弄好了，网络太差，很着急。。。
