### ISSUE TITLE
进阶第十一章有限状态机例子问题

### ISSUE THREAD

**Issue by Winsi0n** [neolee/pilot#809]
在测试部分有这么一句：

`# order1.receive() # => 如果运行这一句会抛出 MachineError 异常，因为当前状态与此 trigger（输入）不匹配，转换不被允许`

--------------------------------------------------------------------------------

老师这里是好像应该是 `order1.t_receive()`

**Comment by Winsi0n** [comment]
例子中 tigger 参数是直接写的，后面也没有再进行定义。是不是 Machine 会自动帮我们生成函数？

**Comment by neolee** [comment]
嗯，这个是我改漏了，已经修复，多谢指出~
