### ISSUE TITLE
安装 VScodes 后的 mkdir 操作出错

### ISSUE THREAD

**Issue by hailinsu** [neolee/pilot#81]
![MU50 9G@)RG U2__4@3)O)J](https://user-images.githubusercontent.com/48571418/67547311-5ac79c00-f731-11e9-8d74-f2da5cbb3b6b.png)
安装好VScode了，但是在命令行界面操作出现了上面这个问题

**Comment by neolee** [comment]
这个和 Visual Studio Code 没关系，你的目录下已经有 Code 这个子目录，所以 mkdir Code 就不行了；既然已经有这个目录，直接 cd Code 进入这个目录开始干活就好了。

**Comment by hailinsu** [comment]
![T9G73W}MUXF{}8OR$9N`PSH](https://user-images.githubusercontent.com/48571418/67547959-1e953b00-f733-11e9-96fd-19a99af6fd64.png)
剩下最后一步了，那这个又怎么解决呢

**Comment by hailinsu** [comment]
![T9G73W}MUXF{}8OR$9N`PSH](https://user-images.githubusercontent.com/48571418/67547998-3b317300-f733-11e9-95ba-e3925e38f010.png)

**Comment by hailinsu** [comment]
![T9G73W}MUXF{}8OR$9N`PSH](https://user-images.githubusercontent.com/48571418/67548061-6d42d500-f733-11e9-8f83-5cd2b27982d4.png)

**Comment by neolee** [comment]
后面这个错误信息是说找不到 Python，你确定装好 Python 了吗？

**Comment by hailinsu** [comment]
![ZB T5_B_8SGIEN`K5DNW_6F](https://user-images.githubusercontent.com/48571418/67548571-b182a500-f734-11e9-9eec-873a528160a3.png)
没有安装好 那这种情况呢 还是说已经有issues解答了这个问题呢

**Comment by hailinsu** [comment]
嗯嗯 已经安装好git和python了。那你看我做的最后一步有问题吗 
![8XR_N0~5I5{E%OR1O8BT1GS](https://user-images.githubusercontent.com/48571418/67550673-a2eabc80-f739-11e9-947a-32c000da37f4.png)

**Comment by neolee** [comment]
你的 hello.py 内容是什么，给我看看。

**Comment by neolee** [comment]
几个问题。

1. 列出当前目录下所有文件和子目录的命令叫 `ls` 不是 `Is`，尝试执行 `ls` 看看。

2. 执行 `code hello.py` 可以用 Visual Studio Code  打开 `hello.py` 文件，然后截屏给我看其内容。

3. 你执行 `python hello.py` 既没有报错也没有正确的结果，比较奇怪，请你执行下面这些命令，把结果给我看看：

```powershell
which python
which pip

python -V
pip -V
pip list
```

**Comment by neolee** [comment]
执行下面两个命令，然后截屏发过来：

```powershell
Get-Command python

python hello.py
```

**Comment by hailinsu** [comment]
![4JH(P_6ZEG%Y7AH73XR4H{A](https://user-images.githubusercontent.com/48571418/67609228-47164700-f7be-11e9-9403-6b00b43fb2c6.png)

**Comment by neolee** [comment]
这已经好了嘛……
