### ISSUE TITLE
对话机器人命令运行时出现命名错误：name"XXX" is not defined.

### ISSUE THREAD

**Issue by dongjin936** [neolee/pilot#811]
![QQ浏览器截图20191217101250](https://user-images.githubusercontent.com/56923938/70959338-fe408780-20b6-11ea-9e52-8cc15fa1bdcb.png)
![QQ浏览器截图20191217101323](https://user-images.githubusercontent.com/56923938/70959356-0ac4e000-20b7-11ea-8193-951feacc60fc.png)

**Comment by dongjin936** [comment]
dog=Dog这一步，写完命令运行时，下面出现了正常的问答框。但命令行前面方括号出现[*]，于是，我点击上面重新加载后，再运行就出现这个错误了。

**Comment by spring-ap** [comment]
是不是bot那个类没有运行呢？我自己的体验是jupyterlab有时候不确定执行了哪些语句，这种需要好几段代码块的可以在vscode里保存成py扩展名文件，然后使用vscode的命令行python xx.py
看看老师怎么回复？

**Comment by neolee** [comment]
从你的截图看，你先执行了使用 Dog 类做实例化的代码，后面才执行定义 Dog 类的代码，搞反了顺序。

**Comment by dongjin936** [comment]
是呢！从上往下都重新run一遍，这下都可以了。谢谢李老师。问题解决。

**Comment by dongjin936** [comment]
> 是不是bot那个类没有运行呢？我自己的体验是jupyterlab有时候不确定执行了哪些语句，这种需要好几段代码块的可以在vscode里保存成py扩展名文件，然后使用vscode的命令行python xx.py
> 看看老师怎么回复？

谢谢解答！

**Comment by dongjin936** [comment]
> 是不是bot那个类没有运行呢？我自己的体验是jupyterlab有时候不确定执行了哪些语句，这种需要好几段代码块的可以在vscode里保存成py扩展名文件，然后使用vscode的命令行python xx.py
> 看看老师怎么回复？

你说的这个看起来很高效，我现在还不会操作，但谢谢你给出的高效建议。
