### ISSUE TITLE
打错了一个单词，造成了程序无线循环下去，请问怎么解决？

### ISSUE THREAD

**Issue by ZhangKaiHua-CW** [neolee/pilot#812]
<img width="725" alt="截屏2019-12-17上午11 05 39" src="https://user-images.githubusercontent.com/58540355/70961666-65f9d100-20bd-11ea-9432-a47a17ed85a7.png">

我把 int 和 input 的搞反了，然后下面就无限循环 Not a valid number
还好我又即时改正了过来，虽然当时已经有点卡了，但最终还是成了。

我对这个错误导致的结果有一点点理解，input() 是个无限循环函数，但整个案例我还不能全面理解；
还有就是我面对这个失误采取的解决方案怎么样？有没有更好的解决方案？
除了要小心避免犯这样低级的错误外，还有什么科学的方法或者有什么针对性的异常处理程序？

**Comment by spring-ap** [comment]
循环的是while语句，而执行try后时，因为字符串‘please input a number’不能转换成int数据，会出现ValueError，所以每次循环都是执行except分支。

**Comment by neolee** [comment]
在 Jupyter Lab 里出现无限循环，选择中断或者重启 kernel 就可以了。

避免这类错误的办法就是自己动脑子、小心的推理和验证。

**Comment by ZhangKaiHua-CW** [comment]
研究了好久 int(input('Please enter a number') 这个嵌套函数依然让我很困惑，一直卡在这里：

int() 返回值是整数，如果是int('34'),返回值是整数34，这个能理解，int()只能做整数转换；
如果是int('Please enter a number'),会报错，我也能理解，因为 Please enter a number 不是整数；
然而，input('Please enter a number')的返回值是字符串Please enter a number，返回值不是整数，为什么没有报错呢？
我想了解一下我是对哪一块或者哪些方面的定义没有搞明白。

谢谢
