### ISSUE TITLE
教程有可以打印的电子版吗

### ISSUE THREAD

**Issue by RayOng666** [neolee/pilot#813]
李老师，
请问课程有可以打印的电子版吗？
我另存了pdf打印随手标记翻看，但发现pdf有图片和部分代码显示缺少的情况。

**Comment by spring-ap** [comment]
手机直接登录网站看也很方便的，我每天的班车上都是直接用手机看教材，其实“看”不是目的，我觉得在电脑上“实操”才能有更大进步。

**Comment by neolee** [comment]
同意 @spring-ap 的观点，关键在于练习，所以光看并没有什么大用（偶尔可能想温习和思考一些点，可以看看）。

以后有时间可能可以集结出版，但目前还顾不上……

**Comment by RayOng666** [comment]
我的问题不在于不清楚学习的重点以及主要方法在哪里
而是在补充和完善学习方法以及提高效率

对于一个纯小白学习非泛读的实践内容来说
基础概念以及细节逻辑的掌握的确可以通过海量练习来内化
不过目前的练习体量太少 也容易漏掉基础细节 过程非常烧脑

这个条件下 反复回顾已学是最有效率的
纸质作为补充能随手标注重点并迅速查看
我个人的习惯里，电子版的书籍容易给我带来一些已经理解的错觉
所以才做了pdf补充，但是没想到电子档转换功能不完善也非常不友好

**Comment by neolee** [comment]
@RayOng666 当然各人有各人的不同情况，但根据我自己以及我接触过的大量程序员的实际情况来看，看和想10小时的效果远远不如坐下来写5小时代码，不断写不断排错，是最容易突破升级的方法。

表面上看教材的代码就那些，照着抄也很快就抄完了，但是再来一遍，不看教材里的代码，自己写出完整的代码试试；根据教材的内容，尝试写出一些不一样的代码试试。这个过程中出现任何问题，都很有讨论的价值——最近越来越多 issue 是这种类型了，我觉得可以参考下。
