### ISSUE TITLE
关于 iterator 的一些疑问

### ISSUE THREAD

**Issue by michaelmakun** [neolee/pilot#815]
在定义squares中，最后的循环是 for n in squares(3),这里显示完全正常。

<img width="675" alt="Screen Shot 2019-12-17 at 8 39 03 PM" src="https://user-images.githubusercontent.com/19246142/70996657-32936280-210e-11ea-899f-7f1b93a18e63.png">

但是，我给iter 赋值 squares(3)时，就开始变得不正常。个人觉得，这里squares(3)就等价于iter。但在执行for循环时，第一次正常，第二次就不执行了。

<img width="668" alt="Screen Shot 2019-12-17 at 8 39 46 PM" src="https://user-images.githubusercontent.com/19246142/70996787-7a19ee80-210e-11ea-8609-a6ed06a6c8d4.png">

<img width="621" alt="Screen Shot 2019-12-17 at 8 40 04 PM" src="https://user-images.githubusercontent.com/19246142/70996807-856d1a00-210e-11ea-8a16-6dcda02ed741.png">

可能这里看的不是很清楚，可以看斐波那契数列，f = fib()，之后截取前十个元素用
list(islice(f,0,10))，第一遍执行时正常显示前十个，但是再次执行就变成了随后十个，一直执行，一直顺序截取十个，而不是固定的前十个，这里不理解。

<img width="689" alt="Screen Shot 2019-12-17 at 8 43 23 PM" src="https://user-images.githubusercontent.com/19246142/70996998-fdd3db00-210e-11ea-8855-97725270453c.png">

<img width="616" alt="Screen Shot 2019-12-17 at 8 43 36 PM" src="https://user-images.githubusercontent.com/19246142/70997009-05937f80-210f-11ea-9cb9-e9e5316baf78.png">

还有，再次回到刚才那个squares，当发现结果跟我预想的不一样时，我就想看一下这个类型，发现了不一样的东西。

<img width="609" alt="Screen Shot 2019-12-17 at 8 40 34 PM" src="https://user-images.githubusercontent.com/19246142/70997127-44293a00-210f-11ea-830a-c3530f384116.png">

后面的squares，我可以理解成**类**，但是前面加了 '''__main__'''，我就不理解了。

**Comment by neolee** [comment]
迭代器会保持自己的状态，比如你的 `iter = square(3)`，这个 `iter` 里面就三个数，你迭代三次，它就停在最后，没有新的数了。如果你要再次迭代，就需要创建一个新的迭代器，也就是再次执行 `iter = square(3)` 才好。

而当你写 `for n in square(3):` 的时候，`square(3)` 会生成一个新的实例，这个迭代器实例因为是新的，所以它在起始状态，所以可以从头开始迭代。

**Comment by neolee** [comment]
至于 `type(iter)` 返回的 `__main__.squares`，那个 `__main__` 是你现在运行的主 module name。

**Comment by michaelmakun** [comment]
谢谢老师~
