### ISSUE TITLE
关于从字符串提取有效数据的问题

### ISSUE THREAD

**Issue by spring-ap** [neolee/pilot#816]
```python
s1="2019-7-17 12:09:08 wed"
t1=datetime.strptime(s1,"%Y-%m-%d  %H:%M:%S wed")
print(type(t1),t1)
```
```python
s1="2019-7-17 12:09:08 wed"
t1=datetime.strptime(s1,"%Y-%m-%d  %H:%M:%S %a")
print(type(t1),t1)
```
```python
s1="2019-7-17 wed 12:09:08 "
t1=datetime.strptime(s1,"%Y-%m-%d %a %H:%M:%S ")
print(type(t1),t1)
```
上面三种表达得到都是下面一样结果：
```
<class 'datetime.datetime'> 2019-07-17 12:09:08
```
是因为datetime对象中是不包含表示星期的字段的，在格式中使用“%a"或者其他字符"wed"仅仅对应字符串而占位。那么如果一个字符串中包含了wed这样的星期属性，是不是需要使用正则表达式来处理并提取？

**Comment by spring-ap** [comment]
对于字符串的处理引起了我更多的注意，是因为我们公司有个产品是实时历史数据库，存储数据的类型最终都转换为字符串，而当查询数据时需要程序parse里面的字符串数据，涉及到包括时间和各种数据类型的数据。有时就会出现一些奇怪的错误。当然一般带有时间的字符串中是很少包含“星期”这个属性的，所以我上面的问题可能不具有代表性。

**Comment by neolee** [comment]
`datetime` 类的对象里没有星期几的属性，但是通过年月日再借助日历工具是可以算出星期几的。所以你自己也试过了，通过 %a 是可以匹配出字符串里的星期内容的。所以不知道你的问题在哪里。

从字符串 parse 出数据，从来都是挺有挑战的，一般来说需要字符串的格式相对固定或者有较易处理的规则，然后还要考虑各种意外的容错。

所以当我们把数据 format 成字符串的时候就要注意，尽量采用紧凑而固定、易于 parse 的格式协议，事前做好规划，事后 parse 的时候自然就会舒服一点。

至于你说的时间里，要看 legacy data 的格式具体特点是啥了，其实在数据应用中有个专门的领域叫“数据清洗”，就是处理遗留的、格式相对不够严谨的数据的。

**Comment by spring-ap** [comment]
嗯，虽然通过“%a"的格式设定，保证变量t1得到正确的datetime类型数据，但是%a格式对应的数据“wed”并没有被保存到变量t1中，所以我想问如何把原始字符串中的“wed”存储到有效的新变量中。通过日历函数确实可以得到一个datetime类型数据的“星期”属性，这是另一个好办法。

**Comment by chenmite** [comment]
同样疑问，为什么在strptime后，没有显示星期？

[5]

s = '2019年-12月-16日 Mon 14:25:28'


[6]

t2 = datetime.strptime(s,'%Y年-%m月-%d日 %a %H:%M:%S')
[7]

print(type(t2))
print(t2) 
<class 'datetime.datetime'>
2019-12-16 14:25:28

**Comment by neolee** [comment]
星期不是一个独立的 time part，它是日期根据日历算出来的。所以作为一种概念分离，Python 把 datetime 和 calendar 分开，需要计算星期的时候引入日历就行了。

**Comment by spring-ap** [comment]
ok.thanks
