### ISSUE TITLE
P1-b-final 求四则运算时，调用 simpleeval为什么显示出这样的错误

### ISSUE THREAD

**Issue by zcwlive** [neolee/pilot#817]
![微信图片_20191217221331](https://user-images.githubusercontent.com/52852209/71002560-7c824580-211a-11ea-826f-137ad0df1b6f.png)

![微信图片_20191217221023](https://user-images.githubusercontent.com/52852209/71002348-0d0c5600-211a-11ea-960d-f9347e064ca6.png)

**Comment by neolee** [comment]
这个有点怪。你可以这么试试：打开一个干净的新 notebook，然后运行下面的代码：

```python
from simpleeval import simple_eval
simple_eval('5+5')
```

**Comment by zcwlive** [comment]
当时我就想到了，在后面写了这个代码，是可以正常运行的，所以就奇怪问题出在了哪里。
![微信图片_20191218200833](https://user-images.githubusercontent.com/52852209/71086086-e90d4b00-21d3-11ea-8ee5-ba5738e5a049.png)

今天又重新从头开始找起，原来是定义父类Bot时最后一行代码出错了。
![出错的地方](https://user-images.githubusercontent.com/52852209/71086090-ec083b80-21d3-11ea-86ed-bd0907bd1ca4.png)

问题已经解决了，谢谢老师。还是那句，再怎么认真检查都不为过





> 这个有点怪。你可以这么试试：打开一个干净的新 notebook，然后运行下面的代码：
> 
> ```python
> from simpleeval import simple_eval
> simple_eval('5+5')
> ```

当时我就想到了，在后面写了这个代码，是可以正常运行的，所以就奇怪问题出在了哪里。
![微信图片_20191218200833](https://user-images.githubusercontent.com/52852209/71086086-e90d4b00-21d3-11ea-8ee5-ba5738e5a049.png)

今天又重新从头开始找起，原来是定义父类Bot时最后一行代码出错了。
![出错的地方](https://user-images.githubusercontent.com/52852209/71086090-ec083b80-21d3-11ea-86ed-bd0907bd1ca4.png)

问题已经解决了，谢谢老师。还是那句，再怎么认真检查都不为过

**Comment by neolee** [comment]
Nice!
