### ISSUE TITLE
类定义与对象创建，输入问题。

### ISSUE THREAD

**Issue by zhipingyang120** [neolee/pilot#818]
![Snap 2019-12-17 at 22 56 39](https://user-images.githubusercontent.com/55620481/71006904-0c2af280-2121-11ea-8393-84e1c92ebc4f.png)

复制李老师的可以，自己输入却老是提示错误。我知道要输入两个下划线。

**Comment by neolee** [comment]
因为你 `__init__` 还是拼错了啊。

**Comment by zhipingyang120** [comment]
呵呵，确实！有些小错误，自己怎么检查都检查不出来！
