### ISSUE TITLE
关于 re 的案例计算结果的疑问

### ISSUE THREAD

**Issue by johnxie1225** [neolee/pilot#819]
re中的案例：
str = 'error wonderer severeness'
re.findall(r'(er)+', str)
输出结果是：['er', 'er', 'er']
为什么结果不是['er', 'erer', 'er']呢？因为第二个应该是匹配到wonderer，，从而返回的是wonderer中的erer呀？

**Comment by neolee** [comment]
好问题。

是这样的，要从 `findall` 这个函数的行为说起：
* `findall` 会返回所有匹配的子串，并把所有这些匹配的子串装进一个列表返回，但是——
* 如果正则表达式里包含 *capturing group*（也就是小括号括起来的部分），`findall` 返回的是被捕获的这些 group 子串组成的一个列表；如果正则表达式里包含多个 *capturing group*，返回列表里的每个元素都是一个 *tuple*，里面是捕获的各个 group 子串。

以你的例子来说，`(er)+` 这个正则表达式，在目标字符串里的第二个匹配确实是 `'erer`（因为 `+` 的缺省行为是匹配尽可能长的子串），但是里面被 `(er)` 这个 group 捕获的只是 `'er'` 这个部分，所以返回的自然就是 `'er'` 了。

那么你想从 `findall` 的返回里看到完整匹配的子串怎么办呢？一个办法是使用“非捕获的” group，如下面这样：

```python
str = 'error wanderer severeness'
re.findall(r'(?:er)+', str)
```

小括号里面用 `?:` 开头，表示这虽然是个 group 但我不需要捕获它，仅用于匹配。你可以运行上面代码试一试。

**Comment by johnxie1225** [comment]
明白了。谢谢。
在网上找到了这个 
https://blog.csdn.net/qq_39021458/article/details/82429978
是对老师以上解释的案例说明，其他同学如果不理解老师上面的解释再看看这个应该就彻底理解了~~
