### ISSUE TITLE
素数的生成器写法

### ISSUE THREAD

**Issue by michaelmakun** [neolee/pilot#821]
![QQ截图20191218144854](https://user-images.githubusercontent.com/19246142/71062480-92891800-21a5-11ea-95c6-c97ca8b4de4b.jpg)

仿照迭代器的写法，写了生成器，运行结果只有一个数。不会自动叠加。

**Comment by michaelmakun** [comment]
说一下，我对yield的理解，简单说，就是碰到yield，返回这次执行的结果，下一次再执行一次，再次遇到yield，再返回结果。

从这个角度说，关于斐波那契数列的生成器写法
```
def fib():
    prev, curr = 0, 1
    while True:
        # 这个 yield 是一切魔法的核心，下面解释
        yield curr
        prev, curr = curr, prev + curr
```

```
def fib():
    prev, curr = 0, 1
    while True:
        prev, curr = curr, prev + curr
        yield prev
```

这两个感觉是一样的，所以就照着这个思路改了，但是素数生成器改完就出问题了

**Comment by neolee** [comment]
`yield` 的作用是，在这里返回并暂停挂起函数执行，当你再一次调用 `next` 时从上次挂起的位置（也就是 `yield` 语句后面）恢复运行。

你的函数，`yield` 后面就啥也没有了，函数结束了，当然也就不会继续出数了。

仔细理解上面的表述，对照你写的两个版本的 `fib` 就会理解，其实这两个版本基本等价，没啥区别。

而 `primes` 就不对了。

**Comment by michaelmakun** [comment]
```
def primes():
    m = 2
    n = m
    while not _is_prime(n):
        n += 1
    yield n
    m = n +1
```

我把yield放到上面一行，还是一样的结果。看来还是没理解好，我再想想

**Comment by neolee** [comment]
提示：如果你的 yield 不在某种形式的循环里的话，最多也只会执行一次，吐出一个数。

**Comment by michaelmakun** [comment]
```
def primes():
    n = 2
    while True:
        if is_prime(n):
            yield n
        n += 1
```
写出了一个，稍微理解了一点。谢谢老师，我再多练练

**Comment by michaelmakun** [comment]
```
def primes():
    n = 2
    while True:
        if is_prime(n):
            yield n
        n += 1
```
写出了一个，稍微理解了一点。谢谢老师，我再多练练
