### ISSUE TITLE
p2-5-functional-1

### ISSUE THREAD

**Issue by ZhaiGuangkai** [neolee/pilot#822]
同样的id()函数的返回值和老师的不同，是因为计算机本身的编码问题吗？

**Comment by michaelmakun** [comment]
存在你电脑的位置和存在老师电脑的位置不一样

**Comment by neolee** [comment]
那个 id 是解释器在运行时自动生成的一个唯一 id，基本是不会一样的，但在解释器运行的上下文里是唯一的。

**Comment by ZhaiGuangkai** [comment]
好的，谢谢老师解答 On 12/18/2019 21:10, Neo Lee wrote: Closed #822. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
