### ISSUE TITLE
关于上传Markdown文件相关操作的问题

### ISSUE THREAD

**Issue by Maxuanrui** [neolee/pilot#823]
![image](https://user-images.githubusercontent.com/53324687/71090203-72754b00-21dd-11ea-96cb-3d77a4ed3010.png)
在学习支线课程-**Markdown应用**中
上传Markdown文件时使用`git st`与`git commit -a -m "Init commit"`出现上图所示问题。
---
下图是课程中返回的内容：
![image](https://user-images.githubusercontent.com/53324687/71090621-6e95f880-21de-11ea-9637-aaa2ed328720.png)

**Comment by neolee** [comment]
`git st` 是我自己设置的快捷命令：

 ```shell
git config --global alias.st status
```

你应该没设置过，所以你要用 `git status`。

后一个错误是因为你没有做你的初始设定，无论是我们的课程还是视频讲解，都有说明需要做的初始设定，先仔细看下。
