### ISSUE TITLE
迭代器例一：平方数序列执行出错

### ISSUE THREAD

**Issue by qingyix** [neolee/pilot#824]
没查找出什么原因
![1](https://user-images.githubusercontent.com/48583363/71092159-ae121400-21e1-11ea-9da4-2c8d6bb6e8cd.JPG)

**Comment by neolee** [comment]
你需要贴出完整的代码。

**Comment by qingyix** [comment]
![2](https://user-images.githubusercontent.com/48583363/71152572-c03b9300-2271-11ea-8b94-5049f4bbab25.JPG)
![1](https://user-images.githubusercontent.com/48583363/71152586-c92c6480-2271-11ea-84e2-086c4b8d3129.JPG)

**Comment by neolee** [comment]
初始化的方法叫 `__init__()` 不是 `__int__()`。
