### ISSUE TITLE
关于局部变量和全局变量引用的问题

### ISSUE THREAD

**Issue by Louiswang2019** [neolee/pilot#825]
![image](https://user-images.githubusercontent.com/50611387/71092914-1a414780-21e3-11ea-925f-208ce0b0744b.png)

![image](https://user-images.githubusercontent.com/50611387/71093068-68eee180-21e3-11ea-8c2e-dd0635078320.png)

**Comment by neolee** [comment]
我们讲变量的作用域，不就是为了说明你的第一个问题么……

`global` 关键字可以在一个函数里引用一个全局变量，虽然我们不推荐这么做。
