### ISSUE TITLE
为什么我的描红本不能写字

### ISSUE THREAD

**Issue by songjuan840213** [neolee/pilot#827]
我打开学习用书后不能填写

**Comment by michaelmakun** [comment]
是不是按老师说的进行配置的呢？

如果可能，把你遇到的问题前后情况一并写下来，最好附个图，好让大家更好的帮到你

**Comment by Lilidandan321** [comment]
你可能克隆的是学习教材，不是练习本。

**Comment by songjuan840213** [comment]
谢谢，查找了一下我克隆的时候确实克隆的是教材，但再去克隆练习本已经说有那个目录了，现在还有别的方法吗？或者可以微信沟通吗？18620346473，我的微信号



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Lilidandan321 <notifications@github.com&gt;
发送时间: 2019年12月19日 21:07
收件人: neolee/pilot <pilot@noreply.github.com&gt;
抄送: songjuan840213 <2755138948@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[neolee/pilot] 为什么我的描红本不能写字 (#827)




你可能克隆的是学习教材，不是练习本。

**Comment by Lilidandan321** [comment]
我觉得可以通过传统的方式，直接删除原来你下载的那个pilote-student文件，然后重新克隆。
![image](https://user-images.githubusercontent.com/53359222/71182237-b08f6f00-22b0-11ea-88b3-377a399db05d.png)

**Comment by neolee** [comment]
@songjuan840213 像 @Lilidandan321 同学说的，删掉老的目录，或者改个名字就可以了。
