### ISSUE TITLE
装饰器: 类装饰器和外部函数装饰能不能公用？

### ISSUE THREAD

**Issue by blueeyezhy** [neolee/pilot#828]
李老师，
我实践RSA加密算法的时候，练习使用装饰器对函数的输入数据进行格式化。
装饰器要写俩个一个给来方法用@data_format_self，一个给外部函数用@data_format；
但是他们代码内容是一样的，有没有方法写一个装饰器，再类的内容和外部都可以使用？

```python
"""
RSA by Python
"""
from bitarray import bitarray

def data_format_self(func):
    def wrapper(self, info, flag):
        if flag == 1:
            info_list = [ord(i.encode("utf-8")) for i in info]
        else:
            info_list = [int(i,16) for i in info.split(chr(0))]  
        res = func(self, info_list, flag)
        if flag == 1:
            return chr(0).join([hex(i)[2:] for i in res])
        else:
            return "".join( [(chr(i)) for i in res])
    return wrapper  


class CryptionRSA():
    """
    class of CryptionRSA
    """
    def __init__(self, pq=(47,61), E=17, info ="", flag=""):
        #实例化的时候，保证形参(p,q)是两个质数，且乘积要大于需要要加密的数字
        #公钥加密部分E也取质数，以方便寻找互质的私钥解密部分
        try: 
            self.__public_key, self.__private_key = self.__creat_keys(pq,E)
        except:
            print("All parameters must be prime, and (p-1)*(q-1)%E !=0.")
    
    def __creat_keys(self, pq , E):
        """
        create public_key and private_key
        """
        #计算模
        N = pq[0]*pq[1]   

        #公钥中的E与(p-1)*(q-1)互素,且(p-1)*(q-1)%E!=0,否则退出函数，重新输入参数E 
        if (pq[0]-1)*(pq[1]-1)%E == 0 or not self.is_prime(pq[0]) or not self.is_prime(pq[1]) or not self.is_prime(E):            
            return False

        #计算私钥中的D，使得E*D%(p-1)*(q-1)=1
        i = 1    
        while (i*(pq[0]-1)*(pq[1]-1)+1)%E != 0: i+=1
        
        D = (i*(pq[0]-1)*(pq[1]-1)+1)//E 
        
        #生成公钥和私钥元组并返回
        return  (N, E), (N, D)
    
    def is_prime(self, n):
        """
        Return a boolean value based upon whether the argument n is a prime number.
        """
        if n < 2:
            return False
        if n == 2:
            return True
        for m in range(2, int(n**0.5)+1):
            if (n % m) == 0:
                return False
        else:
            return True
    
    def get_public_key(self):
        """
        get public_key
        """
        return self.__public_key 

    @data_format_self
    def decrypt_sign_RSA(self, info, flag):
        """
        info: massage which is going to be decrypted or signed.
        flag: 0 when decryption; 1 when signning a massage.
        """
        return [i ** self.__private_key[1] % self.__private_key[0] for i in info]




def data_format(func):
    def wrapper(info, K, flag):
        if flag == 1:
            info_list = [ord(i.encode("utf-8")) for i in info]
        else:
            info_list = [int(i,16) for i in info.split(chr(0))]  
        res = func(info_list, K, flag)
        if flag == 1:
            return chr(0).join([hex(i)[2:] for i in res])
        else:
            return "".join( [(chr(i)) for i in res])
    return wrapper  


@data_format
def encrypt_verify_RSA(info, K, flag):
    """
    K: public key
    info: massage which is going to be encrypted or verified.
    flag: 1 when encryption; 0 when verifiation.
    """
    return [i ** K[1] % K[0] for i in info]   

```

**Comment by neolee** [comment]
假定你已经完整学习过 [S2-13](https://github.com/neolee/pilot/blob/master/p2-d-functional-2.ipynb) 中关于装饰器的有关章节。

我理解你的问题主要来源于你要装饰的两个函数的参数列表不一样，而装饰器需要操作被装饰函数的某些特定的输入参数。可以有几个不同思路来解决（理论上都是可行的）：

1. 让 `CryptionRSA` 的 `decrypt_sign_RSA` 方法，和外面的 `encrypt_verify_RSA` 函数，都调用同一个函数来实现具体计算功能，也就是把两个不同的函数接口统一成一个，比如你可以试试让对象方法调用外面的那个函数来做事。进而只要装饰那个统一的函数就好了。

2. 使用带参数的装饰器。带参数的装饰器实际上是根据参数来返回不同版本的装饰器，然后再去装饰主函数，所以你可以根据具体要装饰的函数，用一个特定参数来让装饰器执行不一样的逻辑（可以参见 S2-13 里的例子）。另外，你的例子里 `flag` 压根就不是给主函数用的，而是装饰器使用的参数，可以考虑把 `flag` 改为装饰器的参数。

不过说实话，我觉得你这例子不是使用装饰器的恰当场景。通常来说，装饰器和主函数做的事情是无关的，是一种概念分离，装饰器通常做的是记日志啦、权限检查啦一类独立的事情。换句话说，一般装饰器对主函数的输入输出都不是太关心，对主函数里做的事情也不需要了解；反之亦然。这样才能充分发挥装饰器的优势——任何函数都可以拿装饰器来用，而一个装饰器写的时候也不会给未来使用自己的函数有任何限制。

另外，绝大多数情况下，不用装饰器的主函数本身就能完成自己的任务，而加上装饰器则是附加了一些功能，也就是说，主函数并不那么依赖于装饰器。

你的这个例子里主函数和装饰器之间的耦合实在是太重了，主函数要清楚装饰器的实现逻辑，装饰器也要清楚主函数的实现逻辑，主函数离开装饰器就跑不起来，装饰器离开主函数也没啥用——这样的话为啥要用装饰器呢？还不如直接写几个函数，彼此复用就好了呀。

**Comment by neolee** [comment]
作为对比，我给你看一个例子，这也是装饰器的一个经典的例子，其作用是检查函数的输入参数是不是预期的类型，不是的话就抛出异常：

```python
from functools import wraps

def accepts(*types):
    def accepts_decorator(f):
        assert len(types) == f.__code__.co_argcount
        @wraps(f)
        def wrapper(*args, **kwds):
            for (a, t) in zip(args, types):
                assert isinstance(a, t), f'arg {a} does not match {t}'
                return f(*args, **kwds)
        return wrapper
    return accepts_decorator

# arg1 should only be int, arg2 can be int or float
@accepts(int, (int, float))
def f(arg1, arg2):
    return arg1 * arg2

f(3, 2) # => 6

f('3', 2.0) # => AssertionError: arg 3 does not match <class 'int'>
```

这个装饰器也需要检查主函数的输入参数列表，但是其处理是完全通用的方式进行的，对主函数输入参数的名称、含义、作用都没有限制。你可以尝试体会一下。

**Comment by blueeyezhy** [comment]
谢谢老师，您说的很透。

我确实有要刻意使用装饰器的心理，从而忽视了装饰器本身的特性，复用性和应用场景。
这种意识上的点拨对我很重要，谢谢老师

发自我的华为手机


-------- 原始邮件 --------
发件人： Neo Lee <notifications@github.com>
日期： 2019年12月20日周五 17:49
收件人： neolee/pilot <pilot@noreply.github.com>
抄送： Harry Zhang <blueeye_zhy@outlook.com>, Author <author@noreply.github.com>
主 题： Re: [neolee/pilot] 装饰器: 类装饰器和外部函数装饰能不能公用？ (#828)

假定你已经完整学习过 S2-13<https://github.com/neolee/pilot/blob/master/p2-d-functional-2.ipynb> 中关于装饰器的有关章节。

我理解你的问题主要来源于你要装饰的两个函数的参数列表不一样，而装饰器需要操作被装饰函数的某些特定的输入参数。可以有几个不同思路来解决（理论上都是可行的）：

  1.  让 CryptionRSA 的 decrypt_sign_RSA 方法，和外面的 encrypt_verify_RSA 函数，都调用同一个函数来实现具体计算功能，也就是把两个不同的函数接口统一成一个，比如你可以试试让对象方法调用外面的那个函数来做事。进而只要装饰那个统一的函数就好了。

  2.  使用带参数的装饰器。带参数的装饰器实际上是根据参数来返回不同版本的装饰器，然后再去装饰主函数，所以你可以根据具体要装饰的函数，用一个特定参数来让装饰器执行不一样的逻辑（可以参见 S2-13 里的例子）。另外，你的例子里 flag 压根就不是给主函数用的，而是装饰器使用的参数，可以考虑把 flag 改为装饰器的参数。

不过说实话，我觉得你这例子不是使用装饰器的恰当场景。通常来说，装饰器和主函数做的事情是无关的，是一种概念分离，装饰器通常做的是记日志啦、权限检查啦一类独立的事情。换句话说，一般装饰器对主函数的输入输出都不是太关心，对主函数里做的事情也不需要了解；反之亦然。这样才能充分发挥装饰器的优势――任何函数都可以拿装饰器来用，而一个装饰器写的时候也不会给未来使用自己的函数有任何限制。

另外，绝大多数情况下，不用装饰器的主函数本身就能完成自己的任务，而加上装饰器则是附加了一些功能，也就是说，主函数并不那么依赖于装饰器。

你的这个例子里主函数和装饰器之间的耦合实在是太重了，主函数要清楚装饰器的实现逻辑，装饰器也要清楚主函数的实现逻辑，主函数离开装饰器就跑不起来，装饰器离开主函数也没啥用――这样的话为啥要用装饰器呢？还不如直接写几个函数，彼此复用就好了呀。

―

**Comment by blueeyezhy** [comment]
试了一下装饰器，代码看上去反而更复杂了。最终选择在函数内部实现功能了。
谢谢李老师
