### ISSUE TITLE
P2-7 中 islice 的 callable 问题

### ISSUE THREAD

**Issue by ZhaiGuangkai** [neolee/pilot#829]
![微信图片_20191220202740](https://user-images.githubusercontent.com/54047618/71254932-703ef800-2367-11ea-8617-a72b377ffb79.png)
老师，前面还可以使用，为什么这个代码段中islice就不能callable了呢？

**Comment by michaelmakun** [comment]
<img width="647" alt="Screen Shot 2019-12-23 at 8 42 32 PM" src="https://user-images.githubusercontent.com/19246142/71358712-dd02fe00-25c4-11ea-9265-c5d418aeb54c.png">

我试了，没问题啊

**Comment by ZhaiGuangkai** [comment]
这也是我反复尝试过，搜索过后的纠结所在。 在2019年12月23日 20:47，michaelmakun 写道： 我试了，没问题啊 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by ZhaiGuangkai** [comment]
今天试了，又可以了，也许是系统或者软件哪里出问题了
