### ISSUE TITLE
scoop checkup 后提示不允许所请求的注册表访问权

### ISSUE THREAD

**Issue by haojie606** [neolee/pilot#83]
PS C:\Users\haojie> scoop checkup
WARN  LongPaths support is not enabled.
You can enable it with running:
    Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1
WARN  Found 1 potential problem.
PS C:\Users\haojie> Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1
Set-ItemProperty : 不允许所请求的注册表访问权。
所在位置 行:1 字符: 1
+ Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem'  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (HKEY_LOCAL_MACH...trol\FileSy
   stem:String) [Set-ItemProperty], SecurityException
    + FullyQualifiedErrorId : System.Security.SecurityException,Microsoft.Powe
   rShell.Commands.SetItemPropertyCommand

PS C:\Users\haojie>

**Comment by neolee** [comment]
你的 Windows 登录账号似乎权限不足，这个问题不是一定会有影响，但是个隐患。

如果安装 Scoop、git、Python、jupyterlab 顺利可以先不管它。

**Comment by neolee** [comment]
Duplicate of #17

**Comment by haojie606** [comment]
Thank you very much!

 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Neo Lee"<notifications@github.com&gt;; 
发送时间: 2019年10月28日(星期一) 下午2:18
收件人: "neolee/pilot"<pilot@noreply.github.com&gt;; 
抄送: "生如夏花"<411860972@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [neolee/pilot] scoop checkup 后提示不允许所请求的注册表访问权 (#83)




Duplicate of #17

**Comment by summercool2020** [comment]
> 你的 Windows 登录账号似乎权限不足，这个问题不是一定会有影响，但是个隐患。
> 
> 如果安装 Scoop、git、Python、jupyterlab 顺利可以先不管它。
