### ISSUE TITLE
SQL增加列限制小问题

### ISSUE THREAD

**Issue by Winsi0n** [neolee/pilot#830]
`ALTER TABLE users ADD CONSTRAINT constraint_username UNIQUE (username)`

老师，这句SQL语句里面 constraint_username 的部分起什么作用呢？

**Comment by neolee** [comment]
`ADD CONSTRAINT` 子句给 `users` 表增加一个 constraint，其名称叫 `constraint_username`（这个你可以自己指定），而具体限制规则是 `UNIQUE (username)`，即 `username` 列不可出现重复值。

**Comment by Winsi0n** [comment]
懂了，谢谢老师
