### ISSUE TITLE
HTML页面调用md文件显示

### ISSUE THREAD

**Issue by blueeyezhy** [neolee/pilot#831]
李老师你好，
写了几篇python学习总结( `.md` 文件)，想要在自己的主页显示，就都需要转化成HTML文件。一个一个转化很麻烦，于是我想编写一个HTML文件模板，然后调用 `.md` 文件显示在HTML上。
写了一段代码，可是显示不出来。网上寻找了一些解决方案，但是不得要领。请老师帮我看看。
```html
<!DOCTYPE html>
    <html>
    <head>
        <script src="./static/js/lib/jquery.min.js"></script>
        <script src="./static/js/lib/marked.min.js"></script>
    </head>

    <body>
        <div id="content"></div>
        <script type="text/javascript">
            $.get("./README.md",function(response, status, xhr){
                $("#content").html(marked(response));
            }); 
        </script>
    </body>
    </html>

```

**Comment by neolee** [comment]
我记得你好像是用 press.one 的吧，直接支持 markdown 的哇。

非要自己来的话，最简单的办法是用新的 Fetch API 来下载 markdown 文件，然后用随便什么那个流行的 Markdown JavaScript 库进行渲染就好了。你的代码，主要是对 JavaScript 和 DOM 不熟悉。下面是我测试过的代码：

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=800, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.7.0/marked.min.js"></script>
    <title>Embedded Markdown</title>
</head>
<body>
    <p>The content of Markdown file:</p>
    <div id="md-content"></div>

    <script>
        fetch('article.md')
        .then((resp) => resp.text())
        .then(function(data) {
            document.getElementById('md-content').innerHTML = marked(data)
        })
    </script>
</body>
</html>
```

**Comment by blueeyezhy** [comment]
谢谢李老师
我是用press.one的，但是press.one不支持Latex排版，写的文章签名出来全是美元符号。
所以就想着能不实现这样的需求。

Harry, a life-long learner.

发件人: Neo Lee<mailto:notifications@github.com>
发送时间: 2019年12月21日 15:06
收件人: neolee/pilot<mailto:pilot@noreply.github.com>
抄送: Harry Zhang<mailto:blueeye_zhy@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [neolee/pilot] HTML页面调用md文件显示 (#831)


我记得你好像是用 press.one 的吧，直接支持 markdown 的哇。

非要自己来的话，最简单的办法是用新的 Fetch API 来下载 markdown 文件，然后用随便什么那个流行的 Markdown JavaScript 库进行渲染就好了。你的代码，主要是对 JavaScript 和 DOM 不熟悉。下面是我测试过的代码：

<!DOCTYPE html>



<html lang="en">



<head>



    <meta charset="UTF-8">



    <meta name="viewport" content="width=800, initial-scale=1.0">



    <meta http-equiv="X-UA-Compatible" content="ie=edge">



    <script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.7.0/marked.min.js"></script>



    <title>Embedded Markdown</title>



</head>



<body>



    <p>The content of Markdown file:</p>



    <div id="md-content"></div>







    <script>



        fetch('article.md')



        .then((resp) => resp.text())



        .then(function(data) {



            document.getElementById('md-content').innerHTML = marked(data)



        })



    </script>



</body>



</html>

―

**Comment by blueeyezhy** [comment]
李老师
为什么你的这部分代码在ie中可用，在chrome上就显不出'article.md' 呢？

Harry, a life-long learner.

发件人: Neo Lee<mailto:notifications@github.com>
发送时间: 2019年12月21日 15:06
收件人: neolee/pilot<mailto:pilot@noreply.github.com>
抄送: Harry Zhang<mailto:blueeye_zhy@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [neolee/pilot] HTML页面调用md文件显示 (#831)


我记得你好像是用 press.one 的吧，直接支持 markdown 的哇。

非要自己来的话，最简单的办法是用新的 Fetch API 来下载 markdown 文件，然后用随便什么那个流行的 Markdown JavaScript 库进行渲染就好了。你的代码，主要是对 JavaScript 和 DOM 不熟悉。下面是我测试过的代码：

<!DOCTYPE html>



<html lang="en">



<head>



    <meta charset="UTF-8">



    <meta name="viewport" content="width=800, initial-scale=1.0">



    <meta http-equiv="X-UA-Compatible" content="ie=edge">



    <script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.7.0/marked.min.js"></script>



    <title>Embedded Markdown</title>



</head>



<body>



    <p>The content of Markdown file:</p>



    <div id="md-content"></div>







    <script>



        fetch('article.md')



        .then((resp) => resp.text())



        .then(function(data) {



            document.getElementById('md-content').innerHTML = marked(data)



        })



    </script>



</body>



</html>

―

**Comment by neolee** [comment]
我就是在 Chrome 测试的，你可以打开 Developer Tools 的 Console 看看有什么错误。

**Comment by blueeyezhy** [comment]
这个使我浏览器的问题吗？没有科学上网？


[cid:image002.png@01D5B81C.430CB900]

Harry, a life-long learner.

发件人: Neo Lee<mailto:notifications@github.com>
发送时间: 2019年12月21日 16:19
收件人: neolee/pilot<mailto:pilot@noreply.github.com>
抄送: Harry Zhang<mailto:blueeye_zhy@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [neolee/pilot] HTML页面调用md文件显示 (#831)


我就是在 Chrome 测试的，你可以打开 Developer Tools 的 Console 看看有什么错误。

―

**Comment by blueeyezhy** [comment]
我知道原因了，是跨域访问的问题。等我把站点弄好了，写一下关于这个问题的总结。
谢谢李老师

发自我的华为手机


-------- 原始邮件 --------
发件人： 张 野 <blueeye_zhy@outlook.com>
日期： 2019年12月21日周六 16:32
收件人： neolee/pilot <reply@reply.github.com>
主 题： 回复: [neolee/pilot] HTML页面调用md文件显示 (#831)
这个使我浏览器的问题吗？没有科学上网？


[cid:image002.png@01D5B81C.430CB900]

Harry, a life-long learner.

发件人: Neo Lee<mailto:notifications@github.com>
发送时间: 2019年12月21日 16:19
收件人: neolee/pilot<mailto:pilot@noreply.github.com>
抄送: Harry Zhang<mailto:blueeye_zhy@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [neolee/pilot] HTML页面调用md文件显示 (#831)


我就是在 Chrome 测试的，你可以打开 Developer Tools 的 Console 看看有什么错误。

―

**Comment by neolee** [comment]
噢，你的 Markdown 和 HTML 还不在一个域名下啊，那就更麻烦了。

**Comment by blueeyezhy** [comment]
我的md文件和HTML文件都在本地git上，用本地测试功能的时候，chrome用fatch访问的是本地file：///开头的文件，所以是跨域。如果用Python把本地git目录开成Server，用http：//localhost访问就可以成功调试了。
这几天把建站的服务器端，浏览器端的搭建及ajax请求与dom显示学习了一下，应该可以解决我的问题，等我实现了好好总结一下。

发自我的华为手机


-------- 原始邮件 --------
发件人： Neo Lee <notifications@github.com>
日期： 2019年12月24日周二 22:29
收件人： neolee/pilot <pilot@noreply.github.com>
抄送： Harry Zhang <blueeye_zhy@outlook.com>, Author <author@noreply.github.com>
主 题： Re: [neolee/pilot] HTML页面调用md文件显示 (#831)

噢，你的 Markdown 和 HTML 还不在一个域名下啊，那就更麻烦了。

―
