### ISSUE TITLE
什么是内存？什么是硬盘？什么是固态硬盘？

### ISSUE THREAD

**Issue by xiaoerhai** [neolee/pilot#833]
李骏老师，这个问题困扰我很久了，感觉大家都知道，但我自己一直没真正搞明白。
根据第一章第一节【理解编程语言】得知：
内存：是计算机的组成部分之一；
硬盘：属于外设，也是计算机的组成部分之一；
拿Windows系统来讲，我可以理解为C盘就是这里的内存，D/E/F盘是这里的硬盘吗？（依据：IT同事协助我安装软件的时候一直建议我最好不要将内存大的软件集中放在C盘，会影响计算机运行速度。）
固态硬盘：它是我从同事嘴里听到的，我进一步问同事具体是什么的时候，他说装了固态硬盘运行速度会很快。至于背后的逻辑问他也答不上来。

**Comment by neolee** [comment]
一、内存和外存

你在 Windows 的文件浏览器里看到的所有盘都是计算机的外部存储——通常都是硬盘，因为现在基本没人用软盘和光盘了。所以 C D E F 等等都是硬盘。

内存是装载计算机主板上的一些芯片，（相对）直接和 CPU 相连，CPU 可以极高速度读写内存，然后把需要长久保留的数据写到硬盘上。

你的 IT 同事的意思应该是“不要把占硬盘太多的软件装在C盘”，原因是 C 盘是 Windows 系统所在的存储，而且有时候 Windows 会用 C 盘来做一些临时用途，所以保证 C 盘有足够空闲空间很重要。

以前内存和外存（硬盘）的差异很清晰，但是到了智能手机时代，不知道从啥时候开始有些厂商有意识的混淆这个概念，所以很多人搞不清楚手机上的内存和外存，比如某手机 128G 存储，这个实际上是外存，就是存放手机应用、照片、邮件等等的，而内存经常大家都不提，实际上现在最新的 iPhone 大概 4G 内存，而台式计算机通常是 8-32G 内存。

二、SSD 和 HD

以前的硬盘都是磁盘，原理是通过磁方式读写专门的一种磁性介质，采取马达加磁碟的机械驱动方式来寻址（就是找到我们要的数据）；近年逐步崛起的 SSD 则采取半导体闪存（Flash）作为存储介质，简单说就是一种具有记忆能力并可以反复擦写的半导体集成电路。由于机理上的巨大差异，Flash 的读写速度可以数十倍甚至百倍于传统的物理硬盘，而且也不容易损坏。

**Comment by xiaoerhai** [comment]
清晰很多了，蟹蟹老师。我试着延伸下，看我说的对不对：
1.  因为```内存是直接和CPU相连的，CPU 可以极高速度读写内存```，这一点，说明其他条件都一样的情况下**内存越大，电脑的运行速度越快**；
2.  ```然后把需要长久保留的数据写到硬盘上```，这一点，说明内存和外存（硬盘）的一个区别：内存不能长久保留数据，但硬盘可以；
3.  相对于Windows操作系统，C盘好比是它的内存（但相对于CPU，它是外存），C盘的闲置内存越大，操作负荷就越小，运行更轻松。

**Comment by neolee** [comment]
前两点都对，第3点不太对，C盘和其他盘一样硬盘（更准确的说叫“硬盘分区”），只不过 Windows 自己的系统文件在 C 盘上（Windows 也倾向于需要时就用 C 盘做缓存一类的事情）。

**Comment by xiaoerhai** [comment]
明白了，谢谢李骏老师解答。
