### ISSUE TITLE
生成迭代器错误

### ISSUE THREAD

**Issue by lihuaiyu123** [neolee/pilot#834]
![1576936726(1)](https://user-images.githubusercontent.com/48613328/71308949-3cce9d00-243d-11ea-994f-08ba36e23551.png)
我在编写平方数迭代器后用for循环迭代
跑出对象不可迭代错误。

问题1、为什么教材的就可以for循环成功，而我的就出错误呢？
问题2、教材中的squarse（3）这里实例化出来一个对象，为什么实例化出来是一个可迭代对象呢？

**Comment by neolee** [comment]
你这个显然写的和教材里的不一样呀，没实现 `__iter__()` 这个方法。

当一个 xxx 出现在 `for x in xxx` 的这个地方时，Python 会隐式调用 `iter(xxx)` 来获取一个 iterator，如果 xxx 实现了 `__iter__()` 方法，就会根据这个方法的返回得到一个 iterator，否则就会抛出 `not iterable` 的错误。

**Comment by lihuaiyu123** [comment]
那意思就是当我们自己写一个迭代器的时候，必须定义内置方法__init__()。否则当for遍历的时候就无法隐形调用__init__(）函数。然后抛出错误

**Comment by neolee** [comment]
必须有 `__iter__` 和 `__next__` 这两个方法，不是 `__init__`，`__init__` 是一般的对象初始化方法。
