### ISSUE TITLE
str 函数在 nteract 下报错

### ISSUE THREAD

**Issue by iceberg-yuan** [neolee/pilot#835]
![nteract-str](https://user-images.githubusercontent.com/57003256/71315643-2f48ff80-249d-11ea-86a8-6ec6598ebc33.PNG)
李老师，我发现str在我的nteract下不能用，f'{a}'是可以的，不知什么原因。
另外，str在jupyter note和python命令行下都没问题。

**Comment by xiaoerhai** [comment]
我的是可以的：
![image](https://user-images.githubusercontent.com/48662601/71316112-b8fccb00-24a5-11ea-9009-d3447f95cdcf.png)

**Comment by neolee** [comment]
感觉和 nteract 没啥关系，是不是你前面用 str 做了变量名？
