### ISSUE TITLE
学习手册里代码不显示

### ISSUE THREAD

**Issue by aosjiabei** [neolee/pilot#836]
我fork了老师的，老师的页面有代码，但为什么我的不显示代码

![image](https://user-images.githubusercontent.com/48588326/71315780-e3e42080-249f-11ea-8a67-5242c6d7371f.png)

**Comment by aosjiabei** [comment]
我fork了老师的，但为什么我不显示代码
![image](https://user-images.githubusercontent.com/48588326/71315768-ada6a100-249f-11ea-842e-be3af72e2236.png)

**Comment by xiaoerhai** [comment]
你应该clone的是老师的**学习用书**```pilot-student```，它就是没有代码的；而你提到的有代码的是老师的**教材**```pilot```。看着**教材**在**学习用书**里自己敲，这就是很好的学习方式。

**Comment by aosjiabei** [comment]
> 你应该clone的是老师的**学习用书**`pilot-student`，它就是没有代码的；而你提到的有代码的是老师的**教材**`pilot`。看着**教材**在**学习用书**里自己敲，这就是很好的学习方式。

我爱死你了，被人回复互动的感觉好棒。我刚学，还不知道，嘻嘻。我是在自己的编辑器上敲代码的
