### ISSUE TITLE
关于字符串的索引问题

### ISSUE THREAD

**Issue by ZhangKaiHua-CW** [neolee/pilot#838]
<img width="305" alt="截屏2019-12-22下午2 54 36" src="https://user-images.githubusercontent.com/58540355/71318410-73eb8f80-24cb-11ea-9dd0-59681569bf93.png">

[9] 输出的结果 Python 重复了6次不是很明白其中的原理。

**Comment by neolee** [comment]
因为你写了 `print(s)`，你是不是其实想写 `print(i)`？

**Comment by ZhangKaiHua-CW** [comment]
[7] 确实写的是 print(i)，显然[9]是没有意义的，只不过它竟然能算出结果来，所以很好奇

**Comment by neolee** [comment]
有没有意义看你想干啥，你让计算机重复输出 n 次一样的东西，这个应该反思的是你吧……
