### ISSUE TITLE
 VSCode 怎么在编辑器里打不开?VSCode里面什么都没有。怎么让编辑器和VSCode联动起来?

### ISSUE THREAD

**Issue by doujingling** [neolee/pilot#839]
![5a08e225590bf3e7a5a8fbe1317b502](https://user-images.githubusercontent.com/48606479/71319220-3a6c5180-24d6-11ea-86cf-8c8e81988012.jpg)
![237e324a9dad2e7c94443a8572cbad7](https://user-images.githubusercontent.com/48606479/71319222-3f310580-24d6-11ea-9cf2-9b7b6192b773.jpg)

**Comment by neolee** [comment]
确保你已经成功下载安装 Visual Studio Code，如果在此前提下命令行里 `code` 命令还是不认识，可以尝试重启下 Windows。

**Comment by doujingling** [comment]
又重新下载后好了。
前面是因为下载时更改了打开方式，导致连不上。
