### ISSUE TITLE
无法安装软件包管理工具 Scoop

### ISSUE THREAD

**Issue by Jenny0523** [neolee/pilot#84]
无法安装软件包管理工具 Scoop，出现 错误提示，请帮忙解决！
![微信图片_20191025115711](https://user-images.githubusercontent.com/48664589/67550520-48516080-f739-11e9-9c26-75e5614d52f0.png)
![微信图片_20191025115735](https://user-images.githubusercontent.com/48664589/67550521-48e9f700-f739-11e9-94aa-f3599fa534f3.png)

**Comment by neolee** [comment]
你执行的命令最后有些奇怪的字符，为啥会有这样的字符？

把这些怪字符去掉再试试。

**Comment by neolee** [comment]
我知道了，你直接复制粘贴了指南里的命令，最后是用来表示“回车”的一个特殊字符，那个字符只是要你输完命令之后回车，不是命令的一部分。

**Comment by Jenny0523** [comment]
![微信图片_20191025160557](https://user-images.githubusercontent.com/48664589/67554147-5b682e80-f741-11e9-9014-ccb990e8b488.png)
又出现了新的问题，老师。

**Comment by Jenny0523** [comment]
它显示我已经成功安装了，但我不能更新。

**Comment by neolee** [comment]
Scoop 没装好啊，你在这之前做了哪些操作？有没有遇到错误？

**Comment by Jenny0523** [comment]
好的，　谢谢老师，我如果装到一半，快下班了，之前的内容还在的吧？

**Comment by neolee** [comment]
正在执行安装任务的时候如果关机或者休眠，会影响安装过程，最好是继续做完当前的在运行的任务。

**Comment by Jenny0523** [comment]
![微信图片_20191025174745](https://user-images.githubusercontent.com/48664589/67561529-9ffac680-f74f-11e9-8ffe-5cf87c870bc3.png)
谢谢老师，今天 安装成功了一些。
![微信图片_20191025174749](https://user-images.githubusercontent.com/48664589/67561532-a0935d00-f74f-11e9-8e37-fefc1e68699d.png)
