### ISSUE TITLE
父类和子类名称定义规则问题

### ISSUE THREAD

**Issue by lgqbee** [neolee/pilot#841]
![11](https://user-images.githubusercontent.com/57405578/71322349-a7e1a780-2501-11ea-8456-3babf56c8270.jpg)
![22](https://user-images.githubusercontent.com/57405578/71322353-add78880-2501-11ea-86c6-570e743375cf.jpg)
图1是因为think前的_ 造成的输出结果不同吗？
图2为什么输出结果是这样的？

**Comment by lgqbee** [comment]
> 
> 
> ![11](https://user-images.githubusercontent.com/57405578/71322349-a7e1a780-2501-11ea-8456-3babf56c8270.jpg)
![22](https://user-images.githubusercontent.com/57405578/71322604-67cff400-2504-11ea-8483-8205321e656a.jpg)

> 图1是因为think前的_ 造成的输出结果不同吗？
> 图2为什么输出结果是这样的？

**Comment by neolee** [comment]
你是否知道你这种问问题的方法，会给看得人很大的困扰啊？要花很多时间还不一定能理解你想问啥。另外你一楼和二楼是同一个问题吗？这两楼有啥区别不？

下面只能就我能猜到的一些点说下，你最好能重新梳理下问题。

1. 下面代码为啥返回 2：
```python
h = Hello()
h.run()
```
这段代码实例化了一个叫 Hello 的类，生成一个 Hello 类的对象实例 h，可是 Hello 类的定义我没看到，所以我没法知道为啥输出 2。

2. 然后下面似乎就掉进类名的坑里了。
原则上来说，你执行 `x = XXX()` 来创建一个实例对象，如果没报错，那就说明 XXX 这个类或者函数是在当前这个运行环境里是定义过的；如果报错说 `XXX is not defined`，就说明 XXX 这个类或者函数没定义过。这种问题计算机基本是不会犯错的，不用怀疑，一定是你自己的问题。

p.s. 如果你运行过一段代码，定义了一个类或者函数 XXX，然后你把这段代码改成别的了，当前环境还是会记得你的定义的。很多时候初学者会在一个 notebook 里改了太长时间，甚至忘记自己做过啥，所以不要在一个 notebook 里做太多、做太久，可以分开的就分开几个 notebook 试；还可以选择 Kernel -> Restart kernel 来重启当前环境，然后按照正确顺序重新执行代码。
