### ISSUE TITLE
异常处理中的例子输入代码后得不出教材中的结果

### ISSUE THREAD

**Issue by yuexiangming** [neolee/pilot#842]
![122202](https://user-images.githubusercontent.com/58320967/71323204-7e2d7e00-250b-11ea-9d7c-97228e43e6fe.PNG)

**Comment by yuexiangming** [comment]
把教材和学习用书关掉再打开，重新运行代码就出结果了。还是想问一下老师，这是什么原因。

**Comment by neolee** [comment]
一点信息和线索都没有，我怎么可能知道啊……
