### ISSUE TITLE
p2-7-iterable-iterator 迭代器重复执行疑问

### ISSUE THREAD

**Issue by bing90740** [neolee/pilot#843]
![P2-7yeild 执行1](https://user-images.githubusercontent.com/56208944/71344140-b92bc200-259c-11ea-8760-1fc51f5c5c8a.JPG)

斐波那契数列中yield语句的执行‘list(islice(f, 0 ,5))’结果是

>[1, 1, 2, 3, 5]
>

重复执行‘list(islice(f, 0 ,5))’结果是 

>[8, 13, 21, 34, 55]
>

我的疑问是：第二次执行时，变量 prev, curr = 3，5
列表第一位为什么不是**5**，而是**8**？

**Comment by neolee** [comment]
下一次执行的时候从上次 yield 那个位置的下一行开始执行，你看看这个“下一行”做了啥？

**Comment by bing90740** [comment]
不明白为什么第一次执行从yield执行，下一次执行从yield下一行执行？

**Comment by neolee** [comment]
> 然后就是 yield 这个魔法的关键了。yield 和 return 相当，也会从函数中返回一些值，但不一样的是：return 返回值的同时彻底终止了函数，而 yield 则是“暂停”了函数执行，保存了函数当时的所有状态（比如所有局部变量的值），以后再返回到 yield 的下一行继续执行——这个“以后”到底是什么时候呢？聪明的你一定可以猜到，就是我们下一次调用 __next()__ 的时候！

教材里讲了，这就是 yield 这个关键字的工作方式，是 Python 解释器实现的。

**Comment by bing90740** [comment]
但是我用return方法重复执行
`list(islice(f, 0, 5, 1))`
得到的结果和yield结果是一样的，return没有终止，感觉也是"暂停"函数运行
代码如下：
```
from itertools import islice

class fib:
    def __init__(self):
        self.prev = 0
        self.curr = 1
    
    def __iter__(self):
        return self
    
    def __next__(self):
        self.prev, self.curr = self.curr, self.prev + self.curr
        return self.prev
    
    next = __next__

f = fib()
list(islice(f, 0, 5, 1))
    
```
![P2-7return执行1](https://user-images.githubusercontent.com/56208944/71388800-c6948b00-2634-11ea-897b-6f3193f3badb.JPG)

![P2-7return执行2](https://user-images.githubusercontent.com/56208944/71388805-cf855c80-2634-11ea-8410-dfcc8ed6e5c3.JPG)

**Comment by best-way** [comment]
你这个代码return是next方法里的最后一行代码，后面没代码所以看不到return终止的效果
return和yield的应用场景也不一样，yield一般用在循环体里

**Comment by neolee** [comment]
@bing90740  一个是迭代器，一个是生成器，两个写法是不一样的，你还是今晚听完课再看吧。
