### ISSUE TITLE
Mac 环境 Python 3.7 运行代码出现以下问题要怎么处理？

### ISSUE THREAD

**Issue by zsqiang001** [neolee/pilot#844]
终端出现的WARNING:
DEPRECATION WARNING: The system version of Tk is deprecated and may be removed in a future release. Please don't rely on it. Set TK_SILENCE_DEPRECATION=1 to suppress this warning.

google 了一个解决方案，意思是说要更新pipfile,应该怎么操作？：
After a few hours messing with it I figured it out!
The Pipfile contained a reference to Python version 3.7
Therefore pipenv install was searching my machine for any 3.7 version of Python installed. The version it found was Homebrew's, which has Tk 8.5.9 statically linked.
By updating the Pipfile to require Python 3.8 my machine started pulling my system Python, which uses the dynamically linked Tk, which I had successfully updated to 8.6.9

**Comment by neolee** [comment]
我们用不到 Tcl/Tk，如果用课程的配置指南，用 Homebrew 的缺省方案安装 Python 3.7.4 的话，是不会有这个问题的。所以你是怎么安装的 Python 呢？

你可以执行一下下面的命令，把结果贴出来：

```shell
which python
which python3
python -V
python -V

brew info python

pip -V
pip3 -V
```

**Comment by zsqiang001** [comment]
自我感觉基础概念掌握的不牢靠，找了套官网的推荐的新手教程《如何像计算机科学家一样思考》做补充练习材料。执行后发现多了一个python3.7.5的版本，是要卸载删除吗？
<img width="1440" alt="截屏2019-12-24上午6 38 10" src="https://user-images.githubusercontent.com/37511474/71383753-bbcbfd00-2618-11ea-8de4-44d137bd63c5.png">

**Comment by zsqiang001** [comment]
https://www.python.org/download/mac/tcltk/#built-in-8-6-8
查到这个解释，两种方案。一是要更新python3的版本，用brew更新python3显示引进安装了3.7.5的版本。二是下载Active的8.6版TCL/TK,要部署包括在现有python框架里。
问题：用brew可以直接更新python3的版本吗？

**Comment by neolee** [comment]
既然基础不扎实，就严格按照指南操作，不要自己乱来，不然只会越来越乱，而且别人帮不了你。

目前这个状态其实问题不大，你只要用 `python3` `pip3` 这两个命令就好了，要运行 Python 源代码用前者，安装第三方包用后者，应该就可以了。

**Comment by zsqiang001** [comment]
好的，感谢老师
