### ISSUE TITLE
老师，为什么我 rindex 和 index 找出来的是一样的呀？

### ISSUE THREAD

**Issue by zhipingyang120** [neolee/pilot#845]
![Snap 2019-12-23 at 23 10 29](https://user-images.githubusercontent.com/55620481/71366031-c0be8b80-25db-11ea-90dc-212ed10ff70d.png)

我看了[#695](https://github.com/neolee/pilot/issues/695)号问题的回答，还是有点不明白

**Comment by neolee** [comment]
你知道 `rindex` 这个函数是干啥的吗？

**Comment by zhipingyang120** [comment]
>find() index() rindex() 可以查找子串并给出子串的位置，区别是：
如果没找到 find() 会返回 -1，而后两个会抛出运行时异常 ValueError；
index() 返回从左向右找到的第一个匹配的位置，rindex() 则是从右向左找。


```
s = 'Perform a string formatting operation. The string on which this method is called can contain literal text...'
s.index('string')   为10
s.rindex('string')  为43
```
李老师，再看了一遍例子，我明白了，rindex()虽然是表示从右向左找，但找到后还是得从左向右数。

**Comment by neolee** [comment]
是呀，找到的是子串的匹配位置，这个位置以子串的起始来标记。
