### ISSUE TITLE
关于”万物皆为布尔值“

### ISSUE THREAD

**Issue by tsao86** [neolee/pilot#847]

**Comment by neolee** [comment]
没有内容？

**Comment by tsao86** [comment]
抱歉不小心按下Enter键发送出去了，但在我提问题的时候我好像找到了答案，不防再说一遍,看我的理解对吗？
贴图如下：
<img width="521" alt="屏幕快照 2019-12-24 下午2 45 57" src="https://user-images.githubusercontent.com/49138260/71398915-f48dc580-265c-11ea-8b57-68e64cd139a7.png">

if n != 0: "相等于" if n:
if 语句后面的逻辑默认的 True,除非一些特殊的数据需要内置函数bool()作出判断

**Comment by neolee** [comment]
> if 语句后面的逻辑默认的 True,除非一些特殊的数据需要内置函数bool()作出判断

这句话理解不能……

”万物皆为布尔值“的意思是，几乎任何东西都可以放在 `if` 后面做逻辑判断表达式，if 会尝试将其转换为布尔值，一些常见值对应的布尔值是这样的：
* 非0的数值 => True
* 0 => False
* 非空的字符串 => True
* 空字符串 "" => False
* 非空的列表 => True
* 空列表 [] => False
* ……

**Comment by tsao86** [comment]
谢谢李老师
