### ISSUE TITLE
P2-7 素数迭代器参考答案中方法 __next__ 如何理解

### ISSUE THREAD

**Issue by Tanyangkai** [neolee/pilot#848]
<img width="540" alt="屏幕快照 2019-12-25 02 25 23" src="https://user-images.githubusercontent.com/19951791/71422580-369b2380-26be-11ea-93a1-d72bf2adef98.png">

1. while not self._is_prime(n) 这个循环中有个not怎么理解？
2. n += 1 与后面 self.next = n + 1 分别表达什么意思？

**Comment by Tanyangkai** [comment]
def __next__(self):
        n = self.next
        while not self._is_prime(n):
                n += 1

        self.next = n + 1
        return n
1. while not self.prime(n) 这个循环中有个not怎么理解？
2. n += 1  与后面 self.next = n + 1 分别表达什么意思？

**Comment by neolee** [comment]
类似这样的问题，最好自己有个思考或者至少猜想，你对这两个问题是怎么看的？
