### ISSUE TITLE
自己写的生成素数的迭代器，不知道哪里出现了问题，生成的是奇数而不是素数

### ISSUE THREAD

**Issue by aosjiabei** [neolee/pilot#849]
````class a:
    def __init__(self):
        self.base = 0
    
    def __iter__(self):
        return self
        
        
    
    def __next__(self):
        while True:
            self.base += 1      
            if self.base == 2:
                return self.base
                break
                         
            for m in range(2,self.base):
                if (self.base % m) != 0: #这个判断素数的代码有什么问题？
                    return self.base
                break
                   
 
    
    next = __next__
        
iter = a()
iter.next()
iter.next()
iter.next()
iter.next()
iter.next()#为什么得到非素数：9

**Comment by neolee** [comment]
迭代器里的 `__next__()` 方法，其目的是给出序列中的下一个数。在素数这个序列里，这具体是什么意思呢？简单说就是：

1. 首先扔出一个 2，第一个素数；把这个素数保存到 self.base 中；
2. 之后调用 `__next__()` 就是从 `self.base+1` 开始寻找下一个素数，方法就是一个个数去测试它是不是素数，不是就 +1 试下一个，是的话就返回，同样要把找到的最新的素数保存到 self.base 中。

用这个逻辑来检查你的代码，可以发现问题主要在下面的代码：

```python
for m in range(2,self.base):
    if (self.base % m) != 0:
        return self.base
    break
```

这段短短的代码却有不少问题。
* `for` 循环体最后是一个 `break`，所以这个 `for` 循环只会运行一次，就 break 了；
* `if` 判断也有问题，它的意思是，用 2 去除 `self.base`，如果不能整除，整个 `__next__()` 方法就返回 `self.base`，这显然不足以证明 `self.base` 就是素数。

正确的逻辑，确实有点复杂，所以需要将其拆分和简化（责任分离），比如可以先写一段”伪代码“来整理思路：

```python
def __next__(self)
    # 从之前返回的素数之后开始找新的素数
    while True:
        self.base += 1
        if self.base 是素数:
            return self.base
```

这段逻辑非常简单直接，基本不可能犯错。所以我们就把问题简化为：如何判断正整数 `self.base` 是否素数，只要解决这个问题并把它写成一个函数就可以直接用了：

```python
def is_prime(n):
    """Return a boolean value based upon whether the argument n is a prime number."""
    # 这里要如何实现？
    return True

class primes:
    ... ...

    def __next__(self)
        # 从之前返回的素数之后开始找新的素数
        while True:
            self.base += 1
            if is_prime(self.base):
                return self.base
```

而判断一个 n 是不是素数，最简单的办法就是用比 n 的平方根小的整数一个个去除 n，看看能不能整除，任何一个可以整除都可以断言 n 不是素数（返回 `False`），都不能整除的话就说明 n 是素数（返回 `True`）。你可以尝试自己去实现一下这个 `is_prime()` 函数，记得写好了试着用一些数去调用测试一下，测试完毕再用于迭代器 `primes` 就比较有谱了——如果写不出，其实 S2 课程的第 3 章 ”模块“ 的例子里就有这个函数的实现，可以参考。

**Comment by aosjiabei** [comment]
@neolee 谢谢李俊老师。昨天看，一脸懵逼；今天再看，病情好转。啊，我要哭啦！终于把生成器generator做出来啦！
```
from math import sqrt
from itertools import islice
def primes():
    n=0
    while True:
        n+=1
        if n < 2:
            n+=1
        if n ==2:
            yield n
        if n>2:   
            for i in range(2, int(sqrt(n)) + 1):
                if n % i == 0:#判定不是素数
                    break
            else:
                yield n
                
        

p=primes()
print(next(p)) 
list(islice(primes(), 0, 20))

**Comment by neolee** [comment]
不错！

做对是第一步，下一步是要做好。几点要求你可以考虑：

1. 先把迭代器真正搞懂搞熟，然后才是生成器，不要急；
2. 学会通过责任分离来简化代码，不要写太长的的函数，尽量用小的函数完成明确清晰地职责，然后组合起来完成更大的目标。

**Comment by Michael-Magic-816** [comment]
正在学iterate这一章，素数判断和逻辑也有点晕，上来看看issue果然很有收获，自己再试试看。
