### ISSUE TITLE
如何让生成器 generator 从头开始？

### ISSUE THREAD

**Issue by spring-ap** [neolee/pilot#850]
昨天听完课后有个小疑问，老师一直在强调yield与return的区别，我想知道如果生成器已经跑过几轮，我要采用什么办法可以终止生成器的继续执行，让它重新开始？

**Comment by neolee** [comment]
重新创建一个新的生成器，比如生成器函数写好了叫 `primes()`，那么下面的代码就会生成一个新的迭代器：

```python
i = primes()
next(i)
next(i)

# create a new one
i = primes()
```

**Comment by spring-ap** [comment]
用代码验证了，确实如此，谢谢老师
