### ISSUE TITLE
素数的 generator 碰到2个问题

### ISSUE THREAD

**Issue by xiaoerhai** [neolee/pilot#853]
![image](https://user-images.githubusercontent.com/48662601/71454917-d1365800-27cd-11ea-950a-80198693af6b.png)
问题一：
函数```def _is_prime(n)```的最后一句```return True```报错，但作为模块```import```的时不会报错；
问题二：
函数```def primes()```的输出和自己的预期不符，一开始觉得肯定会输出[2,3]，至于n=4之后确实没法输出。但实际的输出是10个2 。

**Comment by hermes0911** [comment]
第一个问题， 你的 `return True` 并不属于你的函数模块， 看前面有命令输入的提示符 >>>，相当于直接在运行 `    return True` 这个命令而已。
第二个问题， 程序的逻辑搞错了，在 `n = m` 之后，n 就一直等于2， 后面 `while` 不断循环，每次都是返回 n , 也就是2。

**Comment by xiaoerhai** [comment]
![image](https://user-images.githubusercontent.com/48662601/71457451-fb414780-27d8-11ea-9eb7-1de192f65b0e.png)
第一个问题，如上图结果还是一样的。

**Comment by neolee** [comment]
下面的错误提示说的很清楚了，你在缩进的时候混杂了空格和 Tab 制表符，这在 Python 里是违规的。

**Comment by xiaoerhai** [comment]
![image](https://user-images.githubusercontent.com/48662601/71497297-8b8f9300-2892-11ea-9be3-da9ab1e50b47.png)
昨天的2个问题，自己手敲代码后得到答案了。第一个问题也理解了，是自己粗心大意造成；第二个问题还是没理明白，逻辑上还没完全理解。当时我是模仿教材上的代码(函数__next__())写的：
```python

from math import sqrt
from itertools import islice

class primes:
    def __init__(self):
        self.next = 2

    def __iter__(self):
        return self

    def _is_prime(self, n):
        if n < 2:
            return False

        if n in (2, 3):
            return True

        for i in range(2, int(sqrt(n)) + 1):
            if n % i == 0:
                return False

        return True

    def __next__(self):
        n = self.next
        while not self._is_prime(n):
            n += 1

        self.next = n + 1
        return n
    
list(islice(primes(), 0, 10))
```

**Comment by xiaoerhai** [comment]
l

> 第一个问题， 你的 `return True` 并不属于你的函数模块， 看前面有命令输入的提示符 >>>，相当于直接在运行 ` return True` 这个命令而已。
> 第二个问题， 程序的逻辑搞错了，在 `n = m` 之后，n 就一直等于2， 后面 `while` 不断循环，每次都是返回 n , 也就是2。

@hermes0911  那 `while`  循环里最后的 `m += 1`  为什么没有生效后返回给`n = m`。

**Comment by Jared-Gong** [comment]
1、```m += 1```后执行的是```while```循环，之前的赋值不再重复了。
2、你逻辑没问题，是的判断语句有问题，当```n = 4```的时，```while```判断是```False```，循环自然就结束了。所以你只能得到```2和3```

**Comment by Jared-Gong** [comment]
后面想了想 可能明白你的疑惑在哪里了。迭代器和生成器是运行步骤还是不一样的，迭代器是通过```__next__```不停的运行下次执行的代码，而生成器是通过```yield```所在的循环体运行下次代码。不知道你的疑问是不是这个。

**Comment by xiaoerhai** [comment]
> 1、`m += 1`后执行的是`while`循环，之前的赋值不再重复了。
> 2、你逻辑没问题，是的判断语句有问题，当`n = 4`的时，`while`判断是`False`，循环自然就结束了。所以你只能得到`2和3`

你说的第2点我明白。但第1点还是不明白。

**Comment by xiaoerhai** [comment]
> 后面想了想 可能明白你的疑惑在哪里了。迭代器和生成器是运行步骤还是不一样的，迭代器是通过`__next__`不停的运行下次执行的代码，而生成器是通过`yield`所在的循环体运行下次代码。不知道你的疑问是不是这个。

应该不是的。还是不明白的地方：`n += 1`就可以，`m +=1`却不行。

**Comment by Jared-Gong** [comment]
迭代器中：如果的是素数```n += 1```之后执行的是```__next___```,如果不是素数```n += 1```继续执行```while```循环体里的素数判断代码。
生成器中：无论是否是素数```m +=1```之后都是执行```while```循环体里面的代码。
如果还是不理解，那就是我对你的意思理解错了。

**Comment by neolee** [comment]
首先，修改了 Tab 和 Space 的问题之后，你判断是否素数的 `_is_prime()` 函数就没问题了，所以问题出在生成器本身的逻辑。看看你的 `primes()` 定义，那个 `while` 的条件，在 n=4 的时候就不成立了，然后 `while` 结束，`primes()` 函数也结束了，序列终止。

**Comment by xiaoerhai** [comment]
大致理解你的意思，但不清楚你描述的是哪一段代码，因为我结合你的描述看以下代码感觉是有点出入的：
> 迭代器中：如果是素数`n += 1`之后执行的是`__next___`,如果不是素数`n += 1`继续执行`while`循环体里的素数判断代码。
```python
 def __next__(self):
        n = self.next
        while not self._is_prime(n):
            n += 1

        self.next = n + 1
        return n
```
我当时依照的是这个迭代器。如果`n = self.next`是素数，下一步执行的应该是`self.next = n + 1`（而不是你说的`n += 1`，或许你其实就是指的是`self.next = n + 1`）,再下一步就是`return n`。

> 生成器中：无论是否是素数`m +=1`之后都是执行`while`循环体里面的代码。
关于这个，我结合的是以下代码：
```
def primes():
    m = 2
    n = m
    while _is_prime(n):
        yield n
        m += 1
```
这里，我认为只有是素数的时候才会运行`m +=1`（而你指的是不管是否是素数都会运行）。

最后，感觉是我在阐述一个问题的时候没有强调重点，导致没有得到我想要的答案。我在老师的回答上再次进行提问下吧。

**Comment by xiaoerhai** [comment]
> 首先，修改了 Tab 和 Space 的问题之后，你判断是否素数的 `_is_prime()` 函数就没问题了，所以问题出在生成器本身的逻辑。看看你的 `primes()` 定义，那个 `while` 的条件，在 n=4 的时候就不成立了，然后 `while` 结束，`primes()` 函数也结束了，序列终止。
> 
> 上面 @Jared-Gong 同学说的没错，迭代器是靠不断调用 `__next__()` 来产生下一个数，每次 `__next__()` 都是从头到尾执行的；而生成器是在依靠 `yield` 关键字暂停和回复一个函数的执行，这个函数一共只会运行一次（无论你 next 多少次）。这个区别我在课上也讲了的。

李骏老师，感觉我遇到的问题并非和迭代器、生成器相关，疑似和`静态变量`相关（昨晚mixin上的好友帮我解答时感觉到的），我在此用3段代码及它们的输出来重新提问下：
第①段代码（取自教材中`class primes()`的一部分，它是我模仿的对象）：
```python
def __next__(self):
        n = self.next
        while not self._is_prime(n):
            n += 1
        self.next = n + 1
        return n
list(islice(primes(), 0, 10))
[2, 3, 5, 7, 11, 13, 17, 19, 23, 29]
```
第②段代码（它是我初次模仿的结果）：
```python
def primes():
    m = 2
    n = m
    while _is_prime(n):
        yield n
        m += 1
list(islice(primes(), 0, 10))
[2, 2, 2, 2, 2, 2, 2, 2, 2, 2]
```
第③段代码（它是我再次根据我想要的结果按照mixin好友解答的修改版本）：
```python
def primes():
    n = 2
    while _is_prime(n):
        yield n
        n += 1
list(islice(primes(), 0, 10))
[2,3]
```
问题：②、③2段代码的输出为什么会不一样？，（这一次，希望自己已经把问题表达的够清楚了。）感谢@李骏老师、@Jared-Gong

**Comment by Jared-Gong** [comment]
第②段代码中```while _is_prime(n):```里面的变量```n```永远都等于2呀，因为就赋值了一次，下次循环从```while```下执行，如果你把```n = m```放在``` m += 1```下面结果就一样了吧。
```python
from math import sqrt
from itertools import islice
def _is_prime(n):
        if n < 2:
            return False

        if n in (2, 3):
            return True

        for i in range(2, int(sqrt(n)) + 1):
            if n % i == 0:
                return False

        return True
 
def _primes():
    m = 2
    n = m
    while _is_prime(n):
        yield n
        m += 1
        n = m
print(list(islice(_primes(), 0, 10)))
```

**Comment by neolee** [comment]
这跟静态变量有啥关系……实际上我们没讲过也没用过这东西，我也不推荐使用这东西。

你的第1段代码是迭代器的写法，第2和3段是生成器写法，这咋模仿？

第3段代码的问题就是你的 while 循环写错了，@Jared-Gong 同学和我都说过了，你觉得有什么问题吗？

第2段代码我只能说很莫名，为啥弄出来一个 m 变量啊，循环体里对 m 加一，但是判断条件又是针对永远不变的 n，这是想做什么呢？

**Comment by xiaoerhai** [comment]
是的。感谢@Jared-Gong

李骏老师，是我把自己绕进去了，当时是用m变量模仿迭代器中的实例变量`self.next`来着，我过段时间再回来看这个问题应该会更容易理解。
感谢你们的帮助。
