### ISSUE TITLE
刚开始学，在准备“本地“的学习用书，使用jupyter的时候遇到了点麻烦，希望大家帮忙解答一下，谢谢

### ISSUE THREAD

**Issue by liukairan** [neolee/pilot#857]
就是图一这个步骤。
李骏老师视频里的步骤是图二这样的。
我的是图三这样的，也就是本地的这个文件夹里的学习资料的文件信息。
图四是我在学习资料所在的文件夹运行“jupyter lab "后的结果。也没有弹出本地的阅读网页。
额，跟着步骤来的，不知道哪儿出错了。该安装的东西也都按着步骤安装了。
![48193aeedfe93f08e6c206a333ff723](https://user-images.githubusercontent.com/53088513/71476196-d374d280-281e-11ea-9bec-509d48212009.png)
![efe9c25c81b01bf91f599f03cf45f18](https://user-images.githubusercontent.com/53088513/71476207-db347700-281e-11ea-9295-dee1dd13a5b0.png)
![29054ff73885c80ba4655dc01468906](https://user-images.githubusercontent.com/53088513/71476212-e25b8500-281e-11ea-9deb-24f04ef5b838.png)
![248139320843429350](https://user-images.githubusercontent.com/53088513/71476217-e8e9fc80-281e-11ea-95c9-1df296acfa0f.jpg)

**Comment by neolee** [comment]
感觉是 Jupyter Lab 没装完整。另外为啥截图不截完整了，左边漏了一列……

**Comment by liukairan** [comment]
> 感觉是 Jupyter Lab 没装完整。另外为啥截图不截完整了，左边漏了一列……

老师您是说前面那个绿色的（jupyter)吗？我就是不知道那个是怎么出来的，我的一进入就没有那个绿色的(jupyter)，我截图是截完整了的，您看下面都是对齐的。(不知道是之前哪一步出错了，要重新安装一遍jupyter吗？）
![680810607115620593](https://user-images.githubusercontent.com/53088513/71481036-3a05ea80-2837-11ea-97c6-614e5cf507f0.jpg)

**Comment by liukairan** [comment]
> 感觉是 Jupyter Lab 没装完整。另外为啥截图不截完整了，左边漏了一列……
> 
> 老师您是说前面那个绿色的（jupyter)吗？我就是不知道那个是怎么出来的，我的一进入就没有那个绿色的(jupyter)，我截图是截完整了的，您看下面都是对齐的。(不知道是之前哪一步出错了，要重新安装一遍jupyter吗？）

这张图片是老师您视频课上的，我自己的就是上面那张没有开头绿色（jupyter)的。

**Comment by neolee** [comment]
那个 `jupyter` 没关系，那是我用的虚拟环境，你不需要管它。

你的问题有可能是安装 Jupyter Lab 中间有问题，也就是执行 `pip install jupyterlab` 的时候有点问题。可以试试再运行一次这个命令，看看有没有什么错误出现。

**Comment by liukairan** [comment]
> 那个 jupyter 没关系，那是我用的虚拟环境，你不需要管它。
> 你的问题有可能是安装 Jupyter Lab 中间有问题，也就是执行 pip install jupyterlab 的时候有点问题。可以试试再运行一次这个命令，看看有没有什么错误出现。

![867001180048865124](https://user-images.githubusercontent.com/53088513/71481875-a9c9a480-283a-11ea-981c-c42fb193a86a.jpg)
![9225d6db5edd9b217d09aa3c41758af](https://user-images.githubusercontent.com/53088513/71481883-b4843980-283a-11ea-8ead-cba7dcdaf779.png)
是刚开始装错地方了吗？有点蒙。也麻烦老师这么晚了还帮忙解答疑惑。谢谢老师

**Comment by neolee** [comment]
为什么你装的 Python 是 3.8.1？我不确定这个版本是不是会有兼容性问题。如果你按照[配置指南](https://github.com/neolee/pilot/blob/master/x1-setup.md)严格执行的话，应该装的是 Python 3.7.4（也就是我的课程开发和测试的版本）。

**Comment by neolee** [comment]
建议你卸载 Python 然后重装：

```powershell
scoop uninstall python

scoop bucket add versions
scoop update
scoop install python37@3.7.4

pip install jupyterlab
```

**Comment by liukairan** [comment]
> 建议你卸载 Python 然后重装：
> scoop uninstall python
> 
> scoop bucket add versions
> scoop update
> scoop install python37@3.7.4
> 
> pip install jupyterlab

好的老师，我试试

**Comment by liukairan** [comment]
> pip install jupyterlab

谢谢老师！问题解决啦，可以用jupyterlab打开本地学习资料了。再次谢谢老师，大半夜的还帮忙解答。
