### ISSUE TITLE
关于模块化和接口独立

### ISSUE THREAD

**Issue by tsao86** [neolee/pilot#859]
很多想不通的地方。比如我们怎么把它生成模块的，存放在什么地方？接口独立又是怎么实现的？从哪里可以看到内置的所有函数，是不是人人都可以修改，各类接口人人都可以协同使用，又是如何保证不出现异常的？谢谢。

**Comment by xiaoerhai** [comment]
Q：我们怎么把它生成模块的？
A：如下，引用教材的内容；另外，我是用**Visual Studio Code**这个代码文本编辑器来完成.py 文件的（实际当中你可以谷歌到很多实用的编辑器）。
>你只要把 Python 源代码存成一个 .py 的文件，这就是一个模块（module），而这个文件的文件名（不含后缀 .py）就是模块的名字。

Q：模块存放在什么地方？
A：它就是一个文件，你可以按你学习的过程分类保存到你想保存的地方。我一般学到一个比较典型的代码块我就会取一个和它功能相关的名字保存在一个文档里面，比如：判断是否是素数的代码保存为`is_prime.py`的一个文件，这个**文件**就是上面说的**模块**。

Q：接口独立又是怎么实现的？
A：我的理解是：假如你要在你的代码里导入一个模块（Python 自带的也好、通过 pip install 命令安装的第三方模块也好、我们自己创建的模块也好），那这个时候，相对于你在当前编辑的代码里，导入的模块它就是独立的，你没法直接对它做任何操作，只能用它，它是否能正常使用只和它本身有关。（教材里举的例子好像是灯的开关，开关里复杂的线路好比是一个模块，我们在操作开关的时候不需要care里面乱七八糟的线路，只需要知道通过这个模块，我们直接操作开关就能控制灯的状态。）

Q：从哪里可以看到内置的所有函数?
A：这个我是通过官方文档找的：[内置函数](https://docs.python.org/zh-cn/3/library/functions.html),如果刚开始学的话，建议只需要大致了解下，此阶段没必要去记这些。要用的时候自然会记住它们的。

Q：python的内置函数是不是人人都可以修改？
A：我认为只有python 的人（有权限的人）才可以修改，内置的，应该也就是官方的吧。

Q：各类接口人人都可以协同使用，又是如何保证不出现异常的？
A：我认为，这里的【各类接口】，应该是指各类通用的模块吧，我感觉【接口】它是抽象的一个概念，并非是一个具体的东西。它背后就是各种模块吧，只要模块没问题，不管有多少人使用也是不会有问题的。

以上希望对你有帮助，后续你也可以补一下**第二部分 进阶篇 第三章 模块**

**Comment by neolee** [comment]
其实学编程是一个学习“如何学习”的很好实践。

学习中最重要的一个能力是：学会问问题。

我比较建议你先把你的问题进行一下梳理：有哪几个方面的问题，每个问题说清楚问题的来源（教材里的文字？某段代码？etc.），说清楚你希望取得的成果，以及你为之做了哪些努力，结果如何。

具体来说，从你的描述看，我猜你又两类不同的问题，一类是概念性的（理解问题），一类是操作性的（如何做）。这两类问题很不一样。

关于 Python 模块的问题，S2-3 这一章有很多内容，哪些理解上遇到问题？

关于“接口独立”，这个概念很不清晰，不太清楚你说的是指什么。如果是指概念分离，这是贯穿课程始终一直在讲的，教材和课程录播都可以反复学习。

**Comment by neolee** [comment]
对了，还有个把问题具体化的好办法，你可以看S1最后课程练习的视频讲解，跟着做，中间有什么启示和理解障碍？就这些具体的点进行学习讨论会更有收获。

**Comment by tsao86** [comment]
谢谢李老师和xiaoerhai的耐心回答。
