### ISSUE TITLE
在代码 cell 中输入 Python 代码并运行

### ISSUE THREAD

**Issue by bianka727** [neolee/pilot#86]
在代码 cell 中输入 Python 代码并运行是什么意思？代码cell在哪？我已经打开了jupyterlab

**Comment by neolee** [comment]
是的，你可以吧 `# 请在这里输入代码` 删掉，换成你自己照着教材输入的代码。

也可以点击 Jupyter Lab 左上的 + 号，选择 Python 3 来创建一个新的 notebook，然后在里面写代码。

勇敢地尝试，细心地拍错——这是学编程的一个诀窍。
