### ISSUE TITLE
关于 filter 函数乱试的疑问

### ISSUE THREAD

**Issue by Jared-Gong** [neolee/pilot#860]
```python
lst = [-2, -1, 0, 1, 2]
list(filter(lambda x: x if x >= 0 else 2 , lst))
[-2, -1, 1, 2]  #运行的结果
```
老师 我这里的想法是，把```lst```里面不符合条件的参数全部用2替换并输出，但结果不对，也想不通为啥会出现这样的结果，想请老师帮忙解答下，谢谢！

**Comment by neolee** [comment]
你误解了 `filter` 函数的作用，`filter` 用一个函数来处理每一个元素，处理结果如果是 `True` 就保留该元素，`False` 则滤掉该元素。

按照你定义的这个匿名函数，如果元素大于等于0则返回该元素本身，如果元素小于0则返回2。而所有整数，除了0都相当于 `True`，而元素为0时按照你的函数会返回0，也就是 `False`。所以你的函数过滤下来就是把0给滤掉了。

你想做的事情是吧小于0的元素都换成2，而大于等于0的元素保持不变，这不是对原序列进行过滤，而是一种处理替换，用 list compregensive 是最好的，大致可以这么写：

```python
lst = [-2, -1, 0, 1, 2]
print([x if x >= 0 else 2 for x in lst])
```

**Comment by Jared-Gong** [comment]
嗯嗯  是我理解错了，谢谢老师！
