### ISSUE TITLE
下载 Homebrew 时遭遇失败

### ISSUE THREAD

**Issue by FBY1101** [neolee/pilot#861]
老师，我 brew update-reset 后依然没解决问题，然后按照wiki里重装 homebrew ，再安装xcode-select --install 和 输入：/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"，安装之后显示

==> Downloading and installing Homebrew...
remote: Enumerating objects: 24, done.
remote: Counting objects: 100% (24/24), done.
remote: Compressing objects: 100% (18/18), done.
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
Failed during: git fetch origin master:refs/remotes/origin/master --tags --force

这是不是说我的网络有问题，需要再换个时间，换个网络？

**Comment by neolee** [comment]
对，这个是说网络问题。

**Comment by FBY1101** [comment]
> 对，这个是说网络问题。
谢谢李俊老师的解答，已经成功安装 Homebrew。

**Comment by Endlessfly-oss** [comment]
> > 对，这个是说网络问题。
> > 谢谢李俊老师的解答，已经成功安装Homebrew。

同学，是不是在没安装成功前都是需要重复/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"这个命令就行了？下载好了，但安装出了问题

**Comment by Endlessfly-oss** [comment]
> > > 对，这个是说网络问题。
> > > 谢谢李俊老师的解答，已经成功安装Homebrew。
> 
> 同学，是不是在没安装成功前都是需要重复/ usr / bin / ruby​​ -e“ $（curl -fsSL [https://raw.githubusercontent.com/Homebrew/install/master/install）”这个命令就行了？下载好了，但安装出了问题](https://raw.githubusercontent.com/Homebrew/install/master/install)%22%E8%BF%99%E4%B8%AA%E5%91%BD%E4%BB%A4%E5%B0%B1%E8%A1%8C%E4%BA%86%EF%BC%9F%E4%B8%8B%E8%BD%BD%E5%A5%BD%E4%BA%86%EF%BC%8C%E4%BD%86%E5%AE%89%E8%A3%85%E5%87%BA%E4%BA%86%E9%97%AE%E9%A2%98)问题已解决
