### ISSUE TITLE
关于命令行下载 MySQL 的网络问题

### ISSUE THREAD

**Issue by aosjiabei** [neolee/pilot#862]
心得分享：
1.软件大，而且超慢，科学上网也没用。增加了放弃概率。昨天我学手册里的数据库，下载
MySQL），搞得我心力憔悴（脆弱型强迫症），进度条就是不动，最后还失败了。

2.命令行下载中断了，有时候，你必须
把旧的文件删除，才能下载。新手不知道，增加了放弃概率

3.浏览器下载也有一个技巧，把链接复制到迅雷。一般情况会提速几倍。

总结：速度上——迅雷> 浏览器> 命令行

当然，第一先按教程来，第二根据自己的情况来。ps.以上的话面向-命令行上有网络问题和困扰的孩子，
●能用命令行的通通用命令行●。

不要因为挫折放弃，方法总比困难多，完成就好，不要纠结。

下面是迅雷下载法
![迅雷下载法](https://user-images.githubusercontent.com/48588326/71551768-de4f8300-2a29-11ea-9435-869d2d702bbd.png)

**Comment by neolee** [comment]
很多代理需要特定操作才能对命令行起效。

**Comment by aosjiabei** [comment]
> 很多代理需要特定操作才能对命令行起效。

scoop install aria2
我居然无意间发现了这个！！！试试感觉一下加速效果

**Comment by aosjiabei** [comment]
@neolee 老师好！谢谢老师。我都不敢相信自己把MySQL的实验做好了，而且我是MySQL8.0.  
您不知道，我一开始头皮发麻，怎么python学着学着学到了数据库，一下载软件感觉更复杂了。MySQL57缺少东西，所以下了8.
所以您的教程有的代码还要适当改改，不会改就百度（用google英语不好看不懂）
中途scoop又莫名其妙出现问题，命令行不识别scoop，都重装了两次。
哈哈，最后做完MySQL 和redis，果然好像打开了新世界。
谢谢charming的老师

**Comment by neolee** [comment]
你这个有点厉害，MySQL 8 改的不少，我都偷懒没敢动，一直用 5.x……
