### ISSUE TITLE
VS Code 运行代码提示 not defined

### ISSUE THREAD

**Issue by shujiaojunxiong** [neolee/pilot#863]
![图片](https://user-images.githubusercontent.com/53084501/71552152-f5926e80-2a31-11ea-9781-440bf3516d08.png)
老师你好

截图中的代码是我从教材p1-b-final.ipynb 中复制到VScode中的，shift+enter 运行后，就提示NameError: name 'Garfield' is not defined

为什么会这样呢？

我的理解是，已经创建了一个叫Garfield的类了，garfield = Garfield(1)是在创建这个类的实例对象，为什么系统会提示没有定义Garfield呢？

**Comment by neolee** [comment]
你需要运行整个文件而不是最后一行。

你前面的课程（包括录播和视频）都按顺序学了吗？

**Comment by shujiaojunxiong** [comment]
感谢老师回复。

感到惭愧，回去反省！

**Comment by neolee** [comment]
建议现在 Jupyter Lab 中学习编程的基本知识，按照顺序学习教材（本 repo）、讲课的录播、以及[视频课程](https://github.com/neolee/pilot/wiki/Video-Lectures)，视频课程里的支线课程第一第二讲最好先看看。

在 VSCode 中运行程序，最好的办法是打开一个 PowerShell Terminal（不是 Python），然后执行 `python <你的 Python 源文件完整路径>`。

**Comment by shujiaojunxiong** [comment]
非常感谢老师抽出宝贵的时间，对我做耐心地解答。

教材的第一部分内容我是只字不差的阅读和实操过（教材+学习用书Jupyter Lab）。
类和对象还有第一部分最终章，理解和运用起来较难，我至少反复看了3遍，虽然目前基本理解，可以依葫芦画葫芦了，但是感觉依然没有融会贯通，还需要多多练习，和自我创造。

因为我想尝试一下在VScode 运行整段代码，也可以作为独立文件保存，所以在VScode上尝试编码和运行。

我反思了一下本次的问题，主要可能是以下原因，可供其他学员参考：
1. 本人英语功底较差，程序界面很多功能不知道什么意思
2. VScode 软件功能操作不清楚，胡乱百度方法，没有理解意思（我想运行的是整个文件的代码，但实质上只运行了一行代码，导致报错）
3. 在没有清楚理解自己的操作的真正意思时，胡乱操作，导致归因错误

后续会继续跟着老师的教材认真学习！

**Comment by neolee** [comment]
学习 S1 最后的课程练习，最好的办法是看视频课程（前面我有贴视频课目录的地址，Wiki 里也有），照着做就好。

关于 VS Code，因为目前不是课程重点，我讲的不多，回头会录一个简单的视频，讲讲基本操作。

加油。

**Comment by shujiaojunxiong** [comment]
谢谢老师，我会认真学习！

已推荐我弟弟一起学习。
