### ISSUE TITLE
git commit 出错了，没找出什么原因

### ISSUE THREAD

**Issue by zhangshu-xiong** [neolee/pilot#864]
git add .输入git status查看正常
<img width="471" alt="批注 2019-12-29 173356" src="https://user-images.githubusercontent.com/53045404/71555016-bc71f280-2a61-11ea-8228-51220d358b6f.png">
git commit 出现错误提示，不知道是什么原因，如下图
<img width="688" alt="批注 2019-12-28 180620" src="https://user-images.githubusercontent.com/53045404/71555051-2f7b6900-2a62-11ea-832e-c1701167c2aa.png">
请老师指点

**Comment by neolee** [comment]
这个提示，可以猜想大概是这么个过程：

1. 你以前运行过 `git commit`；
2. git 打开了 vi（或者 vim）这个编辑器来让你输入提交信息（commit message）；
3. 你没有完成编辑保存就强行退出了 vi，可能是直接关了命令行窗口吧；
4. vi 会自动保存你之前没保存的临时文件，下次打开时就会出现你现在看到的提示。

vi（或者 vim）这个编辑器不推荐新人使用，我猜你碰到它会手足无措，连退出都不知道怎么退出。按照我们的 Git 教程，你需要用 `git config` 来设置你的提交信息编辑器，看来你没严格按教程来操作。

你现在需要退出截图里的界面，如果不知道怎么退出就按你以前做过的，直接关掉这个 tab 好了。

你可以删掉之前 vi 保存的临时文件（swp file，截图里有告诉你它的位置）。

最后就可以按照教程的指引设置 Visual Studio Code 作为你的 git 编辑器，再尝试 `git commit`。

**Comment by zhangshu-xiong** [comment]
#感谢老师的耐心讲解
>我猜你碰到它会手足无措，连退出都不知道怎么退出
*真是这样的*
vi（或者 vim）这个编辑器是我按照《自学是门手艺》安装在电脑上的，我以为电脑里有了就没按照老师的讲解重新安装。我从新做一遍看看

**Comment by zhangshu-xiong** [comment]
对了，老师这样应该怎么退出？

**Comment by liukairan** [comment]
我也是在运行git commit 的时候出现的类似的问题。我的提示是这样的。前面几步跟着视频做都是正常的。
![f2e79462b3e26fd468b12b3bffdbb5b](https://user-images.githubusercontent.com/53088513/71720227-e3626700-2e5b-11ea-9bc1-72d1a47657ea.png)

**Comment by neolee** [comment]
@liukairan 

你这不是题主一模一样么，看我上面的回复。
