### ISSUE TITLE
教材第一部分第十章 print语句后面' + str(x) + ' %,其中的+号是什么意思？

### ISSUE THREAD

**Issue by tsao86** [neolee/pilot#865]
<img width="529" alt="1" src="https://user-images.githubusercontent.com/49138260/71555500-0b228b00-2a68-11ea-9819-4a8e01da2949.png">

**Comment by neolee** [comment]
你猜呢？

**Comment by tsao86** [comment]
字符串值这一课讲到单引号''里面不可有单引号'',这个句子外面有一个单引号，我尝试去掉外面的单引号control+return返回是错误的；里面的单引号去掉也会出错，即使单引号前后的空格键去掉也会出错；我能联想到的就是C++,还请老师指点。

**Comment by neolee** [comment]
加号就是把前后两个字符串串起来呀。

**Comment by tsao86** [comment]
同一题，另外一个问题：
这个print语句用了一个大的单引号，里面的字符串函数也用了一个单引号，字符串值的单引号不能包含单引号,我试着把外边的单引号换成双引号，返回的值是一段文字，请老师解释下这种单引号里有单引号是什么情况下使用的，多谢。

**Comment by neolee** [comment]
这里并没有“单引号里面有单引号”的情况呀，`print` 里面是若干个字符串（有的是字符串值，有的是 `str` 函数的返回值）用加号串起来。你再仔细看看。

**Comment by tsao86** [comment]
我把简单问题复杂化了。多谢
