### ISSUE TITLE
关于素数迭代器的实现逻辑

### ISSUE THREAD

**Issue by Lilidandan321** [neolee/pilot#867]
```python
while not self._is_prime(n):
    n += 1
```

为啥 while 循环不是素数时才加 1 呢，是优化方法吗？有点难理解。我想的是循环前加1，然后把合适的素数调用出来就行了，但是又不太对。

![image](https://user-images.githubusercontent.com/53359222/71558017-74ff5c80-2a89-11ea-9718-477425d9cdcf.png)
![image](https://user-images.githubusercontent.com/53359222/71558023-7d579780-2a89-11ea-93c5-d97cfa75cae6.png)

**Comment by neolee** [comment]
首先，我改了你的问题的标题和描述，请你仔细学习，以后提问题不要把一大堆话都堆在标题里，也要学会如何用 Markdown 标签来让问题描述更容易读。

回到的你问题，这个 `__next__()` 的逻辑很简单：从上次找到的素数之后开始，找到下一个素数返回；既然是要找到下一个素数，那么自然是要略过所有不是素数的，这个 `while` 循环的目的就是“略过所有不是素数的数”，那么它的判断条件就不难理解了。

如果按照你那么去写，只要不是素数 `while` 循环就结束了，然后下一个素数在哪里还不知道，甚至也没有明确返回，那就等于返回了个 `None`……

另外可以参考下其他有关问题（搜索“素数”或者“迭代器”有不少）。

**Comment by Lilidandan321** [comment]
好的，谢谢李老师。
