### ISSUE TITLE
Push 文件到 GitHub 的问题

### ISSUE THREAD

**Issue by Maxuanrui** [neolee/pilot#868]
![image](https://user-images.githubusercontent.com/53324687/71558094-38803080-2a8a-11ea-9b05-2e9fecdddc2f.png)
push markdown文件失败，提示如图中所示**1**
搜索得知好像是需要设置一个SSH KEY密钥，输入`ssh ...`命令报错，提示如图所示**2**

**Comment by neolee** [comment]
一直强调要用 https:// 打头的那个 clone 地址，不要用 git@ 打头的那个，后者需要你有 SSH 的环境，在 Windows 下就颇为麻烦。
