### ISSUE TITLE
关于教程整体设计安排

### ISSUE THREAD

**Issue by RayOng666** [neolee/pilot#869]
李老师，python课程的计划是多久全部推出？
能透漏下后续几章的主题吗？

**Comment by neolee** [comment]
S2 结束后主要是几个实例案例，和一份给大家的“编程世界漫游指南”。

**Comment by spring-ap** [comment]
老师，你可以设置个会员制，然后我们交年费订阅，服务项目是帮助解决编程中的疑难杂症，有些问题互联网不好找到答案的，不过这个年费是不是会很贵啊？

**Comment by RayOng666** [comment]
> S2 结束后主要是几个实例案例，和一份给大家的“编程世界漫游指南”。

这么说基础知识点已经结束了，是吧。
后面实例分别是什么方向？
预计全部完结还要多久？

**Comment by neolee** [comment]
@RayOng666 S2 还在进行，还有好多内容没讲呢，你自己看完了也不算就真的学完了吧？至于时间，为啥这么关注还有多久呢？

@spring-ap 未来的模式需要相应的产品支持，还要些时间，成熟了会跟大家说的。

**Comment by RayOng666** [comment]
> @RayOng666 S2 还在进行，还有好多内容没讲呢，你自己看完了也不算就真的学完了吧？至于时间，为啥这么关注还有多久呢？
> 作为资质欠佳的普通中年男，平时能够切分出来的意志力、时间、精力非常有限。所以对一个小事项，我很自然的会关注目标和效率。
对于学python，可能您在教以及我个人在学的时候，这两者间的目标并不一致。学会、精通并不是我的目标。我的初步目标是3个月了解，能读懂小型代码的逻辑，在简单指导下能运行别人的代码，能和程序员比较快的建立基本的沟通，为进一步学习埋种子。
我通常的学习习惯是通篇了解结构，抓重点，再补充细节，所以想对课程整体的章节结构有所了解，以便有所侧重。
在我接触的几个pyton课程里，您的课程细节、落地性比较强，现在是我的首读课程。但是如果时间跨度过于久，我要根据您的计划调整‘追剧’安排，会先切换别的课程。所以跟您了解下预计的时间跨度。
上面是我个人情况和想法的说明，没有冒犯的主观想法，希望您能理解。
也感谢李老师对我们所有人的劳动付出。

**Comment by neolee** [comment]
@RayOng666 好的，搞清楚你问题的内在动机有助于我避免“答非所问”。

践行群的同学们，基础和学习目标差异都很大，所以管理教学节奏不容易，我也还在摸索，几点信息和建议供你参考：

1. 按照目前的节奏，S2 的课程大约还需要 6 周左右；
2. S2 结束后其实基本内容就完成了，之后我会讲几个比较大一点的实战案例，以及一个“编程世界漫游指南”，主要是希望启发大家找到自己后续的兴趣和方向，以及在独自上路探索之前准备一些必备的“生存工具”；这部分可以看做完全是 optional；
3. 目前自学教材（以及学习用书）、课程讲解、视频课这几条线是既有关联又相对独立推进中，这其实给了每个人一定的学习弹性，有的同学比较性急也比较有时间，所以老早就自学完了所有 S2 的课程，然后在这里问问题和交互，这种学习模式完全有可能比“官方进度”快很多完成整个课程；
4. 目前在践行群中的尝试目标并不是教人精通编程，而是给人一个对编程的正确认知，并且提供一个机会让大家能接触到真正一流的编程思维，在与这个思维的交互中可以判断自己是不是真的喜欢编程，或者适合编程。

**Comment by RayOng666** [comment]
@neolee 谢谢老师详细回复，目前我的确还没有太清晰的概念和兴趣方向，还需要补充学习更多内容。
课程里经常能感受到老师提到的一些思维和习惯，为你的无私分享点赞！这种内容在任何科目里都属于非常重要宝贵的部分，也是一流选手和普通选手的关键区别。
