### ISSUE TITLE
安装 Homebrew 到这一步就不动了

### ISSUE THREAD

**Issue by a13500608277** [neolee/pilot#871]
安装brew到这一步，就不动了

硬件：MAC

到这步就不动了，关闭终端后，再安装，也是卡在这步没反应

![53364167-FB72-45C9-9856-98DA2F9F1092](https://user-images.githubusercontent.com/23495897/71579545-0c22ed80-2b38-11ea-9bdb-427147e9bca5.png)

**Comment by neolee** [comment]
网络问题。

**Comment by wcswyw** [comment]
请问老哥，你这个网络问题解决了吗？可以请教下怎么解决的吗？
