### ISSUE TITLE
homebrew安装后，执行brew update，然后再执行brew doctor，出现以下界面，不动了

### ISSUE THREAD

**Issue by czzzy163** [neolee/pilot#872]
homebrew安装后，执行brew update，然后再执行brew doctor，出现以下界面

![截屏2019-12-3022 20 48](https://user-images.githubusercontent.com/30390167/71585982-6da48580-2b53-11ea-8da4-ff46b006078f.png)

**Comment by czzzy163** [comment]
czzzy@abeeMBA ⮀ ~ ⮀ brew update
Already up-to-date.
 czzzy@abeeMBA ⮀ ~ ⮀ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or
https://developer.apple.com/download/more/.

 ✘ czzzy@abeeMBA ⮀ ~ ⮀

**Comment by neolee** [comment]
这个 warning 可以无视，继续安装其他东西就好了。

**Comment by czzzy163** [comment]
好的，谢谢！
