### ISSUE TITLE
关于 Python 封装的问题

### ISSUE THREAD

**Issue by python-yuanweiyu** [neolee/pilot#875]
李老师，我写了个python小程序，统计一段文本中词频最高的词，我想给同事用，下一步应该怎么做呢，是不是牵扯到封装的问题？他只要有一段文本，就可以输出结果。但是我不可能给他搭建python环境，下一步我需要学习的知识应该是哪方面的，我理解是得做出一个界面，把这段代码封装进去，然后生成个exe文件，他直接运行，在界面下选择自己的文件，点执行就可以看到结果。
```python
import jieba
from collections import Counter

with open('c:/life.txt','r') as f:
    word2019 = f.read()
    # print(word2019)
words = jieba.cut(word2019)
cn_char= []
for char in words:
    if len(char)>1:
        cn_char.append(char)

print(Counter(cn_char).most_common(100))

f = open('d:/life-2019.txt','w')
for i in Counter(cn_char).most_common(100):
    f.write(str(i)+'\n')
f.close()
```

**Comment by neolee** [comment]
这个问题看似简单，其实挺复杂的，因为包含了不同层次的几个问题，所以我们最好先做下分解。

1. 从程序层面，如何把一个功能封装成产品。

这里面最关键的是做程序的“功能性封装”，比如你这段程序能够读取一个文件，统计里面的词频，但要想让别人也能用，就要想清楚“什么是输出什么是输入”。

从你的程序来看，输入可以是一个文本文件，也可以是一个文本文件的路径，也可能是一个文本流，这就要看你怎么设计它的使用场景了。

至于输出，可以是命令行标准输出，也可能是做个 GUI 窗口来显示结果，也可以输出成一个文件。

所以你要把这个程序看成一个黑盒，以用户的视点来看，输入是什么。输出是什么，然后改写程序，让它可以从输入产生输出——把它封装成一个函数，有明确定义的输入和输出。

2. 确定用户交互模式。

所谓用户交互模式，就是用户怎么把输入给你，又怎么获得输出。一般常见的有命令行模式和 GUI 模式，还有 Web 服务模式。根据你选择的模式，就需要使用不一样的服务——也就意味着你要学习不同的技术。

如果你选择命令行交互模式，我们的课程里已经有不少可用的东西，用 `input()` 来获取用户输入，用 `print()` 来输出结果；还可以自己学习一下如何给 Python 程序添加命令行参数支持（比如用 `python count.py myfile.txt` 来统计 myfile.txt 文件里的词频），如何用 Python 读写文件（这个你应该已经会了）。

如果要做个图形化界面，那就要学习 Python 的 GUI 库，比如 PyQt 一类的东西。

如果要做成 Web Service，那就要学习 Web 和 Web Service 相关的知识以及选择一个 framework 来用——这个我们以后会讲。

3. 如何在一个目标客户系统上安装并运行你的程序，这个行话叫“交付部署（deliver and deploy）”。

这也是个很复杂的问题，跟你选择的用户交互模式也有关系，但总的来说就是要把一组文件打包，然后在客户的机器上可以方便地安装和配置，然后运行起来。目标客户机器情况可能很复杂，不知道会遇到什么问题，所以需要多测试。

如果你只是想试着把 Python 程序编译打包成一个 Windows Exe 文件看看，可以参考[这篇文章](https://stackoverflow.com/questions/49831163/compile-python-3-6-script-to-standalone-exe-with-nuitka-on-windows-10)。

**Comment by python-yuanweiyu** [comment]
谢谢李老师的详细解答，真是越学不懂的越多！
新年即将到来，祝李老师新年快乐，身体健康。
