### ISSUE TITLE
关于苹果 Homebrew 的网络问题

### ISSUE THREAD

**Issue by Endlessfly-oss** [neolee/pilot#876]
你们说的套一个代理是不是需要购买SSL证书的意思？意思是将http转换为https吗？

**Comment by neolee** [comment]
不是，是指 proxy 或者 VPN 一类。

**Comment by Endlessfly-oss** [comment]
> 不是，是指proxy或VPN一类。

好的，谢谢！网络问题解决了，换了个时间换了个网络，用手机仅有两格信号的4g网络下载完的。

**Comment by neolee** [comment]
哈，不少同学用这一招搞定了。

**Comment by Endlessfly-oss** [comment]
环境配置完毕，网络畅通很重要
