### ISSUE TITLE
关于 dict 的 get() 和 setdefault()

### ISSUE THREAD

**Issue by xiaoerhai** [neolee/pilot#877]
为什么 dict 的 get() 函数和 setdefault() 函数是同样的作用？可以理解为重复造轮子吗？

**Comment by neolee** [comment]
先问是不是，再问为什么。

`dict.get(key, defaultvalue)` vs `dict.setdefault(key, defaultvalue)`

这俩方法看上去确实差不多，输入和输出都一样，但有个巨大差异：`get()` 不会改变 `dict` 的内容，而 `setdefault()` 是有可能改变 `dict` 内容的。

当 `dict` 不包含 `key` 的时候，`get()` 简单的返回 `defaultvalue` 就完事了；而 `setdefault()` 不仅返回 `defaultvalue`，还会在 `dict` 中插入新的数据 `{ key: defaultvalue }`。

`setdefault()` 做的这个事情，技术上称为一种“副作用”，英文是 *side effect*，简单说，就是函数在返回值以外做的事情，副作用有时是不得已的，但它是会降低程序的可维护性的——我们在 S2 最后一章会深入讲这个概念。

这个差异可不 trivial。因为在程序中最重要的是“数据”，而谁只能读数据、谁能改数据是非常敏感的，如果一段本不该修改数据的程序却意外地修改了数据，往往带来很多麻烦，而且找到这样的问题很耗时。

设计程序时经常是以数据为中心的，针对特定的数据，我会把程序代码分成“数据的维护和管理者”和“数据的使用者”，使用者通常是不能修改数据的，它只能读。

回到 `get()` 和 `setdefault()`，如果你的程序不能修改 `dict`，你最好用 `get()`；如果你可以修改 `dict`，并且知道自己在做什么，才可以用 `setdefault()`。

**Comment by xiaoerhai** [comment]
感谢李骏老师耐心解答，受益匪浅~
