### ISSUE TITLE
类class里面定义方法

### ISSUE THREAD

**Issue by wangnanqiang** [neolee/pilot#879]
类class里面定义方法，为啥def  niubi(self,dajia):里面一定要给一个位置参数，不给为啥提示错误，给dajia一个赋值了一个1，主要是啥用。
![图片](https://user-images.githubusercontent.com/53247740/71625479-035b1600-2c23-11ea-8e9b-aa2c68e6659f.png)

**Comment by neolee** [comment]
不太明白，什么情况会出错？出什么错？

**Comment by wangnanqiang** [comment]
可以了，是我自己问题，粗心了，谢谢老师
![图片](https://user-images.githubusercontent.com/53247740/71625921-68177000-2c25-11ea-8425-28f0be0e64e4.png)
