### ISSUE TITLE
安装 git 时出现“拒绝访问”和“Can't shim '7z.exe'” 错误

### ISSUE THREAD

**Issue by Cathleen1520** [neolee/pilot#88]
安装git 最后找不到对应的文件？请问怎么办

![微信图片_2019102517565](https://user-images.githubusercontent.com/56999107/67564405-6fb62680-f755-11e9-8a2a-96298896ade3.jpg)

**Comment by neolee** [comment]
注意到你的截屏中，执行 7zip 安装时出现了一个“拒绝访问”提示，应该 7zip 就没安装成功，具体原因不明，但此后 git 自然也没安装，其他都无法继续了。

你可以用文件浏览器看看 `C:\Users\qsy\scoop` 这个目录是否存在，下面的 apps、shims 等子目录是否都有，你是不是可以打开这些目录访问。

**Comment by Cathleen1520** [comment]
谢谢老师，
按照您的方法查看了下，文件都有，可以访问。
![微信图片_20191025191553](https://user-images.githubusercontent.com/56999107/67567096-e6562280-f75b-11e9-8cd9-0f0d6c7ce768.png)
![微信图片_20191025191558](https://user-images.githubusercontent.com/56999107/67567114-efdf8a80-f75b-11e9-8a39-1fa466aa798c.png)

下一步我可以怎么操作么？
谢谢额

**Comment by neolee** [comment]
执行一下 `scoop list`，看看里面有什么，如果有 7zip 的话，执行 `scoop uninstall 7zip`，然后重试一下：

```powershell
scoop install git
```

**Comment by Cathleen1520** [comment]
谢谢Neolee老师，
我又有一个问题，安装git后， Scoop update 失败了您能看出是啥原因么？
![微信图片_20191028101453](https://user-images.githubusercontent.com/56999107/67647063-d6149200-f96b-11e9-8bb7-c9dce74e350b.png)
Thanks

**Comment by neolee** [comment]
后面这个是网络问题，多试几次，最好换网络或者挂代理试试。
