### ISSUE TITLE
int(input()) 这个嵌套函数应该怎么理解？

### ISSUE THREAD

**Issue by ZhangKaiHua-CW** [neolee/pilot#880]
研究了好久 int(input('Please enter a number') 这个嵌套函数依然让我很困惑，一直卡在这里：

int() 返回值是整数，如果是int('34'),返回值是整数34，这个能理解，int()只能做整数转换；
如果是int('Please enter a number'),会报错，我也能理解，因为 Please enter a number 不是整数；
然而，input('Please enter a number')的返回值是字符串Please enter a number，返回值不是整数，为什么没有报错呢？
我想了解一下我是对哪一块或者哪些方面的定义没有搞明白。

谢谢

**Comment by neolee** [comment]
> input('Please enter a number') 的返回值是字符串 Please enter a number

这里理解错了，请复习或者检索 `input()` 是干啥的。

**Comment by ZhangKaiHua-CW** [comment]
谢谢李老师，终于算是搞清楚了。input（）这个函数括号内的是提示语，不是返回值，提示语可以是空；它的返回值需要键盘输入，然后将其作为字符串返回，也就是说它的返回值是字符串。

这里有个新概念“键盘输入”不是很清晰，从字面上理解，返回值是通过键盘输入没有问题，提示语不也是通过键盘输入的吗？
