### ISSUE TITLE
Redis 环境准备进行到在 service 中启动 Redis 服务这一步出现错误 5

### ISSUE THREAD

**Issue by ds-dog** [neolee/pilot#881]
#740 中我也出现了同样的问题，解决办法是：双击redis进入界面，在登录栏中将账户从网络更改成本地即可启动。后面一切正常，不知道这样有没有问题？

**Comment by neolee** [comment]
噢！这个我都不知道，可能是个有效的方案……

**Comment by qixinsame** [comment]
遇到了相同的问题。题主的方法亲测有效
