### ISSUE TITLE
运行n=42;id(n),教材与学习用书返回值不一致

### ISSUE THREAD

**Issue by powerzhengh** [neolee/pilot#882]
教材
![001捕获](https://user-images.githubusercontent.com/58015512/71640454-479ef280-2cc5-11ea-95c6-7d46b68ea152.PNG)
学习用书
![002捕获](https://user-images.githubusercontent.com/58015512/71640458-4bcb1000-2cc5-11ea-93e9-f52f0689392b.PNG)

**Comment by neolee** [comment]
参考 #822
