### ISSUE TITLE
"cd pilot-student“ failed

### ISSUE THREAD

**Issue by Cathleen1520** [neolee/pilot#885]
![image](https://user-images.githubusercontent.com/56999107/71648746-3b597a80-2d43-11ea-9230-be8299d8dc1a.png)
![微信图片_20200102093656](https://user-images.githubusercontent.com/56999107/71648759-84a9ca00-2d43-11ea-98c6-81247ee5f5c0.png)
老师好，
请问我在设置配套用书时最后一步失败

**Comment by neolee** [comment]
截图不完整，尤其是缺少开始部分，都没法知道是在执行什么命令时出的错，其他就更难判断了。

不过看着像是在下载安装什么东西（`pip install`？），出错提示是网络问题。

至于题目中说的 “cd pilot-student” 出错，不知道是什么意思。

以后问问题最好说清楚，你学习了哪些资料（教材、课程、视频等），然后做什么的时候出问题，出了什么问题。
