### ISSUE TITLE
在 git push -u origin master 时无法访问

### ISSUE THREAD

**Issue by FBY1101** [neolee/pilot#886]
跟着老师在B站学习Git的使用，在实践到第三个视频“Git和GitHub基本操作”时，
按照Git上的指令git push -u origin master，
得到403错误提示：
fatal: 无法访问 'https://github.com/FBY1101/learn-git.git/'：The requested URL returned error: 403
在网上找了几个解决办法都没能改变，在这里麻烦李俊老师了，谢谢！

**Comment by neolee** [comment]
你执行下面命令的输出是什么：

```powershell
git remote -v
```

**Comment by FBY1101** [comment]
> 你执行下面命令的输出是什么：
> 
> ```powershell
> git remote -v
> ```

origin	https://github.com/FBY1101/learn-git.git (fetch)

**Comment by FBY1101** [comment]
是这样的：
origin	https://github.com/FBY1101/learn-git.git (fetch)
origin	https://github.com/FBY1101/learn-git.git (push)

**Comment by FBY1101** [comment]
而且我现在检测python版本时，也不会显示3.7.4这类的版本号，而是：
# installing zipimport hook
import zipimport # builtin
……

**Comment by neolee** [comment]
你有没有严格按照这个 [指南](https://github.com/neolee/pilot/blob/master/x1-setup.md) 完成环境的准备？

**Comment by FBY1101** [comment]
是按照指南一步步安装的，只有最开始安装brew时遇到一些问题，在向老师请教后成功解决，除此之外再没遇到什么问题了，发出指令和得到的反馈都和老师在指南的一样。只有在学支线课程时，遇到这种情况。是否需要把python删除，重新安装呢？但我查了几个删除的方法，第一步都是要查看version。。。

谢谢老师。

**Comment by neolee** [comment]
你这个问题和 Python 无关，是 git 访问 GitHub 时出现权限问题。

**Comment by FBY1101** [comment]
按照老师对我问题的描述，我找到了解决的办法，谢谢李老师！
