### ISSUE TITLE
 index() 与 rindex() 有时灵验，有时不灵？

### ISSUE THREAD

**Issue by ygrdkl** [neolee/pilot#888]
![rindex(sda)问题](https://user-images.githubusercontent.com/31388214/71669192-d2a3e980-2da6-11ea-8ed6-3dabf747c1ec.png)

**Comment by neolee** [comment]
这两个结果很正常啊，你认为应该是怎样的结果才对呢？

**Comment by ygrdkl** [comment]
s.rindex('string')按照仿照应该是倒过来数的，不应该是4啊，下一句，s.rindex('sda')显示数据是24，这是对了。。。

**Comment by neolee** [comment]
第一个为啥不是4，你觉得应该是多少？

**Comment by ygrdkl** [comment]
应该是21，倒过来数吧

**Comment by ygrdkl** [comment]
![string问题](https://user-images.githubusercontent.com/31388214/71673876-d8a0c700-2db4-11ea-8f5e-d05b5e97fe1b.png)

**Comment by neolee** [comment]
如果按照你这个理论，为啥你觉得第二个 24 是对的呢，那明显也不对呀。

`rindex()` 是从右边开始向左寻找匹配的子串，找到之后返回的是匹配子串**开始位置**的下标。

**Comment by ygrdkl** [comment]
我的第二张图s.index('string')，正确答案应该是10 和43，但在仿的时候，两个参数对应不上，是10 和10，我就纳闷了。。。，我也知道这两个参数是相反操作的，不知道哪里出错了，换了一个自己随手写，就对了（在第一张图）

**Comment by neolee** [comment]
你理解我说的 `rindex()` 的记住了吗？然后再仔细核对下你的几个例子，就知道了。

另外，开始学的时候，测试例子不要像这样，太长太复杂，连你自己都容易数错，误导自己的判断。可以用短一点，测试目的性更强的例子。

**Comment by ygrdkl** [comment]
好的，我还是稍微稳一点。
