### ISSUE TITLE
下载的 Python 显示是 3.7.3 影不影响后面

### ISSUE THREAD

**Issue by TheTreeTree** [neolee/pilot#889]
<img width="375" alt="截屏2020-01-03下午2 53 31" src="https://user-images.githubusercontent.com/50830915/71710769-d1230180-2e38-11ea-8f80-5be1a0e2ed79.png">

**Comment by neolee** [comment]
仅仅从 Python 版本来说没啥问题，但是你这个版本说明肯定不是按照课程的环境配置指南做的，所以我没法保证你这个环境是不是在后面会遇到问题。

总的来说我的建议是，要么你很熟悉了解你的系统，那么其实怎么做都没啥问题；要么就严格按照配置指南来做，这样出现问题的时候大家比较可能帮得上。

**Comment by TheTreeTree** [comment]
@neolee 是按照环境配置指南弄的，上一步安装brew的时候弄了很久都不行，显示网络问题，然后今天练了自己的手机热点解决的了brew的安装。

之后安装python也是按指南的代码输进去的。
显示3.7.3

**Comment by neolee** [comment]
绝无可能。按照指南安装，在 macOS 下 Python 应该是 3.7.6。

**Comment by TheTreeTree** [comment]
@neolee 我是最近买的macbookpro ，以前有台macmini，那个时候是按照流程全部都装好了的
我有试过用迁移助理把原来的macmini文件转到，macbook。但是没转多久，我嫌速度太慢，就终止了。
难道是这个。。有文件的残留影响了。。

**Comment by neolee** [comment]
除非你以前的环境就配置的很好很干净，否则没啥必要 transfer，从头弄个干净的系统多好。

**Comment by TheTreeTree** [comment]
我继续从brew update这步开始重新弄了，现在显示是3.7.6了。重新安装的python会覆盖之前的版本吗？还是都在？

**Comment by neolee** [comment]
如果都是 Homebrew 装的，那么只有最新的会激活，清除老版本可以用 `brew cleanup`。如果是其他办法装的，那就没谱了，当初咋装的咋清理。
