### ISSUE TITLE
执行 scoop install git 出现无法对参数“FilePath”执行参数验证的错误

### ISSUE THREAD

**Issue by jiu-jinwen** [neolee/pilot#89]
![QQ图片20191025191345](https://user-images.githubusercontent.com/56920623/67566969-98411f00-f75b-11e9-8bc7-d74ef0ece56b.png)

**Comment by neolee** [comment]
试试先运行 `scoop update innounp -f`

然后再试 `scoop install git`

另外还有下面这个命令最好也执行一下：

`Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1`

**Comment by jiu-jinwen** [comment]
老师，运行之后这样了，按照scoop checkup之后的建议操作
![4](https://user-images.githubusercontent.com/56920623/67574712-8b2d2b80-f76d-11e9-9f82-f57d0d8e05f3.png)
![2](https://user-images.githubusercontent.com/56920623/67573820-d0e8f480-f76b-11e9-948c-a6167d374f6a.png)
![3](https://user-images.githubusercontent.com/56920623/67574383-ed396100-f76c-11e9-8307-91591b4876ad.png)
![5](https://user-images.githubusercontent.com/56920623/67574801-b9ab0680-f76d-11e9-8975-072982c78793.png)

**Comment by neolee** [comment]
你的系统里问题好像比较多，你是什么版本的 Windows？

按照 [Wiki](https://github.com/neolee/pilot/wiki) 中的指引重装 Scoop，执行下面几个命令，每一个不成功不要试下一个，然后把结果完整地截屏发过来：

```powershell
cd
del .\scoop -Force
Set-ExecutionPolicy RemoteSigned -scope CurrentUser
iwr -useb get.scoop.sh | iex
```

**Comment by jiu-jinwen** [comment]
![1](https://user-images.githubusercontent.com/56920623/67576544-56bb6e80-f771-11e9-8e92-8502174845ef.png)
电脑是win10的版本

**Comment by jiu-jinwen** [comment]
![2](https://user-images.githubusercontent.com/56920623/67577308-c8e08300-f772-11e9-8b7c-77280260568f.png)

**Comment by neolee** [comment]
下载 Scoop 安装包时出现网络问题，需要重试最后那句。也可以试试别的网络或者代理。

**Comment by jiu-jinwen** [comment]
好啦，这次是显示安装成功了，谢谢老师！
