### ISSUE TITLE
Visual Studio Code 不让安装

### ISSUE THREAD

**Issue by TheTreeTree** [neolee/pilot#890]
<img width="532" alt="截屏2020-01-03下午3 02 50" src="https://user-images.githubusercontent.com/50830915/71711047-1dbb0c80-2e3a-11ea-8e14-a12226678138.png">
<img width="375" alt="截屏2020-01-03下午3 03 35" src="https://user-images.githubusercontent.com/50830915/71711067-39beae00-2e3a-11ea-91f5-72262f40ba77.png">

**Comment by neolee** [comment]
你有把 Visual Studio Code 拖到 Applications 目录里吗？

**Comment by neolee** [comment]
我试了下，好像最新版本的 VS Code 的开发者签名有些问题（不知道是不是过期了），所以运行时会出你看到的提示，可以打开你的系统设定 -> 安全和隐私，第一个 tab，在下面点允许打开的按钮：

<img width="780" alt="VSC" src="https://user-images.githubusercontent.com/24796/71719511-8f568300-2e59-11ea-86bd-19cce9090d78.png">
