### ISSUE TITLE
确认 PowerShell 版本后安装 Windows Management Framework 5.x 时出现错误

### ISSUE THREAD

**Issue by xiao-sky** [neolee/pilot#891]
提示“安装程序遇到错误：0x80240037"    
我的电脑是windows 7   64位。
在命令行界面输入 $PSVersionTable.PSVersion.Major ↩︎。
上面的命令返回为 2

**Comment by neolee** [comment]
系统实在太老了。事实上现在 Windows 7 已经 EoL 了，就是微软不再提供维护了。

建议升级系统。
