### ISSUE TITLE
容器里的局部变量和全局变量的代入求解 不太理解

### ISSUE THREAD

**Issue by Erika00** [neolee/pilot#892]
![f099146fa41e7842045fc147ebc3723](https://user-images.githubusercontent.com/52418630/71725347-7f956980-2e6e-11ea-92f3-88ff30b00b34.png)
不理解的是 :modify (l) 打印的结果是 [0,100,2,3]，条件只说修改了l[1]=100,而没有说增加3，增加3是append(l)的方法，为什么modify (l)结果打印出来是 [0,100,2,3]，而不是[0,100,2,]
李老师，您帮我看看，我漏掉了哪些因素？

**Comment by neolee** [comment]
因为前面运行完 `append(l)` 之后 `l` 就变成 `[0, 1, 2, 3]` 了呀。

**Comment by Erika00** [comment]
李老师 我绕不出来，append(l) 运行之后l变成[0, 1, 2, 3] ,就直接用这个l当全局变量？
那原来的全局变量l= [0,1, 2]就不能再带入modify(l)求解是吗？

**Comment by neolee** [comment]
我在最新的支线课程里讲了用 Visual Studio Code 里单步调试 Python 代码的方法，你可以试试，观察每一步之后全局变量 l 的值。

另外这个例子我在上周的课上也做了详细解释，看你的问题，似乎你没上课？

**Comment by Erika00** [comment]
噢哦，我回头把课补上
