### ISSUE TITLE
Jupyter Lab 自建文件无法显示测试结果

### ISSUE THREAD

**Issue by ygrdkl** [neolee/pilot#895]
![jupyter lab 问题](https://user-images.githubusercontent.com/31388214/71764464-289d9c00-2f23-11ea-8f1a-a98e25a14495.png)

**Comment by neolee** [comment]
你运行 Jupyter Lab 的命令行界面上有什么提示么？

如果在这个界面上选择重启 kernel，再试可以吗？

**Comment by ygrdkl** [comment]
使用kernel就好了，原来重启jupyter lab没有用，这个平台的各种用途，还没研究过。。。谢谢老师
