### ISSUE TITLE
基类（self）问题

### ISSUE THREAD

**Issue by ygrdkl** [neolee/pilot#896]
为啥在如图最后一句print（）内，要写上self.think()，而不是直接print（think（）），调用函数不是正常的么？想不通为什么要加self. 。

![20 1 4 基类Bot，self问题](https://user-images.githubusercontent.com/31388214/71765006-fba0b780-2f29-11ea-8e7a-3c942a7f16bb.png)

**Comment by neolee** [comment]
因为 `think()` 是一个类的方法，不是一个普通的函数；类中定义的方法就要用 `对象.函数` 这种方式来调用；而在类定义里你还不知道是什么对象，就用 `self` 就是对未来实例化对象的引用。

这就是这个语言的语法。

**Comment by ygrdkl** [comment]
我还得听下，前面的音频，对方法，对象，实例化对象，概念还是一知半解。李老师，在群内的音频可以转化成文字，放到这个平台上么，有些东西必须反复听才有感觉。
