### ISSUE TITLE
属性错误

### ISSUE THREAD

**Issue by dingkunpeng** [neolee/pilot#897]
我用的是python3.7.0,在列表章节中,运行下列代码时出现错误,怎么回事?

![Snip20200104_2](https://user-images.githubusercontent.com/24670493/71765927-26443d80-2f35-11ea-9337-5bfbb6741d1c.png)

**Comment by neolee** [comment]
你这个 fruits 为啥是 str 类型，教材里是 list 呀？

**Comment by neolee** [comment]
为何不在这里简单的回复而要新开一个 issue？

请在这里回复。

**Comment by dingkunpeng** [comment]
抱歉,第一次回复弄错了
