### ISSUE TITLE
类似Typeform/麦客/问卷星的在线信息收集系统(答题系统)，并自动生成报告

### ISSUE THREAD

**Issue by wessyde** [neolee/pilot#898]
需求：
李老师，我在工作中有这样的需求，我做管理咨询的，经常要对客户公司的员工做调研或测评，工作量不小，想制作一个类似Typeform/麦客/问卷星这种在线信息收集系统，让每个员工答题，并需要根据答题结果给每人出具一份测评报告。

步骤分解：
1. 在数据库中导入现有的各种题库（题库未来可能持续增加题）；
2. 根据客户需求，从不同题库选题，生成问卷（选择题）；
3. 发送问卷至公司全体中高层员工（或在员工群里发链接二维码）；
4. 员工答题并提交；
5. 根据结果按照既定格式给每人出具一份测评报告，写入word/pdf文件，发送每人（测评报告：针对答题结果进行打分，并在每组/类测评项后写一段评语）

抱歉：第一次发issue，没加on-demand label

**Comment by neolee** [comment]
客观的说，这个需求属于相当复杂的商业应用，可以说是相当不简单的，自己做远不如使用成熟的服务。

不过作为对自己的思维和动手练习，倒是可以试试做个简单的。

**Comment by wessyde** [comment]
是的，真正做到应用级别，这个调研/测评过程中的场景较为复杂，目前是想做个简单的作为练习。

**Comment by neolee** [comment]
这要看这个报告要做成啥样子了，如果一般的统计应该不难，可以咨询下问卷星一类的；如果要很深入和个性化的，恐怕要找咨询服务了。

**Comment by wessyde** [comment]
明白了，报告的场景确实比较复杂
