### ISSUE TITLE
S1 课程练习中 run 方法的问题

### ISSUE THREAD

**Issue by ygrdkl** [neolee/pilot#899]
写完_say函数后，在修改run程序时，图中的灰色块状处的self.q未填入，程序也能顺利运行，那么self._say(),是否无所谓调用内部参数？不写也没关系吧？
![20 1 4 self q问题](https://user-images.githubusercontent.com/31388214/71767873-079d7100-2f4c-11ea-86df-55beba945d9c.png)

**Comment by ds-dog** [comment]
这里不写的话应该只是那个时间的模块没有实现吧，也就是没有暂停1秒再反应，你可以把wait设为5试试看。另外，一个函数里只有默认有缺省值的参数不写没有影响吧（argument with default value)，具体可以学习s2第一部分的内容~

**Comment by ds-dog** [comment]
这里不写应该只是影响了时间模的实现，把wait值改大一点试试，应该就可以看出来不同了吧。关于函数参数，建议先学习s2第一课的内容，就不会这样问啦~

**Comment by ds-dog** [comment]
这里不写应该只是影响了时间模的实现，把wait值改大一点试试，应该就可以看出来不同了吧。关于函数参数，建议先学习s2第一课的内容~

**Comment by neolee** [comment]
你的 `_say()` 方法完全是错的。

在第一次上课时我就说了，学编程起步一定要把计算机当朋友，你要确定的明白你告诉计算机的每句话是啥意思。你可以问问自己，该方法里的这些东西都是什么意思：

- `self.s` 是什么？
- `time.sleep` 是干啥的，返回值是什么？
- `self.wait` 是什么，有这个东西吗？
- 参数 `s` 是什么，该如何使用？

**Comment by ygrdkl** [comment]
的确有些蒙，在之前的课程中懵懵懂懂，练习对话机器人的时候，才有点感觉，的确目前还是对不同的self有些蒙，time.sleep是引入函数的调用方法，self.wait没有这东西吧，wait是对时间量化的一个类变量，参数s是一个返回的“大门”，再回头看第五课，刚开始一直没听明白，所以直接上手去做对话机器人的，在模仿的时候有点感觉了。
感谢李老师的提醒。。。
