### ISSUE TITLE
之前issue被关了，现在还是未能成功安装

### ISSUE THREAD

**Issue by sunyan023** [neolee/pilot#90]
原issues：macOS Catalina 安装 jupyterlab 出现 DEPRECATION: Python 2.7 will reach the end of its life... #26
 Closed	sunyan023 opened this issue 2 days ago · 21 comments
新issues：按您最后一步方式运行后，是下面这个样子：
192:~ sunny$ cd /usr
192:usr sunny$ sudo chown -R sunny:admin local
Password:
chown: local: Operation not permitted
192:usr sunny$ 
192:usr sunny$ 
192:usr sunny$ cd /usr/local
192:local sunny$ sudo chown -R sunny:admin *
192:local sunny$ brew install python
Updating Homebrew...
Warning: python 3.7.4_1 is already installed and up-to-date
To reinstall 3.7.4_1, run `brew reinstall python`
192:local sunny$ 
那么现在我应该从哪一步开始进行？谢谢！

**Comment by neolee** [comment]
关掉是因为长时间没有反馈，以为你已经解决。你可以重新打开 issue 的，我现在已经帮你 reopen 了：issue #26 

请你把上面的后半段内容贴到那边，我们继续交流。
