### ISSUE TITLE
你这个 fruits 为啥是 str 类型，教材里是 list 呀？

### ISSUE THREAD

**Issue by dingkunpeng** [neolee/pilot#901]
你这个 fruits 为啥是 str 类型，教材里是 list 呀？

_Originally posted by @neolee in https://github.com/neolee/pilot/issues/897#issuecomment-570785212_

**Comment by dingkunpeng** [comment]
我保存之后,推出,今天把上面代码重新运行了一遍,发现这个问题没有了

**Comment by neolee** [comment]
请在原 issue 回复，不要另开。
