### ISSUE TITLE
装饰器（decorator）的用处？

### ISSUE THREAD

**Issue by iceberg-yuan** [neolee/pilot#903]
李老师，我看了笑来老师讲的关于装饰器的内容，似懂非懂。笑来老师说装饰器很重要，我想了半天也想不出它为什么重要，装饰器主要应用的场景是什么呢？能不能专题讲一下？

**Comment by neolee** [comment]
S2 最后一章有讲 decorator，其实就是一种“把一个函数改造成另一个函数”的一种高阶函数。

装饰器很强大，但是应用场景比较特定，应避免滥用。可以看看 #828 。
