### ISSUE TITLE
jupyter lab 打开界面没有学习用书

### ISSUE THREAD

**Issue by huzhongzhu** [neolee/pilot#904]
运行的代码如下：
PS C:\Users\Administrator> cd Code
PS C:\Users\Administrator\Code> git clone https://github.com/huzhongzhu/pilot-student.git
fatal: destination path 'pilot-student' already exists and is not an empty directory.
PS C:\Users\Administrator\Code> cd pilot-student
PS C:\Users\Administrator\Code\pilot-student> jupyter lab
[I 22:04:10.182 LabApp] JupyterLab extension loaded from c:\users\administrator\scoop\apps\python37\3.7.4\lib\site-packages\jupyterlab
[I 22:04:10.183 LabApp] JupyterLab application directory is c:\users\administrator\scoop\apps\python37\3.7.4\share\jupyter\lab
[I 22:04:10.583 LabApp] Serving notebooks from local directory: C:\Users\Administrator\Code\pilot-student
[I 22:04:10.584 LabApp] The Jupyter Notebook is running at:
[I 22:04:10.584 LabApp] http://localhost:8888/?token=9016863b8e722221cdaa36615d29bfa90bac2aba2eb0aefa
[I 22:04:10.584 LabApp]  or http://127.0.0.1:8888/?token=9016863b8e722221cdaa36615d29bfa90bac2aba2eb0aefa
[I 22:04:10.585 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 22:04:10.629 LabApp]

    To access the notebook, open this file in a browser:
        file:///C:/Users/Administrator/AppData/Roaming/jupyter/runtime/nbserver-6516-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=9016863b8e722221cdaa36615d29bfa90bac2aba2eb0aefa
     or http://127.0.0.1:8888/?token=9016863b8e722221cdaa36615d29bfa90bac2aba2eb0aefa
[I 22:04:12.744 LabApp] 301 GET /lab/workspaces/auto-K/?clone (::1) 4.00ms
[I 22:04:14.468 LabApp] Build is up to date
运行结果打开界面以后没有学习用书，查看了下之前的提问，老师的回答是多数是运行命令的工作目录有问题，还是不解，望大家解答下，谢谢！

**Comment by neolee** [comment]
你的 `C:\Users\Administrator\Code\pilot-student` 下面有些啥？在这个工作目录下运行 `ls` 输出是啥？

另外支线课程第一讲你看过么？
