### ISSUE TITLE
无法pull

### ISSUE THREAD

**Issue by Gittplayer** [neolee/pilot#905]
李老师，我想测试一下pull这个功能，我把本地仓库里的一个文件删掉后，用Git  pull这个命令想把远程上的仓库更新下来，结果显示已更新，但实际未更新，不知道为什么
![image](https://user-images.githubusercontent.com/57967597/71785596-6cd08f80-303c-11ea-8161-169ff94239b5.png)

**Comment by neolee** [comment]
Pull 是在远程和本地的 git 版本数据库之间比较和同步，而你删除的并不是本地 git 版本数据，而是 working copy 里的文件。所以如果想恢复被删除的文件，你需要做的是 git checkout master。

Pull 只有远端拥有比你本地更新的 commit 时才会做事。
