### ISSUE TITLE
使用 Git log 后无法回到命令输入的状态

### ISSUE THREAD

**Issue by Gittplayer** [neolee/pilot#906]
李老师，我用Git log查看历史版本后，命令行无法回到密令输入的状态，只能新打开一个tab，很麻烦，是不是我哪里没作对？
![image](https://user-images.githubusercontent.com/57967597/71785683-70184b00-303d-11ea-90e1-910949d3d716.png)

**Comment by neolee** [comment]
按 Q 键可以退出。

**Comment by Gittplayer** [comment]
好的，谢谢李老师
