### ISSUE TITLE
克隆自己的远程仓库后命令行报错

### ISSUE THREAD

**Issue by Gittplayer** [neolee/pilot#907]
李老师，我在同一台pc上想模拟别人克隆自己的远程仓库，新建了一个temp的文件夹，然后克隆了自己的远程仓库，克隆下来之后命令行输入什么命令都没有正常的反应的是怎么回事呢？都报错
![image](https://user-images.githubusercontent.com/57967597/71786117-1450c080-3043-11ea-81cc-454a8f12a873.png)

**Comment by neolee** [comment]
你要先进入你 clone 回来的目录呀。

我建议你先学习视频支线课程里的第一和第二讲。

**Comment by Gittplayer** [comment]
哈哈，已解决，谢谢李老师
