### ISSUE TITLE
关于继承的问题

### ISSUE THREAD

**Issue by Winsi0n** [neolee/pilot#908]
最近重新复习了第一阶段的课程并再重写了一次作业。写大作业时发现一下不理解的问题：

`super().__init__(runtype)`

请问老师，我们在写父类 Bot 的时候不是已经在初始化中写了 `self.runtype = runtype` 吗？

```
def __init__(self, runtype='once'):
    self.runtype = runtype
    self.q = ''
    self.a = ''
```

那子类继承时不是也就拥有了 `self.runtype = runtype` 这一句。为什么还需要重新写 `super().__init__(runtype)` 呢？（实际上我自己测试了下也报错了）

另外，`super().__init__(runtype)`  这一句是不是和我直接在子类写  `self.runtype = runtype` 的效果是一样的？只不过是以后要修改的时候比较方便，只需要修改父类就好了？

**Comment by neolee** [comment]
课上我讲过的，子类 override 父类的方法，会完全覆盖父类实现，如果我们需要复用父类实现里的代码，就用 `super().xxx()` 来调用之。

你最后一段的理解是对的。

**Comment by Winsi0n** [comment]
老师，那为什么不用再继承 `self.a = ''` 呢？

**Comment by neolee** [comment]
在 `HelloBot` 版本的 `__init__()` 中，首先调用父类版本（对三个属性都进行了定义和初始化），然后需要改变对 `self.q` 的初始值，其他不需要改变，所以也没有对其他几个属性做处理。

**Comment by Winsi0n** [comment]
老师我越来越糊涂了。
按照您说的，那 `HelloBot` 继承父类时不就已经是默认 `runtype = ‘once’` 了吗？那为什么还需要`super().__init__(runtype)` 这一句呢？继承父类的时候不就把 `self.runtype = runtype` 这一句继承过来了？

**Comment by neolee** [comment]
谁告诉你“继承父类的时候把 self.runtype = runtype 这一句继承过来了”的？仔细读这句话：

> 课上我讲过的，子类 override 父类的方法，会完全覆盖父类实现。

一旦覆盖，父类的实现就被子类的实现完全替代，子类的对象实例调用的就是子类的那个方法，不会自动帮你父类子类实现都调一遍（真这样会乱套）。

**Comment by Winsi0n** [comment]
捋了捋好像知道自己在哪里有问题：

1.  以为子类的 `__init__()` 不算 override
2. 对老师的回答还不够理解
> 在 HelloBot 版本的 `__init__()` 中，首先调用父类版本（对三个属性都进行了定义和初始化），然后需要改变对 self.q 的初始值，其他不需要改变，所以也没有对其他几个属性做处理。
老师说：“调用父类版本（对三个属性都进行了定义和初始化）” 这里是否意味着子类的 `__init__()` 中也有参数 `self.runtype = runtype` 呢？
 
（3.我得再把课听一遍）

**Comment by neolee** [comment]
> 这里是否意味着子类的 __init__() 中也有参数 self.runtype = runtype 呢？

你怎么还没兜出来，子类的 `__init__()` 里有啥没有啥，就看你在里面写了啥啊！要么你把父类做过的事情再写一遍，要么你用 `super().__init__(runtype)` 调用父类实现；如果这俩都没做，那就啥都没有呗。

**Comment by Winsi0n** [comment]
哦！！！我知道我弄错了啥了！！！

我记混了，一直以为子类里有override  `run`  方法，所以我一直纠结子类里为啥没有定义 `self.a = ''`  却能在 `run`  里调用；所以我就反而开始疑惑自己对继承的理解，以为没有写到可以默认继承（脑洞大开

谢谢老师（今晚可以睡个好觉了

**Comment by bing90740** [comment]
那么为什么子类里面不需要重新定义`self.a = ''  `?

**Comment by Winsi0n** [comment]
> 那么为什么子类里面不需要重新定义`self.a = '' `?

因为用不到
