### ISSUE TITLE
TypeError: 'list' object is not callable

### ISSUE THREAD

**Issue by onthebus98** [neolee/pilot#909]
请教老师，这个报错是怎么回事
![图片](https://user-images.githubusercontent.com/53966721/71804185-b1d8de00-309d-11ea-81af-1700226802f8.png)

**Comment by neolee** [comment]
你这个 cell 执行过不止一次吧，第一次执行时由于 `list = ('aeiou')` 这句，`list` 变成了一个 tuple（里面只有一个元素 `'aeiou'`），而一个 tuple 是不能当成函数来调用的，所以你再次执行这个 cell 时 `list()` 这句就出错了。

你需要运行的正确代码是：

```python
l = list('aeiou')
print(l)
```

最后输出 `['a', 'e', 'i', 'o', 'u']`。

**Comment by onthebus98** [comment]
是的,执行过不止一次.
