### ISSUE TITLE
无法安装 jupyterlab

### ISSUE THREAD

**Issue by shizuhe** [neolee/pilot#91]
![image](https://user-images.githubusercontent.com/49558005/67570226-6b910580-f763-11e9-9673-7e62784c44d1.png)

**Comment by neolee** [comment]
网络问题，可以稍后重试，也可以换别的网络或者挂代理试试。

**Comment by shizuhe** [comment]
好的 ，谢谢老师！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Neo Lee"<notifications@github.com&gt;; 
发送时间: 2019年10月25日(星期五) 晚上8:16
收件人: "neolee/pilot"<pilot@noreply.github.com&gt;; 
抄送: "施祖合"<2115318112@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [neolee/pilot] 无法安装 jupyterlab (#91)




网络问题，可以稍后重试，也可以换别的网络或者挂代理试试。

**Comment by wangbingfeng** [comment]
the solution is :
pip3 --default-timeout=100 install -U jupyterlab

it works for me

**Comment by shizuhe** [comment]
什么意思啊？

**Comment by neolee** [comment]
@shizuhe 上面 @wangbingfeng 同学的建议是给 `pip install jupyterlab` 命令加上一个参数，效果是延长网络等待的时间，你可以试试：

```shell
pip --default-timeout=100 install jupyterlab
```

**Comment by shizuhe** [comment]
安装成功了，感谢这位同学！谢谢老师！ @wangbingfeng @neolee
