### ISSUE TITLE
lower不是python内的函数么？

### ISSUE THREAD

**Issue by ygrdkl** [neolee/pilot#912]
已经有两次没通过，不知道为什么
![1 6 lower问题](https://user-images.githubusercontent.com/31388214/71820944-b4eac300-30cb-11ea-901b-aefaf45a59de.png)

**Comment by ygrdkl** [comment]
o ，这不是函数，是方法，既然已经内置了lower方法，我这不知道错在哪了？

**Comment by ygrdkl** [comment]
刚刚重新启动，试了一下又好了。。。

**Comment by neolee** [comment]
这种问题一般是你在这个 notebook 里执行了某些代码，把 `s` 定义成个函数了，于是 `s.lower()` 就会报那个错。
