### ISSUE TITLE
Iterable 与 Iterator 一章中文档问题 __next()__

### ISSUE THREAD

**Issue by wessyde** [neolee/pilot#913]
1. 李老师，如下图，“_\_next()__”括号的位置是不是写错了？
位置：pilot/p2-7-iterable-iterator.ipynb，最后章节One More Thing...中的一段话
![微信图片_20200106175825](https://user-images.githubusercontent.com/48742886/71838120-18d4b200-30f3-11ea-919e-541902ba5a22.jpg)

2. 文中您提到下次调用__next__()
>以后再返回到 yield 的下一行继续执行——这个“以后”到底是什么时候呢？聪明的你一定可以猜到，就是我们下一次调用 __next()__ 的时候！

我是否可以把
```
yield curr 改为 yield prev
```
放在函数最后一句，与前面的“八股”一致，如下：
```
def fib():
    prev, curr = 0, 1
    while True:
        prev, curr = curr, prev + curr
        yield prev
f = fib()
list(islice(f, 0, 10))
```
返回的仍是
```
[1, 1, 2, 3, 5, 8, 13, 21, 34, 55]
```
这样是不是也正确？

3. 另外，貌似我new issue无法加标签，是我new的位置不对没有权限吗？我应该在我fork的位置new吗？

**Comment by neolee** [comment]
1. 是笔误，已经修正，多谢指出~

2. 你的改写没问题，也是可以的。我之所以那么写，一来是为了示范 `yield` 与 `return` 的差异：`yield` 写在代码中间位置完全没问题，因为下次会从它这里向后继续执行，而 `return` 就不行了；二来也因为 `yield curr` 比起 `yield prev` 语义上稍微更顺一点。

3. 你当然应该在我的主仓库提问，不然我和其他同学怎么方便的找到呀。Label 我会做合适的设置，不用担心。

**Comment by wessyde** [comment]
明白了，谢谢老师解答
