### ISSUE TITLE
Git commit 失败：Error: Cannot find module 'D:\'

### ISSUE THREAD

**Issue by xiaoyaogege-233** [neolee/pilot#914]
![image](https://user-images.githubusercontent.com/59498906/71855727-23d31680-30e2-11ea-9f7a-672db93a7f0b.png)
已设置过git和vscode，但是输入git commit不弹出VSCode，显示
Error: Cannot find module 'D:\'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
    at Function.Module._load (internal/modules/cjs/loader.js:531:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:850:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
error: There was a problem with the editor 'code -w'.
Please supply the message using either -m or -F option.

如何解决？

**Comment by xiaoyaogege-233** [comment]
我又把VSC从D盘卸载又安装到了C盘，现在git commit出现的情况是
![image](https://user-images.githubusercontent.com/59498906/71876496-2310a380-3127-11ea-82c7-5c4d2bd562c5.png)
请问如何解决？

**Comment by xiaoyaogege-233** [comment]
已经输入过了  git config --global core.editor "code -w"，
![image](https://user-images.githubusercontent.com/59498906/71876588-5d7a4080-3127-11ea-8c4e-8d718760c922.png)

**Comment by neolee** [comment]
你在命令行输入 `code` 能启动 Visual Studio Code 吗？

**Comment by xiaoyaogege-233** [comment]
> 你在命令行输入 `code` 能启动 Visual Studio Code 吗？

不可以。之前好像可以，但是卸载又装到C盘就不行了

**Comment by neolee** [comment]
尝试卸载然后重装 Visual Studio Code，注意一定要下载和安装稳定版本，VSCode 有个 Inside 版本，是不会配置命令行命令 `code` 的。

**Comment by xiaoyaogege-233** [comment]
> > 你在命令行输入 `code` 能启动 Visual Studio Code 吗？
> 
> 不可以。之前好像可以，但是卸载又装到C盘就不行了

重新下载安装了Stable Build并重启电脑后可以拉起，问题已解决，谢谢老师
