### ISSUE TITLE
Jupyter Lab 中代码的颜色问题

### ISSUE THREAD

**Issue by onthebus98** [neolee/pilot#915]
请教老师：jupyter lab 中代码部分的颜色是遵循了什么规律？因为python 实在太大了，提前引用很多。对于彻底的编程小白来说，搞清楚这些基础的东西或许会有帮助。

**Comment by neolee** [comment]
以缺省配色主题来说，

- 粗体绿色是语言关键字（*keyword*）；
- 红色是字符串；
- 蓝色是函数定义，以及调用对象的方法；
- 非粗体的绿色有好几种，比如数字、函数调用等；
- 紫色是运算符（*operator*）。

如果顺着课程一步步走下来，应该并不会有“太多太繁杂”的感觉才对。按部就班学习，在哪里遇到障碍就停下来解决，是学习的正道。
