### ISSUE TITLE
关于.items()等方法中 '()' 的使用； <class 'dict_items'> 和<class 'list'>的区别

### ISSUE THREAD

**Issue by xiaoqie007** [neolee/pilot#917]
<img width="1001" alt="Screen Shot 2020-01-08 at 4 17 01 PM" src="https://user-images.githubusercontent.com/43660812/71961724-fe095700-3232-11ea-9525-0305820bd8f8.png">
<img width="1027" alt="Screen Shot 2020-01-08 at 4 18 40 PM" src="https://user-images.githubusercontent.com/43660812/71961729-01044780-3233-11ea-90c3-b035c8c29648.png">
<img width="1025" alt="Screen Shot 2020-01-08 at 4 19 47 PM" src="https://user-images.githubusercontent.com/43660812/71961739-05306500-3233-11ea-8cc5-f2cc79378e18.png">

**Comment by neolee** [comment]
1. `items()` 是 `dict` 类中定义的方法，`d.items` 是一个变量，指向 `d.items()` 这个方法（函数）；而 `d.items()` 则是 `d` 对象调用了自己的 `items()` 方法。请复习函数调用的语法和对象概念。

2. `dict_items` 是 `dict.items()` 返回数据的类型，是一种 iterable 对象；`list` 不仅是 iterable 而且是 seqeunce。所以 `list` 有序号（下标）而 `dict_items` 没有。

**Comment by xiaoqie007** [comment]
> 1. `items()` 是 `dict` 类中定义的方法，`d.items` 是一个变量，指向 `d.items()` 这个方法（函数）；而 `d.items()` 则是 `d` 对象调用了自己的 `items()` 方法。请复习函数调用的语法和对象概念。
> 2. `dict_items` 是 `dict.items()` 返回数据的类型，是一种 iterable 对象；`list` 不仅是 iterable 而且是 seqeunce。所以 `list` 有序号（下标）而 `dict_items` 没有。

嗯嗯，明白了，谢谢老师～😊
