### ISSUE TITLE
掌握基本知识点后如何进一步巩固和尝试开始用编程做点东西？

### ISSUE THREAD

**Issue by JianhaoChen2018** [neolee/pilot#918]
李骏老师好，有个问题想请您指点一下：跟随老师的课程我基本对Python里的基础知识和概念有了一个简单的知识框架，但水平也只局限于应付各知识点的简单练习题，我想深入去巩固各个知识点，是该直接找更多类似课本的“练习题”来学习熟练，还是应该可以考虑开始选一个自己感兴趣的方向（比如爬虫/Web应用/数据分析等）来实际动手做点东西，然后在写的过程中不停地回去查找需要用到的知识点进而巩固呢？如果可以选择后者的话又该注意点什么呢？在这方面有点迷茫，希望能得到老师的意见。谢谢！

**Comment by neolee** [comment]
其实都可以，编程这件事，重在不断尝试。我个人的建议是找到自己感兴趣的一个点去找一些 tutorial 来玩。一定要自己有兴趣，成果对自己有用，目前阶段不必太在意是不是热门之类的——不客气的说，外面吹的热门很多其实是不对的。

**Comment by ygrdkl** [comment]
我也是这个问题，只是依葫芦画葫芦，还处在对代码语言的生疏期，虽然其中的一部分逻辑有些概念，但是，对李老师——先理解，再操作的要求还是达不到。看到自己女儿在玩拼图的时候，很多时候就没有外围框架的概念，只是一味的寻找细节对的上就拼上去，虽然最后也能完成，但是面对下一个难度更高的拼图时，还是用老方法，笨办法。我感觉自己也只是处在模仿阶段。继续反复听李老师的课吧

**Comment by JianhaoChen2018** [comment]
> 其实都可以，编程这件事，重在不断尝试。我个人的建议是找到自己感兴趣的一个点去找一些 tutorial 来玩。一定要自己有兴趣，成果对自己有用，目前阶段不必太在意是不是热门之类的——不客气的说，外面吹的热门很多其实是不对的。

好的，明白，谢谢老师。
