### ISSUE TITLE
print None 问题

### ISSUE THREAD

**Issue by ygrdkl** [neolee/pilot#919]
![Uploading 1.8 print none问题.png…]()

在函数中原来输入的return，变成print后，打印出None，不是为“空”么？

**Comment by ygrdkl** [comment]
![1 8 print none 问题2](https://user-images.githubusercontent.com/31388214/71981867-3d00d200-325e-11ea-97c9-c2926ded1f01.png)

**Comment by neolee** [comment]
`increase(n)` 没有显式的返回，所以相当于返回了一个 `None`，打印出来就是 None。

你觉得应该返回啥呢？
