### ISSUE TITLE
scoop install python 失败

### ISSUE THREAD

**Issue by Fanfan1031** [neolee/pilot#92]
请教老师："scoop install python" 安装的是python3.8.0，失败；后输入“scoop install python37”
PS C:\Users\asus> scoop list
Installed apps:

  7zip 19.00
  busybox 3244-g48128b9aa
  dark  *failed*
  git 2.23.0.windows.1
  lessmsi 1.6.91
  python 3.8.0 *failed*

PS C:\Users\asus> scoop install python37
Couldn't find manifest for 'python37'

**Comment by Fanfan1031** [comment]
PS C:\Users\asus> scoop install python
ERROR It looks like a previous installation of python failed.
Run 'scoop uninstall python' before retrying the install.
WARN  'python' (3.8.0) is already installed.
Use 'scoop update python' to install a new version.
PS C:\Users\asus> scoop update python
python: 3.8.0 (latest version)
Latest versions for all apps are installed! For more information try 'scoop status'
PS C:\Users\asus> scoop status
Scoop is up to date.
These apps failed to install:
    dark
    python

**Comment by neolee** [comment]
首先你有两个安装失败的包，dark 和 python，先用 `scoop uninstall dark python` 删掉。

然后严格按照 [配置指南](https://github.com/neolee/pilot/blob/master/x1-setup.md) 的“安装 Python”一节操作。

**Comment by Fanfan1031** [comment]
PS C:\Users\asus> scoop bucket add versions
WARN  The 'versions' bucket already exists. Use 'scoop bucket rm versions' to remove it.
PS C:\Users\asus> scoop install python37@3.7.4
WARN  Given version (3.7.4) does not match manifest (3.7.5)
WARN  Attempting to generate manifest for 'python37' (3.7.4)
Autoupdating python37
Searching hash for python-3.7.4.exe in https://www.python.org/downloads/release/python-374/
Found: md5:33cc602942a54446a3d6451476394789 using Extract Mode
Searching hash for python-3.7.4-amd64.exe in https://www.python.org/downloads/release/python-374/
Found: md5:a702b4b0ad76debdb3043a583e563400 using Extract Mode
Writing updated python37 manifest
Installing 'python37' (3.7.4) [64bit]
python-3.7.4-amd64.exe (25.4 MB) [======================================>                                                                                      ]  31%
Checking hash of python-3.7.4-amd64.exe ... ERROR Hash check failed!
App:         python37
URL:         https://www.python.org/ftp/python/3.7.4/python-3.7.4-amd64.exe#/py3.exe
First bytes: 4D 5A 90 00 03 00 00 00
Expected:    a702b4b0ad76debdb3043a583e563400
Actual:      80c674360e0ccae37c50e8a8ac575476

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/ScoopInstaller/Versions/issues/new?title=python37%403.7.5%3a+hash+check+failed

**Comment by neolee** [comment]
前面 OK 了，但是下载安装 Python 时，网络原因没有下载完成，所以失败了。

稍后再试，或者试试换网络或者挂代理。

**Comment by Fanfan1031** [comment]
谢谢老师！

**Comment by Fanfan1031** [comment]
请教老师：安装python出现一下问题
PS C:\Users\asus> scoop install python37@3.7.4
WARN  Given version (3.7.4) does not match manifest (3.7.5)
WARN  Attempting to generate manifest for 'python37' (3.7.4)
Autoupdating python37
Searching hash for python-3.7.4.exe in https://www.python.org/downloads/release/python-374/
Found: md5:33cc602942a54446a3d6451476394789 using Extract Mode
Searching hash for python-3.7.4-amd64.exe in https://www.python.org/downloads/release/python-374/
Found: md5:a702b4b0ad76debdb3043a583e563400 using Extract Mode
Writing updated python37 manifest
Installing 'python37' (3.7.4) [64bit]
Loading python-3.7.4-amd64.exe from cache
Checking hash of python-3.7.4-amd64.exe ... ok.
Running installer... error.
ERROR Exit code was 1618!
Installation aborted. You might need to run 'scoop uninstall python37' before trying again.

**Comment by neolee** [comment]
Python 安装程序运行出错，一般是以前安装过有遗留。

去 Windows 设置的软件卸载中找 Python，修复和卸载，然后：

```powershell
scoop uninstall python37
scoop install python37
```
