### ISSUE TITLE
网络问题下载不了，是否可以直接跳过编程环境配置这一节课

### ISSUE THREAD

**Issue by yusen7** [neolee/pilot#922]
由于一些原因，无法科学上网，可否直接跳过环境编程设置这一环节。 #

**Comment by yusen7** [comment]
不行的话找办法

**Comment by neolee** [comment]
跳过了你怎么动手编程呢，不自己动手大概永远也学不会编程……

**Comment by yusen7** [comment]
不能科学上网，那就另寻僻径。 我在一位践行群的朋友的帮助下，下载了Anaconda3,并在里面安装了vscode,虽然会挺麻烦的。​------------------ 原始邮件 ------------------
发件人: "Neo Lee"<notifications@github.com>
发送时间: 2020年1月9日(星期四) 中午1:16
收件人: "neolee/pilot"<pilot@noreply.github.com>;
抄送: "yusen7"<1578269248@qq.com>;"State change"<state_change@noreply.github.com>;
主题: Re: [neolee/pilot] 网络问题下载不了，是否可以直接跳过编程环境配置这一节课 (#922)



跳过了你怎么动手编程呢，不自己动手大概永远也学不会编程……
 
&mdash;
