### ISSUE TITLE
课本例子少一个“等号”

### ISSUE THREAD

**Issue by gaoteng-pro** [neolee/pilot#929]
def leap_years(begin, end):
    year = begin
    while year < end:
        if (year % 4 == 0 and year % 100 != 0) or year % 400 == 0:
            print(year)
        year += 1
        
leap_years(2000, 2020)
2000
2004
2008
2012
2016

在p2-1-function-def函数定义再探——没有、一个和多个参数的判断闰年的例子中，while的逻辑判断语句应该是 <=,而不是<，2020年是闰年。

**Comment by neolee** [comment]
这个问题，取决于你对输入参数 `begin` 和 `end` 的理解。在 Python（以及很多其他语言中），当出现起止范围的参数时，通常都是包含“起”而不包含“止”的，用数学语言就是“半开半闭区间”。示例代码也是如此实现的。

当然如果明确注明：测试范围包括 `begin` 和 `end` 两个年份，就应该把判断改为 `<=` 了。

**Comment by gaoteng-pro** [comment]
get了
