### ISSUE TITLE
VScode 无法保存新建文件

### ISSUE THREAD

**Issue by zsqiang001** [neolee/pilot#93]
![WechatIMG377](https://user-images.githubusercontent.com/37511474/67572804-8cf4f000-f769-11e9-8617-ee624cc2cfe0.jpeg)

搜索论坛让更改文件权限，改好没效果。该怎么处理？

**Comment by neolee** [comment]
你是 macOS 吧？

你这是想吧 hello.py 保存在系统的 `/` 目录下，这个目录是系统保护的，一般不要去碰。你应该在 `/Users/<你的用户名>/` 下面创建一个目录（比如 `/Users/<你的用户名>/Code`），然后把你的程序放在里面。

**Comment by zsqiang001** [comment]
![WechatIMG378](https://user-images.githubusercontent.com/37511474/67588554-f9331c00-f788-11e9-9fb3-7786fc380f69.jpeg)
Code文件在/user下创建好了，但是ls，code . 的命令都不能用，是设置有问题吗？

**Comment by neolee** [comment]
建议你先看看新发的支线课程第一讲，链接在这个页面上面的 Wiki 主页上。
