### ISSUE TITLE
transitions 库安装问题

### ISSUE THREAD

**Issue by dingkunpeng** [neolee/pilot#930]
在有限状态机这个章节中,我用pip install transitions 安装时出现下列问题:

![Snip20200110_2](https://user-images.githubusercontent.com/24670493/72130957-e3132000-33b5-11ea-9505-55b798afa939.png)

查了一下transitions 的兼容如下:

![Snip20200110_3](https://user-images.githubusercontent.com/24670493/72131176-75b3bf00-33b6-11ea-90c7-ec05a75fe028.png)

而我的Python 2.7和Python 3.7.9,不知道怎么回事?

**Comment by neolee** [comment]
Python 哪儿有 3.7.9 这个版本？

**Comment by dingkunpeng** [comment]
![Snip20200110_5](https://user-images.githubusercontent.com/24670493/72159361-28a40d00-33f7-11ea-8d18-5875ee0ab804.png)

![Snip20200110_4](https://user-images.githubusercontent.com/24670493/72159239-e7abf880-33f6-11ea-8926-71fb9036a5fe.png)

python 3.7.0 版本

**Comment by neolee** [comment]
你应该用 `pip3 install transitions` 来安装，如果还有问题，最好把 Python 升到 3.7.6。

另外，我的疑问是，你是按照我的环境配置指南操作的么？如果是的话，怎么会出来个 3.7.0 的 Python？

**Comment by dingkunpeng** [comment]
我以前没有在没有学习课程之前,就按照了一个Python3,稍后我自己升级到Python3.7.6.
