### ISSUE TITLE
克隆分叉的 repo 到机器本地时报错

### ISSUE THREAD

**Issue by EthanGMAT** [neolee/pilot#932]
![image](https://user-images.githubusercontent.com/56030518/72140233-422f5f80-33cb-11ea-998c-f70c558e1bd4.png)
请教老师，前面的步骤都是按照流程走的，但是到了克隆分叉的repo到机器本地时报错，连续试了三次，都显示的是上面的结果，不知道除了什么问题。

**Comment by neolee** [comment]
这个是网络问题。
