### ISSUE TITLE
安装 Python 第三步报错

### ISSUE THREAD

**Issue by liuke008** [neolee/pilot#934]
PS C:\Users\LiuKe> scoop install python37@3.7.4
WARN  Given version (3.7.4) does not match manifest ()
WARN  Attempting to generate manifest for 'python37' (3.7.4)
'python37' does not have autoupdate capability
couldn't find manifest for 'python37@3.7.4'

**Comment by liuke008** [comment]
纯小白请教，排错试过了，解决不了。

**Comment by liuke008** [comment]
PS C:\Users\LiuKe> scoop install python37@3.7.4
WARN  Given version (3.7.4) does not match manifest ()
WARN  Attempting to generate manifest for 'python37' (3.7.4)
'python37' does not have autoupdate capability
couldn't find manifest for 'python37@3.7.4'
PS C:\Users\LiuKe> scoop checkup
WARN  LongPaths support is not enabled.
You can enable it with running:
    Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1
ERROR 'Inno Setup Unpacker' is not installed! It's required for unpacking InnoSetup files. Please run 'scoop install innounp'.
ERROR 'dark' is not installed! It's required for unpacking installers created with the WiX Toolset. Please run 'scoop install dark' or 'scoop install wixtoolset'.
WARN  Found 3 potential problems.
PS C:\Users\LiuKe> Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1
Set-ItemProperty : 不允许所请求的注册表访问权。
所在位置 行:1 字符: 1
+ Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem'  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (HKEY_LOCAL_MACH...trol\FileSy
   stem:String) [Set-ItemProperty], SecurityException
    + FullyQualifiedErrorId : System.Security.SecurityException,Microsoft.Powe
   rShell.Commands.SetItemPropertyCommand

**Comment by neolee** [comment]
首先 `scoop checkup` 的问题最好都先排除掉，你现在运行 `Set-ItemProperty` 那个命令出错，可以尝试打开一个 Admin 权限的 PowerShell 窗口试试，如果还不行，可能是 Windows 版本太低。

至于安装 Python，你之前运行 `scoop bucket add versions` 了吗？成功吗？有什么返回信息？

**Comment by liuke008** [comment]
[cid:image001.png@01D5C80A.742B4A80] [cid:image002.png@01D5C80A.9C68CE00]  [cid:image003.png@01D5C80B.79259800]
李骏老师：

你好！

上图是您两个问题的截图，我电脑是W10的系统，360更新的。版本应该不会太老，电脑配置见图三。

祝好！
刘可
2020年1月10号

发件人: Neo Lee<mailto:notifications@github.com>
发送时间: 2020年1月10日 22:53
收件人: neolee/pilot<mailto:pilot@noreply.github.com>
抄送: liuke008<mailto:lake-liu@outlook.com>; Author<mailto:author@noreply.github.com>
主题: Re: [neolee/pilot] 安装python第三步报错 (#934)


首先 scoop checkup 的问题最好都先排除掉，你现在运行 Set-ItemProperty 那个命令出错，可以尝试打开一个 Admin 权限的 PowerShell 窗口试试，如果还不行，可能是 Windows 版本太低。

至于安装 Python，你之前运行 scoop bucket add versions 了吗？成功吗？有什么返回信息？

―

**Comment by liuke008** [comment]
李骏老师：

您好！

我可以将您的编程的链接发给我家的孩子们吗？他们不在践行群，这个违反规定吗？
感谢您这么晚还在帮忙解答问题。

祝好！

刘可
2020年1月10日星期五

发件人: Neo Lee <notifications@github.com>
发送时间: 2020年1月10日 22:53
收件人: neolee/pilot <pilot@noreply.github.com>
抄送: liuke008 <lake-liu@outlook.com>; Author <author@noreply.github.com>
主题: Re: [neolee/pilot] 安装python第三步报错 (#934)


首先 scoop checkup 的问题最好都先排除掉，你现在运行 Set-ItemProperty 那个命令出错，可以尝试打开一个 Admin 权限的 PowerShell 窗口试试，如果还不行，可能是 Windows 版本太低。

至于安装 Python，你之前运行 scoop bucket add versions 了吗？成功吗？有什么返回信息？

**Comment by liuke008** [comment]
[cid:image001.png@01D5C80E.D8C58BA0]

发件人: Neo Lee <notifications@github.com>
发送时间: 2020年1月10日 22:53
收件人: neolee/pilot <pilot@noreply.github.com>
抄送: liuke008 <lake-liu@outlook.com>; Author <author@noreply.github.com>
主题: Re: [neolee/pilot] 安装python第三步报错 (#934)


首先 scoop checkup 的问题最好都先排除掉，你现在运行 Set-ItemProperty 那个命令出错，可以尝试打开一个 Admin 权限的 PowerShell 窗口试试，如果还不行，可能是 Windows 版本太低。

至于安装 Python，你之前运行 scoop bucket add versions 了吗？成功吗？有什么返回信息？

**Comment by neolee** [comment]
教材和视频支线课程都是开放的，可以分享。

看不到你的截图。

**Comment by liuke008** [comment]
![1](https://user-images.githubusercontent.com/59735353/72171820-b6d7bd80-340e-11ea-83fe-10c68a77a96e.png)
![2](https://user-images.githubusercontent.com/59735353/72171824-b7705400-340e-11ea-91eb-64d3d071ae10.png)
![3](https://user-images.githubusercontent.com/59735353/72171827-b8a18100-340e-11ea-8156-be5db2a21e55.png)
![4](https://user-images.githubusercontent.com/59735353/72171833-ba6b4480-340e-11ea-947a-a16e0f783af1.png)
我是邮件发您的。现在这儿再试一下。
春节回家把您的课当新年礼物给我家的孩子们，顺便搞定他们的父母。

**Comment by neolee** [comment]
你现在已经搞定了 `scoop checkup` 里的第一个问题，还有两个问题比较简单，安装 `scoop install innounp dark` 就可以了。

另外看上去你也加过 `versions` 包了，现在执行 `scoop update`，如果没有出错信息，然后再安装 `scoop install python37@3.7.4`。

**Comment by liuke008** [comment]
Windows PowerShell
版权所有 (C) Microsoft Corporation。保留所有权利。

PS C:\Users\LiuKe> scoop install innounp dark
Updating Scoop...
Updating 'main' bucket...
 * d0406e1b trid: Update to version 2.24-20.01.10                        56 minutes ago
 * acb384c2 force: Update to version 0.27.1                              3 hours ago
 * 27fb36ad exiftool: Update to version 11.84                            3 hours ago
Updating 'versions' bucket...
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
Scoop was updated successfully!
Installing 'dark' (3.11.2) [64bit]
基础连接已经关闭: 发送时发生错误。
URL https://raw.githubusercontent.com/ScoopInstaller/Binary/master/dark/dark-3.11.2.zip is not valid
PS C:\Users\LiuKe> scoop update
Updating Scoop...
Updating 'main' bucket...
Updating 'versions' bucket...
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
Scoop was updated successfully!
PS C:\Users\LiuKe> scoop install python37@3.7.4
WARN  Given version (3.7.4) does not match manifest ()
WARN  Attempting to generate manifest for 'python37' (3.7.4)
'python37' does not have autoupdate capability
couldn't find manifest for 'python37@3.7.4'
PS C:\Users\LiuKe> scoop checkup
ERROR 'Inno Setup Unpacker' is not installed! It's required for unpacking InnoSetup files. Please run 'scoop install innounp'.
ERROR 'dark' is not installed! It's required for unpacking installers created with the WiX Toolset. Please run 'scoop install dark' or 'scoop install wixtoolset'.
WARN  Found 2 potential problems.
PS C:\Users\LiuKe> scoop install innounp
Installing 'innounp' (0.49) [64bit]
基础连接已经关闭: 发送时发生错误。
URL https://raw.githubusercontent.com/ScoopInstaller/Binary/master/innounp/innounp049.rar is not valid
PS C:\Users\LiuKe> scoop install innounp dark
WARN  'dark' () is already installed. Skipping.
WARN  'innounp' () is already installed. Skipping.
PS C:\Users\LiuKe> scoop checkup
ERROR 'Inno Setup Unpacker' is not installed! It's required for unpacking InnoSetup files. Please run 'scoop install innounp'.
ERROR 'dark' is not installed! It's required for unpacking installers created with the WiX Toolset. Please run 'scoop install dark' or 'scoop install wixtoolset'.
WARN  Found 2 potential problems.
PS C:\Users\LiuKe> scoop install innounp
ERROR It looks like a previous installation of innounp failed.
Run 'scoop uninstall innounp' before retrying the install.
WARN  'innounp' () is already installed.
Use 'scoop update innounp' to install a new version.
PS C:\Users\LiuKe> scoop uninstall innounp
Uninstalling 'innounp' ().
'innounp' was uninstalled.
PS C:\Users\LiuKe> scoop checkup
ERROR 'Inno Setup Unpacker' is not installed! It's required for unpacking InnoSetup files. Please run 'scoop install innounp'.
ERROR 'dark' is not installed! It's required for unpacking installers created with the WiX Toolset. Please run 'scoop install dark' or 'scoop install wixtoolset'.
WARN  Found 2 potential problems.
PS C:\Users\LiuKe> scoop install innounp
Installing 'innounp' (0.49) [64bit]
基础连接已经关闭: 发送时发生错误。
URL https://raw.githubusercontent.com/ScoopInstaller/Binary/master/innounp/innounp049.rar is not valid
PS C:\Users\LiuKe> scoop install innounp
ERROR It looks like a previous installation of innounp failed.
Run 'scoop uninstall innounp' before retrying the install.
WARN  'innounp' () is already installed.
Use 'scoop update innounp' to install a new version.
PS C:\Users\LiuKe> scoop uninstall innounp
Uninstalling 'innounp' ().
'innounp' was uninstalled.
PS C:\Users\LiuKe> scoop checkup
ERROR 'Inno Setup Unpacker' is not installed! It's required for unpacking InnoSetup files. Please run 'scoop install innounp'.
ERROR 'dark' is not installed! It's required for unpacking installers created with the WiX Toolset. Please run 'scoop install dark' or 'scoop install wixtoolset'.
WARN  Found 2 potential problems.
PS C:\Users\LiuKe> scoop install innounp
Installing 'innounp' (0.49) [64bit]
基础连接已经关闭: 发送时发生错误。
URL https://raw.githubusercontent.com/ScoopInstaller/Binary/master/innounp/innounp049.rar is not valid
PS C:\Users\LiuKe>

**Comment by liuke008** [comment]
PS C:\Users\LiuKe> scoop update
Updating Scoop...
Updating 'main' bucket...
 * e5ae944e k9s: Update to version 0.12.0                                18 minutes ago
Updating 'versions' bucket...
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
Scoop was updated successfully!
PS C:\Users\LiuKe> scoop install python37@3.7.4
WARN  Given version (3.7.4) does not match manifest ()
WARN  Attempting to generate manifest for 'python37' (3.7.4)
'python37' does not have autoupdate capability
couldn't find manifest for 'python37@3.7.4'
PS C:\Users\LiuKe>
感觉有点人机交互了，哈哈。

**Comment by neolee** [comment]
网络问题，你之前加 versions bucket 应该也没成功，需要删了 Scoop 重来。

**Comment by liuke008** [comment]
![1](https://user-images.githubusercontent.com/59735353/72205896-0b3c7500-34c3-11ea-9fa4-3e30c6df52d1.png)
删完Scoop，再装显示如图。

**Comment by neolee** [comment]
还是网络不行。核心还是搞定网络。

**Comment by liuke008** [comment]
网络问题已解决，配置完毕。

**Comment by neolee** [comment]
赞！Keep going!

**Comment by zhangshouren666** [comment]
![V_7UA3FY(OXKTOIN@3OJ@K4](https://user-images.githubusercontent.com/55570261/73512711-95725c00-4425-11ea-83be-72989e9ce512.png)
我的也是类似的问题，看了前面刘同志的这个问题，我判断也是网络问题，但在中间就是有犹豫，因为我卸载又重装了几次（scoop uninstall git和 scoop install git），还是一样的提示，于是检查（scoop checkup），还是没什么问题（No problems identified!）所以我翻了几篇issue，都不太一样。看到这里，我就在坚持多验证几次，看是不是网络问题。因为检查没问题了，那只能重复卸载再安装，检查网络，网络目前我也没处理过，网络神经刀，坑了我两天时间，最后提示6%，说明已经在安装了，哇，搞定。
