### ISSUE TITLE
我没打开一个管理员权限的 PowerShell 界面，就执行了Scoop 的安装命令

### ISSUE THREAD

**Issue by de-cheng** [neolee/pilot#936]
结果就是这样
PS C:\Users\Administrator> scoop checkup
scoop : The term 'scoop' is not recognized as the name of a cmdlet, function, script  file, or operable program. Check the spelling of the name, or if a path was include d, verify that the path is correct and try again.
At line:1 char:1
+ scoop checkup
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (scoop:String) [], CommandNotFoundExc
   eption
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by de-cheng** [comment]
现在如何补救呢？

**Comment by neolee** [comment]
在 Wiki 的常见问题里，以及环境配置指南的 Scoop 安装部分都有一些拍错的说明，你可以先看看。

这个 Issues 里也有不少相关问题，可以 search 一下。

你现在的问题是 Scoop 没装好，最简单的办法就是删除之后重装（Wiki 里有指引）。

**Comment by de-cheng** [comment]
PS C:\Users\Administrator> iwr -useb get.scoop.sh | iex
Initializing...
Scoop is already installed. Run 'scoop update' to get the latest versio
n.

**Comment by neolee** [comment]
都说了先删掉 Scoop 再重装，都说了 wiki 里有方法。为啥就是不听呢？

**Comment by de-cheng** [comment]
> 都说了先删掉 Scoop 再重装，都说了 wiki 里有方法。为啥就是不听呢？

scoop已经重装了

**Comment by de-cheng** [comment]
> 都说了先删掉 Scoop 再重装，都说了 wiki 里有方法。为啥就是不听呢？

scoop checkup 没问题

PS C:\Users\Administrator> scoop checkup
No problems identified!

**Comment by neolee** [comment]
那你运行 `scoop update` 会怎样？

你现在碰到的问题，很可能就是 Scoop 没装好，重装也没成功，你可以仔细的看你安装时候计算机给你的提示。

**Comment by de-cheng** [comment]
> 那你运行 `scoop update` 会怎样？
> 
> 你现在碰到的问题，很可能就是 Scoop 没装好，重装也没成功，你可以仔细的看你安装时候计算机给你的提示。

PS C:\Users\Administrator> scoop update
Updating Scoop...
Updating 'main' bucket...
Checking repo... ok
error: RPC failed; curl 56 OpenSSL SSL_read: Connection was reset, errno 10054
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
The main bucket was added successfully.
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
Updating 'versions' bucket...
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
Scoop was updated successfully!

**Comment by neolee** [comment]
由于网络问题，scoop update 失败了，也就是说没能成功从服务器获得 scoop 所有软件包的信息，下面也就没法正常使用了。

建议换个网络或者挂代理试试，注意命令行要使用代理经常需要特定命令，可以咨询代理提供商。

**Comment by de-cheng** [comment]
> 由于网络问题，scoop update 失败了，也就是说没能成功从服务器获得 scoop 所有软件包的信息，下面也就没法正常使用了。
> 
> 建议换个网络或者挂代理试试，注意命令行要使用代理经常需要特定命令，可以咨询代理提供商。

这样算不算成功了呢？

PS C:\Users\Administrator> scoop update
Updating Scoop...
Updating 'main' bucket...
Checking repo... ok
The main bucket was added successfully.
Updating 'versions' bucket...
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
Scoop was updated successfully!

**Comment by neolee** [comment]
没，看下面的 `fatal:` 那几行，“fatal” 的意思是“严重/致命错误”。

**Comment by de-cheng** [comment]
> 由于网络问题，scoop update 失败了，也就是说没能成功从服务器获得 scoop 所有软件包的信息，下面也就没法正常使用了。
> 
> 建议换个网络或者挂代理试试，注意命令行要使用代理经常需要特定命令，可以咨询代理提供商。

这样应该就好了吧

PS C:\Users\Administrator> scoop update
Updating Scoop...
Updating 'main' bucket...
 * 8139a381 jfrog: Update to version 1.33.1                              15 minutes a
go
Scoop was updated successfully!

**Comment by neolee** [comment]
试试 `scoop checkup` 和 `scoop list`。
