### ISSUE TITLE
scoop install git 操作超时

### ISSUE THREAD

**Issue by de-cheng** [neolee/pilot#937]
PS C:\Users\Administrator> scoop install git
Installing '7zip' (19.00) [64bit]
7z1900-x64.msi (1.7 MB) [==================================================] 100%
Checking hash of 7z1900-x64.msi ... ok.
Extracting 7z1900-x64.msi ... done.
Linking ~\scoop\apps\7zip\current => ~\scoop\apps\7zip\19.00
Creating shim for '7z'.
Creating shortcut for 7-Zip (7zFM.exe)
'7zip' (19.00) was installed successfully!
Installing 'git' (2.24.1.windows.2) [64bit]
PortableGit-2.24.1.2-64-bit.7z.exe (41.9 MB) [>                            ]   1%
操作已超时。
URL https://github.com/git-for-windows/git/releases/download/v2.24.1.windows.2/PortableGit-2.24.1.2-64-bit.7z.exe#/dl.7z is not valid

**Comment by neolee** [comment]
网络问题。
