### ISSUE TITLE
关于 rindex() 的返回

### ISSUE THREAD

**Issue by AlwaysSleepy** [neolee/pilot#939]
```python
s = 'Perform a string formatting operation. The string on which this method is called can contain literal text...'
length = len(' on which this method is called can contain literal text...')
l = " on which this method is called can contain literal text..."
length2 = l.replace(' ','')
print(l.replace(' ',''))
print(len(length2))
print(s.rindex('string'))
```
run:
onwhichthismethodiscalledcancontainliteraltext...
49
43

Process finished with exit code 0

为啥俩数不一样？求教，谢谢了。

**Comment by neolee** [comment]
你理解 `rindex()` 返回的是什么吗？

**Comment by AlwaysSleepy** [comment]
从最后一个往前数字符数 我的理解就是

Neo Lee <notifications@github.com>于2020年1月10日 周五21:23写道：

**Comment by neolee** [comment]
学编程有个窍门，下次上课我会详细说说，就是：永远相信计算机是对的，不要自己猜想——而应该根据计算机的反馈，去找到一个合理的解释。

客观来说，计算机也会出问题，但非常非常少。所以，只要你能找到计算机反应出来信息的合理解释，基本上就是真相。

如果你按照上面的思路去思考，应该会发现真相，然后去查查 Python 的文档，就可以确认下面的事实：

> `s.index()` 和 `s.rindex()` 都是用一个字符串去匹配 `s`（一个从左向右尝试，一个从右向左尝试），如果匹配到 `s` 的某个部分——一般叫做“匹配子串（*matched sub-string*）”——就返回这个子串的“起始下标”。

**Comment by AlwaysSleepy** [comment]
**返回这个子串的“起始下标”。**
我明白了  多谢
