### ISSUE TITLE
运行 iwr -useb get.scoop.sh | iex 报错了

### ISSUE THREAD

**Issue by jianlonglaoda** [neolee/pilot#94]
Scoop : 无法将“Scoop”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检
查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ Scoop is already installed. Run 'scoop update' to get the latest vers ...
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (Scoop:String) [], ParentContain
   sErrorRecordException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by neolee** [comment]
没有完整的错误信息难以判断，可以再运行一次，截屏发过来看看。

**Comment by jianlonglaoda** [comment]
PS C:\Users\赵建龙> Get-ExecutionPolicy
RemoteSigned
PS C:\Users\赵建龙> Set-ExecutionPolicy RemoteSigned -scope CurrentUser
PS C:\Users\赵建龙> iwr -useb get.scoop.sh | iex
Initializing...
Scoop is already installed. Run 'scoop update' to get the latest version.
PS C:\Users\赵建龙> scoop list
scoop : 无法将“scoop”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检
查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ scoop list
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (scoop:String) [], ParentContain
   sErrorRecordException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\赵建龙>

**Comment by neolee** [comment]
之前安装失败了，需要删了重装，请点击这个页面上面的 Wiki，然后按照“重装 Scoop”的说明操作。

**Comment by jianlonglaoda** [comment]
已经解决了，非常感谢解答
