### ISSUE TITLE
关于 VS Code 的 Settings

### ISSUE THREAD

**Issue by xiaoerhai** [neolee/pilot#940]
我按视频里的讲解，将`Terminal:Explorer Kind`设置为`external`，`Terminal>External:Windows Exec`设置为`powershell`之后还是不能和命令行一样输出一样的结果。如下图所示：

![image](https://user-images.githubusercontent.com/48662601/72200196-533aa800-3481-11ea-9d97-d4edc4e05127.png)

另外，我应该如何确认以上2个选项是和命令行环境保持一致的？

**Comment by neolee** [comment]
你在第二个框里面输入的命令和 ConEmu 里的设置一致就行了。

你可以试试在 Code 里选择 Terminal -> New Terminal，然后用 python ... 来运行你的文件试试。

如果还是不对就算了吧，没多大影响。

**Comment by xiaoerhai** [comment]
好的，谢谢李骏老师解答。
