### ISSUE TITLE
python安装出错

### ISSUE THREAD

**Issue by de-cheng** [neolee/pilot#941]
PS C:\Users\Administrator> scoop install python37@3.7.4
WARN  Given version (3.7.4) does not match manifest ()
WARN  Attempting to generate manifest for 'python37' (3.7.4)
'python37' does not have autoupdate capability
couldn't find manifest for 'python37@3.7.4'

**Comment by de-cheng** [comment]
PS C:\Users\Administrator> scoop update
Updating Scoop...
Updating 'main' bucket...
Checking repo... ok
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
The main bucket was added successfully.
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
Scoop was updated successfully!

**Comment by neolee** [comment]
你的 #936 还没解决，当然没法继续安装东西。

如果你想解决问题，就一个问题一个问题来，而且严格按照我告诉你的去做，否则神也帮不了你。
