### ISSUE TITLE
判断一个数是否为素数的函数定义？

### ISSUE THREAD

**Issue by 1137337921** [neolee/pilot#942]
```python
from math import sqrt

def is_prime(n):
    """Return a boolean value based upon whether the argument n is a prime number."""
    if n<2:
        return False
    if n in(2,3):
        return True
    for i in range(2, int(sqrt(n))+1):
        if n % i == 0:
            return False
        
    return True
```

老师，`if n in (2,3)` 的意思就是 `n` 包括 2 和 3 这两个值吗？
`int(sqrt(n))+1`，那 `n` 开平方取整数结果是 1，`range(2, int(sqrt(n))+1)` 的结果就是 `range(2,2)`，这样理解感觉是错的，我思路哪里错的？

**Comment by neolee** [comment]
1. `(2, 3)` 是一个 tuple（上次课刚讲了），`in` 这个操作符就是判断它前面的值在不在它后面的数据容器里，所以 `n in (2, 3)` 就是判断 `n` 是不是 2 或者 3，只要是其中之一就返回 `True`，否则返回 `False`。

2. `n = 2` 时，`range(2, int(sqrt(n))+1)` 确实就是 `range(2, 2)`；`n = 100` 时，`range(2, int(sqrt(n))+1)` 就是 `range(2, 11)`；`n = 200` 时，`range(2, int(sqrt(n))+1)` 就是 `range(2, 15)`……所以这里你的计算没问题——问题是，你为什么觉得这个有问题？你觉得这里有问题，是不是其实没理解这个循环的实际含义呢？再思考一下。
