### ISSUE TITLE
Mac 安装 jupyterlab 报错

### ISSUE THREAD

**Issue by EthanGMAT** [neolee/pilot#944]
![image](https://user-images.githubusercontent.com/56030518/72203135-e1735600-34a2-11ea-825b-298562481034.png)
安装jupyter时显示如上问题，切换了网络之后还是不行。

**Comment by neolee** [comment]
网络问题。

**Comment by EthanGMAT** [comment]
> 网络问题。

我尝试了不同的网络——wifi, 手机热点，翻墙，但依然显示上面的信息。

**Comment by neolee** [comment]
说明这些网络访问官方 pip 站点都有问题。你可以尝试用国内的镜像，例如：

https://mirror.tuna.tsinghua.edu.cn/help/pypi/
