### ISSUE TITLE
关于树形数据结构的方法实现问题

### ISSUE THREAD

**Issue by spring-ap** [neolee/pilot#945]
```python
class TreeNode:
    def __init__(self, name='root', data=None, parent=None, children=None):
        self.name = name
        self.data = data
        # 确认 parent 参数是 TreeNode 类型
        assert isinstance(parent, TreeNode)
        self.parent = parent
        self.children = []
        if children is not None:
            for child in children:
                self.add_child(child)

    def add_child(self, node):
        # 1. 确认 node 参数是 TreeNode 类型
        # 2. 将要加入的子节点的 parent 属性设为自己
        # 3. 然后将其加入 children 列表
        assert isinstance(node, TreeNode)
        node.parent = self
        self.children.append(node)
```
这个TreeNode类中为什么要单独写个方法“add_child”？直接在init方法的最后的for循环中添加self.children.append（child），然后在for循环前判断child是否为TreeNode类型?

**Comment by xiaoerhai** [comment]
我也有同样的疑问。

**Comment by neolee** [comment]
因为这个类写出来给人用的呀，很可能应用场景需要创建树对象之后再调用 `add_child` 来加子节点。

其实这个类还可以写很多方法进去，比如有同学在这里做的 #933

**Comment by spring-ap** [comment]
可能我的问题没有表述清楚，我不是说这个类的作用不明白。而是不确定什么时候可以将一个点独立出来写个函数方法。比如如果我来设计这个类，可能就不会想到独立出来这个add_child方法。也无法提炼出来这个加子节点的函数功能的设计。

**Comment by neolee** [comment]
当这个方法有用的时候。

你可以仔细读一读教材，中间花了很多时间在分析树型结构有哪些常见操作，那些就是用这个结构的人会需要的功能，这些功能通常就可以考虑作为对象接口（属性或者方法）实现出来。

所以教材那一章的关键其实不是最后的代码，而是前面的抽象分析。

**Comment by spring-ap** [comment]
在 #933 中定义init方法时他增加了根节点的名字判断的条件语句，否则在实例对象时，如果不提供有效的父节点参数，无法正确执行。但是如果我要创建多个树，不可能每个树的name都叫“root”，此时根节点的实例化时，如果保证下面语句可以校验通过？
```python
# 确认 parent 参数是 TreeNode 类型
assert isinstance(parent, TreeNode)
```

**Comment by neolee** [comment]
`isinstance` 和对象属性无关，只要对象是指定类型就可以。

**Comment by spring-ap** [comment]
> `isinstance` 和对象属性无关，只要对象是指定类型就可以。

但是一个树的根节点是没有parent的，在实例一个树时，根节点如何才能正确的实例化呢？

**Comment by neolee** [comment]
噢，你问的是这个啊，这是个好问题，因为教材中的代码只是一个初步设计，所以没有严格的测试，你说的这个算 bug，如果真的继续做下去会发现这个问题，然后可以把 `__init__()` 改成类似下面的这样：

```python
def __init__(self, name='root', data=None, parent=None, children=None):
    self.name = name
    self.data = data

    if parent: 
        assert isinstance(parent, TreeNode)
    self.parent = parent

    self.children = []
    if children:
        for child in children:
            self.add_child(child)
```

**Comment by neolee** [comment]
@spring-ap 已经修正了，多谢指出 👍

**Comment by spring-ap** [comment]
老师，不客气，我是对比#933的代码和教材的代码后，发现了init方法实现有不同，在nteract环境实际运行后，一直提示我有错误，在经过思考后发现的问题。
再次证明了，代码必须经过执行检验，否则单单浏览是行不通的。
老师的修正方法也是真实巧妙！就是简单一句`if parent:`一个条件语句就修正了问题！我只是看到了问题，但是没有想到修正的简单方法。
非常感谢那位同学的代码，帮助我更好的理解如何使用代码实现，我对于将树形数据的文字描述分析抽象到代码实现过程感到非常的困难。这种困难让我想起初中时第一次学习抛物线的时候状态，仿佛就是那么一个知识点，当你真正掌握了感觉不难，但是当你没有完全理解的时候就是完全不知所措。

**Comment by neolee** [comment]
> 代码必须经过执行检验，否则单单浏览是行不通的

确实是的，尤其是和各种所谓“边界条件”有关的，很容易忽略。

所以每个问题，每个尝试都是有用的，只要有思考。

**Comment by zhigang-he** [comment]
> 
> 
> 在 #933 中定义init方法时他增加了根节点的名字判断的条件语句，否则在实例对象时，如果不提供有效的父节点参数，无法正确执行。但是如果我要创建多个树，不可能每个树的name都叫“root”，此时根节点的实例化时，如何保证下面语句可以校验通过？
> 
> ```python
> # 确认 parent 参数是 TreeNode 类型
> assert isinstance(parent, TreeNode)
> ```

我增加`if self.name != 'root':`这个判断确实是为了避开根节点不能创建的问题。这个做法其实有缺陷，只是避开了问题，并没有解决。它实际上要求实例对象初始化必须提供父节点，否则就会报错，因为`parent`默认的`None`也不等于 `'root'`。这意味着只能创建一棵树，进一步的问题是：通过`__init__`在初始化一个实例对象的时候就添加新的子节点是不可能的，因为除了根节点，任何子节点在创建的时候都已经有了父节点。我当时避开问题之后，就接着往下做了，没有再去处理。

李骏老师的解决方法就很彻底，没有了之前的限制，可以创建独立的很多棵树。随之而来的好处是：一个节点可以添加另外的一棵树；删除节点的时候也不必非要像我实现的方法一样必须同时删除节点上的整个分支。灵活性增加了许多。
