### ISSUE TITLE
运行 git push 出现了一个提示要选择凭据助手

### ISSUE THREAD

**Issue by h140** [neolee/pilot#947]
在运行 git push -u origin master 出现了一个提示，选择凭据助手，是什么意思呢，如何继续操作

<img width="792" alt="批注 2020-01-11 215831" src="https://user-images.githubusercontent.com/54472184/72205417-a7637d80-34bd-11ea-817c-4ef7641da1a0.png">

**Comment by neolee** [comment]
这个是让你选一个保存你的密码等重要涉密内容的方案，应该选缺省的那个就可以。
