### ISSUE TITLE
自动交易问题

### ISSUE THREAD

**Issue by bigbigblock** [neolee/pilot#948]
import ccxt
import time
import requests
exchange = ccxt.binance()
exchange.apiKey = '*****'
exchange.secret = '****'
balance = exchange.fetch_balance() #抓取账户余
data = exchange.fetchTicker(symbol='ONG/USDT')#抓取ONG价格

order_info = exchange.create_limit_sell_order('ONG/USDT', 10, 0.1051)

print(onder_info)

#print(data)

exit

看到了ccxt 代码，尝试了

问题 1   exchange = ccxt.binance() 是可以执行的
但 exchange = ccxt.bigone() 就报错了，应该是ccxt 没有默认支持bigone，bigone 的API 在https://big.one/api/v3/  ，应该怎么引用API?
问题 2  order_info = exchange.create_limit_sell_order('ONG/USDT', 10, 0.1051)
  提示 InvalidOrder: binance {"code":-1013,"msg":"Filter failure: MIN_NOTIONAL"}？

**Comment by neolee** [comment]
这个问题应该问 ccxt 的维护者吧？
