### ISSUE TITLE
斐波那契数列 __next__ 部分为什么不能分行写呢？

### ISSUE THREAD

**Issue by xiaoswain** [neolee/pilot#949]
老师，我自己是分行写的，怎么运算结果就是错误呢？
![数列](https://user-images.githubusercontent.com/57038028/72211881-defa1600-350d-11ea-8cf8-570250434ce5.jpg)

![数列运行结果](https://user-images.githubusercontent.com/57038028/72211883-e7eae780-350d-11ea-860f-e62246e2bd1f.jpg)

**Comment by neolee** [comment]
那两个赋值需要同时发生，如果要分行写也可以，就需要临时变量把现在的 curr 和 prev 先存一下才行。

为什么呢？你可以自己思考一下。

**Comment by gaoteng-pro** [comment]
遇到了同样的情况，正准备提问题，搜索到了你的issue。

按照老师的思路，在next的方法的第一行，把self.prev = self.curr 改成 a = self.curr ;然后第二行不动，下面再加一行 self.prev = a。 其他的都不变，运行结果一样。

猜想：同时写，init里的两个参数都可以传递到next方法中；分开写，init方法中 self.prev一开始就赋值为1，就用不了self.prev = 0这个赋值语句了，或者说是被覆盖掉了。

**Comment by gaoteng-pro** [comment]
遇到了同样的情况，正准备提问题，搜索到了你的issue。

按照老师的思路，在next的方法的第一行，把self.prev = self.curr 改成 a = self.curr ;然后第二行不动，下面再加一行 self.prev = a。 其他的都不变，运行结果一样。

猜想：同时写，init里的两个参数都可以传递到next方法中；分开写，init方法中 self.prev一开始被赋值为1，用不了一开头的self.prev = 0这个赋值语句，或者说是被覆盖掉了。然后就变成，self.prev = self.curr + self.curr，就输出了指数。

**Comment by neolee** [comment]
@gaoteng-pro 是的，差不多就是这样。以前大部分编程语言都不支持双重（多重）赋值，那时候要交换 a 和 b 两个变量的值，必须这么写：

```c
temp = a
a = b
b = temp
```

而在支持多重赋值的语言里，可以直接写：

```python
a, b = b, a
```

和本问题描述的情况是类似的。
