### ISSUE TITLE
关于 touch 指令的问题

### ISSUE THREAD

**Issue by Winsi0n** [neolee/pilot#95]
并不影响下一步操作，只是问下这里为什么会报错？

PS C:\Users\Winsion\Code\learn-git> touch README.md
touch : 无法将“touch”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称
的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ touch README.md
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (touch:String) [], CommandNotFoundExce
   ption
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by neolee** [comment]
touch 这个命令是 busybox 带的，Windows 本身没有，你可以运行 `scoop install busybox` 来安装。

或者用 `New-Item -ItemType File README.md` 实现一样的效果。

p.s. 可以看看 Wiki 里新发的支线课程第一讲。

**Comment by Winsi0n** [comment]
谢谢老师
