### ISSUE TITLE
进入编程世界第九课 数据容器之一 mk2.py加上__iter__方法才能运行

### ISSUE THREAD

**Issue by dongxia1** [neolee/pilot#950]
![image](https://user-images.githubusercontent.com/41526712/72213237-e1686a00-3525-11ea-9d99-103b8140a949.png)
在我的电脑上运行时，报错 TypeError: 'primes' object is not iterable
加上__iter__方法后能正常运行

![image](https://user-images.githubusercontent.com/41526712/72213198-6606b880-3525-11ea-8b0a-c2486f9db8ff.png)
最后面三行，没有__iter__方法时，为什么用for...in..又可以迭代呢

**Comment by neolee** [comment]
1. 图片里放不下所以省略了八卦部分（每个迭代器都有的）。

2. 讲课时我讲过 `for x in col` 循环的实现机理，其中一步需要执行 `iter(col)`，也就要求 `col` 有 `__iter__()` 方法。

3. 最后那几行可以，因为你直接手动调用 `__next__()`，绕开了 `__iter__()`。

**Comment by dongxia1** [comment]
谢谢老师解答。上面的困惑还因为教材中有下面一段话，自己没有理解透，误认为在某些情况下，可以省略__iter__。
另外，X 可以同时支持 __iter__() 和 __next__()，这样 X 既是 iterable 也是自己的 iterator，可以**省略取迭代器**的步骤，直接用 __next__() 开始，上面列出的几种内置数据容器都是这么做的。

**Comment by neolee** [comment]
嗯，这段话的本义没问题，但是确实有点模糊。

其实很简单，如果一个对象 `obj` 有 `__iter__()` 方法，就可以用 `iter(obj)` 来取得它的迭代器；如果一个对象 `obj` 有 `__next__()` 方法，就可以用 `next(obj)` 来迭代获取其下一个值。当 `obj` 放到 `for...in obj` 循环里时，两个方法都会用到。
