### ISSUE TITLE
用 pip 安装 jupyter lab 报错

### ISSUE THREAD

**Issue by EthanGMAT** [neolee/pilot#951]
![image](https://user-images.githubusercontent.com/56030518/72213745-67d57980-352f-11ea-824e-8cbad6fdf383.png)
如图，利用pip安装jupyter lab时出现如上错误。

**Comment by neolee** [comment]
你需要用 `pip3 install jupyterlab` 来安装，因为你的系统里还有个 Python 2 存在。

**Comment by EthanGMAT** [comment]
> 你需要用 `pip3 install jupyterlab` 来安装，因为你的系统里还有个 Python 2 存在。

![image](https://user-images.githubusercontent.com/56030518/72215770-a29cd900-3552-11ea-8772-4e26aa711440.png)
李老师，使用pip3 install jupyterlab会出现以上的信息。

**Comment by neolee** [comment]
咦，怎么你 pip3 也是 Python 2？你执行下面的命令看看：

```shell
which python
which python3
python -V
python3 -V
pip -V
pip3 -V
```

**Comment by EthanGMAT** [comment]
> 咦，怎么你 pip3 也是 Python 2？你执行下面的命令看看：
> 
> ```shell
> which python
> which python3
> python -V
> python3 -V
> pip -V
> pip3 -V
> ```

![image](https://user-images.githubusercontent.com/56030518/72215857-ee9c4d80-3553-11ea-8c18-c844751ba394.png)
在命令行中输入上述指令后的信息。
![image](https://user-images.githubusercontent.com/56030518/72215893-75e9c100-3554-11ea-93ff-ceb307f427b1.png)
我之前想让命令行默认能打开Python3.7，于是按照网上的说明，更改了.bash_profile文件，不知道是不是跟这个有关系？

**Comment by neolee** [comment]
你的 pip3 指向的路径不对（指向了 Python 2 的路径）。从你的 .bashrc 看你安装过 Anaconda，这东西表面上对初学者很傻瓜很一键，但其实用的越久问题越多。

你再执行下：

```shell
which pip
which pip3
```

**Comment by EthanGMAT** [comment]
![image](https://user-images.githubusercontent.com/56030518/72220787-41dfc180-358f-11ea-8958-21ac858c1e54.png)
执行which pip和which pip3之后显示如图。

**Comment by EthanGMAT** [comment]
![image](https://user-images.githubusercontent.com/56030518/72220787-41dfc180-358f-11ea-8958-21ac858c1e54.png)
执行which pip和which pip3之后显示如图。

> 你的 pip3 指向的路径不对（指向了 Python 2 的路径）。从你的 .bashrc 看你安装过 Anaconda，这东西表面上对初学者很傻瓜很一键，但其实用的越久问题越多。
> 
> 你再执行下：
> 
> ```shell
> which pip
> which pip3
> ```

![image](https://user-images.githubusercontent.com/56030518/72220872-52446c00-3590-11ea-8f5e-bfc14a8453d9.png)

**Comment by neolee** [comment]
你的 pip3 的位置不对，为啥你会装了个 pip3 在 /usr/bin 下面呢，这里如果有 pip3 一般是 Xcode 装的，但你的 'pip3 -V' 信息显示了并不是这样。

所以结论是，不知道什么东西在你的 /usr/bin 下面装了 pip3（可能还有别的东西），而这套东西是有问题的，造成你安装 Python 包有问题。

最好先把你的环境清理好。

**Comment by EthanGMAT** [comment]
> 你的 pip3 的位置不对，为啥你会装了个 pip3 在 /usr/bin 下面呢，这里如果有 pip3 一般是 Xcode 装的，但你的 'pip3 -V' 信息显示了并不是这样。
> 
> 所以结论是，不知道什么东西在你的 /usr/bin 下面装了 pip3（可能还有别的东西），而这套东西是有问题的，造成你安装 Python 包有问题。
> 
> 最好先把你的环境清理好。

老师，我删了电脑上Anaconda，重新卸载并安装了pip，但是依然显示之前的错误，如何才能回到之前没有安装Python和pip的状态呢？

**Comment by neolee** [comment]
你咋卸载和安装 pip 的？

还有你的 `.bash_profile` 清理了么？

**Comment by EthanGMAT** [comment]
> 你咋卸载和安装 pip 的？
> 
> 还有你的 `.bash_profile` 清理了么？

![image](https://user-images.githubusercontent.com/56030518/72236372-89a72d00-3611-11ea-908f-c937bb3e3261.png)

1. 我用了sudo easy_install pip命令，现在的Python和pip版本是这样的。2. .bash_profile中内容全部删除了。

**Comment by neolee** [comment]
你的环境现在比较乱，比较难准确的给出建议，但是大体思路是这样：

1. 首先确保 /usr/bin 下面没有乱七八糟的东西，如果你没装过 Xcode 的话，/usr/bin 下不应该有 python3 和 pip3；
2. 按照环境配置指南安装 Homebrew，并用它安装 python（3.7.4），装好之后它会帮你配置系统 PATH，让 /usr/local/bin 优先，从而使用 Homebrew 安装在 /usr/local/bin 下面的 python3 和 pip3。

一切顺利的话，你执行 `which python3` `which pip3` 结果都会显示 `/usr/local/bin` 下面的，而 `pip3 -V` 应该显示 `pip 19.2.3 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)`。

**Comment by EthanGMAT** [comment]
> `which python3` `which pip3`

老师，我的问题解决了。我按照<编程环境配置指南>重新安装了一遍，中间没有出现什么问题。现在回头来看的话，应该是在安装homebrew上出了问题，因为我电脑上之前安装过homebrew，在这一步上，我可能没有严格遵照指南里的步骤，希望对其他人有帮助。
