### ISSUE TITLE
平方数序列之 return 和 print

### ISSUE THREAD

**Issue by gaoteng-pro** [neolee/pilot#952]
[103]:

```
def f(i):
    for n in range(i):
        if n<=i:
            n+=1
            return n**2
```

[104]:

```
f(3)
```

[104]:

```
1
```

[105]:

```
f(5)
```

[105]:

```
1
```
想依照老师的平方数序列的类写一个平方数序列的函数，但无论函数的参数i的值是多少，返回值都是1，后来把return换成print（）就可以了，return时的返回值为什么都是1？

**Comment by neolee** [comment]
`return` 终止函数运行并返回其后的值。你的 for 循环第一次运行就碰到 `return`，然后返回一个 1 整个函数就结束了。

所以你这是想写个什么？生成器么？如果写生成器，就不能用 `return` 而要用 `yield`，从你的表述看你对 `return` 是干啥的还不太明白，如果从课程一开始按部就班学到现在的，应该不会这样。

**Comment by gaoteng-pro** [comment]
开始的有些晚，现在确实在赶进度。今天练习到这里了，看到老师写平方序列的类，然后就想着依葫芦画瓢写一个平方序列的函数，然后就出现了上面的问题。

确实是对return这个语句理解有偏差，开始认为return只是返回一个值，print也是返回一个值，所以认为上面的函数中for循环会正常运行循环。现在明白了：return是返回一个值，并且**结束这个函数**。

最后想问下老师，python能不能在运行程序的时候，看到程序具体的执行顺序。
比如写了5行代码，运行的时候可以看到这5行代码的执行顺序，例如先是第一行代码第二行第三行第四行，然后是第二行第三行第四行，再然后是第二行第三行第四行，最后是第五行，即1-2-3-4-2-3-4-2-3-4-5。用高亮显示在代码上，这样我们可以更好的看到程序的具体执行过程。

**Comment by neolee** [comment]
`return` 是返回一个值（给函数的调用端），`print()` 是个函数，会在命令行打印出值，这俩完全不同，我在课上专门强调过的。

基础很重要，一定要打扎实。

你问的最后那个问题可以看支线课程5，我在你的另个 issue 里正好也给了这个建议。

**Comment by gaoteng-pro** [comment]
嗯，知道print（）是个函数，听音频的时候，确实有听你讲有同学在issues上提问return和print的区别，你说这两者差别很大，没有写return的时候，会默认是return None。以为自己懂了，今天才知道原来自己不知道自己不知道。
