### ISSUE TITLE
迭代器中的循环

### ISSUE THREAD

**Issue by gaoteng-pro** [neolee/pilot#953]
```python
class squares:
    # 这次我们的初始化方法增加了一个参数 high
    # 初始化时将其保存在一个新增实例变量 self.high 中，限制迭代时 self.base 不能超过这个数
    def __init__(self, high):
        self.base = 0
        self.high = high
        
    def __iter__(self):
        return self

    # 在迭代器主方法里加入判断，如果 self.base 超过了 self.high 就扔出一个 StopIteration 异常
    def __next__(self):
        self.base += 1
        if self.base > self.high:
            raise StopIteration
        else:
            return self.base * self.base

    next = __next__

# 这次我们实例化时要传入一个参数来指定 self.high 的值
# 这将使得我们调用三次 next()，输出 1，4，9 之后再调用就不会有返回值
iter = squares(3)
```

在 p2-7-iterable-iterator 迭代器一平方数序列的例子中，“这将使得我们调用三次 next()，输出 1，4，9 之后再调用就不会有返回值”，**__next__ 函数没有 while 循环是如何实现三次调用的**？

**Comment by neolee** [comment]
`__next__()` 每一次被调用就返回一个值而已，为啥需要用 `while` 循环？

**Comment by gaoteng-pro** [comment]
iter=squares(3)，参数3传递给self.high，self.high在if self.base >self.high做条件判断，当self.high=3时，if...else...条件判断只执行else下面的函数体一次，也就是返回1结束，为何会返回1，4，9呢？

**Comment by neolee** [comment]
你再仔细想想，返回的是什么，`self.base` 和 `self.high` 又是什么。

支线课程第五讲 - Visual Studio Code 中有介绍如何用 VSCode 进行代码的单步调试，你不妨试试，看看程序执行的顺序和你想的是否一样，各个变量的值是否一样。

**Comment by gaoteng-pro** [comment]
next函数没有while循环，for in 语句相当于一个while，所以才不断循环，输出三个数而不是一个。
