### ISSUE TITLE
反转一个字符串，尾部出现]

### ISSUE THREAD

**Issue by wangnanqiang** [neolee/pilot#954]
使用了一个strip去掉了],打印出来的字符串还是有]。
第一个函数fanzhuang不正常，出现问题。
第二个函数fanzhuang1正常。

**Comment by neolee** [comment]
我稍微改了下你的代码，主要是名字更清晰一点，是下面这样：

```python
s = 'abcdefghijklm'

def my_reverse1(s):
    l = list(s)
    l.reverse()
    s1 = str(l)
    for c in s1:
        print(c.strip("', []"), end='')
    return c

def my_reverse2(s):
    l = list(s)
    l.reverse()
    return ''.join(l)

print(my_reverse1(s))
print(my_reverse2(s))
```

第二个版本是没问题的，也是“字符串 -> list -> 字符串”的标准做法，主要说说第一个版本。

首先，第一个版本是走了很大的弯路的，核心问题是 `s1 = str(l)` 这一句，做的完全不是你想做的事情，出来一个下面这样的字符串：

`['m', 'l', 'k', 'j', 'i', 'h', 'g', 'f', 'e', 'd', 'c', 'b', 'a']`

和你想要的相去甚远，所以你就用 `strip` 来把里面所有你不要的字符（`', []`）都删掉，这就是制造了一个问题，然后去解决这个问题——为什么不干脆就别制造那个问题呢？所以我上次告诉你第二个版本那才是正确的思路。

然后，如果非要这样走，也不是不行，也可以走通，你在函数里用了一个 `for` 循环来遍历 s1，然后用 `strip` 来把去掉不要的字符，但是你的代码有两个问题：

1. 你的函数应该返回输入字符串的倒序，但是你现在用 `print()` 来打印其中的一个个字符，而不是返回一个完整的倒序字符串给调用端，这个函数实际含义就变了，它变成了“倒序打印输入字符串”。我反复说过，`print()` 不等于 `return`，这俩完全不同。

2. 最后 `return c` 是多余的，等于把字符串 `s1` 最后的那个 `']'` 返回了，然后在调用端你又用了 `print(my_reverse1(s))` 把这个 `]` 打印了出来，这就是你看到多出来的那个字符。

总的来说，第一个函数的思路问题比较大，完全不应该这么写。

**Comment by wangnanqiang** [comment]
我懂了,就是return c这一步，我写的这多余的一步，就是假如我不写，删掉return c，会返回mlkjihgfedcbaNone，我不想要这个None，我希望结果是mlkjhgfeba，有没有办法去掉None？

**Comment by neolee** [comment]
那你就要想办法把逆序之后的字符串组合成一个字符串再 return 出来呀，所以还不如用第二个版本。

所以我前面已经解释了，第一个函数整个思路就不对……

**Comment by wangnanqiang** [comment]
嘻嘻，我懂了，十分感谢。
