### ISSUE TITLE
第十课 数据容器之二 在线课程bug

### ISSUE THREAD

**Issue by wessyde** [neolee/pilot#955]
李老师，践行群中的第十课  数据容器之二  在线课程里第一张图错误如下：
![20200113012249](https://user-images.githubusercontent.com/48742886/72222820-e7049500-35a3-11ea-82b7-9961e41ba942.jpg)

**Comment by neolee** [comment]
嗯嗯，这个我已经发现了 😃

**Comment by wessyde** [comment]
好的
