### ISSUE TITLE
MySQL 环境安装问题

### ISSUE THREAD

**Issue by dingkunpeng** [neolee/pilot#956]
![Snip20200113_6](https://user-images.githubusercontent.com/24670493/72247361-abafa800-362f-11ea-8934-b3d22e3f8102.png)

>brew install mysql@5.7
brew services start mysql@5.7

运行上面代码之后,我输入:

 >mysql -uroot

显示 zsh: command not found: mysql,不知道怎么回事?

**Comment by neolee** [comment]
如 Homebrew 的提示所述，你需要把 `/usr/local/opt/mysql@5.7/bin` 加入到系统 PATH 环境变量中：

```
export PATH=/usr/local/opt/mysql@5.7/bin:$PATH
```

你可以在命令行运行这句命令，也可以将其加入到你的 `.zshrc` 或者 `.bashrc` 配置中（看你用的哪个 Shell）。

然后再运行 `mysql` 就没问题了。

**Comment by tyler1zhang** [comment]
李骏老师，你好。 我用homebrew安装了mysql之后，运行 `mysql -uroot` 也出现了上面的错误。然后我就上网去查找解决方案，照搬如下：
<img width="756" alt="Screen Shot 2020-03-07 at 10 32 36 PM" src="https://user-images.githubusercontent.com/49228317/76145423-470b4980-60c4-11ea-82b0-ad7bd797aab0.png">
这里面用的安装目录是`/usr/local/mysql/bin`,而我真正的安装目录却是 `/usr/local/opt/mysql@5.7/bin`，所以这次并没有成功。但当时我并不懂，于是我找issue，看到了上面的解答。所以就去找mysql安装成功后的提示，运行了`export PATH="/usr/local/opt/mysql@5.7/bin:$PATH"`如图：
<img width="802" alt="Screen Shot 2020-03-07 at 10 33 20 PM" src="https://user-images.githubusercontent.com/49228317/76145490-be40dd80-60c4-11ea-85e3-22a374505b16.png">
可是这个时候出现了另外一个error，`ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)` 对于这个error，我尝试follow stackoverflow 的做法，做了如下尝试，但是并没有成功。
<img width="663" alt="Screen Shot 2020-03-07 at 10 43 24 PM" src="https://user-images.githubusercontent.com/49228317/76145532-1841a300-60c5-11ea-8d53-d285ed6cf1ab.png">
不知问题出现在哪里，希望老师解惑。 谢谢

**Comment by neolee** [comment]
@tyler1zhang 

首先，第一个问题是要把 `/usr/local/opt/mysql@5.7/bin` 加到你的 PATH 变量中，这个前面我的回答里已经写了，执行下面的命令就可以了：

```shell
export PATH=/usr/local/opt/mysql@5.7/bin:$PATH
```

第二个问题应该是你的 MySQL 服务没有起来，你可以执行：

```shell
brew services list
```

这个命令会列出所有通过 Homebrew 安装的服务，里面应该有一个 `mysql@5.7`，而且状态应该是 `stopped`，如果是这样，你就可以用下面的命令来启动它：

```shell
brew services start mysql@5.7
```
