### ISSUE TITLE
老师，我电脑上的这个配置以后会有麻烦吗？

### ISSUE THREAD

**Issue by Zhang-Jinlei** [neolee/pilot#957]
# 老师好：

我是之前先安装的 python3 ，之后才安装的 brew。jupyterlab 也装好了能运行，看了下和 python3 装在一个目录下（理论上就应该在一起）。就是想问一下老师，我目前的这种配置以后会有麻烦吗？谢谢！

附截图：
1、
![image](https://user-images.githubusercontent.com/28210665/72307837-ab0e2480-36b6-11ea-9c77-dba00f9e3347.png)

2、
![image](https://user-images.githubusercontent.com/28210665/72307908-ca0cb680-36b6-11ea-84ed-5d7c368e342f.png)

**Comment by neolee** [comment]
只要你 Jupyter Lab 运行正常，其运行的 Python 来自 Homebrew，就问题不大。

**Comment by Zhang-Jinlei** [comment]
好的，谢谢老师！
