### ISSUE TITLE
用 scoop 安装 git 提示操作超时

### ISSUE THREAD

**Issue by amYueTao** [neolee/pilot#958]
![无标题](https://user-images.githubusercontent.com/29993272/72310806-b1ec6580-36bd-11ea-9105-860831346ced.png)

**Comment by neolee** [comment]
网络问题。

**Comment by xin-yanyu** [comment]
我在单位和家里安装git都是出现超时情况。解决办法：
1、先scoop list ，将显示安装失败的文件用“scoop uninstall 文件名” 删除，
2、 scoop install aria2 安装多线程下载
3、用scoop search git 找到库
3、尝试选择不同的网络。我在家里就分别采用电信网络、广电网络才搞定的。除了固定网络外，我还尝试用手机作为热点，用移动、或联通无线热点连接wifi下载软件的。
4、scoop install git 用多进程安装下载也会出错。出错后，输入scoop uninstall git 清除信息。再重新用scoop search git 找到库，scoop install git 安装。如此出错，反复执行第四步骤。因为多线程下载接收到的中间数据是保留下来的。如此多次后，网络数据会逐渐下载完成的。
5、安装完成后，运行scoop checkup。如果出现系统上建议你命令：
Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1。请点击powershell  菜单的右上角的+号，选择shells，再选admin。在admin的窗口下运行那个建议的命令。
6、其他软件如果网络下载不成功，运行多次后，多线程下载基本会自动解决问题。
