### ISSUE TITLE
嵌套函数最后 return 为啥要返回内函数

### ISSUE THREAD

**Issue by wangnanqiang** [neolee/pilot#959]
嵌套函数最后return 为啥要返回内函数，不返回结果都是一样的，那为啥要返回，返回内函数本身到底有啥意义
![图片](https://user-images.githubusercontent.com/53247740/72316754-13b6ca80-36d2-11ea-969c-6684587f4d8b.png)

**Comment by neolee** [comment]
我想你在说的是“装饰器（*decorator*）”。你需要了解 decorator 是为什么而生的，它的存在是为了解决什么问题。可以看看 S2-13。

**Comment by wangnanqiang** [comment]
好的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Neo Lee"<notifications@github.com&gt;; 
发送时间: 2020年1月14日(星期二) 下午2:18
收件人: "neolee/pilot"<pilot@noreply.github.com&gt;; 
抄送: "?"<1215369914@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [neolee/pilot] 嵌套函数最后 return 为啥要返回内函数 (#959)




我想你在说的是“装饰器（decorator）”。你需要了解 decorator 是为什么而生的，它的存在是为了解决什么问题。可以看看 S2-13。
