### ISSUE TITLE
关于touch指令的问题 

### ISSUE THREAD

**Issue by Winsi0n** [neolee/pilot#96]
PS C:\Users\Winsion\Code\learn-git> touch README.md
touch : 无法将“touch”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称
的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ touch README.md
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (touch:String) [], CommandNotFoundExce
   ption
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by neolee** [comment]
Duplicate of #95
