### ISSUE TITLE
“hook”  和 “pipeline” 在编程中代表的是什么意思？

### ISSUE THREAD

**Issue by Zhang-Jinlei** [neolee/pilot#961]
老师好！

不知道我这个问题在这里问合适不合适，但我真的很想问一下。因为有的时候会看到这两个词，想麻烦老师通俗的解释一下，谢谢老师！

我自己调研了一下，关于“hook”的：

https://stackoverflow.com/questions/467557/what-is-meant-by-the-term-hook-in-programming

可是还是没怎么看懂，hook 到底在代码中起到什么作用？老师能类比一下吗？

**Comment by neolee** [comment]
这俩都是比较常见的概念，理解概念一般来说最好的办法就是理解概念背后的应用场景，这也是对初学编程的同学来说比较有挑战的点，我下面尝试解释一下。

一、关于 *hook*

一般来说 *hook* 是指程序 A 在程序 B 里埋入的一段代码，当程序 B 运行到某种特定状态，或者某个特定条件成立，就会调用 A 埋入的那段代码。

这种 *hooking* 是为了啥呢？一般来说是程序 B 希望把一些定制能力开放给用户或者第三方的开发者。举个例子来说，比如 GitHub 上有很多很多的 git repo，每个 repo 都有很多人提交代码，而且很多时候这些人之间互相不认识，假如我希望我的某个 repo，只要有人提交了代码就自动运行一个测试程序，然后把测试结果发给我，这件事 GitHub 自己要做就不现实，因为它不知道我想如何测试，也不知道我想根据测试结果做什么，这时候 GitHub 的解决方案就是设计一个 *hook API*，允许我写一个“钩子函数（*hook*）”，并在我的 repo 的 “收到新 commit” 这个 “事件（*event*）” 上 “注册（*register*）” 这个钩子函数，以后 GitHub 只要收到该 repo 的 commit 就会触发这个钩子函数，执行我写的代码，我想做什么就我自己控制了。

GitHub 事实上确实有这个功能（实际上是 git 底层就支持的），提供了 commit 前后的钩子接口，commit 前的钩子里你甚至可以根据运行情况决定是不是直接拒绝这个 commit。

还有一种情况，钩子的接口不是程序 B 自己提供的，而是操作系统提供的机制，甚至是黑客强行在程序 B 中注入的，这就涉及到一些特定技术了，在特定环境下也是能做到的。不过，好孩子不干这个 ^_^

二、关于 *pipeline*

所谓 *pipeline*，就是程序 A 的输出作为程序 B 的输入，程序 B 的输出又作为程序 C 的输入，如此这般可以一直串下去；或者更微观一点，函数 A 的输出作为函数 B 的输入，函数 B 的输出又作为函数 C 的输入。

前面一种 *pipeline*，最早在 Unix 上被设计和实现，之后所有类 Unix 的操作系统上都支持，比如下面这个命令：

```shell
ls -la | grep py
```

就是两个命令（程序）组成的 *pipeline*：第一个命令 `ls -la` 以详细列表方式列出当前目录下所有文件和目录（包括隐藏文件），然后 `|` 是 *pipeline* 操作符，表示把前一个程序的运行结果送给后一个程序作为输入，而后一个命令（程序） `grep py` 在里面查找带 “py” 的行。最后这个组合起来的 *pipeline* 输出的是当前目录下所有包含 “py” 的文件。

熟练的 Unix 命令行用户可以用 *pipeline* 串起很多基本命令来完成复杂的工作，效率比 GUI 高得多。

我们编程的时候，采用类似的思维方式，可以设计出类似的处理模式，比如读取一个用户输入，一个函数检查输入是否合法，第二个函数去除里面的空格，第三个函数从里面分离出特定的几个关键属性，这几个函数可以首尾相连，前一个的输出作为后一个的输入，这就是名为 *pipeline* 的设计模式。

**Comment by Zhang-Jinlei** [comment]
非常感谢老师细致的解答，老师回答问题的方式也是我最喜欢的。果断在群里用 BOX “狠狠” 地砸向老师。（^_^，小小心意，谢谢老师！）

**Comment by neolee** [comment]
搞懂了就好 😀
