### ISSUE TITLE
运行 Scoop 的安装命令出错

### ISSUE THREAD

**Issue by de-cheng** [neolee/pilot#962]
PS C:\Users\Administrator> iwr -useb get.scoop.sh | iex
iwr : The underlying connection was closed: An unexpected error occurred on a send.
At line:1 char:1
+ iwr -useb get.scoop.sh | iex
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-W
   ebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebR
   equestCommand

**Comment by neolee** [comment]
网络问题。实际上你提过好几个问题，都是一样的问题，你的网络访问 Scoop 的网站是有问题的，要么换网络要么挂代理，否则总是会有问题的。
