### ISSUE TITLE
配置环境出错

### ISSUE THREAD

**Issue by hongxiaojun** [neolee/pilot#964]
配置好了jupyter 然后删除了Code这个文件夹，重新打开终端无法调用jupyter 。提示如下
[C 21:02:40.822 LabApp] Bad config encountered during initialization:
[C 21:02:40.822 LabApp] Could not decode '\xe6\x9c\xaa\xe5\x91\xbd\xe5\x90\x8d' for unicode trait 'untitled_notebook' of a LargeFileManager instance.

**Comment by neolee** [comment]
信息太少，无法判断。

**Comment by maomaomizi** [comment]
建议看一下老师讲支线课程第三讲 jupyter lab   这是链接https://www.bilibili.com/video/av74039311
看完会通透很多

**Comment by hongxiaojun** [comment]
> 建议看一下老师讲支线课程第三讲 jupyter lab 这是链接https://www.bilibili.com/video/av74039311
> 看完会通透很多

感谢 折腾了俩个晚上，搞定啦。

**Comment by hongxiaojun** [comment]
> 信息太少，无法判断。

感谢老师回复。在pip和pip3上忽略了，卡在这一步。后面重新阅读文档才发现这个错误。
