### ISSUE TITLE
迭代器 iter语句中的返回自己

### ISSUE THREAD

**Issue by gaoteng-pro** [neolee/pilot#966]
```python
def __iter__(self):
        return self

def _think（self,s）:
      return s
```

上面是迭代器中的返回自己，下面是对话机器人例子中 think 方法的返回自己。

同样是返回自己，两者的语法不同，think 方法中的返回自己好理解，迭代器中返回自己，老师例子中的注释是这样的：  __iter__() 返回迭代器，这里就是自己，我们直接返回 self。

都是返回自己，迭代器返回self和think方法中返回的s，**有啥不同**？是一个没输入参数一个有输入参数的写法吗？不是太明白。

**Comment by neolee** [comment]
我编辑了你的问题，贴代码的时候使用 Markdown 的代码标签，否则显示不对也不好看。

回到你的问题，我还是那句话，从头开始一课一课的学，群里的课程从头开始仔细听，从最简单的程序开始自己动手写，动手 run，搞懂每一行代码的含义，搞懂程序运行输出的每一个结果。不然是浪费时间。

很明显，`_think()` 方法并不是返回“自己”，这个方法的第一个参数 `self` 是对象实例的提前引用，第二个参数 `s` 是一个输入的字符串，`_think()` 方法根据这个输入字符串思考应该如何回应，并返回回应字符串。在 `Bot` 父类中这个“思考”很简单，就是你说啥我也说啥，直接返回输入的字符串 s。

`__iter__()` 方法要求返回一个迭代器 iterator，也就是支持 `__next__()` 方法的对象，所以我们简单地返回 `self` 就可以了。

上述答案，只要按部就班学下来的，一定是清楚的。而你的问题，感觉对变量、函数、对象的基本概念还没理解。建议从头学。
