### ISSUE TITLE
安装 Scoop 出错：iex 使用2个参数调用 ExtractToDirectory 时发生异常

### ISSUE THREAD

**Issue by Zhang-Jinlei** [neolee/pilot#967]
# 老师好：

在 win10 我的安装 scoop 出现了如标题所示的问题。搜了一下 Closed Issues 只找到了"DownloadFile"  错误，没发现我这种错误。根据查看的 Issues，我进行了如下操作，还是没有安装成功，所以才来这里问一下老师。 （感觉不像是网络问题，我已经科学上网了）

截图：
![图片](https://user-images.githubusercontent.com/28210665/72489931-a4b3b000-3850-11ea-9bdd-ea91d324d18c.png)

说明：
1、已经使用了**管理员**权限；
2、在卸载 scoop 的时候，我用 scoop uninstall scoop不成功，在 Issues 中查看到使用  del .\scoop -Force 方法卸载，所以就有了上图的指令；
3、输入 Get-ExecutionPolicy 返回的是 **RemoteSigned**；
4、 输入 $PSVersionTable.PSVersion.Major 返回的也是 **5**；
5、以上测试是在重启了之后重新敲入的，我原来以为报错的信息 **“...由另一个进程使用...”**重启一下会好 ，但是发现还是老样子；
6、最后又重新卸载了一边 scoop。

**Comment by neolee** [comment]
首先确保完整的删除 C:\Users\admin\scoop 这个目录，无论你用文件管理器还是命令行，都可以，如果用命令行 `del .\scoop -Force` 的话，记得输入A表示全部确认删除。

然后重新执行 Scoop 安装命令。

**Comment by neolee** [comment]
不是，你上面的截图显示 scoop 确实删除了，但是安装时还是出现了这个错误，目前还不知道为什么。

**Comment by Zhang-Jinlei** [comment]
好的老师，之前看到一个 Issue 里面提到过**关闭防火墙**和**杀毒软件**的。我这台是公司的电脑，确实安装了防病毒之类的软件：

![图片](https://user-images.githubusercontent.com/28210665/72515982-dc8c1900-388b-11ea-9b85-b738ab85c40a.png)

那可能就是这个原因吧，我关不了，看来公司的电脑配置不了了，哎！

谢谢，老师！

**Comment by Zhang-Jinlei** [comment]
老师，这个遗留的问题，今天我貌似弄好了，处理方法大致的如下：
1、我对提示的错误“ExtractToDirectory”分析了一下，发现“scoop-master”已经下载下来了，只是没有解压。然后我手动将其解压。
2、之后尝试搜索“手动安装scoop”，看到有人用这个指令“ iex xxxxx.ps1”，我 cd 到有install.ps1文件的位置试了一下。发现貌似有曙光。
3、之后就是根据提示先删除掉_temp/current/...（大概是这个路径）中之前解压“scoop-master”文件夹，然后 copy 一份和 buckets 放在一个目录下，重复执行一遍“ iex install.ps1”，然后在scoop update 一下，貌似就好使了。
4、老师，我可能说的有点混乱，但大致就是这么个流程，按照错误提示一点点的最后就能安装成功。最关键的是： cd  C:\Users\admin\scoop\scoop-master\bin  powershell（在此目录下打开powershell），然后 iex install.ps1。
最后，附两张图，遇到错误的小伙伴可以来我这里参考一下，同时我记录给我自己看：
![图片](https://user-images.githubusercontent.com/28210665/76731604-c241bf00-6798-11ea-940c-0a0388427619.png)

![图片](https://user-images.githubusercontent.com/28210665/76731643-dc7b9d00-6798-11ea-90e4-1f2913a2fe74.png)

**Comment by neolee** [comment]
你能沿着这条路径走完，已经好厉害了！

这里的关键，可能是你的网络现在比较好用，以及你用其他方法装好了 git。

**Comment by BrandonBocheng** [comment]
@Zhang-Jinlei 您好，我按照你图上的cmd命令执行，在报错ParentContainsErrorRecordException之后就不知道怎么走了。我的powershell执行情况和我目前的scoop文件结构情况如下：

![安装scoop报错](https://user-images.githubusercontent.com/42810939/115533834-b5f83180-a2c9-11eb-9cbf-9503c5ea368d.jpg)
![scoop安装的文件结构](https://user-images.githubusercontent.com/42810939/115533840-b8f32200-a2c9-11eb-8a0f-3bb22157f7c6.jpg)

望能解答

**Comment by iamjinlei0312** [comment]
> @Zhang-Jinlei 您好，我按照你图上的cmd命令执行，在报错ParentContainsErrorRecordException之后就不知道怎么走了。我的powershell执行情况和我目前的scoop文件结构情况如下：
> 
> ![安装scoop报错](https://user-images.githubusercontent.com/42810939/115533834-b5f83180-a2c9-11eb-9cbf-9503c5ea368d.jpg)
> ![scoop安装的文件结构](https://user-images.githubusercontent.com/42810939/115533840-b8f32200-a2c9-11eb-8a0f-3bb22157f7c6.jpg)
> 
> 望能解答

@BrandonBocheng 时隔1年多，我努力回忆了一下我当时多的场景，发现已经完全没有印象了。然后，我尝试着从零开始分析这个问题。我发现：你使用的路径和我截图中的路径是不一样的，虽然最后两级目录都是：\scoop-master\bin

你再往上看看我们之间的路径是否是有差异的呢～

**Comment by iamjinlei0312** [comment]
> 你能沿着这条路径走完，已经好厉害了！
> 
> 这里的关键，可能是你的网络现在比较好用，以及你用其他方法装好了 git。

哇，被老师说「好厉害」，好开心呀！

老师说的对，关键确实是 **可能是你的网络现在比较好用，以及你用其他方法装好了 git**。

时隔1年多，今天要不是 @BrandonBocheng 问问题，我可能会一直忘记回复老师，我觉得这样不好，没礼貌。

**Comment by BrandonBocheng** [comment]
> > @Zhang-Jinlei 您好，我按照你图上的cmd命令执行，在报错ParentContainsErrorRecordException之后就不知道怎么走了。我的powershell执行情况和我目前的scoop文件结构情况如下：
> > ![安装scoop报错](https://user-images.githubusercontent.com/42810939/115533834-b5f83180-a2c9-11eb-9cbf-9503c5ea368d.jpg)
> > ![scoop安装的文件结构](https://user-images.githubusercontent.com/42810939/115533840-b8f32200-a2c9-11eb-8a0f-3bb22157f7c6.jpg)
> > 望能解答
> 
> @BrandonBocheng 时隔1年多，我努力回忆了一下我当时多的场景，发现已经完全没有印象了。然后，我尝试着从零开始分析这个问题。我发现：你使用的路径和我截图中的路径是不一样的，虽然最后两级目录都是：\scoop-master\bin
> 
> 你再往上看看我们之间的路径是否是有差异的呢～

您好，我通过iex .\install.ps1安装scoop的时候报了MethodInvocationException之后的文件目录就是这样
![scoop安装报错后的初始文件结构](https://user-images.githubusercontent.com/42810939/115642943-70317c80-a34e-11eb-8bb9-00591b0c5779.jpg)

**Comment by iamjinlei0312** [comment]
> > > @Zhang-Jinlei 您好，我按照你图上的cmd命令执行，在报错ParentContainsErrorRecordException之后就不知道怎么走了。我的powershell执行情况和我目前的scoop文件结构情况如下：
> > > ![安装scoop报错](https://user-images.githubusercontent.com/42810939/115533834-b5f83180-a2c9-11eb-9cbf-9503c5ea368d.jpg)
> > > ![scoop安装的文件结构](https://user-images.githubusercontent.com/42810939/115533840-b8f32200-a2c9-11eb-8a0f-3bb22157f7c6.jpg)
> > > 望能解答
> > 
> > 
> > @BrandonBocheng 时隔1年多，我努力回忆了一下我当时多的场景，发现已经完全没有印象了。然后，我尝试着从零开始分析这个问题。我发现：你使用的路径和我截图中的路径是不一样的，虽然最后两级目录都是：\scoop-master\bin
> > 你再往上看看我们之间的路径是否是有差异的呢～
> 
> 您好，我通过iex .\install.ps1安装scoop的时候报了MethodInvocationException之后的文件目录就是这样
> ![scoop安装报错后的初始文件结构](https://user-images.githubusercontent.com/42810939/115642943-70317c80-a34e-11eb-8bb9-00591b0c5779.jpg)

那可能就需要你自己耐心地根据提示一项一项的排查了，我当时也是这么做的，可能会感觉比较繁琐吧，但弄通了还是很开心的一件事。

这里列举的是我当时遇到的可以参考的一种情况，所以，你要具体分析一下你的问题，加油。

**Comment by iamjinlei0312** [comment]
@BrandonBocheng 关于之前说的路径，我记得好像是我当时根据错误提示，是要找到 `install.ps1` 这个文件。然后发现这个文件在 `C:\Users\admin\scoop\scoop-master\bin` 这个路径下，之后我就解决了问题。

![企业微信截图_20210422134101](https://user-images.githubusercontent.com/28210665/115661678-66b90c00-a370-11eb-9f52-885e316eb270.png)
这是我现在电脑上的截图

**Comment by BrandonBocheng** [comment]
> @BrandonBocheng 关于之前说的路径，我记得好像是我当时根据错误提示，是要找到 `install.ps1` 这个文件。然后发现这个文件在 `C:\Users\admin\scoop\scoop-master\bin` 这个路径下，之后我就解决了问题。
> 
> ![企业微信截图_20210422134101](https://user-images.githubusercontent.com/28210665/115661678-66b90c00-a370-11eb-9f52-885e316eb270.png)
> 这是我现在电脑上的截图

您好，我找到了原因：我本机.NET Framework的版本是3.5，而安装scoop的要求是,NET Framework4.5+。升级完了之后直接安装就没问题了

**Comment by iamjinlei0312** [comment]
@BrandonBocheng 可以，恭喜你！
