### ISSUE TITLE
关于列表切片下标[m:n]为负整数的问题

### ISSUE THREAD

**Issue by shujiaojunxiong** [neolee/pilot#968]
老师在教材p2-8-list-列表切片中，提到“在列表下标中使用 [m:n]（m 和 n 都是非负整数）”
![image](https://user-images.githubusercontent.com/53084501/72507727-6386c480-387f-11ea-8e0e-4c4c7d791d93.png)

但是测试发现，m和n可以为负数，是不是写错了，还是我哪里理解错了？
![image](https://user-images.githubusercontent.com/53084501/72514754-dd23b000-3889-11ea-979a-4661966d01a3.png)

**Comment by neolee** [comment]
嗯，是个 bug，已经修正，多谢指出~
