### ISSUE TITLE
关于列表切片后产生的新列表对象的赋值疑问

### ISSUE THREAD

**Issue by shujiaojunxiong** [neolee/pilot#969]
<img width="908" alt="360截图17860531110126107" src="https://user-images.githubusercontent.com/53084501/72526649-e1f45e00-38a1-11ea-8a24-a41f45800cd0.png">
在教材p2-8-list-列表切片中，老师说：

> 使用切片的方式会生成原来列表一个片段组成的新列表对象，原列表不会变化。

但是紧接着老师又说：
> 把列表切片放在赋值语句的左边，给列表的某一个片段赋值，这样会直接替换掉原列表中指定的那个片段

我的理解是，使用列表切片会生成一个新列表对象，那么赋值给新列表对象，按逻辑原列表不会变化，但是代码实际显示为，原列表发生了变化。

请问老师我是不是哪里理解有误？

**Comment by gaoteng-pro** [comment]
老师在第九课音频有讲，两者确实不一样。切片操作会生成新的列表，而切片的赋值语句会改变原来的列表，也就是说跟前者（仅切片操作）不一样。

**Comment by neolee** [comment]
读取列表的切片 => 新的列表，和原列表无关：
```python
l1 = [0, 1, 2, 3, 4, 5, 6, 7]
l2 = l1[1:4]
print(l1, l2)
l2[0] = 999
print(l1, l2)
```
```shell
[0, 1, 2, 3, 4, 5, 6, 7] [1, 2, 3]
[0, 1, 2, 3, 4, 5, 6, 7] [999, 2, 3]
```

给列表切片赋值 => 直接修改原列表：
```python
l1 = [0, 1, 2, 3, 4, 5, 6, 7]
print(l1)
l1[1:4] = [999, 2, 3]
print(l1)
```
```shell
[0, 1, 2, 3, 4, 5, 6, 7]
[0, 999, 2, 3, 4, 5, 6, 7]
```

**Comment by shujiaojunxiong** [comment]
非常感谢老师细致的回复，我去认真听课（我的习惯是先看教材，然后才会听课）

看来以后要把课程听完了，还是没办法解决问题，再来提问题。

**Comment by neolee** [comment]
其实教材写的也是这个意思，但文字的理解很难100%按照作者想表达的原意，所以课上讲解是重要的补充和印证。毕竟比较不好理解的就那些，基本都会拿来重点讲。
