### ISSUE TITLE
从传输流收到意外的 EOF 或 0 个字节

### ISSUE THREAD

**Issue by MoofersLAon** [neolee/pilot#97]
[]([](![微信图片_20191025211516](https://user-images.githubusercontent.com/49604516/67574433-06daa880-f76d-11e9-8a2c-4b0be9b689c7.png)))

尝试了很多次，都是这样。求老师解惑。

**Comment by neolee** [comment]
网络问题。可能需要换别的网络或者挂代理试试。

不知道你什么操作时出现这个提示，有些可能可以用国内的镜像。

**Comment by MoofersLAon** [comment]
> 网络问题。可能需要换别的网络或者挂代理试试。
> 
> 不知道你什么操作时出现这个提示，有些可能可以用国内的替代。

谢谢老师的用心回复。目前用的香港的网络，我试试其他国家的网络吧。

**Comment by MoofersLAon** [comment]
> 网络问题。可能需要换别的网络或者挂代理试试。
> 
> 不知道你什么操作时出现这个提示，有些可能可以用国内的替代。

跟着老师说的做，切换网络，刚刚已经解决了，再次感谢老师！
