### ISSUE TITLE
调用 fastnumber 这个模块出了问题

### ISSUE THREAD

**Issue by maomaomizi** [neolee/pilot#970]
用之前安装了 fastnumber 但是还是报错，而且我的python是3.7.5 但是不知道为什么在jupyter lab里面总提示python 2.7  /Users/a/Desktop/屏幕快照 2020-01-16 下午11.53.56.png

**Comment by maomaomizi** [comment]
<img width="1427" alt="屏幕快照 2020-01-16 下午11 53 56" src="https://user-images.githubusercontent.com/57162859/72541397-6b655980-38bd-11ea-9556-3ca5efef1530.png">

**Comment by neolee** [comment]
你是 macOS 环境吧？环境中有 Pytjon 2.7，所以需要用 `pip3 install` 来安装 Python 第三方包。

**Comment by maomaomizi** [comment]
太棒了 老师终于过去了 感谢！ 这次学到的是。以后我只要是需要装python第三方包，都试一下pip3 install 。
