### ISSUE TITLE
git restore 命令以及 1s 命令不管用

### ISSUE THREAD

**Issue by xiaoyaogege-233** [neolee/pilot#971]
看老师的视频里， git restore理应把staging area里的文件给拿出来，但是我的restore命令不管用，如下图
![image](https://user-images.githubusercontent.com/59498906/72567362-0c501680-38b6-11ea-847c-1a073b8d28a4.png)
另外，我看老师输入“1s”指令可以显示当前文件夹下的文件，但是我的也不行，如下图
![image](https://user-images.githubusercontent.com/59498906/72567441-30135c80-38b6-11ea-82ca-88c6e3021660.png)
我的git版本如下
![image](https://user-images.githubusercontent.com/59498906/72567492-48837700-38b6-11ea-81df-6b55fcc71c33.png)
请问老师这是什么原因，该如何解决？

**Comment by neolee** [comment]
因为你命令写错了。是 `ls` 不是 `1s`，`git restore` 后面的参数也没写对（git 命令给出的信息里就有正确的命令）。

**Comment by xiaoyaogege-233** [comment]
好的，谢谢老师，昨天太晚了头脑不清醒了
