### ISSUE TITLE
安装 Python 出现两个 WARN 有没有问题？

### ISSUE THREAD

**Issue by de-cheng** [neolee/pilot#973]
PS C:\Users\Administrator> scoop install python37@3.7.4
WARN  Given version (3.7.4) does not match manifest (3.7.6)
WARN  Attempting to generate manifest for 'python37' (3.7.4)
Autoupdating python37
Searching hash for python-3.7.4.exe in https://www.python.org/downloads/release/python-374/
Found: md5:33cc602942a54446a3d6451476394789 using Extract Mode
Searching hash for python-3.7.4-amd64.exe in https://www.python.org/downloads/release/python-374/
Found: md5:a702b4b0ad76debdb3043a583e563400 using Extract Mode
Writing updated python37 manifest
Installing 'python37' (3.7.4) [64bit]
python-3.7.4-amd64.exe (25.4 MB) [==========================================================] 100%
Checking hash of python-3.7.4-amd64.exe ... ok.
Running installer... done.
Linking ~\scoop\apps\python37\current => ~\scoop\apps\python37\3.7.4
Creating shim for 'python'.
Creating shim for 'pythonw'.
Creating shim for 'python3'.
Creating shim for 'python37'.
Creating shim for 'idle'.
Creating shim for 'idle3'.
Creating shim for 'idle37'.
'python37' (3.7.4) was installed successfully!

**Comment by neolee** [comment]
没问题的，那两句话只是告诉你 3.7.4 不是最新版本，Scoop 生成了必要的配置文件来维持这个版本，这个事情的后遗症是你没法升级到更新的 Python，要升级就要自己动手删掉特殊的配置。目前这个完全不是问题。
