### ISSUE TITLE
运行 code . 出错

### ISSUE THREAD

**Issue by de-cheng** [neolee/pilot#974]
```
PS C:\Users\Administrator\Code> code .
code : The term 'code' is not recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify that the path is correct a nd try again.
At line:1 char:1
+ code .
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (code:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by neolee** [comment]
和 #975 类似，你的命令行找不到本该找得到的可执行程序了，这个例子里是 code（Visual Studio Code 的命令行命令），#975 里是 powershell 这个程序。

我估计你的系统里 PATH 环境变量出了些问题，仅凭你提供的信息无法判断，你可以自己从这个角度去找找问题。

**Comment by de-cheng** [comment]
> 和 #975 类似，你的命令行找不到本该找得到的可执行程序了，这个例子里是 code（Visual Studio Code 的命令行命令），#975 里是 powershell 这个程序。
> 
> 我估计你的系统里 PATH 环境变量出了些问题，仅凭你提供的信息无法判断，你可以自己从这个角度去找找问题。

应该怎么排查这个问题呢？

**Comment by de-cheng** [comment]
应该怎么排查PATH环境变量问题呢？

**Comment by neolee** [comment]
自己尝试探索一下吧。

比如 Wiki 里有我们某位同学写的心得，应该能找到吧？
