### ISSUE TITLE
创建用户名+github.io，复制地址打开显示404

### ISSUE THREAD

**Issue by dongjin936** [neolee/pilot#976]
如图：
![QQ浏览器截图20200117213230](https://user-images.githubusercontent.com/56923938/72616192-5a762000-3971-11ea-8d06-91a65352e06a.png)

**Comment by neolee** [comment]
我看你的那个仓库是空的：

https://github.com/dongjin936/dongjin936.github.io

那自然是没文件可以展示，所以出 404 错。

**Comment by dongjin936** [comment]
明白了，谢谢李老师。
