### ISSUE TITLE
只用 VS Code 和 Markdown 写网页内容，若不用github在线仓库，可以在不同电脑上继续写作同一内容不？

### ISSUE THREAD

**Issue by dongjin936** [neolee/pilot#977]
如题：根据李老师支线视频课程，刚学会用visual studio code和markdown在网页上写作内容。我现在的困惑有两个：

1、如果不用github在线仓库上传和下载写作的网页内容，那么我如何做到在不同电脑上继续编辑写作同一内容？比如，用word，我知道可以随时拷走或者云盘备份。markdown写作完，是不是也可以拷走md文件就可以拿到另一台电脑上继续写作？

2、稳定性问题。比如我在一台电脑上用markdown写东西，我会担心会不会出现那种丢失文件或者突然打不开就找不到文件的情况？

请老师和会的同学多指导，谢谢您。

**Comment by neolee** [comment]
Markdown 就是一种文本格式的文件，随便 copy 到哪里都可以，一个 U 盘就能带着到处走，甚至 VS Code 也有 portable 的版本。

不过这样你就没法把你写的东西给别人看了，只是写给自己看了。

**Comment by dongjin936** [comment]
谢谢李老师解答。
