### ISSUE TITLE
S1学的不是很透彻，是继续啃S2，还是反刍S1？

### ISSUE THREAD

**Issue by bai-zhijie** [neolee/pilot#978]
李骏老师，我是一个零基础小白。但S1都能看懂，也全都上手敲了一遍，支线课程也全部看过，感觉难度也不大。但是到最后的大练习以及作业就不知道如何下手了。

在最后的作业里，两种思路只想到简单的那种。但因为理解有偏差，想的太复杂，导致简单的那种思路都没能自己搞定代码，属于不及格。

这种情况下，（1）我是继续硬着头皮学S2，然后时不时的根据需要回头重温S1？（2）还是反刍一遍甚至几遍S1，直到自认为完全没问题，可以不看教材搞定大作业里的所有代码，然后再继续S2？如果选择第二种，我怕节奏太慢，落后太多。如何在提高效率和夯实基础之间取得平衡，我想听听您的意见。

**Comment by neolee** [comment]
如果时间有限，我建议先温习S1直到可以完全自己完成S1课程练习。S2的要求，光看教材似乎还好，其实是提升了不少的，如果S1不扎实会比较难受。

如果时间比较充裕，其实可以两件事一起做，除了上述的，可以同时看S2的教材，听课（尤其是听课）。

**Comment by Milkmocha** [comment]
老师能再提供一下第一阶段学习完成后的问卷链接吗？我好像在哪看过一个链接，但当时以为是和之前的问卷相同，就没有专门打开查看。

**Comment by neolee** [comment]
@Milkmocha Wiki 里有
