### ISSUE TITLE
布尔运算结果怎么老是出错呢？

### ISSUE THREAD

**Issue by xiaofeidong2028** [neolee/pilot#98]
![无标题](https://user-images.githubusercontent.com/56985358/67577008-3b9d2e80-f772-11e9-8375-d7cedea7890f.png)

**Comment by neolee** [comment]
你没有运行第一个 cell 呀（它前面的 [ ] 里面是空的） ，所以相当于 t 和 f 两个变量还没建立，后面的几行代码要用它们自然就出错了。
