### ISSUE TITLE
通过添加 #!/usr/bin/env python3 语句在命令行中直接运行文件的问题

### ISSUE THREAD

**Issue by Ceasar1978** [neolee/pilot#980]
我是 mac 10.15.2 系统，在自学教材和网上看到这样一种在命令行中直接运行文件的方法：
1、在脚本的第一行输入  #!/usr/bin/env python3；
2、命令行中输入 chmod +x 文件名，给文件授权；
3、命令行中输入 ./文件名，回车就可以自动运行文件。
奇怪的是这个方法对有些脚本有效，有些脚本无效，反复测试了很多次都是如此，请教 @neolee 老师和各位同学，问题出在哪里呢？谢谢！

**Comment by Ceasar1978** [comment]
报错信息是：
env: python3\r: No such file or directory

**Comment by Ceasar1978** [comment]
经过测试后，新建 .py 文件，将老文件的内容复制粘贴，上述方法可以生效。

**Comment by neolee** [comment]
你用的什么编辑器？为啥在行末会有 `\r`，macOS 上应该换行符是 `\n`。

方法是没错的，运行出问题的应该就是换行符错了，我怀疑是 Windows 下的文件（Windows 默认的换行符是 `\r\n`）拿到 Mac 下了，在 macOS 下用 Visual Studio Code 编辑保存应该没问题。

**Comment by Ceasar1978** [comment]
谢谢老师，我用的是 VScode，新建脚本文件都能正常运行了，老文件还有问题，不过也没关系了。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Neo Lee"<notifications@github.com&gt;; 
发送时间: 2020年1月19日(星期天) 下午2:57
收件人: "neolee/pilot"<pilot@noreply.github.com&gt;; 
抄送: "云轩"<4655438@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [neolee/pilot] 通过添加 #!/usr/bin/env python3 语句在命令行中直接运行文件的问题 (#980)




你用的什么编辑器？为啥在行末会有 \r，macOS 上应该换行符是 \n。
 
方法是没错的，运行出问题的应该就是换行符错了，我怀疑是 Windows 下的文件（Windows 默认的换行符是 \r\n）拿到 Mac 下了，在 macOS 下用 Visual Studio Code 编辑保存应该没问题。
