### ISSUE TITLE
MySQL 环境配置问题

### ISSUE THREAD

**Issue by wessyde** [neolee/pilot#981]
李骏老师，

请问之前安装过Wampserver，现在是不是必须先卸载Wampserver，再"scoop install mysql57"？

谢谢老师！

**Comment by neolee** [comment]
我没用过你说的那个东西，你可以自己摸索下。总的来说，你有一个可以正常运行的 MySQL 就够了（最好5.x版本）。

**Comment by wessyde** [comment]
Wampserver是php+阿帕奇+MySQL集成环境，试了下直接用现有的MySQL还是出错，我再研究下，谢谢
