### ISSUE TITLE
关于 Scope Re-visit 的个人理解

### ISSUE THREAD

**Issue by shujiaojunxiong** [neolee/pilot#984]
![image](https://user-images.githubusercontent.com/53084501/72862507-5e56c900-3d08-11ea-8efa-4da51bc7a3d4.png)
老师在音频课 第九课里，讲到了关于Scope Re-visit的几个规则：
1. 局部变量和全局变量是在不同的范围起作用
2. 变量其实是对象的引用（名字、标签）
3. 分配对象会创建和打破原来引用-对象之间的**链接**，尽管局部和全局的变量名字一样
4. 对象发生变化，会影响所有指向对象的引用

我这里对第3点有个人一些不同的理解：
局部和全局的变量名字可以一样，但我们关注的重点应该是，是否创建了**新对象**。

用之前老师讲到的Python内置函数id()，可以看到其中的奥妙：
![image](https://user-images.githubusercontent.com/53084501/72863243-daeaa700-3d0a-11ea-9bf8-3da42785c506.png)

可以发现reassign里的局部变量L和全局变量L的id值是不一样的。

老师用的关键词是**链接（links）**，我个人觉得用关键词**对象（object）**.更精准一点，不知道这样理解是否正确，请老师指正。

**Comment by neolee** [comment]
规则2的几句话的意思是：

> “变量”是“值”的名字/引用；给变量赋值的操作（assignment）实际上是建立了变量和值之间的引用关系（reference link），同时也解除了变量之前对其他值的引用关系（如果有的话）。
> 
> 如果一个可变对象（mutable object）的内容发生变化，那么所有指向它的变量都会被影响到。

你用 `id()` 验证的是另外一件事，就是 `reassign()` 里定义的 list 和全局 scope 原先那个 list 不是同一个对象（值）。

**Comment by shujiaojunxiong** [comment]
感谢老师的指正。


---原始邮件---
发件人: &quot;Neo Lee&quot;<notifications@github.com&gt;
发送时间: 2020年1月22日(周三) 中午1:38
收件人: &quot;neolee/pilot&quot;<pilot@noreply.github.com&gt;;
抄送: &quot;shujiaojunxiong&quot;<shujiaojunxiong@foxmail.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题: Re: [neolee/pilot] 关于 Scope Re-visit 的个人理解 (#984)



规则2的几句话的意思是：
  
“变量”是“值”的名字/引用；给变量赋值的操作（assignment）实际上是建立了变量和值之间的引用关系（reference link），同时也解除了变量之前对其他值的引用关系（如果有的话）。
 
如果一个可变对象（mutable object）的内容发生变化，那么所有指向它的变量都会被影响到。
  
你用 id() 验证的是另外一&#x4EF6;事，就是 reassign() 里定义的 list 和全局 scope 原先那个 list 不是同一个对象（值）。
 
&mdash;
