### ISSUE TITLE
git 和 Python 都可以在官网下载

### ISSUE THREAD

**Issue by hong66666** [neolee/pilot#985]
在scoop运行下载git会出现网络问题，除了换代理和换网络，后面还会不停的出现问题，可以为什么不能在官网直接下载git和python呢？

**Comment by neolee** [comment]
你试试呀。环境配置指南是针对所有人的，要保证最大限度的标准化、而且可以支持长久持续的学习，目前的方案是我找到的相对最好的方案，如果你找到更好的方案，欢迎分享。
