### ISSUE TITLE
安装和运行 Jupiter Lab 无法找到 pip/pip3

### ISSUE THREAD

**Issue by lidewen-yue** [neolee/pilot#99]
当运行python -m pip install --upgrade pip代码后反馈的是如下代码：
lidewendeMacBook-Air:~ k$ python -m pip install --upgrade pip3
/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: No module named pip

**Comment by neolee** [comment]
从下面的出错提示可以看出，执行的是系统自带的老版本 python，你需要运行：

```shell
python3 -m pip install -U pip
```
或者：
```shell
pip3 install -U pip
```
