### ISSUE TITLE
无法下载 busybox 工具包

### ISSUE THREAD

**Issue by stsfg** [neolee/pilot#990]
PS C:\Users\stsfg> scoop install busybox
Installing 'busybox' (3329-gcf0fa4d13) [64bit]
busybox-w64-FRP-3329-gcf0fa4d13.exe (594.0 KB) [>                   ]   0%
操作已超时。
URL https://frippery.org/files/busybox/busybox-w64-FRP-3329-gcf0fa4d13.exe#/busybox.exe is not valid

**Comment by neolee** [comment]
网络问题，这个不是必须的，只是提供了一些常用的方便工具，并不影响学习。
