### ISSUE TITLE
如何在 git config 中修改自己的用户名和邮箱地址

### ISSUE THREAD

**Issue by bai-zhijie** [neolee/pilot#992]
老师，我第一次进行git设置时使用的邮箱地址是我第一个GitHub账户注册时用的Gmail邮箱。现在和您交流的是第二个GitHub账户，使用QQ邮箱注册的。

我现在弃用了第一个GitHub账户和Gmail邮箱，为了把自己所学习的内容在git commit和git push时作为POW，我重新运行git config --global user.email your_email@foo.bar把git设置里邮箱地址更改为了QQ邮箱，运行git config --list显示已更改，然后我就修改了一些代码后重新运行git commit和git push，但contributor那里依然是我之前没有头像的GitHub账户。

请问是哪里的问题？
<img width="283" alt="1" src="https://user-images.githubusercontent.com/54059980/73133877-cb9c8e00-4069-11ea-86a3-8968d3ccbbb7.PNG">
<img width="178" alt="2" src="https://user-images.githubusercontent.com/54059980/73133878-cb9c8e00-4069-11ea-9c16-6814faa29f22.PNG">

**Comment by neolee** [comment]
我 clone 了你的 repo，然后 `git log` 看了下：

```
❯ git log
commit d2574f90e8c4b72c190a9f17f35c287016253c4c (HEAD -> master, origin/master, origin/HEAD)
Author: Percy <513698043@qq.com>
Date:   Sun Jan 19 23:49:23 2020 +0800

    new modified

commit 74343ef92a69bf2204f2ca186924ca4527f23bf3
Author: Percy <zhijie312@gmail.com>
Date:   Sun Jan 19 22:53:31 2020 +0800

    S1 modified

commit ea4e5dfd98ae260d961d2a0efba382da79f34b9a
Author: Percy <zhijie312@gmail.com>
Date:   Wed Jan 1 23:03:43 2020 +0800

    first commit

commit 8a4219bf90025fff54253b8073b7eb5c5afcd398
Author: Neo Lee <neo.lee@gmail.com>
Date:   Wed Nov 27 18:58:00 2019 +0800

    Sync Part 2 release
```

旧的几个 commits（来自 `Percy <zhijie312@gmail.com>`）在 GitHub 上被识别为你的老 GitHub 账号，并显示了老的头像；新的那个来自 `Percy <513698043@qq.com>` 的 commit 在 GitHub 上显示为 `Percy` 和“非 GitHub 用户”的缺省头像，说明 `513698043@qq.com` 这个电子邮箱似乎没有识别出来。

你可以在 [GitHub 的这个页面](https://github.com/settings/emails) 配置你当前账号下绑定的电子邮箱，这里配置的所有电子邮箱所提交的 commits 都会被绑定到你当前登录的 GitHub 账号。

**Comment by bai-zhijie** [comment]
问题已解决，谢谢Neo老师！
