### ISSUE TITLE
安装 python37 不成功

### ISSUE THREAD

**Issue by yanyongqi911** [neolee/pilot#993]
PS C:\Users\12425> scoop list
Installed apps:

  7zip 19.00
  busybox 3329-gcf0fa4d13
  dark 3.11.2
  git 2.25.0.windows.1
  lessmsi 1.6.91

PS C:\Users\12425> scoop install python37
Couldn't find manifest for 'python37'.
PS C:\Users\12425>

**Comment by neolee** [comment]
你是不是严格按照配置指南一步步执行的？其中有 `scoop bucket add versions` 和 `scoop update` 两步，都成功后才能安装 `scoop install python37@3.7.4`。

**Comment by yanyongqi911** [comment]
我再重新试一下，请问李老师，若用python默认安装版本3.8.1 是不是也可以？

**Comment by neolee** [comment]
> 请问李老师，若用python默认安装版本3.8.1 是不是也可以？

如果可以，我为啥要写那么麻烦的指南呢？

**Comment by yanyongqi911** [comment]
输入第一行代码就提示有错误了

PS C:\Users\12425> scoop bucket add versions
Checking repo... 'https://github.com/ScoopInstaller/Versions' doesn't look like a valid git repository

Error given:
fatal: unable to access 'https://github.com/ScoopInstaller/Versions/': Failed to connect to github.com port 443: Timed out

**Comment by yanyongqi911** [comment]
谢谢 李老师，已经搞定了。 原因是没有按照具体步骤一步一步操作的原因。

**Comment by sanweiliu** [comment]
PS C:\Users\liusw> scoop install python37@3.7.4
WARN  Given version (3.7.4) does not match manifest ()
WARN  Attempting to generate manifest for 'python37' (3.7.4)
'python37' does not have autoupdate capability
couldn't find manifest for 'python37@3.7.4'

**Comment by sanweiliu** [comment]
每一步报错 都需要修正，不然结果会有偏差。谢谢李老师。
