### ISSUE TITLE
运行 scoop checkup 排错出现的问题 是不是需要解决所有问题才能进行下一步

### ISSUE THREAD

**Issue by stsfg** [neolee/pilot#994]
PS C:\Users\stsfg> scoop checkup
WARN  Windows Defender may slow down or disrupt installs with realtime scanning.
  Consider running:
    sudo Add-MpPreference -ExclusionPath 'C:\Users\stsfg\scoop'
  (Requires 'sudo' command. Run 'scoop install sudo' if you don't have it.)
WARN  Windows Defender may slow down or disrupt installs with realtime scanning.
  Consider running:
    sudo Add-MpPreference -ExclusionPath 'C:\ProgramData\scoop'
  (Requires 'sudo' command. Run 'scoop install sudo' if you don't have it.)
WARN  LongPaths support is not enabled.
You can enable it with running:
    Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1
ERROR 'Inno Setup Unpacker' is not installed! It's required for unpacking InnoSetup files. Please run 'scoop install innounp'.
ERROR 'dark' is not installed! It's required for unpacking installers created with the WiX Toolset. Please run 'scoop install dark' or 'scoop install wixtoolset'.
WARN  Found 5 potential problems.

**Comment by neolee** [comment]
最好都解决。

**Comment by stsfg** [comment]
按提示操作的解决方案好像都不可行
PS C:\Users\stsfg> Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1
Set-ItemProperty : 不允许所请求的注册表访问权。
所在位置 行:1 字符: 1
+ Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem'  ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (HKEY_LOCAL_MACH...trol\File
   System:String) [Set-ItemProperty], SecurityException
    + FullyQualifiedErrorId : System.Security.SecurityException,Microsoft.Po
   werShell.Commands.SetItemPropertyCommand

**Comment by neolee** [comment]
打开一个 Admin 权限的 PowerShell 试试。

这个问题多次出现，可以查询下老的 issues。

**Comment by stsfg** [comment]
Admin权限解决了其中一个问题
PS C:\Users\stsfg> Set-ItemProperty 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1
PS C:\Users\stsfg> scoop install innounp dark
'dark' install failed previously. Please uninstall it and try again.
PS C:\Users\stsfg> scoop checkup
WARN  Windows Defender may slow down or disrupt installs with realtime scanning.
  Consider running:
    sudo Add-MpPreference -ExclusionPath 'C:\Users\stsfg\scoop'
  (Requires 'sudo' command. Run 'scoop install sudo' if you don't have it.)
WARN  Windows Defender may slow down or disrupt installs with realtime scanning.
  Consider running:
    sudo Add-MpPreference -ExclusionPath 'C:\ProgramData\scoop'
  (Requires 'sudo' command. Run 'scoop install sudo' if you don't have it.)
ERROR 'dark' is not installed! It's required for unpacking installers created with the WiX Toolset. Please run 'scoop install dark' or 'scoop install wixtoolset'.
WARN  Found 3 potential problems.
剩下的有解决的必要吗?

**Comment by neolee** [comment]
1. 不要重复问已经回答过的问题，前面已经说了，最好都解决。

2. 我在课上反复说过，学编程的关键是打掉恐惧感，和计算机做朋友；做朋友的标准就是，能够和计算机对话，明白自己在做啥，也明白计算机告诉你啥，进而越来越懂怎么和计算机打交道。这比学几门编程语言都重要。

具体来说，你运行 `scoop install innounp dark` 时计算机说：`'dark' install failed previously. Please uninstall it and try again.`，所以你应该：

```powershell
scoop uninstall dark
scoop install dark
```

直到安装 `dark` 这个包成功，这就解决了一个问题。

另外两个问题是说系统的防病毒软件 Windows Defender 有可能导致 Scoop 出问题或者变得很慢，建议把 Scoop 操作的两个目录加到 Windows Defender 的排除列表，照它说的做就好了。

**Comment by stsfg** [comment]
PS C:\Users\stsfg> scoop install innounp dark
WARN  'innounp' (0.49) is already installed. Skipping.
Installing 'dark' (3.11.2) [64bit]
dark-3.11.2.zip (3.5 MB) [>                                         ]   1%
操作已超时。
URL https://raw.githubusercontent.com/ScoopInstaller/Binary/master/dark/dark-3.11.2.zip is not valid
这个是属于网络问题吗  是不是需要换时间安装

Scoop操作的两个目录加到Windows Defender的排除列表  除了把Scoop这个文件夹加到排除列表还有别的吗

**Comment by neolee** [comment]
如果你已经在一个 Admin 权限的 PowerShell 窗口里，有可能不需要 sudo 命令（这个命令是类 Unix 环境下临时使用管理员权限的一个命令），你可以直接试试：

```powershell
Add-MpPreference -ExclusionPath 'C:\Users\stsfg\scoop'
Add-MpPreference -ExclusionPath 'C:\ProgramData\scoop'
```

如果不行的话，那就先用 Scoop 装一下 sudo 命令（前面说了这是个 Unix 体系下的命令，Windows 本身并没有这个命令）：

```powershell
scoop install sudo
```
然后再：
```powershell
sudo Add-MpPreference -ExclusionPath 'C:\Users\stsfg\scoop'
sudo Add-MpPreference -ExclusionPath 'C:\ProgramData\scoop'
```

看你最新的回复，你似乎已经安装好了 sudo，为啥你还要执行 `scoop update sudo` 这个命令呢？这个命令的含义是“更新 sudo 到最新版本”。所以我前面说，一定要把计算机当朋友，把对计算机的操作看做和朋友聊天，搞懂你自己说的每一句话（你输入的命令）和计算机的回复（计算机输出给你的信息）。

**Comment by stsfg** [comment]
已解决 谢谢
