### ISSUE TITLE
code . 问题

### ISSUE THREAD

**Issue by stsfg** [neolee/pilot#995]
PS C:\Users\stsfg\code> code .
code : 无法将“code”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检
查名称的拼写，如果包括路径，请确保路径正确，然后再试一次。
所在位置 行:1 字符: 1
+ code .
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (code:String) [], CommandNotFo
   undException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by neolee** [comment]
Visual Studio Code 的命令行命令 `code` 没配置好，你有没有完成 Visual Studio Code 的下载和安装？注意一定要装 Stable 版本，而不是 Insider 版本。

**Comment by stsfg** [comment]
下载的是稳定版 并且已经安装打开

**Comment by neolee** [comment]
重启系统试试，如果还不行，查看一下系统的 PATH 环境变量。
