### ISSUE TITLE
Win10 无法启动 MySQL Workbench 8.0 CE

### ISSUE THREAD

**Issue by bai-zhijie** [neolee/pilot#996]
老师，前面 MySQL的服务安装和运行均无误，但到了安装完MySQL Workbench 8.0 CE这一步后，双击无法打开该程序，完全没反应的那种，任何提示框都没有，就像是在桌面空白处双击了鼠标左键那种没反应。即便是用管理员权限依然不行。但其他程序均可正常打开。

在网上搜了下其他人遇到的问题，但年份都比较久远，答案不具备参考意义，而且试过后也无效。

请问是哪里的问题？

**Comment by neolee** [comment]
你在命令行里运行 `mysql` 是没问题，可以连到本地的 MySQL 服务的对吧？

无法启动 Workbench 有点少见，信息太少很难判断，会不会和防病毒软件之类的有关？

**Comment by bai-zhijie** [comment]
是的，按照教材里边的内容一直都可以操作下去，直到下载完Workbench，安装完毕后双击启动就无法启动了，无任何反应。而且关掉防病毒软件，卸载重装，系统重启都试了，都不行。而且我的笔记本是2019年买的小米的新本，配置都可以。issue里没人提这个问题，难道就我一个遇到了？

**Comment by bai-zhijie** [comment]
老师，问题已经解决了。抱着试试看的心态，我卸载了最新版的Workbench 8.0.18，安装了上一个版本8.0.17，结果就打开了。然后按照向导成功导入fifa19.CSV。
<img width="481" alt="3" src="https://user-images.githubusercontent.com/54059980/73260479-f2db9280-4204-11ea-814b-de4c2738ede5.PNG">

**Comment by neolee** [comment]
Emmm, 我用的是 8.0.17，可能是 8.0.18 有啥问题，我回头试试。

**Comment by neolee** [comment]
我试了试最新的 8.0.19，没有问题。你可以试试。

**Comment by bai-zhijie** [comment]
抱歉老师，我有问题打不开的是8.0.19，这个才是最新版，我昨天说错了。8.0.18和8.0.17都能正常安装并打开，所以我现在装了8.0.18。

**Comment by neolee** [comment]
噢噢，那就不知道了，我这边好像都没问题……

**Comment by ysy950803** [comment]
我也有这个问题，用前一个版本8.0.18就能打开了，我的Windows版本是1909。估计是Workbench的bug。

**Comment by neolee** [comment]
@ysy950803 不太确定，我 Windows 也是最新的 1909，但是我用 Workbench 的几个版本都没问题。

操作系统太庞大复杂之后会有些难以简单排查的细微环境差异，这类问题一般能用就行，不值得深究。

**Comment by drizzleing** [comment]
这个问题我也遇到了，操作系统也是win10，安装8.0.19后运行一点反应都没有，8.0.18就没问题

**Comment by L-ios** [comment]
搜索到这里，贴一下解决方案：win10缺少库的：https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

**Comment by D68321** [comment]
![图片](https://user-images.githubusercontent.com/61172012/76388761-d5254f80-63a4-11ea-9673-e59266a37861.png)
我也遇到了workbencd 8.0.19 打不开的情况
现在也按各位同学的办法试一试降级看能否可以用

**Comment by sherlockwhite** [comment]
同8.0.19打不开

**Comment by longhulv** [comment]
我也是打不开。。
