### ISSUE TITLE
安装 pyzmail 模块报错问题

### ISSUE THREAD

**Issue by Ceasar1978** [neolee/pilot#997]
在安装 pyzmail 时，运行 pip3 install pyzmail 或者 sudo -H pip3 install pyzmail 后，都是下面的报错信息，其中 ERROR: Command errored out with exit status 1:及以下部分是红字，我的操作系统是 mac 10.15，Python 版本 3.7.5，编辑器是 VScode。请问 @neolee 老师和其他战友，应该如何解决？

WARNING: The directory '/Users/mac/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
WARNING: The directory '/Users/mac/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting pyzmail
  Downloading https://files.pythonhosted.org/packages/23/9a/c8709821fa15cec44f825fba884284b261a06d8a0033a16f4c35470eb26a/pyzmail-1.0.3.tar.gz (57kB)
     |████████████████████████████████| 61kB 228kB/s 
Collecting distribute
  Downloading https://files.pythonhosted.org/packages/5f/ad/1fde06877a8d7d5c9b60eff7de2d452f639916ae1d48f0b8f97bf97e570a/distribute-0.7.3.zip (145kB)
     |████████████████████████████████| 153kB 192kB/s 
    ERROR: Command errored out with exit status 1:
     command: /usr/local/opt/python/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/y5/8r00fy8n3bz2j__jyx9479xh0000gn/T/pip-install-t7c5qcr5/distribute/setup.py'"'"'; __file__='"'"'/private/var/folders/y5/8r00fy8n3bz2j__jyx9479xh0000gn/T/pip-install-t7c5qcr5/distribute/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/y5/8r00fy8n3bz2j__jyx9479xh0000gn/T/pip-install-t7c5qcr5/distribute/pip-egg-info
         cwd: /private/var/folders/y5/8r00fy8n3bz2j__jyx9479xh0000gn/T/pip-install-t7c5qcr5/distribute/
    Complete output (15 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/y5/8r00fy8n3bz2j__jyx9479xh0000gn/T/pip-install-t7c5qcr5/distribute/setuptools/__init__.py", line 2, in <module>
        from setuptools.extension import Extension, Library
      File "/private/var/folders/y5/8r00fy8n3bz2j__jyx9479xh0000gn/T/pip-install-t7c5qcr5/distribute/setuptools/extension.py", line 5, in <module>
        from setuptools.dist import _get_unpatched
      File "/private/var/folders/y5/8r00fy8n3bz2j__jyx9479xh0000gn/T/pip-install-t7c5qcr5/distribute/setuptools/dist.py", line 7, in <module>
        from setuptools.command.install import install
      File "/private/var/folders/y5/8r00fy8n3bz2j__jyx9479xh0000gn/T/pip-install-t7c5qcr5/distribute/setuptools/command/__init__.py", line 8, in <module>
        from setuptools.command import install_scripts
      File "/private/var/folders/y5/8r00fy8n3bz2j__jyx9479xh0000gn/T/pip-install-t7c5qcr5/distribute/setuptools/command/install_scripts.py", line 3, in <module>
        from pkg_resources import Distribution, PathMetadata, ensure_directory
      File "/private/var/folders/y5/8r00fy8n3bz2j__jyx9479xh0000gn/T/pip-install-t7c5qcr5/distribute/pkg_resources.py", line 1518, in <module>
        register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
    AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by Ceasar1978** [comment]
网上搜索后用 pip3 install pyzmail36 命令成功安装。

**Comment by Ceasar1978** [comment]
不过看到网上很多人在安装其他模块时也遇到类似问题，不知道究竟是什么原因。

**Comment by neolee** [comment]
有的 Mac 环境下系统的 Python 2.7 和对应的 pip 占用了 python 和 pip 这两个命令，我们用 Homebrew 安装的 Python 3.x 需要使用 python3 和 pip3 来使用，你碰到的就是这种情况。

另外要注意，如果你是一个不太熟悉命令行的用户，千万千万不要使用 sudo 命令（除非你完全清楚在做什么），sudo 命令临时开放管理员权限给你，让你可以读写几乎任何系统文件，很容易造成不易恢复的状况，切记。

**Comment by Ceasar1978** [comment]
我用的安装命令就是 pip3 啊。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Neo Lee"<notifications@github.com&gt;; 
发送时间: 2020年1月28日(星期二) 下午5:07
收件人: "neolee/pilot"<pilot@noreply.github.com&gt;; 
抄送: "云轩"<4655438@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [neolee/pilot] 安装 pyzmail 模块报错问题。 (#997)




有的 Mac 环境下系统的 Python 2.7 和对应的 pip 占用了 python 和 pip 这两个命令，我们用 Homebrew 安装的 Python 3.x 需要使用 python3 和 pip3 来使用，你碰到的就是这种情况。
 
另外要注意，如果你是一个不太熟悉命令行的用户，千万千万不要使用 sudo 命令（除非你完全清楚在做什么），sudo 命令临时开放管理员权限给你，让你可以读写几乎任何系统文件，很容易造成不易恢复的状况，切记。

**Comment by neolee** [comment]
你的环境有些奇怪，你的 Python 是用 Homebrew 装的么？

**Comment by Ceasar1978** [comment]
是按您在 Github 上给的教程一步步装的。具体用什么软件装的不太记得了，好像&nbsp;Homebrew 出了点问题。有没有办法能卸载清空，我从头重置一次？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Neo Lee"<notifications@github.com&gt;; 
发送时间: 2020年1月28日(星期二) 晚上10:21
收件人: "neolee/pilot"<pilot@noreply.github.com&gt;; 
抄送: "云轩"<4655438@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [neolee/pilot] 安装 pyzmail 模块报错问题。 (#997)




你的环境有些奇怪，你的 Python 是用 Homebrew 装的么？

**Comment by neolee** [comment]
Emmm，我发现我自己晕了，和 Python 环境无关，是库的问题。

我们教材里应该没有用过 pyzmail 这个库，这个库已经停止维护很多年，不支持新的 Python 版本，而 pyzmail36 是有人 fork 了原来的 pyzmail 而支持 Python 3.6+ 的一个库，但这个库也一年多没维护了，总的来说我不太推荐这类非常不活跃的库。

目前 Python 自带的 smtplib 和 email 库就够用。

**Comment by Ceasar1978** [comment]
好的，谢谢老师！这个库是我在《自学是门手艺》中推荐的一本教材里看到的，作者的观点是这个库比&nbsp;smtplib 更好用。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Neo Lee"<notifications@github.com&gt;; 
发送时间: 2020年1月29日(星期三) 下午2:34
收件人: "neolee/pilot"<pilot@noreply.github.com&gt;; 
抄送: "云轩"<4655438@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [neolee/pilot] 安装 pyzmail 模块报错问题。 (#997)




Emmm，我发现我自己晕了，和 Python 环境无关，是库的问题。
 
我们教材里应该没有用过 pyzmail 这个库，这个库已经停止维护很多年，不支持新的 Python 版本，而 pyzmail36 是有人 fork 了原来的 pyzmail 而支持 Python 3.6+ 的一个库，但这个库也一年多没维护了，总的来说我不太推荐这类非常不活跃的库。
 
目前 Python 自带的 smtplib 和 email 库就够用。
