### ISSUE TITLE
提个建议

### ISSUE THREAD

**Issue by stsfg** [neolee/pilot#999]
我89年的，不懂英语，没接触过编程，按部就班操作还成，在操作过程中遇到问题通过提问、网上查翻译、百度解决。相信不同的人会遇到不同的问题，这个东西能不能提供像电子书一样的备注功能？哪个步骤遇到问题了，解决了。学习者可以把解决方案在这个地方上传一下，以供其它人参考

**Comment by eiyen** [comment]
就我们的编程课而言，问题的解决都是有套路的，无论多少岁、水平如何：
1. 所有在 issues 中的提问及其解决方式都会保留下来，也就成了你所说的“电子书”。
2. 想要使用这本“电子书”，只需要按照下图先搜索你问题的关键词（字数不要多，几个字就好了），再选择 Closed, 把每个问题都看一遍，一般就能找到。
![image](https://user-images.githubusercontent.com/52303623/73240671-9ebbb880-41da-11ea-930f-83ceed419812.png)
3. 如果依旧没有找到答案，就新建 issue 提出一个**好**问题。

做好以上几点，在编程课中的问题一般都可以得到解决。

我在看了你前几个 issue 后，觉得问题无法解决的原因在于没有提出一个好问题。好问题是有[特征](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md#%E5%9C%A8%E6%8F%90%E9%97%AE%E4%B9%8B%E5%89%8D)的，其核心是用你查询到的资料和对问题的思考，帮助回答者减轻思考的负担。

以你提问的 #994 为例，直接将报错的结果当作问题就不是一个好问题，因为其中没有体现出你对问题的思考。好的做法是将报错的英文部分复制到[翻译网页](http://fanyi.youdao.com/)中，根据翻译结果以及之前的操作，思考报错想要表达的问题是什么，如果知道该怎么做了就动手尝试，还不清楚就将问题的关键字提炼出来在 issues 中搜索，如果依旧得不到答案就新建 issue 提问，将你认为报错想要表达的问题作为标题，将之前的尝试都写进去，顺便粘贴你的报错。

其实在目前的入门阶段，几乎所有 issues 中提出的问题老师都有能力解决，但并非每个问题都值得被解决，所以努力让自己的问题成为一个值得被解决的问题吧。加油~

**Comment by neolee** [comment]
上面 @eiyen 同学说的我很赞同。

另外对 @stsfg 同学说的注释，我觉得你完全可以直接在学习用书上做笔记。我们的教材和学习用书都是 Jupyter Notebook 格式的文档，用 Jupyter Lab 打开之后可以随意编辑（尤其是学习用书），拟采用一种独特的格式就可以了，比如写成下面这样：

> **心得**：上面这段一开始没搞懂，后来……

如果你按照我们的学习指南 fork 和 clone 了你自己独有的学习用书，你做了上面描述的修改之后可以 push 到 GitHub 上，进而还可以给主仓库发 Pull Request；如果对这套流程不熟悉可以学习；如果暂时没时间学习这个，那么如 @eiyen 同学所说，在这个 Issues 里提问和分享你的心得是最简单的办法。
